[IMP] new zerobug version

diff --git a/zerobug/zerobug b/zerobug/zerobug
--- a/zerobug/zerobug
+++ b/zerobug/zerobug
@@ -1,6 +1,6 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
-# Regression tests on zerobug
+# Zerobug
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
@@ -22,31 +22,7 @@ Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.2.5
-
-
-Z0BUG_setup() {
-    # Just for regression tests
-    coveragerc_file="$RUNDIR/.coveragerc"
-    coveragerc_bak="$RUNDIR/coveragerc.bak"
-    if [ ! -f "$coveragerc_bak" ]; then
-      if [ -f "$coveragerc_file" ]; then
-         mv -f $coveragerc_file $coveragerc_bak
-      fi
-    fi
-    if [ -f "$coveragerc_file" ]; then
-      rm -f $coveragerc_file
-    fi
-}
-
-Z0BUG_teardown() {
-    if [ -f "$coveragerc_file" ]; then
-      rm -f $coveragerc_file
-    fi
-    if [ -f "$coveragerc_bak" ]; then
-      mv -f $coveragerc_bak $coveragerc_file
-    fi
-}
+__version__=0.2.6.1
 
 
 Z0BUG_init
@@ -54,6 +30,14 @@ parseoptest -l$TESTDIR/test_zerobug.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
+fi
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
 UT1_LIST=
 UT_LIST=
