[FIX] Various fixes: see packages docs

diff --git a/python_plus/vem b/python_plus/vem
--- a/python_plus/vem
+++ b/python_plus/vem
@@ -8,10 +8,11 @@
 # -----------------------------------------------------------------------------
 # PIP features truth table depending on pip version (21.0 + only python3):
 # option                                    |  18- | 18.0 | 19.0 | 20.0 | 21.0
+# --disable-pip-version-check               |  OK  |  OK  |  OK  |  OK  |  OK
+# --no-python-version-warning               |  OK  |  OK  |  OK  |  OK  |  OK
+# --no-warn-conflicts                       |   X  |  OK  |  OK  |  OK  |  OK
 # --use-features=(2020-resolver, fast-deps) |   X  |  OK  |  OK  |  no  |   X
 # --use-features=in-tree-build              |   X  |   X  |   X  |   X  |  OK
-# --no-warn-conflicts                       |   X  |  OK  |  OK  |  OK  |  OK
-# --disable-pip-version-check               |  OK  |  OK  |  OK  |  OK  |  OK
 # -----------------------------------------------------------------------------
 # OK -> Use feature / X -> Feature unavailable / no -> Do use use
 # READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
@@ -35,7 +36,8 @@ if [[ -z "$Z0LIBDIR" ]]; then
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
 
-__version__=1.0.3.3
+__version__=1.0.3.4
+
 declare -A PY3_PKGS
 NEEDING_PKGS="future clodoo configparser os0 z0lib"
 DEV_PKGS="click coveralls codecov flake8 pycodestyle pylint"
@@ -72,15 +74,16 @@ pop_venv() {
       VIRTUAL_ENV=${VENV_STACK[$i]}
       unset VENV_STACK[$i]
     fi
+    [[ $opt_verbose -gt 2 ]] && echo ">>> VIRTUAL_ENV=$VIRTUAL_ENV"
     export VENV_STACK
 }
 
 do_activate() {
   # do_activate(VENV -q)
   local i f VENV_DIR="$1"
-  [[ $opt_verbose -gt 2 ]] && echo ">>> do_activate($@)"
+  [[ $opt_verbose -gt 2 ]] && echo ">>> VIRTUAL_ENV=$VIRTUAL_ENV" && echo ">>> do_activate($@)"
   if [[ -z "$VIRTUAL_ENV" || $VIRTUAL_ENV != $VENV_DIR ]]; then
-    [[ $opt_verbose -ge 3 || ( ! $1 =~ q && $opt_verbose -ne 0 ) ]] && echo "$FLAG source $VENV_DIR/bin/activate"
+    [[ $opt_verbose -ge 3 || ( ! ${2}z =~ q && $opt_verbose -ne 0 ) ]] && echo "$FLAG source $VENV_DIR/bin/activate"
     [[ ! -f $VENV_DIR/bin/activate ]] && echo "Fatal error! bin/activate not found in $(readlink -f $VENV_DIR)" && exit 1
     [[ $opt_verbose -gt 3 ]] && set +x
     . $VENV_DIR/bin/activate
@@ -96,7 +99,7 @@ do_deactivate() {
   [[ $opt_verbose -gt 2 ]] && echo ">>> do_deactivate($@)"
   if [[ -n "$VIRTUAL_ENV" ]]; then
     [[ $opt_verbose -ge 3 || ( ! $1 =~ q && $opt_verbose -ne 0 ) ]] && echo "$FLAG deactivate"
-    [[ "$(type -t $cmd)" == "function" ]] && deactivate
+    [[ "$(type -t deactivate)" == "function" ]] && deactivate
     pop_venv
   fi
 }
@@ -811,7 +814,7 @@ do_venv_mgr() {
   elif [[ "$cmd" == "cp" ]]; then
     do_deactivate "-q"
     if [[ -d $VENV_TGT ]]; then
-      if [ $opt_force -eq 0 ]; then
+      if [[ $opt_force -eq 0 ]]; then
         echo "Destination v.environment $VENV_TGT already exists!!"
         echo "use: venv_mgr cp -f VENV NEW_VENV"
         exit 1
@@ -844,7 +847,7 @@ do_venv_mgr() {
     V=$VENV
   fi
   if [[ ! $cmd =~ (amend|check|test|inspect) ]]; then
-    set_python_exe "$V"
+    set_python_exe "$V/bin"
   fi
   if [[ ! $cmd =~ (test|inspect) ]]; then
     if [ $opt_dry_run -eq 0 -a -L ./lib64 ]; then
@@ -1013,6 +1016,7 @@ do_venv_create() {
   fi
 
   do_activate "$VENV"
+  # [[ -d $VENV/bin ]] && export PATH=$VENV/bin:$PATH
   venv_mgr_check_src_path "$VENV"
   x=$($PIP --version|grep -Eo "python [23]"|grep -Eo [23])
   [[ $x == "2" ]] && run_traced "$PIP install \"pip<21.0\" -Uq" || run_traced "$PIP install pip -Uq"
@@ -1035,10 +1039,9 @@ do_venv_create() {
   pip_install_1
   [[ -n "$opt_oever" ]] && pip_install_2
   [[ -n "$opt_rfile" ]] && pip_install_req
-  # [[ $opt_travis -ne 0 ]] && set_python_exe "$VENV/bin"
+  [[ $opt_travis -ne 0 ]] && set_python_exe "$VENV/bin"
   # do_deactivate
   # [[ -n "$opt_oever" && -d $HOME/$opt_oever ]] && run_traced "ln -s $opt_oepath $(readlink -f ./odoo)"
-  [[ $opt_travis -ne 0 ]] && set_python_exe "$VENV"
   do_venv_mgr_test $VENV
 }
 
@@ -1066,7 +1069,6 @@ do_venv_pip() {
     [[ $opt_verbose -ne 0 ]] && echo "$ PATH=$PATH"
   fi
   V=""
-  # do_activate
   pkg="$(get_actual_pkg $3)"
   [[ $pkg =~ "-e " ]] && pkg=${pkg//-e /--editable=}
   if [[ $cmd == "uninstall" ]]; then
@@ -1153,6 +1155,7 @@ fi
 ACTIONS="help amend cp check create exec info inspect install merge mv python shell rm show uninstall update test"
 REXACT="^(${ACTIONS// /|})\$"
 # In old vem version p1 -> action and p2 > venv
+[[ $opt_verbose -gt 3 ]] && set -x
 action=""
 p2=""
 for x in 3 4 5 6; do
@@ -1180,6 +1183,7 @@ if [[ -z "$p2" && -n "$VIRTUAL_ENV" && -f $VIRTUAL_ENV/bin/activate ]]; then
 elif [[ -z "$p2" && -f ./bin/activate ]]; then
   p2="$(readlink -e ./)"
 fi
+[[ -z "$p2" || ! -f $p2/bin/activate ]] && echo -e "${RED}Missed or invalid virtual environment!${CLR}" && exit 1
 [[ -z "$p8" && -n "$p9" ]] && p8="$p9" && p9=""
 [[ -z "$p7" && -n "$p8" ]] && p7="$p8" && p8=""
 [[ -z "$p6" && -n "$p7" ]] && p6="$p7" && p7=""
@@ -1195,7 +1199,6 @@ fi
 [[ -z $VENV_STACK ]] && declare -A VENV_STACK && export VENV_STACK
 [[ -n "$VIRTUAL_ENV" && -z "$VENV_STACK" ]] && push_venv "$VIRTUAL_ENV"
 [[ $opt_verbose -eq -1 ]] && opt_verbose=1
-[[ $opt_verbose -gt 3 ]] && set -x
 if [[ $action == "create" && -n "$VIRTUAL_ENV" && ${opt_force:-0} -eq 0 ]]; then
   echo "You cannot create a new virtual environment inside $VIRTUAL_ENV"
   exit 1
@@ -1225,7 +1228,7 @@ if [[ $action == "rm" ]]; then
   unset PYTHON PIP
   exit 0
 elif [[ ! $action =~ (help|create) ]]; then
-  do_activate $p2 "-q"
+  do_activate "$p2" "-q"
   venv_mgr_check_src_path $p2
   check_installed_pkgs
   venv_mgr_check_oever $action $p2
