[IMP] Stable release

diff --git a/python_plus/venv_mgr b/python_plus/venv_mgr
--- a/python_plus/venv_mgr
+++ b/python_plus/venv_mgr
@@ -26,7 +26,7 @@ if [ -z "$Z0LIBDIR" ]; then
   exit 2
 fi
 
-__version__=0.1.3.9
+__version__=0.1.4
 DEV_PKGS="coveralls codecov flake8 pycodestyle pylint"
 SUP_PKGS="future python_plus"
 SECURE_PKGS="urllib3[secure] cryptography pyOpenSSL idna certifi asn1crypto pyasn1"
@@ -39,12 +39,13 @@ XPKGS_RE=""
 cd_venv() {
 # cd_venv(VENV -q)
     [ $opt_verbose -gt 2 ] && echo ">>> cd_venv($@)"
-    if [[ ! "$1" == "$PWD" ]]; then
-        [[ "$2" == "-q" ]] || [ $opt_verbose -eq 0 ] || echo "$FLAG pushd $1 >/dev/null"
+    if [[ ! "$1" == "$PWD" || $2 =~ f ]]; then
+        [[ $2 =~ q ]] || [ $opt_verbose -eq 0 ] || echo "$FLAG pushd $1 >/dev/null"
         if [[ -d $1 ]]; then
             pushd $1 >/dev/null
             ((DO_POP++))
         fi
+        [ $opt_verbose -gt 2 ] && echo "$PWD>"
     fi
 }
 
@@ -57,6 +58,7 @@ pop_cd() {
             popd >/dev/null
             ((DO_POP--))
         fi
+        [ $opt_verbose -gt 2 ] && echo "$PWD>DO_POP=$DO_POP"
     fi
 }
 
@@ -65,6 +67,7 @@ do_activate() {
     [ $opt_verbose -gt 2 ] && echo ">>> do_activate($@)"
     if [[ -z "$VIRTUAL_ENV" ]]; then
         [[ "$1" == "-q" ]]  || [ $opt_verbose -eq 0 ] || echo "$FLAG source bin/activate"
+        [[ ! -f bin/activate ]] && echo "Fatal error! bin/activate not found in $PWD" && exit 1
         [ $opt_verbose -gt 3 ] && set +x
         [ $opt_verbose -gt 3 ] && echo "$FLAG source bin/activate"
         . bin/activate
@@ -411,7 +414,6 @@ custom_env() {
 # custom_env(VENV pyver)
     [ $opt_verbose -gt 2 ] && echo ">>> custom_env($@)"
     local VIRTUAL_ENV=$1
-    # cd_venv "$1" "-q"
     sed -i -e 's:VIRTUAL_ENV=.*:VIRTUAL_ENV="\$(readlink -f \$(dirname \$(readlink -f \$BASH_SOURCE))/..)":g' $PWD/bin/activate
     if $(grep -q "^export HOME=" $PWD/bin/activate); then
         sed -i -e 's|^export HOME=.*|export HOME="\$VIRTUAL_ENV"|g' $PWD/bin/activate
@@ -471,7 +473,7 @@ venv_mgr_check_src_path() {
         echo "Invalid virtual env $VENV!!"
         exit 1
     fi
-    cd_venv "$VENV" "-q"
+    cd_venv "$VENV" "-fq"
     # do_activate "-q"
     for f in ./bin/python[23].*; do PYTHON=$(echo $f|grep -Eo "python[2-3]\.[0-9]"); break; done
     [[ -z "$PYTHON"  && -x ./bin/python ]] && PYTHON=$(readlink -e ./bin/python)
@@ -494,13 +496,9 @@ venv_mgr_check_src_path() {
 check_local_pkgs() {
     local f VENV
     VENV="$1"
-    # cd_venv $VENV -q
-    # do_activate -q
     FUTURE=$(pip show future 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
     Z0LIB=$(pip show z0lib 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
     OS0=$(pip show os0 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
-    # do_deactivate -q
-    # pop_cd -q
 }
 
 
@@ -511,7 +509,7 @@ venv_mgr_check_oever() {
         x=$(find -L $p2 -not -path "*/__to_remove/*" -not -path "*/lib/*" -not -path "*/lib64/*"  -not -path "*/tests/res/*" -name release.py)
         if [[ -n "$x" ]]; then
             p=$(dirname $x)
-            cd_venv $p -q
+            cd_venv $p -fq
             x=$(echo -e "import release\nprint(release.version)\n"|python)
             opt_oever="$x"
             pop_cd -q
@@ -536,7 +534,7 @@ do_venv_mgr_test() {
     VENV="$1"
     [ $opt_verbose -gt 0 ] && echo "Validation test ..."
     [ $opt_dry_run -ne 0 ] && return
-    cd_venv $VENV "-q"
+    cd_venv $VENV "-fq"
     if [[ -z "$VIRTUAL_ENV" ]]; then
         do_activate "-q"
         if [ $opt_verbose -gt 0 ]; then
@@ -569,9 +567,9 @@ do_venv_mgr() {
     [[ $cmd =~ (amend|check|reset|test) ]] && VENV_TGT=$VENV
     popt=""
     [ $opt_alone -ne 0 ] && popt="--isolated"
-    [ $PIPVER -gt 18 ] && [[ ! no-warn-conflicts =~ $popt ]] && popt="$popt --no-warn-conflicts"
+    [ $PIPVER -gt 18 ] && [[ -z $popt || ! no-warn-conflicts =~ $popt ]] && popt="$popt --no-warn-conflicts"
     [ $opt_verbose -eq 0 ] && popt="$popt -q"
-    cd_venv $VENV "-q"
+    cd_venv "$VENV" "-fq"
     do_activate "-q"
     [ $opt_verbose -gt 1 -a -n "$opt_oever" ] && echo "list_requirements.py -qs\" \" -BPRT -t bin -b $opt_oever -y $opt_pyver"
     [ $opt_verbose -gt 1 -a -z "$opt_oever" ] && echo "list_requirements.py -qs\" \" -PT -t bin -y $opt_pyver"
@@ -636,7 +634,7 @@ do_venv_mgr() {
         done
     fi
     if [[ ! "$cmd" == "test" ]]; then
-        cd_venv $V
+        cd_venv $V -f
         do_activate
         if [ $opt_dry_run -eq 0  -a -L ./lib64 ]; then
             rm -f ./lib64
@@ -731,7 +729,7 @@ do_venv_create() {
     run_traced "$venvexe $p $VENV"
     sts=$?
     [ $sts -ne 0 ] && return
-    cd_venv $VENV
+    cd_venv $VENV -f
     do_activate
     run_traced "pip install pip -U"
     PIPVER=$(pip --version|grep -Eo [0-9]+|head -n1)
@@ -763,7 +761,7 @@ do_venv_exec() {
 # do_venv_exec VENV cmd
     local d f mime VENV V sitecustom
     VENV="$1"
-    cd_venv $VENV
+    cd_venv $VENV -f
     do_activate
     run_traced "$2 $3 $4 $5 $6 $7 $8 $9"
     do_deactivate
@@ -776,7 +774,7 @@ do_venv_pip() {
     local d f VENV V popt
     local cmd="$2"
     VENV="$1"
-    cd_venv "$VENV"
+    cd_venv "$VENV" "-f"
     do_activate
     pkg="$3"
     popt=""
@@ -872,7 +870,6 @@ FLAG=">"
 if [[ ! $action =~ (help|create) ]]; then
     cd_venv $p2 "-q"
     do_activate "-q"
-    # check_local_pkgs $p2
     [[ -z "$opt_pyver" ]] && venv_mgr_check_src_path $p2
     [[ -n "$opt_pyver" ]] && set_pyver_files
 fi
@@ -883,7 +880,7 @@ venv_mgr_check_oever $action
 if [ $opt_dev -eq 0 ] || [[ -z "$FUTURE" || -z "$Z0LIB" || -z "$OS0" ]]; then
     DEV_PKGS=""
 else
-    cmd="list_requirements.py -t python -BP"
+    cmd="list_requirements.py -qt python -BP"
     [ $opt_dev -ne 0 ] && cmd="$cmd -TR"
     [[ -n "$opt_pyver" ]] && cmd="$cmd -y$opt_pyver"
     [[ -n "$opt_oever" ]] && cmd="$cmd -b$opt_oever"
