[RUN] test nightly

diff --git a/product/tests/all_tests b/product/tests/all_tests
--- a/product/tests/all_tests
+++ b/product/tests/all_tests
@@ -1,4 +1,149 @@
-# for aa in "Ubuntu14" "CentOS7"; do
-#   ../product -L ./product.log -t whatis odoo
-# done
-../product -L ./product.log regression_test
+#! /bin/bash
+# -*- coding: utf-8 -*-
+# Sample of Regression tests
+#
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
+if [ -d $TDIR/tests ]; then
+  TESTDIR=$TDIR/tests
+  RUNDIR=$TDIR
+elif [ -d $TDIR/../tests ]; then
+  TESTDIR=$TDIR
+  RUNDIR=$TDIR/..
+elif [ -d ./tests ]; then
+  TESTDIR=./tests
+  RUNDIR=./
+elif [ -d ../tests ]; then
+  TESTDIR=.
+  RUNDIR=..
+else
+  TESTDIR=$TDIR
+  RUNDIR=$TDIR/..
+fi
+if [ -d $TDIR/_travis ]; then
+  TRAVISDIR=$TDIR
+elif [ -d $TDIR/../_travis ]; then
+  TRAVISDIR=$TDIR/..
+elif [ -d ./_travis ]; then
+  TRAVISDIR=.
+elif [ -d ../_travis ]; then
+  TRAVISDIR=..
+else
+  TRAVISDIR=~/dev/_travis
+fi
+if [ -e $TDIR/z0librc ]; then
+. $TDIR/z0librc
+  Z0LIBDIR=$TDIR
+elif [ -e ./z0librc ]; then
+. ./z0librc
+  Z0LIBDIR=.
+elif [ -e ../z0librc ]; then
+. ../z0librc
+  Z0LIBDIR=..
+elif [ -e ~/z0librc ]; then
+. ~/z0librc
+  Z0LIBDIR=~
+else
+. /etc/z0librc
+  Z0LIBDIR=/etc
+fi
+if [ -e $TDIR/z0testrc ]; then
+. $TDIR/z0testrc
+  Z0TLIBDIR=$TDIR
+elif [ -e ./z0testrc ]; then
+. ./z0testrc
+  Z0TLIBDIR=.
+elif [ -e ../z0testrc ]; then
+. ../z0testrc
+  Z0TLIBDIR=..
+else
+. ~/dev/z0testrc
+  Z0TLIBDIR=~
+fi
+TESTDIR=$(readlink -e $TESTDIR)
+RUNDIR=$(readlink -e $RUNDIR)
+TRAVISDIR=$(readlink -e $TRAVISDIR)
+Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+Z0TLIBDIR=$(readlink -e $Z0TLIBDIR)
+
+
+__version__=0.2.28.7
+
+declare -a ctrs
+export WNoCtr=1
+parseoptest -l$TESTDIR/test_product.log $@
+sts=$?
+if [ $sts -ne 127 ]; then
+  exit $sts
+fi
+opt4childs=$(inherit_opts)
+UT1_LIST=""
+UT_LIST="product_test_01"
+saved_ctr=$ctr
+saved_max_test=$max_test
+saved_opt_verbose=$opt_verbose
+saved_opt_dry_run=$opt_dry_run
+saved_LNEW=$LNEW
+saved_LECHO=$LECHO
+
+ix=0
+sts=0
+if [ -n "$UT1_LIST" ]; then
+  WLOGCMD=echo
+  FLOG=
+fi
+# pass 1: count for # of tests
+max_test=0
+# 1 test is for version id
+exec_tests_4_count "version" "1"
+if [ -n "$UT1_LIST" ]; then
+  exec_tests_4_count "$UT1_LIST"
+fi
+exec_tests_4_count "$UT_LIST"
+if [ ${saved_max_test:-0} -gt 0 ]; then
+  max_test=$saved_max_test
+elif [ ${opt_noctr:-0} -gt 0 ]; then
+  max_test=
+fi
+# pass 2: execute tests
+ctr=$saved_ctr
+opt_verbose=$saved_opt_verbose
+opt_dry_run=$saved_opt_dry_run
+LNEW=$saved_LNEW
+LECHO=$saved_LECHO
+if [ -n "$UT1_LIST" ]; then
+  if [ "$LECHO" == "echo" ]; then
+    WLOGCMD="wecho-1"
+  else
+    WLOGCMD="wecho-0"
+  fi
+  FLOG=
+fi
+if [ ${opt_noctr:-0} -eq 0 -a ${ctr:-0} -gt 0 -a ${saved_max_test:-0} -eq 0 ]; then
+   let max_test="$max_test"+"$ctr"
+fi
+if [ ${opt_dry_run:-0} -eq 0 ]; then
+  ix=0
+  sts=0
+  # 1 test is for version id
+  xtlver=$($RUNDIR/product -V)
+  ci-test "check for product version" "$__version__" "$xtlver"
+  ctr=$saved_ctr
+  # exec_all_tests "version" "2"
+  if [ -n "$UT1_LIST" ]; then
+    # test w/o tracelog
+    exec_all_tests "$UT1_LIST"
+    # Test log file successfully ended; set log file to next tests
+    WLOGCMD=
+    set_tlog_file "$TESTDIR/TEST_MYAPP.log" "" "$LECHO"
+  fi
+  exec_all_tests "$UT_LIST"
+  if [ $sts -eq 0 ]; then
+    echo "Test successfully terminated"
+  else
+    echo "Test failed!"
+  fi
+else
+  echo "$max_test"
+fi
+exit $sts
