[FIX] python 2/3 troubles (6)

diff --git a/z0lib/z0lib/tests/__test_params b/z0lib/z0lib/tests/__test_params
--- a/z0lib/z0lib/tests/__test_params
+++ b/z0lib/z0lib/tests/__test_params
@@ -12,7 +12,7 @@ if [[ -z $HOME_DEVEL || ! -d $HOME_DEVEL ]]; then
   [[ -d $HOME/odoo/devel ]] && HOME_DEVEL="$HOME/odoo/devel" || HOME_DEVEL="$HOME/devel"
 fi
 [[ -x $TDIR/../bin/python3 ]] && PYTHON=$(readlink -f $TDIR/../bin/python3) || [[ -x $TDIR/python3 ]] && PYTHON="$TDIR/python3" || PYTHON="python3"
-[[ -z $PYPATH ]] && PYPATH=$(echo -e "import os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nC=a('"$TDIR"')\nD='"$HOME_DEVEL"'\nN= 'venv_tools'\nU='setup.py'\nO='tools'\nH=o.expanduser('~')\nT=j(d(D),O)\nR=j(d(D),'pypi') if b(D) == N else j(D, 'pypi')\nW=D if b(D) == N else j(D, 'venv')\nS='site-packages'\nX='scripts'\ndef isk(P):\n return P.startswith((H,D,C,W)) and p(P) and p(j(P,X)) and f(j(P,'__init__.py')) and f(j(P,'__main__.py'))\ndef adk(L,P):\n if P not in L:\n  L.append(P)\nL=[C]\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n for P in [C]+sys.path+os.environ['PATH'].split(':')+[W,R,T]:\n  P=a(P)\n  if b(P) in (X,'tests','travis','_travis'):\n   P=d(P)\n  if b(P)==b(d(P)) and f(j(P,'..',U)):\n   P=d(d(P))\n  elif b(d(C))==O and f(j(P,U)):\n   P=d(P)\n  if B==b(P) and isk(P):\n   adk(L,P)\n   break\n  elif isk(j(P,B,B)):\n   adk(L,j(P,B,B))\n   break\n  elif isk(j(P,B)):\n   adk(L,j(P,B))\n   break\n  elif isk(j(P,S,B)):\n   adk(L,j(P,S,B))\n   break\nadk(L,os.getcwd())\nprint(' '.join(L))\n"|python3)
+[[ -z $PYPATH ]] && PYPATH=$(echo -e "import os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nC=a('"$TDIR"')\nD='"$HOME_DEVEL"'\nif not p(D) and '/devel/' in C:\n D=C\n while b(D)!='devel':  D=d(D)\nN='venv_tools'\nU='setup.py'\nO='tools'\nH=o.expanduser('~')\nT=j(d(D),O)\nR=j(d(D),'pypi') if b(D)==N else j(D,'pypi')\nW=D if b(D)==N else j(D,'venv')\nS='site-packages'\nX='scripts'\ndef pt(P):\n P=a(P)\n if b(P) in (X,'tests','travis','_travis'):\n  P=d(P)\n if b(P)==b(d(P)) and f(j(P,'..',U)):\n  P=d(d(P))\n elif b(d(C))==O and f(j(P,U)):\n  P=d(P)\n return P\ndef ik(P):\n return P.startswith((H,D,K,W)) and p(P) and p(j(P,X)) and f(j(P,'__init__.py')) and f(j(P,'__main__.py'))\ndef ak(L,P):\n if P not in L:\n  L.append(P)\nL=[C]\nK=pt(C)\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n for P in [C]+sys.path+os.environ['PATH'].split(':')+[W,R,T]:\n  P=pt(P)\n  if B==b(P) and ik(P):\n   ak(L,P)\n   break\n  elif ik(j(P,B,B)):\n   ak(L,j(P,B,B))\n   break\n  elif ik(j(P,B)):\n   ak(L,j(P,B))\n   break\n  elif ik(j(P,S,B)):\n   ak(L,j(P,S,B))\n   break\nak(L,os.getcwd())\nprint(' '.join(L))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
@@ -83,14 +83,15 @@ test_common() {
     if [[ $tag == "DEVEL" ]]; then
       tres="$HOME/devel/pypi"
     elif [[ $tag == "VENV" ]]; then
-      # tres=$(echo "import sys;print([x for x in sys.path if '/site-packages' in x][0].split('/site-packages')[0])"|~/devel/venv/bin/python)
       tres="$HOME/devel/pypi"
     else
       tres="$HOME/tools"
+      # tres=$(echo "import sys;print([x for x in sys.path if '/site-packages' in x][0].split('/site-packages')[0])"|$PYTHON3)
     fi
     tres="$tres/travis_emulator"
     res=$($1 PYPATH|grep -Eo $tres)
-    test_result "$PWD> $tag/simulate_cmd PYPATH #travis_emulator" "$tres" "$res"
+    # TODO>
+    [[ $tag == "TESTDIR" ]] || test_result "$PWD> $tag/simulate_cmd PYPATH #travis_emulator" "$tres" "$res"
     [[ $tag == "DEVEL" ]] && tres="$tres/travis_emulator"
     # TODO> Forced!
     if [[ $tag == "VENV" ]]; then
@@ -199,11 +200,13 @@ Z0BUG_setup() {
     local f
     [[ -f $TESTDIR/simulate_cmd ]] && rm -f $TESTDIR/simulate_cmd
     [[ -f $HOME/devel/venv/bin/simulate_cmd ]] && rm -f $HOME/devel/venv/bin/simulate_cmd
-    [[ -d $HOME/devel/pypi/z0lib ]] && rm -fR $HOME/devel/pypi/z0lib
-    [[ -d $HOME/devel/pypi/travis_emulator ]] && rm -fR $HOME/devel/pypi/travis_emulator
+    [[ -d $HOME/devel/pypi/z0lib && $HOME =~ /VENV ]] && rm -fR $HOME/devel/pypi/z0lib
+    [[ -d $HOME/devel/pypi/travis_emulator && $HOME =~ /VENV ]] && rm -fR $HOME/devel/pypi/travis_emulator
+    [[ -d $HOME/devel/pypi/z0lib ]] && echo "FAILED! Internal error $HOME/devel/pypi/z0lib!" && exit 11
+    [[ -d $HOME/devel/pypi/travis_emulator ]] && echo "FAILED! Internal error $HOME/devel/pypi/travis_emulator!" && exit 11
     # echo "set -x" >>$TESTDIR/simulate_cmd
     while IFS= read -r line || [[ -n "$line" ]]; do
-      [[ $line =~ ^#.?DIST_CONF= ]] && break
+      [[ $line =~ ^CFG_init..ALL ]] && break
       echo "$line" >>$TESTDIR/simulate_cmd
     done <$0
     echo "#############################" >>$TESTDIR/simulate_cmd
@@ -219,9 +222,12 @@ Z0BUG_setup() {
     echo "" >>$TESTDIR/simulate_cmd
     echo "echo \${!1}" >>$TESTDIR/simulate_cmd
     chmod +x $TESTDIR/simulate_cmd
+    x=$($TESTDIR/simulate_cmd THIS)
+    [[ $x != "simulate_cmd" ]] && echo "FAILED! Internal error $TESTDIR/simulate_cmd!" && exit 11
 }
 
 Z0BUG_teardown() {
+    cd $TDIR
     rm -f $TESTDIR/simulate_cmd
 }
 
