[IMP] zerobug stable version

diff --git a/zerobug/build/lib.linux-x86_64-2.7/zerobug/_travis/travis_run_pypi_tests b/zerobug/build/lib.linux-x86_64-2.7/zerobug/_travis/travis_run_pypi_tests
--- a/zerobug/build/lib.linux-x86_64-2.7/zerobug/_travis/travis_run_pypi_tests
+++ b/zerobug/build/lib.linux-x86_64-2.7/zerobug/_travis/travis_run_pypi_tests
@@ -11,22 +11,23 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
+# Based on template 1.0.3.3
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
-[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
-PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
 if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found!"
+  echo "Library file z0librc not found in <$PYPATH>!"
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
@@ -38,7 +39,18 @@ fi
 . $TRAVISLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TRAVISLIBDIR=$TRAVISLIBDIR"
 
-__version__=1.0.4
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+CLR="\e[0m"
+
+__version__=1.0.5
 
 
 travis_test_bash() {
@@ -119,10 +131,10 @@ please_test_pylint() {
     echo "======== Testing test_pylint ========"
     local s sts
     sts=0
+    run_traced "export PYLINT_CONFIG_DIR=$($READLINK -f $TDIR/../_travis/cfg)"
     if [ ${opt_dry_run:-0} -eq 0 ]; then
       TRAVIS_BUILD_DIR=$PKGPATH
       MODULES_TO_TEST=$TRAVIS_BUILD_DIR
-      PYLINT_CONFIG_DIR="$FLAKE8_CONFIG_DIR"
       if [ "$PRJNAME" == "Odoo" ]; then
         pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg
       else
@@ -146,7 +158,7 @@ run_regression_test() {
         [[ $TRAVIS_DEBUG_MODE =~ [89] ]] && opts="${opts}n"
         OPTS=$(inherits_travis_opts "$opts" "T")
         run_traced "COVERAGE_PROCESS_START=$($READLINK -f .coveragerc)"
-        COVERAGE_PROCESS_START=$($READLINK -f .coveragerc)
+        # COVERAGE_PROCESS_START=$($READLINK -f .coveragerc)
         if [ ! -f $COVERAGE_PROCESS_START ]; then
             cat << EOF > $COVERAGE_PROCESS_START
 # Config file .coveragerc 2019-08-22
@@ -196,30 +208,30 @@ EOF
         fi
         if [ -f ./tests/all_tests.py ]; then
             if [ ${opt_dprj:-0} -gt 0 ]; then
-                run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/all_tests.py $OPTS"
+                run_traced "cd $PRJPATH; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/all_tests.py $OPTS"
             else
-                run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START all_tests.py $OPTS"
+                run_traced "cd $PRJPATH/tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START all_tests.py $OPTS"
             fi
             s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
         elif [[ -f ./tests/all_tests && ${opt_pyth:-0} -eq 0 ]]; then
             if [ ${opt_dprj:-0} -gt 0 ]; then
-                run_traced "./tests/all_tests $OPTS"
+                run_traced "$PRJPATH/tests/all_tests $OPTS"
             else
-                run_traced "cd ./tests; ./all_tests $OPTS"
+                run_traced "cd $PRJPATH/tests; ./all_tests $OPTS"
             fi
             s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
         elif [ -f ./tests/test_$PRJNAME.py ]; then
             if [ ${opt_dprj:-0} -gt 0 ]; then
-                run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/test_$PRJNAME.py $OPTS"
+                run_traced "cd $PRJPATH; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/test_$PRJNAME.py $OPTS"
             else
-                run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START test_$PRJNAME.py $OPTS"
+                run_traced "cd $PRJPATH/tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START test_$PRJNAME.py $OPTS"
             fi
             s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
         else
             if [ ${opt_dprj:-0} -gt 0 ]; then
-                run_traced "DEV_ENVIRONMENT=$PRJNAME $(which zerobug) $OPTS"
+                run_traced "cd $PRJPATH; DEV_ENVIRONMENT=$PRJNAME $(which zerobug) $OPTS"
             else
-                run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME $(which zerobug) $OPTS"
+                run_traced "cd $PRJPATH/tests; DEV_ENVIRONMENT=$PRJNAME $(which zerobug) $OPTS"
             fi
             s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
         fi
@@ -335,9 +347,9 @@ install_n_activate_tools() {
 
 OPTOPTS=(h        c        j        K         n            p        q           r     T        t         V           v)
 OPTDEST=(opt_help opt_conf opt_dprj opt_check opt_dry_run  opt_pyth opt_verbose opt_r opt_regr test_mode opt_version opt_verbose)
-OPTACTI=(1        "="      1        1         1            1        0           1     1        1         "*>"        "+")
-OPTDEFL=(0        ""       0        0         0            0        -1          0     0        0         ""          -1)
-OPTMETA=("help"   "file"   "dprj"   "check"   "do nothing" ""       "qiet"     "rxt"  "test"   "test"    "version"   "verbose")
+OPTACTI=("+"      "="      1        1         1            1        0           1     1        1         "*>"        "+")
+OPTDEFL=(0        ""       0        0         0            0        0           0     0        0         ""          -1)
+OPTMETA=("help"   "file"   "dprj"   "check"   "do nothing" ""       "quiet"     "rxt" "test"   "test"    "version"   "verbose")
 OPTHELP=("this help"\
  "configuration file (def .travis.conf)"\
  "execute tests in project dir rather in test dir"\
@@ -369,9 +381,6 @@ fi
 [ ${TRAVIS_DEBUG_MODE:-0} -ne 0 ] && opt_verbose=1
 
 opts_travis
-CFG_init
-conf_default
-link_cfg $DIST_CONF $TCONF
 [[ $opt_verbose -gt 2 ]] && set -x
 init_travis
 prepare_env_travis
