[RUN] test nightly

diff --git a/travis_emulator/tests/all_tests b/travis_emulator/tests/all_tests
--- a/travis_emulator/tests/all_tests
+++ b/travis_emulator/tests/all_tests
@@ -2,7 +2,7 @@
 # -*- coding: utf-8 -*-
 # Regression tests on travis emulator
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
@@ -36,12 +36,12 @@ __version__=0.1.86.9
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log "$@ -J"
+parseoptest -l$TESTDIR/test_travis_em.log "$@" -J
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-if [ ${opt_tlib:-0} -ne 0 ]; then
+if [ ${opt_tjlib:-0} -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
   if [ -z "$TRAVISLIBDIR" ]; then
     echo "Library file travisrc not found!"
@@ -49,10 +49,18 @@ if [ ${opt_tlib:-0} -ne 0 ]; then
   fi
   . $TRAVISLIBDIR
 fi
+if [ ${opt_oelib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev /etc")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
+fi
 UT_LIST="__version_V_${__version__}$RUNDIR/travis"
 UT_LIST="$UT_LIST __version_1_${__version__}$RUNDIR/travisrc"
 UT_LIST="$UT_LIST __version_0_0.2.9_$Z0TLIBDIR/z0testrc"
-UT_LIST="$UT_LIST __version_1_0.2.1$Z0LIBDIR/z0librc"
+UT_LIST="$UT_LIST __version_1_0.2.1.4$Z0LIBDIR/z0librc"
 # UT_LIST="$UT_LIST test_travisrc1 test_travisrc2 test_autopep8 test_cvt4dist test_yaml test_regex test_dist_pkg test_cronow test_vfdiff test_vfcp"
 UT_LIST="$UT_LIST test_travisrc1 test_travisrc2 test_autopep8 test_cvt4dist           test_regex test_dist_pkg             test_vfdiff test_vfcp"
 if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
diff --git a/travis_emulator/tests/test_vfdiff b/travis_emulator/tests/test_vfdiff
--- a/travis_emulator/tests/test_vfdiff
+++ b/travis_emulator/tests/test_vfdiff
@@ -2,7 +2,7 @@
 # -*- coding: utf-8 -*-
 # Regression tests on travis emulator
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
@@ -16,6 +16,12 @@ if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $TDIR/../zerobug $TDIR/../../zerobug  . .. $HOME/dev")
@@ -25,6 +31,7 @@ if [ -z "$Z0TLIBDIR" ]; then
 fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
+
 __version__=0.1.15
 
 
@@ -135,18 +142,26 @@ opt_tlib=1
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log "$@ -J"
+parseoptest -l$TESTDIR/test_travis_em.log "$@" -J
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-if [ ${opt_tlib:-0} -ne 0 ]; then
+if [ ${opt_tjlib:-0} -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
   if [ -z "$TRAVISLIBDIR" ]; then
     echo "Library file travisrc not found!"
     exit 2
   fi
   . $TRAVISLIBDIR
+fi
+if [ ${opt_oelib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev /etc")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
 fi
 UT1_LIST=
 UT_LIST=
