[IMP] New feature for travis emulator

diff --git a/travis_emulator/tests/all_tests b/travis_emulator/tests/all_tests
--- a/travis_emulator/tests/all_tests
+++ b/travis_emulator/tests/all_tests
@@ -16,7 +16,7 @@ if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
-TRAVISLIBDIR=$(findpkg travisrc "$TDIR . .. $HOME/dev $TDIR/../../travis_emulator")
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
   exit 2
@@ -24,18 +24,30 @@ fi
 . $TRAVISLIBDIR
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.78
+__version__=0.1.78.1
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log $@
+parseoptest -l$TESTDIR/test_travis_em.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
+fi
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
 
 UT_LIST="__version_V_${__version__}$RUNDIR/travis"
@@ -44,5 +56,8 @@ UT_LIST="$UT_LIST __version_0_0.2.7_$Z0TLIBDIR/z0testrc"
 UT_LIST="$UT_LIST __version_1_0.1.44$Z0LIBDIR/z0librc"
 # UT_LIST="$UT_LIST test_travisrc1 test_travisrc2 test_yaml test_regex test_dist_pkg test_cronow test_vfdiff test_vfcp"
 UT_LIST="$UT_LIST test_travisrc1 test_travisrc2 test_regex test_dist_pkg test_vfdiff test_vfcp"
-Z0BUG_main_file "" "$UT_LIST"
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
 exit $sts
diff --git a/travis_emulator/tests/test_regex b/travis_emulator/tests/test_regex
--- a/travis_emulator/tests/test_regex
+++ b/travis_emulator/tests/test_regex
@@ -18,21 +18,25 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.30
+__version__=0.1.31
 
 
-Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log $@
-sts=$?
-if [ $sts -ne 127 ]; then
-  exit $sts
-fi
-sts=0
-saved_opt_dry_run=$opt_dry_run
+#Z0BUG_init
+#parseoptest -l$TESTDIR/test_travis_em.log $@
+#sts=$?
+#if [ $sts -ne 127 ]; then
+#  exit $sts
+#fi
+#sts=0
+
 
 
 test_result_k () {
@@ -151,22 +155,27 @@ test_01() {
 # if [ -f $GCONF ]; then rm -f $GCONF; fi
 # link_cfg $FCONF $GCONF
 # set_cfg_def "ignore" ".pyc .log .bak .out .conf build/ dist/ conf/ .cover/ .coverage/ .git/ ~"
+saved_opt_dry_run=$opt_dry_run
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_travis_em.log "$@ -J"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
-if [ -z "$TRAVISLIBDIR" ]; then
-  echo "Library file travisrc not found!"
-  exit 2
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
-. $TRAVISLIBDIR
 
 UT1_LIST=""
 UT_LIST=""
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
-exit $?
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/travis_emulator/tests/test_travisrc2 b/travis_emulator/tests/test_travisrc2
--- a/travis_emulator/tests/test_travisrc2
+++ b/travis_emulator/tests/test_travisrc2
@@ -18,11 +18,15 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.3
+__version__=0.1.4
 
 
 save_testenv() {
@@ -418,22 +422,25 @@ test_06() {
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_travis_em.log "$@ -J"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
-if [ -z "$TRAVISLIBDIR" ]; then
-  echo "Library file travisrc not found!"
-  exit 2
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
-. $TRAVISLIBDIR
 
 UT1_LIST=""
 UT_LIST=""
 Z0BUG_setup
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
-Z0BUG_teardown
-exit $?
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/travis_emulator/tests/test_vfdiff b/travis_emulator/tests/test_vfdiff
--- a/travis_emulator/tests/test_vfdiff
+++ b/travis_emulator/tests/test_vfdiff
@@ -18,11 +18,15 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.13
+__version__=0.1.14
 
 
 Z0BUG_setup() {
@@ -132,7 +136,7 @@ opt_tlib=1
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_travis_em.log "$@ -J"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
diff --git a/z0lib/tests/all_tests b/z0lib/tests/all_tests
--- a/z0lib/tests/all_tests
+++ b/z0lib/tests/all_tests
@@ -3,7 +3,7 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
@@ -17,7 +17,11 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
@@ -33,7 +37,7 @@ test_00() {
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
+parseoptest -l$TESTDIR/test_z0lib.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
@@ -50,6 +54,7 @@ UT1_LIST="test_wlog"
 UT_LIST="__version_1_${__version__}$RUNDIR/z0librc"
 UT_LIST="$UT_LIST test_00"
 UT_LIST="$UT_LIST test_findpkg test_run test_parseoptargs test_dict1 test_dict2 test_cfg1 test_cfg2 test_cfg3 test_cfg4 test_Makefile"
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
 sts=$?
 if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
diff --git a/z0lib/tests/test_Makefile b/z0lib/tests/test_Makefile
--- a/z0lib/tests/test_Makefile
+++ b/z0lib/tests/test_Makefile
@@ -3,7 +3,7 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
@@ -17,10 +17,13 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
 __version__=0.1.84
 
 
@@ -188,7 +191,7 @@ test_01() {
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_z0lib.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
diff --git a/z0lib/tests/test_cfg4 b/z0lib/tests/test_cfg4
--- a/z0lib/tests/test_cfg4
+++ b/z0lib/tests/test_cfg4
@@ -3,7 +3,7 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
@@ -17,7 +17,11 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
@@ -64,7 +68,7 @@ test_01() {
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_z0lib.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
@@ -80,11 +84,12 @@ fi
 UT1_LIST=
 UT_LIST=
 if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
-# This code must be execute at the main level
+# Follow code must be executed at main level sue bash limitations
 for tid in 0 1 2 3; do
   eval $(init_cfg $tid)
   eval $(active_cfg $tid)
 done
+# /End Included Block/
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
 sts=$?
 if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
diff --git a/z0lib/tests/test_parseoptargs b/z0lib/tests/test_parseoptargs
--- a/z0lib/tests/test_parseoptargs
+++ b/z0lib/tests/test_parseoptargs
@@ -3,7 +3,7 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
@@ -17,7 +17,11 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
@@ -277,10 +281,18 @@ test_06() {
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
+parseoptest -l$TESTDIR/test_z0lib.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
+fi
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
 UT1_LIST=
 UT_LIST=
