[RUN] blueman test

diff --git a/travis_emulator/tests/test_cronow b/travis_emulator/tests/test_cronow
--- a/travis_emulator/tests/test_cronow
+++ b/travis_emulator/tests/test_cronow
@@ -4,73 +4,65 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-# TRAVISRC=$(findpkg "travisrc" "$TDIR . .. $HOME/dev" "_travis")
-# . $TRAVISRC
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
+__version__=0.1.21.1
 
-__version__=0.1.21
+test_01() {
+    CFG_init
+    FCONF="$TESTDIR/test.conf"
 
-Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
-sts=$?
-if [ $sts -ne 127 ]; then
-  exit $sts
-fi
-sts=0
-
-
-eval $(init_cfg)
-eval $(active_cfg)
-FCONF="$TESTDIR/test.conf"
-
-CRONCMD="$RUNDIR/cronow"
-TESTOUT=$TESTDIR/cronow.out
-TESTTMP=$TESTDIR/cronow.tmp
-TESTRES=$TESTDIR/cronow.test
-TESTSH=$TESTDIR/cronow.test.sh
-TESTNOP=$TESTDIR/cronow.nop.sh
-TESTOUCH=$TESTDIR/cron.touch
-TESTSAVE=$TESTDIR/cronow.saved
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  if [ -f $TESTSAVE ]; then
-    dtf=$(stat $RUNDIR/cronow -c %y|awk '{print $1}')
-    tod=$(date +%Y-%m-%d)
-    if [ "$dtf" != "$tod" ]; then
-      crontab -l>$TESTSAVE
-    fi
-  else
-    crontab -l>$TESTSAVE
-  fi
-  cat <<EOF >$TESTNOP
+    CRONCMD="$RUNDIR/cronow"
+    TESTOUT=$TESTDIR/cronow.out
+    TESTTMP=$TESTDIR/cronow.tmp
+    TESTRES=$TESTDIR/cronow.test
+    TESTSH=$TESTDIR/cronow.test.sh
+    TESTNOP=$TESTDIR/cronow.nop.sh
+    TESTOUCH=$TESTDIR/cron.touch
+    TESTSAVE=$TESTDIR/cronow.saved
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      if [ -f $TESTSAVE ]; then
+        dtf=$(stat $RUNDIR/cronow -c %y|awk '{print $1}')
+        tod=$(date +%Y-%m-%d)
+        if [ "$dtf" != "$tod" ]; then
+          crontab -l>$TESTSAVE
+        fi
+      else
+        crontab -l>$TESTSAVE
+      fi
+      cat <<EOF >$TESTNOP
 # Script to validate unit test of cronow
 true
 EOF
-  cat <<EOF >$TESTSH
+      cat <<EOF >$TESTSH
 # Script to validate unit test of cronow
 date>$TESTOUCH
 EOF
-  chmod +x $TESTSH
-  if [ -f "$TESTOUCH" ]; then
-    rm -f $TESTOUCH
-  fi
-  echo -e "00 00 * * * $TESTNOP\n10 00 * * * $TESTSH"|crontab
-fi
+      chmod +x $TESTSH
+      if [ -f "$TESTOUCH" ]; then
+        rm -f $TESTOUCH
+      fi
+      echo -e "00 00 * * * $TESTNOP\n10 00 * * * $TESTSH"|crontab
+    fi
 
-if [ ${opt_dry_run:-0} -eq 0 ]; then
- cat <<EOF >$TESTRES
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+     cat <<EOF >$TESTRES
 Usage: cronow [-heflnR][-s regex][-Vvw]
 Run now a selected cron statement from crontab
  -h             this help
@@ -88,60 +80,72 @@ Run now a selected cron statement from crontab
 http://wiki.zeroincombenze.org/en/Linux/dev
 Author: antoniomaria.vigliotti@gmail.com
 EOF
-  eval $CRONCMD>$TESTOUT
-fi
-ci-test "cronow" "$TESTOUT" "$TESTRES" "diff -Ztb"
-
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  crontab -l>$TESTRES
-  eval $CRONCMD -l>$TESTOUT
-fi
-ci-test "cronow -l" "$TESTOUT" "$TESTRES" "diff -Ztb"
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  x=$(basename $TESTSH)
-  eval $CRONCMD -s $x
-  cp $TESTRES $TESTTMP
-  echo "****************************************************************************">>$TESTTMP
-  echo "cronow is waiting for cron activation, please do not execute crontab command!">>$TESTTMP
-  eval $CRONCMD -l>$TESTOUT
-fi
-ci-test "cronow -s -l" "$TESTOUT" "$TESTTMP" "diff -Ztb"
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  eval $CRONCMD -R
-  eval $CRONCMD -l>$TESTOUT
-fi
-ci-test "cronow -R" "$TESTOUT" "$TESTRES" "diff -Ztb"
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  x=$(basename $TESTSH)
-  eval $CRONCMD -s $x
-  eval $CRONCMD -w
-  # echo "Waiting for execution in 70 seconds: please do not halt the test"
-  # sleep 70
-fi
-if [ -f "$TESTOUCH" -o ${opt_dry_run:-0} -ne 0 ]; then
-  RES=True
-else
-  RES=False
-fi
-ci-test "cronow -s" "True" "$RES"
-
-eval $CRONCMD -l>$TESTOUT
-ci-test "cronow -l" "$TESTOUT" "$TESTRES" "diff -Ztb"
-
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  for fn in $TESTOUT $TESTTMP $TESTRES $TESTSH $TESTNOP $TESTOUCH; do
-    if [ -f "$fn" ]; then
-      rm -f $fn
+      eval $CRONCMD>$TESTOUT
     fi
-  done
-fi
+    ci-test "cronow" "$TESTOUT" "$TESTRES" "diff -Ztb"
+
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      crontab -l>$TESTRES
+      eval $CRONCMD -l>$TESTOUT
+    fi
+    ci-test "cronow -l" "$TESTOUT" "$TESTRES" "diff -Ztb"
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      x=$(basename $TESTSH)
+      eval $CRONCMD -s $x
+      cp $TESTRES $TESTTMP
+      echo "****************************************************************************">>$TESTTMP
+      echo "cronow is waiting for cron activation, please do not execute crontab command!">>$TESTTMP
+      eval $CRONCMD -l>$TESTOUT
+    fi
+    ci-test "cronow -s -l" "$TESTOUT" "$TESTTMP" "diff -Ztb"
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      eval $CRONCMD -R
+      eval $CRONCMD -l>$TESTOUT
+    fi
+    ci-test "cronow -R" "$TESTOUT" "$TESTRES" "diff -Ztb"
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      x=$(basename $TESTSH)
+      eval $CRONCMD -s $x
+      eval $CRONCMD -w
+      # echo "Waiting for execution in 70 seconds: please do not halt the test"
+      # sleep 70
+    fi
+    if [ -f "$TESTOUCH" -o ${opt_dry_run:-0} -ne 0 ]; then
+      RES=True
+    else
+      RES=False
+    fi
+    ci-test "cronow -s" "True" "$RES"
+
+    eval $CRONCMD -l>$TESTOUT
+    ci-test "cronow -l" "$TESTOUT" "$TESTRES" "diff -Ztb"
+
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      for fn in $TESTOUT $TESTTMP $TESTRES $TESTSH $TESTNOP $TESTOUCH; do
+        if [ -f "$fn" ]; then
+          rm -f $fn
+        fi
+      done
+    fi
+
+}
 
 
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  cat $TESTSAVE|crontab
+Z0BUG_init
+parseoptest -l$TESTDIR/test_zerobug.log $@
+sts=$?
+if [ $sts -ne 127 ]; then
+  exit $sts
 fi
 
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
 fi
-exit $sts
+. $TRAVISLIBDIR
+
+UT1_LIST=""
+UT_LIST=""
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+exit $?
diff --git a/travis_emulator/tests/test_dist_pkg b/travis_emulator/tests/test_dist_pkg
--- a/travis_emulator/tests/test_dist_pkg
+++ b/travis_emulator/tests/test_dist_pkg
@@ -14,122 +14,129 @@ done
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-TRAVISRC=$(findpkg "travisrc" "$TDIR . .. $HOME/dev" "_travis")
-. $TRAVISRC
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.81
+
+__version__=0.1.82
+
+test_01() {
+    TEST_GCONF=$TESTDIR/test_dist_pkg.conf
+    TEST_LCONF=$TESTDIR/test_local_dist_pkg.conf
+    if [ -f $TEST_LCONF ]; then
+      rm -f $TEST_LCONF
+    fi
+    echo "# Sample conf file for test">$TEST_GCONF
+    echo "distpath=/opt/odoo/tools/\${prjname}">>$TEST_GCONF
+    echo "openerp_distpath=/opt/odoo/8.0">>$TEST_GCONF
+    echo "zeroincombenze_distpath=/opt/odoo/7.0/zeroincombenze">>$TEST_GCONF
+    echo "server_distpath=/opt/odoo/7.0/server/openerp">>$TEST_GCONF
+    echo "CONFN=$TEST_LCONF">>$TEST_GCONF
+
+    echo "# Sample conf file for test">$TEST_LCONF
+    echo "tgt9path=odoo@shsprd14:~/dev/pypi">>$TEST_LCONF
+
+
+    CWD=$PWD
+
+    TRES=$($RUNDIR/dist_pkg -V)
+    test_result "version" "$__version__" "$TRES"
+
+    cd $RUNDIR
+    TRES=$($RUNDIR/dist_pkg -W PKGPATH)
+    cd $CWD
+    test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
+
+    cd $RUNDIR
+    cd ..
+    TRES=$($RUNDIR/dist_pkg -W PKGPATH)
+    cd $CWD
+    test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
+
+    cd $TESTDIR
+    TRES=$($RUNDIR/dist_pkg -W PKGPATH)
+    cd $CWD
+    test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
+
+    TRES=$($RUNDIR/dist_pkg -W PKGPATH -p /opt/odoo/dev/pypi/travis_emulator/conf)
+    test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
+
+    TRES=$($RUNDIR/dist_pkg -W PKGPATH -p /opt/odoo/dev/pypi/travis_emulator/travis_emulator/conf)
+    test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
+
+    TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
+    test_result "param LGITPATH (travis)" "/opt/odoo/tools/travis_emulator" "$TRES"
+
+    if [ "$HOSTNAME" == "shsdev14" ]; then
+      cd /opt/odoo/7.0
+      TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
+      cd $CWD
+      test_result "param LGITPATH (odoo8)" "/opt/odoo/8.0" "$TRES"
+    else
+      test_result "dummy" "true" "true"
+    fi
+
+    if [ -d "/opt/openerp/7.0/zeroincombenze/l10n_it_bbone" ]; then
+      cd /opt/openerp/7.0/zeroincombenze/l10n_it_bbone
+      TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
+      cd $CWD
+      test_result "param LGITPATH (zeroincombenze)" "/opt/odoo/7.0/zeroincombenze" "$TRES"
+    fi
+
+    cd $TESTDIR
+    TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
+    cd $CWD
+    test_result "commit travis_emulator 1" "dist_pkg -n -C -p \"/opt/odoo/tools/travis_emulator\" travis_emulator travis_emulator" "$TRES"
+
+    cd $TESTDIR
+    cd ..
+    TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
+    cd $CWD
+    test_result "commit travis_emulator 2" "dist_pkg -n -C -p \"/opt/odoo/tools/travis_emulator\" travis_emulator travis_emulator" "$TRES"
+
+    if [ "$HOSTNAME" == "shsdev14" ]; then
+      cd /opt/odoo/7.0
+      TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
+      cd $CWD
+      test_result "commit openerp" "dist_pkg -n -C -p \"/opt/odoo/8.0\" 7.0 openerp" "$TRES"
+    else
+      test_result "dummy" "true" "true"
+    fi
+
+    echo "distpath=/opt/odoo">>$TEST_LCONF
+    cd $TESTDIR
+    TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
+    cd $CWD
+    test_result "param LGITPATH (odoo)" "/opt/odoo" "$TRES"
+
+    if [ -d "/opt/openerp/7.0/server/openerp/workflow" ]; then
+      cd /opt/openerp/7.0/server/openerp/workflow
+      TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
+      cd $CWD
+      test_result "param LGITPATH (workflow)" "/opt/odoo/7.0/server/openerp" "$TRES"
+    fi
+
+    TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
+    test_result "commit travis_emulator" "dist_pkg -n -C -p \"/opt/odoo\" travis_emulator travis_emulator" "$TRES"
+}
+
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log $@
+parseoptest -l$TESTDIR/test_zerobug.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-sts=0
 
-TEST_GCONF=$TESTDIR/test_dist_pkg.conf
-TEST_LCONF=$TESTDIR/test_local_dist_pkg.conf
-if [ -f $TEST_LCONF ]; then
-  rm -f $TEST_LCONF
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
 fi
-echo "# Sample conf file for test">$TEST_GCONF
-echo "distpath=/opt/odoo/tools/\${prjname}">>$TEST_GCONF
-echo "openerp_distpath=/opt/odoo/8.0">>$TEST_GCONF
-echo "zeroincombenze_distpath=/opt/odoo/7.0/zeroincombenze">>$TEST_GCONF
-echo "server_distpath=/opt/odoo/7.0/server/openerp">>$TEST_GCONF
-echo "CONFN=$TEST_LCONF">>$TEST_GCONF
+. $TRAVISLIBDIR
 
-echo "# Sample conf file for test">$TEST_LCONF
-echo "tgt9path=odoo@shsprd14:~/dev/pypi">>$TEST_LCONF
-
-
-CWD=$PWD
-
-TRES=$($RUNDIR/dist_pkg -V)
-test_result "version" "$__version__" "$TRES"
-
-cd $RUNDIR
-TRES=$($RUNDIR/dist_pkg -W PKGPATH)
-cd $CWD
-test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
-
-cd $RUNDIR
-cd ..
-TRES=$($RUNDIR/dist_pkg -W PKGPATH)
-cd $CWD
-test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
-
-cd $TESTDIR
-TRES=$($RUNDIR/dist_pkg -W PKGPATH)
-cd $CWD
-test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
-
-TRES=$($RUNDIR/dist_pkg -W PKGPATH -p /opt/odoo/dev/pypi/travis_emulator/conf)
-test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
-
-TRES=$($RUNDIR/dist_pkg -W PKGPATH -p /opt/odoo/dev/pypi/travis_emulator/travis_emulator/conf)
-test_result "param PKGPATH" "/opt/odoo/dev/pypi/travis_emulator" "$TRES"
-
-TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
-test_result "param LGITPATH (travis)" "/opt/odoo/tools/travis_emulator" "$TRES"
-
-if [ "$HOSTNAME" == "shsdev14" ]; then
-  cd /opt/odoo/7.0
-  TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
-  cd $CWD
-  test_result "param LGITPATH (odoo8)" "/opt/odoo/8.0" "$TRES"
-else
-  test_result "dummy" "true" "true"
-fi
-
-if [ -d "/opt/openerp/7.0/zeroincombenze/l10n_it_bbone" ]; then
-  cd /opt/openerp/7.0/zeroincombenze/l10n_it_bbone
-  TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
-  cd $CWD
-  test_result "param LGITPATH (zeroincombenze)" "/opt/odoo/7.0/zeroincombenze" "$TRES"
-fi
-
-cd $TESTDIR
-TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
-cd $CWD
-test_result "commit travis_emulator 1" "dist_pkg -n -C -p \"/opt/odoo/tools/travis_emulator\" travis_emulator travis_emulator" "$TRES"
-
-cd $TESTDIR
-cd ..
-TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
-cd $CWD
-test_result "commit travis_emulator 2" "dist_pkg -n -C -p \"/opt/odoo/tools/travis_emulator\" travis_emulator travis_emulator" "$TRES"
-
-if [ "$HOSTNAME" == "shsdev14" ]; then
-  cd /opt/odoo/7.0
-  TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
-  cd $CWD
-  test_result "commit openerp" "dist_pkg -n -C -p \"/opt/odoo/8.0\" 7.0 openerp" "$TRES"
-else
-  test_result "dummy" "true" "true"
-fi
-
-echo "distpath=/opt/odoo">>$TEST_LCONF
-cd $TESTDIR
-TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
-cd $CWD
-test_result "param LGITPATH (odoo)" "/opt/odoo" "$TRES"
-
-if [ -d "/opt/openerp/7.0/server/openerp/workflow" ]; then
-  cd /opt/openerp/7.0/server/openerp/workflow
-  TRES=$($RUNDIR/dist_pkg -c $TEST_GCONF -W LGITPATH)
-  cd $CWD
-  test_result "param LGITPATH (workflow)" "/opt/odoo/7.0/server/openerp" "$TRES"
-fi
-
-TRES=$($RUNDIR/dist_pkg -nc $TEST_GCONF -C|head -n1)
-test_result "commit travis_emulator" "dist_pkg -n -C -p \"/opt/odoo\" travis_emulator travis_emulator" "$TRES"
-
-
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
-fi
-exit $sts
+UT1_LIST=""
+UT_LIST=""
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+exit $?
diff --git a/travis_emulator/tests/test_regex b/travis_emulator/tests/test_regex
--- a/travis_emulator/tests/test_regex
+++ b/travis_emulator/tests/test_regex
@@ -14,14 +14,12 @@ done
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-TRAVISRC=$(findpkg "travisrc" "$TDIR . .. $HOME/dev" "_travis")
-. $TRAVISRC
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
+__version__=0.1.29
 
-__version__=0.1.28
 
 Z0BUG_init
 parseoptest -l$TESTDIR/test_travis_em.log $@
@@ -55,6 +53,86 @@ test_result_cp () {
     test_result "$1" "$2" "$3"
 }
 
+test_01() {
+    robocopy_init
+    a_append "--new"
+    a_append "KEY_A" "aaa"
+    a_append "KEY_B" "bbb"
+    a_append "^KEY.*" "any"
+
+    test_result_k "KEY_A" "KEY_A" "aaa"
+    test_result_k "KEY_B" "KEY_B" "bbb"
+    test_result_k "KEY_Z" "KEY_Z" "any"
+    test_result_k "NOKEY" "NOKEY" ""
+
+    a_append "--new"
+    a_append "/opt/odoo/dev/travis" "1"
+    a_append "/opt/odoo/dev/travis/travis.pyc" "0"
+    a_append "/opt/odoo/dev/travis/travis.log" "0"
+    a_append "/opt/odoo/dev/travis/travis.bak" "0"
+    a_append "/opt/odoo/dev/travis/build/travis.py" "0"
+    a_append "/opt/odoo/dev/travis/dist/travis.py" "0"
+    a_append "/opt/odoo/dev/travis/.coverage/result" "0"
+    a_append "/opt/odoo/dev/travis/.git/travis" "0"
+    a_append "/opt/odoo/dev/travis/conf/travis.conf" "0"
+    a_append "/opt/odoo/dev/travis/travis" "1"
+    a_append "/opt/odoo/dev/travis/travis/tests" "1"
+    a_append "/opt/odoo/dev/travis/travis/tests/travis.log" "0"
+    a_append "/opt/odoo/dev/travis/travis/tests/.logfile" "1"
+    a_append "build/travis.py" "0"
+    a_append ".coverage/result" "0"
+    a_append ".git/travis" "0"
+    a_append "conf/travis.conf" "0"
+    a_append "conf/travis.conf.sample" "1"
+    a_append "dist/travis.py" "0"
+
+    for f in ${DEFPRM[*]}; do
+      TRES=$(a_search "$f")
+      # set -x
+      test_result_x "$f" "$f" "$TRES"
+      sts=$?
+      # set +x
+      if [ $sts -gt 0 ]; then
+        break
+      fi
+    done
+
+    MAKEF=/opt/odoo/dev/pypi/travis_emulator/travis_emulator/Makefile
+
+    opt_dry_run=1
+    opts_dry_run="-n"
+    opt_fetch=0
+
+    robocopy_init "travis_emulator" "travis_emulator"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/travis_emulator" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy # rsync" "rsync -n -ab  --del --copy-links  --exclude=*.pyc --exclude=*.log --exclude=*.bak --exclude=*.out --exclude=*.conf --exclude=build/ --exclude=dist/ --exclude=conf/ --exclude=filestore/ --exclude=.cover/ --exclude=.coverage/ --exclude=.git/ --exclude=*~ /opt/odoo/dev/pypi/travis_emulator/travis_emulator/ /opt/odoo/tools/travis_emulator/" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/travis_emulator.egg-info" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/build" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/dist" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/README.rst" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.rst /opt/odoo/tools/travis_emulator/" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/README.md" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.md /opt/odoo/tools/travis_emulator/" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/setup.py" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/conf" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "" "$TRES"
+    TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/conf/conf.sample" "/opt/odoo/tools/travis_emulator")
+    test_result_cp "robocopy" "" "$TRES"
+
+    robocopy_init "Odoo" "zeroincombenze"
+    TRES=$(robocopy "/opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py" "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal")
+    test_result_cp "robocopy # odoo" "1||cp -L /opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/" "$TRES"
+    TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
+    test_result_cp "robocopy # rsync" "rsync -n -ab  --del --copy-links  --exclude=*.pyc --exclude=*.log --exclude=*.bak --exclude=*.out --exclude=*.conf --exclude=build/ --exclude=dist/ --exclude=conf/ --exclude=filestore/ --exclude=.cover/ --exclude=.coverage/ --exclude=.git/ --exclude=*~ /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data/ /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data/" "$TRES"
+    TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
+    test_result_cp "robocopy" "" "$TRES"
+    TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
+    test_result_cp "robocopy" "1||cp -L /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data" "$TRES"
+}
 
 # TODO: integration with z0librc
 # $(init_cfg)
@@ -66,87 +144,21 @@ test_result_cp () {
 # link_cfg $FCONF $GCONF
 # set_cfg_def "ignore" ".pyc .log .bak .out .conf build/ dist/ conf/ .cover/ .coverage/ .git/ ~"
 
-robocopy_init
-a_append "--new"
-a_append "KEY_A" "aaa"
-a_append "KEY_B" "bbb"
-a_append "^KEY.*" "any"
-
-test_result_k "KEY_A" "KEY_A" "aaa"
-test_result_k "KEY_B" "KEY_B" "bbb"
-test_result_k "KEY_Z" "KEY_Z" "any"
-test_result_k "NOKEY" "NOKEY" ""
-
-a_append "--new"
-a_append "/opt/odoo/dev/travis" "1"
-a_append "/opt/odoo/dev/travis/travis.pyc" "0"
-a_append "/opt/odoo/dev/travis/travis.log" "0"
-a_append "/opt/odoo/dev/travis/travis.bak" "0"
-a_append "/opt/odoo/dev/travis/build/travis.py" "0"
-a_append "/opt/odoo/dev/travis/dist/travis.py" "0"
-a_append "/opt/odoo/dev/travis/.coverage/result" "0"
-a_append "/opt/odoo/dev/travis/.git/travis" "0"
-a_append "/opt/odoo/dev/travis/conf/travis.conf" "0"
-a_append "/opt/odoo/dev/travis/travis" "1"
-a_append "/opt/odoo/dev/travis/travis/tests" "1"
-a_append "/opt/odoo/dev/travis/travis/tests/travis.log" "0"
-a_append "/opt/odoo/dev/travis/travis/tests/.logfile" "1"
-a_append "build/travis.py" "0"
-a_append ".coverage/result" "0"
-a_append ".git/travis" "0"
-a_append "conf/travis.conf" "0"
-a_append "conf/travis.conf.sample" "1"
-a_append "dist/travis.py" "0"
-
-for f in ${DEFPRM[*]}; do
-  TRES=$(a_search "$f")
-  # set -x
-  test_result_x "$f" "$f" "$TRES"
-  sts=$?
-  # set +x
-  if [ $sts -gt 0 ]; then
-    break
-  fi
-done
-
-MAKEF=/opt/odoo/dev/pypi/travis_emulator/travis_emulator/Makefile
-
-opt_dry_run=1
-opts_dry_run="-n"
-opt_fetch=0
-
-robocopy_init "travis_emulator" "travis_emulator"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/travis_emulator" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy # rsync" "rsync -n -ab  --del --copy-links  --exclude=*.pyc --exclude=*.log --exclude=*.bak --exclude=*.out --exclude=*.conf --exclude=build/ --exclude=dist/ --exclude=conf/ --exclude=filestore/ --exclude=.cover/ --exclude=.coverage/ --exclude=.git/ --exclude=*~ /opt/odoo/dev/pypi/travis_emulator/travis_emulator/ /opt/odoo/tools/travis_emulator/" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/travis_emulator.egg-info" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/build" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/dist" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/README.rst" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.rst /opt/odoo/tools/travis_emulator/" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/README.md" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.md /opt/odoo/tools/travis_emulator/" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/setup.py" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/conf" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "" "$TRES"
-TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/conf/conf.sample" "/opt/odoo/tools/travis_emulator")
-test_result_cp "robocopy" "" "$TRES"
-
-robocopy_init "Odoo" "zeroincombenze"
-TRES=$(robocopy "/opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py" "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal")
-test_result_cp "robocopy # odoo" "1||cp -L /opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/" "$TRES"
-TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
-test_result_cp "robocopy # rsync" "rsync -n -ab  --del --copy-links  --exclude=*.pyc --exclude=*.log --exclude=*.bak --exclude=*.out --exclude=*.conf --exclude=build/ --exclude=dist/ --exclude=conf/ --exclude=filestore/ --exclude=.cover/ --exclude=.coverage/ --exclude=.git/ --exclude=*~ /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data/ /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data/" "$TRES"
-TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
-test_result_cp "robocopy" "" "$TRES"
-TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
-test_result_cp "robocopy" "1||cp -L /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data" "$TRES"
-
-
-opt_dry_run=$saved_opt_dry_run
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
+Z0BUG_init
+parseoptest -l$TESTDIR/test_zerobug.log $@
+sts=$?
+if [ $sts -ne 127 ]; then
+  exit $sts
 fi
+
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
+
+UT1_LIST=""
+UT_LIST=""
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+exit $?
diff --git a/travis_emulator/tests/test_vfcp b/travis_emulator/tests/test_vfcp
--- a/travis_emulator/tests/test_vfcp
+++ b/travis_emulator/tests/test_vfcp
@@ -2,26 +2,28 @@
 # -*- coding: utf-8 -*-
 # Regression tests on travis emulator
 #
-THIS=$(basename $0)
+TTHIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-TRAVISRC=$(findpkg "travisrc" "$TDIR . .. $HOME/dev" "_travis")
-. $TRAVISRC
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
+__version__=0.1.4
 
-__version__=0.1.3
 
 test_copy() {
     local cmd="$RUNDIR/vfcp -nv $1 $2"
@@ -55,30 +57,38 @@ test_copy() {
     test_result "cp $msg1 $msg2" "$6" "$TRES"
 }
 
+test_01() {
+    test_copy "~/7.0" "~/v7" "" "" "" "cp -R /opt/odoo/7.0 /opt/odoo/v7"
+    test_copy "~/8.0" "~/7.0" "" "" "" "cp -R /opt/odoo/8.0 /opt/odoo/7.0"
+    test_copy "~/7.0" "~/8.0" "l10n-italy" "" "" "cp -R /opt/odoo/7.0/l10n-italy /opt/odoo/8.0/l10n-italy"
+    test_copy "~/7.0" "~/9.0" "l10n-italy" "l10n_it_vat_registries" "" "cp -R /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries /opt/odoo/9.0/l10n-italy/l10n_it_vat_registries"
+    test_copy "~/v7" "~/7.0" "zeroincombenze" "" "" "cp -R /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
+    test_copy "~/7.0" "~/v7" "zeroincombenze" "" "" "cp -R /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
+    test_copy "~/v7" "~/7.0" "l10n-italy-supplemental" "" "" "cp -R /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
+    test_copy "~/7.0" "~/v7" "l10n-italy-supplemental" "" "" "cp -R /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
+    test_copy "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "8.0" "" "" "" "cp  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
+    test_copy "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "" "" "" "-8" "cp  /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py"
+    test_copy " ~/v7/l10n-italy/l10n_it_base" "8.0" "" "" "" "cp -R /opt/odoo/v7/l10n-italy/l10n_it_base /opt/odoo/8.0/l10n-italy/l10n_it_base"
+    test_copy "~/v7/l10n-italy/l10n_it_base" "8.0" "" "" "" "cp -R /opt/odoo/v7/l10n-italy/l10n_it_base /opt/odoo/8.0/l10n-italy/l10n_it_base"
+    #test_copy " ~/7.0/l10n-italy-supplemental/account_banking_pain_base/" "~/v7.0/bank-payment/account_banking_pain_base" "" "" "" "cp -R /opt/odoo/7.0/l10n-italy-supplemental/account_banking_pain_base /opt/odoo/v7.0/bank-payment/account_banking_pain_base"
+}
+
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
+parseoptest -l$TESTDIR/test_zerobug.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-sts=0
 
-test_copy "~/7.0" "~/v7" "" "" "" "cp -R /opt/odoo/7.0 /opt/odoo/v7"
-test_copy "~/8.0" "~/7.0" "" "" "" "cp -R /opt/odoo/8.0 /opt/odoo/7.0"
-test_copy "~/7.0" "~/8.0" "l10n-italy" "" "" "cp -R /opt/odoo/7.0/l10n-italy /opt/odoo/8.0/l10n-italy"
-test_copy "~/7.0" "~/9.0" "l10n-italy" "l10n_it_vat_registries" "" "cp -R /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries /opt/odoo/9.0/l10n-italy/l10n_it_vat_registries"
-test_copy "~/v7" "~/7.0" "zeroincombenze" "" "" "cp -R /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
-test_copy "~/7.0" "~/v7" "zeroincombenze" "" "" "cp -R /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
-test_copy "~/v7" "~/7.0" "l10n-italy-supplemental" "" "" "cp -R /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
-test_copy "~/7.0" "~/v7" "l10n-italy-supplemental" "" "" "cp -R /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
-test_copy "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "8.0" "" "" "" "cp  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
-test_copy "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "" "" "" "-8" "cp  /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py"
-test_copy " ~/v7/l10n-italy/l10n_it_base" "8.0" "" "" "" "cp -R /opt/odoo/v7/l10n-italy/l10n_it_base /opt/odoo/8.0/l10n-italy/l10n_it_base"
-test_copy "~/v7/l10n-italy/l10n_it_base" "8.0" "" "" "" "cp -R /opt/odoo/v7/l10n-italy/l10n_it_base /opt/odoo/8.0/l10n-italy/l10n_it_base"
-test_copy " ~/7.0/l10n-italy-supplemental/account_banking_pain_base/" "~/v7.0/bank-payment/account_banking_pain_base" "" "" "" "cp -R /opt/odoo/7.0/l10n-italy-supplemental/account_banking_pain_base /opt/odoo/v7.0/bank-payment/account_banking_pain_base"
-
-
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
 fi
-exit $sts
+. $TRAVISLIBDIR
+
+UT1_LIST=""
+UT_LIST=""
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+exit $?
diff --git a/travis_emulator/tests/test_vfdiff b/travis_emulator/tests/test_vfdiff
--- a/travis_emulator/tests/test_vfdiff
+++ b/travis_emulator/tests/test_vfdiff
@@ -4,24 +4,26 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-TRAVISRC=$(findpkg "travisrc" "$TDIR . .. $HOME/dev" "_travis")
-. $TRAVISRC
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
+__version__=0.1.4
 
-__version__=0.1.3
 
 test_diff() {
     local cmd="$RUNDIR/vfdiff -nv $1 $2"
@@ -55,33 +57,42 @@ test_diff() {
     test_result "diff $msg1 $msg2" "$6" "$TRES"
 }
 
+test_01() {
+    test_diff "~/7.0" "~/v7" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0 /opt/odoo/v7"
+    test_diff "~/8.0" "~/7.0" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/8.0 /opt/odoo/7.0"
+    test_diff "~/7.0" "~/8.0" "l10n-italy" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy /opt/odoo/8.0/l10n-italy"
+    test_diff "~/7.0" "~/9.0" "l10n-italy" "l10n_it_vat_registries" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries /opt/odoo/9.0/l10n-italy/l10n_it_vat_registries"
+    test_diff "~/v7" "~/7.0" "zeroincombenze" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
+    test_diff "~/7.0" "~/v7" "zeroincombenze" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
+    test_diff "~/v7" "~/7.0" "l10n-italy-supplemental" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
+    test_diff "~/7.0" "~/v7" "l10n-italy-supplemental" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
+    test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "8.0" "" "" "" "diff  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
+    test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "" "" "" "8" "diff  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
+    test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "" "" "" "-8" "diff -y /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
+    CWD=$PWD
+    cd /opt/odoo/7.0/l10n-italy/l10n_it_base
+    test_diff "__openerp__.py" "" "" "" "8" "diff  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
+    cd $CWD
+    test_diff "~/v7/l10n-italy/l10n_it_base" "8.0" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/v7/l10n-italy/l10n_it_base /opt/odoo/8.0/l10n-italy/l10n_it_base"
+    # test_diff " ~/7.0/l10n-italy-supplemental/account_banking_pain_base/" "~/v7.0/bank-payment/account_banking_pain_base" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy-supplemental/account_banking_pain_base /opt/odoo/v7.0/bank-payment/account_banking_pain_base"
+}
+
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
+parseoptest -l$TESTDIR/test_zerobug.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-sts=0
 
-test_diff "~/7.0" "~/v7" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0 /opt/odoo/v7"
-test_diff "~/8.0" "~/7.0" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/8.0 /opt/odoo/7.0"
-test_diff "~/7.0" "~/8.0" "l10n-italy" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy /opt/odoo/8.0/l10n-italy"
-test_diff "~/7.0" "~/9.0" "l10n-italy" "l10n_it_vat_registries" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy/l10n_it_vat_registries /opt/odoo/9.0/l10n-italy/l10n_it_vat_registries"
-test_diff "~/v7" "~/7.0" "zeroincombenze" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
-test_diff "~/7.0" "~/v7" "zeroincombenze" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
-test_diff "~/v7" "~/7.0" "l10n-italy-supplemental" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/v7/zeroincombenze /opt/odoo/7.0/l10n-italy-supplemental"
-test_diff "~/7.0" "~/v7" "l10n-italy-supplemental" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy-supplemental /opt/odoo/v7/zeroincombenze"
-test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "8.0" "" "" "" "diff  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
-test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "" "" "" "8" "diff  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
-test_diff "/opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py" "" "" "" "-8" "diff -y /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
-CWD=$PWD
-cd /opt/odoo/7.0/l10n-italy/l10n_it_base
-test_diff "__openerp__.py" "" "" "" "8" "diff  /opt/odoo/7.0/l10n-italy/l10n_it_base/__openerp__.py /opt/odoo/8.0/l10n-italy/l10n_it_base/__openerp__.py"
-cd $CWD
-test_diff "~/v7/l10n-italy/l10n_it_base" "8.0" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/v7/l10n-italy/l10n_it_base /opt/odoo/8.0/l10n-italy/l10n_it_base"
-test_diff " ~/7.0/l10n-italy-supplemental/account_banking_pain_base/" "~/v7.0/bank-payment/account_banking_pain_base" "" "" "" "diff -x*.pyc -x*.po* -x*.bak -x*~ -qr /opt/odoo/7.0/l10n-italy-supplemental/account_banking_pain_base /opt/odoo/v7.0/bank-payment/account_banking_pain_base"
-
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
 fi
-exit $sts
+. $TRAVISLIBDIR
+
+UT1_LIST=""
+UT_LIST=""
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+exit $?
diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -38,40 +38,40 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.1.62.1
+__version__=0.1.62.3
 
 
-run_cmd () {
-    if [ "$(echo :$SHELLOPTS:|grep :xtrace: 2>/dev/null)" ]; then set +x; local SET_X="set -x"; else local SET_X=; fi
-    local xcmd="$1"
-    local sts=$STS_SUCCESS
-    local t=$(type -t $xcmd|head -n1)
-    local x
-    local s
-    read -r -a x<<<"$xcmd"
-    local k="${x[0]}"
-    if [ "$t" == "file" ]; then
-      grep -q "^.ELF" $k
-      s=$?
-      if [ $s -eq $STS_SUCCESS ]; then
-        t="bin"
-      fi
-    fi
-    if [ ${opt_dry_run:-0} -eq 0 ]; then
-      if [ ${opt_verbose:-0} -gt 1 ]; then
-        echo "\$ $xcmd"
-      fi
-      if [ "$t" == "file" ]; then
-        eval "$xcmd"
-        sts=$?
-      else
-        eval "$xcmd"
-        sts=$?
-      fi
-    fi
-    $SET_X
-    return $sts
-}
+# run_cmd () {
+#     if [ "$(echo :$SHELLOPTS:|grep :xtrace: 2>/dev/null)" ]; then set +x; local SET_X="set -x"; else local SET_X=; fi
+#     local xcmd="$1"
+#     local sts=$STS_SUCCESS
+#     local t=$(type -t $xcmd|head -n1)
+#     local x
+#     local s
+#     read -r -a x<<<"$xcmd"
+#     local k="${x[0]}"
+#     if [ "$t" == "file" ]; then
+#       grep -q "^.ELF" $k
+#       s=$?
+#       if [ $s -eq $STS_SUCCESS ]; then
+#         t="bin"
+#       fi
+#     fi
+#     if [ ${opt_dry_run:-0} -eq 0 ]; then
+#       if [ ${opt_verbose:-0} -gt 1 ]; then
+#         echo "\$ $xcmd"
+#       fi
+#       if [ "$t" == "file" ]; then
+#         eval "$xcmd"
+#         sts=$?
+#       else
+#         eval "$xcmd"
+#         sts=$?
+#       fi
+#     fi
+#     $SET_X
+#     return $sts
+# }
 
 process_local () {
     if [ $TOOLS_PATH/travis_run_tests ]; then
@@ -315,13 +315,13 @@ process_yaml_file () {
     local line1=
     local lne1=
     local linex=
-    local i
-    local a
-    local b
-    while IFS=\~ read -r line; do
-      if [[ $line =~ ^[[:space:]]*# ]]; then
-        line=
-      elif [[ $line =~ ^[[:space:]]+ ]]; then
+    local a b i r
+    # while IFS=\~ read -r line; do
+    while IFS="#" read -r line r; do
+      # if [[ $line =~ ^[[:space:]]*# ]]; then
+      #   line=
+      # elif [[ $line =~ ^[[:space:]]+ ]]; then
+      if [[ $line =~ ^[[:space:]]+ ]]; then
         for i in {0..10};do if [ "${line:i:1}" != " " ]; then break; fi; done
         if [ $i -gt $ident ]; then
            ((lev++))
@@ -397,10 +397,7 @@ process_yaml_before_install () {
 process_yaml_install () {
     wlog "===== [Install] ====="
     local sts=$STS_SUCCESS
-    local i
-    local s
-    local line
-    local lne
+    local i s line lne
     for lne in $YML_install; do
       line=$(process_yaml_quote_xtl $lne)
       wlog "\$ $line"
@@ -483,12 +480,8 @@ process_yaml_after_success () {
 
 process_yaml () {
     local sts=$STS_SUCCESS
-    local i
-    local s
-    local line
-    local lne
-    local line1
-    local lne1
+    local i s
+    local line lne line1 lne1
     f1=$PRJPATH/.travis.yml
     if [ ! -f $f1 ]; then
       f1=$TOOLS_PATH/travis.yml
@@ -496,6 +489,18 @@ process_yaml () {
     if [ -f $f1 ]; then
       process_yaml_file "$f1"
       sts=$STS_SUCCESS
+      wlog "===== [System informations] ====="
+      wlog "# Execution environment: $TRAVIS_ENV"
+      if [ ${opt_virt:-0} -gt 0 ]; then
+        wlog "\$ virtualenv $TRAVIS_ENVOPTS $TRAVIS_ENVDIR"
+        create_virtual_env
+      fi
+      for lne in HOSTENV TOOLS_PATH MQT_PATH DEVPATH PRJNAME pkgname REPOSNAME BRANCH PRJPATH PKGPATH; do
+         lne1=${!lne}
+         if [ -n "$lne1" ]; then
+           wlog "\$ $lne=$lne1"
+         fi
+      done
       wlog "===== [Initialize] ====="
       run_svr_test_init
       process_yaml_before_install
@@ -526,6 +531,7 @@ process_yaml () {
       if [ $sts -eq $STS_SUCCESS ]; then
         process_yaml_after_success
       fi
+      drop_virtual_env
     else
       process_local
       sts=$?
@@ -534,14 +540,15 @@ process_yaml () {
 }
 
 
-OPTOPTS=(h        b          c        j        m       n            q           r     V           v)
-OPTDEST=(opt_help opt_branch opt_conf opt_dprj opt_mis opt_dry_run  opt_verbose opt_r opt_version opt_verbose)
-OPTACTI=(1        "="        "="      1        1       "1>"         0           1     "*>"        "+")
-OPTDEFL=(0        9.0        ""       0        0       0            -1          0     ""          -1)
-OPTMETA=("help"   "branch"   "file"   "dprj"   ""      "do nothing" "verbose"   "res" "version"   "verbose")
+OPTOPTS=(h        b          c        H        j        m       n            q           r     V           v)
+OPTDEST=(opt_help opt_branch opt_conf opt_virt opt_dprj opt_mis opt_dry_run  opt_verbose opt_r opt_version opt_verbose)
+OPTACTI=(1        "="        "="      1        1        1       "1>"         0           1     "*>"        "+")
+OPTDEFL=(0        9.0        ""       -1       0        0       0            -1          0     ""          -1)
+OPTMETA=("help"   "branch"   "file"   ""       "dprj"   ""      "do nothing" "verbose"   "res" "version"   "verbose")
 OPTHELP=("this help"\
  "branch: must be 7.0 or 8.0 or 9.0 (def 9.0)"\
  "configuration file (def .travis.conf)"\
+ "use virtualenv to run tests"\
  "execute tests in project dir rather in test dir"\
  "show missing line in report coverage"\
  "do nothing (dry-run)"\
@@ -564,20 +571,29 @@ fi
 
 if [ -z "$action" ]; then action=all; fi
 if [ -z $pkg ]; then pkg="."; fi
+# if [ "$action" != "check" -a "$action" != "test" -a "$action" != "all" -a "$action" != "setup" -a "$action" != "chkconfig" ]; then
+ACTIONS="check test all setup chkconfig"
+VIRTACTS="check test all"
+if [[ " $ACTIONS " =~ [[:space:]]$action[[:space:]] ]]; then
+  if [[ " $VIRTACTS " =~ [[:space:]]$action[[:space:]] ]]; then
+    :
+  else
+    opt_virt=0
+  fi
+else
+  echo "Invalid action!"
+  echo "action should be one of $ACTIONS"
+  exit $STS_FAILED
+fi
 opts_travis
 CFG_init
 conf_default
 link_cfg $TCONF
+
 init_travis
 prepare_env_travis "$action"
 sts=$STS_SUCCESS
 if [ $opt_verbose -gt 1 ]; then set -x; fi
-
-if [ "$action" != "check" -a "$action" != "test" -a "$action" != "all" -a "$action" != "setup" -a "$action" != "chkconfig" ]; then
-  echo "Invalid action!"
-  echo "action should be one of check, test, all, setup or chkconfig"
-  exit $STS_FAILED
-fi
 
 if [ "$action" == "setup" ]; then
   opt_r=0
@@ -605,10 +621,6 @@ fi
 
 check_4_travis
 sts=$STS_SUCCESS
-#if [ -f $TOOLS_PATH/travis_install_pkgs ]; then
-#  run_traced $TOOLS_PATH/travis_install_pkgs
-#  if [ $? -ne 0 ]; then sts=$?; fi
-#fi
 if [ $sts -eq $STS_SUCCESS ]; then
   if [ $opt_r -gt 0 ]; then
     wlog "=== Simulate YAML test ==="
