[IMP] Minor features

diff --git a/travis_emulator/tests/test_Makefile b/travis_emulator/tests/test_Makefile
--- a/travis_emulator/tests/test_Makefile
+++ b/travis_emulator/tests/test_Makefile
@@ -18,10 +18,13 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
 __version__=0.1.77
 
 
diff --git a/zerobug/z0bug_cvt_script b/zerobug/z0bug_cvt_script
--- a/zerobug/z0bug_cvt_script
+++ b/zerobug/z0bug_cvt_script
@@ -32,18 +32,19 @@ fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.3
+__version__=0.1.4
 
 
 cvt_file() {
 # cvt_file(file)
     local f1=$1
+    local fntmp=$f1.tmp
+    local bakfn=$f1.bak
+    local x y empty line
     sts=$STS_SUCCESS
+    local prc=0
     if [ -n "$f1" ]; then
-      local fntmp=$f1.tmp
-      local bakfn=$f1.bak
-      prc=0
-      if [ -f "$f1" ]; then
+      if [ -x "$f1" ]; then
          if [ $opt_tlib -ne 0 ]; then
            OPTS_J=" -J"
          else
@@ -52,7 +53,20 @@ cvt_file() {
          local incl=0
          local empty=0
          rm -f $fntmp
-         while IFS= read -r line r || [ -n "$p" ]; do
+         while IFS= read -r line r || [ -n "$line" ]; do
+           if [ $opt_keep -eq 0 ] && [[ $line =~ ^__version__=.* ]]; then
+             if [ $opt_lev3 -eq 0 ]; then
+               x=$(echo $line|grep -Eo [0-9]+\.[0-9]+\.[0-9]+\(\.[0-9]*\)?|awk -F. '{print $4}')
+               ((x++))
+               y="$(echo $line|grep -Eo [0-9.]+|awk -F. '{print $1"."$2"."$3}')"
+               line="__version__=$y.$x"
+             else
+               x=$(echo $line|grep -Eo [0-9]+\.[0-9]+\.[0-9]+|awk -F. '{print $3}')
+               ((x++))
+               y="$(echo $line|grep -Eo [0-9.]+|awk -F. '{print $1"."$2}')"
+               line="__version__=$y.$x"
+             fi
+           fi
            if [ $prc -eq 0 ]; then
              if [[ $line =~ ^THIS.*basename.* ]]; then
                prc=1
@@ -105,6 +119,11 @@ cvt_file() {
                prc=11
                blk_11 "$fntmp"
                empy=0
+             elif [[ $line =~ ^opts_travis ]]; then
+               prc=21
+               blk_21 "$fntmp"
+             elif [[ $line =~ ^TCONF=.* ]]; then
+               :
              else
                echo "$line">>$fntmp
              fi
@@ -127,7 +146,7 @@ cvt_file() {
                echo "$line">>$fntmp
              fi
            elif [ $prc -eq 13 ]; then
-             echo "$incl) $line" #debug
+             # echo "$incl) $line" #debug
              if [[ $line =~ ^Z0BUG_main_file.* ]]; then
                prc=14
                blk_14 "$fntmp"
@@ -143,6 +162,19 @@ cvt_file() {
              fi
            elif [ $prc -eq 14 ]; then
              :
+           elif [ $prc -eq 21 ]; then
+             if [[ $line =~ ^init_travis ]]; then
+               echo "$line">>$fntmp
+               prc=22
+             elif [[ $line =~ ^#.End.Include.Block.* ]]; then
+               echo "$line">>$fntmp
+               incl=0
+             elif [[ $line =~ ^#.Follow.code.must.be.executed.* ]]; then
+               echo "$line">>$fntmp
+               incl=1
+             elif [ $incl -gt 0 ]; then
+               echo "$line">>$fntmp
+             fi
            elif [ "${line:0:1}" == "#" ]; then
              echo "$line">>$fntmp
              empy=0
@@ -155,26 +187,28 @@ cvt_file() {
            fi
          done < $f1
       else
-        echo "File $f1 not found!"
+        echo "File $f1 not found or not executable!"
         sts=2
       fi
     fi
-    diff $f1 $fntmp
-    if [ $? -eq 0 ]; then
-      dummy='n'
-    else
-      read -p "Confirm (Y/N)? " dummy
-    fi
-    if [ "$dummy" == "Y" -o "$dummy" == "y" ]; then
-      cp -p $f1 $bakfn
-      mv $fntmp $f1
-      chmod +x $f1
-      if [ $opt_verbose -gt 0 ]; then
-        echo "File $f1 upgraded"
+    if [ -f $fntmp ]; then
+      diff $f1 $fntmp
+      if [ $? -eq 0 ]; then
+        dummy='n'
+      else
+        read -p "Confirm (Y/N)? " dummy
       fi
-    else
-      rm -f $fntmp
-      echo "Upgrade of $f1 discarded!"
+      if [ "$dummy" == "Y" -o "$dummy" == "y" ]; then
+        cp -p $f1 $bakfn
+        mv $fntmp $f1
+        chmod +x $f1
+        if [ $opt_verbose -gt 0 ]; then
+          echo "File $f1 upgraded"
+        fi
+      else
+        rm -f $fntmp
+        echo "Upgrade of $f1 discarded!"
+      fi
     fi
     return $sts
 }
@@ -263,13 +297,28 @@ exit \$sts
 EOF
 }
 
-OPTOPTS=(h        J        n           m         q           V           v           y)
-OPTDEST=(opt_help opt_tlib opt_dry_run opt_id    opt_verbose opt_version opt_verbose opt_yes)
-OPTACTI=(1        1        1           "="       0           "*"         "+"         1)
-OPTDEFL=(1        0        0           "UNKNOWN" -1          ""          -1          0)
-OPTMETA=("help"   ""       "noop"      "name"    "quiet"     "version"   "verbose"   "")
+
+blk_21() {
+    cat <<EOF >>$1
+opts_travis
+DIST_CONF=\$(readlink -f \$PKGPATH/conf/.local_dist_pkg.conf)
+CFG_init
+conf_default
+link_cfg \$DIST_CONF \$TCONF
+if [ \$opt_verbose -gt 1 ]; then set -x; fi
+EOF
+}
+
+
+OPTOPTS=(h        J        K        k        n           m         q           V           v           y)
+OPTDEST=(opt_help opt_tlib opt_lev3 opt_keep opt_dry_run opt_id    opt_verbose opt_version opt_verbose opt_yes)
+OPTACTI=(1        1        1        1        1           "="       0           "*"         "+"         1)
+OPTDEFL=(1        0        0        0        0           "UNKNOWN" -1          ""          -1          0)
+OPTMETA=("help"   ""       ""       ""       "noop"      "name"    "quiet"     "version"   "verbose"   "")
 OPTHELP=("this help"\
  "load travisrc library"\
+ "set script version format n.n.n"\
+ "Keep script version"\
  "do nothing (dry-run)"\
  "module name"\
  "silent mode"\
diff --git a/zerobug/zerobug b/zerobug/zerobug
--- a/zerobug/zerobug
+++ b/zerobug/zerobug
@@ -18,15 +18,18 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
 __version__=0.2.8
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_zerobug.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
