[RUN] test nightly

diff --git a/travis_emulator/tests/test_lib b/travis_emulator/tests/test_lib
--- a/travis_emulator/tests/test_lib
+++ b/travis_emulator/tests/test_lib
@@ -14,14 +14,48 @@ done
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-TRAVISRC=$(findpkg "travisrc" "$TDIR . .. $HOME/dev" "_travis")
-. $TRAVISRC
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR . .. $HOME/dev $HOME" "_travis")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
+__version__=0.1.7
 
-__version__=0.1.4
+
+save_testenv() {
+    local p
+    for p in opt_dry_run opt_verbose TOOLS_PATH PRJNAME PRJPATH; do
+      eval SAVE_$p=${!p}
+    done
+    SAVE_BRIEF="$1"
+    for p in PKGPATHX; do
+      if [ "$SAVE_BRIEF" != "brief" ]; then
+        eval SAVE_$p=${!p}
+      fi
+    done
+}
+
+restore_testenv() {
+    local p x
+    for p in opt_dry_run opt_verbose TOOLS_PATH PRJNAME PRJPATH; do
+      x=saved_$p
+      eval $p=${!x}
+      eval SAVE_$p=
+    done
+    for p in PKGPATHX; do
+      x=saved_$p
+      if [ "$SAVE_BRIEF" != "brief" ]; then
+        eval $p=${!x}
+      fi
+      eval SAVE_$p=
+    done
+}
+
 
 Z0BUG_init
 parseoptest -l$TESTDIR/test_z0librc.log $@
@@ -31,11 +65,7 @@ if [ $sts -ne 127 ]; then
 fi
 sts=0
 
-SAVE_opt_verbose=$opt_verbose
-SAVE_opt_dry_run=$opt_dry_run
-SAVE_TOOLS_PATH=$TOOLS_PATH
-SAVE_PRJNAME=$PRJNAME
-SAVE_PRJPATH=$PRJPATH
+save_testenv
 SAVE_PKGPATH=$PKGPATH
 SAVE_pkgname=$pkgname
 SAVE_REPOSNAME=$REPOSNAME
@@ -48,15 +78,14 @@ opt_verbose=-1
 pkg=
 DEV_ENVIRONMENT=$THIS
 opts_travis
-eval $(init_cfg)
-eval $(active_cfg)
+CFG_init
 conf_default
 link_cfg $TCONF
 init_travis
 tested_opt_verbose=$opt_verbose
-opt_verbose=$SAVE_opt_verbose
 tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$SAVE_opt_dry_run
+restore_testenv
+save_testenv
 ci-test "echo \$TCONF" "$opt_conf" "$TCONF"
 ci-test "echo \$FLOG_ECHO" "echo" "$FLOG_ECHO"
 T=$(readlink -e $RUNDIR/..)
@@ -73,15 +102,14 @@ opt_verbose=2
 pkg=
 DEV_ENVIRONMENT=$THIS
 opts_travis
-eval $(init_cfg)
-eval $(active_cfg)
+CFG_init
 conf_default
 link_cfg $TCONF
 init_travis
 tested_opt_verbose=$opt_verbose
-opt_verbose=$SAVE_opt_verbose
 tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$SAVE_opt_dry_run
+restore_testenv
+save_testenv
 ci-test "echo \$TCONF" "$TESTDIR/.travis.conf" "$TCONF"
 ci-test "echo \$opt_verbose" "2" "$tested_opt_verbose"
 
@@ -89,8 +117,8 @@ ci-test "echo \$opt_verbose" "2" "$tested_opt_verbose"
 TOOLS_PATH=~/dev/_travis
 opt_verbose=1
 opts=$(inherits_travis_opts "v")
-opt_verbose=$SAVE_opt_verbose
-TOOLS_PATH=$SAVE_TOOLS_PATH
+restore_testenv
+save_testenv
 ci-test ". -v" "-v" "$opts"
 
 
@@ -98,8 +126,8 @@ TOOLS_PATH=~/maintainer-quality-tools/travis
 opt_verbose=1
 MQT_VERBOSE_MODE=
 inherits_travis_opts "v" >/dev/null
-opt_verbose=$SAVE_opt_verbose
-TOOLS_PATH=$SAVE_TOOLS_PATH
+restore_testenv
+save_testenv
 ci-test ". \$MQT_VERBOSE_MODE" "1" "$MQT_VERBOSE_MODE"
 
 
@@ -116,6 +144,7 @@ cat<<'EOF' >$FTEST
 > cp_n_upd "/etc/odoo/odooT-server.conf"
 > mkdir /opt/odoo/dependencies
 > export INCLUDE=l10n_it_base
+> ln -s /opt/odoo/odoo/T.0/l10n_italy /opt/odoo/dependencies/
 > ln -s /opt/odoo/odoo/T.0 /opt/odoo/odoo-T.0
 > ln -s /opt/odoo/dev/pypi/travis_emulator/l10n_it_base /opt/odoo/l10n_it_base-T.0
 EOF
@@ -132,10 +161,7 @@ mkdir -p $PKGPATH
 opt_verbose=1
 opt_dry_run=1
 run_svr_test_init > $FOUT
-opt_verbose=$SAVE_opt_verbose
-opt_dry_run=$SAVE_opt_dry_run
-PRJNAME=$SAVE_PRJNAME
-PRJPATH=$SAVE_PRJPATH
+restore_testenv
 PKGPATH=$SAVE_PKGPATH
 pkgname=$SAVE_pkgname
 REPOSNAME=$SAVE_REPOSNAME
