[IMP] new autopep8 features

diff --git a/travis_emulator/tests/test_yaml b/travis_emulator/tests/test_yaml
--- a/travis_emulator/tests/test_yaml
+++ b/travis_emulator/tests/test_yaml
@@ -4,7 +4,7 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
@@ -18,11 +18,14 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
-__version__=0.1.1
+__version__=0.1.1.1
 
 test_01() {
     local TESTOUT TESTRES TESTFN
@@ -58,20 +61,23 @@ EOF
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_travis_em.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
-if [ -z "$TRAVISLIBDIR" ]; then
-  echo "Library file travisrc not found!"
-  exit 2
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
-. $TRAVISLIBDIR
-
 UT1_LIST=""
 UT_LIST=""
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
-exit $?
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
