[IMP] Correction after regression tests

diff --git a/z0lib/_travis/_travis/travis_run_tests b/z0lib/_travis/_travis/travis_run_tests
--- a/z0lib/_travis/_travis/travis_run_tests
+++ b/z0lib/_travis/_travis/travis_run_tests
@@ -11,23 +11,33 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
+if [ -e $TDIR/z0librc ]; then
 . $TDIR/z0librc
-elif [ -f ./z0librc ]; then
+elif [ -e ./z0librc ]; then
 . ./z0librc
-elif [ -f ~/z0librc ]; then
+elif [ -e ../z0librc ]; then
+. ../z0librc
+elif [ -e ~/z0librc ]; then
 . ~/z0librc
-else
+elif [ -f /etc/z0librc ]; then
 . /etc/z0librc
+else
+  echo "Library file z0librc not found!"
+  exit $STS_FAILED
 fi
-DEVPATH=$(readlink -f $TDIR/..)
-. $DEVPATH/travisrc
-TCONF=$TDIR/.$THIS.conf
+if [ -f $TDIR/travisrc ]; then
+. $TDIR/travisrc
+elif [ -f ./travisrc ]; then
+. ./travisrc
+elif [ -f ~/travisrc ]; then
+. ~/travisrc
+fi
 
-__version__=0.1.2
+__version__=0.1.4
 
 
 test_flake8 () {
+    echo "======== Testing test_flake8 ========"
     FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"
     run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg"
     local status1=$?
@@ -37,7 +47,8 @@ test_flake8 () {
 }
 
 test_pylint () {
-    sts=0
+    echo "======== Testing test_pylint ========"
+    sts=$STS_SUCCESS
     TRAVIS_BUILD_DIR=$PKGPATH
     MODULES_TO_TEST=$TRAVIS_BUILD_DIR
     PYLINT_CONFIG_DIR="$(dirname $0)/cfg"
@@ -61,7 +72,6 @@ test_pylint () {
 
 
 run_regression_test () {
-    #set -x  #debug
     if [ -f ~/dev/pypi/$1/$1/tests/all_tests ]; then
       cd ~/dev/pypi/$1/$1/tests
       ./all_tests
@@ -71,24 +81,25 @@ run_regression_test () {
       python ~/dev/pypi/$1/$1/tests/test_$1.py
       sts=$?
     else
-      sts=1
+      sts=$STS_FAILED
     fi
-    #set +x #debug
 }
 
 
-OPTOPTS=(h        C         n            R        V           v)
-OPTDEST=(opt_help opt_check opt_dry_run  opt_regr opt_version opt_verbose)
-OPTACTI=(1        "1>"      "1>"         "1>"     "*>"        1)
-OPTDEFL=(0        0         0            0        ""          0)
-OPTMETA=("help"   "check"   "do nothing" "test"   "version"   "verbose")
+OPTOPTS=(h        C         c        n            R        t         V           v)
+OPTDEST=(opt_help opt_check opt_conf opt_dry_run  opt_regr test_mode opt_version opt_verbose)
+OPTACTI=(1        "1>"      "="      "1>"         "1>"     1         "*>"        1)
+OPTDEFL=(0        0         ""        0            0       0         ""          0)
+OPTMETA=("help"   "check"   "filr"   "do nothing" "test"   "test"    "version"   "verbose")
 OPTHELP=("this help"\
  "do flake8 and pylint checks"\
+ "configuration file"\
  "do nothing (dry-run)"\
  "do regression tests"\
+ "test mode (implies dry-run)"\
  "show version"\
  "verbose mode")
-OPTARGS=(pkg_path PRJNAME)
+OPTARGS=(pkg PRJNAME)
 
 parseoptargs "$@"
 if [ "$opt_version" ]; then
@@ -101,40 +112,41 @@ if [ $opt_help -gt 0 ]; then
   exit 0
 fi
 
-if [ "$pkg_path" ]; then
-  PKGPATH=$pkg_path
-else
-  PKGPATH=$PWD
+opts_travis
+$(init_cfg)
+$(active_cfg)
+conf_default
+link_cfg $TCONF
+init_travis
+if [ $opt_verbose -gt 1 ]; then
+  set -x
 fi
-PKGPATH=$(set_pkgpath "$PKGPATH")
-if [ ! -d $PKGPATH ]; then
-  echo "Invalid path $PKGPATH"
-  exit 1
-elif [ "$PRJNAME" != "Odoo" ]; then
-  if [ ! -d $PKGPATH/$pkgname ]; then
-    echo "Invalid path $PKGPATH/$pkgname"
-    exit 1
-  fi
+prepare_env_travis ""
+sts=$STS_SUCCESS
+if [ $test_mode -gt 0 ]; then
+  do_chkconfig
+  exit $STS_SUCCESS
 fi
+check_4_travis
 
 
-sts=0
+
 if [ $opt_verbose -gt 0 ]; then
   echo "if [ \${opt_check:-0} -gt 0 -o \"\${LINT_CHECK:-1}\" == \"1\" ]; then  #($opt_check,$LINT_CHECK)"
 fi
 if [ ${opt_check:-0} -gt 0 -o "${LINT_CHECK:-1}" == "1" ]; then
   test_flake8
-  sts=$?
-  if [ $sts -eq 0 ]; then
-    test_pylint
-    sts=$?
-  fi
+  sts_flake8=$?
+  test_pylint
+  sts_pylint=$?
+  do_summary "$sts_flake8" "$sts_pylint"
+  sts=$(($sts_flake8 || $sts_pylint))
 fi
 if [ $opt_verbose -gt 0 ]; then
   echo "if [ \${opt_regr:-0} -gt 0 -o \"\$LINT_CHECK\" != \"1\" ]; then  #($opt_regr,$LINT_CHECK)$sts"
 fi
 if [ ${opt_regr:-0} -gt 0 -o "$LINT_CHECK" != "1" ]; then
-  if [ $sts -eq 0 ]; then
+  if [ $sts -eq $STS_SUCCESS ]; then
     pkgname=$(basename $PKGPATH)
     # if [ $opt_verbose -gt 0 ]; then
     #   echo "run_regression_test $pkgname"
