[IMP] test last upgrade

diff --git a/maintainer-quality-tools/_travis/travis_run_pypi_tests b/maintainer-quality-tools/_travis/travis_run_pypi_tests
--- a/maintainer-quality-tools/_travis/travis_run_pypi_tests
+++ b/maintainer-quality-tools/_travis/travis_run_pypi_tests
@@ -38,7 +38,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.2.33
+__version__=0.2.2.35
 
 
 travis_test_bash() {
@@ -123,7 +123,6 @@ please_test_pylint() {
       fi
       IFS="/" read -a REPO <<< "${ODOO_REPO}"
       export PATH=${PATH}:${PWD}/../${REPO[1]}-${VERSION}/openerp
-      #run pylint command
       run_traced "pylint --rcfile=$pylint_rcfile ${MODULES_TO_TEST}"
       sts=$?
     fi
@@ -143,12 +142,11 @@ run_regression_test() {
       COVERAGE_PROCESS_START=$(readlink -f .coveragerc)
       if [ ! -f $COVERAGE_PROCESS_START ]; then
         cat <<EOF >$COVERAGE_PROCESS_START
-# Config file .coveragerc 2019-07-19
-
+# Config file .coveragerc 2019-08-22
 [report]
 include =
-    */${TRAVIS_BUILD_DIR}/*
-    # *.py
+#    ${TRAVIS_BUILD_DIR}/*
+    *.py
 
 omit =
     */scenario/*
@@ -158,7 +156,10 @@ omit =
     *_example/*
     __main__.py
     setup.py
-    */lib*/python*/*
+    */site-packages/*
+    */lib/python*/*
+    */lib64/python*/*
+    */__init__.py
     */__openerp__.py
     */__manifest__.py
 # Regexes for lines to exclude from consideration
@@ -184,10 +185,16 @@ exclude_lines =
 
     # Ignore unit test failure
     return TEST_FAILED
-
 EOF
       fi
-      if [[ -f ./tests/all_tests && ${opt_pyth:-0} -eq 0 || ! -f ./tests/test_$PRJNAME.py ]]; then
+      if [ -f ./tests/all_tests.py ]; then
+        if [ ${opt_dprj:-0} -gt 0 ]; then
+          run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/all_tests.py"
+        else
+          run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START all_tests.py"
+        fi
+        sts=$?
+      elif [[ -f ./tests/all_tests && ${opt_pyth:-0} -eq 0 ]]; then
         if [ ${opt_dprj:-0} -gt 0 ]; then
           run_traced "./tests/all_tests $OPTS -1"
         else
@@ -202,8 +209,12 @@ EOF
         fi
         sts=$?
       else
-        elog "!????? Module test for $PRJNAME not found!??????"
-        sts=$STS_FAILED
+        if [ ${opt_dprj:-0} -gt 0 ]; then
+          run_traced "DEV_ENVIRONMENT=$PRJNAME $(which zerobug) -b"
+        else
+          run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME $(which zerobug) -b"
+        fi
+        sts=$?
       fi
       if [ ! -f .coverage ]; then
         echo "Result coverage file not found!"
@@ -231,6 +242,69 @@ do_test () {
     fi
     sts=$?
     return $sts
+}
+
+set_pythonpath() {
+# set_pythonpath(path file PIP)
+    local PYPATH="${1//,/ }"
+    PYPATH="${PYPATH//:/ }"
+    local FSITE=$2
+    local PIP=${3:-pip}
+    local pth PYLIB
+    if [[ -n "$PYPATH" || -n "$FSITE" ]]; then
+      PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
+      if [ -z "$PYLIB" ]; then
+        PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
+      fi
+    fi
+    if [ -n "$PYLIB" ]; then
+      if [[ -n "$PYPATH" ]]; then
+        if [ -f $PYLIB/sitecustomize.py ]; then
+          if grep -q "import sys" $PYLIB/sitecustomize.py; then
+            :
+          else
+            echo 'import sys' >> $PYLIB/sitecustomize.py
+          fi
+        else
+          echo 'import sys' > $PYLIB/sitecustomize.py
+        fi
+        for pth in $PYPATH; do
+          echo \"if '$pth' not in sys.path:    sys.path.insert(0, '$pth')\" >> $PYLIB/sitecustomize.py
+        done
+      fi
+      if [[ -n "$FSITE" && -f $FSITE ]]; then
+        if [ -f $PYLIB/sitecustomize.py ]; then
+          if grep -q "import sys" $PYLIB/sitecustomize.py; then
+            run_traced "tail $FSITE -n -1 >> $PYLIB/sitecustomize.py"
+          else
+            run_traced "cat $FSITE >> $PYLIB/sitecustomize.py"
+          fi
+        else
+          run_traced "cp $FSITE $PYLIB"
+        fi
+      fi
+    fi
+}
+
+check_pythonpath() {
+# check_pythonpath(path python)
+    local PYPATH="${1//,/ }"
+    PYPATH="${PYPATH//:/ }"
+    local PYTHON=${2:-python}
+    local PYVER=$(python --version 2>&1|grep -Eo "[0-9]+"|head -n1)
+    local pth PYLIB
+    for pth in $PYPATH; do
+      if [ "$PYVER" == "2" ]; then
+        echo -e "import sys\nfor x in sys.path:\n  print x,"|$PYTHON|grep -q " $pth "
+      else
+        echo -e "import sys\nfor x in sys.path:\n  print (x,end=' ')"|$PYTHON|grep -q " $pth "
+      fi
+      if [ $? -ne 0 ]; then
+        echo "Warning: sitecustomize.py without effect! Use PYTHONPATH method"
+        [ -n "$PYTHONPATH" ] && export PYTHONPATH=$PYTHONPATH:$pth
+        [ -z "$PYTHONPATH" ] && export PYTHONPATH=$pth
+      fi
+    done
 }
 
 
@@ -296,34 +370,40 @@ if [ "${LINT_CHECK:-1}" == "0" ]; then LINT_CHECK_DISABLED=1; else LINT_CHECK_DI
 if [ "${TESTS:-0}" == "1" ]; then TEST_CHECK_ENABLED=1; else TEST_CHECK_ENABLED=0; fi
 if [ -z "${TESTS}" ]; then TESTS_UNSPECIFIED=1; else TESTS_UNSPECIFIED=0; fi
 if [ "${TRANSIFEX_CHECK:-0}" == "1" ]; then TRANSIFEX_CHECK_ENABLED=1; else TRANSIFEX_CHECK_ENABLED=0; fi
-[[ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]] && PIP=pip3
-[[ ! "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]] && PIP=pip
-if [ -d $HOME/dev ]; then
-  [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME/dev/activate_tools\e[${PS_TXT_COLOR}m"
-  . $HOME/dev/activate_tools
-  PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
-  if [ -z "$PYLIB" ]; then
-    PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
-  fi
-  if [ -n "$PYLIB" ]; then
-     for pth in ${PYTHONPATH//:/ } $(readlink -e $TRAVIS_BUILD_DIR/..); do
-       if $(echo ":$PYTHONPATH:"|grep -qv ":$pth:" 2>/dev/null); then
-         [ ${opt_verbose:-0} -gt 0 ] && echo "Adding $pth in sys.path ..."
-         echo "if '$pth' not in sys.path:    sys.path.insert(0,'$pth')" >> $PYLIB/sitecustomize.py
-       fi
-     done
-     export PYTHONPATH=
-  fi
-  if [[ ! $TRAVIS_DEBUG_MODE =~ ^[01] ]]; then
-    if [ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]; then
-      echo -e "import sys\nprint('sys.path=%s' % sys.path)\n"|python3
-    else
-      echo -e "import sys\nprint 'sys.path=%s' % sys.path\n"|python
-    fi
-  fi
-else
-  echo "!! Directory $HOME/dev not found!"
-fi
+[[ ! "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]] && PIP=pip || PIP=pip3
+[[ ! "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]] && PYTHON=python || PYTHON=python3
+# if [ -d $HOME/dev ]; then
+#   [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME/dev/activate_tools\e[${PS_TXT_COLOR}m"
+#   . $HOME/dev/activate_tools
+#   PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
+#   if [ -z "$PYLIB" ]; then
+#     PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
+#   fi
+#   if [ -n "$PYLIB" ]; then
+#      for pth in ${PYTHONPATH//:/ } $(readlink -e $TRAVIS_BUILD_DIR/..); do
+#        if $(echo ":$PYTHONPATH:"|grep -qv ":$pth:" 2>/dev/null); then
+#          [ ${opt_verbose:-0} -gt 0 ] && echo "Adding $pth in sys.path ..."
+#          echo "if '$pth' not in sys.path:    sys.path.insert(0,'$pth')" >> $PYLIB/sitecustomize.py
+#        fi
+#      done
+#      export PYTHONPATH=
+#   fi
+#   if [[ ! $TRAVIS_DEBUG_MODE =~ ^[012] ]]; then
+#     if [ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]; then
+#       echo -e "import sys\nprint('sys.path=%s' % sys.path)\n"|python3
+#     else
+#       echo -e "import sys\nprint 'sys.path=%s' % sys.path\n"|python
+#     fi
+#   fi
+# else
+#   echo "!! Directory $HOME/dev not found!"
+# fi
+pth=
+for p in $(readlink -e $TRAVIS_BUILD_DIR/..); do pth=$p:$pth; done
+pth=${pth:0: -1}
+set_pythonpath "$pth" "" $PIP
+check_pythonpath "$pth" $PYTHON
+
 if [ $opt_verbose -gt 0 ]; then
   echo -e "\e[${PS_HDR3_COLOR}mPYTHONPATH=$PYTHONPATH\e[${PS_TXT_COLOR}m"
   echo -e "\e[${PS_HDR3_COLOR}mBASH_CHECK_ENABLED=$BASH_CHECK_ENABLED LINT_CHECK_ENABLED=$LINT_CHECK_ENABLED $0 $__version__\e[${PS_TXT_COLOR}m"
