[IMP] Enhancements

diff --git a/maintainer-quality-tools/_travis/travis_run_pypi_tests b/maintainer-quality-tools/_travis/travis_run_pypi_tests
--- a/maintainer-quality-tools/_travis/travis_run_pypi_tests
+++ b/maintainer-quality-tools/_travis/travis_run_pypi_tests
@@ -31,7 +31,7 @@ if [ -z "$TRAVISLIBDIR" ]; then
 fi
 . $TRAVISLIBDIR
 
-__version__=0.2.2.47
+__version__=0.2.2.48
 
 
 travis_test_bash() {
@@ -126,15 +126,15 @@ run_regression_test() {
     local x
     echo "======== Running regression_test ========"
     if [ ${opt_dry_run:-0} -eq 0 ]; then
-      if [ "$TRAVIS_DEBUG_MODE" != "0" ]; then
-        local OPTS=$(inherits_travis_opts "n" "T")
-      else
-        local OPTS=$(inherits_travis_opts "" "T")
-      fi
-      run_traced "COVERAGE_PROCESS_START=$(readlink -f .coveragerc)"
-      COVERAGE_PROCESS_START=$(readlink -f .coveragerc)
-      if [ ! -f $COVERAGE_PROCESS_START ]; then
-        cat <<EOF >$COVERAGE_PROCESS_START
+        if [ "$TRAVIS_DEBUG_MODE" != "0" ]; then
+            local OPTS=$(inherits_travis_opts "n" "T")
+        else
+            local OPTS=$(inherits_travis_opts "" "T")
+        fi
+        run_traced "COVERAGE_PROCESS_START=$(readlink -f .coveragerc)"
+        COVERAGE_PROCESS_START=$(readlink -f .coveragerc)
+        if [ ! -f $COVERAGE_PROCESS_START ]; then
+            cat << EOF > $COVERAGE_PROCESS_START
 # Config file .coveragerc 2019-08-22
 [report]
 include =
@@ -179,44 +179,49 @@ exclude_lines =
     # Ignore unit test failure
     return TEST_FAILED
 EOF
-      fi
-      if [ -f ./tests/all_tests.py ]; then
-        if [ ${opt_dprj:-0} -gt 0 ]; then
-          run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/all_tests.py"
-        else
-          run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START all_tests.py"
         fi
-        sts=$?
-      elif [[ -f ./tests/all_tests && ${opt_pyth:-0} -eq 0 ]]; then
-        if [ ${opt_dprj:-0} -gt 0 ]; then
-          run_traced "./tests/all_tests $OPTS -1"
+        if [ -f ./tests/all_tests.py ]; then
+            if [ ${opt_dprj:-0} -gt 0 ]; then
+                run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/all_tests.py"
+            else
+                run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START all_tests.py"
+            fi
+            sts=$?
+        elif [[ -f ./tests/all_tests && ${opt_pyth:-0} -eq 0 ]]; then
+            if [ ${opt_dprj:-0} -gt 0 ]; then
+                run_traced "./tests/all_tests $OPTS -1"
+            else
+                run_traced "cd ./tests; ./all_tests $OPTS -1"
+            fi
+            sts=$?
+        elif [ -f ./tests/test_$PRJNAME.py ]; then
+            if [ ${opt_dprj:-0} -gt 0 ]; then
+                run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/test_$PRJNAME.py"
+            else
+                run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START test_$PRJNAME.py"
+            fi
+            sts=$?
         else
-          run_traced "cd ./tests; ./all_tests $OPTS -1"
+            if [ ${opt_dprj:-0} -gt 0 ]; then
+                run_traced "DEV_ENVIRONMENT=$PRJNAME $(which zerobug) -b"
+            else
+                run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME $(which zerobug) -b"
+            fi
+            sts=$?
         fi
-        sts=$?
-      elif [ -f ./tests/test_$PRJNAME.py ]; then
-        if [ ${opt_dprj:-0} -gt 0 ]; then
-          run_traced "DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START ./tests/test_$PRJNAME.py"
-        else
-          run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME coverage run -a --rcfile $COVERAGE_PROCESS_START test_$PRJNAME.py"
+        $(ls ./pytest* &> /dev/null) && cd ..
+        if $(ls ./tests/pytest* &> /dev/null); then
+            run_traced "coverage run -m pytest -v ./tests/pytest*"
+            sts=$?
         fi
-        sts=$?
-      else
-        if [ ${opt_dprj:-0} -gt 0 ]; then
-          run_traced "DEV_ENVIRONMENT=$PRJNAME $(which zerobug) -b"
-        else
-          run_traced "cd ./tests; DEV_ENVIRONMENT=$PRJNAME $(which zerobug) -b"
+        if [ ! -f .coverage ]; then
+            echo "Result coverage file not found!"
+        elif [ ${opt_dprj:-0} -eq 0 ]; then
+            run_traced "mv .coverage .."
+            run_traced "cd .."
         fi
-        sts=$?
-      fi
-      if [ ! -f .coverage ]; then
-        echo "Result coverage file not found!"
-      elif [ ${opt_dprj:-0} -eq 0 ]; then
-        run_traced "mv .coverage .."
-        run_traced "cd .."
-      fi
     else
-      sts=$STS_SUCCESS
+        sts=$STS_SUCCESS
     fi
     return $sts
 }
@@ -245,43 +250,41 @@ set_pythonpath() {
     local PIP=${3:-pip}
     local pth PYLIB x
     if [[ -n "$PYPATH" || -n "$FSITE" ]]; then
-      PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
-      if [ -z "$PYLIB" ]; then
-        PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
-      fi
+        PYLIB=$(dirname $($PIP --version | grep -Eo "from [^ ]+" | awk '{print $2}'))
+        if [ -z "$PYLIB" ]; then
+            PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
+        fi
     fi
     if [ -n "$PYLIB" ]; then
-      if [[ -n "$PYPATH" ]]; then
         if [ -f $PYLIB/sitecustomize.py ]; then
-          if grep -q "import sys" $PYLIB/sitecustomize.py; then
-            :
-          else
-            echo 'import sys' >> $PYLIB/sitecustomize.py
-          fi
+            if grep -q "import sys" $PYLIB/sitecustomize.py; then
+                :
+            else
+                echo 'import sys' >> $PYLIB/sitecustomize.py
+            fi
         else
-          echo 'import sys' > $PYLIB/sitecustomize.py
+            echo 'import sys' > $PYLIB/sitecustomize.py
         fi
         for pth in $PYPATH; do
-          echo "if '$pth' not in sys.path:    sys.path.insert(0, '$pth')" >> $PYLIB/sitecustomize.py
-          if echo ":$PYTHONPATH":|grep -q ":$pth:"; then
-            x=${PYTHONPATH//$pth/}
-            export $PYTHONPATH=${x//::/:}
-          fi
+            echo "if '$pth' not in sys.path:    sys.path.insert(0, '$pth')" >> $PYLIB/sitecustomize.py
+            if echo ":$PYTHONPATH": | grep -q ":$pth:"; then
+                x=${PYTHONPATH//$pth/}
+                export $PYTHONPATH = ${x//::/:}
+            fi
         done
-        [ "${PYTHONPATH:0:1}" == ":" ] && export $PYTHONPATH=${PYTHONPATH:1}
-      fi
-      if [[ -n "$FSITE" && -f $FSITE ]]; then
-        if [ -f $PYLIB/sitecustomize.py ]; then
-          if grep -q "import sys" $PYLIB/sitecustomize.py; then
-            run_traced "tail $FSITE -n -1 >> $PYLIB/sitecustomize.py"
-          else
-            run_traced "cat $FSITE >> $PYLIB/sitecustomize.py"
-          fi
-        else
-          run_traced "cp $FSITE $PYLIB"
+        [ "${PYTHONPATH:0:1}" == ":" ] && export $PYTHONPATH = ${PYTHONPATH:1}
+        if [[ -n "$FSITE" && -f $FSITE ]]; then
+            if [ -f $PYLIB/sitecustomize.py ]; then
+                if grep -q "import sys" $PYLIB/sitecustomize.py; then
+                    run_traced "tail $FSITE -n -1 >> $PYLIB/sitecustomize.py"
+                else
+                    run_traced "cat $FSITE >> $PYLIB/sitecustomize.py"
+                fi
+            else
+                run_traced "cp $FSITE $PYLIB"
+            fi
+            export PYTHONPATH=
         fi
-        export PYTHONPATH=
-      fi
     fi
 }
 
@@ -310,8 +313,8 @@ install_n_activate_tools() {
     if [ -d $HOME/tools ]; then
       [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ cd $HOME/tools\e[${PS_TXT_COLOR}m"
       pushd $HOME/tools > /dev/null
-      [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && x=-p
-      [ ${TRAVIS_DEBUG_MODE:-0} -le 2 ] && x=-qp
+      [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && x=-op
+      [ ${TRAVIS_DEBUG_MODE:-0} -le 2 ] && x=-qop
       run_traced "./install_tools.sh $x"
       [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME/dev/activate_tools\e[${PS_TXT_COLOR}m"
       . $HOME/dev/activate_tools
diff --git a/python_plus/venv_mgr b/python_plus/venv_mgr
--- a/python_plus/venv_mgr
+++ b/python_plus/venv_mgr
@@ -26,7 +26,7 @@ if [ -z "$Z0LIBDIR" ]; then
   exit 2
 fi
 
-__version__=0.1.3.4
+__version__=0.1.3.6
 DEV_PKGS="coveralls codecov flake8 pycodestyle pylint"
 SUP_PKGS="future python_plus"
 SECURE_PKGS="urllib3[secure] cryptography pyOpenSSL idna certifi asn1crypto pyasn1"
@@ -34,6 +34,7 @@ FLT_PKGS="(jwt|FOO)"
 ERROR_PKGS=""
 LOCAL_PKGS="(clodoo|odoo_score|os0|python_plus|z0bug_odoo|z0lib|zerobug)"
 XPKGS_RE=""
+
 
 cd_venv() {
 # cd_venv(VENV -q)
@@ -46,6 +47,7 @@ cd_venv() {
     fi
 }
 
+
 pop_cd() {
     if [ $DO_POP -ne 0 ]; then
         [[ "$1" == "-q" ]] || echo "$FLAG popd >/dev/null"
@@ -56,13 +58,15 @@ pop_cd() {
     fi
 }
 
+
 do_activate() {
     if [[ -z "$VIRTUAL_ENV" ]]; then
-        [[ "$1" == "-q" ]] || echo "$FLAG . bin/activate"
+        [[ "$1" == "-q" ]] || echo "$FLAG source bin/activate"
         . bin/activate
-        do_deact=1
+        DO_DEACT=1
     fi
 }
+
 
 do_deactivate() {
     if [ $DO_DEACT -ne 0 ]; then
@@ -71,6 +75,7 @@ do_deactivate() {
         DO_DEACT=0
     fi
 }
+
 
 bin_install() {
 #pip_install pkg
@@ -126,6 +131,7 @@ bin_install() {
     fi
 }
 
+
 bin_install_1() {
 # bin_install_1(popt)
     local pkg popt=$1
@@ -134,10 +140,11 @@ bin_install_1() {
     if [[ -n "$opt_bins" ]]; then
         [ $opt_verbose -gt 0 ] && echo -e "\e[1m.1 - Analyzing $opt_bins\e[0m"
         for pkg in $binreq; do
-            [[ "[[:space:]]$BINPKGS[[:space:]] =~ [[:space:]]$pkg[0-9.<=>]*[[:space:]]" ]] && bin_install $pkg $popt
+            [[ -n "$BINPKGS" && "[[:space:]]$BINPKGS[[:space:]] =~ [[:space:]]$pkg[0-9.<=>]*[[:space:]]" ]] && bin_install $pkg $popt
         done
     fi
 }
+
 
 pip_install() {
 #pip_install pkg
@@ -146,8 +153,8 @@ pip_install() {
     local srcdir
     [[ $pkg =~ (psycopg2).* ]] && pkg="psycopg2-binary>=2.0.0"
     if [[ -z "$XPKGS_RE" || ! $pkg =~ ($XPKGS_RE) ]]; then
-        if [[ "[[:space:]]$BINPKGS[[:space:]] =~ [[:space:]]$pkg[0-9.<=>]*[[:space:]]" ]]; then
-            bin_install $pkg
+        if [[ -n "$BINPKGS" && "[[:space:]]$BINPKGS[[:space:]] =~ [[:space:]]$pkg[0-9.<=>]*[[:space:]]" ]]; then
+            bin_install $*
         elif [[ $pkg =~ $LOCAL_PKGS ]] && [ $opt_debug -ne 0 ]; then
             [[ -d $pypath/$pkg && ! -L $pypath/$pkg ]] && rm -fR $pypath/$pkg
             srcdir=$(readlink $pypath/pkg)
@@ -171,6 +178,7 @@ pip_install() {
     fi
 }
 
+
 pip_install_1() {
 # pip_install_1(popt)
     local pkg popt=$1
@@ -180,6 +188,7 @@ pip_install_1() {
     done
 }
 
+
 pip_install_2() {
 # pip_install_2(popt)
     local pkg popt=$1
@@ -188,6 +197,7 @@ pip_install_2() {
         pip_install $pkg $popt
     done
 }
+
 
 pip_install_req() {
 # pip_install_req(popt)
@@ -208,6 +218,7 @@ pip_install_req() {
         done
     done
 }
+
 
 check_package() {
 # check_package(pkg cmd)
@@ -241,6 +252,7 @@ check_package() {
     fi
 }
 
+
 pip_check_1() {
 # pip_check_1(cmd)
     local pkg cmd=$1
@@ -262,6 +274,7 @@ pip_check_2() {
     done
 }
 
+
 pip_check_req() {
 # pip_check_req(cmd)
     local f fn pkg cmd=$1 flist
@@ -280,27 +293,30 @@ pip_check_req() {
     done
 }
 
+
 package_debug() {
 # package_debug(VENV)
     local VENV=$1
     local p pkgdir
+    local pkgs="${LOCAL_PKGS//| }"
+    pkgs="${pkgs:1: -1}"
     pkgdir=$VENV/lib/python$opt_pyver/site-packages
     if [ $opt_debug -ne 0 -a -d $HOME/tools/ ]; then
-        for p in clodoo odoo_score os0 python_plus z0bug_odoo z0lib zerobug; do
+        for p in $pkgs; do
             if [[ -d $pkgdir/$p && ! -L $pkgdir/$p ]]; then
                 run_traced "rm -fR $pkgdir/$p"
                 run_traced "ln -s $HOME/tools/$p $pkgdir"
             fi
         done
     else
-        for p in clodoo odoo_score os0 python_plus z0bug_odoo z0lib zerobug; do
+        for p in $pkgs; do
             if [[ -L $pkgdir/$p ]]; then
                 run_traced "rm -f $pkgdir/$p"
-                # run_traced "pip install $p"
             fi
         done
     fi
 }
+
 
 custom_env() {
 # custom_env(VENV pyver)
@@ -335,9 +351,9 @@ custom_env() {
     elif [[ -d $PWD/.local/lib/python$2/site-packages ]]; then
       echo -e "import site\nsite.addsitedir('$PWD/.local/lib/python$2/site-packages')\n">$PWD/lib/python$2/site-packages/sitecustomize.py
     fi
-    # popd >/dev/null
     pop_cd
 }
+
 
 set_pyver_files() {
     if [ -n "$opt_pyver" ]; then
@@ -349,6 +365,7 @@ set_pyver_files() {
     fi
     PIPVER=$($PIP --version|grep -Eo [0-9]+|head -n1)
 }
+
 
 venv_mgr_check_src_path() {
 # venv_mgr_check_src_path(VENV create)
@@ -374,17 +391,21 @@ venv_mgr_check_src_path() {
         exit 1
     fi
     opt_pyver=$($PYTHON --version 2>&1|grep -Eo "[0-9]\.[0-9]")
+    FUTURE=$(pip show future 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+    Z0LIB=$(pip show z0lib 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+    OS0=$(pip show os0 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
     do_deactivate "-q"
     pop_cd "-q"
     [ $opt_verbose -gt 0 ] && echo "### Python version $opt_pyver ... ###"
     set_pyver_files
 }
 
+
 venv_mgr_check_oever() {
 #venv_mgr_check_oever action
     local p x
     if [[ -z "$opt_oever" && ! $1 =~ (help|create) ]]; then
-        x=$(find -L $p2 -not -path "*/__to_remove/*" -name release.py)
+        x=$(find -L $p2 -not -path "*/__to_remove/*" -not -path "*/lib/*" -not -path "*/lib64/*" -name release.py)
         if [[ -n "$x" ]]; then
             p=$(dirname $x)
             cd_venv $p -q
@@ -395,8 +416,15 @@ venv_mgr_check_oever() {
     fi
     if [[ ! $1 =~ (help|create) ]]; then
         [ $opt_verbose -gt 0 ] && echo "### Odoo version $opt_oever ...  ###"
+        [[ -z "$FUTURE" ]] && pip_install future -q
+        FUTURE=$(pip show future 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+        [[ -z "$Z0LIB" ]] && pip_install z0lib -q
+        Z0LIB=$(pip show z0lib 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+        [[ -z "$OS0" ]] && pip_install os0 -q
+        OS0=$(pip show os0 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
     fi
 }
+
 
 venv_mgr_test() {
 #venv_mgr_test(VENV)
@@ -422,18 +450,16 @@ venv_mgr_test() {
         x=$(readlink -e $(which $f 2>/dev/null) 2>/dev/null)
         [[ -z "$x" ]] && echo "Corrupted VME: file $f not found!!"
         [[ -z "$x" ]] && continue
-        [[ -n "$x" && ! $x =~ ^$VENV ]] && echo "Incomplete VME: file $x outside virtual env"
-        [[ -n "$x" && ! $x =~ ^$VENV ]] && continue
-        [ "$f" != "pylint" -a $opt_verbose -gt 0 ] && eval $f --version
-        [ "$f" == "pylint" -a $opt_verbose -gt 0 ] && eval $f --version 2>/dev/null
+        [[ -n "$x" && ! $x =~ ^$VENV ]] && echo "VME system-package: file $x is outside of virtual env"
     done
     do_deactivate "-q"
     pop_cd "-q"
 }
 
+
 do_venv_mgr() {
 # do_venv_mgr {cp|mv|merge|reset|test} VENV NEW_VENV
-    local d f mime VENV V sitecustom XPKGS_RE popt
+    local d f mime VENV V sitecustom popt x
     local cmd=$1
     [ -z "$2" ] && VENV=$(readlink -e ./)
     [ -n "$2" ] && VENV=$(readlink -e $2)
@@ -451,14 +477,14 @@ do_venv_mgr() {
     [[ -n "$opt_oever" ]] && OEPKGS=$(list_requirements.py -s" " -BPRT -t python -q -b $opt_oever -y $opt_pyver)
     [[ -z "$opt_oever" ]] && OEPKGS=$(list_requirements.py -s" " -PT -t python -q -y $opt_pyver)
     if [[ -z "$VENV" || -z "$VENV_TGT" ]]; then
-      echo "Missed parameters!"
-      echo "use: venv_mgr ${CMDS// /|} VENV NEW_VENV"
-      exit 1
+        echo "Missed parameters!"
+        echo "use: venv_mgr ${CMDS// /|} VENV NEW_VENV"
+        exit 1
     fi
     if [[ "$VENV" == "$VENV_TGT" && ! $cmd =~ (amend|check|reset|test) ]]; then
-      echo "Source and destination directories are the same!"
-      echo "use: venv_mgr ${CMDS// /|} VENV NEW_VENV"
-      exit 1
+        echo "Source and destination directories are the same!"
+        echo "use: venv_mgr ${CMDS// /|} VENV NEW_VENV"
+        exit 1
     fi
     if [[ $cmd =~ (amend|check|reset|test) ]]; then
       V=$VENV
@@ -474,16 +500,17 @@ do_venv_mgr() {
       run_traced "cp -r $VENV $VENV_TGT"
       V=$VENV_TGT
     elif [[ "$cmd" == "merge" ]]; then
-      if [[ ! -d $VENV_TGT  || ! -d $VENV_TGT/bin || ! -f $VENV_TGT/bin/activate ]]; then
-        echo "Invalid destination virtual env $VENV_TGT!"
-        exit 1
-      fi
-      for d in bin include lib lib64 .local; do
-        if [ -d "$VENV/$d" ]; then
-          run_traced "rsync -a $VENV/$d/ $VENV_TGT/$d/"
+        if [[ ! -d $VENV_TGT || ! -d $VENV_TGT/bin || ! -f $VENV_TGT/bin/activate ]]; then
+            echo "Invalid destination virtual env $VENV_TGT!"
+            exit 1
         fi
-      done
-      V=$VENV_TGT
+        for d in bin include lib lib64 .local; do
+            if [ -d "$VENV/$d" ]; then
+                [ $opt_verbose -gt 1 ] && run_traced "rsync -a $VENV/$d/ $VENV_TGT/$d/"
+                [ $opt_verbose -eq 0 ] && run_traced "rsync -aq $VENV/$d/ $VENV_TGT/$d/"
+            fi
+        done
+        V=$VENV_TGT
     else
       if [[ -d $VENV_TGT ]]; then
         echo "Destination virtual env $VENV_TGT already exists!"
@@ -502,7 +529,7 @@ do_venv_mgr() {
         done
     fi
     if [[ ! "$cmd" == "test" ]]; then
-        cd_venv $VENV
+        cd_venv $V
         do_activate
         if [ $opt_dry_run -eq 0  -a -L ./lib64 ]; then
             rm -f ./lib64
@@ -532,16 +559,24 @@ do_venv_mgr() {
                 [ $opt_alone -eq 0 ] && run_traced "sed -i -e 's|export HOME=\$(grep|# export HOME=\$(grep|' $PWD/bin/activate"
             fi
             if [ $opt_dry_run -eq 0 ]; then
-                sitecustom=$PWD/lib/python$opt_pyver/site-packages/sitecustomize.py
-                echo "import sys">$sitecustom
                 if [ $opt_spkg -ne 0 ]; then
-                  if [[ -d $PWD/.local/lib/python$opt_pyver/site-packages ]]; then
-                    echo -e "import site\nif '$VENV_TGT/.local/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('$VENV_TGT/.local/lib/python$opt_pyver/site-packages')\nif '/usr/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('/usr/lib/python$opt_pyver/site-packages')\nif '/usr/lib64/python$opt_pyver/site-packages' not in sys.path:     site.addsitedir('/usr/lib64/python$opt_pyver/site-packages')\n">>$sitecustom
-                  else
-                    echo -e "import site\nif '/usr/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('/usr/lib/python$opt_pyver/site-packages')\nif '/usr/lib64/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('/usr/lib64/python$opt_pyver/site-packages')\n">>$sitecustom
-                  fi
+                    if [[ -d $PWD/.local/lib/python$opt_pyver/site-packages ]]; then
+                        sitecustom=$PWD/.local/lib/python$opt_pyver/site-packages/sitecustomize.py
+                        echo "import sys" > $sitecustom
+                        echo -e "import site\nif '$VENV_TGT/.local/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('$VENV_TGT/.local/lib/python$opt_pyver/site-packages')\nif '/usr/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('/usr/lib/python$opt_pyver/site-packages')\nif '/usr/lib64/python$opt_pyver/site-packages' not in sys.path:     site.addsitedir('/usr/lib64/python$opt_pyver/site-packages')\n" >> $sitecustom
+                    else
+                        sitecustom=$PWD/lib/python$opt_pyver/site-packages/sitecustomize.py
+                        echo "import sys" > $sitecustom
+                        echo -e "import site\nif '/usr/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('/usr/lib/python$opt_pyver/site-packages')\nif '/usr/lib64/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('/usr/lib64/python$opt_pyver/site-packages')\n" >> $sitecustom
+                    fi
                 elif [[ -d $PWD/.local/lib/python$opt_pyver/site-packages ]]; then
-                  echo -e "import site\nif '$VENV_TGT/.local/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('$VENV_TGT/.local/lib/python$opt_pyver/site-packages')\n">>$sitecustom
+                    sitecustom=$PWD/.local/lib/python$opt_pyver/site-packages/sitecustomize.py
+                    echo "import sys" > $sitecustom
+                    echo -e "import site\nif '$VENV_TGT/.local/lib/python$opt_pyver/site-packages' not in sys.path:    site.addsitedir('$VENV_TGT/.local/lib/python$opt_pyver/site-packages')\n" >> $sitecustom
+                fi
+                if [[ -n "$sitecustom" ]]; then
+                    x=$sitecustom; while [[ ! "$x" == "/" && ! "$(basename $x)" == "lib" ]]; do x=$(dirname $x); done; x=$(dirname $x); x=$x/bin
+                    [[ ! :$PATH: =~ :$x: ]] && export PATH=$x:$PATH
                 fi
             fi
         fi
@@ -554,6 +589,7 @@ do_venv_mgr() {
     fi
     venv_mgr_test $V
 }
+
 
 do_venv_create() {
 # do_venv_create VENV
@@ -601,6 +637,7 @@ do_venv_create() {
     venv_mgr_test $VENV
 }
 
+
 do_venv_exec() {
 # do_venv_exec VENV cmd
     local d f mime VENV V sitecustom
@@ -613,6 +650,7 @@ do_venv_exec() {
     do_deactivate
     pop_cd
 }
+
 
 do_venv_pip() {
 # do_venv_pip VENV action pkg
@@ -635,10 +673,23 @@ do_venv_pip() {
 }
 
 
+check_local_pkgs() {
+    local f VENV
+    [[ -z "$1" ]] && VENV=$(readlink -e ./)
+    [[ -n "$1" ]] && VENV=$(readlink -e $1)
+    cd_venv $VENV -q
+    do_activate -q
+    FUTURE=$(pip show future 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+    Z0LIB=$(pip show z0lib 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+    OS0=$(pip show os0 2>/dev/null|grep "Version"|grep -Eo "[0-9.]+")
+    do_deactivate -q
+    pop_cd -q
+}
+
 OPTOPTS=(h        a        B         D       f         k        I         n           O         p         q           r         s        V           v)
 OPTDEST=(opt_help opt_bins opt_debug opt_dev opt_force opt_keep opt_alone opt_dry_run opt_oever opt_pyver opt_verbose opt_rfile opt_spkg opt_version opt_verbose)
 OPTACTI=(1        "="      "+"       1       1         1        1         1           "="       "="       0           "="       1        "*>"        "+")
-OPTDEFL=(0        ""        0         0       0         0        0         0           ""        ""        -1          ""        0        ""          -1)
+OPTDEFL=(0        ""       0         0       0         0        0         0           ""        ""        -1          ""        0        ""          -1)
 OPTMETA=("help"   "list"   ""        ""      ""        ""       ""        ""          "ver"     "pyver"   ""          "file"    ""       "version"   "verbose")
 OPTHELP=("this help"\
  "bin packages to install (def=wkhtmltopdf,lessc)"\
@@ -672,34 +723,51 @@ elif [[ $p2 =~ $REXACT ]]; then
     p2=$p1
 fi
 if [ -z "$action" ]; then
-  opt_help=1
+    opt_help=1
 fi
-DO_POP=0
-DO_DEACT=0
 # It runs inside travis test environment too
 [ -z "$opt_pyver" -a -n "$TRAVIS_PYTHON_VERSION" ] && opt_pyver=$TRAVIS_PYTHON_VERSION
 [ $opt_verbose -eq -1 ] && opt_verbose=1
 if [ $opt_help -gt 0 ]; then
-  print_help "Manage virtual environment\naction may be: $ACTIONS"\
-  "(C) 2018-2020 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
-  exit $STS_SUCCESS
+    print_help "Manage virtual environment\naction may be: $ACTIONS" "(C) 2018-2020 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+    exit $STS_SUCCESS
 fi
+p1=
+if [[ -d "$p2" ]]; then
+    p1=$(readlink -e $p2)
+    unset p2
+fi
+[[ -z "$p1" ]] && p1=$(readlink -e ./)
+[[ ! -f $p1/bin/activate && -f $HOME/bin/activate ]] && p1=$(readlink -e $HOME)
+if [[ -z "$p2" ]]; then
+    p2=$p1
+else
+    p9="$p8"; p8="$p7"; p7="$p6"; p6="$p5"; p5="$p4"; p4="$p3"; p3="$p2"; p2="$p1"
+fi
+unset p1
+DO_POP=0
+DO_DEACT=0
 export PYTHONWARNINGS="ignore"
 SAVED_HOME=$HOME
 [ $opt_debug -ne 0 -a -d $HOME/tools/ ] && PYTHONPATH=$HOME/tools/
 FLAG=">"
 [ $opt_dry_run -eq 0 ] && FLAG="\$"
+check_local_pkgs $p2
 [[ -n "$opt_pyver" ]] && set_pyver_files
 [[ -z "$opt_pyver" && ! $action  =~ (help|create) ]] && venv_mgr_check_src_path $p2
 venv_mgr_check_oever $action
-[ $opt_dev -eq 0 ] && x=$(find ${p2}lib -name pylint -o -name unittest2 -o -name coveralls|wc -l)
+[ $opt_dev -eq 0 -a -d "$p2" ] && x=$(find ${p2}/lib -name pylint -o -name unittest2 -o -name coverage -o -name flake8|wc -l)
 [ $opt_dev -eq 0 -a ${x:-0} -gt 1 ] && opt_dev=1
-if [ $opt_dev -eq 0 ]; then
-    DEV_PKGS=$(list_requirements.py -qs" " -B -t python)
+if [[ -z "$FUTURE" || -z "$Z0LIB" || -z "$OS0" ]]; then
+    DEV_PKGS="future"
+elif [ $opt_dev -eq 0 ]; then
+    [[ -n "$opt_pyver" ]] && DEV_PKGS=$(list_requirements.py -qs" " -B -t python -y $opt_pyver)
+    [[ -z "$opt_pyver" ]] && DEV_PKGS=$(list_requirements.py -qs" " -B -t python)
 elif [[ -n "$opt_oever" ]]; then
     DEV_PKGS="$(list_requirements.py -qs" " -TBP -t python -b$opt_oever)"
 else
-    DEV_PKGS="$(list_requirements.py -qs" " -TBP -t python)"
+    [[ -n "$opt_pyver" ]] && DEV_PKGS=$(list_requirements.py -qs" " -TBP -t python -y $opt_pyver)
+    [[ -z "$opt_pyver" ]] && DEV_PKGS=$(list_requirements.py -qs" " -TBP -t python)
 fi
 if [ "$action" == "help" ]; then
     man $TDIR/$THIS.man
diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -35,7 +35,7 @@ fi
 
 opts_travis() {
 #opts_travis(git-org/pkgname)
-    local x
+    local b x
     REMOTEREPO=
     PRJNAME=
     PRJPATH=
@@ -43,25 +43,34 @@ opts_travis() {
     PKGPATH=
     REPOSNAME=
     if [ -n "$1" ]; then
-      IFS="/" read REMOTEREPO x <<< "$1"
+        IFS="/" read REMOTEREPO x <<< "$1"
     fi
     [ -z "$REMOTEREPO" ] && REMOTEREPO="local"
     build_pypi_param ALL $1
     export TRAVIS_REPO_SLUG=$REMOTEREPO/$PKGNAME
     if [ -n "$opt_conf" -a -f "$opt_conf" ]; then
-      TCONF=$opt_conf
+        TCONF=$opt_conf
+    elif [[ -f $TDIR/.travis.conf ]]; then
+        TCONF=$TDIR/.travis.conf
     else
-      TCONF=$TDIR/.travis.conf
+        b=""
+        x=$TDIR
+        while [[ ! "$b" == "pypi" && ! "b" == "tools" && ! "$x" == "$HOME" ]]; do
+            x=$(readlink -e $x/..)
+            b=$(basename $x)
+        done
+        TCONF=$x/travis_emulator/.travis.conf
+        [[ -f $x/travis_emulator/travis_emulator/.travis.conf ]] && TCONF=$x/travis_emulator/travis_emulator/.travis.conf
     fi
     DIST_CONF=$(readlink -f $PKGPATH/conf/.local_dist_pkg.conf)
     if [ -z "$DIST_CONF" ]; then
-      DIST_CONF=$(readlink -f $PKGPATH/../conf/.local_dist_pkg.conf)
+        DIST_CONF=$(readlink -f $PKGPATH/../conf/.local_dist_pkg.conf)
     fi
     if [ "$DEV_ENVIRONMENT" == "$THIS" ]; then
-      test_mode=1
+        test_mode=1
     fi
     if [ ${test_mode:-0} -gt 0 ]; then
-      opt_dry_run=1
+        opt_dry_run=1
     fi
 }
 
@@ -160,14 +169,15 @@ inherits_travis_opts() {
 }
 
 get_value_from_file() {
-# get_value_from_file(file value)
+# get_value_from_file(file value [sep])
     local x=$(basename $1)
-    local n r
+    local n r s=$3
+    [[ -z "$s" ]] && s="="
     if [ "$x" == "setup.py" ]; then
         if [ "$2" == "name" ]; then
-            r=$(grep "[^a-zA-Z0-9_]$2 *=" $1 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"', \r\n")
+            r=$(grep "[^a-zA-Z0-9_][\"']*$2[\"']* *$s" $1 2>/dev/null|awk -F"$s" '{print $2}'|tr -d "\"', \r\n")
         else
-            r=$(grep "^ *$2 *=" $1 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"'\r\n")
+            r=$(grep "^ *[\"']*$2[\"']* *$s" $1 2>/dev/null|awk -F"$s" '{print $2}'|tr -d "\"'\r\n")
             [ "${r: -1}" == "," ] && r="${r:0: -1}"
         fi
     fi
@@ -436,8 +446,8 @@ venv_mgr_test() {
     deactivate
 }
 
-venv_mgr() {
-# venv_mgr {chk|cp|mv|merge} VENV NEW_VENV
+_venv_mgr() {
+# _venv_mgr {chk|cp|mv|merge} VENV NEW_VENV
     local d f mime VENV VIRTUAL_ENV V sitecustom
     local cmd=$1
     [ -n "$2" ] && VENV=$(readlink -f $2)
@@ -445,12 +455,12 @@ venv_mgr() {
     [[ "$cmd" == "chk" ]] && VIRTUAL_ENV=$VENV
     if [[ -z "$VENV" || -z "$VIRTUAL_ENV" ]]; then
       echo "Missed parameters!"
-      echo "use: venv_mgr cp|mv|merge VENV NEW_VENV"
+      echo "use: _venv_mgr cp|mv|merge VENV NEW_VENV"
       exit 1
     fi
     if [[ "$VENV" == "$VIRTUAL_ENV" && ! "$cmd" == "chk" ]]; then
       echo "Source and destination directories are the same!"
-      echo "use: venv_mgr cp|mv|merge VENV NEW_VENV"
+      echo "use: _venv_mgr cp|mv|merge VENV NEW_VENV"
       exit 1
     fi
     if [[ ! -d $VENV  || ! -d $VENV/bin || ! -f $VENV/bin/activate ]]; then
@@ -552,14 +562,14 @@ custom_env() {
 }
 
 create_virtual_env() {
-    local f p x
+    local f p x VENVOPTS=-D
     local HOME_BRANCH=$HOME/$BRANCH
     export TRAVIS_BRANCH=$BRANCH
-    if [ $opt_py3 -ne 0 ]; then
-      local CURPYVER=$(python3 --version 2>&1|grep -Eo "[0-9]+\.[0-9]+")
-    else
-      local CURPYVER=$(python --version 2>&1|grep -Eo "[0-9]+\.[0-9]+")
-    fi
+    # if [ $opt_py3 -ne 0 ]; then
+    #   local CURPYVER=$(python3 --version 2>&1|grep -Eo "[0-9]+\.[0-9]+")
+    # else
+    #   local CURPYVER=$(python --version 2>&1|grep -Eo "[0-9]+\.[0-9]+")
+    # fi
     local sts=0
     local VER=${VERSION}
     [ -z "$VER" ] && VER="${TRAVIS_PYTHON_VERSION:0:1}"
@@ -567,58 +577,62 @@ create_virtual_env() {
     export TRAVIS_SAVED_HOME=$HOME
     export TRAVIS_HOME=$(readlink -f $HOME/VENV_$$)
     if [ "$TRAVIS_SAVED_HOME" == "/home/travis" ]; then
-      export TRAVIS=true
+        export TRAVIS=true
     elif [ $opt_full -ne 0 ]; then
-      export TRAVIS=emulate
+        export TRAVIS=emulate
     else
-      export TRAVIS=false
+        export TRAVIS=false
     fi
-    SET_GLOBAL_PYVER=$(get_cfg_value "" "SET_GLOBAL_PYVER")
+    [[ -d $HOME/devel ]] && Z0DEV_DIR=$HOME/devel
+    [[ -d $HOME/dev ]] && Z0DEV_DIR=$HOME/dev
+    if [[ -z "$Z0DEV_DIR" ]]; then
+        echo "Zeroincombenze(R) tools not found!"
+        exit 1
+    fi
+    # SET_GLOBAL_PYVER=$(get_cfg_value "" "SET_GLOBAL_PYVER")
     TRAVIS_ENVOPTS="$TRAVIS_ENVOPTS -p /usr/bin/python$TRAVIS_PYTHON_VERSION"
-    if [ ${opt_virt:-0} -eq 0 ]; then
-      mkdir -p $TRAVIS_HOME
-      cd $TRAVIS_HOME
-      export TRAVIS=false
-      export HOME=$TRAVIS_HOME
-    else
-      hash -r
-      echo "\$ virtualenv -q $TRAVIS_ENVOPTS $TRAVIS_HOME"
-      [ ${opt_dry_run:-0} -ne 0 ] || virtualenv -q $TRAVIS_ENVOPTS $TRAVIS_HOME
-      sts=$?
-      [ $sts -ne 0 ] && return
-      local SAVE_COLOR=$PS_RUN_COLOR
-      export PS_RUN_COLOR=$PS_HDR3_COLOR
-      echo -en "\e[${PS_RUN_COLOR}m"
-      if [ ${opt_cache:-0} -ne 0 -a -n "$TRAVIS_PYTHON_VERSION" ]; then
-          if [[ -d $TRAVIS_SAVED_HOME/VME/VME$BRANCH ]]; then
-              echo "# .. loading stored packages from VME$BRANCH ..."
-              run_traced "venv_mgr merge $TRAVIS_SAVED_HOME/VME/VME$BRANCH $TRAVIS_HOME -q"
-          elif [[ -d "$TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION" ]]; then
-              echo "# .. loading stored packages from VME$TRAVIS_PYTHON_VERSION ..."
-              run_traced "venv_mgr merge $TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION $TRAVIS_HOME -q"
-          fi
-      fi
-      source bin/activate
-      if [ -d $HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/ ]; then
-        export PYPI_CACHED=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
-      fi
-      export PS_RUN_COLOR=$SAVE_COLOR
+    [[ "$SYSTEM_SITE_PACKAGES" == "true" ]] && TRAVIS_ENVOPTS="$TRAVIS_ENVOPTS --system-site-packages"
+    [[ ! "$SYSTEM_SITE_PACKAGES" == "true" ]] && VENVOPTS="-DI"
+    HOME=$TRAVIS_HOME
+    hash -r
+    echo "\$ virtualenv -q $TRAVIS_ENVOPTS $TRAVIS_HOME"
+    [ ${opt_dry_run:-0} -ne 0 ] || virtualenv -q $TRAVIS_ENVOPTS $TRAVIS_HOME
+    sts=$?
+    [ $sts -ne 0 ] && return
+    local SAVE_COLOR=$PS_RUN_COLOR
+    export PS_RUN_COLOR=$PS_HDR3_COLOR
+    echo -en "\e[${PS_RUN_COLOR}m"
+    if [ ${opt_cache:-0} -ne 0 -a -n "$TRAVIS_PYTHON_VERSION" ]; then
+        if [[ -d $TRAVIS_SAVED_HOME/VME/VME$BRANCH ]]; then
+            # echo "# .. loading stored packages from VME$BRANCH ..."
+            run_traced "venv_mgr merge $VENVOPTS $TRAVIS_SAVED_HOME/VME/VME$BRANCH $TRAVIS_HOME -q"
+        elif [[ -d "$TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION" ]]; then
+            # echo "# .. loading stored packages from VME$TRAVIS_PYTHON_VERSION ..."
+            run_traced "venv_mgr merge $VENVOPTS $TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION $TRAVIS_HOME -q"
+        fi
     fi
+    cd $TRAVIS_HOME
+    source bin/activate
+    if [ -d $HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/ ]; then
+        export PYPI_CACHED=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
+    fi
+    export PS_RUN_COLOR=$SAVE_COLOR
     [ ${opt_dry_run:-0} -eq 0 ] && mkdir -p $TRAVIS_HOME/build
     [ ${opt_dry_run:-0} -eq 0 ] && mkdir -p $TRAVIS_HOME/build/${TRAVIS_REPO_SLUG%%/*}
     export TRAVIS_BUILD_DIR="$TRAVIS_HOME/build/$TRAVIS_REPO_SLUG"
     if [ "$PKGNAME" == "OCB" ]; then
-      emulate_git_clone_OCB $TRAVIS_CWD $TRAVIS_BUILD_DIR
+        emulate_git_clone_OCB $TRAVIS_CWD $TRAVIS_BUILD_DIR
     else
-      mkdir -p $TRAVIS_BUILD_DIR
-      x=$(readlink -f $TRAVIS_BUILD_DIR/..)
-      run_traced "cp -R $TRAVIS_CWD/ $x/"
-      if [ ${opt_dbgmnt:-0} -ne 0 -a "$TRAVIS_REPO_SLUG" == "local/tools" ]; then
-        for p in clodoo lisa maintainer-quality-tools python_plus travis_emulator z0bug_odoo z0lib zerobug; do
-          run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$p/$p/ $TRAVIS_BUILD_DIR/$p/  # Use no stable version"
-        done
-        run_traced "cp $TRAVIS_SAVED_HOME/dev/pypi/tools/install_tools.sh $TRAVIS_BUILD_DIR/"
-      fi
+        mkdir -p $TRAVIS_BUILD_DIR
+        x=$(readlink -f $TRAVIS_BUILD_DIR/..)
+        run_traced "cp -R $TRAVIS_CWD/ $x/"
+        if [ ${opt_dbgmnt:-0} -ne 0 -a "$TRAVIS_REPO_SLUG" == "local/tools" ]; then
+            # for p in clodoo lisa maintainer-quality-tools python_plus travis_emulator z0bug_odoo z0lib zerobug; do
+            for p in $(get_cfg_value 0 "PKGS_LIST"); do
+                run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$p/$p/ $TRAVIS_BUILD_DIR/$p/  # Use no stable version"
+            done
+            run_traced "cp $TRAVIS_SAVED_HOME/dev/pypi/tools/install_tools.sh $TRAVIS_BUILD_DIR/ -o"
+        fi
     fi
     [ "$PWD" != "$TRAVIS_BUILD_DIR" ] && run_traced "cd $TRAVIS_BUILD_DIR"
 }
@@ -689,35 +703,34 @@ git_clone() {
 # emulate git clone
     local d x
     while [[ -n "$1" && "${1:0:1}" == "-" ]]; do
-      shift
+        shift
     done
     if [[ "$1" == "https://github.com/zeroincombenze/tools.git" ]]; then
-      if [[ -n "$2" ]]; then
-        d=$(readlink -m $2/..)
-      else
-        d="./"
-      fi
-      run_traced "cp -R $TRAVIS_SAVED_HOME/tools $d"
-      if [[ -n "$YML_lisa" ]]; then
-        x=$(dirname $YML_lisa)
-        run_traced "rsync -a $x/ $HOME/tools/lisa/"
-      fi
-      if [[ -n "$YML_mgrodoo" ]]; then
-        x=$(dirname $YML_mgrodoo)
-        run_traced "rsync -a $x/ $HOME/tools/clodoo/"
-      fi
-      if [ $opt_dbgmnt -ne 0 ]; then
-        # x=$(basename $TRAVIS_REPO_SLUG)
-        x=${TRAVIS_REPO_SLUG#*/}
-        for p in clodoo lisa maintainer-quality-tools python_plus travis_emulator z0bug_odoo z0lib zerobug; do
-          [ -d $TRAVIS_SAVED_HOME/dev/pypi/$p/$p/ -a "$p" != "$x" ] && run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$p/$p/ $HOME/tools/$p/  # Use no stable version"
-        done
-        run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/ $HOME/tools/maintainer-quality-tools/travis/"
-        run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/_travis/ $HOME/tools/maintainer-quality-tools/_travis/"
-        # if [ -n "$x" -a -d $TRAVIS_SAVED_HOME/dev/pypi/$x/$x/ ]; then 
-        #   run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$x/$x/ $HOME/tools/$x/"
+        if [[ -n "$2" ]]; then
+            d=$(readlink -m $2/..)
+        else
+            d="./"
+        fi
+        run_traced "cp -R $TRAVIS_SAVED_HOME/tools $d"
+        # if [[ -n "$YML_lisa" ]]; then
+        #     x=$(dirname $YML_lisa)
+        #     run_traced "rsync -a $x/ $HOME/tools/lisa/"
         # fi
-      fi
+        # if [[ -n "$YML_mgrodoo" ]]; then
+        #     x=$(dirname $YML_mgrodoo)
+        #     run_traced "rsync -a $x/ $HOME/tools/clodoo/"
+        # fi
+        if [ $opt_dbgmnt -ne 0 ]; then
+            x=${TRAVIS_REPO_SLUG#*/}
+            # for p in clodoo lisa maintainer-quality-tools python_plus travis_emulator z0bug_odoo z0lib zerobug; do
+            for p in $(get_cfg_value 0 "PKGS_LIST"); do
+                [ -d $TRAVIS_SAVED_HOME/dev/pypi/$p/$p/ -a "$p" != "$x" ] && run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$p/$p/ $HOME/tools/$p/  # Use unstable version"
+                [ $? -ne 0 ] && echo "Internal error! Statement failed! <<<"
+            done
+            # run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/ $HOME/tools/maintainer-quality-tools/travis/"
+            # run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/_travis/ $HOME/tools/maintainer-quality-tools/_travis/"
+            true    # FIX: return no error
+        fi
     fi
 }
 
@@ -786,11 +799,6 @@ prepare_env_travis() {
         LGITPATH=
       fi
     fi
-    # if [ -x $TDIR/travis ]; then
-    #   export TRAVIS_RUNDIR=$TDIR
-    # else
-    #   export TRAVIS_RUNDIR=$(readlink -f ~/dev)
-    # fi
     export TOOLS_PATH
     export MQT_PATH
     export ODOO_SETUP
@@ -839,7 +847,7 @@ conf_default() {
       set_cfg_def "PRD_HOST" "shsprd[0-9]*"
     fi
     set_cfg_def "CHAT_HOME" "https://tawk.to/85d4f6e06e68dd4e358797643fe5ee67540e408b"
-    set_cfg_def "SET_GLOBAL_PYVER" "0"
+    # set_cfg_def "SET_GLOBAL_PYVER" "0"
     # set_cfg_def "PIDFILE" "/var/run/travis_emulator/travis_emulator.pid"
     # set_cfg_def "ODOO_SETUP" "__openerp__.py" #TODO: remove early
     set_cfg_def "ODOO_SETUPS" "__manifest__.py __openerp__.py __odoo__.py __terp__.py"
@@ -872,7 +880,6 @@ conf_default() {
       set_cfg_def "upgrade_dow" "4"
     fi
     set_cfg_def "Environment" "bash"
-    # set_cfg_def "virtualenv_opts" "--no-pip --no-setuptools --no-wheel"
     set_cfg_def "virtualenv_opts" ""
     set_cfg_def "NPM_CONFIG_PREFIX" "$HOME/.npm-global"
     set_cfg_def "filedel" ".log .bak .out .tmp .tracehis .tracehistory ,cover .coverage .cover/ .coverage/ ~ test*.pdf tmp tmp.* npm-debug.log.*"
@@ -887,6 +894,11 @@ conf_default() {
     set_cfg_def "PS_HDR1_COLOR" "97;48;5;22"
     set_cfg_def "PS_HDR2_COLOR" "30;43"
     set_cfg_def "PS_HDR3_COLOR" "30;47"
+    set_cfg_def "PKGS_LIST" "clodoo devel_tools lisa maintainer-quality-tools odoo_score os0 python_plus travis_emulator wok_code z0bug_odoo z0lib zar zerobug"
+    set_cfg_def "HTML_SVG_DIR" "/var/www/html/wp-zi/wp-content/uploads/ci-ct"
+    set_cfg_def "DEV_SVG" "$HOME/dev/svg"
+    set_cfg_def "HTML_DOCS_DIR" "/var/www/html/mw/html"
+    set_cfg_def "HTML_DOWNLOAD_DIR" "/var/www/html/mw/download"
 }
 
 
