[IMP] Darwin implementation

diff --git a/devel_tools/cvt_script b/devel_tools/cvt_script
--- a/devel_tools/cvt_script
+++ b/devel_tools/cvt_script
@@ -7,14 +7,20 @@
 # author: Antonio Maria Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2016-2020 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
+export READLINK=readlink
+OS=$(uname -s)
+if [[ $OS == "Darwin" ]]; then
+  READLINK=$(which greadlink 2>/dev/null)
+  [[ -n "$READLINK" ]] && READLINK=$(basename $READLINK) || READLINK="echo 'greadlink not found\!'; exit 125;"
+fi
 THIS=$(basename "$0")
-TDIR=$(readlink -f $(dirname $0))
+TDIR=$($READLINK -f $(dirname $0))
 PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/devel_tools/devel_tools/../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib/z0lib; do
+for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc $TDIR/../z0lib $TDIR/../../z0lib $TDIR/../../z0lib/z0lib; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
     break
   fi
 done
@@ -23,7 +29,7 @@ if [[ -z "$Z0LIBDIR" ]]; then
   exit 2
 fi
 
-__version__=1.0.0.6
+__version__=1.0.0.8
 
 #//Only human upgradable code/
 # blk1 => z0librc
@@ -136,6 +142,7 @@ cvt_file() {
             line_ver="__version__=$y.$x"
           fi
           if [ $prc -eq 0 ]; then
+            [[ $opt_keep -ne 0 ]] && echo "$line_ver" >>$fntmp
             continue
           fi
         fi
@@ -148,7 +155,7 @@ cvt_file() {
         elif [ $incl -eq 1 ]; then
           echo "$line" >>$fntmp
         elif [ $prc -eq 0 ]; then
-          if [[ $line =~ ^THIS.*basename.* ]]; then
+          if [[ $line =~ ^THIS=..basename || $line =~ ^export.READLINK=readlink ]]; then
             prc=1
             blk_1 "$fntmp"
             empty=0
@@ -377,14 +384,20 @@ cvt_file() {
 
 blk_1() {
   cat <<EOF >>$1
+export READLINK=readlink
+OS=\$(uname -s)
+if [[ \$OS == "Darwin" ]]; then
+  READLINK=\$(which greadlink 2>/dev/null)
+  [[ -n "\$READLINK" ]] && READLINK=\$(basename \$READLINK) || READLINK="echo 'greadlink not found\!'; exit 125;"
+fi
 THIS=\$(basename "\$0")
-TDIR=\$(readlink -f \$(dirname \$0))
+TDIR=\$(\$READLINK -f \$(dirname \$0))
 PYPATH=\$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in \$TDIR \${PATH//:/ } \${PYPATH//:/ } /etc $TDIR/../z0lib $TDIR/../../z0lib $TDIR/../../z0lib/z0lib; do
+for d in \$TDIR \${PATH//:/ } \${PYPATH//:/ } /etc \$TDIR/../z0lib \$TDIR/../../z0lib \$TDIR/../../z0lib/z0lib; do
   if [[ -e \$d/z0librc ]]; then
     . \$d/z0librc
     Z0LIBDIR=\$d
-    Z0LIBDIR=\$(readlink -e \$Z0LIBDIR)
+    Z0LIBDIR=\$(\$READLINK -e \$Z0LIBDIR)
     break
   fi
 done
@@ -476,7 +489,7 @@ EOF
 blk_8() {
   cat <<EOF >>$1
 TESTDIR=\$(findpkg "" "\$TDIR . .." "tests")
-RUNDIR=\$(readlink -e \$TESTDIR/..)
+RUNDIR=\$($READLINK -e \$TESTDIR/..)
 EOF
 }
 
@@ -542,7 +555,6 @@ if [ \$opt_verbose -gt 1 ]; then set -x; fi
 EOF
 }
 #//Enable.auto.upgrade.code/
-
 
 OPTOPTS=(h        J         K        k        m         n           O         q           T        U      V           v           w          y       Z)
 OPTDEST=(opt_help opt_tjLib opt_lev3 opt_keep opt_id    opt_dry_run opt_oeLib opt_verbose opt_Test opt_UT opt_version opt_verbose opt_nowarn opt_yes opt_zLib)
diff --git a/devel_tools/please b/devel_tools/please
--- a/devel_tools/please
+++ b/devel_tools/please
@@ -8,14 +8,20 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2020 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
+export READLINK=readlink
+OS=$(uname -s)
+if [[ $OS == "Darwin" ]]; then
+  READLINK=$(which greadlink 2>/dev/null)
+  [[ -n "$READLINK" ]] && READLINK=$(basename $READLINK) || READLINK="echo 'greadlink not found\!'; exit 125;"
+fi
 THIS=$(basename "$0")
-TDIR=$(readlink -f $(dirname $0))
+TDIR=$($READLINK -f $(dirname $0))
 PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/devel_tools/devel_tools/../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib/z0lib; do
+for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc $TDIR/../z0lib $TDIR/../../z0lib $TDIR/../../z0lib/z0lib; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
     break
   fi
 done
@@ -38,7 +44,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=1.0.0.6
+__version__=1.0.0.8
 
 #
 # General Purpose options:
@@ -90,24 +96,24 @@ move_n_bak() {
 }
 
 search_pofile() {
-    srcs=$(find -L $odoo_root -not -path '*/__to_remove/*' -type d -name "$opt_modules")
-    f=0
-    for src in $srcs; do
-        if [ -n "$src" ]; then
-            if [ -f $src/i18n/it.po ]; then
-                src=$src/i18n/it.po
-                if [ $opt_exp -ne 0 ]; then
-                    run_traced "cp $src $src.bak"
-                fi
-                f=1
-                break
-            else
-                alt=$(find -L $src/i18n -name '*.po' | head -n1)
-                src=
-                if [ -n "$alt" ]; then fi=1 break; fi
-            fi
+  srcs=$(find -L $odoo_root -not -path '*/__to_remove/*' -type d -name "$opt_modules")
+  f=0
+  for src in $srcs; do
+    if [ -n "$src" ]; then
+      if [ -f $src/i18n/it.po ]; then
+        src=$src/i18n/it.po
+        if [ $opt_exp -ne 0 ]; then
+          run_traced "cp $src $src.bak"
         fi
-    done
+        f=1
+        break
+      else
+        alt=$(find -L $src/i18n -name '*.po' | head -n1)
+        src=
+        if [ -n "$alt" ]; then fi=1 break; fi
+      fi
+    fi
+  done
 }
 
 add_copyright() {
@@ -1554,12 +1560,12 @@ do_edit_translation_from_pofile() {
   fi
   pyv=$(python3 --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
   [[ -n "$pyv" ]] && pyver="-p $pyv"
-  pyver="-p 2.7"    #debug
-  [[ ! -d $HOME/clodoo/venv ]] \
-    && run_traced "vem $pyver create $HOME/clodoo/venv" \
-    && run_traced "vem $HOME/clodoo/venv install xlrd" \
-    && run_traced "vem $HOME/clodoo/venv install Babel" \
-    && run_traced "vem $HOME/clodoo/venv install clodoo"
+  pyver="-p 2.7" #debug
+  [[ ! -d $HOME/clodoo/venv ]] && \
+    run_traced "vem $pyver create $HOME/clodoo/venv" && \
+    run_traced "vem $HOME/clodoo/venv install xlrd" && \
+    run_traced "vem $HOME/clodoo/venv install Babel" && \
+    run_traced "vem $HOME/clodoo/venv install clodoo"
   run_traced "pushd $HOME/clodoo >/dev/null"
   [ $opt_verbose -ne 0 ] && opts="-v" || opts="-q"
   [ $opt_dbg -ne 0 ] && opts="${opts}B"
@@ -1567,14 +1573,6 @@ do_edit_translation_from_pofile() {
   sts=$?
   run_traced "popd >/dev/null"
   return $sts
-
-
-
-
-
-
-
-
 
   [[ -f "$HOME/dev/pypi/tools/odoo_default_tnl.xlsx" ]] && xfile="$HOME/dev/pypi/tools/odoo_default_tnl.xlsx"
   [[ -f "$HOME/devel/pypi/tools/odoo_default_tnl.xlsx" ]] && xfile="$HOME/devel/pypi/tools/odoo_default_tnl.xlsx"
@@ -1824,13 +1822,13 @@ do_distribution_odoo() {
         sts=$STS_FAILED
       else
         run_traced "git clone $GITPRJ tmp -b $BRANCH --depth 1 --single-branch"
-        ORIG=$(readlink -e tmp)
+        ORIG=$($READLINK -e tmp)
       fi
     else
       if [ -d ~/original ]; then rm -fR -d ~/original; fi
       if [ -n "$GITPRJ" ]; then
         run_traced "git clone $GITPRJ ~/original/$1 -b $BRANCH --depth 1 --single-branch"
-        ORIG=$(readlink -e ~/original/$1)
+        ORIG=$($READLINK -e ~/original/$1)
       fi
     fi
   fi
@@ -1846,7 +1844,7 @@ do_distribution_odoo() {
   fi
   local PKGS= FL= PIGN=
   for f in $(find . -type f \( -name __openerp__.py -o -name __manifest__.py -o -name ".travis.yml" -o -name "README*" -a -not -name "*.bak" -a -not -name "*~" -a -not -name "*.z0i" -a -not -name "*.oca" -a -not -name "*.tmp" \)); do
-    x=$(readlink -e $f)
+    x=$($READLINK -e $f)
     f1=$(dirname $x)
     f2=$(build_odoo_param REPOS $f1)
     b=$(basename $f)
@@ -1875,7 +1873,7 @@ do_distribution_odoo() {
       fi
     fi
   done
-  f2=$(readlink -e .)
+  f2=$($READLINK -e .)
   for f in $(find . -type d -name 'egg-info'); do
     d=$(dirname $f)
     run_traced "pushd $d >/dev/null"
@@ -1961,7 +1959,7 @@ do_docs() {
   local docs_dir=./docs
   local author version theme SETUP b f t x
   local opts src_png odoo_fver
-  [[ $PWD =~ /dev(el)?/pypi/ ]] && opts=-B || opts=
+  [[ $opt_dbg -ne 0 || $PWD =~ /dev(el)?/pypi/ ]] && opts=-B || opts=
   if [ "$PRJNAME" == "Odoo" ]; then
     [[ -z "$opt_branch" ]] && odoo_fver=$(build_odoo_param FULLVER ".") || odoo_fver=$(build_odoo_param FULLVER "$opt_branch")
     [[ -z "$opt_branch" ]] && orgid=$(build_odoo_param GIT_ORGID ".") || odoo_fver=$(build_odoo_param GIT_ORGID "$opt_branch")
@@ -1974,7 +1972,7 @@ do_docs() {
       [[ $GIT_ORGNM == "zeroincombenze" ]] && orgid="zero"
       [[ $GIT_ORGNM =~ (axitec|axilor) ]] && orgid="axitec"
     elif [[ -z "$opt_branch" && -d $PARENTDIR/.git ]]; then
-      push $PARENTDIR >/dev/null
+      pushd $PARENTDIR >/dev/null
       GIT_URL=$(git remote get-url --push origin 2>/dev/null)
       [[ -n "$GIT_URL" ]] && GIT_ORGNM=$(basename $(dirname $(git remote -v | echo $GIT_URL | awk -F: '{print $2}')))
       [[ $GIT_ORGNM == "OCA" ]] && orgid="oca"
@@ -1999,8 +1997,8 @@ do_docs() {
   fi
   if [[ ! -f $docs_dir/logozero_180x46.png ]]; then
     src_png=
-    [[ -z "$src_png" && -f ../tools/docs/logozero_180x46.png ]] && src_png=$(readlink -e ../tools/docs/logozero_180x46.png)
-    [[ -z "$src_png" && -f ../../tools/docs/logozero_180x46.png ]] && src_png=$(readlink -e ../../tools/docs/logozero_180x46.png)
+    [[ -z "$src_png" && -f ../tools/docs/logozero_180x46.png ]] && src_png=$($READLINK -e ../tools/docs/logozero_180x46.png)
+    [[ -z "$src_png" && -f ../../tools/docs/logozero_180x46.png ]] && src_png=$($READLINK -e ../../tools/docs/logozero_180x46.png)
     [[ -n "$src_png" ]] && run_traced "cp $src_png $docs_dir/logozero_180x46.png"
   fi
   for f in $(grep -E "^ *(rtd_|pypi_)" docs/index.rst | tr "\n" " "); do
@@ -2325,7 +2323,7 @@ do_export() {
     return $STS_FAILED
   fi
   if [[ -z "$db" ]]; then
-    DBs=$(psql -Atl|awk -F'|' '{print $1}'|tr \"\\n\" '|')
+    DBs=$(psql -Atl | awk -F'|' '{print $1}' | tr \"\\n\" '|')
     DBs="^(${DBs:0: -1})\$"
     for x in tnl test demo; do
       [[ $x$odoo_ver =~ $DBs ]] && db="$x$odoo_ver" && break
@@ -2417,7 +2415,7 @@ do_translate() {
     return $STS_FAILED
   fi
   if [[ -z "$db" ]]; then
-    DBs=$(psql -Atl|awk -F'|' '{print $1}'|tr \"\\n\" '|')
+    DBs=$(psql -Atl | awk -F'|' '{print $1}' | tr \"\\n\" '|')
     DBs="^(${DBs:0: -1})\$"
     for x in tnl test demo; do
       [[ $x$odoo_ver =~ $DBs ]] && db="$x$odoo_ver" && break
@@ -2435,12 +2433,12 @@ do_translate() {
   fi
   pyv=$(python3 --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
   [[ -n "$pyv" ]] && pyver="-p $pyv"
-  pyver="-p 2.7"    #debug
-  [[ ! -d $HOME/clodoo/venv ]] \
-    && run_traced "vem $pyver create $HOME/clodoo/venv" \
-    && run_traced "vem $HOME/clodoo/venv install xlrd" \
-    && run_traced "vem $HOME/clodoo/venv install Babel" \
-    && run_traced "vem $HOME/clodoo/venv install clodoo"
+  pyver="-p 2.7" #debug
+  [[ ! -d $HOME/clodoo/venv ]] && \
+    run_traced "vem $pyver create $HOME/clodoo/venv" && \
+    run_traced "vem $HOME/clodoo/venv install xlrd" && \
+    run_traced "vem $HOME/clodoo/venv install Babel" && \
+    run_traced "vem $HOME/clodoo/venv install clodoo"
   run_traced "pushd $HOME/clodoo >/dev/null"
   [ $opt_verbose -ne 0 ] && opts="-v" || opts="-q"
   [ $opt_dbg -ne 0 ] && opts="${opts}B"
@@ -2639,7 +2637,7 @@ do_replica() {
       echo "File $fn not found"
       exit 1
     fi
-    srcfn=$(readlink -f $fn)
+    srcfn=$($READLINK -f $fn)
     for ver in 14.0 13.0 12.0 11.0 10.0 9.0 8.0 7.0 6.1; do
       if [ "$ver" != "$cur_ver" ]; then
         tgtfn="${srcfn/$cur_ver/$ver}"
@@ -2677,7 +2675,7 @@ do_replica() {
 do_showdoc() {
   if [[ ! "$PRJNAME" == "Odoo" ]]; then
     if [[ -f ./docs/_build/html/index.html ]]; then
-      firefox $(readlink -e ./docs/_build/html/index.html) &
+      firefox $($READLINK -e ./docs/_build/html/index.html) &
     else
       echo "No documentation found in ./docs!"
     fi
@@ -2822,9 +2820,9 @@ do_config() {
   if [ "$sub1" == "global" ]; then
     cfgfn=$TCONF
   elif [ "$sub1" == "repository" ]; then
-    cfgfn=$(readlink -m $PKGPATH/../conf/.local_dist_pkg.conf)
+    cfgfn=$($READLINK -m $PKGPATH/../conf/.local_dist_pkg.conf)
   elif [ "$sub1" == "local" ]; then
-    cfgfn=$(readlink -m $PKGPATH/conf/.local_dist_pkg.conf)
+    cfgfn=$($READLINK -m $PKGPATH/conf/.local_dist_pkg.conf)
   elif [ "$sub1" == "current" ]; then
     cfgfn=$DIST_CONF
   elif [ "$sub1" == "zero" -o "$sub1" == "axitec" ]; then
@@ -2868,7 +2866,6 @@ do_wep() {
   set_executable
   return 0
 }
-
 
 OPTOPTS=(h        B       b          c        d        f         j        k        L         m       n           o        O        p         q           r     s        t         u       V           v)
 OPTDEST=(opt_help opt_dbg opt_branch opt_conf opt_date opt_force opt_dprj opt_keep opt_log   opt_mis opt_dry_run opt_ids  opt_orig opt_dpath opt_verbose opt_r opt_srcs test_mode opt_uop opt_version opt_verbose)
diff --git a/devel_tools/vfdiff b/devel_tools/vfdiff
--- a/devel_tools/vfdiff
+++ b/devel_tools/vfdiff
@@ -6,28 +6,34 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2020 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 # This free software is released under GNU Affero GPL3
+export READLINK=readlink
+OS=$(uname -s)
+if [[ $OS == "Darwin" ]]; then
+  READLINK=$(which greadlink 2>/dev/null)
+  [[ -n "$READLINK" ]] && READLINK=$(basename $READLINK) || READLINK="echo 'greadlink not found\!'; exit 125;"
+fi
 THIS=$(basename "$0")
-TDIR=$(readlink -f $(dirname $0))
+TDIR=$($READLINK -f $(dirname $0))
 PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../.. $TDIR/../../z0lib $TDIR/../../z0lib/z0lib $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
-  if [ -e $d/z0librc ]; then
+for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc $TDIR/../z0lib $TDIR/../../z0lib $TDIR/../../z0lib/z0lib; do
+  if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
     break
   fi
 done
-if [ -z "$Z0LIBDIR" ]; then
+if [[ -z "$Z0LIBDIR" ]]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/dev ${PYPATH//:/ } . .." "clodoo")
+ODOOLIBDIR=$(findpkg odoorc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "clodoo")
 if [ -z "$ODOOLIBDIR" ]; then
   echo "Library file odoorc not found!"
   exit 2
 fi
 . $ODOOLIBDIR
-TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $HOME/tools/travis_emulator $HOME/dev ${PYPATH//:/ } . .." "travis_emulator")
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
   exit 2
@@ -38,199 +44,198 @@ RUNDIR=$(readlink -e $TESTDIR/..)
 
 __version__=0.2.3.2
 
-
 vf_init() {
-    VF_IGNORE="$(get_cfg_value 0 filedel)"
-    VF_IGNORE="$VF_IGNORE $(get_cfg_value 0 fileignore)"
-    VF_DIGNORE=$(get_cfg_value 0 "filediffignore")
-    XRGX=
-    XLFS=
-    XLDF=
-    for x in $VF_IGNORE; do
-      local x1="${x:0:1}"
-      local x9="${x: -1}"
-      if [ "$x9" == "/" ]; then
-         XRGX="$XRGX ^(.*\\/|)$x"
-         XLFS="$XLFS --exclude=$x"
-         XLDF="$XLDF -x '${x:0: -1}'"
-      elif [ "$x1" == "." -o "$x1" == "," -o "$x" == "~" ]; then
-         XRGX="$XRGX ^.*\\$x\$"
-         XLFS="$XLFS --exclude=*$x"
-         XLDF="$XLDF -x '*$x'"
-      else
-         XRGX="$XRGX $x"
-         XLFS="$XLFS --exclude=*$x*"
-         XLDF="$XLDF -x '*$x'"
-      fi
-    done
-    XXDF=
-    for x in $VF_DIGNORE; do
-      local x1="${x:0:1}"
-      local x9="${x: -1}"
-      if [ "$x9" == "/" ]; then
-         XXDF="$XXDF ^(.*\\/|)$x"
-      elif [ "$x1" == "." -o "$x" == "~" ]; then
-         XXDF="$XXDF ^.*\\$x\$"
-      else
-         XXDF="$XXDF $x"
-      fi
+  VF_IGNORE="$(get_cfg_value 0 filedel)"
+  VF_IGNORE="$VF_IGNORE $(get_cfg_value 0 fileignore)"
+  VF_DIGNORE=$(get_cfg_value 0 "filediffignore")
+  XRGX=
+  XLFS=
+  XLDF=
+  for x in $VF_IGNORE; do
+    local x1="${x:0:1}"
+    local x9="${x: -1}"
+    if [ "$x9" == "/" ]; then
+      XRGX="$XRGX ^(.*\\/|)$x"
+      XLFS="$XLFS --exclude=$x"
+      XLDF="$XLDF -x '${x:0:-1}'"
+    elif [ "$x1" == "." -o "$x1" == "," -o "$x" == "~" ]; then
+      XRGX="$XRGX ^.*\\$x\$"
+      XLFS="$XLFS --exclude=*$x"
       XLDF="$XLDF -x '*$x'"
-    done
+    else
+      XRGX="$XRGX $x"
+      XLFS="$XLFS --exclude=*$x*"
+      XLDF="$XLDF -x '*$x'"
+    fi
+  done
+  XXDF=
+  for x in $VF_DIGNORE; do
+    local x1="${x:0:1}"
+    local x9="${x: -1}"
+    if [ "$x9" == "/" ]; then
+      XXDF="$XXDF ^(.*\\/|)$x"
+    elif [ "$x1" == "." -o "$x" == "~" ]; then
+      XXDF="$XXDF ^.*\\$x\$"
+    else
+      XXDF="$XXDF $x"
+    fi
+    XLDF="$XLDF -x '*$x'"
+  done
 }
 
 simple_diff() {
-# simple_diff(opts src tgt)
-    local opts=$1
-    local src=$2
-    local tgt=$3
-    local d n s
-    run_traced "diff$opts $src $tgt"
-    s=$?
-    return $s
+  # simple_diff(opts src tgt)
+  local opts=$1
+  local src=$2
+  local tgt=$3
+  local d n s
+  run_traced "diff$opts $src $tgt"
+  s=$?
+  return $s
 }
 
 exec_os() {
-    local l r x
-    if [ $opt_reve -gt 0 ]; then
-        local left=$2
-        local right=$1
+  local l r x
+  if [ $opt_reve -gt 0 ]; then
+    local left=$2
+    local right=$1
+  else
+    local left=$1
+    local right=$2
+  fi
+  if [ -d "$left" ]; then
+    if [ $opt_all -gt 0 ]; then
+      opts=" -Zqr"
     else
-        local left=$1
-        local right=$2
+      opts="$XLDF -ZBqr"
     fi
+    [ $opt_igns -gt 0 ] && opts="${opts}Eb"
+    [ $opt_ignas -gt 0 ] && opts="${opts}w"
+    [ $opt_md -ne 0 ] && opts="$opts -I '^#' -I \"^ *[_\\\"']\?_\?version[_\\\"']\?_\? *[:=]\""
+  else
+    opts=" -ZB"
+    [ $opt_para -ne 0 ] && opts="${opts}y"
+    [ $opt_igns -gt 0 ] && opts="${opts}Eb"
+    [ $opt_ignas -gt 0 ] && opts="${opts}w"
+    [ $opt_md -ne 0 ] && opts="$opts -I '^#' -I \"^ *[_\\\"']\?_\?version[_\\\"']\?_\? *[:=]\""
+    [ $opt_diffe -ne 0 ] && opts="$opts  --suppress-common-line"
+  fi
+  if [[ $opt_dcmd == "meld" ]]; then
     if [ -d "$left" ]; then
-        if [ $opt_all -gt 0 ]; then
-            opts=" -Zqr"
-        else
-            opts="$XLDF -ZBqr"
-        fi
-        [ $opt_igns -gt 0 ] && opts="${opts}Eb"
-        [ $opt_ignas -gt 0 ] && opts="${opts}w"
-        [ $opt_md -ne 0 ] && opts="$opts -I '^#' -I \"^ *[_\\\"']\?_\?version[_\\\"']\?_\? *[:=]\""
+      for ln in $(eval "diff $opts $left $right" | grep ^Files | awk '{print $2 "|" $4}'); do
+        l=$(echo $ln | awk -F"|" '{print $1}')
+        r=$(echo $ln | awk -F"|" '{print $2}')
+        run_traced "$opt_dcmd $l $r"
+      done
+      x=$(eval "diff $opts $left $right" | grep -E "^Only.*__(manifest|openerp)__.py" | awk '{print $3 $4}')
+      l=$(echo $x | awk '{print $1}')
+      r=$(echo $x | awk '{print $2}')
+      if [[ -n "$l" && -n "$r" ]]; then
+        l=${l//:/}
+        r=${r//:/}
+        run_traced "$opt_dcmd $l $r"
+      fi
+      eval "diff $opts $left $right" | grep -v ^Files
     else
-        opts=" -ZB"
-        [ $opt_para -ne 0 ] && opts="${opts}y"
-        [ $opt_igns -gt 0 ] && opts="${opts}Eb"
-        [ $opt_ignas -gt 0 ] && opts="${opts}w"
-        [ $opt_md -ne 0 ] && opts="$opts -I '^#' -I \"^ *[_\\\"']\?_\?version[_\\\"']\?_\? *[:=]\""
-        [ $opt_diffe -ne 0 ] && opts="$opts  --suppress-common-line"
+      run_traced "$opt_dcmd $left $right"
     fi
-    if [[ $opt_dcmd == "meld" ]]; then
-        if [ -d "$left" ]; then
-            for ln in $(eval "diff $opts $left $right"|grep ^Files|awk '{print $2 "|" $4}'); do
-                l=$(echo $ln|awk -F"|" '{print $1}')
-                r=$(echo $ln|awk -F"|" '{print $2}')
-                run_traced "$opt_dcmd $l $r"
-            done
-            x=$(eval "diff $opts $left $right"|grep -E "^Only.*__(manifest|openerp)__.py"|awk '{print $3 $4}')
-            l=$(echo $x|awk '{print $1}')
-            r=$(echo $x|awk '{print $2}')
-            if [[ -n "$l" && -n "$r" ]]; then
-                l=${l//:/}
-                r=${r//:/}
-                run_traced "$opt_dcmd $l $r"
-            fi
-            eval "diff $opts $left $right"|grep -v ^Files
-        else
-            run_traced "$opt_dcmd $left $right"
-        fi
-    else
-        run_traced "$opt_dcmd$opts $left $right"
-    fi
-    return $?
+  else
+    run_traced "$opt_dcmd$opts $left $right"
+  fi
+  return $?
 }
 
 exec_iar() {
-    local param=-i
-    local left=$1
-    local right=$2
-    local f
-    local cparq=""
-    local cparv=""
-    local sts=$opt_sts
-    if [ "$opt_sel" ]; then param="$param -s$opt_sel"; fi
-    if [ $opt_verbose -gt 0 ]; then
-      param="$param -v"
-    else
-      cparq="$cparq -q"
-    fi
-    if [ $opt_para -ne 0 ]; then
-      cparv="$cparv -y"
-      [ $opt_diffe -ne 0 ] && cparv="$cparv --suppress-common-lines"
-      param="$param -y"
-    fi
-    if [ $opt_md -ne 0 ]; then param="$param -m"; fi
-    if [ -d $left ]; then
-      for f in $(ls -1 $left); do
-        if [ $opt_verbose -gt 1 ]; then
-          echo "> $0 $param $left/$f $right/$f"
+  local param=-i
+  local left=$1
+  local right=$2
+  local f
+  local cparq=""
+  local cparv=""
+  local sts=$opt_sts
+  if [ "$opt_sel" ]; then param="$param -s$opt_sel"; fi
+  if [ $opt_verbose -gt 0 ]; then
+    param="$param -v"
+  else
+    cparq="$cparq -q"
+  fi
+  if [ $opt_para -ne 0 ]; then
+    cparv="$cparv -y"
+    [ $opt_diffe -ne 0 ] && cparv="$cparv --suppress-common-lines"
+    param="$param -y"
+  fi
+  if [ $opt_md -ne 0 ]; then param="$param -m"; fi
+  if [ -d $left ]; then
+    for f in $(ls -1 $left); do
+      if [ $opt_verbose -gt 1 ]; then
+        echo "> $0 $param $left/$f $right/$f"
+      fi
+      if $(matches1of "$f" "$XRGX"); then
+        :
+      else
+        $0 -$sts $param -2 $left/$f $right/$f
+        if [ $? -gt 0 ]; then
+          sts=$STS_FAILED
         fi
-        if $(matches1of "$f" "$XRGX"); then
+      fi
+    done
+    if [ -d $right ]; then
+      for f in $(ls -1 $right); do
+        if $(matches1of "$f" "$XRGX $XXDF"); then
           :
         else
-          $0 -$sts $param -2 $left/$f $right/$f
-          if [ $? -gt 0 ]; then
+          if [ ! -e $left/$f ]; then
+            echo "Only in $right: $f"
             sts=$STS_FAILED
           fi
         fi
       done
-      if [ -d $right ]; then
-        for f in $(ls -1 $right); do
-          if $(matches1of "$f" "$XRGX $XXDF"); then
-            :
-          else
-            if [ ! -e $left/$f ]; then
-              echo "Only in $right: $f"
-              sts=$STS_FAILED
-            fi
-          fi
-        done
-      fi
-      if [ $opt_2nd -eq 0 -a $sts -eq $STS_SUCCESS -a $opt_verbose -gt 0 ]; then
-         echo "No diff found"
-      fi
+    fi
+    if [ $opt_2nd -eq 0 -a $sts -eq $STS_SUCCESS -a $opt_verbose -gt 0 ]; then
+      echo "No diff found"
+    fi
+  else
+    if [ $opt_verbose -gt 1 ]; then
+      echo "> $0 $left $right"
+    fi
+    if $(matches1of "$left" "$XRGX $XXDF"); then
+      :
     else
-      if [ $opt_verbose -gt 1 ]; then
-        echo "> $0 $left $right"
-      fi
-      if $(matches1of "$left" "$XRGX $XXDF"); then
-        :
-      else
-        if [ -f $right ]; then
-          if [[ "$left" =~ $opt_sel ]]; then
-            local mime=$(file -b --mime-type $left)
-            if [ $opt_md -ne 0  -a "$mime" == "text/x-python" -o "${left: -3}" == ".py" ]; then
-              # if [ $opt_verbose -eq 0 ]; then
-              #   if diff -qZBI'^#' $left $right; then
-              #     echo "diff -ZBI'^#' $cparv $left $right"
-              #   fi
-              # fi
-              run_traced "diff -ZBI'^#' $cparv $left $right"
-            else
-              run_traced "diff $cparv $left $right"
-            fi
+      if [ -f $right ]; then
+        if [[ "$left" =~ $opt_sel ]]; then
+          local mime=$(file -b --mime-type $left)
+          if [ $opt_md -ne 0 -a "$mime" == "text/x-python" -o "${left: -3}" == ".py" ]; then
+            # if [ $opt_verbose -eq 0 ]; then
+            #   if diff -qZBI'^#' $left $right; then
+            #     echo "diff -ZBI'^#' $cparv $left $right"
+            #   fi
+            # fi
+            run_traced "diff -ZBI'^#' $cparv $left $right"
           else
-            run_traced "diff $cparq $left $right"
+            run_traced "diff $cparv $left $right"
           fi
-          if [ $? -gt 0 ]; then
-            sts=$STS_FAILED
-          fi
-        elif [ ! -f $right ]; then
-          fd=$(dirname $left)
-          fb=$(basename $left)
-          echo "Only in $fd: $fb"
+        else
+          run_traced "diff $cparq $left $right"
+        fi
+        if [ $? -gt 0 ]; then
           sts=$STS_FAILED
         fi
+      elif [ ! -f $right ]; then
+        fd=$(dirname $left)
+        fb=$(basename $left)
+        echo "Only in $fd: $fb"
+        sts=$STS_FAILED
       fi
     fi
-    return $sts
+  fi
+  return $sts
 }
 
 set_oever() {
-# set_oever(odoo_ver)
-    if [ -z "$VF_FVER" ]; then
-      VF_FVER=$1
-    fi
+  # set_oever(odoo_ver)
+  if [ -z "$VF_FVER" ]; then
+    VF_FVER=$1
+  fi
 }
 
 # PATH examples:
@@ -241,40 +246,39 @@ set_oever() {
 #   filename
 #   ${ver}
 get_path_ver() {
-# get_path_ver(path rep pkg)
-    VF_MSTS=0
-    local i
-    local p r t v x
-    local re="(13\.0|12\.0|11\.0|10\.0|9\.0|8\.0|7\.0|v7)"
-    [ -n "$2" ] && i=$(build_odoo_param ALL "$1" "$2") || i=$(build_odoo_param ALL "$1" "$3")
-    IFS="|" read x v r p x <<< "$i"
-    if [[ -n "$v" && -n "$r"  && ( ! "$r" == "OCB" || -z "$VF_REPO" ) ]]; then
-        [ -n "$2" ] && i=$(build_odoo_param ROOT "$1" "$2") || i=$(build_odoo_param ROOT "$1" "$3")
-        VF_ROOT=$(dirname $i)
-        VF_REPO=$r
-        [ -n "$2" ] && VF_PATH=$(build_odoo_param PKGPATH "$1" "$2") || VF_PATH=$(build_odoo_param PKGPATH "$1" "$3")
-    else
-        VF_PATH=""
-    fi
-    VF_FVER=$v
-    [[ -n "$r" && ! "$r" == "OCB" ]] || [[ -z "$VF_REPO" ]] && VF_REPO=${r}
-    [[ -n "$p" && ! "$p" == "OCB" ]] && VF_PKG=${p}
-    if [[ -z "$VF_PATH" ]]; then
-        VF_PATH=$VF_ROOT/$VF_FVER
-        [[ -n "$VF_REPO" && ! "$VF_REPO" == "OCB" ]] && VF_PATH="$VF_PATH/$VF_REPO"
-        [[ -n "$VF_PKG" && ! "$VF_PKG" == "OCB" ]] && VF_PATH="$VF_PATH/$VF_PKG"
-    fi
-    [[ -f $1 ]] && VF_FN=$(basename $1)
-    if [[ -f $1 ]]; then
-        result=$1
-    elif [[ -d $1 ]]; then
-        [[ -n "$VF_FN" ]] && result=$1/$VF_FN || result=$1
-    else
-        result=$VF_PATH
-        [[ -n "$VF_FN" ]] && result=$result/$VF_FN
-    fi
+  # get_path_ver(path rep pkg)
+  VF_MSTS=0
+  local i
+  local p r t v x
+  local re="(13\.0|12\.0|11\.0|10\.0|9\.0|8\.0|7\.0|v7)"
+  [ -n "$2" ] && i=$(build_odoo_param ALL "$1" "$2") || i=$(build_odoo_param ALL "$1" "$3")
+  IFS="|" read x v r p x <<<"$i"
+  if [[ -n "$v" && -n "$r" && (! "$r" == "OCB" || -z "$VF_REPO") ]]; then
+    [ -n "$2" ] && i=$(build_odoo_param ROOT "$1" "$2") || i=$(build_odoo_param ROOT "$1" "$3")
+    VF_ROOT=$(dirname $i)
+    VF_REPO=$r
+    [ -n "$2" ] && VF_PATH=$(build_odoo_param PKGPATH "$1" "$2") || VF_PATH=$(build_odoo_param PKGPATH "$1" "$3")
+  else
+    VF_PATH=""
+  fi
+  VF_FVER=$v
+  [[ -n "$r" && ! "$r" == "OCB" ]] || [[ -z "$VF_REPO" ]] && VF_REPO=${r}
+  [[ -n "$p" && ! "$p" == "OCB" ]] && VF_PKG=${p}
+  if [[ -z "$VF_PATH" ]]; then
+    VF_PATH=$VF_ROOT/$VF_FVER
+    [[ -n "$VF_REPO" && ! "$VF_REPO" == "OCB" ]] && VF_PATH="$VF_PATH/$VF_REPO"
+    [[ -n "$VF_PKG" && ! "$VF_PKG" == "OCB" ]] && VF_PATH="$VF_PATH/$VF_PKG"
+  fi
+  [[ -f $1 ]] && VF_FN=$(basename $1)
+  if [[ -f $1 ]]; then
+    result=$1
+  elif [[ -d $1 ]]; then
+    [[ -n "$VF_FN" ]] && result=$1/$VF_FN || result=$1
+  else
+    result=$VF_PATH
+    [[ -n "$VF_FN" ]] && result=$result/$VF_FN
+  fi
 }
-
 
 OPTOPTS=(h        a       b        c        e         i       m      n            O         p         q           r            R        V           v           w         X        y        0       1       2)
 OPTDEST=(opt_help opt_all opt_igns opt_conf opt_diffe opt_iar opt_md opt_dry_run  odoo_ver  opt_pkg   opt_verbose opt_rep      opt_reve opt_version opt_verbose opt_ignas opt_dcmd opt_para opt_sts opt_sts opt_2nd)
@@ -282,26 +286,26 @@ OPTACTI=(1        1       1        "="      1         1       1      1          
 OPTDEFL=(0        0       0        ""       0         0       0      0            ""        ""        -1          ""           0        ""          -1          0         ""       0        0       0       0)
 OPTMETA=("help"   ""      ""       "file"   ""        ""      ""     "do nothing" "version" "package" ""          "repository" ""       "version"   "verbose"   ""        "cmd"    ""       ""      ""      "")
 OPTHELP=("this help"\
- "diff all files (ignore exclusion list)"\
- "ignore space differences"\
- "configuration file (def ~/dev/.travis.conf)"\
- "side by side (only differences)"\
- "use internal algorithm rather than standard recursive diff"\
- "ignore minor difference (i.e. remarks)"\
- "do nothing (dry-run)"\
- "select target Odoo version (may be 7, 8, 9 o 10)"\
- "select package name"\
- "silent mode"\
- "select repository name"\
- "reverse diff from target to source rather source to target"\
- "show version"\
- "verbose mode"\
- "ignore all space differences"\
- "diff command (def meld or diff)"\
- "side by side (all lines)"\
- "initial status is true"\
- "initial status is false"\
- "undocumented")
+  "diff all files (ignore exclusion list)"
+  "ignore space differences"
+  "configuration file (def ~/dev/.travis.conf)"
+  "side by side (only differences)"
+  "use internal algorithm rather than standard recursive diff"
+  "ignore minor difference (i.e. remarks)"
+  "do nothing (dry-run)"
+  "select target Odoo version (may be 7, 8, 9 o 10)"
+  "select package name"
+  "silent mode"
+  "select repository name"
+  "reverse diff from target to source rather source to target"
+  "show version"
+  "verbose mode"
+  "ignore all space differences"
+  "diff command (def meld or diff)"
+  "side by side (all lines)"
+  "initial status is true"
+  "initial status is false"
+  "undocumented")
 OPTARGS=(source target)
 
 parseoptargs "$@"
@@ -311,12 +315,13 @@ if [ "$opt_version" ]; then
 fi
 [[ -z "$odoo_ver" && -z "$source" ]] && opt_help=1
 if [ $opt_help -gt 0 ]; then
-  print_help "Diff file between Odoo versions"\
-  "© 2015-2020 by zeroincombenze®\nhttps://zeroincombenze-tools.readthedocs.io/\nAuthor: antoniomaria.vigliotti@gmail.com"
+  print_help "Diff file between Odoo versions" \
+    "© 2015-2020 by zeroincombenze®\nhttps://zeroincombenze-tools.readthedocs.io/\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 [ $opt_all -gt 0 ] && opt_iar=0
-[ $opt_diffe -ne 0 ] & opt_para=1
+[ $opt_diffe -ne 0 ] &
+opt_para=1
 [[ " 14 13 12 11 10 9 8 7 " =~ [[:space:]]$odoo_ver[[:space:]] ]] && odoo_ver="$odoo_ver.0"
 if [ -n "$opt_conf" -a -f "$opt_conf" ]; then
   TCONF=$opt_conf
@@ -324,8 +329,8 @@ else
   TCONF=$TDIR/.travis.conf
 fi
 if [[ -z "$opt_dcmd" ]]; then
-    meld --version >/dev/null
-    [ $? -eq 0 ] && opt_dcmd="meld" || opt_dcmd="diff"
+  meld --version >/dev/null
+  [ $? -eq 0 ] && opt_dcmd="meld" || opt_dcmd="diff"
 fi
 CFG_init
 conf_default
@@ -333,32 +338,32 @@ link_cfg $TCONF
 vf_init
 
 if [ $opt_2nd -eq 0 ]; then
-    VF_ROOT=$HOME
-    VF_FVER=
-    VF_REPO=
-    VF_PKG=
-    VF_PATH=
-    VF_FN=
-    if [[ "$source" =~ (^\.$|^\.\.$|(\./|\.\./|~/|/)) ]]; then
-        get_path_ver "$source" "$opt_rep" "$opt_pkg"
-        left=$source
-    else
-        get_path_ver "$source" "$opt_rep" "$opt_pkg"
-        left=$result
-    fi
-    if [[ "$target" =~ (^\.$|^\.\.$|(\./|\.\./|~/|/)) ]]; then
-        right="$target"
-    else
-        get_path_ver "$target" "$opt_rep" "$opt_pkg"
-        right=$result
-    fi
-else
+  VF_ROOT=$HOME
+  VF_FVER=
+  VF_REPO=
+  VF_PKG=
+  VF_PATH=
+  VF_FN=
+  if [[ "$source" =~ (^\.$|^\.\.$|(\./|\.\./|~/|/)) ]]; then
+    get_path_ver "$source" "$opt_rep" "$opt_pkg"
     left=$source
-    right=$target
+  else
+    get_path_ver "$source" "$opt_rep" "$opt_pkg"
+    left=$result
+  fi
+  if [[ "$target" =~ (^\.$|^\.\.$|(\./|\.\./|~/|/)) ]]; then
+    right="$target"
+  else
+    get_path_ver "$target" "$opt_rep" "$opt_pkg"
+    right=$result
+  fi
+else
+  left=$source
+  right=$target
 fi
 if [ $opt_iar -gt 0 ]; then
-    exec_iar "$left" "$right"
+  exec_iar "$left" "$right"
 else
-    exec_os "$left" "$right"
+  exec_os "$left" "$right"
 fi
 exit $?
diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -8,14 +8,20 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2019 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
+export READLINK=readlink
+OS=$(uname -s)
+if [[ $OS == "Darwin" ]]; then
+  READLINK=$(which greadlink 2>/dev/null)
+  [[ -n "$READLINK" ]] && READLINK=$(basename $READLINK) || READLINK="echo 'greadlink not found\!'; exit 125;"
+fi
 THIS=$(basename "$0")
-TDIR=$(readlink -f $(dirname $0))
+TDIR=$($READLINK -f $(dirname $0))
 PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/devel_tools/devel_tools/../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib/z0lib; do
+for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc $TDIR/../z0lib $TDIR/../../z0lib $TDIR/../../z0lib/z0lib; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
     break
   fi
 done
@@ -80,12 +86,12 @@ process_yaml_init() {
   [[ -z $MQT_DBUSER ]] && export MQT_DBUSER==$(get_dbuser)
   python_ver_req=
   if [ $opt_dbgmnt -ne 0 ]; then
-    [[ -d $HOME/devel ]] \
-        && export YML_lisa=$HOME/devel/pypi/lisa/lisa/lisa \
-        || export YML_lisa=$HOME/dev/pypi/lisa/lisa/lisa
-    [[ -d $HOME/devel ]] \
-        && export YML_mgrodoo=$HOME/devel/pypi/clodoo/clodoo/manage_odoo \
-        || export YML_mgrodoo=$HOME/dev/pypi/clodoo/clodoo/manage_odoo
+    [[ -d $HOME/devel ]] && \
+      export YML_lisa=$HOME/devel/pypi/lisa/lisa/lisa || \
+      export YML_lisa=$HOME/dev/pypi/lisa/lisa/lisa
+    [[ -d $HOME/devel ]] && \
+      export YML_mgrodoo=$HOME/devel/pypi/clodoo/clodoo/manage_odoo || \
+      export YML_mgrodoo=$HOME/dev/pypi/clodoo/clodoo/manage_odoo
     (($opt_debug)) && export TRAVIS_PDB="true"
   else
     export YML_lisa=lisa
@@ -661,7 +667,7 @@ process_yaml_run_cmd() {
     if [ -z "$REPOSNAME" ]; then
       pp=$PKGPATH
     else
-      pp=$(readlink -e $PRJPATH/../$REPOSNAME/)
+      pp=$($READLINK -e $PRJPATH/../$REPOSNAME/)
     fi
     while [ -n "${x[$ix]}" ]; do
       if [[ "${x[$ix]}" =~ cd ]]; then
@@ -1090,7 +1096,7 @@ elif [[ $action =~ (wep_db|wep-db) ]]; then
         done=1
       done
     fi
-    ((md=60*60*24*90))
+    ((md = 60 * 60 * 24 * 90))
     for d in $LOGDIR/*; do
       dd=$(stat -c "%Y" $d)
       df=$(($dt - $dd))
diff --git a/z0lib/z0librc b/z0lib/z0librc
--- a/z0lib/z0librc
+++ b/z0lib/z0librc
@@ -3,7 +3,7 @@
 # Copyright (C) SHS-AV s.r.l. (<http://ww.zeroincombenze.it>)
 # This software is free software under GNU Affero GPL3
 # Bash general purpose library
-#__version__=1.0.0
+#__version__=1.0.0.1
 STS_FAILED=1
 STS_SUCCESS=0
 PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
@@ -42,6 +42,14 @@ _install_z0librc() {
 }
 export -f _install_z0librc
 
+ack_os() {
+    [[ -n "$READLINK" ]] && return
+    export READLINK=readlink
+    OS=$(uname -s)
+    [[ $OS == "Darwin" ]] && \
+      READLINK=$(which readlink 2>/dev/null) && \
+      [[ -n "$READLINK" ]] && READLINK=$(basename $READLINK) || READLINK="echo 'greadlink not found\!'; exit 125"
+}
 
 ##############################################################################
 # Detect and print more OS informations than uname command
@@ -95,6 +103,10 @@ xuname() {
     OSSTR="${OS} ${REV}(${ARCH} $(uname -v))"
   elif [ "${OS}" = "AIX" ]; then
     OSSTR="${OS} $(oslevel) ($(oslevel -r))"
+  elif [ "${OS}" = "Darwin" ]; then
+    DIST=$OS
+    FAMILY="osx"
+    OSSTR="${OS} ${VER}(${CODENAME} ${KERNEL} ${MACH})"
   elif [ "${OS}" = "Linux" ]; then
     KERNEL=$(uname -r)
     CODENAME=""
