[IMP] Minor improvements

diff --git a/devel_tools/please b/devel_tools/please
--- a/devel_tools/please
+++ b/devel_tools/please
@@ -11,25 +11,25 @@
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../.. $TDIR/../../z0lib $TDIR/../../z0lib/z0lib $HOME/devel $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
-  if [ -e $d/z0librc ]; then
+for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/devel_tools/devel_tools/../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib/z0lib; do
+  if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$d
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
     break
   fi
 done
-if [ -z "$Z0LIBDIR" ]; then
+if [[ -z "$Z0LIBDIR" ]]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/devel $HOME/dev ${PYPATH//:/ } . .." "clodoo")
+ODOOLIBDIR=$(findpkg odoorc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "clodoo")
 if [ -z "$ODOOLIBDIR" ]; then
   echo "Library file odoorc not found!"
   exit 2
 fi
 . $ODOOLIBDIR
-TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $HOME/tools/travis_emulator $HOME/devel $HOME/dev ${PYPATH//:/ } . .." "travis_emulator")
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
   exit 2
@@ -38,7 +38,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=1.0.0.3
+__version__=1.0.0.4
 
 #
 # General Purpose options:
@@ -75,24 +75,6 @@ __version__=1.0.0.3
 # -W whatis
 # -w wep
 
-get_dbuser() {
-  local u
-  for u in $USER odoo openerp postgresql; do
-    if [[ -n "$1" ]]; then
-      psql -U$u$1 -l &>/dev/null
-      if [ $? -eq 0 ]; then
-        opt_user="$u$1"
-        break
-      fi
-    fi
-    psql -U$u -l &>/dev/null
-    if [ $? -eq 0 ]; then
-      opt_user="$u"
-      break
-    fi
-  done
-}
-
 move() {
   # move(src dst)
   if [ -f "$2" ]; then rm -f $2; fi
@@ -105,6 +87,27 @@ move_n_bak() {
   if [ -f "$2.bak" ]; then rm -f $2.bak; fi
   run_traced "cp -p $2 $2.bak"
   run_traced "mv -f $1 $2"
+}
+
+search_pofile() {
+    srcs=$(find -L $odoo_root -not -path '*/__to_remove/*' -type d -name "$opt_modules")
+    f=0
+    for src in $srcs; do
+        if [ -n "$src" ]; then
+            if [ -f $src/i18n/it.po ]; then
+                src=$src/i18n/it.po
+                if [ $opt_exp -ne 0 ]; then
+                    run_traced "cp $src $src.bak"
+                fi
+                f=1
+                break
+            else
+                alt=$(find -L $src/i18n -name '*.po' | head -n1)
+                src=
+                if [ -n "$alt" ]; then fi=1 break; fi
+            fi
+        fi
+    done
 }
 
 add_copyright() {
@@ -1500,11 +1503,40 @@ do_annotate() {
   return $STS_FAILED
 }
 
-do_autopep8() {
-  wlog "Outdated function: autopep8"
-  return $STS_FAILED
+do_edit() {
+  #do_edit PKGNAME (pofile|translation|untranslated)
+  local cmd
+  wlog "do_edit $1 $2"
+  [[ -n "$2" ]] && cmd="do_edit_$2" || cmd="do_edit_$1"
+  sts=$STS_SUCCESS
+  if [ "$(type -t $cmd)" == "function" ]; then
+    eval $cmd "$@"
+  else
+    echo "Missing object! Use:"
+    echo "> please edit (pofile|translation|untranslated)"
+    sts=$STS_FAILED
+  fi
+  return $sts
 }
 
+do_edit_pofile() {
+  [[ -f "./i18n/it.po" ]] && run_traced "poedit ./i18n/it.po" || echo "No file it.po found!"
+  return $STS_STS_SUCCESS
+}
+
+do_edit_translation() {
+  local xfile
+  [[ -f "$HOME/dev/pypi/tools/odoo_default_tnl.xlsx" ]] && xfile="$HOME/dev/pypi/tools/odoo_default_tnl.xlsx"
+  [[ -f "$HOME/devel/pypi/tools/odoo_default_tnl.xlsx" ]] && xfile="$HOME/devel/pypi/tools/odoo_default_tnl.xlsx"
+  [[ -n "$xfile" ]] && run_traced "libreoffice $xfile" || echo "No file odoo_default_tnl.xlsx found!"
+  return $STS_STS_SUCCESS
+}
+
+do_edit_untranslated() {
+  local xfile
+  [[ -f "$HOME/odoo_default_tnl.csv" ]] && run_traced "libreoffice $HOME/odoo_default_tnl.csv" || echo "No file odoo_default_tnl.csv found!"
+  return $STS_STS_SUCCESS
+}
 create_pkglist() {
   # create_pkglist(pkgname type)
   local PKGLIST Z0LIB OELIB x
@@ -2216,31 +2248,52 @@ do_duplicate() {
 do_export() {
   wlog "do_export '$1' '$2' '$3'"
   local db module odoo_fver sts=$STS_FAILED
-  if [ "$PRJNAME" == "Odoo" ]; then
+  if [[ "$PRJNAME" == "Odoo" ]]; then
     module=$2
     db=$3
   else
     module=$1
     db=$2
   fi
-  [[ "$module" == '.' ]] && module=$PKGNAME
-  [[ -n "$opt_branch" ]] && odoo_fver=$opt_branch || odoo_fver=10.0
-  odoo_ver=$(echo $odoo_fver | grep -Eo [0-9]+ | head -n1)
-  # [[ -z "$db" ]] && db="tnl_odoo$odoover"
-  if [[ -z "$module" || -z "$db" ]]; then
-    echo "Missing parameters! use:"
-    echo "> do_export -bBRANCH 'MODULE' 'DB'"
+  if [[ -z "$module" || "$module" == '.' ]]; then
+    odoo_fver=$(build_odoo_param FULLVER '.')
+    pofile="$(build_odoo_param PKGPATH '.')/i18n/it.po"
+    module=$(build_odoo_param PKGNAME '.')
+  else
+    [[ -n "$opt_branch" ]] && odoo_fver=$opt_branch
+    pofile="$(find $HOME/$opt_branch -type d -name $module)/i18n/it.po"
+  fi
+  if [[ -z "$odoo_fver" ]]; then
+    echo "Missing Odoo branch! use:"
+    echo "$0 export -bBRANCH 'MODULE' 'DB'"
     return $STS_FAILED
   fi
-  get_dbuser $odoo_ver
-  stat=$(psql -U$opt_user -Atc "select state from ir_module_module where name = '$module'" $db)
-  if [[ $stat == "uninstalled" ]]; then
-    run_traced "run_odoo_debug -Wb$odoo_fver -Ism $module -d $db"
-  else
-    run_traced "run_odoo_debug -Wb$odoo_fver -usm $module -d $db"
+  odoo_ver=$(echo $odoo_fver | grep -Eo [0-9]+ | head -n1)
+  if [[ ! -f "$pofile" ]]; then
+    echo "File $pofile not found!"
+    return $STS_FAILED
   fi
-  sts=$?
-  [ $? -eq 0 ] && run_traced "run_odoo_debug -Wb$odoo_fver -em $module -d $db"
+  if [[ -z "$db" ]]; then
+    DBs=$(psql -Atl|awk -F'|' '{print $1}'|tr \"\\n\" '|')
+    DBs="^(${DBs:0: -1})\$"
+    for x in tnl test demo; do
+      [[ $x$odoo_ver =~ $DBs ]] && db="$x$odoo_ver" && break
+    done
+  fi
+  if [[ -z "$module" || -z "$db" ]]; then
+    echo "Parameters mismatch! use:"
+    echo "$0 export -bBRANCH 'MODULE' 'DB'"
+    return $STS_FAILED
+  fi
+  opt_user=$(get_dbuser $odoo_ver)
+  stat=$(psql -U$opt_user -Atc "select state from ir_module_module where name = '$module'" $db)
+  [[ $stat == "uninstalled" ]] && run_traced "run_odoo_debug -b$odoo_fver -Ism $module -d $db"
+  dbdt=$(psql -U$opt_user -Atc "select write_date from ir_module_module where name='$module' and state='installed'" $db)
+  [[ -n "$dbdt" ]] && dbdt=$(date -d "$dbdt" +"%s") || dbdt="999999999999999999"
+  echo "db_date=$dbdt"   #debug
+  podt=$(stat -c "%Y" $pofile)
+  ((dbdt < podt)) && run_traced "run_odoo_debug -b$odoo_fver -usm $module -d $db"
+  run_traced "run_odoo_debug -b$odoo_fver -em $module -d $db"
   sts=$?
   return $sts
 }
@@ -2278,32 +2331,70 @@ do_list() {
     fi
   done
 }
+
 do_translate() {
   wlog "do_translate '$1' '$2' '$3'"
-  local confn db module odoo_fver sts=$STS_FAILED dbg
-  if [ "$PRJNAME" == "Odoo" ]; then
+  local confn db module odoo_fver sts=$STS_FAILED opts pyv pofile
+  if [[ "$PRJNAME" == "Odoo" ]]; then
     module=$2
     db=$3
   else
     module=$1
     db=$2
   fi
-  [[ "$module" == '.' ]] && module=$PKGNAME
-  [ -n "$opt_branch" ] && odoo_fver=$opt_branch || odoo_fver=10.0
-  [ -n "$opt_conf" ] && conf=$opt_conf
-  [ -z "$opt_conf" ] && confn=$HOME/clodoo/confs/${odoo_fver/./-}.conf
-  if [ ! -f $confn ]; then
+  if [[ -z "$module" || "$module" == '.' ]]; then
+    odoo_fver=$(build_odoo_param FULLVER '.')
+    pofile="$(build_odoo_param PKGPATH '.')/i18n/it.po"
+    module=$(build_odoo_param PKGNAME '.')
+  else
+    [[ -n "$opt_branch" ]] && odoo_fver=$opt_branch
+    pofile="$(find $HOME/$opt_branch -type d -name $module)/i18n/it.po"
+  fi
+  if [[ -z "$odoo_fver" ]]; then
+    echo "Missing Odoo branch! use:"
+    echo "$0 export -bBRANCH 'MODULE' 'DB'"
+    return $STS_FAILED
+  fi
+  odoo_ver=$(echo $odoo_fver | grep -Eo [0-9]+ | head -n1)
+  if [[ ! -f "$pofile" ]]; then
+    echo "File $pofile not found!"
+    return $STS_FAILED
+  fi
+  [[ -n "$opt_conf" ]] && conf=$opt_conf
+  [[ -z "$opt_conf" ]] && confn=$HOME/clodoo/confs/${odoo_fver/./-}.conf
+  if [[ ! -f $confn ]]; then
     echo "Configuration file $confn not founcd!"
     return $STS_FAILED
   fi
-  if [ -z "$module" -o -z "$db" ]; then
-    echo "Missing parameters! use:"
-    echo "> do_translate -bBRANCH 'MODULE' 'DB'"
+  if [[ -z "$db" ]]; then
+    DBs=$(psql -Atl|awk -F'|' '{print $1}'|tr \"\\n\" '|')
+    DBs="^(${DBs:0: -1})\$"
+    for x in tnl test demo; do
+      [[ $x$odoo_ver =~ $DBs ]] && db="$x$odoo_ver" && break
+    done
+  fi
+  if [[ -z "$module" || -z "$db" ]]; then
+    echo "Parameters mismatch! use:"
+    echo "$0 export -bBRANCH 'MODULE' 'DB'"
     return $STS_FAILED
   fi
+  if [[ ! -d $HOME/clodoo ]]; then
+    echo "Missed environment!"
+    echo "Directory clodoo not found!"
+    return $STS_FAILED
+  fi
+  pyv=$(python3 --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
+  [[ -n "$pyv" ]] && pyver="-p $pyv"
+  pyver="-p 2.7"    #debug
+  [[ ! -d $HOME/clodoo/venv ]] \
+    && run_traced "vem $pyver create $HOME/clodoo/venv" \
+    && run_traced "vem $HOME/clodoo/venv install xlrd" \
+    && run_traced "vem $HOME/clodoo/venv install Babel" \
+    && run_traced "vem $HOME/clodoo/venv install clodoo"
   run_traced "pushd $HOME/clodoo >/dev/null"
-  [ $opt_dbg -ne 0 ] && dbg="-B" || dbg=
-  run_traced "odoo_translation.py $dbg -b$odoo_fver -m $module -d $db -c $confn"
+  [ $opt_verbose -ne 0 ] && opts="-v" || opts="-q"
+  [ $opt_dbg -ne 0 ] && opts="${opts}B"
+  run_traced "vem $HOME/clodoo/venv exec \"odoo_translation.py $opts -b$odoo_fver -m $module -d $db -c $confn -p $pofile\""
   sts=$?
   run_traced "popd >/dev/null"
   return $sts
@@ -2757,7 +2848,7 @@ if [ "$opt_version" ]; then
   echo "$__version__"
   exit 0
 fi
-HLPCMDLIST="help|build|chkconfig|[commit|config|distribution|docs|download_rep|duplicate|export|import|list|lsearch|publish|push|pythonhosted|synchro|replace|replica|showdoc|status|test|translate|version|wep"
+HLPCMDLIST="help|build|chkconfig|[commit|config|distribution|docs|download_rep|duplicate|edit|export|import|list|lsearch|publish|push|pythonhosted|synchro|replace|replica|showdoc|status|test|translate|version|wep"
 if [ $opt_help -gt 0 ]; then
   print_help "Developer shell\nAction may be on of:\n$HLPCMDLIST" \
     "© 2015-2020 by zeroincombenze®\nhttps://zeroincombenze-tools.readthedocs.io/\nAuthor: antoniomaria.vigliotti@gmail.com"
diff --git a/devel_tools/topep8 b/devel_tools/topep8
--- a/devel_tools/topep8
+++ b/devel_tools/topep8
@@ -6,33 +6,33 @@
 # (C) 2015-20 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])" | python)
-for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../.. $TDIR/../../z0lib $TDIR/../../z0lib/z0lib $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
-    if [ -e $d/z0librc ]; then
-        . $d/z0librc
-        Z0LIBDIR=$d
-        Z0LIBDIR=$(readlink -e $Z0LIBDIR)
-        break
-    fi
+PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
+for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/devel_tools/devel_tools/../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib /home/odoo/devel/pypi/devel_tools/devel_tools/../../z0lib/z0lib; do
+  if [[ -e $d/z0librc ]]; then
+    . $d/z0librc
+    Z0LIBDIR=$d
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
 done
-if [ -z "$Z0LIBDIR" ]; then
-    echo "Library file z0librc not found!"
-    exit 2
+if [[ -z "$Z0LIBDIR" ]]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/dev ${PYPATH//:/ } . .." "clodoo")
+ODOOLIBDIR=$(findpkg odoorc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "clodoo")
 if [ -z "$ODOOLIBDIR" ]; then
-    echo "Library file odoorc not found!"
-    exit 2
+  echo "Library file odoorc not found!"
+  exit 2
 fi
 . $ODOOLIBDIR
-TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $HOME/tools/travis_emulator $HOME/dev ${PYPATH//:/ } . .." "travis_emulator")
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
-    echo "Library file travisrc not found!"
-    exit 2
+  echo "Library file travisrc not found!"
+  exit 2
 fi
 . $TRAVISLIBDIR
 
-__version__=1.0.0.3
+__version__=1.0.0.4
 
 [ -f $TDIR/../../clodoo/list_requirements.py ] && LISTREQ=$TDIR/../../clodoo/list_requirements.py || LISTREQ=list_requirements.py
 YAML_TMPL=~/dev/pypi/z0bug_odd/z0bug_odoo/sample_files/.travis.yml
