[IMP] MQT statements to adapt to TravisCI

diff --git a/devel_tools/pull_from_oca b/devel_tools/pull_from_oca
--- a/devel_tools/pull_from_oca
+++ b/devel_tools/pull_from_oca
@@ -35,25 +35,67 @@ if [ -z "$ODOOLIBDIR" ]; then
 fi
 . $ODOOLIBDIR
 
-__version__=0.2.2.16
+__version__=0.2.2.17
+
+
+do_edit_module() {
+# do_edit_module(tgtpath)
+    local tgtpath=$1
+    local fn lm ln x
+    if [ -f $tgtpath/odoo/addons/base/module/module.py ]; then
+      fn=$tgtpath/odoo/addons/base/module/module.py
+    elif [ -f $tgtpath/openerp/addons/base/module/module.py ]; then
+      fn=$tgtpath/openerp/addons/base/module/module.py
+    else
+      echo "File module.py not found!"
+      return
+    fi
+    grep -q "antoniov.*Avoid translation error" $fn
+    [ $? -eq 0 ] && return
+    ln=$(grep "output = publish_string" $fn)
+    lm=$(echo "$ln"|grep -Eo "^[ ]+")
+    lm=${lm// /\\ }
+    x="${lm}# [antoniov 2018-09-04] Avoid translation error"
+    run_traced "sed \"/output = publish_string/i$x\" -i $fn"
+    x="${lm}try:"
+    run_traced "sed \"/output = publish_string/i$x\" -i $fn"
+    run_traced "sed -e \"s/output = publish_string/    output = publish_string/\" -i $fn"
+    x="${lm}\ \ \ \ output = 'Error in Description'"
+    run_traced "sed \"/output = publish_string/a$x\" -i $fn"
+    x="${lm}except:"
+    run_traced "sed \"/output = publish_string/a$x\" -i $fn"
+}
 
 
 sync_tmp_2_tgt() {
 # sync_tmp_2_tgt(tmpdir tgtpath repo)
-    local b d dlist f flist l t1
+    local b d dlist f fn flist l t1 OPTS
     local tmpdir=$1
     local tgtpath=$2
     local repo=$3
-    # [ "${rep: -1}" == "/" ] && rep=${rep:0: -1}
-    # echo -en "$TRAVIS_HDR2_COLOR"
+    [ $opt_dry_run -ne 0 ] && OPTS=${OPTS}n
+    [ -n "$OPTS" ] && OPTS="-$OPTS"
+    OCB_SUBDIRS_RE=$(build_odoo_param OCB_SUBDIRS_RE)
+    OCB_SUBDIRS_RE="${OCB_SUBDIRS_RE:0: -2}|.git|.github)\$"
+    run_traced "shopt -s dotglob"
     if [ "$repo" == "OCB" ]; then
-      run_traced "shopt -s dotglob; rsync -a --ignore-existing $tgtpath/ $tmpdir/"
+      for fn in $tgtpath/*; do
+        b=$(basename $fn)
+        [[ $b =~ .*\.bak$ || "$b" == "__to_remove" ]] && continue
+        if [ -f "$fn" ]; then
+          run_traced "cp $fn $tmpdir/$b"
+        else
+          if [[ $b =~ $OCB_SUBDIRS_RE ]]; then
+            run_traced "rsync -a --ignore-existing $fn/ $tmpdir/$b"
+          fi
+        fi
+      done
     else
-      run_traced "shopt -s dotglob; rsync -a --ignore-existing $tgtpath/ $tmpdir/$rep/"
+      run_traced "rsync -a --ignore-existing $tgtpath/ $tmpdir/"
     fi
-    # echo -en "$TRAVIS_NOP_COLOR"
     l=${#tgtpath}
-    dlist=$(find $tmpdir/$rep -type d -name readme|tr "\n" " ")
+    ((l++))
+    dlist=$(find $tmpdir -maxdepth 2 -type d -name readme|tr "\n" " ")
     for d in $dlist; do
       t1=$(dirname $d)
       if [ ! -d $t1/egg-info ]; then
@@ -76,35 +118,48 @@ sync_tmp_2_tgt() {
         run_traced "rm -fR $d"
       fi
     done
-    flist=$(find $tgtpath -type f -exec grep -l "antoniov" '{}' \;)
+    flist=$(find $tgtpath -maxdepth 2 -type f -exec grep -l "antoniov" '{}' \;)
     for f in $flist; do
       t=${f:l}
-      t=${tmpdir}/${rep}$t
+      t=${tmpdir}/$t
       t1=($dirname $t)
-      run_traced "cp -f $f $t1"
+      [ -f $t1 ] && run_traced "mv $t1 $t1.bak"
+      run_traced "cp -f $f $t1  # Modificed file by Antoniov"
     done
-    [ -d $tmpdir/$rep/setup ] && run_traced "rm -fR $tmpdir/$rep/setup"
+    [ -d $tmpdir/setup ] && run_traced "rm -fR $tmpdir/setup"
     [ -d $tgtpath.bak ] && run_traced "rm -fR $tgtpath.bak"
-    d=$(dirname $tgtpath)
-    [ ! -d $d/__to_remove ] && run_traced "mkdir __to_remove"
-    [ -d $d/__to_remove/$rep ] && run_traced "rm -fR $d/__to_remove/$rep"
-    run_traced "mv $tgtpath $d/__to_remove/$rep"
-    run_traced "mv $tmpdir/$rep $tgtpath"
-    run_traced "~/regen_all_docs.sh $tgtpath zero"
+    [ -d $tmpdir/doc/cla ] && run_traced "rm -fR $tmpdir/doc/cla"
+    if [ "$repo" == "OCB" ]; then
+      d=$tmpdir
+      [ -d $d/__to_remove ] && run_traced "rm -fR $d/__to_remove"
+      run_traced "mv $tgtpath $d/__to_remove"
+    else
+      d=$(dirname $tgtpath)
+      [ ! -d $d/__to_remove ] && run_traced "mkdir $d/__to_remove"
+      [ -d $d/__to_remove/$repo ] && run_traced "rm -fR $d/__to_remove/$repo"
+      run_traced "mv $tgtpath $d/__to_remove/$repo"
+    fi
+    run_traced "mv $tmpdir $tgtpath"
+    if [ "$repo" == "OCB" ]; then
+      run_traced "odoo_skin.sh $tgtpath zeroincombenze $OPTS"
+      do_edit_module $tgtpath
+    fi
+    $TDIR/regen_all_docs $tgtpath zero $OPTS
 }
 
-OPTOPTS=(h        b          D        H           n           V           v)
-OPTDEST=(opt_help opt_branch opt_drop opt_humdrum opt_dry_run opt_version opt_verbose)
-OPTACTI=(1        "="        1        1           1           "*>"        "+")
-OPTDEFL=(0        ""         0        0           0           ""          -1)
-OPTMETA=("help"   "branch"   ""       ""          ""          ""          "")
+OPTOPTS=(h        b          D        H           n           V           v           y)
+OPTDEST=(opt_help opt_branch opt_drop opt_humdrum opt_dry_run opt_version opt_verbose opt_yes)
+OPTACTI=(1        "="        1        1           1           "*>"        "+"         1)
+OPTDEFL=(0        ""         0        0           0           ""          -1          0)
+OPTMETA=("help"   "branch"   ""       ""          ""          ""          ""          "")
 OPTHELP=("this help"\
  "branches: may be one or more of 6.1 7.0 8.0 9.0 10.0 11.0 or 12.0"\
  "drop oca repository before upgrade"\
  "humdrum, display w/o colors"\
  "do nothing (dry-run)"\
  "show version"\
- "verbose mode")
+ "verbose mode"\
+ "assume yes")
 OPTARGS=(tgtpath)
 
 parseoptargs "$@"
@@ -138,47 +193,47 @@ else
   TRAVIS_NOP_COLOR=
 fi
 
-
-INVALID_MODNAMES_RE=$(build_odoo_param INVALID_MODNAMES_RE)
-INVALID_MODNAMES_RE="${INVALID_MODNAMES_RE:0: -2}|profiles|uncovered|openupgrade)\$"
+[ "${tgtpath: -1}" == "/" ] && tgtpath=${tgtpath:0: -1}
 if [ ! -d $tgtpath ]; then
   echo "Directory $tgtpath not found!"
   exit 1
 fi
+[ "$PWD" == "$tgtpath" ] && cd $HOME
 tgt_odoo_dir=$(dirname $tgtpath)
-tgt_odoo_fver=$(build_odoo_param FULLVER "$tgtpath")
-if [ "$tgt_odoo_fver" != "$opt_branch" ]; then
-  echo "Directory $tgtpath is $tgt_odoo_fver: not for Odoo $opt_branch!"
+odoo_fver=$(build_odoo_param FULLVER "$tgtpath")
+if [ "$odoo_fver" != "$opt_branch" ]; then
+  echo "Directory $tgtpath is $odoo_fver: not for Odoo $opt_branch!"
   exit 1
 fi
-odoo_ver=$(build_odoo_param MAJVER "$tgt_odoo_fver")
+odoo_ver=$(build_odoo_param MAJVER "$odoo_fver")
 repo=$(build_odoo_param REPOS "$tgtpath")
-[ "$repo" != "OCB" ] && src_odoo=$HOME/oca$odoo_ver/$repo || src_odoo=$HOME/oca$odoo_ver
-if [ ! -d $src_odoo ]; then
-  echo "Odoo source repository $src_odoo not found!"
+[ "$repo" != "OCB" ] && src_oca=$HOME/oca$odoo_ver/$repo || src_oca=$HOME/oca$odoo_ver
+if [ ! -d $src_oca ]; then
+  echo "Odoo source repository $src_oca not found!"
   exit 1
+fi
+echo "Upgrade repository $repo from $src_oca to $tgtpath ..."
+if [ $opt_yes -eq 0 ]; then
+  read -p "Proceed (yes/no)? " dummy
+  if [[ -z "$dummy" || ! "$dummy" == "yes" ]]; then
+    echo "Command aborted."
+    exit 0
+  fi
 fi
 tmpdir=$HOME/tmp
-echo "Upgrade repository $repo from $src_odoo to $tgtpath ..."
-read -p "Proceed (yes/no)? " dummy
-if [[ -z "$dummy" || ! "$dummy" = "yes" ]]; then
-  echo "Command aborted."
-  exit 0
-fi
-mkdir -p $tmpdir
-[ -d $tmpdir/$repo ] && rm -fR $tmpdir/$repo
+[ ! -d $tmpdir ] && run_traced "mkdir -p $tmpdir"
+[ "$repo" != "OCB" ] && tmp_odoo=$tmpdir/$repo || tmp_odoo=$tmpdir/$odoo_fver
+[ "$PWD" == "$tmp_odoo" ] && cd $HOME
 OPTS=
 [ $opt_dry_run -ne 0 ] && OPTS=${OPTS}n
 [ -n "$OPTS" ] && OPTS="-$OPTS"
-# echo -en "$TRAVIS_HDR1_COLOR"
-if [ "$repo" != "OCB" ]; then
-  if [ $opt_drop -ne 0 ]; then
-    run_traced "odoo_install_repository -b$opt_branch $repo -Ooca -o $HOME/oca$odoo_ver/$repo -Cqy $OPTS"
-  else
-    run_traced "odoo_install_repository -b$opt_branch $repo -Ooca -o $HOME/oca$odoo_ver/$repo -UCq $OPTS"
-  fi
+[ -d $tmp_odoo ] && run_traced "rm -fR $tmp_odoo"
+if [ $opt_drop -ne 0 ]; then
+  run_traced "odoo_install_repository -b$opt_branch $repo -Ooca -o $tmp_odoo -Cqy $OPTS"
+else
+  run_traced "mkdir $tmp_odoo"
+  run_traced "shopt -u dotglob; rsync -aC --exclude='.*' $src_oca/ $tmp_odoo/"
 fi
-# echo -en "$TRAVIS_HDR1_COLOR"
-run_traced "shopt -u dotglob; rsync -aC --exclude=".*" $src_odoo/ $tmpdir/$repo/"
-# echo -en "$TRAVIS_NOP_COLOR"
-sync_tmp_2_tgt $tmpdir $tgtpath
+[ $opt_dry_run -ne 0 ] && mkdir -p $tmp_odoo
+sync_tmp_2_tgt $tmp_odoo $tgtpath $repo
+run_traced "shopt -u dotglob"
