[IMP] New enhancements in order to manage Odoo 11

diff --git a/maintainer-quality-tools/travis/travis_install_env b/maintainer-quality-tools/travis/travis_install_env
--- a/maintainer-quality-tools/travis/travis_install_env
+++ b/maintainer-quality-tools/travis/travis_install_env
@@ -30,7 +30,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.1.34
+__version__=0.2.1.35
 
 
 cp_n_upd_odoo_conf() {
@@ -145,11 +145,12 @@ if [ "${LINT_CHECK:-1}" == "0" ]; then LINT_CHECK_DISABLED=1; else LINT_CHECK_DI
 if [ "${TESTS:-0}" == "1" ]; then TEST_CHECK_ENABLED=1; else TEST_CHECK_ENABLED=0; fi
 if [ -z "${TESTS}" ]; then TESTS_UNSPECIFIED=1; else TESTS_UNSPECIFIED=0; fi
 if [ "${TRANSIFEX_CHECK:-0}" == "1" ]; then TRANSIFEX_CHECK_ENABLED=1; else TRANSIFEX_CHECK_ENABLED=0; fi
-[ -z "MQT_TEST_MODE" ] && IFS="/" read MQT_TEST_MODE dummy <<< "${TRAVIS_REPO_SLUG}"
+[ -z "MQT_TEST_MODE" ] && IFS="/" read MQT_TEST_MODE PKGNAME <<< "${TRAVIS_REPO_SLUG}"
 MQT_TEST_MODE=${MQT_TEST_MODE,,}
 [[ ! " oca oia zero " =~ " $MQT_TEST_MODE " ]] && MQT_TEST_MODE=zero
 [ -z "$mode" ] && mode=$MQT_TEST_MODE
 export MQT_TEST_MODE=$mode
+[ -z "$PKGNAME" ] && PKGNAME=$(basename $TRAVIS_BUILD_DIR)
 PIP=pip
 if [ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]; then
   [ -f /usr/bin/pip3.6 ] && PIP=/usr/bin/pip3.6
@@ -192,65 +193,7 @@ if [ "$MQT_TEST_MODE" == "tools" ]; then
     fi
   done
   exit $sts
-elif [ "${TESTS}" != "1" ]; then
-  [ -z "${VERSION}" ] &&  VERSION="$opt_branch"
-  [ -z "${ODOO_BRANCH}"  ] && export ODOO_BRANCH=${VERSION}
-  [ $opt_verbose -gt 0 ] && echo "- breqs=\$($LISTREQ -b$VERSION -p'.' $dopts -t bin -s ' ' -qT)"
-  breqs=$($LISTREQ -b$VERSION -p'.' $dopts -t bin -s ' ' -qT)
-  [ $opt_verbose -gt 0 ] && echo "\$ breqs=$breqs"
-  for f in $breqs; do
-    [ $opt_verbose -gt 0 ] && echo "\$ $LISA install-if $f"
-    pkg=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|head -n1)
-    if [[ $HOSTNAME =~ shs[a-z0-9]+ && "$USER" == "odoo" && "$opt_pyver" != "3"  ]]; then
-      :
-    elif [ "$f" == "$pkg" ]; then
-      eval $LISA status -q $f
-      [ $? -ne 0 ] && run_traced "$LISA install -q $opts $f"
-    fi
-  done
-  [ $opt_verbose -gt 0 ] && echo "- preqs=\$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPT)"
-  preqs="$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPT)"
-  [ $opt_verbose -gt 0 ] && echo "\$ preqs=$preqs"
-  for f in $preqs; do
-    op=$(echo "$f"|grep -Eo '[<=>]*'|head -n1)
-    pkg=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|head -n1)
-    reqver=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|tr "\n" " "|awk '{print $2}')
-    sts=0
-    eval $LISA status -q $f
-    sts=$?
-    if [ $sts -eq 1 ] || [ -n "$reqver" ]; then
-      [ $sts -eq 0 ] && curver=$(pip show $pkg|grep ^[Vv]ersion|awk -F: '{print $2}'|tr -d ', \r\n\(\)') || curver=
-      if [[ (-z "$op" && $sts > 0) || ($op == "==" && ! $curver == $reqver) || ($op == "<" && ! $curver < $reqver) || ($op == ">" && ! $curver > $reqver) || ($op == ">=" && $curver < $reqver) || ($op == "<=" && $curver > $reqver) ]]; then
-        cmd="$PIP install -q $f --upgrade"
-        [ $EUID -ne 0 ] && cmd="$cmd --user"
-        echo "- Update '$pkg' version '$curver' with version '$reqver'"
-        if [ ${TRAVIS_DEBUG_MODE:-0} -gt 1 ]; then
-          echo "> $cmd"
-        else
-          run_traced "$cmd"
-        fi
-      fi
-    fi
-  done
-  for f in $preqs; do
-    op=$(echo "$f"|grep -Eo '[<=>]*'|head -n1)
-    pkg=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|head -n1)
-    reqver=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|tr "\n" " "|awk '{print $2}')
-    if [ -n "$reqver" ]; then
-      curver=$($PIP show $pkg|grep ^[Vv]ersion|awk -F: '{print $2}'|tr -d ', \r\n\(\)')
-      if [[ ($op == "==" && ! $curver == $reqver) || ($op == "<" && ! $curver < $reqver) || ($op == ">" && ! $curver > $reqver) || ($op == ">=" && $curver < $reqver) || ($op == "<=" && $curver > $reqver) ]]; then
-        echo "- Update '$pkg' version '$curver' with version '$reqver'"
-        if [ $EUID -eq 0 ]; then
-          run_traced "$PIP install -q $f --upgrade --no-deps"
-        else
-          run_traced "$PIP install -q $f --upgrade --no-deps --user"
-        fi
-      fi
-    fi
-  done
-  exit $sts
-fi
-if [ "$TRAVIS" == "true" -a "$MQT_TEST_MODE" == "oca" ]; then
+elif [ "$TRAVIS" == "true" -a "$MQT_TEST_MODE" == "oca" ]; then
   [ $opt_verbose -gt 0 ] && echo "\$ $TDIR/travis_install_nightly"
   eval $TDIR/travis_install_nightly
 else
@@ -259,75 +202,131 @@ else
   : ${MQT_TEMPLATE_DB:="openerp_template"}
   : ${MQT_TEST_DB:="openerp_test"}
   : ${ODOO_REPO:="odoo/odoo"}
-  if [[ ! "$TRAVIS" == "true" ]]; then
-    pg_db_active -a $MQT_TEMPLATE_DB -w; dropdb $MQT_TEMPLATE_DB
-    pg_db_active -a $MQT_TEST_DB -w; dropdb $MQT_TEST_DB
-  fi
-  x=$(which nodejs 2>/dev/null)
-  [[ -z "$x" ]] && x=$(which node 2>/dev/null)
-  echo "\$ ln -s $x $HOME/maintainer-quality-tools/travis/node"
-  ln -s $x $HOME/maintainer-quality-tools/travis/node
   IFS="/" read -a REPO <<< "${ODOO_REPO}"
   export REMOTE="${REPO[0],,}"
   export REPO_NAME="${REPO[1]}"
   export BRANCH="${ODOO_BRANCH}"
   [[ $BRANCH == *"/"*  ]] && export BRANCH=${BRANCH/\//-}
-  PGKNAME=$(basename $TRAVIS_BUILD_DIR)
   export ODOO_PATH=${HOME}/$REPO_NAME-$ODOO_BRANCH
-  if [[ "$TRAVIS" == "true" ]]; then
-    if [[ "$PGKNAME" == "OCB" ]]; then
-      echo "- Tested repository is OCB: ln -s ${TRAVIS_BUILD_DIR} ${ODOO_PATH}"
+  if [ "${TESTS}" == "1" ]; then
+    if [[ ! "$TRAVIS" == "true" ]]; then
+      pg_db_active -wa $MQT_TEMPLATE_DB; dropdb $MQT_TEMPLATE_DB
+      pg_db_active -wa $MQT_TEST_DB; dropdb $MQT_TEST_DB
+    fi
+    x=$(which nodejs 2>/dev/null)
+    [[ -z "$x" ]] && x=$(which node 2>/dev/null)
+    echo "\$ ln -s $x $HOME/maintainer-quality-tools/travis/node"
+    ln -s $x $HOME/maintainer-quality-tools/travis/node
+    if [[ "$PKGNAME" == "OCB" ]]; then
+      if [[ "$TRAVIS" == "true" ]]; then
+        echo "- Tested repository is OCB: ln -s ${TRAVIS_BUILD_DIR} ${ODOO_PATH}"
+      else
+        [ $opt_verbose -gt 0 ] && echo "- Tested repository is OCB: ln -s ${TRAVIS_BUILD_DIR} ${ODOO_PATH}"
+      fi
       ln -s ${TRAVIS_BUILD_DIR} ${ODOO_PATH}
     else
-      export ODOO_URL="https://github.com/$REMOTE/$REPO_NAME/archive/$BRANCH.tar.gz"
-      echo "- Installing Odoo $ODOO_URL"
-      wget -nv -O odoo.tar.gz $ODOO_URL
-      tar -xf odoo.tar.gz -C ${HOME}
+      if [[ "$TRAVIS" == "true" ]]; then
+        export ODOO_URL="https://github.com/$REMOTE/$REPO_NAME/archive/$BRANCH.tar.gz"
+        echo "- Installing Odoo $ODOO_URL"
+        wget -nv -O odoo.tar.gz $ODOO_URL
+        tar -xf odoo.tar.gz -C ${HOME}
+      else
+        [ $opt_verbose -gt 0 ] && echo "\$ ln -s $TRAVIS_SAVED_HOME/$BRANCH ${ODOO_PATH}"
+        ln -s $TRAVIS_SAVED_HOME/$BRANCH ${ODOO_PATH}
+      fi
     fi
     eval $PIP install --upgrade pip
-  else
-    if [[ "$PGKNAME" == "OCB" ]]; then
-      [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ] && echo "- Tested repository is OCB: ln -s ${TRAVIS_BUILD_DIR} ${ODOO_PATH}"
-      ln -s ${TRAVIS_BUILD_DIR} ${ODOO_PATH}
-    else
-      [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ] && echo "\$ ln -s $TRAVIS_SAVED_HOME/$BRANCH ${ODOO_PATH}"
-      ln -s $TRAVIS_SAVED_HOME/$BRANCH ${ODOO_PATH}
+    mkdir -p ${HOME}/dependencies
+    cp_n_upd_odoo_conf
+    [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ] && echo "\$ $TDIR/clone_oca_dependencies"
+    eval $TDIR/clone_oca_dependencies
+    sts=$?
+    if [ $sts -ne 0 ]; then
+      echo "- Error cloning dependencies"
+      exit $sts
     fi
-  fi
-  mkdir -p ${HOME}/dependencies
-  cp_n_upd_odoo_conf
-  [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ] && echo "\$ $TDIR/clone_oca_dependencies"
-  eval $TDIR/clone_oca_dependencies
-  sts=$?
-  if [ $sts -ne 0 ]; then
-    echo "- Error cloning dependencies"
-    exit $sts
-  fi
-  if [[ "$PGKNAME" == "OCB" ]]; then
-    dependecies_dir=${HOME}/dependencies
-  else
-    dependecies_dir=${ODOO_PATH},${HOME}/dependencies
-  fi
-  [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ] && echo "\$ $MGRODOO requirements -b'.' -vsy -O$MQT_TEST_MODE -p${TRAVIS_PYTHON_VERSION:0:1}"
-  eval $MGRODOO requirements -b'.' -vsy -O$MQT_TEST_MODE -p${TRAVIS_PYTHON_VERSION:0:1}
-  [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ] && echo "\$ cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc ."
-  cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .
-  if [ $opt_verbose -gt 0 -o "${TRAVIS_DEBUG_MODE:-0}" -ne 0 ]; then
-    echo "- preqs=\$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPBTR)"
-    preqs="$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPBTR)"
-    for f in $preqs; do
-      preqs=$(echo "$preqs"|tr " " "\n"|sort|tr "\n" " ")
-      for pkg in $L; do
-        v=$($PIP show $pkg|grep "^[Vv]ersion")
-        echo "-- $pkg $v"
+    if [[ "$PKGNAME" == "OCB" ]]; then
+      dependencies_dir=${HOME}/dependencies
+    else
+      dependencies_dir=${ODOO_PATH},${HOME}/dependencies
+    fi
+    dopts="-O$dependencies_dir"
+    [ $opt_verbose -gt 0 ] && echo "\$ $MGRODOO requirements -b'.' $dopts -vsy -O$MQT_TEST_MODE -p${TRAVIS_PYTHON_VERSION:0:1}"
+    eval $MGRODOO requirements -b'.' $dopts -vsy -O$MQT_TEST_MODE -p${TRAVIS_PYTHON_VERSION:0:1}
+    [ $opt_verbose -gt 0 ] && echo "\$ cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc ."
+    cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .
+    if [ $opt_verbose -gt 0 ]; then
+      echo "- reqs=\$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPBTR)"
+      reqs="$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPBTR)"
+      for f in $reqs; do
+        reqs=$(echo "$reqs"|tr " " "\n"|sort|tr "\n" " ")
+        for pkg in $L; do
+          v=$($PIP show $pkg|grep "^[Vv]ersion")
+          echo "-- $pkg $v"
+        done
       done
+      echo "Content of ${HOME}:"
+      ls -l ${HOME}
+      echo "Content of ${TRAVIS_BUILD_DIR}:"
+      ls -l ${TRAVIS_BUILD_DIR}
+      echo "Content of ${HOME}/dependencies:"
+      ls -l ${HOME}/dependencies
+    fi
+  else
+    dopts=
+    [ $opt_verbose -gt 0 ] && echo "- reqs=\$($LISTREQ -b$VERSION -p'.' $dopts -t bin -s ' ' -qT)"
+    reqs=$($LISTREQ -b$VERSION -p'.' $dopts -t bin -s ' ' -qT)
+    [ $opt_verbose -gt 0 ] && echo "\$ reqs=$reqs"
+    for f in $reqs; do
+      [ $opt_verbose -gt 0 ] && echo "\$ $LISA install-if $f"
+      pkg=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|head -n1)
+      if [[ $HOSTNAME =~ shs[a-z0-9]+ && "$USER" == "odoo" && "$opt_pyver" != "3"  ]]; then
+        :
+      elif [ "$f" == "$pkg" ]; then
+        eval $LISA status -q $f
+        [ $? -ne 0 ] && run_traced "$LISA install -q $opts $f"
+      fi
     done
-    echo "Content of ${HOME}:"
-    ls -l ${HOME}
-    echo "Content of ${TRAVIS_BUILD_DIR}:"
-    ls -l ${TRAVIS_BUILD_DIR}
-    echo "Content of ${HOME}/dependencies:"
-    ls -l ${HOME}/dependencies
+    [ $opt_verbose -gt 0 ] && echo "- reqs=\$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPT)"
+    reqs="$($LISTREQ -b$VERSION -p'.' $dopts -t python -s ' ' -qPT)"
+    [ $opt_verbose -gt 0 ] && echo "\$ reqs=$reqs"
+    for f in $reqs; do
+      op=$(echo "$f"|grep -Eo '[<=>]*'|head -n1)
+      pkg=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|head -n1)
+      reqver=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|tr "\n" " "|awk '{print $2}')
+      sts=0
+      eval $LISA status -q $f
+      sts=$?
+      if [ $sts -eq 1 ] || [ -n "$reqver" ]; then
+        [ $sts -eq 0 ] && curver=$(pip show $pkg|grep ^[Vv]ersion|awk -F: '{print $2}'|tr -d ', \r\n\(\)') || curver=
+        if [[ (-z "$op" && $sts > 0) || ($op == "==" && ! $curver == $reqver) || ($op == "<" && ! $curver < $reqver) || ($op == ">" && ! $curver > $reqver) || ($op == ">=" && $curver < $reqver) || ($op == "<=" && $curver > $reqver) ]]; then
+          cmd="$PIP install -q $f --upgrade"
+          [ $EUID -ne 0 ] && cmd="$cmd --user"
+          echo "- Update '$pkg' version '$curver' with version '$reqver'"
+          if [ ${TRAVIS_DEBUG_MODE:-0} -gt 1 ]; then
+            echo "> $cmd"
+          else
+            run_traced "$cmd"
+          fi
+        fi
+      fi
+    done
+    for f in $reqs; do
+      op=$(echo "$f"|grep -Eo '[<=>]*'|head -n1)
+      pkg=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|head -n1)
+      reqver=$(echo "$f"|grep -Eo '[^!<=>\\[]*'|tr "\n" " "|awk '{print $2}')
+      if [ -n "$reqver" ]; then
+        curver=$($PIP show $pkg|grep ^[Vv]ersion|awk -F: '{print $2}'|tr -d ', \r\n\(\)')
+        if [[ ($op == "==" && ! $curver == $reqver) || ($op == "<" && ! $curver < $reqver) || ($op == ">" && ! $curver > $reqver) || ($op == ">=" && $curver < $reqver) || ($op == "<=" && $curver > $reqver) ]]; then
+          echo "- Update '$pkg' version '$curver' with version '$reqver'"
+          if [ $EUID -eq 0 ]; then
+            run_traced "$PIP install -q $f --upgrade --no-deps"
+          else
+            run_traced "$PIP install -q $f --upgrade --no-deps --user"
+          fi
+        fi
+      fi
+    done
   fi
 fi
 exit $sts
