[FIX] wrong prior release

diff --git a/maintainer-quality-tools/travis/travis_install_env b/maintainer-quality-tools/travis/travis_install_env
--- a/maintainer-quality-tools/travis/travis_install_env
+++ b/maintainer-quality-tools/travis/travis_install_env
@@ -30,7 +30,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.2.35
+__version__=0.2.2.36
 
 
 conf_default() {
@@ -160,6 +160,90 @@ git_clone_ocb() {
     fi
 }
 
+set_pythonpath() {
+# set_pythonpath(path file PIP)
+    local PYPATH="${1//,/ }"
+    PYPATH="${PYPATH//:/ }"
+    local FSITE=$2
+    local PIP=${3:-pip}
+    local pth PYLIB x
+    if [[ -n "$PYPATH" || -n "$FSITE" ]]; then
+      PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
+      if [ -z "$PYLIB" ]; then
+        PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
+      fi
+    fi
+    if [ -n "$PYLIB" ]; then
+      if [[ -n "$PYPATH" ]]; then
+        if [ -f $PYLIB/sitecustomize.py ]; then
+          if grep -q "import sys" $PYLIB/sitecustomize.py; then
+            :
+          else
+            echo 'import sys' >> $PYLIB/sitecustomize.py
+          fi
+        else
+          echo 'import sys' > $PYLIB/sitecustomize.py
+        fi
+        for pth in $PYPATH; do
+          echo "if '$pth' not in sys.path:    sys.path.insert(0, '$pth')" >> $PYLIB/sitecustomize.py
+          if echo ":$PYTHONPATH":|grep -q ":$pth:"; then
+            x=${PYTHONPATH//$pth/}
+            export $PYTHONPATH=${x//::/:}
+          fi
+        done
+        [ "${PYTHONPATH:0:1}" == ":" ] && export $PYTHONPATH=${PYTHONPATH:1}
+      fi
+      if [[ -n "$FSITE" && -f $FSITE ]]; then
+        if [ -f $PYLIB/sitecustomize.py ]; then
+          if grep -q "import sys" $PYLIB/sitecustomize.py; then
+            run_traced "tail $FSITE -n -1 >> $PYLIB/sitecustomize.py"
+          else
+            run_traced "cat $FSITE >> $PYLIB/sitecustomize.py"
+          fi
+        else
+          run_traced "cp $FSITE $PYLIB"
+        fi
+        export PYTHONPATH=
+      fi
+    fi
+}
+
+check_pythonpath() {
+# check_pythonpath(path python)
+    local PYPATH="${1//,/ }"
+    PYPATH="${PYPATH//:/ }"
+    local PYTHON=${2:-python}
+    local PYVER=$(python --version 2>&1|grep -Eo "[0-9]+"|head -n1)
+    local pth PYLIB
+    for pth in $PYPATH; do
+      if [ "$PYVER" == "2" ]; then
+        echo -e "import sys\nfor x in sys.path:\n  print x,"|$PYTHON|grep -q " $pth "
+      else
+        echo -e "import sys\nfor x in sys.path:\n  print (x,end=' ')"|$PYTHON|grep -q " $pth "
+      fi
+      if [ $? -ne 0 ]; then
+        echo "Warning: sitecustomize.py without effect! Use PYTHONPATH method"
+        [ -n "$PYTHONPATH" ] && export PYTHONPATH=$PYTHONPATH:$pth
+        [ -z "$PYTHONPATH" ] && export PYTHONPATH=$pth
+      fi
+    done
+}
+
+install_n_activate_tools() {
+    if [ -d $HOME/tools ]; then
+      [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ cd $HOME/tools\e[${PS_TXT_COLOR}m"
+      pushd $HOME/tools > /dev/null
+      [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && x=-p
+      [ ${TRAVIS_DEBUG_MODE:-0} -le 2 ] && x=-qp
+      run_traced "./install_tools.sh $x"
+      [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME/dev/activate_tools\e[${PS_TXT_COLOR}m"
+      . $HOME/dev/activate_tools
+      popd > /dev/null
+      [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PATH=$PATH"
+      [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PYTHONPATH=$PYTHONPATH"
+    fi
+}
+
 
 OPTOPTS=(h        b          j        K        H           n            q           T        t         V           v)
 OPTDEST=(opt_help opt_branch opt_dprj opt_lint opt_humdrum opt_dry_run  opt_verbose opt_regr test_mode opt_version opt_verbose)
@@ -232,46 +316,49 @@ if [[ ! $TRAVIS =~ (true|emulate) && -d $HOME/.local && ! "$SYSTEM_SITE_PACKAGES
 else
   PIP_OPTS=
 fi
-if [ -d $HOME/tools ]; then
-  [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ cd $HOME/tools\e[${PS_TXT_COLOR}m"
-  cd $HOME/tools
-  [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && x=-p
-  [ ${TRAVIS_DEBUG_MODE:-0} -le 2 ] && x=-qp
-  run_traced "./install_tools.sh $x"
-fi
+install_n_activate_tools
 if [ -d $HOME/dev ]; then
-  if [ -f $HOME/dev/sitecustomize.py ]; then
-    PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
-    if [ -z "$PYLIB" ]; then
-      PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
-    fi
-    if [ -n "$PYLIB" ]; then
-      if [ -f $PYLIB/sitecustomize.py ]; then
-        if grep -q "import sys" $PYLIB/sitecustomize.py; then
-          run_traced "tail $HOME/dev/sitecustomize.py -n -1 >> $PYLIB/sitecustomize.py"
-        else
-          run_traced "cat $HOME/dev/sitecustomize.py >> $PYLIB/sitecustomize.py"
-        fi
-      else
-        run_traced "cp $HOME/dev/sitecustomize.py $PYLIB"
-      fi
-    fi
-  fi
+  set_pythonpath "" "$HOME/dev/sitecustomize.py" $PIP
+  [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PATH=$PATH"
+  [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PYTHONPATH=$PYTHONPATH"
+#   if [ -f $HOME/dev/sitecustomize.py ]; then
+#     PYLIB=$(dirname $($PIP --version|grep -Eo "from [^ ]+"|awk '{print $2}'))
+#     if [ -z "$PYLIB" ]; then
+#       PYLIB=$(findpkg "" "$HOME/virtualenv $HOME/python${TRAVIS_PYTHON_VERSION}_with_system_site_packages $HOME/local  $HOME/.local $HOME/lib64 $HOME/lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages local lib64 lib" "python${TRAVIS_PYTHON_VERSION} site-packages" "site-packages")
+#     fi
+#     if [ -n "$PYLIB" ]; then
+#       if [ -f $PYLIB/sitecustomize.py ]; then
+#         if grep -q "import sys" $PYLIB/sitecustomize.py; then
+#           run_traced "tail $HOME/dev/sitecustomize.py -n -1 >> $PYLIB/sitecustomize.py"
+#         else
+#           run_traced "cat $HOME/dev/sitecustomize.py >> $PYLIB/sitecustomize.py"
+#         fi
+#       else
+#         run_traced "cp $HOME/dev/sitecustomize.py $PYLIB"
+#       fi
+#     fi
+#   fi
 else
   echo "!! Error! Directory $HOME/dev not found!"
 fi
-if echo -e "import sys\nfor x in sys.path:\n  print x,"|python|grep -q " $HOME/tools "; then
-  :
+check_pythonpath "$HOME/tools" $PYTHON
+if [ "${TRAVIS_PYTHON_VERSION:0:1}" == "3" ]; then
+  echo -e "import sys\nprint('sys.path=%s' % sys.path)\n"|python3
 else
-  echo "Warning: sitecustomize.py without effect! Use PYTHONPATH method"
-  if [ -f $HOME/dev/activate_tools ]; then
-    [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME/dev/activate_tools\e[${PS_TXT_COLOR}m"
-    . $HOME/dev/activate_tools
-    [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && echo "PYTHONPATH=$PYTHONPATH"
-  else
-    echo "Path to tools not active! Tests may fail!"
-  fi
+  echo -e "import sys\nprint 'sys.path=%s' % sys.path\n"|python
 fi
+# if echo -e "import sys\nfor x in sys.path:\n  print x,"|python|grep -q " $HOME/tools "; then
+#   :
+# else
+#   echo "Warning: sitecustomize.py without effect! Use PYTHONPATH method"
+#   if [ -f $HOME/dev/activate_tools ]; then
+#     [ $opt_verbose -gt 0 ] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME/dev/activate_tools\e[${PS_TXT_COLOR}m"
+#     . $HOME/dev/activate_tools
+#     [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && echo "PYTHONPATH=$PYTHONPATH"
+#   else
+#     echo "Path to tools not active! Tests may fail!"
+#   fi
+# fi
 run_traced "$PIP install -q pip --upgrade" "nolocal"
 run_traced "$PIP install -q future --upgrade" "nolocal"
 MGRODOO=$(which manage_odoo 2>/dev/null)
