[RUN] test nightly

diff --git a/lisa/tests/lisa_test_02 b/lisa/tests/lisa_test_02
--- a/lisa/tests/lisa_test_02
+++ b/lisa/tests/lisa_test_02
@@ -3,7 +3,7 @@
 # Regression tests on lisa
 # Check for commands & info
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
@@ -26,7 +26,8 @@ if [ -z "$Z0TLIBDIR" ]; then
 fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-__version__=0.2.1.26
+
+__version__=0.2.1.27
 
 test_run () {
 # test_run(msg,package,disto,cmd)
@@ -73,208 +74,248 @@ test_01() {
 lisa (install by wget)
 EOF
       echo " command=$RUNDIR/lisa">>$TESTDIR/res/lisa.02.test
-      echo " get ver=$RUNDIR/lisa -V">>$TESTDIR/res/lisa.02.test
+      echo " get_ver=$RUNDIR/lisa -V">>$TESTDIR/res/lisa.02.test
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/lisa.02.test
       cat <<EOF >$TESTDIR/res/LAMP__Debian.02.test
 LAMP=(LAMP pip LAMP_security openssh-server apache2 mysql-server postgresql php5 python) (install by lisa)
 EOF
+      echo " confn=$RUNDIR/LAMP.lish">>$TESTDIR/res/LAMP__Debian.02.test
       cat <<EOF >$TESTDIR/res/LAMP__CentOS6.02.test
 LAMP=(LAMP epel-release pip yum-utils LAMP_security openssh-server httpd mysql-server postgresql-server php python) (install by lisa)
 EOF
+      echo " confn=$RUNDIR/LAMP.lish">>$TESTDIR/res/LAMP__CentOS6.02.test
       cat <<EOF >$TESTDIR/res/LAMP__CentOS7.02.test
 LAMP=(LAMP epel-release pip wheel yum-utils LAMP_security openssh-server httpd mariadb postgresql-server php python) (install by lisa)
 EOF
+      echo " confn=$RUNDIR/LAMP.lish">>$TESTDIR/res/LAMP__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/httpd__RHEL.02.test
 httpd (install by yum)
  service=httpd
  command=apachectl
- get ver=apachectl -v
+ get_ver=apachectl -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/httpd__RHEL.02.test
       cat <<EOF >$TESTDIR/res/apache2__RHEL.02.test
 apache2=httpd (install by yum)
  service=httpd
  command=apachectl
- get ver=apachectl -v
+ get_ver=apachectl -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/apache2__RHEL.02.test
       cat <<EOF >$TESTDIR/res/httpd__Debian.02.test
 httpd=apache2 (install by apt-get)
  service=apache2
  command=apachectl
- get ver=apachectl -v
+ get_ver=apachectl -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/httpd__Debian.02.test
       cat <<EOF >$TESTDIR/res/apache2__Debian.02.test
 apache2 (install by apt-get)
  service=apache2
  command=apachectl
- get ver=apachectl -v
+ get_ver=apachectl -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/apache2__Debian.02.test
       cat <<EOF >$TESTDIR/res/pip__Debian.02.test
 pip (install by pip)
  command=pip
- get ver=pip --version
+ get_ver=pip --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/pip__Debian.02.test
       cat <<EOF >$TESTDIR/res/pip__CentOS7.02.test
 pip (install by pip)
  command=pip
- get ver=pip --version
+ get_ver=pip --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/pip__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/pip__CentOS6.02.test
 pip (install by pip)
  command=pip
- get ver=pip --version
+ get_ver=pip --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/pip__CentOS6.02.test
       cat <<EOF >$TESTDIR/res/python-pip__CentOS7.02.test
 python-pip (install by yum)
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/python-pip__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/python-pip__CentOS6.02.test
 python-pip (install by yum)
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/python-pip__CentOS6.02.test
       cat <<EOF >$TESTDIR/res/python-pip__Debian.02.test
 python-pip (install by apt-get)
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/python-pip__Debian.02.test
       cat <<EOF >$TESTDIR/res/mysql__Debian.02.test
 mysql=mysql-server (install by apt-get)
  service=mysql
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mysql__Debian.02.test
       cat <<EOF >$TESTDIR/res/mysql__CentOS7.02.test
 mysql=mariadb (install by yum)
  service=mariadb
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mysql__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/mysql__CentOS6.02.test
 mysql=mysql-server (install by yum)
  service=mysqld
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mysql__CentOS6.02.test
       cat <<EOF >$TESTDIR/res/mysql-server__Debian.02.test
 mysql-server (install by apt-get)
  service=mysql
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mysql-server__Debian.02.test
       cat <<EOF >$TESTDIR/res/mysql-server__CentOS7.02.test
 mysql-server=mariadb-server (install by yum)
  service=mariadb
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mysql-server__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/mysql-server__CentOS6.02.test
 mysql-server (install by yum)
  service=mysqld
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+     echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mysql-server__CentOS6.02.test
      cat <<EOF >$TESTDIR/res/mariadb__Debian.02.test
 mariadb=mysql-server (install by apt-get)
  service=mysql
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mariadb__Debian.02.test
       cat <<EOF >$TESTDIR/res/mariadb__CentOS7.02.test
 mariadb (install by yum)
  service=mariadb
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mariadb__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/mariadb__CentOS6.02.test
 mariadb=mysql-server (install by yum)
  service=mysqld
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
-     cat <<EOF >$TESTDIR/res/mariadb-server__Debian.02.test
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mariadb__CentOS6.02.test
+      cat <<EOF >$TESTDIR/res/mariadb-server__Debian.02.test
 mariadb-server=mysql-server (install by apt-get)
  service=mysql
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mariadb-server__Debian.02.test
       cat <<EOF >$TESTDIR/res/mariadb-server__CentOS7.02.test
 mariadb-server (install by yum)
  service=mariadb
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mariadb-server__CentOS7.02.test
       cat <<EOF >$TESTDIR/res/mariadb-server__CentOS6.02.test
 mariadb-server=mysql-server (install by yum)
  service=mysqld
  command=mysql
- get ver=mysql --version
+ get_ver=mysql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/mariadb-server__CentOS6.02.test
       cat <<EOF >$TESTDIR/res/postgres__RHEL.02.test
 postgres=postgresql-server (install by yum)
  service=postgresql
  command=psql
- get ver=psql --version
+ get_ver=psql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/postgres__RHEL.02.test
       cat <<EOF >$TESTDIR/res/postgres__Debian.02.test
 postgres=postgresql (install by apt-get)
  service=postgresql
  command=psql
- get ver=psql --version
+ get_ver=psql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/postgres__Debian.02.test
       cat <<EOF >$TESTDIR/res/postgresql__RHEL.02.test
 postgresql=postgresql-server (install by yum)
  service=postgresql
  command=psql
- get ver=psql --version
+ get_ver=psql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/postgresql__RHEL.02.test
       cat <<EOF >$TESTDIR/res/postgresql__Debian.02.test
 postgresql (install by apt-get)
  service=postgresql
  command=psql
- get ver=psql --version
+ get_ver=psql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/postgresql__Debian.02.test
       cat <<EOF >$TESTDIR/res/postgresql-server__RHEL.02.test
 postgresql-server (install by yum)
  service=postgresql
  command=psql
- get ver=psql --version
+ get_ver=psql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/postgresql-server__RHEL.02.test
       cat <<EOF >$TESTDIR/res/postgresql-server__Debian.02.test
 postgresql-server=postgresql (install by apt-get)
  service=postgresql
  command=psql
- get ver=psql --version
+ get_ver=psql --version
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/postgresql-server__Debian.02.test
       cat <<EOF >$TESTDIR/res/php__Debian.02.test
 php=php5 (install by apt-get)
  command=php5
- get ver=php5 -v
+ get_ver=php5 -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/php__Debian.02.test
       cat <<EOF >$TESTDIR/res/php__RHEL.02.test
 php (install by yum)
  command=php
- get ver=php -v
+ get_ver=php -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/php__RHEL.02.test
       cat <<EOF >$TESTDIR/res/php5__RHEL.02.test
 php5=php (install by yum)
  command=php
- get ver=php -v
+ get_ver=php -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/php5__RHEL.02.test
       cat <<EOF >$TESTDIR/res/php5__Debian.02.test
 php5 (install by apt-get)
  command=php5
- get ver=php5 -v
+ get_ver=php5 -v
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/php5__Debian.02.test
       cat <<EOF >$TESTDIR/res/openssh__RHEL.02.test
 openssh=openssh-server (install by yum)
  service=sshd
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/openssh__RHEL.02.test
       cat <<EOF >$TESTDIR/res/openssh__Debian.02.test
 openssh=openssh-server (install by apt-get)
  service=ssh
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/openssh__Debian.02.test
       cat <<EOF >$TESTDIR/res/openssh-server__RHEL.02.test
 openssh-server (install by yum)
  service=sshd
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/openssh-server__RHEL.02.test
       cat <<EOF >$TESTDIR/res/openssh-server__Debian.02.test
 openssh-server (install by apt-get)
  service=ssh
 EOF
+      echo " confn=$RUNDIR/lisa.lish">>$TESTDIR/res/openssh-server__Debian.02.test
     fi
     Real_FH=$(xuname "-f")
     x=$(xuname "-v")
@@ -291,24 +332,32 @@ EOF
          else
            opt_e="-E$Disto"
          fi
-         test_run "info $Package $opt_e" "$Package" "$Disto" "diff"
+         test_run "info $Package $opt_e" "$Package" "$Disto" "diff -b"
       done
     done
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log "$@"
+parseoptest -l$TESTDIR/test_lisa.log "$@" 
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-if [ ${opt_tlib:-0} -ne 0 ]; then
+if [ ${opt_tjlib:-0} -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
   if [ -z "$TRAVISLIBDIR" ]; then
     echo "Library file travisrc not found!"
     exit 2
   fi
   . $TRAVISLIBDIR
+fi
+if [ ${opt_oelib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
 fi
 UT1_LIST=""
 UT_LIST=""
diff --git a/lisa/tests/lisa_test_04 b/lisa/tests/lisa_test_04
--- a/lisa/tests/lisa_test_04
+++ b/lisa/tests/lisa_test_04
@@ -3,7 +3,7 @@
 # Regression tests on lisa
 # Check for status, version and others
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
@@ -26,7 +26,8 @@ if [ -z "$Z0TLIBDIR" ]; then
 fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-__version__=0.2.1.22
+
+__version__=0.2.1.24
 
 test_run () {
 # test_run(msg,package,disto,cmd)
@@ -108,9 +109,9 @@ if [ ${opt_dry_run:-0} -eq 0 ]; then
     echo "apache2: installed by apt-get">$TESTDIR/res/apache2.04.test
     echo "httpd: installed by yum">$TESTDIR/res/httpd.04.test
     if [ "$Real_FH" == "Debian" ]; then
-      x=$(dpkg -s vsftpd|grep "Version"|awk -F: '{print $2}')
+      x=$(dpkg -s vsftpd|grep "Version"|head -n1|awk -F: '{print $2}')
     elif [ "$Real_FH" == "RHEL" ]; then
-      x=$(yum info vsftpd|grep "Version"|awk -F: '{print $2}')
+      x=$(yum info vsftpd|grep "Version"|head -n1|awk -F: '{print $2}')
     fi
     x=$(echo $x)
     if [ -n "$x" ]; then
@@ -172,9 +173,9 @@ if [ ${opt_dry_run:-0} -eq 0 ]; then
     echo "httpd should be installed by yum">$TESTDIR/res/httpd.04.test
   fi
   if [ "$Real_FH" == "Debian" ]; then
-    x=$(dpkg -s vsftpd 2>/dev/null|grep "Version"|awk -F: '{print $2}')
+    x=$(dpkg -s vsftpd 2>/dev/null|grep "Version"|head -n1|awk -F: '{print $2}')
   elif [ "$Real_FH" == "RHEL" ]; then
-    x=$(yum info vsftpd 2>/dev/null|grep "Version"|awk -F: '{print $2}')
+    x=$(yum info vsftpd 2>/dev/null|grep "Version"|head -n1|awk -F: '{print $2}')
   fi
   x=$(echo $x)
   if [ -n "$x" ]; then
@@ -218,18 +219,26 @@ Z0BUG_setup() {
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log "$@"
+parseoptest -l$TESTDIR/test_lisa.log "$@" 
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-if [ ${opt_tlib:-0} -ne 0 ]; then
+if [ ${opt_tjlib:-0} -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
   if [ -z "$TRAVISLIBDIR" ]; then
     echo "Library file travisrc not found!"
     exit 2
   fi
   . $TRAVISLIBDIR
+fi
+if [ ${opt_oelib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
 fi
 UT1_LIST=""
 UT_LIST=""
diff --git a/lisa/tests/lisa_test_08 b/lisa/tests/lisa_test_08
--- a/lisa/tests/lisa_test_08
+++ b/lisa/tests/lisa_test_08
@@ -3,7 +3,7 @@
 # Regression tests on lisa
 # Check for odoo
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
@@ -26,7 +26,8 @@ if [ -z "$Z0TLIBDIR" ]; then
 fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-__version__=0.2.1.20
+
+__version__=0.2.1.21
 
 test_run () {
 # test_run(msg,package,disto,cmd)
@@ -83,10 +84,12 @@ if [ ${opt_dry_run:-0} -eq 0 ]; then
 odoo (install by git)
  service=odoo-server
 EOF
+  echo " confn=$TESTDIR/odoo.lish">>$TESTDIR/res/odoo__Debian.08.test
   cat <<EOF >$TESTDIR/res/odoo__RHEL.08.test
 odoo (install by git)
  service=odoo-server
 EOF
+  echo " confn=$TESTDIR/odoo.lish">>$TESTDIR/res/odoo__RHEL.08.test
 fi
 Real_FH=$(xuname "-f")
 x=$(xuname "-v")
@@ -729,18 +732,26 @@ fi
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log "$@"
+parseoptest -l$TESTDIR/test_lisa.log "$@" 
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-if [ ${opt_tlib:-0} -ne 0 ]; then
+if [ ${opt_tjlib:-0} -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
   if [ -z "$TRAVISLIBDIR" ]; then
     echo "Library file travisrc not found!"
     exit 2
   fi
   . $TRAVISLIBDIR
+fi
+if [ ${opt_oelib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
 fi
 UT_LIST=""
 if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
diff --git a/travis_emulator/please b/travis_emulator/please
--- a/travis_emulator/please
+++ b/travis_emulator/please
@@ -31,7 +31,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.1.51.3
+__version__=0.1.52.1
 
 
 #
@@ -1440,21 +1440,6 @@ do_docs() {
     return $sts
 }
 
-do_publish() {
-#do_publish PKGNAME (svg|docs|pypi|testpypi|tar)
-    wlog "do_publish $1 $2"
-    local cmd="do_publish_$2"
-    sts=$STS_SUCCESS
-    if [ "$(type -t $cmd)" == "function" ]; then
-      eval $cmd "$@"
-    else
-      echo "Missing object! Use:"
-      echo "> please publish PKGNAME (svg|docs|pypi|testpypi|tar)"
-      sts=$STS_FAILED
-    fi
-    return $sts
-}
-
 do_register() {
 #do_register PKGNAME (pypi|testpypi)
     wlog "do_register $1 $2"
@@ -1506,58 +1491,31 @@ mvfiles () {
     return $sts
 }
 
-do_publish_svg() {
-#do_publish_svg pgkname svg (prd|dev)
-    local sts=$STS_FAILED
-    local HTML_SVG_DIR=$(get_cfg_value 0 "HTML_SVG_DIR")
-    local DEV_SVG=$(get_cfg_value 0 "DEV_SVG")
-    if [ "$HOSTNAME" == "$PRD_HOST" ]; then
-      local tgt="prd"
-    elif [ "$HOSTNAME" == "$DEV_HOST" ]; then
-      local tgt="dev"
-    else
-      local tgt=""
-    fi
-    mvfiles "$DEV_SVG" "$HTML_SVG_DIR/$tgt" "*.svg" "apache:apache"
-    local sts=$?
-    if [ "$HOSTNAME" == "$DEV_HOST" ]; then
-      scpfiles "$HTML_SVG_DIR/$tgt" "$PRD_HOST:$HTML_SVG_DIR/$tgt" "*.svg"
-      local s=$?
-      [ $sts -eq $STS_SUCCESS ]&&sts=$s
-    fi
-    return $sts
+create_pubblished_index() {
+# create_pubblished_index(index_dir) {
+    local f
+    run_traced "cd $1"
+    cat <<EOF >index.html
+<!DOCTYPE HTML>
+<html>
+    <head>
+        <title>Speed Test</title>
+    </head>
+    <body>
+    <table>
+EOF
+    for f in *; do
+      if [ "$f" != "index.html" ]; then
+        echo "        <tr><td>$f</td></tr>">>index.html
+      fi
+    done
+    echo "    </body>">>index.html
+    echo "</html>">>index.html
 }
 
-do_publish_docs() {
-#do_publish_svg pgkname docs
-    local sts=$STS_FAILED
-    if [ $EUID -ne 0 ]; then
-      echo "!!Error: no privilege to publish documentation!!"
-      return $sts
-    fi
-    local HTML_DOCS_DIR=$(get_cfg_value "" "HTML_DOCS_DIR")
-    if [ -d $HTML_DOCS_DIR/$1 ]; then
-      run_traced "rm -fR $HTML_DOCS_DIR/$1"
-    fi
-    if [ ! -d $HTML_DOCS_DIR/$1 ]; then
-      run_traced "mkdir -p $HTML_DOCS_DIR/$1"
-      run_traced "chown apache:apache $HTML_DOCS_DIR/$1"
-    fi
-    mvfiles "$PRJPATH/html" "$HTML_DOCS_DIR/$1" "" "apache:apache"
-    local sts=$?
-    rmdir $PRJPATH/html
-    if [ -d $PRJPATH/latex ]; then
-      rm -fR $PRJPATH/latex
-    fi
-    if [ $opt_verbose -gt 0 ]; then
-      echo ""
-      echo -e "see \e[1mdocs.zeroincombenze.org/$1\e[0m webpage"
-    fi
-    return $sts
-}
 
-do_publish_tar() {
-#do_publish_tar pgkname tar
+do_build() {
+#do_build pgkname tar
     local sts=$STS_SUCCESS
     local rpt=pypi
     local f i l n p s v x y PKGLIST invalid PASSED
@@ -1574,12 +1532,16 @@ do_publish_tar() {
       # run_traced "mkdir -p tmp"
       s=$?; [ ${s-0} -ne 0 ] && sts=$s
       n=$(cat setup.py|grep "name *="|awk -F= '{print $2}'|grep -Eo [a-zA-Z0-9_-]+|head -n1)
-      v=$(cat setup.py|grep version|grep -Eo [0-9]+[0-9\.]*|head -n1)
+      v=$(cat setup.py|grep version|grep -Eo [0-9]+\.[0-9]+\.[0-9]+|head -n1)
       if [ ! -f "$n*$v*tar.gz" -o $opt_force -gt 0 ]; then
         PKGLIST=$(cat setup.py|grep "# PKGLIST="|awk -F= '{print $2}')
         if [ -n "$PKGLIST" ]; then
           PKGLIST=${PKGLIST//,/ }
         else
+          if [ "$PRJNAME" != "lisa" ]; then
+            cp ../../clodoo/clodoo/odoorc ./
+            cp ../../z0lib/z0lib/z0librc ./
+          fi
           x="find . -type f"
           for f in $xx "setup.*"; do
             if [ "${f: -1}" == "/" ]; then
@@ -1646,8 +1608,135 @@ do_publish_tar() {
           echo "cp -p $f $PKGPATH/$y">>$SETUP
         done
         chmod +x $SETUP
+        if [ -x $PRJPATH/setup.sh ]; then
+          run_traced "cp $PRJPATH/setup.sh $SETUP"
+        fi
         run_traced "tar $x $p $SETUP"
         run_traced "rm -f $SETUP"
+      fi
+    fi
+    return $sts
+}
+
+do_publish() {
+#do_publish PKGNAME (docs|download|pypi|svg|testpypi|tar)
+    wlog "do_publish $1 $2"
+    local cmd="do_publish_$2"
+    sts=$STS_SUCCESS
+    if [ "$(type -t $cmd)" == "function" ]; then
+      eval $cmd "$@"
+    else
+      echo "Missing object! Use:"
+      echo "> please publish PKGNAME (docs|download|pypi|svg|testpypi|tar)"
+      echo "publish doc      -> publish generate docs to website (require system privileges)"
+      echo "   type 'please docs' to generate docs files"
+      echo "publish download -> publish tarball to download (require system privileges)"
+      echo "   type 'please build' to generate tarball file"
+      echo "publish pypi     -> publish package to pypi website (require system privileges)"
+      echo "publish svg      -> publish test result svg file (require system privileges)"
+      echo "publish tar      -> write a tarball with package files"
+      sts=$STS_FAILED
+    fi
+    return $sts
+}
+
+do_publish_svg() {
+#do_publish_svg pgkname svg (prd|dev)
+    local sts=$STS_FAILED
+    local HTML_SVG_DIR=$(get_cfg_value 0 "HTML_SVG_DIR")
+    local DEV_SVG=$(get_cfg_value 0 "DEV_SVG")
+    if [ $EUID -ne 0 ]; then
+      echo "!!Error: no privilege to publish svg!!"
+      return $sts
+    fi
+    if [ "$HOSTNAME" == "$PRD_HOST" ]; then
+      local tgt="prd"
+    elif [ "$HOSTNAME" == "$DEV_HOST" ]; then
+      local tgt="dev"
+    else
+      local tgt=""
+    fi
+    if [ ! -d $HTML_SVG_DIR ]; then
+      run_traced "mkdir -p $HTML_SVG_DIR"
+      run_traced "chown apache:apache $HTML_SVG_DIR"
+      if [ ! -d $HTML_SVG_DIR/$tgt ]; then
+        run_traced "mkdir -p $HTML_SVG_DIR/$tgt"
+        run_traced "chown apache:apache $HTML_SVG_DIR/$tgt"
+      fi
+    fi
+    mvfiles "$DEV_SVG" "$HTML_SVG_DIR/$tgt" "*.svg" "apache:apache"
+    local sts=$?
+    if [ "$HOSTNAME" == "$DEV_HOST" ]; then
+      scpfiles "$HTML_SVG_DIR/$tgt" "$PRD_HOST:$HTML_SVG_DIR/$tgt" "*.svg"
+      local s=$?
+      [ $sts -eq $STS_SUCCESS ]&&sts=$s
+    fi
+    return $sts
+}
+
+do_publish_docs() {
+#do_publish_svg pgkname docs
+    local sts=$STS_FAILED
+    if [ $EUID -ne 0 ]; then
+      echo "!!Error: no privilege to publish documentation!!"
+      return $sts
+    fi
+    local HTML_DOCS_DIR=$(get_cfg_value "" "HTML_DOCS_DIR")
+    if [ -d $HTML_DOCS_DIR/$1 ]; then
+      run_traced "rm -fR $HTML_DOCS_DIR/$1"
+    fi
+    if [ ! -d $HTML_DOCS_DIR/$1 ]; then
+      run_traced "mkdir -p $HTML_DOCS_DIR/$1"
+      run_traced "chown apache:apache $HTML_DOCS_DIR/$1"
+    fi
+    mvfiles "$PRJPATH/html" "$HTML_DOCS_DIR/$1" "" "apache:apache"
+    local sts=$?
+    rmdir $PRJPATH/html
+    if [ -d $PRJPATH/latex ]; then
+      rm -fR $PRJPATH/latex
+    fi
+    if [ $opt_verbose -gt 0 ]; then
+      echo ""
+      echo -e "see \e[1mdocs.zeroincombenze.org/$1\e[0m webpage"
+    fi
+    return $sts
+}
+
+do_publish_download() {
+#do_publish_download pgkname
+    local f n s v
+    local sts=$STS_FAILED
+    if [ $EUID -ne 0 ]; then
+      echo "!!Error: no privilege to publish download!!"
+      return $sts
+    fi
+    local HTML_DOWNLOAD_DIR=$(get_cfg_value "" "HTML_DOWNLOAD_DIR")
+    if [ "$PRJNAME" != "Odoo" ]; then
+      if [ ! -d $HTML_DOWNLOAD_DIR ]; then
+        run_traced "mkdir -p $HTML_DOWNLOAD_DIR"
+        run_traced "chown apache:apache $HTML_DOWNLOAD_DIR"
+      fi
+      run_traced "cd $PKGPATH"
+      s=$?; [ ${s-0} -ne 0 ] && sts=$s
+      n=$(cat setup.py|grep "name *="|awk -F= '{print $2}'|grep -Eo [a-zA-Z0-9_-]+|head -n1)
+      v=$(cat setup.py|grep version|grep -Eo [0-9]+\.[0-9]+\.[0-9]+|head -n1)
+      f=$(ls -1 $n*$v*tar.gz)
+      # f=$n*$v*tar.gz
+      if [ -n "$f" -a -f "$f" ]; then
+        mvfiles "$PKGPATH" "$HTML_DOWNLOAD_DIR" "$f" "apache:apache"
+        sts=$?
+        if [ $sts -eq $STS_SUCCESS ]; then
+          run_traced "cp $HTML_DOWNLOAD_DIR/$f $HTML_DOWNLOAD_DIR/$n.tar.gz"
+          run_traced "chown apache:apache $HTML_DOWNLOAD_DIR/$n.tar.gz"
+          create_pubblished_index "$HTML_DOWNLOAD_DIR"
+          if [ $opt_verbose -gt 0 ]; then
+            echo ""
+            echo -e "You can download this package typing"
+            echo -e "\$ wget http://download.zeroincombenze.org/$n.tar.gz"
+          fi
+        fi
+      else
+        echo "Source $n*$v*tar.gz file non found!"
       fi
     fi
     return $sts
@@ -1772,7 +1861,7 @@ if [ "$opt_version" ]; then
   echo "$__version__"
   exit 0
 fi
-HLPCMDLIST="help|annotate|autopep8|check|chkconfig|[if-commit]|config|coverage|diff|distribution|docs|[if-]fetch|[if-push]|[if-replace]|publish|pythonhosted|synchro|test|travis|version|wep"
+HLPCMDLIST="help|annotate|autopep8|build|check|chkconfig|[if-commit]|config|coverage|diff|distribution|docs|[if-]fetch|[if-push]|[if-replace]|publish|pythonhosted|synchro|test|travis|version|wep"
 if [ $opt_help -gt 0 ]; then
   print_help "Developer shell\nAction may be on of:\n$HLPCMDLIST"\
   "(C) 2015-2017 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
@@ -1788,6 +1877,7 @@ if [ $opt_verbose -gt 1 ]; then set -x; fi
 set_cfg_def "HTML_SVG_DIR" "/var/www/html/wp-zi/wp-content/uploads/ci-ct"
 set_cfg_def "DEV_SVG" "/opt/odoo/dev/svg"
 set_cfg_def "HTML_DOCS_DIR" "/var/www/html/mw/html"
+set_cfg_def "HTML_DOWNLOAD_DIR" "/var/www/html/mw/download"
 # /End Included Block/
 link_cfg $TCONF
 init_travis
diff --git a/wok_code/cvt_script b/wok_code/cvt_script
--- a/wok_code/cvt_script
+++ b/wok_code/cvt_script
@@ -2,7 +2,7 @@
 # -*- coding: utf-8 -*-
 # Upgrade bash script in z0lib environment
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
@@ -32,7 +32,7 @@ fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.8.1
+__version__=0.1.8.3
 
 
 cvt_file() {
@@ -40,32 +40,40 @@ cvt_file() {
     local f1=$1
     local fntmp=$f1.tmp
     local bakfn=$f1.bak
-    local x y empty line
-    local z0bug_sh=0
+    local x y empty line line_ver
     sts=$STS_SUCCESS
     local prc=0
     if [ -n "$f1" ]; then
       if [ -x "$f1" ]; then
-         if [ $opt_tlib -ne 0 ]; then
-           OPTS_J=" -J"
+         if [ $opt_tjlib -ne 0 ]; then
+           OPTS_J="-J"
          else
            OPTS_J=
+         fi
+         if [ $opt_oelib -ne 0 ]; then
+           OPTS_O=" -O"
+         else
+           OPTS_O=
          fi
          local incl=0
          local empty=0
          rm -f $fntmp
          while IFS= read -r line r || [ -n "$line" ]; do
-           if [ $opt_keep -eq 0 ] && [[ $line =~ ^__version__=.* ]]; then
+           # echo "$prc>$line"  #debug
+           if [ $opt_keep -lt 10 ] && [[ $line =~ ^__version__=.* ]]; then
              if [ $opt_lev3 -eq 0 ]; then
                x=$(echo $line|grep -Eo [0-9]+\.[0-9]+\.[0-9]+\(\.[0-9]*\)?|awk -F. '{print $4}')
                ((x++))
                y="$(echo $line|grep -Eo [0-9.]+|awk -F. '{print $1"."$2"."$3}')"
-               line="__version__=$y.$x"
+               line_ver="__version__=$y.$x"
              else
                x=$(echo $line|grep -Eo [0-9]+\.[0-9]+\.[0-9]+|awk -F. '{print $3}')
                ((x++))
                y="$(echo $line|grep -Eo [0-9.]+|awk -F. '{print $1"."$2}')"
-               line="__version__=$y.$x"
+               line_ver="__version__=$y.$x"
+             fi
+             if [  $prc -eq 0 ]; then
+               continue
              fi
            fi
            if [ $prc -eq 0 ]; then
@@ -76,47 +84,69 @@ cvt_file() {
              else
                echo "$line">>$fntmp
              fi
-           elif [ $prc -eq 1 ]; then
-             if [[ $line =~ ^TRAVISLIBDIR.*findpkg.*travisrc.* ]]; then
+           elif [ $prc -ge 1 -a $prc -le 9 ]; then
+             if [[ $line =~ ^ODOOLIBDIR.*findpkg.*odoorc ]]; then
                prc=2
-               blk_2 "$fntmp"
+               if [ $opt_oelib -ne 0 ]; then
+                 blk_2 "$fntmp"
+               fi
+               empy=0
+             elif [[ $line =~ ^TRAVISLIBDIR.*findpkg.*travisrc.* ]]; then
+               if [ $opt_oelib -ne 0 -a $prc -eq 1 ]; then
+                 prc=2
+                 blk_2 "$fntmp"
+                 if [  $opt_ut -eq 0 ]; then
+                   opt_oelib=0
+                 fi
+               fi
+               prc=3
+               if [ $opt_tjlib -ne 0 ]; then
+                 blk_3 "$fntmp"
+               fi
                empy=0
              elif [[ $line =~ ^TESTDIR.*findpkg.*TDIR.* ]]; then
-               prc=3
-               blk_3 "$fntmp"
-               empy=0
-             elif [[ $line =~ ^__version__.* ]]; then
-               if [ $empy -eq 0 ]; then
-                 echo "">>$fntmp
+               if [ $opt_tjlib -ne 0 -a $prc -lt 3 ]; then
+                 prc=3
+                 blk_3 "$fntmp"
+                 if [  $opt_ut -eq 0 ]; then
+                   opt_tjlib=0
+                 fi
                fi
-               prc=5
-               echo "$line">>$fntmp
-             fi
-           elif [ $prc -eq 2 ]; then
-             if [[ $line =~ ^TESTDIR.*findpkg.*TDIR.* ]]; then
-               prc=3
-               blk_3 "$fntmp"
-               empy=0
-             elif [[ $line =~ ^__version__.* ]]; then
-               prc=5
-               echo "$line">>$fntmp
-             fi
-           elif [ $prc -eq 3 ]; then
-             if [[ $line =~ ^Z0TLIBDIR.*findpkg.*z0testrc.* ]]; then
                prc=4
                blk_4 "$fntmp"
                empy=0
-               z0bug_sh=1
-             elif [[ $line =~ ^__version__.* ]]; then
+             elif [[ $line =~ ^Z0TLIBDIR.*findpkg.*z0testrc.* ]]; then
                prc=5
-               echo "$line">>$fntmp
+               blk_5 "$fntmp"
+               empy=0
+               opt_ut=1
+             elif [[ $line =~ ^__version__.* ]] || [[ $line =~ ^[a-zA_Z0-9_]+[:space:]*\( ]]; then
+               if [ $opt_oelib -ne 0 -a $prc -eq 1 ]; then
+                 prc=2
+                 blk_2 "$fntmp"
+                 if [  $opt_ut -eq 0 ]; then
+                   opt_oelib=0
+                 fi
+               fi
+               if [ $opt_tjlib -ne 0 -a $prc -lt 3 ]; then
+                 prc=3
+                 blk_3 "$fntmp"
+                 if [  $opt_ut -eq 0 ]; then
+                   opt_tjlib=0
+                 fi
+               fi
+               if [ $empy -eq 0 ]; then
+                 echo "">>$fntmp
+               fi
+               echo "$line_ver">>$fntmp
+               prc=10
+               if ! [[ $line =~ ^__version__.* ]]; then
+                 echo "$line">>$fntmp
+               fi
+             else
+               :
              fi
-           elif [ $prc -eq 4 ]; then
-             if [[ $line =~ ^__version__.* ]]; then
-               prc=5
-               echo "$line">>$fntmp
-             fi
-           elif [ $prc -eq 5 ]; then
+           elif [ $prc -eq 10 ]; then
              if [[ $line =~ ^Z0BUG_init ]]; then
                prc=11
                blk_11 "$fntmp"
@@ -130,9 +160,14 @@ cvt_file() {
                echo "$line">>$fntmp
              fi
            elif [ $prc -eq 11 ]; then
-             if [[ $line =~ ^UT1?_LIST=.* ]]; then
+             if [  -z "$line" ]; then
                prc=12
                echo "$line">>$fntmp
+             elif [[ $line =~ ^UT1?_LIST=.* ]]; then
+               prc=12
+               echo "$line">>$fntmp
+             else
+               :
              fi
            elif [ $prc -eq 12 ]; then
              if [[ $line =~ ^if.*type.*Z0BUG_setup.*function.* ]]; then
@@ -217,7 +252,7 @@ cvt_file() {
 
 blk_1() {
     cat <<EOF >>$1
-THIS=\$(basename \$0)
+THIS=\$(basename "\$0")
 TDIR=\$(readlink -f \$(dirname \$0))
 for x in \$TDIR \$TDIR/.. \$TDIR/../z0lib \$TDIR/../../z0lib . .. /etc; do
   if [ -e \$x/z0librc ]; then
@@ -236,6 +271,17 @@ EOF
 
 blk_2() {
     cat <<EOF >>$1
+ODOOLIBDIR=\$(findpkg odoorc "\$TDIR \$TDIR/.. \$TDIR/../clodoo \$TDIR/../../clodoo . .. \$HOME/dev")
+if [ -z "\$ODOOLIBDIR" ]; then
+  echo "Library file odoorc not found!"
+  exit 2
+fi
+. \$ODOOLIBDIR
+EOF
+}
+
+blk_3() {
+    cat <<EOF >>$1
 TRAVISLIBDIR=\$(findpkg travisrc "\$TDIR \$TDIR/.. \$TDIR/../travis_emulator \$TDIR/../../travis_emulator . .. \$HOME/dev")
 if [ -z "\$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
@@ -245,14 +291,14 @@ fi
 EOF
 }
 
-blk_3() {
+blk_4() {
     cat <<EOF >>$1
 TESTDIR=\$(findpkg "" "\$TDIR . .." "tests")
 RUNDIR=\$(readlink -e \$TESTDIR/..)
 EOF
 }
 
-blk_4() {
+blk_5() {
     cat <<EOF >>$1
 Z0TLIBDIR=\$(findpkg z0testrc "\$TDIR \$TDIR/.. \$TDIR/../zerobug \$TDIR/../../zerobug  . .. \$HOME/dev")
 if [ -z "\$Z0TLIBDIR" ]; then
@@ -268,18 +314,26 @@ EOF
 blk_11() {
     cat <<EOF >>$1
 Z0BUG_init
-parseoptest -l\$TESTDIR/test_${opt_id}.log "\$@$OPTS_J"
+parseoptest -l\$TESTDIR/test_${opt_id}.log "\$@" $OPTS_J$OPTS_O
 sts=\$?
 if [ \$sts -ne 127 ]; then
   exit \$sts
 fi
-if [ \${opt_tlib:-0} -ne 0 ]; then
+if [ \${opt_tjlib:-0} -ne 0 ]; then
   TRAVISLIBDIR=\$(findpkg travisrc "\$TDIR \$TDIR/.. \$TDIR/../travis_emulator \$TDIR/../../travis_emulator . .. \$HOME/dev")
   if [ -z "\$TRAVISLIBDIR" ]; then
     echo "Library file travisrc not found!"
     exit 2
   fi
   . \$TRAVISLIBDIR
+fi
+if [ \${opt_oelib:-0} -ne 0 ]; then
+  ODOOLIBDIR=\$(findpkg odoorc "\$TDIR \$TDIR/.. \$TDIR/../clodoo \$TDIR/../../clodoo . .. \$HOME/dev")
+  if [ -z "\$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . \$ODOOLIBDIR
 fi
 EOF
 }
@@ -311,18 +365,20 @@ EOF
 }
 
 
-OPTOPTS=(h        J        K        k        n           m         q           V           v           y)
-OPTDEST=(opt_help opt_tlib opt_lev3 opt_keep opt_dry_run opt_id    opt_verbose opt_version opt_verbose opt_yes)
-OPTACTI=(1        1        1        1        1           "="       0           "*"         "+"         1)
-OPTDEFL=(1        0        0        0        0           "UNKNOWN" -1          ""          -1          0)
-OPTMETA=("help"   ""       ""       ""       "noop"      "name"    "quiet"     "version"   "verbose"   "")
+OPTOPTS=(h        J         K        k        n           m         O         q           U      V           v           y)
+OPTDEST=(opt_help opt_tjlib opt_lev3 opt_keep opt_dry_run opt_id    opt_oelib opt_verbose opt_ut opt_version opt_verbose opt_yes)
+OPTACTI=(1        1         1        1        1           "="       1         0           1      "*"         "+"         1)
+OPTDEFL=(1        0         0        0        0           "UNKNOWN" 0         -1          0      ""          -1          0)
+OPTMETA=("help"   ""        ""       ""       "noop"      "name"    ""        "quiet"     ""     "version"   "verbose"   "")
 OPTHELP=("this help"\
  "load travisrc library"\
  "set script version format n.n.n"\
  "Keep script version"\
  "do nothing (dry-run)"\
  "module name"\
+ "load odoorc library"\
  "silent mode"\
+ "unit test with required switch -J and/or -O"\
  "show version end exit"\
  "verbose mode"\
  "assume yes")
