[IMP] new travis emulator features

diff --git a/travis_emulator/dist_pkg b/travis_emulator/dist_pkg
--- a/travis_emulator/dist_pkg
+++ b/travis_emulator/dist_pkg
@@ -13,26 +13,32 @@ elif [ -f ~/z0librc ]; then
 else
 . /etc/z0librc
 fi
+THIS=$(basename $0)
 TDIR=$(echo $(readlink -f $(dirname $0)))
+DIST_GCONF=$TDIR/$THIS.conf
 . $TDIR/travisrc
 
-__version__="0.1.38"
+__version__="0.1.41"
 
 # main
-OPTOPTS=(h        c          d        f         n            O              p         S        V           -)
-OPTDEST=(opt_help opt_commit opt_diff opt_fetch opt_dry_run  opt_own        opt_dpath opt_sts  opt_version opt_sync)
-OPTACTI=(1        "1>"       1        1         1            "="            "=>"      "=>"     "*"         "1>")
-OPTDEFL=(1        0          0        0         0            "openerp:ERPs" ""        ""       ""          0)
-OPTMETA=("help"   "commit"   "diff"   "fetch"   "do nothing" "uid:gid"      "path"    "status" "version"   "sync")
+OPTOPTS=(h        C         c        d        F         n            O              P         p         R         S        V           v           -)
+OPTDEST=(opt_help opt_cpush opt_conf opt_diff opt_fetch opt_dry_run  opt_own        opt_cpush opt_dpath opt_cpush opt_sts  opt_version opt_verbose opt_sync)
+OPTACTI=(1        "*>"      "="      1        1         1            "="            "*>"      "="       "*>"      "=>"     "*"         1           "1>")
+OPTDEFL=(1        ""        ""       0        0         0            "openerp:ERPs" ""        ""        ""        ""       ""          0           0)
+OPTMETA=("help"   "commit"  "file"   "diff"   "fetch"   "do nothing" "uid:gid"      "push"    "path"    "replace" "status" "version"   "verbose"   "sync")
 OPTHELP=("this help"\
- "push commit to external projects"\
- "diff with distribution directory"\
- "fetch from external project"\
+ "commit and push to production project"\
+ "configuration file"\
+ "diff with local git path"\
+ "fetch from local git path"\
  "do nothing (dry-run)"\
  "set owner user:group (def openerp:ERPs)"\
- "local path for git cloned project"\
- "set evelopment Status"\
+ "push to external projects"\
+ "local git path"\
+ "replace local git path"\
+ "set development Status"\
  "show version"\
+ "verbose mode"\
  "refresh info for distribution")
 OPTARGS=(pkg_path prjname)
 
@@ -51,49 +57,8 @@ if [ $opt_dry_run -gt 0 ]; then
 else
   opts_dry_run=
 fi
-
-
-if [ "$opt_sts" ]; then
-  if [ "$opt_sts" == "0" ]; then
-    opt_sts=" 0 - WIP"
-  elif [ "$opt_sts" == "1" ]; then
-    opt_sts=" 1 - Planning"
-  elif [ "$opt_sts" == "2" ]; then
-    opt_sts=" 2 - Pre-Alpha"
-  elif [ "$opt_sts" == "3" ]; then
-    opt_sts=" 3 - Alpha"
-  elif [ "$opt_sts" == "4" ]; then
-    opt_sts=" 4 - Beta"
-  elif [ "$opt_sts" == "5" ]; then
-    opt_sts=" 5 - Production/Stable"
-  elif [ "$opt_sts" == "6" ]; then
-    opt_sts=" 5 - Production/Stable"
-  elif [ "$opt_sts" == "6" ]; then
-    opt_sts=" 6 - Mature"
-  elif [ "$opt_sts" == "7" ]; then
-    opt_sts=" 7 - Inactive"
-  else
-    echo "Invalid status:"
-    echo "use $(basename $0) -n -S n pkg_path"
-    echo "where n is 0..7 for more info about status"
-    exit 1
-  fi
-fi
-if [ $opt_dry_run -gt 0 ]; then
-  if [ $opt_sync -gt 0 ]; then
-    echo "$(basename $0) -n -- $pkg_path $prjname"
-  elif [ $opt_diff -gt 0 ]; then
-    echo "$(basename $0) -n -d -p \"$opt_dpath\" $pkg_path $prjname"
-  elif [ $opt_commit -gt 0 ]; then
-    echo "$(basename $0) -n -c $pkg_path $prjname"
-  elif [ $opt_fetch -gt 0 ]; then
-    echo "$(basename $0) -n -f -p \"$opt_dpath\" $pkg_path $prjname"
-  elif [ "$opt_sts" ]; then
-    echo "$opt_sts"
-  else
-    echo "$(basename $0) -n -p \"$opt_dpath\" $pkg_path $prjname"
-  fi
-  # set -x  # debug
+if [ "$opt_conf" -a -f "$opt_conf" ]; then
+  DIST_GCONF=$opt_conf
 fi
 if [ "$pkg_path" ]; then
   PKGPATH=$pkg_path
@@ -101,11 +66,6 @@ fi
 PKGPATH=$(set_pkgpath "$PKGPATH")
 pkgname=$(basename $PKGPATH)
 SETUP=$(if [ -f $ODOO_SETUP ]; then echo "$ODOO_SETUP"; elif [ -f setup.py ]; then echo "setup.py"; else echo "$ODOO_SETUP"; fi)
-if [ "$opt_sts" ]; then
-  devstatus="$opt_sts"
-else
-  devstatus=""
-fi
 if [ "$SETUP" == "$ODOO_SETUP" ]; then
   if [ -z "$prjname" ]; then
     prjname="Odoo"
@@ -133,6 +93,59 @@ else
     prjdesc="Unrecognized Odoo module"
   fi
 fi
+declare DPATH=$(grep "^distpath *=" $DIST_GCONF 2>/dev/null|awk -F"[a-z ]=" '{print $2}'|tr -d "\"', \r\n")
+if [ "$opt_dpath" ]; then
+  DPATH="$opt_dpath"
+else
+  DPATH=$DPATH/$prjname
+fi
+if [ "$opt_sts" ]; then
+  if [ "$opt_sts" == "0" ]; then
+    opt_sts=" 0 - WIP"
+  elif [ "$opt_sts" == "1" ]; then
+    opt_sts=" 1 - Planning"
+  elif [ "$opt_sts" == "2" ]; then
+    opt_sts=" 2 - Pre-Alpha"
+  elif [ "$opt_sts" == "3" ]; then
+    opt_sts=" 3 - Alpha"
+  elif [ "$opt_sts" == "4" ]; then
+    opt_sts=" 4 - Beta"
+  elif [ "$opt_sts" == "5" ]; then
+    opt_sts=" 5 - Production/Stable"
+  elif [ "$opt_sts" == "6" ]; then
+    opt_sts=" 5 - Production/Stable"
+  elif [ "$opt_sts" == "6" ]; then
+    opt_sts=" 6 - Mature"
+  elif [ "$opt_sts" == "7" ]; then
+    opt_sts=" 7 - Inactive"
+  else
+    echo "Invalid status:"
+    echo "use $(basename $0) -n -S n pkg_path"
+    echo "where n is 0..7 for more info about status"
+    exit 1
+  fi
+fi
+if [ "$opt_sts" ]; then
+  devstatus="$opt_sts"
+else
+  devstatus=""
+fi
+if [ $opt_dry_run -gt 0 ]; then
+  if [ $opt_sync -gt 0 ]; then
+    echo "$(basename $0) -n -- $pkg_path $prjname"
+  elif [ $opt_diff -gt 0 ]; then
+    echo "$(basename $0) -n -d -p \"$DPATH\" $pkg_path $prjname"
+  elif [ "$opt_cpush" ]; then
+    echo "$(basename $0) -n $opt_cpush -p \"$DPATH\" $pkg_path $prjname"
+  elif [ $opt_fetch -gt 0 ]; then
+    echo "$(basename $0) -n -f -p \"$DPATH\" $pkg_path $prjname"
+  elif [ "$opt_sts" ]; then
+    echo "$opt_sts"
+  else
+    echo "$(basename $0) -n -p \"$DPATH\" $pkg_path $prjname"
+  fi
+fi
+
 if [ "$prjname" != "Odoo" ]; then
   LSETUP=$PKGPATH/$pkgname/setup.py
   DEVSSTS0=" 1 - Planning"
@@ -149,22 +162,34 @@ if [ "$prjname" != "Odoo" ]; then
     devstatus=$(grep " *'Development Status" $LSETUP 2>/dev/null|awk -F":" '{print $3}'|tr -d "\"',\r\n")
   fi
 fi
-if [ $opt_commit -gt 0 ]; then
+if [ "$opt_cpush" == "-C" -o "$opt_cpush" == "-P" ]; then
   if [ -f $DIST_CONF ]; then
-    find $PWD -name "*.pyc" -exec rm -f '{}' \;
-    for ii in 1 2 3 4; do
+    robocopy_init "$prjname" "$pkgname"
+    f_done=0
+    for ii in {1..9}; do
       declare x=tgt${ii}path
-      declare $x=$(grep "^$x *=" $DIST_CONF 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"', \r\n")
-      if [ "${!x}" ]; then
-        declare y=tgt${ii}params
-        declare $y=$(grep "^$y *=" $DIST_CONF 2>/dev/null|awk -F"[a-z]=" '{print $2}'|tr -d "\"', \r\n")
-        if [ "${!y}" ]; then
-          declare $y=$(echo "${!y}"|sed 's:\\::g')
-          echo rsync $opts_dry_run -avzhe \"ssh ${!y}\" $PWD/ ${!x}
-          rsync -avzhe $opts_dry_run "ssh ${!y}" $PWD ${!x}
-        else
-          echo "rsync $opts_dry_run -avzhe ssh $PWD/ ${!x}"
-          rsync $opts_dry_run -avzhe ssh $PWD ${!x}
+      declare y=tgt${ii}params
+      declare tgtpath=$(grep "^$x *=" $DIST_GCONF 2>/dev/null|awk -F"[a-z ]=" '{print $2}'|tr -d "\"', \r\n")
+      declare tgtparm=$(grep "^$y *=" $DIST_GCONF 2>/dev/null|awk -F"[a-z ]=" '{print $2}'|tr -d "\"', \r\n")
+      if [ -z "$tgtpath" ]; then
+        declare tgtpath=$(grep "^$x *=" $DIST_CONF 2>/dev/null|awk -F"[a-z ]=" '{print $2}'|tr -d "\"', \r\n")
+        declare tgtparm=$(grep "^$y *=" $DIST_CONF 2>/dev/null|awk -F"[a-z ]=" '{print $2}'|tr -d "\"', \r\n")
+      fi
+      if [ "$tgtpath" ]; then
+        declare z=tgt${ii}enable
+        declare enabled=$(grep "^$z *=" $DIST_CONF 2>/dev/null|awk -F"[a-z ]=" '{print $2}'|tr -d "\"', \r\n")
+        if [ ${enabled:-0} -eq 2 ]; then
+          if [ "$opt_cpush" != "-C" ]; then enabled=0; fi
+        fi
+        if [ ${enabled:-0} -gt 0 ]; then
+          if [ "tgtparm" ]; then
+            declare $y=$(echo "$tgtparm"|sed 's:\\::g')
+            if [ $opt_verbose -gt 0 ]; then echo "> robocopy \"$PWD\" \"$tgtpath\" \"ssh $tgtparm\""; fi
+            robocopy "$PWD" "$tgtpath" "ssh $tgtparm"
+          else
+           if [ $opt_verbose -gt 0 ]; then echo "> robocopy \"$PWD\" \"$tgtpath\" \"ssh\""; fi
+            robocopy "$PWD" "$tgtpath" "ssh"
+          fi
         fi
         f_done=1
       fi
@@ -188,6 +213,7 @@ if [ "$prjname" != "Odoo" ]; then
     echo "Warning: package name $pkgname and project name $prjname are different!"
   else
     if [ $opt_dry_run -eq 0 -a $opt_diff -eq 0 ]; then
+      if [ $opt_verbose -gt 0 ]; then echo "> cp $SETUP $PKGPATH/$pkgname/setup.py"; fi
       echo "from setuptools import setup">$PKGPATH/$pkgname/setup.py
       echo "">>$PKGPATH/$pkgname/setup.py
       echo "setup(name='$prjname',">>$PKGPATH/$pkgname/setup.py
@@ -205,12 +231,12 @@ fi
 if [ $opt_sync -gt 0 ]; then
   exit 0
 fi
-if [ ! -d "$opt_dpath" ]; then
-  echo "Invalid destination path $opt_dpath"
+if [ ! -d "$DPATH" ]; then
+  echo "Invalid destination path $DPATH"
   exit 1
 fi
-dpath_parent=$opt_dpath
-dpath_child=$opt_dpath/$pkgname
+dpath_parent=$DPATH
+dpath_child=$DPATH/$pkgname
 if [ "$prjname" == "travis_emulator" ]; then
   XDPATH=$(echo "$(dirname $MAKEF)")
   RFLIST="beauty dist_pkg Makefile topep8 travis travisrc wok_doc wok_doc.py"
@@ -228,14 +254,15 @@ if [ "$prjname" == "travis_emulator" ]; then
     for x in $RFLIST; do
       if [ -f $PKGPATH/$pkgname/$x ]; then
         if [ $opt_diff -gt 0 ]; then
-          if [ "$(diff -rq -x '*.pyc' $PKGPATH/$pkgname/$x $XDPATH/$x)" ]; then
-            diff -rq -x '*.pyc' $PKGPATH/$pkgname/$x $XDPATH/$x
+          if [ "$(diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x)" ]; then
+            if [ $opt_verbose -gt 0 ]; then echo "> diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
+            diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x
           fi
         elif [ $opt_fetch -gt 0 ]; then
-          echo "$opt_dry_run||cp $XDPATH/$x $PKGPATH/$pkgname/$x"
+          if [ $opt_verbose -gt 0 ]; then echo "> $opt_dry_run||cp $XDPATH/$x $PKGPATH/$pkgname/$x"; fi
           (($opt_dry_run))||cp $XDPATH/$x $PKGPATH/$pkgname/$x
         else
-          echo "$opt_dry_run||cp $PKGPATH/$pkgname/$x $XDPATH/$x"
+          if [ $opt_verbose -gt 0 ]; then echo "> $opt_dry_run||cp $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
           (($opt_dry_run))||cp $PKGPATH/$pkgname/$x $XDPATH/$x
         fi
       fi
@@ -243,15 +270,16 @@ if [ "$prjname" == "travis_emulator" ]; then
     MAKEF=$PKGPATH/$pkgname/Makefile
   fi
 elif [ "$prjname" == "Odoo" ]; then
-  opt_dpath=$dpath_child
-  if [ ! -d "$opt_dpath" ]; then
-    echo "Invalid destination path $opt_dpath"
+  DPATH=$dpath_child
+  if [ ! -d "$DPATH" ]; then
+    echo "Invalid destination path $DPATH"
     exit 1
   fi
 fi
 robocopy_init "$prjname" "$pkgname"
 if [ $opt_diff -gt 0 ]; then
-  diff -rq -x '*.pyc' $PKGPATH/ $opt_dpath/
+  if [ $opt_verbose -gt 0 ]; then echo "> diff -rq $XLDF $PKGPATH/$prjname $DPATH/"; fi
+  diff -rq $XLDF $PKGPATH/$prjname $DPATH/
   if [ $? -eq 0 ]; then
     echo "No difference found"
   fi
@@ -259,12 +287,15 @@ if [ $opt_diff -gt 0 ]; then
 fi
 if [ $opt_fetch -eq 0 ]; then
   for f in $(dir $PKGPATH); do
-    robocopy "$PKGPATH/$f" "$opt_dpath"
+    if [ $opt_verbose -gt 0 ]; then echo "> robocopy \"$PKGPATH/$f\" \"$DPATH\""; fi
+    robocopy "$PKGPATH/$f" "$DPATH"
   done
-  clean_dirs "$opt_dpath"
+  if [ $opt_verbose -gt 0 ]; then echo "> clean_dirs \"$DPATH\""; fi
+  clean_dirs "$DPATH"
 else
-  for f in $(dir $opt_dpath); do
-    robocopy "$opt_dpath/$f" "$PKGPATH"
+  for f in $(dir $DPATH); do
+    if [ $opt_verbose -gt 0 ]; then echo "> robocopy \"$DPATH/$f\" \"$PKGPATH\""; fi
+    robocopy "$DPATH/$f" "$PKGPATH"
   done
 fi
 exit 0
diff --git a/travis_emulator/tests/test_regex b/travis_emulator/tests/test_regex
--- a/travis_emulator/tests/test_regex
+++ b/travis_emulator/tests/test_regex
@@ -1,5 +1,12 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
+if [ -f ./z0librc ]; then
+. ./z0librc
+  TESTDIR=./tests
+elif [ -f ../z0librc ]; then
+. ../z0librc
+  TESTDIR=.
+fi
 if [ -f ./travisrc ]; then
 . ./travisrc
 TESTDIR=./tests
@@ -8,19 +15,36 @@ elif [ -f ../travisrc ]; then
 TESTDIR=.
 fi
 
-
-test_result_k () {
-    echo "Test $1"
-    local TRES=$(a_find "$2")
-    if [ "$TRES" != "$3" ]; then
-      echo "Test failed: for $2 expected '$3', found '$TRES'"
+test_result () {
+  ((ctr++))
+  wlog "Test $ctr: $1"
+  if [ "$4" ]; then
+    if [ "$($4 $2 $3)" ]; then
+      echo "Test failed: $4 '$2' '$3'"
       exit 1
     fi
+  else
+    if [ "$2" != "$3" ]; then
+      echo "Test failed: expected '$2', found '$3'"
+      exit 1
+    fi
+  fi
+}
+
+test_result_k () {
+    #echo "Test $1"
+    local TRES=$(a_search "$2")
+    test_result "$1" "$TRES" "$3"
+    #if [ "$TRES" != "$3" ]; then
+    #  echo "Test failed: for $2 expected '$3', found '$TRES'"
+    #  exit 1
+    #fi
 }
 
 
 test_result_x () {
-    echo "Test $1"
+    ((ctr++))
+    wlog "Test $ctr: $1"
     if $(matches1of "$2" "$XRGI"); then
       sts=1
     else
@@ -37,26 +61,31 @@ test_result_x () {
 
 
 test_result_cp () {
-    echo "Test $1"
-    if [ "$2" != "$3" ]; then
-      echo "Test failed: expected '$2', found '$3'"
-      exit 1
-    fi
+    #echo "Test $1"
+    #if [ "$2" != "$3" ]; then
+    #  echo "Test failed: expected '$2', found '$3'"
+    #  exit 1
+    #fi
+    test_result "$1" "$2" "$3"
 }
 
-ctr=0
+# Previous test_wlog executed 0 unit test
+#if [ ${ctr:-0} -eq 0 ]; then
+  ctr=0
+#fi
+if [ -z "$FLOG" ]; then
+  set_tlog_file "$TESTDIR/test_travis_em.log" "" "echo"
+fi
+
 a_append "--new"
 a_append "KEY_A" "aaa"
 a_append "KEY_B" "bbb"
 a_append "^KEY.*" "any"
-((ctr++))
-test_result_k "$ctr" "KEY_A" "aaa"
-((ctr++))
-test_result_k "$ctr" "KEY_B" "bbb"
-((ctr++))
-test_result_k "$ctr" "KEY_Z" "any"
-((ctr++))
-test_result_k "$ctr" "NOKEY" ""
+
+test_result_k "KEY_A" "KEY_A" "aaa"
+test_result_k "KEY_B" "KEY_B" "bbb"
+test_result_k "KEY_Z" "KEY_Z" "any"
+test_result_k "NOKEY" "NOKEY" ""
 
 a_append "--new"
 a_append "/opt/odoo/dev/travis" "1"
@@ -80,10 +109,9 @@ a_append "conf/travis.conf.sample" "1"
 a_append "dist/travis.py" "0"
 
 for f in ${DEFPRM[*]}; do
-  TRES=$(a_find "$f")
-  ((ctr++))
+  TRES=$(a_search "$f")
   # set -x
-  test_result_x "$ctr" "$f" "$TRES"
+  test_result_x "$f" "$f" "$TRES"
   sts=$?
   # set +x
   if [ $sts -gt 0 ]; then
@@ -98,45 +126,31 @@ opts_dry_run="-n"
 opt_fetch=0
 
 robocopy_init "travis_emulator" "travis_emulator"
-((ctr++))
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/travis_emulator" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "rsync -n -ab --del --copy-links  --exclude *.pyc --exclude *.log --exclude *.bak --exclude *.out --exclude *build/ --exclude *dist/ --exclude *conf/ --exclude *.cover/ --exclude *.coverage/ --exclude *.git/ /opt/odoo/dev/pypi/travis_emulator/travis_emulator/ /opt/odoo/tools/travis_emulator/" "$TRES"
-((ctr++))
+test_result_cp "robocopy # rsync" "rsync -n -ab --del --copy-links  --exclude *.pyc --exclude *.log --exclude *.bak --exclude *.out --exclude *.conf --exclude *build/ --exclude *dist/ --exclude *conf/ --exclude *.cover/ --exclude *.coverage/ --exclude *.git/ --exclude *~ /opt/odoo/dev/pypi/travis_emulator/travis_emulator/ /opt/odoo/tools/travis_emulator/" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/travis_emulator.egg-info" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/build" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/dist" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/README.rst" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.rst /opt/odoo/tools/travis_emulator/" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.rst /opt/odoo/tools/travis_emulator/" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/README.md" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.md /opt/odoo/tools/travis_emulator/" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "1||cp -L /opt/odoo/dev/pypi/travis_emulator/README.md /opt/odoo/tools/travis_emulator/" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/setup.py" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/conf" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "" "$TRES"
 TRES=$(robocopy "/opt/odoo/dev/pypi/travis_emulator/conf/conf.sample" "/opt/odoo/tools/travis_emulator")
-test_result_cp "$ctr" "" "$TRES"
+test_result_cp "robocopy" "" "$TRES"
 
 robocopy_init "Odoo" "zeroincombenze"
-((ctr++))
 TRES=$(robocopy "/opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py" "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal")
-test_result_cp "$ctr" "1||cp -L /opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/" "$TRES"
-((ctr++))
+test_result_cp "robocopy # odoo" "1||cp -L /opt/odoo/dev/7.0/zeroincombenze/l10n_it_fiscal/__init__.py /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/" "$TRES"
 TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
-test_result_cp "$ctr" "rsync -n -ab --del --copy-links  --exclude *.pyc --exclude *.log --exclude *.bak --exclude *.out --exclude *build/ --exclude *dist/ --exclude *conf/ --exclude *.cover/ --exclude *.coverage/ --exclude *.git/ /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data/ /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data/" "$TRES"
-((ctr++))
+test_result_cp "robocopy # rsync" "rsync -n -ab --del --copy-links  --exclude *.pyc --exclude *.log --exclude *.bak --exclude *.out --exclude *.conf --exclude *build/ --exclude *dist/ --exclude *conf/ --exclude *.cover/ --exclude *.coverage/ --exclude *.git/ --exclude *~ /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/data/ /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data/" "$TRES"
 TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
-test_result_cp "$ctr" "" "$TRES"
-((ctr++))
+test_result_cp "robocopy" "" "$TRES"
 TRES=$(robocopy "/opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample" "/opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data")
-test_result_cp "$ctr" "1||cp -L /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data" "$TRES"
-
+test_result_cp "robocopy" "1||cp -L /opt/odoo/7.0/zeroincombenze/l10n_it_fiscal/conf/res_sample /opt/odoo/8.0/zeroincombenze/l10n_it_fiscal/data" "$TRES"
