[IMP] New feature for travis emulator

diff --git a/travis_emulator/dist_pkg b/travis_emulator/dist_pkg
--- a/travis_emulator/dist_pkg
+++ b/travis_emulator/dist_pkg
@@ -11,19 +11,25 @@
 
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -f ./z0librc ]; then
-. ./z0librc
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-elif [ -f /etc/z0librc ]; then
-. /etc/z0librc
-else
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
-  exit $STS_FAILED
+  exit 2
 fi
-. $TDIR/travisrc
+TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR . .. $HOME/dev $HOME")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
+
 
 __version__=0.1.83.3
 
@@ -197,7 +203,7 @@ if [ "$PRJNAME" != "Odoo" ]; then
     echo "Warning: package name $PKGNAME and project name $PRJNAME are different!"
   else
     if [ $opt_dry_run -eq 0 -a $opt_diff -eq 0 ]; then
-      run_traced "cp $SETUP $PKGPATH/$PKGNAME/setup.py"
+      # run_traced "cp $SETUP $PKGPATH/$PKGNAME/setup.py"
       echo "from setuptools import setup">$PKGPATH/$PKGNAME/setup.py
       echo "">>$PKGPATH/$PKGNAME/setup.py
       echo "setup(name='$PRJNAME',">>$PKGPATH/$PKGNAME/setup.py
@@ -304,15 +310,18 @@ else
     done
   fi
 fi
-LGITPATH=$(readlink -e $LGITPATH/..)
-for f in $(dir $LGITPATH); do
-  if [ -d $LGITPATH/$f ]; then
-    if [ ! -f $LGITPATH/$f/z0librc ]; then
-      run_traced "ln -s $LGITPATH/z0lib/z0librc $LGITPATH/$f/z0librc"
-    fi
-  fi
-done
-if [ ! -f $LGITPATH/travis_emulator/_travis/z0librc ]; then
-  run_traced "ln -s $LGITPATH/z0lib/z0librc $LGITPATH/travis_emulator/_travis/z0librc"
-fi
+# LGITPATH=$(readlink -e $LGITPATH/..)
+# for f in $(dir $LGITPATH); do
+#   if [ -d $LGITPATH/$f ]; then
+#     if [ ! -f $LGITPATH/$f/z0librc ]; then
+#       run_traced "ln -s $LGITPATH/z0lib/z0librc $LGITPATH/$f/z0librc"
+#     fi
+#   fi
+# done
+# if [ ! -f $LGITPATH/travis_emulator/_travis/z0librc ]; then
+#   run_traced "ln -s $LGITPATH/z0lib/z0librc $LGITPATH/travis_emulator/_travis/z0librc"
+# fi
+# if [ ! -f $LGITPATH/travis_emulator/z0librc ]; then
+#   run_traced "cp $LGITPATH/z0lib/z0librc $LGITPATH/travis_emulator/z0librc"
+# fi
 exit $STS_SUCCESS
