[RUN] test nightly

diff --git a/travis_emulator/please b/travis_emulator/please
--- a/travis_emulator/please
+++ b/travis_emulator/please
@@ -725,7 +725,7 @@ do_docs() {
 }
 
 do_publish() {
-#do_publish PKGNAME (svg|docs|pypi|testpypi)
+#do_publish PKGNAME (svg|docs|pypi|testpypi|tar)
     wlog "do_publish $1 $2"
     local cmd="do_publish_$2"
     sts=$STS_SUCCESS
@@ -733,7 +733,7 @@ do_publish() {
       eval $cmd "$@"
     else
       echo "Missing object! Use:"
-      echo "> please publish PKGNAME (svg|docs|pypi|testpypi)"
+      echo "> please publish PKGNAME (svg|docs|pypi|testpypi|tar)"
       sts=$STS_FAILED
     fi
     return $sts
@@ -828,6 +828,64 @@ do_publish_docs() {
     rmdir $PRJPATH/html
     if [ -d $PRJPATH/latex ]; then
       rm -fR $PRJPATH/latex
+    fi
+    return $sts
+}
+
+do_publish_tar() {
+#do_publish_tar pgkname tar
+    local sts=$STS_SUCCESS
+    local rpt=pypi
+    local f i n p s v x PKGLIST invalid
+    local SETUP=./setup.sh
+    if [ "$PRJNAME" != "Odoo" ]; then
+      run_traced "cd $PKGPATH"
+      s=$?; [ ${s-0} -ne 0 ] && sts=$s
+      n=$(cat setup.py|grep "name *="|awk -F= '{print $2}'|grep -Eo [a-zA-Z0-9_-]+|head -n1)
+      v=$(cat setup.py|grep version|grep -Eo [0-9]+[0-9\.]*|head -n1)
+      if [ ! -f "$n*$v*tar.gz" -o $opt_force -gt 0 ]; then
+        PKGLIST=$(cat setup.py|grep "# PKGLIST="|awk -F= '{print $2}')
+        if [ -n "$PKGLIST" ]; then
+          PKGLIST=${PKGLIST//,/ }
+        else
+          PKGLIST=$(find . -type f|grep -v "/tests/"|grep -v "/conf/"|grep -v ".pyc$"|grep -v "./setup."|grep -v "/__old")
+        fi
+        invalid=
+        for f in $PKGLIST; do
+          if [ -f $f ]; then
+            cp $f $HOME/tmp
+          else
+            invalid=$f
+          fi
+        done
+        if  [ -n "$invalid" ]; then
+          echo "File $f not found"
+          return 1
+        fi
+        p="$n-$v.tar.gz"
+        if [ -f $p ]; then
+           run_traced "rm -f $p"
+        fi
+        echo "# $p">$SETUP
+        f=
+        for i in {2..9}; do
+          x=$(echo $PKGPATH|awk -F/ '{print $'$i'}')
+          if [ -n "$x" ]; then
+            f=$f/$x
+            if [ $i -gt 3 ]; then
+              echo "mkdir -p $f">>$SETUP
+            fi
+          fi
+        done
+        x="-cf"
+        for f in $PKGLIST; do
+          run_traced "tar $x $p $f"
+          x=${x/c/r}
+          echo "cp -p $f $PKGPATH">>$SETUP
+        done
+        chmod +x $SETUP
+        run_traced "tar $x $p $SETUP"
+      fi
     fi
     return $sts
 }
diff --git a/travis_emulator/tests/test_vfcp b/travis_emulator/tests/test_vfcp
--- a/travis_emulator/tests/test_vfcp
+++ b/travis_emulator/tests/test_vfcp
@@ -22,12 +22,12 @@ Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.12.3
+__version__=0.1.13
 
 
 Z0BUG_setup() {
     LCLTEST_RMDIR=
-    for VERSION in 8.0 9.0 10.0; do
+    for VERSION in 7.0 8.0 9.0 10.0; do
       if [ ! -d ~/$VERSION ]; then
         LCLTEST_RMDIR="$LCLTEST_RMDIR $VERSION"
         mkdir -p ~/$VERSION
@@ -40,7 +40,7 @@ Z0BUG_setup() {
 }
 
 Z0BUG_teardown() {
-    for VERSION in 8.0 9.0 10.0; do
+    for VERSION in 7.0 8.0 9.0 10.0; do
       if [[ "$LCLTEST_RMDIR" =~ $VERSION ]]; then
         rm -fR ~/$VERSION/l10n-italy/l10n_it_vat_registries/i18n
         rm -fR ~/$VERSION/l10n-italy/l10n_it_vat_registries
@@ -139,6 +139,8 @@ test_01() {
     cd $CWD
 }
 
+opt_tlib=1
+
 
 Z0BUG_init
 parseoptest -l$TESTDIR/test_zerobug.log $@
@@ -146,17 +148,18 @@ sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
-if [ -z "$TRAVISLIBDIR" ]; then
-  echo "Library file travisrc not found!"
-  exit 2
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
-. $TRAVISLIBDIR
-
-UT1_LIST=""
-UT_LIST=""
-Z0BUG_setup
+UT1_LIST=
+UT_LIST=
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
-Z0BUG_teardown
-exit $?
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
