[IMP] New enhancements in order to manage Odoo 11

diff --git a/travis_emulator/please b/travis_emulator/please
--- a/travis_emulator/please
+++ b/travis_emulator/please
@@ -28,6 +28,12 @@ if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
+ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
+if [ -z "$ODOOLIBDIR" ]; then
+  echo "Library file odoorc not found!"
+  exit 2
+fi
+. $ODOOLIBDIR
 TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
@@ -37,7 +43,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.1.5
+__version__=0.2.1.6
 
 
 #
@@ -339,7 +345,8 @@ cvt_gitmodule() {
           IFS== read p v <<<$lne
           lne=$(echo $p)
           if [ "$lne" == "url" ]; then
-            url=$(build_pkgurl $submod $urlty URL)
+            # url=$(build_pkgurl $submod $urlty URL)
+            url=$(build_odoo_param URL '' $submod $urlty)
             lne=$(echo $v)
             if [ "$lne" != "$url" ]; then
               v="${line//$lne/$url}"
@@ -1637,9 +1644,11 @@ do_distribution() {
     if [ -f .gitrepname ]; then
       currpt=$(grep "^repository" .gitrepname|awk -F= '{print $2}'|tr -d " ")
     fi
-    local gitprj=$(build_pkgurl $1 $2 RUPSTREAM)
+    # local gitprj=$(build_pkgurl $1 $2 RUPSTREAM)
+    local gitprj=$(build_odoo_param RUPSTREAM '' $1 $2)
     if [ -z "$gitprj" ]; then
-      gitprj=$(build_pkgurl $1 $2 RORIGIN)
+      # gitprj=$(build_pkgurl $1 $2 RORIGIN)
+      local gitprj=$(build_odoo_param RORIGIN '' $1 $2)
     fi
     if [ $travis_passed -eq 0 ]; then
       if [ $opt_orig -gt 0 ]; then
@@ -1757,8 +1766,10 @@ do_distribution() {
         fi
       fi
       if [ -z "$REPOSNAME" ]; then
-        local ro=$(build_pkgurl $1 $2 RORIGIN)
-        local lo=$(build_pkgurl $1 $2 URL)
+        # local ro=$(build_pkgurl $1 $2 RORIGIN)
+        local ro=$(build_odoo_param RORIGIN '' $1 $2)
+        # local lo=$(build_pkgurl $1 $2 URL)
+        local lo=$(build_odoo_param URL '' $1 $2)
         if [ "$ro" != "$lo" ]; then
           if [ -n "$ro" ]; then
             run_traced "git remote remove origin"
@@ -1769,8 +1780,10 @@ do_distribution() {
           fi
         fi
         if [ "$1" != "l10n-italy-supplemental" ]; then
-          local ro=$(build_pkgurl $1 $2 RUPSTREAM)
-          local lo=$(build_pkgurl $1 $2 UPSTREAM)
+          # local ro=$(build_pkgurl $1 $2 RUPSTREAM)
+          local ro=$(build_odoo_param RUPSTREAM '' $1 $2)
+          # local lo=$(build_pkgurl $1 $2 UPSTREAM)
+          local lo=$(build_odoo_param UPSTREAM '' $1 $2)
           if [ "$ro" != "$lo" ]; then
             if [ -n "$ro" ]; then
               run_traced "git remote remove upstream"
@@ -1968,7 +1981,8 @@ do_synchro() {
             opts=-f
           fi
         fi
-        local ro=$(build_pkgurl $1 $2 RORIGIN)
+        # local ro=$(build_pkgurl $1 $2 RORIGIN)
+        local ro=$(build_odoo_param RORIGIN '' $1 $2)
         run_traced "git push $opts $ro"
         restore_owner
         git remote -v
@@ -2133,7 +2147,8 @@ elif [ "$action" == "config" ]; then
       r="origin_$sub1"
       x=$(git remote|grep $r)
       if [ -z "$x" ]; then
-        ro=$(build_pkgurl $PKGNAME $sub1 RORIGIN)
+        # ro=$(build_pkgurl $PKGNAME $sub1 RORIGIN)
+        local ro=$(build_odoo_param RORIGIN '' $PKGNAME $sub1)
         run_traced "git remote add $r $ro"
         run_traced "git remote set-url --add --push $r $ro"
       fi
diff --git a/travis_emulator/test_nightly b/travis_emulator/test_nightly
--- a/travis_emulator/test_nightly
+++ b/travis_emulator/test_nightly
@@ -6,12 +6,18 @@
 #
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2018 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
-  if [ -e $x/z0librc ]; then
-    . $x/z0librc
-    Z0LIBDIR=$x
+PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
+for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
+  if [ -e $d/z0librc ]; then
+    . $d/z0librc
+    Z0LIBDIR=$d
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  elif [ -d $d/z0lib ]; then
+    . $d/z0lib/z0librc
+    Z0LIBDIR=$d/z0lib
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
     break
   fi
@@ -20,13 +26,18 @@ if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev /etc")
+ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
 if [ -z "$ODOOLIBDIR" ]; then
   echo "Library file odoorc not found!"
   exit 2
 fi
 . $ODOOLIBDIR
-
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
 
 __version__=0.1.79.14
 
diff --git a/travis_emulator/tests/test_travisrc1 b/travis_emulator/tests/test_travisrc1
--- a/travis_emulator/tests/test_travisrc1
+++ b/travis_emulator/tests/test_travisrc1
@@ -32,7 +32,7 @@ fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.2.1.5
+__version__=0.2.1.6
 
 
 save_testenv() {
@@ -243,10 +243,18 @@ test_04() {
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log "$@" "-J"
+parseoptest -l$TESTDIR/test_travis_em.log "$@" "-JO"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
+fi
+if [ ${opt_oeLib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
 fi
 if [ $opt_tjLib -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
@@ -256,6 +264,7 @@ if [ $opt_tjLib -ne 0 ]; then
   fi
   . $TRAVISLIBDIR
 fi
+
 
 UT1_LIST=""
 UT_LIST=""
diff --git a/travis_emulator/tests/test_travisrc2 b/travis_emulator/tests/test_travisrc2
--- a/travis_emulator/tests/test_travisrc2
+++ b/travis_emulator/tests/test_travisrc2
@@ -32,7 +32,7 @@ fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.2.1.5
+__version__=0.2.1.6
 
 
 save_testenv() {
@@ -374,6 +374,7 @@ test_04() {
     fi
     test_result "init_travis \$MQT_VERBOSE_MODE" "1" "$MQT_VERBOSE_MODE"
     s=$?; [ ${s-0} -ne 0 ] && sts=$s
+    BRANCH=9.0
     if [ -d ~/9.0 ]; then
       if [ ${opt_dry_run:-0} -eq 0 ]; then
         opt_verbose=1
@@ -479,10 +480,18 @@ test_06() {
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_travis_em.log "$@" "-J"
+parseoptest -l$TESTDIR/test_travis_em.log "$@" "-JO"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
+fi
+if [ ${opt_oeLib:-0} -ne 0 ]; then
+  ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
+  if [ -z "$ODOOLIBDIR" ]; then
+    echo "Library file odoorc not found!"
+    exit 2
+  fi
+  . $ODOOLIBDIR
 fi
 if [ $opt_tjLib -ne 0 ]; then
   TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
@@ -492,6 +501,7 @@ if [ $opt_tjLib -ne 0 ]; then
   fi
   . $TRAVISLIBDIR
 fi
+
 
 UT1_LIST=""
 UT_LIST=""
diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -33,12 +33,18 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2018 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
-THIS=$(basename $0)
+THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
-  if [ -e $x/z0librc ]; then
-    . $x/z0librc
-    Z0LIBDIR=$x
+PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
+for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
+  if [ -e $d/z0librc ]; then
+    . $d/z0librc
+    Z0LIBDIR=$d
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  elif [ -d $d/z0lib ]; then
+    . $d/z0lib/z0librc
+    Z0LIBDIR=$d/z0lib
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
     break
   fi
@@ -47,7 +53,13 @@ if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
-TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
+ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
+if [ -z "$ODOOLIBDIR" ]; then
+  echo "Library file odoorc not found!"
+  exit 2
+fi
+. $ODOOLIBDIR
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
   exit 2
@@ -56,7 +68,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.1.5
+__version__=0.2.1.6
 
 
 store_cfg_param_value() {
@@ -123,7 +135,6 @@ process_yaml_init() {
     else
       YML_lisa=lisa
     fi
-    TRAVIS=false
     TRAVIS_DEBUG_MODE="0"
     for i in {1..9}; do
       declare YML_CMD_DIS_$i=$(get_cfg_value "" "yaml__cmd_dis__$i")
@@ -497,7 +508,7 @@ process_yaml_run_cmd() {
     c=$xcmd
     if [ "$FH" == "RHEL" ]; then
       if [[ $xcmd =~ which[[:space:]]nodejs ]]; then
-        xcmd=$(echo "$xcmd"|sed -e s/nodejs/node/g) 
+        xcmd=$(echo "$xcmd"|sed -e s/nodejs/node/g)
       fi
     fi
     read -r -a x<<<"$xcmd"
@@ -563,11 +574,7 @@ process_yaml_run_cmd() {
       tk=${x[$ix]}
       while [ "${tk:0:1}" == "-" ]; do ((ix++)); tk=${x[$ix]}; done
       if [ "${x[$ix]}" == "https://github.com/zeroincombenze/tools.git" ]; then
-        if [ ${opt_virt:-0} -eq 0 ]; then
-          xcmd="ln -s $TRAVIS_SAVED_HOME/tools $HOME"
-        else
-          xcmd="cp -R $TRAVIS_SAVED_HOME/tools $HOME"
-        fi
+        xcmd="ln -s $TRAVIS_SAVED_HOME/tools $HOME"
       elif [ "${x[$ix]}" == "https://github.com/OCA/maintainer-quality-tools.git" ]; then
         if [ ${opt_virt:-0} -eq 0 ]; then
           if [ -d $HOME/maintainer-quality-tools/ -a ! -L $HOME/maintainer-quality-tools/ ]; then
@@ -642,10 +649,10 @@ process_yaml_run_cmd() {
       xcmd=${xcmd/mv /cp -R }
     elif [ "${x[$ix]}" == "rvm" -a "${x[$ix1]}" == "install" ]; then
       xcmd="# $xcmd"
-    # elif [ "${x[$ix]}" == "npm" -a "${x[$ix1]}" == "install" ]; then
-    #   xcmd="# $xcmd"
     elif [ ${opt_virt:-0} -eq 0 -a "${x[$ix]}" == "ln" -a "${x[$ix1]}" == "-s" -a "${x[$ix2]:0:16}" == "/opt/odoo/build/" ]; then
       # xcmd="ln -s /opt/odoo/${VERSION} /opt/odoo/${ODOO_REPO#*/}-${VERSION}"
+      xcmd="# $xcmd"
+    elif [ "${x[$ix]}" == "sh" -a "${x[$ix2]}" == "/etc/init.d/xvfb" ]; then
       xcmd="# $xcmd"
     elif [ ${opt_virt:-0} -eq 0 -a "${x[$ix]}" == "sh" ]; then
       xcmd="# $xcmd"
@@ -668,9 +675,9 @@ process_yaml_run_cmd() {
           xcmd="# $xcmd"
         elif [[ "${x[$ix]}" =~ TESTS=.1. ]]; then
           xtest=1
-        elif [[ "${x[$ix]}" =~ ODOO_REPO=.odoo/odoo. && ! "$YML_repo" == "odoo/odoo" ]]; then 
+        elif [[ "${x[$ix]}" =~ ODOO_REPO=.odoo/odoo. && ! "$YML_repo" == "odoo/odoo" ]]; then
           xcmd="# $xcmd"
-        elif [[ "${x[$ix]}" =~ ODOO_REPO=.OCA/OCB. && ! "$YML_repo" == "OCA/OCB" ]]; then 
+        elif [[ "${x[$ix]}" =~ ODOO_REPO=.OCA/OCB. && ! "$YML_repo" == "OCA/OCB" ]]; then
           xcmd="# $xcmd"
         elif [[ "${x[$ix]}" =~ ODOO_REPO=.$YML_repo. ]]; then
           if [ ${opt_virt:-0} -eq 0 ]; then
@@ -747,7 +754,7 @@ process_yaml() {
       create_virtual_env
       s=$?; [ ${s-0} -ne 0 ] && sts=$s
       wlog "===== [System informations] ====="
-      for lne in HOSTENV TCONF YML_FILE YML_repo MQT_DEF_PATH MQT_PATH DEVPATH TOOLS_PATH PRJNAME PKGNAME REPOSNAME BRANCH PRJPATH PKGPATH TRAVIS TRAVIS_BUILD_DIR TRAVIS_HOME TRAVIS_CWD TRAVIS_REPO_SLUG TRAVIS_BRANCH HOME_BRANCH; do
+      for lne in TCONF YML_FILE YML_repo MQT_DEF_PATH MQT_PATH DEVPATH TOOLS_PATH PRJNAME PKGNAME REPOSNAME BRANCH PRJPATH PKGPATH TRAVIS TRAVIS_BUILD_DIR TRAVIS_HOME TRAVIS_CWD TRAVIS_REPO_SLUG TRAVIS_BRANCH HOME_BRANCH; do
          lne1=${!lne}
          if [ -n "$lne1" ]; then
            wlog "\$ $lne=$lne1"
@@ -837,28 +844,29 @@ checkpid() {
 }
 
 
-OPTOPTS=(h        b          c        f         H        j        k        M          m       n            p        q           r     V           v           w)
-OPTDEST=(opt_help opt_branch opt_conf opt_force opt_virt opt_dprj opt_keep opt_dbgmnt opt_mis opt_dry_run  opt_pyth opt_verbose opt_r opt_version opt_verbose opt_wait)
-OPTACTI=(1        "="        "="      1         1        1        1        1          1       "1>"         1        0           1     "*>"        "+"         1)
-OPTDEFL=(0        10.0       ""       0         -1       0        0        0          0       0            0        -1          0     ""          -1          0)
-OPTMETA=("help"   "branch"   "file"   ""        ""       "dprj"   ""       ""         ""      "do nothing" ""       "verbose"   "res" "version"   "verbose"   "")
+OPTOPTS=(h        b          c        f         j        k        M          m       n            O         p        q           r     V           v           w        W)
+OPTDEST=(opt_help opt_branch opt_conf opt_force opt_dprj opt_keep opt_dbgmnt opt_mis opt_dry_run  opt_org   opt_pyth opt_verbose opt_r opt_version opt_verbose opt_wait opt_virt)
+OPTACTI=(1        "="        "="      1         1        1        1          1       "1>"         "="       1        0           1     "*>"        "+"         1        1)
+OPTDEFL=(0        10.0       ""       0         0        0        0          0       0            "local"   0        -1          0     ""          -1          0        0)
+OPTMETA=("help"   "branch"   "file"   ""        "dprj"   ""       ""         ""      "do nothing" "git-org" ""       "verbose"   "res" "version"   "verbose"   ""       "")
 OPTHELP=("this help"\
  "branch: must be 6.1 7.0 8.0 9.0 10.0 or 11.0 (def 10.0)"\
  "configuration file (def .travis.conf)"\
  "force yaml to run w/o cmd subst"\
- "use virtualenv to run tests"\
  "execute tests in project dir rather in test dir (or expand macro if parseyaml)"\
- "keep Db after tests"\
+ "keep DB after tests"\
  "use local MQT"\
  "show missing line in report coverage"\
  "do nothing (dry-run)"\
+ "git organization, i.e. oca or zeroincombenze"\
  "prefer python test over bash test when avaiable"\
  "silent mode"\
  "run restricted mode (w/o parsing travis.yml file)"\
  "show version"\
  "verbose mode"\
- "wait for another instance running")
-OPTARGS=(pkg action sub)
+ "wait for another instance running"\
+ "use virtualenv to run tests")
+OPTARGS=(action sub)
 
 parseoptargs "$@"
 if [ "$opt_version" ]; then
@@ -872,7 +880,6 @@ if [ $opt_help -gt 0 ]; then
 fi
 
 if [ -z "$action" ]; then action=all; fi
-if [ -z $pkg ]; then pkg="."; fi
 ACTIONS="check test all setup chkconfig parseyaml"
 VIRTACTS="check test all"
 if [[ " $ACTIONS " =~ [[:space:]]$action[[:space:]] ]]; then
@@ -886,7 +893,7 @@ else
   echo "action should be one of $ACTIONS"
   exit $STS_FAILED
 fi
-opts_travis "$pkg"
+opts_travis "$opt_org"
 CFG_init
 conf_default
 link_cfg $DIST_CONF $TCONF
