[IMP] New feature for travis emulator

diff --git a/travis_emulator/prjdiff b/travis_emulator/prjdiff
--- a/travis_emulator/prjdiff
+++ b/travis_emulator/prjdiff
@@ -4,23 +4,27 @@
 # Tool for internal use
 #
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
-# (C) 2015 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -f ./z0librc ]; then
-. ./z0librc
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
-. $TDIR/travisrc
-TCONF=$TDIR/.$THIS.conf
 
-__version__=0.1.14
+__version__=0.1.15
+
+
+TCONF=$TDIR/.$THIS.conf
 
 OPTOPTS=(h        c        n            s       V           v           0       1       2)
 OPTDEST=(opt_help opt_conf opt_dry_run  opt_sel opt_version opt_verbose opt_sts opt_sts opt_2nd)
@@ -45,7 +49,7 @@ if [ "$opt_version" ]; then
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Diff files of project"\
-  "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2017 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 
diff --git a/travis_emulator/set_ssh_prot b/travis_emulator/set_ssh_prot
--- a/travis_emulator/set_ssh_prot
+++ b/travis_emulator/set_ssh_prot
@@ -1,18 +1,27 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
+# Set default protection of user root dir in order to run ssh
+#
+# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
+# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -f ./z0librc ]; then
-. ./z0librc
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
 
-__version__=0.1.4
+__version__=0.1.5
+
+
 OPTOPTS=(h        G         n            V           v)
 OPTDEST=(opt_help opt_group opt_dry_run  opt_version opt_verbose)
 OPTACTI=(1        "="       "1>"         "*>"        1)
@@ -32,7 +41,7 @@ if [ "$opt_version" ]; then
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Set default protection of user root dir in order to run ssh"\
-  "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2017 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 if [ $opt_verbose -gt 1 ]; then set -x; fi
diff --git a/travis_emulator/test_nightly b/travis_emulator/test_nightly
--- a/travis_emulator/test_nightly
+++ b/travis_emulator/test_nightly
@@ -5,30 +5,29 @@
 # Tool for internal use
 #
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
-# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
+
+__version__=0.1.79
+
 
 if [ $EUID -eq 0 -a -d /opt/odoo/tools/z0lib ]; then
   cd /opt/odoo/tools/z0lib
 fi
-THIS=$(basename $0)
-TDIR=$(readlink -f $(dirname $0))
 FCONF=$TDIR/.$THIS.conf
-if [ -e $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -e ./z0librc ]; then
-. ./z0librc
-elif [ -e ../z0librc ]; then
-. ../z0librc
-elif [ -e ~/z0librc ]; then
-. ~/z0librc
-elif [ -f /etc/z0librc ]; then
-. /etc/z0librc
-else
-  echo "Library file z0librc not found!"
-  exit 1
-fi
-
-__version__=0.1.78
 
 # main
 OPTOPTS=(h        A         C        K        n           O        R           t        V           v           8     9)
@@ -57,7 +56,7 @@ if [ "$opt_version" ]; then
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Test nightly"\
-  "(C) 2015-2016 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2017 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 
diff --git a/travis_emulator/tests/test_Makefile b/travis_emulator/tests/test_Makefile
--- a/travis_emulator/tests/test_Makefile
+++ b/travis_emulator/tests/test_Makefile
@@ -4,17 +4,21 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
diff --git a/travis_emulator/wok_doc b/travis_emulator/wok_doc
--- a/travis_emulator/wok_doc
+++ b/travis_emulator/wok_doc
@@ -4,21 +4,25 @@
 # Tool for internal use
 #
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
-# (C) 2015 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -f ./z0librc ]; then
-. ./z0librc
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
 
-__version__=0.1.5
+__version__=0.1.6
+
 
 # main
 OPTOPTS=(h        n            V           v)
@@ -39,7 +43,7 @@ if [ "$opt_version" ]; then
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Write module documentation\nTemporary: do not use in production!"\
-  "(C) 2015 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2017 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 if [ -z "$module" ]; then
diff --git a/z0lib/optargs b/z0lib/optargs
--- a/z0lib/optargs
+++ b/z0lib/optargs
@@ -1,13 +1,5 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
-if [ -f z0librc ]; then
-. ./z0librc
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
-fi
-
 ##############################################################################
 #
 #    Copyright (C) SHS-AV s.r.l. (<http://ww.zeroincombenze.it>)
@@ -27,7 +19,23 @@ fi
 #
 ##############################################################################
 
-__version__=0.1.4
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
+
+__version__=0.1.5
+
 if [ "$OPTARGS_TEST_1_2" ]; then
   test_1_2=$OPTARGS_TEST_1_2
 else
diff --git a/z0lib/xuname b/z0lib/xuname
--- a/z0lib/xuname
+++ b/z0lib/xuname
@@ -1,19 +1,29 @@
 #!/bin/bash
-
-if [ -f z0librc ]; then
-. ./z0librc
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
-fi
-
+# -*- coding: utf-8 -*-
+# xuname: enhanced uname
 # Detect and print more OS informations than uname command
-# Simple how to use z0librc library 
+# Simple how to use z0librc library
 # Copyright (C) SHS-AV s.r.l. (<http://ww.zeroincombenze.it>)
 # This free software is released under GNU Affero GPL3
+#
 
-__version__="0.1.8"
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
+
+__version__=0.1.9
+
 
 # Main program
 OPTOPTS=(h        a       c       d       f        i       k       m       p       r       s       v       V           x)
diff --git a/zar/restwww b/zar/restwww
--- a/zar/restwww
+++ b/zar/restwww
@@ -2,19 +2,21 @@
 # -*- coding: utf-8 -*-
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -e $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -e ./z0librc ]; then
-. ./z0librc
-elif [ -e ../z0librc ]; then
-. ../z0librc
-elif [ -e ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
+for x in $TDIR $TDIR/.. . .. $TDIR/../../z0lib /etc; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
 
-__version__="1.4.29"
+__version__=1.4.30
+
 
 conf_default () {
     set_cfg_def "DEV_HOST" "shsita16"
