[RUN] blueman test

diff --git a/travis_emulator/test_nightly b/travis_emulator/test_nightly
--- a/travis_emulator/test_nightly
+++ b/travis_emulator/test_nightly
@@ -21,7 +21,7 @@ if [ -z "$Z0LIBDIR" ]; then
   exit 2
 fi
 
-__version__=0.1.79.3
+__version__=0.1.79.5
 
 
 FCONF=$TDIR/.$THIS.conf
@@ -144,24 +144,24 @@ test_pkg_pypi() {
       mkdir ~/dev/svg
     fi
     if [ $opt_dry_run -eq 0 ]; then
-      wlog "------------------------------------"
-      wlog "Required test for $1 package ..."
+      wlog "-----------------------------------------"
+      wlog "### Required test for $1 package ..."
     else
-      wlog "Package $1 should be tested"
+      wlog "### Package $1 should be tested"
     fi
     if [ ! -d ~/dev/pypi/$1 ]; then
       generate_svg "$USER" "WARN" "$__version__"
-      wlog "!? Package $1 not found!"
+      wlog "!!!? Package $1 not found!"
       exit 1
     fi
     if [ ! -d ~/dev/pypi/$1/$1 ]; then
       generate_svg "$USER" "WARN" "$__version__"
-      wlog "!? Invalid package $1!"
+      wlog "!!!? Invalid package $1!"
       exit 1
     fi
     if [ ! -d ~/dev/pypi/$1/$1/tests ]; then
       generate_svg "$1" "WARN"
-      wlog "!? Unit test for package $1 not found"
+      wlog "!!!? Unit test for package $1 not found"
       exit 0
     fi
     sts=$STS_SUCCESS
@@ -171,7 +171,7 @@ test_pkg_pypi() {
     if [ $sts -eq $STS_SUCCESS ]; then
       if [ $opt_dry_run -eq 0 ]; then
         run_traced "please wep  # $1"
-        wlog "Package $1: test successfully terminated"
+        wlog "### Package $1: test successfully terminated"
       fi
       if [ -x ./$1 ]; then
         local ver=$(./$1 -V)
@@ -181,7 +181,7 @@ test_pkg_pypi() {
       generate_svg "$1" "OK" "$ver"
     else
       generate_svg "$1" "FAIL"
-      wlog "!? Package $1: test failed ($sts)! See package log in ~/dev/pypi/$1/$1/tests!!!"
+      wlog "!!!? Package $1: test failed ($sts)! See package log in ~/dev/pypi/$1/$1/tests!!!"
     fi
     return $sts
 }
@@ -191,20 +191,20 @@ pkg_pypi_commit() {
 # pkg_pypi_commit(name)
 # return: sts
     if [ $opt_dry_run -eq 0 ]; then
-      wlog "Committing $1 package  ..."
+      wlog "### Committing $1 package  ..."
     else
-      wlog "Package $1 should be committed"
+      wlog "### Package $1 should be committed"
     fi
     if [ ! -d ~/dev/pypi/$1 ]; then
-      wlog "!? Package $1 not found!"
+      wlog "!!!? Package $1 not found!"
       exit 1
     fi
     if [ ! -d ~/dev/pypi/$1/$1 ]; then
-      wlog "!? Invalid package $1!"
+      wlog "!!!? Invalid package $1!"
       exit 1
     fi
     if [ ! -d ~/dev/pypi/$1/$1/tests ]; then
-      wlog "!? Unit test for package $1 not found"
+      wlog "!!!? Unit test for package $1 not found"
       exit 0
     fi
     sts=$STS_SUCCESS
@@ -225,7 +225,7 @@ oe_upd_burst() {
       local clodir=$(get_cfg_value "" "CLODIR")
       run_traced "cd $clodir"
       if [ -z "$opt_ncld" -a -f $1.conf -a $opt_dry_run -eq 0 ]; then
-        wlog "Starting all DB Odoo burst upgrade (-c $1.conf)"
+        wlog "### Starting all DB Odoo burst upgrade (-c $1.conf)"
         local SLEEP_TM=$(get_cfg_value "" "SLEEP_TIME")
         local SLEEP_TML
         local SLEEP_TMS
@@ -275,15 +275,15 @@ oe_upd_burst() {
           fi
           run_traced "mv $1.conf $1.conf.bak"
         fi
-        wlog "** All DB Odoo burst upgrade ended **"
+        wlog "### All DB Odoo burst upgrade ended **"
       else
-        wlog "No clodoo operations to do"
+        wlog "### No clodoo operations to do"
       fi
       if [ -f /var/log/$THIS.log ]; then
         chmod +rw /var/log/$THIS.log
       fi
     else
-      wlog "*** Odoo burst upgrade is already running ***"
+      wlog "### Odoo burst upgrade is already running ***"
     fi
     return $sts
 }
@@ -291,11 +291,11 @@ oe_upd_burst() {
 
 check4env() {
     if [ ! -d ~/dev/pypi ]; then
-      wlog "!? Invalid environment: missing ~/dev/pypi directory!"
+      wlog "!!!? Invalid environment: missing ~/dev/pypi directory!"
       exit 1
     fi
     if [ ! -d ~/dev/_travis ]; then
-      wlog "!? Invalid environment: missing ~/dev/_travis directory!"
+      wlog "!!!? Invalid environment: missing ~/dev/_travis directory!"
       exit 1
     fi
     if [ ! -d /opt/odoo/tools ]; then
@@ -411,7 +411,7 @@ mvfiles() {
 generate_svg() {
 # generate_svg(id, result, ver?)
     if [ $opt_dry_run -eq 0 ]; then
-      wlog "generate_svg $1[ $2 ] -V$3"
+      wlog "### generate_svg $1[ $2 ] -V$3"
     fi
     local sw_id="$1"
     local sw_date=$(date +%d-%m-%Y)
@@ -479,41 +479,60 @@ synchronize_odoo() {
     local dow=$1
     local VERSION=
     local sts=$STS_SUCCESS
+    declare -A PYPKGS
+    wlog "========================================================"
+    wlog "======            Starting Odoo tests             ======"
     for VERSION in 6.1 7.0 8.0 9.0 10.0; do
       n=$(echo $VERSION|grep -Eo [0-9]*|head -n1)
-      let n="11-$n"
+      let n="13-$n"
       if [ $n -ne $dow ]; then
         continue
       fi
+      wlog "====== Odoo $VERSION ======"
       for d in $HOME/$VERSION/*; do
         if [ -d $d ]; then
           if [ -d $d/.git ]; then
+            wlog "------ Module $d ------"
             run_traced "cd $d"
             run_traced "please synchro . zero-merged"
             s=$?; [ ${s-0} -ne 0 ] && sts=$s
             if [ $s -eq $STS_SUCCESS ]; then
               run_traced "travis"
               s=$?; [ ${s-0} -ne 0 ] && sts=$s
-              if [ $s -ne $STS_SUCCESS ]; then
-                wlog "-- travis tes of $d FAILED!"
+              if [ $s -eq $STS_SUCCESS ]; then
+                PYPKGS[$PKGNAME]='Ok'
+              else
+                PYPKGS[$PKGNAME]='FAILED'
+                wlog "### travis test of $d FAILED!"
               fi
             else
-              wlog "-- synchronization of $d FAILED!"
+              PYPKGS[$PKGNAME]='Not synchronized'
+              wlog "### synchronization of $d FAILED!"
             fi
           fi
         fi
+        PKGNAME=OCB
         run_traced "cd $HOME/$VERSION/"
         run_traced "please synchro . zero-merged"
         s=$?; [ ${s-0} -ne 0 ] && sts=$s
         if [ $s -eq $STS_SUCCESS ]; then
           run_traced "travis"
           s=$?; [ ${s-0} -ne 0 ] && sts=$s
-          if [ $s -ne $STS_SUCCESS ]; then
-            wlog "-- travis tes of $d FAILED!"
+          if [ $s -eq $STS_SUCCESS ]; then
+            PYPKGS[$PKGNAME]='Ok'
+          else
+            PYPKGS[$PKGNAME]='FAILED'
+            wlog "### travis tes of $d FAILED!"
           fi
         else
-          wlog "-- synchronization of $d FAILED!"
+          PYPKGS[$PKGNAME]='Not synchronized'
+          wlog "## synchronization of $d FAILED!"
         fi
+        wlog "--------------------------------------------------------"
+        for PKGNAME in ${!PYPKGS[*]}; do
+          echo "$VERSION/$PKGNAME: ${PYPKGS[$PKGNAME]}"
+        done
+        wlog "--------------------------------------------------------"
       done
     done
     retrun $sts
@@ -531,9 +550,9 @@ exit_n_status() {
       ssh $PRD_HOST "~/bin/cronow -s $THIS"
     fi
     if [ $opt_dry_run -eq 0 ]; then
-      wlog "Test $__version__ successfully terminated"
+      wlog "### Test $__version__ successfully terminated"
     else
-      wlog "++ Dry-run $__version__ executed with success ++"
+      wlog "+++ Dry-run $__version__ executed with success +++"
     fi
   else
     generate_svg "$USER" "FAIL" "$__version__"
@@ -638,12 +657,13 @@ fi
 
 ODOO_LTF=~/testlog/result.log
 
+dtme=$(date +"%Y-%m-%d %H:%M:%S")
 if [ $opt_dry_run -eq 0 ]; then
-  wlog "********************************************************"
-  wlog "Test nightly $__version__ starting by $USER"
-  wlog "********************************************************"
+  wlog "*************************************************************"
+  wlog "Test nightly $__version__ starting by $USER on $dtme"
+  wlog "*************************************************************"
 else
-  wlog "++ Test nightly $__version__ is dry-running by $USER ++"
+  wlog "+++ Test nightly $__version__ is dry-running by $USER +++"
 fi
 if [ $EUID -eq 0 ]; then
   if [ -d /opt/odoo/tools/z0lib ]; then
@@ -768,35 +788,45 @@ if [ $EUID -eq 0 ]; then
 fi
 if [ "$USER" == "odoo" ]; then
   (($opt_dry_run))||check4env
+  sts=$STS_SUCCESS
+  wlog "========================================================"
+  wlog "### PYPI Package tests"
   cd ~/dev/pypi
+  declare -A PYPKGS
   for PKGNAME in *; do
-    if [ $sts -eq $STS_SUCCESS ]; then
-      valid=0
-      if [ -d "$PKGNAME" ]; then
-        for p in $PKGSLX; do
-          if [ "$PKGNAME" == "$p" ]; then
-            valid=1
-            break
-          fi
-        done
-        if [ $valid -gt 0 ]; then
-          test_pkg_pypi $PKGNAME
-          sts=$?
-          if [ $sts -eq $STS_SUCCESS ]; then
-            pkg_pypi_commit $PKGNAME
-          fi
-        else
-          wlog "------------------------------------"
-          wlog "Module $PKGNAME uncertificated ($sts)!"
+    valid=0
+    if [ -d "$PKGNAME" ]; then
+      for p in $PKGSLX; do
+        if [ "$PKGNAME" == "$p" ]; then
+          valid=1
+          break
         fi
+      done
+      if [ $valid -gt 0 ]; then
+        test_pkg_pypi $PKGNAME
+        s=$?; [ ${s-0} -ne 0 ] && sts=$s
+        if [ $s -eq $STS_SUCCESS ]; then
+          PYPKGS[$PKGNAME]='Ok'
+          pkg_pypi_commit $PKGNAME
+        else
+          PYPKGS[$PKGNAME]='FAILED'
+        fi
+      else
+        wlog "------------------------------------"
+        wlog "### Module $PKGNAME uncertificated!"
       fi
     fi
     cd ~/dev/pypi
   done
+  wlog "-----------------------------------------------------------"
+  for PKGNAME in ${!PYPKGS[*]}; do
+    echo "$PKGNAME: ${PYPKGS[$PKGNAME]}"
+  done
+  wlog "-----------------------------------------------------------"
+  wlog "### End of package tests, commit results into tool package"
   wlog "cd ~/tools"
   cd ~/tools
   if [ $opt_dry_run -eq 0 ]; then
-    wlog "-- End of package tests, commit results into tool package"
     tm=$(date +%H%M)
     if [ $tm -gt 2000 -o $tm -lt 0600 ]; then
       cmsg="[RUN] test nightly"
