[IMP] test_synchro: test account.payment.term

diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -2,7 +2,7 @@
 #
 # Common file for travis emulator scripts
 #
-#__version__=1.0.0.5
+#__version__=1.0.0.6
 
 # MAKEF=$HOME/dev/Makefile
 [[ "${BASH_SOURCE-}" == "$0" ]] && echo "You must source this script: \$ source $0" >&2 && exit 33
@@ -398,6 +398,21 @@ custom_env() {
   fi
 }
 
+uname() {
+    local x UNAME
+    UNAME=$(which uname)
+    [[ -x $TRAVIS_HOME/bin/greadlink ]] && echo "Darwin" || $UNAME "$@"
+}
+
+set_osx() {
+    local x
+    x=$(which readlink)
+    run_traced "ln -s $x $TRAVIS_HOME/bin/greadlink"
+    echo "echo '*** INVALID READLINK: USE GREADLINK! ***'" >$TRAVIS_HOME/bin/readlink
+    echo "exit 2" >>$TRAVIS_HOME/bin/readlink
+    chmod +x $TRAVIS_HOME/bin/readlink
+}
+
 create_virtual_env() {
   local f p t x
   export TRAVIS_BRANCH=$BRANCH
@@ -456,6 +471,7 @@ create_virtual_env() {
     sts=$?
   fi
   [ $sts -ne 0 ] && return
+  [[ $TRAVIS_EMULATE_OSX == "true" ]] && set_osx
   local SAVE_COLOR=$PS_RUN_COLOR
   export PS_RUN_COLOR=$PS_HDR3_COLOR
   echo -en "\e[${PS_RUN_COLOR}m"
