[IMP] new cronow command

diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -1,27 +1,37 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
-if [ -f z0librc ]; then
+#
+# Travis-ci emulator
+# Emulate travis-ci on local machine, to test before upgrade git project
+#
+# This free software is released under GNU Affero GPL3
+# author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
+# (C) 2015 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+#
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
+if [ -f $TDIR/z0librc ]; then
+. $TDIR/z0librc
+elif [ -f ./z0librc ]; then
 . ./z0librc
 elif [ -f ~/z0librc ]; then
 . ~/z0librc
 else
 . /etc/z0librc
 fi
-MYDIR=$(echo $(readlink -f $(dirname $0)))
-. $MYDIR/travisrc
+. $TDIR/travisrc
+TCONF=$TDIR/.$THIS.conf
 
-# Travis-ci emulator
-# Emulate travis-ci on local machine, to test before upgrade git project
-# Copyright (C) SHS-AV s.r.l. (<http://ww.zeroincombenze.it>)
-# This software is free software under GNU Affero GPL3
+__version__=0.1.28
 
-__version__=0.1.23
-OPTOPTS=(h        n            V           v           b)
-OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose opt_branch)
-OPTACTI=(1        "1>"         "*>"        1           "=")
-OPTDEFL=(1        0            ""          0           8.0)
-OPTMETA=("help"   "do nothing" "version"   "verbose"   "branch")
+
+OPTOPTS=(h        c        n            V           v           b)
+OPTDEST=(opt_help opt_conf opt_dry_run  opt_version opt_verbose opt_branch)
+OPTACTI=(1        "="      "1>"         "*>"        1           "=")
+OPTDEFL=(1        ""       0            ""          0           8.0)
+OPTMETA=("help"   "file"   "do nothing" "version"   "verbose"   "branch")
 OPTHELP=("this help"\
+ "configuration file"\
  "do nothing (dry-run)"\
  "show version"\
  "verbose mode",
@@ -38,47 +48,41 @@ if [ $opt_help -gt 0 ]; then
   "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
-if [ $opt_verbose -gt 0 ]; then
-  set -x
-fi
-
-if [ -f travis.conf ]; then
-   SETUP=travis.conf
-   DEV_PATH=$(grep "[^a-zA-Z0-9_]devpath *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d ", \r\n")
-   TOOLS_PATH=$(grep "[^a-zA-Z0-9_]tools_path *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d ", \r\n")
-   if [ -z "repository" ]; then
-     repository=$(grep "[^a-zA-Z0-9_]odoo_repo *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d ", \r\n")
-   fi
-   BRANCH=$(grep "[^a-zA-Z0-9_]branch *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d ", \r\n")
+DEVPATH=$TDIR
+if [ "$opt_conf" -a -f "$opt_conf" ]; then
+  TCONF=$opt_conf
 fi
 if [ "$repository" == "." ]; then repository=$(echo "local/$(basename $PWD)"); fi
 if [ -z "$repository" ]; then repository=$(echo "local/$(basename $PWD)"); fi
-prjname=$(basename $repository)
 if [ -z $PKGPATH ]; then
   PKGPATH=$PWD
 fi
 PKGPATH=$(set_pkgpath "$PKGPATH")
+pkgname=$(basename $PKGPATH)
+$(init_cfg)
+$(active_cfg)
+conf_default
+link_cfg $TCONF
+init_travis
+PRJNAME=$(basename $repository)
 
-if [ -z "$DEV_PATH" ]; then
-  if [ "$prjname" == "travis_emulator" ]; then
-    DEV_PATH=$PKGPATH/$prjname/travis
-    if [ -z "$TOOLS_PATH" ]; then
-      devpath=$(if [ "$PYTHONPATH" ]; then echo "$PYTHONPATH"; elif [ -d $HOME/dev ]; then echo "$HOME/dev"; else echo "/opt/openerp/dev"; fi)
-      if [ -d $devpath/maintainer-quality-tools/travis ]; then
-       TOOLS_PATH=$devpath/maintainer-quality-tools/travis
-      else
-       unset -v TOOLS_PATH
-     fi
-    fi
+
+if [ $opt_verbose -eq 0 ]; then
+  opt_verbose=$(get_cfg_value "" "loglevel")
+fi
+if [ $opt_verbose -gt 1 ]; then
+  set -x
+fi
+
+if [ -z "$TOOLS_PATH" ]; then
+  if [ -d $DEVPATH/maintainer-quality-tools/travis ]; then
+    TOOLS_PATH=$DEVPATH/maintainer-quality-tools/travis
+  elif [ -d $HOME/dev/maintainer-quality-tools/travis ]; then
+    TOOLS_PATH=$HOME/dev/maintainer-quality-tools/travis
+  elif [ -d /opt/odoo/dev/maintainer-quality-tools/travis ]; then
+    TOOLS_PATH=/opt/odoo/dev/maintainer-quality-tools/travis
   else
-    DEV_PATH=$(if [ "$PYTHONPATH" ]; then echo "$PYTHONPATH"; elif [ -d $HOME/dev ]; then echo "$HOME/dev"; else echo "/opt/openerp/dev"; fi)
-    if [ -z "$TOOLS_PATH" ]; then
-      if [ -d $DEV_PATH/maintainer-quality-tools/travis ]; then
-       TOOLS_PATH=$DEV_PATH/maintainer-quality-tools/travis
-      else
-       unset -v TOOLS_PATH
-     fi
-    fi
+    unset -v TOOLS_PATH
   fi
 fi
 if [ "$TOOLS_PATH" ]; then
@@ -93,14 +97,10 @@ if [ "$action" == "check" ]; then
   export LINT_CHECK=1
 elif [ "$action" == "test" ]; then
   export LINT_CHECK=0
-elif [ "$prjname" != "Odoo" ]; then
+elif [ "$PRJNAME" != "Odoo" ]; then
   export LINT_CHECK=1
 else
   unset -v LINT_CHECK
-  if [ $opt_dry_run -eq 0 ]; then
-    find $PKGPATH -name "*~" -exec rm -vf '{}' \;
-    find $PKGPATH -name "*.bak" -exec rm -vf '{}' \;
-  fi
 fi
 # Default value for local environment
 if [ -z $BRANCH ]; then
@@ -109,38 +109,48 @@ fi
 export VERSION=$BRANCH
 export TRAVIS_BUILD_DIR=$PKGPATH
 export ODOO_REPO=$repository
-# export INCLUDE=/opt/openerp/$BRANCH
-if [ ! -d $PKGPATH/$prjname ]; then
-  echo "Invalid repository"
+export VERBOSE_MODE=$opt_verbose
+if [ ! -d $PKGPATH ]; then
+  echo "Invalid repository $PKGPATH"
   exit 1
+elif [ "$PRJNAME" != "Odoo" ]; then
+  if [ ! -d $PKGPATH/$pkgname ]; then
+    echo "Invalid repository $PKGPATH/$pkgname"
+    exit 1
+  fi
 fi
-if [ "$prjname" == "Odoo" ]; then
+if [ "$PRJNAME" == "Odoo" ]; then
   if [ $opt_dry_run -eq 0 ]; then
     dropdb  openerp_template 2>/dev/null||true
   fi
 fi
 if [ $opt_dry_run -eq 0 ]; then
   if [ "$TOOLS_PATH" ]; then
-    echo "$TOOLS_PATH/travis_run_tests"
+    if [ $opt_verbose -gt 0 ]; then
+      echo "$TOOLS_PATH/travis_run_tests"
+    fi
     $TOOLS_PATH/travis_run_tests
   else
-    echo "travis_run_tests"
+    if [ $opt_verbose -gt 0 ]; then
+      echo "travis_run_tests"
+    fi
     travis_run_tests
   fi
 fi
 if [ $? -eq 0 -a "$action" != "check" ]; then
-  if [ "$prjname" != "Odoo" ]; then
-    cd $PKGPATH/$prjname;
+  if [ "$PRJNAME" != "Odoo" ]; then
+    cd $PKGPATH/$PRJNAME;
     if [ $opt_dry_run -eq 0 ]; then
-      find . -name "*$prjname*.log" -exec rm -f '{}' \;
+      find . -name "*$PRJNAME*.log" -exec rm -f '{}' \;
       coverage erase
-      DEV_ENVIRONMENT=$prjname PYTHONPATH=$PKGPATH coverage run --source $prjname __main__.py
-      # PYTHONPATH=$PKGPATH coverage run --source $prjname $TESTDIR/test_$prjname.py
+      DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py
     fi
   fi
-  echo ""
-  echo "The command \"travis_run_tests\" exited with 0."
-  echo "coveralls"
+  if [ $opt_verbose -gt 0 ]; then
+    echo ""
+    echo "The command \"travis_run_tests\" exited with 0."
+    echo "coveralls"
+  fi
   if [ $opt_dry_run -eq 0 ]; then
     coverage report
   fi
diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -2,51 +2,153 @@
 # -*- coding: utf-8 -*-
 #
 # Common file for travis emulator scripts
-#__version__=0.1.9
+#__version__=0.1.32
 
-ODOO_SETUP=__openerp__.py
 MAKEF=/opt/odoo/dev/Makefile
-DIST_CONF=./conf/.friends.conf
-XRGX="^.*\.pyc$ ^.*\.log$ ^.*\.bak$ ^.*\.out$ ^.*\.conf$ ^(.*\/|)build\/ ^(.*\/|)dist\/ ^(.*\/|)conf\/ ^(.*\/|)\.cover\/ ^(.*\/|)\.coverage\/ ^(.*\/|)\.git\/ ^.*~$"
+DIST_CONF=./conf/.local_dist_pkg.conf
 XRGI="^(.*\/|)conf\/.*sample$"
 XXXX=".pyc .log .bak .out .conf build/ dist/ conf/ .cover/ .coverage/ .git/ ~"
-XLFS=
-for x in $XXXX;do
-  XLFS="$XLFS --exclude *$x"
-done
-XLDF=
-for x in $XXXX;do
-  XLDF="$XLDF -x *$x"
-done
+
+
+init_travis () {
+    if [ $opt_dry_run -gt 0 ]; then
+      opts_dry_run=-n
+    else
+      opts_dry_run=
+    fi
+    if [ ${opt_upd:-0} -gt 0 ]; then
+      opts_upd=-u
+    else
+      opts_upd=
+    fi
+    ODOO_SETUP=$(get_cfg_value "" "ODOO_SETUP")
+    if [ "$ODOO_SETUP" -a -f $ODOO_SETUP ]; then
+      SETUP="$ODOO_SETUP";
+      REPOSNAME=$(basename $(readlink -e ..))
+      if [ "$REPOSNAME" == "odoo" -o "$REPOSNAME" == "openerp" ]; then
+        REPOSNAME=
+      fi
+    elif [ -f $PKGPATH/setup.py ]; then
+      SETUP="$PKGPATH/setup.py";
+      REPOSNAME=$(basename $PKGPATH)
+    else
+       SETUP="$ODOO_SETUP";
+       REPOSNAME=
+    fi
+    if [ "$SETUP" == "$ODOO_SETUP" ]; then
+      if [ -z "$PRJNAME" ]; then
+        PRJNAME="Odoo"
+      fi
+      if [ -f $ODOO_SETUP ]; then
+        prjversion=$(grep "'version' *:" $SETUP 2>/dev/null|awk -F":" '{print $2}'|tr -d "\"', \r\n")
+        prjdesc=$(grep "'name' *:" $SETUP 2>/dev/null|awk -F":" '{print $2}'|tr -d "\"',\r\n")
+      else
+        prjversion=""
+        prjdesc="Unrecognized Odoo module"
+      fi
+    else
+      if [ "$SETUP" -a -f $SETUP ]; then
+        if [ -z "$PRJNAME" ]; then
+          PRJNAME=$(grep "[^a-zA-Z0-9_]name *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"', \r\n")
+        fi
+        prjversion=$(grep "[^a-zA-Z0-9_]version *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"', \r\n")
+        if [ "$prjversion" == "version" ]; then
+          prjversion=""
+        fi
+        prjdesc=$(grep "[^a-zA-Z0-9_]description *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"',\r\n")
+        if [ "$prjdesc" == "description" ]; then
+          prjdesc="Unrecognized Odoo module"
+        fi
+      fi
+    fi
+    if [ "$PRJNAME" == "odoo" ]; then
+      PRJNAME=Odoo
+    fi
+    if [ "$PRJNAME" == "Odoo" ]; then
+      if [ -z "$prjversion" ]; then
+        prjversion=$(if $(echo "$PWD/"|grep "/v8/\|8.0/">/dev/null); then echo "8.0"; else echo "7.0"; fi)
+      fi
+    fi
+}
+
+
+conf_default () {
+    set_cfg_def "loglevel" "0"
+    set_cfg_def "ODOO_SETUP" "__openerp__.py"
+}
 
 
 expand_path () {
 # expand_path (path)
 # return:path
-    echo "$1"|sed s:\${pkgpath}:$PKGPATH:g|sed s:\${pkgname}:$pkgname:g|sed s:\${prjname}:$prjname:g
+    echo "$1"|sed -e s:\${pkgpath}:$PKGPATH:g -e s:\${pkgname}:$pkgname:g -e s:\${prjname}:$PRJNAME:g -e s:\${reposname}:$REPOSNAME:g
 }
 
 
 set_pkgpath () {
 # set_pkgpath (pkgname)
 # return:pkgpath
-    PKGPATH=$1
+    PKGPATH="$1"
     if [ -z "$PKGPATH" ]; then
       PKGPATH=$PWD
-    elif [ "${PKGPATH:0:1}" != "." -a "${PKGPATH:0:1}" != "/" ]; then
-      local oPKGPATH="$PKGPATH"
+    fi
+    if [ "${PKGPATH:0:1}" != "." -a "${PKGPATH:0:1}" != "/" ]; then
       local x=$(readlink -e ../$PKGPATH)
       if [ "$x" -a "$(basename $x)" == "$PKGPATH" ]; then
         PKGPATH=$x
-        local x=$(readlink -e $PKGPATH/..)
-        if [ "$x" -a "$(basename $x)" == "$oPKGPATH" ]; then
-          PKGPATH=$x
-        fi
       fi
     fi
-    echo $PKGPATH
+    local x="$(readlink -e $PKGPATH/..)"
+    if [ "$x" ]; then
+      local d=
+      for d in tests build dist conf .cover .coverage; do
+        if [ "$(basename $PKGPATH)" == "$d" ]; then
+          PKGPATH="$x"
+          local x="$(readlink -e $PKGPATH/..)"
+          break
+        fi
+      done
+    fi
+    if [ "$x" -a "$(basename $x)" == "$(basename $PKGPATH)" -a -f "$x/setup.py" ]; then
+      PKGPATH="$x"
+    fi
+    echo "$PKGPATH"
 }
 
+
+update_dev_travis () {
+    XDPATH=$(echo "$(dirname $MAKEF)")
+    RFLIST="beauty cronow .dist_pkg.conf dist_pkg Makefile prjdiff test_nightly topep8 travis travisrc wok_doc wok_doc.py"
+    xvalid=1
+    for x in $RFLIST; do
+      if [ ! -f $PKGPATH/$pkgname/$x ]; then
+        xvalid=0
+      fi
+    done
+    if [ $xvalid -eq 0 ]; then
+       echo "Invalid package travis_emulator!"
+       exit 1
+    fi
+    if [ -z "$opt_sts" -o "$opt_cpush" != "-w" ]; then
+      for x in $RFLIST; do
+        if [ -f $PKGPATH/$pkgname/$x ]; then
+          if [ ${opt_diff:-0} -gt 0 ]; then
+            if [ "$(diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x)" ]; then
+              if [ ${opt_verbose:-0} -gt 0 ]; then echo "> diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
+              diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x
+            fi
+          elif [ ${opt_fetch:-0} -gt 0 ]; then
+            if [ ${opt_verbose:-0} -gt 0 ]; then echo "> $opt_dry_run||cp $XDPATH/$x $PKGPATH/$pkgname/$x"; fi
+            (($opt_dry_run))||cp $XDPATH/$x $PKGPATH/$pkgname/$x
+          else
+            if [ $opt_verbose -gt 0 ]; then echo "> $opt_dry_run||cp $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
+            (($opt_dry_run))||cp $PKGPATH/$pkgname/$x $XDPATH/$x
+          fi
+        fi
+      done
+      MAKEF=$PKGPATH/$pkgname/Makefile
+    fi
+}
 
 a_append () {
 # a_append (key, values)::DEFPRM,DEFVAL
@@ -106,7 +208,7 @@ matches1of () {
 
 
 robocopy_init () {
-# robocopy_init (prjname, pkgname)::opt_fetch
+# robocopy_init (prjname, pkgname)::DIST_CONF,TCONF,opt_fetch,opt_verbose
 # return:
     a_append "--new"
     a_append "^.*\.egg-info$" ""
@@ -117,18 +219,64 @@ robocopy_init () {
       a_append "setup.py" ""
       a_append "$2" "/"
       a_append "conf" "/"
-      if [ $opt_fetch -eq 0 ]; then
-      #   a_append "README.rst" "/$2/README.rst"
-      #   a_append "README.md" "/$2/README.md"
+      if [ ${opt_fetch:-0} -eq 0 ]; then
          a_append "README.rst" "/"
          a_append "README.md" "/"
       fi
       a_append "^.*" ""
     fi
+    if [ "$DIST_CONF" ]; then
+      local xx=$(grep "^ignore *=" $DIST_CONF 2>/dev/null|awk -F"[a-z0-9 ]=" '{print $2}'|tr -d "\"'\r\n")
+      local yy=$(grep "^ignorediff *=" $DIST_CONF 2>/dev/null|awk -F"[a-z0-9 ]=" '{print $2}'|tr -d "\"'\r\n")
+    fi
+    if [ -z "$xx" -a "$TCONF" ]; then
+      local xx=$(grep "^ignore *=" $TCONF 2>/dev/null|awk -F"[a-z0-9 ]=" '{print $2}'|tr -d "\"'\r\n")
+      local yy=$(grep "^ignorediff *=" $TCONF 2>/dev/null|awk -F"[a-z0-9 ]=" '{print $2}'|tr -d "\"'\r\n")
+    fi
+    if [ -z "$xx" ]; then
+      # TODO: addons
+      local xx=".pyc .log .bak .out .conf build/ dist/ conf/ filestore/ .cover/ .coverage/ .git/ ~"
+      local yy=".po .pot"
+    fi
+    XRGX=
+    XLFS=
+    XLDF=
+    for x in $xx; do
+      local x1="${x:0:1}"
+      local l=
+      let l=${#x}-1
+      local x9="${x:l:1}"
+      if [ "$x9" == "/" ]; then
+         XRGX="$XRGX ^(.*\\/|)$x"
+         XLFS="$XLFS --exclude=$x"
+      elif [ "$x1" == "." -o "$x" == "~" ]; then
+         XRGX="$XRGX ^.*\\$x\$"
+         XLFS="$XLFS --exclude=*$x"
+      else
+         XRGX="$XRGX $x"
+         XLFS="$XLFS --exclude=*$x*"
+      fi
+      XLDF="$XLDF -x '*$x'"
+    done
+    XXDF=
+    for x in $yy; do
+      local x1="${x:0:1}"
+      local l=
+      let l=${#x}-1
+      local x9="${x:l:1}"
+      if [ "$x9" == "/" ]; then
+         XXDF="$XXDF ^(.*\\/|)$x"
+      elif [ "$x1" == "." -o "$x" == "~" ]; then
+         XXDF="$XXDF ^.*\\$x\$"
+      else
+         XXDF="$XXDF $x"
+      fi
+    done
 }
 
+
 robocopy () {
-# robocopy (srcfname, tgtpath, sshopt)::opt_dry_run,opts_dry_run,XRGX,XRGI,XLFS
+# robocopy (srcfname, tgtpath, sshopt)::opt_dry_run,opts_dry_run,opt_verbose,XRGX,XRGI,XLFS
 # return:
     if [ -d "$1" ]; then
       local t="d"
@@ -148,20 +296,23 @@ robocopy () {
     if [ "${v:0:1}" == "/" ]; then
       if [ "$v" == "/" -a "$t" == "d" ]; then
         if [ "${3:0:3}" == "ssh" ]; then
-          local optrsync="-abvzhe"
-          local optssh="$3"
-          if [ "$v" == "/" ]; then
-            v=/$fn/
+          if [ ${opt_verbose:-0} -gt 0 ]; then
+            local optrsync="-abvzhe"
           else
-            v=$v/$fn/
+            local optrsync="-abzhe"
           fi
-          echo "rsync $opts_dry_run $optrsync \"$optssh\" --del --copy-links $XLFS $ff $2$v"
-          rsync $opts_dry_run $optrsync "$optssh" --del --copy-links $XLFS $ff $2$v
+          local optssh="$3"
+          echo "rsync $opts_dry_run $optrsync \"$optssh\" $opts_upd --del --copy-links $XLFS $ff $2$v"
+          rsync $opts_dry_run $optrsync "$optssh" $opts_upd --del --copy-links $XLFS $ff $2$v
         else
-          local optrsync="-ab"
+          if [ ${opt_verbose:-0} -gt 0 ]; then
+            local optrsync="-abv"
+          else
+            local optrsync="-ab"
+          fi
           local optssh=""
-          echo "rsync $opts_dry_run $optrsync --del --copy-links $XLFS $ff $2$v"
-          rsync $opts_dry_run $optrsync --del --copy-links $XLFS $ff $2$v
+          echo "rsync $opts_dry_run $optrsync $opts_upd --del --copy-links $XLFS $ff $2$v"
+          rsync $opts_dry_run $optrsync $opts_upd --del --copy-links $XLFS $ff $2$v
         fi
       else
         if [ "${3:0:3}" == "ssh" ]; then
@@ -172,8 +323,11 @@ robocopy () {
           if [ ! -d "$2" ]; then
             local v=
           fi
-          echo "$opt_dry_run||cp -L $ff $2$v"
-          (($opt_dry_run))||cp -L $ff $2$v
+          diff -q $ff $2$v &>/dev/null
+          if [ $? -ne 0 ]; then
+            echo "$opt_dry_run||cp -L $ff $2$v"
+            (($opt_dry_run))||cp -L $ff $2$v
+          fi
         fi
       fi
     fi
@@ -182,13 +336,13 @@ robocopy () {
 clean_dirs () {
 # clean_dirs (directory)::
 # return:
-    if [ $opt_dry_run -gt 0 ]; then
-      for x in $XXXX;do
-        find $1 -nowarn -type f -name "*$x" -exec echo "1||rm '{}'" \;
-      done
-    else
-      for x in $XXXX;do
-        find $1 -nowarn -type f -name "*$x" -exec rm -f '{}' \;
-      done
-    fi
+    for x in $XXXX;do
+      if [ "$x" != ".conf" ]; then
+        if [ $opt_dry_run -gt 0 ]; then
+          find $1 -nowarn -name "*$x" -exec echo "1||rm '{}'" \;
+        else
+          find $1 -nowarn -name "*$x" -exec rm -f '{}' \;
+        fi
+      fi
+    done
 }
