[FIX] Fix minor bugs of zar

diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -90,7 +90,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.2.13
+__version__=0.2.2.14
 
 
 store_cfg_param_value() {
@@ -109,9 +109,9 @@ store_cfg_param_value() {
 process_local() {
     wlog "=== Simulate YAML test ==="
     if [ -f $TOOLS_PATH/travis_run_tests ]; then
-      if [ "$action" == "lint" ]; then
+      if [[ $action =~ (force-lint|lint) ]]; then
         opts=$(inherits_travis_opts "K" "T")
-      elif [ "$action" == "test" ]; then
+      elif [[ $action =~ (force-test|test) ]]; then
         opts=$(inherits_travis_opts "T" "T")
       else
         opts=$(inherits_travis_opts "KT" "T")
@@ -119,10 +119,10 @@ process_local() {
       run_traced "TOOLS_PATH=$TOOLS_PATH $TOOLS_PATH/travis_run_tests $opts"
       sts=$?
     elif [ $opt_r -gt 0 ]; then
-      if [ "$action" == "test" ]; then
+      if [[ $action =~ (force-test|test) ]]; then
         please_run_tests "-T"
         sts=$?
-      elif [ "$action" == "lint" ]; then
+      elif [[ $action =~ (force-lint|lint) ]]; then
         please_run_tests "-K"
         sts=$?
       else
@@ -132,7 +132,7 @@ process_local() {
     else
       sts=127
     fi
-    if [ $sts -eq $STS_SUCCESS -a "$action" != "lint" -a "$action" != "test" ]; then
+    if [ $sts -eq $STS_SUCCESS ] && [[ $action =~ (force-lint|lint|force-test|test) ]]; then
       opts=$(inherits_travis_opts "" "A")
       run_traced "$TOOLS_PATH/travis_after_tests_success $opts"
       if [ $? -ne 0 ]; then sts=$?; fi
@@ -207,23 +207,23 @@ process_yaml_do() {
       local line="$1"
     fi
     if [[ "$line" =~ LINT_CHECK=... ]]; then
-      if [ "$action" == "lint" ]; then
+      if [ "$action" == "force-lint" ]; then
         line=$(echo "$line"|sed -e s/LINT_CHECK=[\"']0[\"']/LINT_CHECK=\"1\"/g)
-      elif [ "$action" == "test" ]; then
+      elif [ "$action" == "force-test" ]; then
         line=$(echo "$line"|sed -e s/LINT_CHECK=[\"']1[\"']/LINT_CHECK=\"0\"/g)
       fi
     fi
     if [[ "$line" =~ BASH_CHECK=... ]]; then
-      if [ "$action" == "lint" ]; then
+      if [ "$action" == "force-lint" ]; then
         line=$(echo "$line"|sed -e s/BASH_CHECK=[\"']0[\"']/BASH_CHECK=\"1\"/g)
-      elif [ "$action" == "test" ]; then
+      elif [ "$action" == "force-test" ]; then
         line=$(echo "$line"|sed -e s/BASH_CHECK=[\"']1[\"']/BASH_CHECK=\"0\"/g)
       fi
     fi
     if [[ "$line" =~ TESTS=... ]]; then
-      if [ "$action" == "lint" ]; then
+      if [ "$action" == "force-lint" ]; then
         line=$(echo "$line"|sed -e s/TESTS=[\"']1[\"']/TESTS=\"0\"/g)
-      elif [ "$action" == "test" ]; then
+      elif [ "$action" == "force-test" ]; then
         line=$(echo "$line"|sed -e s/TESTS=[\"']0[\"']/TESTS=\"1\"/g)
       fi
     fi
@@ -882,7 +882,7 @@ process_yaml() {
           done
           CURPYVER=$(echo $TRAVIS_PYTHON_VERSION|grep -Eo [0-9]|head -n1)
           [ "$CURPYVER" != "3" ] && PYTHON=python || PYTHON=python3
-          eval $PYTHON --version
+          # eval $PYTHON --version
           if [[ ! $TRAVIS_DEBUG_MODE =~ ^[01] ]]; then
             if [ $opt_py3 -ne 0 ]; then
               echo -e "import sys\nprint('sys.path=%s' % sys.path)\n"|python3
@@ -903,8 +903,15 @@ process_yaml() {
             fi
             if [[ "$lne1" =~ ODOO_REPO=.[A-Za-z]+ ]]; then
               if [[ ! "$lne1" =~ ODOO_REPO=.$YML_repo. ]]; then
+                wlog "\e[${PS_HDR3_COLOR}mMatrix skipped due invalid repo\e[${PS_TXT_COLOR}m"
                 continue
               fi
+            elif [[ "$action" == "lint" && ! "$lne1" =~ LINT=.1. ]]; then
+              wlog "\e[${PS_HDR3_COLOR}mMatrix skipped because does not match the lint action\e[${PS_TXT_COLOR}m"
+              continue
+            elif [[ "$action" == "test" && ! "$lne1" =~ TEST=.1. ]]; then
+              wlog "\e[${PS_HDR3_COLOR}mMatrix skipped because does not match the test action\e[${PS_TXT_COLOR}m"
+              continue
             fi
             wlog "\e[${PS_HDR1_COLOR}m===== [Build job $lne1] =====\e[${PS_TXT_COLOR}m"
             create_virtual_env
@@ -1024,15 +1031,15 @@ if [ "$opt_version" ]; then
   exit $STS_SUCCESS
 fi
 if [ $opt_help -gt 0 ]; then
-  print_help "Travis-ci emulator for local developer environment\nAction may be: lint, test, emulate (default), setup, chkconfig or parseyaml"\
+  print_help "Travis-ci emulator for local developer environment\nAction may be: [force-]lint, [force-]test, emulate (default), new_vm, chkconfig or parseyaml"\
   "(C) 2015-2019 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit $STS_SUCCESS
 fi
 
 export PYTHONWARNINGS="ignore"
 [ -z "$action" ] && action=emulate
-ACTIONS="lint test emulate setup chkconfig parseyaml"
-VIRTACTS="lint test emulate"
+ACTIONS="force-lint lint force-test test emulate new_vm chkconfig parseyaml"
+VIRTACTS="force-lint lint force-test test emulate"
 if [[ " $ACTIONS " =~ [[:space:]]$action[[:space:]] ]]; then
   if [[ " $VIRTACTS " =~ [[:space:]]$action[[:space:]] ]]; then
     :
@@ -1051,7 +1058,50 @@ link_cfg $DIST_CONF $TCONF
 if [ $opt_verbose -gt 1 ]; then set -x; fi
 init_travis
 
-if [ "$action" == "parseyaml" ]; then
+if [ "$action" == "new_vm" ]; then
+   if [ -z "$sub" ]; then
+     echo "Missed vm name!"
+     echo "use: $0 new_vm VMNAME"
+     exit 1
+   fi
+   # set -x   #debug
+   TRAVIS_CWD=$PWD
+   TRAVIS_ENVOPTS=$(get_cfg_value "" "virtualenv_opts")
+   [[ "${opt_syspkg:-true}" == "true" ]] && export SYSTEM_SITE_PACKAGES=true
+   [[ "${opt_syspkg:-true}" == "true" ]] && TRAVIS_ENVOPTS="$TRAVIS_ENVOPTS --system-site-packages"
+   VENV_DIR=$(readlink -f ~/VME/$sub)
+   VENV_TMP=${VENV_DIR}~
+   [ -d $VENV_TMP ] && run_traced "rm -fR $VENV_TMP"
+   if [ $opt_py3 -eq 0 ]; then
+     TRAVIS_PYTHON_VERSION="2.7"
+     PIP=pip
+   else
+     TRAVIS_PYTHON_VERSION="3.5"
+     PIP=pip3
+   fi
+   TRAVIS_ENVOPTS="$TRAVIS_ENVOPTS -p /usr/bin/python$TRAVIS_PYTHON_VERSION"
+   echo "\$ virtualenv -q $TRAVIS_ENVOPTS $VENV_TMP"
+   virtualenv -q $TRAVIS_ENVOPTS $VENV_TMP
+   sts=$?
+   [ $sts -eq 0 ] || exit $sts 
+   LISTREQ=$(which list_requirements.py 2>/dev/null)
+   run_traced "cd $VENV_TMP"
+   echo "\$ source bin/activate"
+   source bin/activate
+   req=$($LISTREQ -PBRT -t python -s" ")
+   req="${req/python=/}"
+   echo $req|tr -d "'"|tr " " "\n" > $HOME/requirements.txt
+   run_traced "$PIP install -r $HOME/requirements.txt --force-reinstall"
+   # run_traced "$PIP install -r $HOME/requirements.txt"
+   echo "\$ deactivate"
+   deactivate
+   cd $TRAVIS_CWD
+   find $VENV_TMP -name "*.pyc" -delete
+   [ -d $VENV_DIR ] && run_traced "rm -fR $VENV_DIR"
+   run_traced "venv_mgr mv $VENV_TMP $VENV_DIR"
+   # set +x   #debug
+   exit $sts
+elif [ "$action" == "parseyaml" ]; then
   # init_travis
   prepare_env_travis "$action"
   check_4_travis
@@ -1103,36 +1153,14 @@ if [ "$action" == "parseyaml" ]; then
   sts=$STS_SUCCESS
   exit $sts
 fi
-if [ "$action" == "setup" ]; then
-  opt_r=0
-  DEF_DEVPATH=$(readlink -f ~/dev)
-  if [ ! -d $DEF_DEVPATH ]; then
-    run_traced mkdir -p $DEF_DEVPATH
-  fi
-  # if [ ! -d $DEF_DEVPATH/_travis ]; then
-  #   run_traced  mkdir -p $DEF_DEVPATH/_travis
-  # fi
-  # if [ ! -d $DEF_DEVPATH/_travis/cfg ]; then
-  #   run_traced mkdir -p $DEF_DEVPATH/_travis/cfg
-  # fi
-  # if [ "$TDIR" != "$DEF_DEVPATH" ]; then
-  #   run_traced cp $TDIR/$THIS $DEF_DEVPATH/$THIS
-  #   for f in travis_run_tests travis_after_tests_success; do
-  #     run_traced cp $TDIR/_travis/$f $DEF_DEVPATH/_travis/$f
-  #   done
-  # fi
-  exit $STS_SUCCESS
+
+if [[ $PWD == $HOME ]]; then
+  echo "Cannot execute travis-ci from home directory!"
+  exit 1
 fi
 
 sts=$STS_SUCCESS
-# init_travis
-if $(echo $PWD|grep -q "/VENV"); then
-  echo "Curent directory is a virtualized environment."
-  echo "Test cannot be executed!"
-  exit 1
-fi
 prepare_env_travis "$action"
-# check_4_travis
 echo -e "\e[0;30;107m$(printf '%-80.80s' ' ')\e[0m"
 if [ $sts -eq $STS_SUCCESS ]; then
   if [ $opt_r -gt 0 ]; then
diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -1,7 +1,7 @@
 #
 # Common file for travis emulator scripts
 # 
-#__version__=0.2.2.13
+#__version__=0.2.2.14
 
 
 MAKEF=/opt/odoo/dev/Makefile
@@ -377,13 +377,110 @@ drop_test_db() {
     fi
 }
 
+venv_mgr_rename() {
+    local d f mime VENV VIRTUAL_ENV V
+    [ -n "$1" ] && VENV=$(readlink -f $1)
+    [ -n "$2" ] && VIRTUAL_ENV=$(readlink -f $2)
+    if [[ -z "$VENV" || -z "$VIRTUAL_ENV" ]]; then
+      echo "Missed parameters!"
+      echo "use: venv_mgr cp|mv|merge VENV NEW_VENV"
+      exit 1
+    fi
+    if [[ "$VENV" == "$VIRTUAL_ENV" ]]; then
+      echo "Source and destination directories are the same!"
+      echo "use: venv_mgr cp|mv VENV NEW_VENV"
+      exit 1
+    fi
+    if [[ ! -d "$VENV" ]]; then
+      echo "Source directory $VENV does not exist!" 
+      exit 1
+    fi
+    if [[ "$3" == "merge" ]]; then
+      if [[ ! -d "$VIRTUAL_ENV" ]]; then
+        echo "Destination directory $VIRTUAL_ENV does not exist!" 
+        exit 1
+      fi
+      for d in bin include lib lib64 .local; do
+        if [ -d "$VENV/$d" ]; then
+          rsync -a $VENV/$d/ $VIRTUAL_ENV/$d/
+        fi
+      done
+      V=$VIRTUAL_ENV
+    else
+      V=$VENV
+    fi
+    # for f in $(find $V/bin $V/lib -type f); do
+    for f in $V/bin/*; do
+      mime=$(file --mime-type -b $f)
+      if [ "$mime" == "text/x-python" -o "${f: -3}" == ".py" ]; then
+        # echo "sed -i -e \"s|^#\!.*/bin/python|#\!$VIRTUAL_ENV/bin/python|\" $f"
+        sed -i -e "s|^#\!.*/bin/python|#\!$VIRTUAL_ENV/bin/python|" $f
+      fi
+    done
+    pushd $V >/dev/null
+    if [ -L ./lib64 ]; then
+      rm -f ./lib64
+      ln -s ./lib ./lib64
+    fi
+    sed -i -e 's:VIRTUAL_ENV=.*:VIRTUAL_ENV="'$VIRTUAL_ENV'":g' $PWD/bin/activate
+    if $(grep -q "^export HOME=" $PWD/bin/activate); then
+      sed -i -e 's|^export HOME=.*|export HOME="\$VIRTUAL_ENV"|g' $PWD/bin/activate
+    else
+      sed -ri "/deactivate *\(\) *\{/a\    export HOME=\$(grep \$USER /etc/passwd|awk -F: '{print \$6}')" $PWD/bin/activate
+      echo "export HOME=\"\$VIRTUAL_ENV\"">>$PWD/bin/activate
+    fi
+    if [[ "$SYSTEM_SITE_PACKAGES" == "true" ]]; then
+      if [[ -d $PWD/.local/lib/python$TRAVIS_PYTHON_VERSION/site-packages ]]; then
+        echo -e "import site\nsite.addsitedir('$VIRTUAL_ENV/.local/lib/python$TRAVIS_PYTHON_VERSION/site-packages')\nsite.addsitedir('/usr/lib/python$TRAVIS_PYTHON_VERSION/site-packages')\nsite.addsitedir('/usr/lib64/python$TRAVIS_PYTHON_VERSION/site-packages')\n">$PWD/lib/python$TRAVIS_PYTHON_VERSION/site-packages/sitecustomize.py
+      else
+        echo -e "import site\nsite.addsitedir('/usr/lib/python$TRAVIS_PYTHON_VERSION/site-packages')\nsite.addsitedir('/usr/lib64/python$TRAVIS_PYTHON_VERSION/site-packages')\n">$PWD/lib/python$TRAVIS_PYTHON_VERSION/site-packages/sitecustomize.py
+      fi
+    elif [[ -d $PWD/.local/lib/python$TRAVIS_PYTHON_VERSION/site-packages ]]; then
+      echo -e "import site\nsite.addsitedir('$VIRTUAL_ENV/.local/lib/python$TRAVIS_PYTHON_VERSION/site-packages')\n">$PWD/lib/python$TRAVIS_PYTHON_VERSION/site-packages/sitecustomize.py
+    fi
+    popd >/dev/null
+}
+
+venv_mgr_test() {
+    local f x
+    cd $1
+    . bin/activate
+    for f in python pip coveralls codecov flake8 pylint; do
+      x=$(readlink -e $(which $f))
+      [[ ! $x =~ ^$1 ]] && echo "Corrupted VME ($f)"
+      eval $f --version
+    done
+    deactivate
+}
+
+venv_mgr() {
+# venv_mgr {cp|mv|merge} VENV NEW_VENV
+    local cmd=$1
+    if [[ "$cmd" == "cp" ]]; then
+      venv_mgr_rename $2 $3
+      cp $2 $3
+      venv_mgr_test $3
+    elif [[ "$cmd" == "mv" ]]; then
+      venv_mgr_rename $2 $3
+      mv $2 $3
+      venv_mgr_test $3
+    elif [[ "$cmd" == "merge" ]]; then
+      venv_mgr_rename $2 $3 merge
+      venv_mgr_test $3
+    else
+      echo "Invalid cmd $1!"
+      echo "use: venv_mgr cp|mv|merge VENV NEW_VENV"
+      exit 1
+    fi
+}
+
 custom_env() {
 # custom_env(VENV pyver)
     cd $1
     sed -i -e 's:VIRTUAL_ENV=.*:VIRTUAL_ENV="\$(readlink -f \$(dirname \$(readlink -f \$BASH_SOURCE))/..)":g' $PWD/bin/activate
     if $(grep -q "^export HOME=" $PWD/bin/activate); then
       sed -i -e 's|^export HOME=.*|export HOME="\$VIRTUAL_ENV"|g' $PWD/bin/activate
-      sed -i -e "s|^#.*/bin/python|#\!$PWD/bin/python|g" $PWD/bin/python-config
+      # sed -i -e "s|^#.*/bin/python|#\!$PWD/bin/python|g" $PWD/bin/python-config
     else
       sed -ri "/deactivate *\(\) *\{/a\    export HOME=\$(grep \$USER /etc/passwd|awk -F: '{print \$6}')" $PWD/bin/activate
       [ "$SYSTEM_SITE_PACKAGES" != "true" -a -n "$2" ] && echo "[ -f /usr/bin/pip$2 -a ! -f \$VIRTUAL_ENV/bin/pip ] && ln -s /usr/bin/pip$2 \$VIRTUAL_ENV/bin/pip">>$PWD/bin/activate
@@ -391,12 +488,9 @@ custom_env() {
       echo "    [ -x \$f ] && sed -i -e \"s|^#\!.*/bin/python|#\!\$VIRTUAL_ENV/bin/python|\" \$f">>$PWD/bin/activate
       echo "done">>$PWD/bin/activate
       echo "export HOME=\"\$VIRTUAL_ENV\"">>$PWD/bin/activate
-      [[ "$SYSTEM_SITE_PACKAGES" == "true" ]] && echo "[ -d $HOME/tools ] && export PYTHONPATH=$HOME/tools">>$PWD/bin/activate
-      sed -i -e "s:^#\!*/bin/python:#!$PWD/bin/python:g" $PWD/bin/python-config
+      # [[ "$SYSTEM_SITE_PACKAGES" == "true" ]] && echo "[ -d $HOME/tools ] && export PYTHONPATH=$HOME/tools">>$PWD/bin/activate
+      # sed -i -e "s:^#\!*/bin/python:#!$PWD/bin/python:g" $PWD/bin/python-config
     fi
-    # if $(grep -qv \"-f...VIRTUAL_ENV/bin/pip.*sed\" $PWD/bin/activate); then
-    #   echo "[ -f $VIRTUAL_ENV/bin/pip ] && sed -i -e \"s|#\!.*python2.7|#\!\$VIRTUAL_ENV/bin/python2.7|\" \$VIRTUAL_ENV/bin/pip">>$PWD/bin/activate
-    # fi
     sed -i -e 's|PATH="\$VIRTUAL_ENV/bin:\$PATH"|PATH="\$VIRTUAL_ENV/.local/bin:\$VIRTUAL_ENV/bin:\$PATH"|g' $PWD/bin/activate
     if [[ "$SYSTEM_SITE_PACKAGES" == "true" ]]; then
       if [[ -d $PWD/.local/lib/python$2/site-packages ]]; then
@@ -406,58 +500,6 @@ custom_env() {
       fi
     elif [[ -d $PWD/.local/lib/python$2/site-packages ]]; then
       echo -e "import site\nsite.addsitedir('$PWD/.local/lib/python$2/site-packages')\n">$PWD/lib/python$2/site-packages/sitecustomize.py
-    fi
-}
-
-emulate_git_clone_OCB() {
-# emulate_git_clone_OCB(src tgt)
-    local d f
-    local SAVE_COLOR=$PS_RUN_COLOR
-    export PS_RUN_COLOR="1;90;46"
-    run_traced "mkdir -p $2/"
-    valid="addons babel.cfg bin CONTRIBUTING.md COPYRIGHT debian doc gen_translations.sh gunicorn.conf.py LICENSE logging.json Makefile MANIFEST.in npybabel.py odoo odoo.py odoo-bin openerp openerp-cron-worker openerp-gevent openerp-server openerp-web openerp-web.cfg openerp-wsgi.py README.md requirements.txt server setup setup.cfg setup.py win32"
-    for d in $1/*; do
-      f=$(basename $d)
-      if [[ " $valid " =~ " $f " ]]; then
-        if [ -d $1/$f ]; then
-          run_traced "cp -R $1/$f/ $2/"
-        else
-          run_traced "cp $1/$f $2"
-        fi
-      fi
-    done
-    export PS_RUN_COLOR=$SAVE_COLOR
-}
-
-git_clone() {
-# emulate git clone
-    local d x
-    while [[ -n "$1" && "${1:0:1}" == "-" ]]; do
-      shift
-    done
-    if [[ "$1" == "https://github.com/zeroincombenze/tools.git" ]]; then
-      if [[ -n "$2" ]]; then
-        d=$(readlink -m $2/..)
-      else
-        d="./"
-      fi
-      run_traced "cp -R $TRAVIS_SAVED_HOME/tools $d"
-      if [[ -n "$YML_lisa" ]]; then
-        x=$(dirname $YML_lisa)
-        run_traced "rsync -a $x/ $HOME/tools/lisa/"
-      fi
-      if [[ -n "$YML_mgrodoo" ]]; then
-        x=$(dirname $YML_mgrodoo)
-        run_traced "rsync -a $x/ $HOME/tools/clodoo/"
-      fi
-      if [ $opt_dbgmnt -ne 0 ]; then
-        run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/ $HOME/tools/maintainer-quality-tools/travis/"
-        run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/_travis/ $HOME/tools/maintainer-quality-tools/_travis/"
-        x=${TRAVIS_REPO_SLUG#*/}
-        if [ -n "$x" -a -d $TRAVIS_SAVED_HOME/dev/pypi/$x/$x/ ]; then 
-          run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$x/$x/ $HOME/tools/$x/"
-        fi
-      fi
     fi
 }
 
@@ -504,14 +546,15 @@ create_virtual_env() {
       echo -en "\e[${PS_RUN_COLOR}m"
       if [ ${opt_cache:-0} -ne 0 -a -n "${VER}" -a -d "$TRAVIS_SAVED_HOME/VME/VME${VER}" ]; then
         echo "# .. loading stored packages from VME${VER} ..."
-        for d in bin include lib lib64 .local; do
-          if [ -d "$TRAVIS_SAVED_HOME/VME/VME${VER}/$d" ]; then
-            [ -d "$TRAVIS_HOME/$d" ] && rm -fR $TRAVIS_HOME/$d
-            run_traced "cp -R $TRAVIS_SAVED_HOME/VME/VME${VER}/$d $TRAVIS_HOME/"
-          fi
-        done
+        run_traced "venv_mgr merge $TRAVIS_SAVED_HOME/VME/VME${VER} $TRAVIS_HOME"
+        # for d in bin include lib lib64 .local; do
+        #   if [ -d "$TRAVIS_SAVED_HOME/VME/VME${VER}/$d" ]; then
+        #     [ -d "$TRAVIS_HOME/$d" ] && rm -fR $TRAVIS_HOME/$d
+        #     run_traced "cp -R $TRAVIS_SAVED_HOME/VME/VME${VER}/$d $TRAVIS_HOME/"
+        #   fi
+        # done
       fi
-      custom_env "$TRAVIS_HOME" "$TRAVIS_PYTHON_VERSION"
+      # custom_env "$TRAVIS_HOME" "$TRAVIS_PYTHON_VERSION"
       source bin/activate
       # FIX
       # pip install flake8
@@ -580,11 +623,62 @@ wash_virtual_env() {
     hash -r
 }
 
+emulate_git_clone_OCB() {
+# emulate_git_clone_OCB(src tgt)
+    local d f
+    local SAVE_COLOR=$PS_RUN_COLOR
+    export PS_RUN_COLOR="1;90;46"
+    run_traced "mkdir -p $2/"
+    valid="addons babel.cfg bin CONTRIBUTING.md COPYRIGHT debian doc gen_translations.sh gunicorn.conf.py LICENSE logging.json Makefile MANIFEST.in npybabel.py odoo odoo.py odoo-bin openerp openerp-cron-worker openerp-gevent openerp-server openerp-web openerp-web.cfg openerp-wsgi.py README.md requirements.txt server setup setup.cfg setup.py win32"
+    for d in $1/*; do
+      f=$(basename $d)
+      if [[ " $valid " =~ " $f " ]]; then
+        if [ -d $1/$f ]; then
+          run_traced "cp -R $1/$f/ $2/"
+        else
+          run_traced "cp $1/$f $2"
+        fi
+      fi
+    done
+    export PS_RUN_COLOR=$SAVE_COLOR
+}
+
+git_clone() {
+# emulate git clone
+    local d x
+    while [[ -n "$1" && "${1:0:1}" == "-" ]]; do
+      shift
+    done
+    if [[ "$1" == "https://github.com/zeroincombenze/tools.git" ]]; then
+      if [[ -n "$2" ]]; then
+        d=$(readlink -m $2/..)
+      else
+        d="./"
+      fi
+      run_traced "cp -R $TRAVIS_SAVED_HOME/tools $d"
+      if [[ -n "$YML_lisa" ]]; then
+        x=$(dirname $YML_lisa)
+        run_traced "rsync -a $x/ $HOME/tools/lisa/"
+      fi
+      if [[ -n "$YML_mgrodoo" ]]; then
+        x=$(dirname $YML_mgrodoo)
+        run_traced "rsync -a $x/ $HOME/tools/clodoo/"
+      fi
+      if [ $opt_dbgmnt -ne 0 ]; then
+        run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/ $HOME/tools/maintainer-quality-tools/travis/"
+        run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/_travis/ $HOME/tools/maintainer-quality-tools/_travis/"
+        x=${TRAVIS_REPO_SLUG#*/}
+        if [ -n "$x" -a -d $TRAVIS_SAVED_HOME/dev/pypi/$x/$x/ ]; then 
+          run_traced "rsync -a $TRAVIS_SAVED_HOME/dev/pypi/$x/$x/ $HOME/tools/$x/"
+        fi
+      fi
+    fi
+}
+
 prepare_env_travis() {
     local action="$1"
     local v x
-    # if [[ $action =~ (lint|test|emulate|test|coverage) ]]; then
-    if [[ $action =~ (lint|test|emulate|test) ]]; then
+    if [[ $action =~ (force-lint|lint|force-test|test|emulate|test) ]]; then
       if [ -n "$TOOLS_PATH" ]; then
         if [ ${opt_r:-0} -gt 0 ]; then
           if [[ ! :$PATH: =~ :$TOOLS_PATH: ]]; then
@@ -601,9 +695,9 @@ prepare_env_travis() {
     export NPM_CONFIG_PREFIX=$NPM_CONFIG_PREFIX
     export BRANCH
     [ -z "$VERSION" ] && export VERSION=$BRANCH
-    if [ "$action" == "lint" ]; then
+    if [ "$action" == "force-lint" ]; then
       export LINT_CHECK=1
-    elif [ "$action" == "test" ]; then
+    elif [ "$action" == "force-test" ]; then
       export LINT_CHECK=0
     fi
     if [ "$PRJNAME" == "Odoo" ]; then
