[IMP] arcangelo 2.1.1, stable version

diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -8,7 +8,7 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2025 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
-# Based on template 2.1.0
+# Based on template 2.1.1
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
 READLINK=$(which readlink 2>/dev/null)
 export READLINK
@@ -31,10 +31,8 @@ x=$ME; while [[ $x != $HOME && $x != "/" && ! -d $x/lib && ! -d $x/bin && ! -d $
 [[ -d $x/lib ]] && PYPATH="$PYPATH $x/lib"
 [[ -d $HOME_DEVEL/venv/bin ]] && PYPATH="$PYPATH $HOME_DEVEL/venv/bin"
 [[ -d $HOME_DEVEL/../tools ]] && PYPATH="$PYPATH $(readlink -f $HOME_DEVEL/../tools)"
-# [[ -x $TDIR/../bin/python3 ]] && PYTHON=$(readlink -f $TDIR/../bin/python3) || [[ -x $TDIR/python3 ]] && PYTHON="$TDIR/python3" || PYTHON=$(which python3 2>/dev/null) || PYTHON="python"
-# [[ -z $PYPATH ]] && PYPATH=$(echo -e "import os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nC=a('"$TDIR"')\nD='"$HOME_DEVEL"'\nif not p(D) and '/devel/' in C:\n D=C\n while b(D)!='devel':  D=d(D)\nN='venv_tools'\nU='setup.py'\nO='tools'\nH=o.expanduser('~')\nT=j(d(D),O)\nR=j(d(D),'pypi') if b(D)==N else j(D,'pypi')\nW=D if b(D)==N else j(D,'venv')\nS='site-packages'\nX='scripts'\ndef pt(P):\n P=a(P)\n if b(P) in (X,'tests','travis','_travis'):\n  P=d(P)\n if b(P)==b(d(P)) and f(j(P,'..',U)):\n  P=d(d(P))\n elif b(d(C))==O and f(j(P,U)):\n  P=d(P)\n return P\ndef ik(P):\n return P.startswith((H,D,K,W)) and p(P) and p(j(P,X)) and f(j(P,'__init__.py')) and f(j(P,'__main__.py'))\ndef ak(L,P):\n if P not in L:\n  L.append(P)\nL=[C]\nK=pt(C)\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n for P in [C]+sys.path+os.environ['PATH'].split(':')+[W,R,T]:\n  P=pt(P)\n  if B==b(P) and ik(P):\n   ak(L,P)\n   break\n  elif ik(j(P,B,B)):\n   ak(L,j(P,B,B))\n   break\n  elif ik(j(P,B)):\n   ak(L,j(P,B))\n   break\n  elif ik(j(P,S,B)):\n   ak(L,j(P,S,B))\n   break\nak(L,os.getcwd())\nprint(' '.join(L))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
-for d in $PYPATH /etc; do
+for d in $TDIR $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$(readlink -e $d)
@@ -64,7 +62,7 @@ CYAN="\e[1;36m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
-__version__=2.0.11
+__version__=2.0.12
 
 
 store_cfg_param_value() {
@@ -85,8 +83,8 @@ debug_shell() {
     local sts h v
     sts=0
     if [[ -n $1 && -n $2 && $2 =~ $1 ]]; then
-      [[ -z "$3" ]] && echo "PATH=$PATH"
-      echo "PS1='\[\033[=25h\](ctrl+d to continue)> '">/tmp/$$.sh
+      [[ -z $3 ]] && echo "PATH=$PATH"
+      echo "PS1='\[\033[31m\]DEBUG\[\033[=25h\033[0m\]> '">/tmp/$$.sh
       echo "alias EXIT='exit 1'">>/tmp/$$.sh
       h=" * HELP       # This help\n"
       h="${h} * EXIT       # Exit from debug session and ${RED}quit testing process${CLR}\n"
@@ -106,6 +104,10 @@ debug_shell() {
           TRAVIS_HOME TRAVIS_PYTHON_VERSION TRAVIS_SAVED_HOME TRAVIS_SAVED_PKGPATH; do
         [[ -n ${!v} ]] && echo "export $v='${!v}'">>/tmp/$$.sh
       done
+      [[ $2 =~ ^::[a-zA-Z0-9_]+$ ]] && v="YML_${2:2}" && [[ -n ${!v} ]] && echo "export $v='${!v}'">>/tmp/$$.sh
+      h="${h} ctrl+d       # Continue debug session\n"
+      # echo "export process_yaml_quote_xtl">>/tmp/$$.sh
+      # echo "alias LS_TODO='for ln in $YML_before_install; do echo "$(process_yaml_quote_xtl \"$ln\")"; done'>>/tmp/$$.sH
       echo -e "$h"
       eval $SHELL --noprofile --rcfile /tmp/$$.sh -s
       sts=$?
@@ -529,14 +531,12 @@ process_yaml_before_install() {
   if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
     wlog "\e[${PS_HDR3_COLOR}m------ [[before_install] in .travis.yml] ------\e[0m"
   fi
-  if [ $sts -eq $STS_SUCCESS ]; then
-    for lne in $YML_before_install; do
-      [[ $TRAVIS_DEBUG_MODE -ge 3 ]] && echo "#> $(process_yaml_quote_xtl $lne)"
-      process_yaml_run_cmd "$lne"
-      s=$?; [[ ${s-1} -ne 0 && $sts -eq 0 ]] && sts=$s
-      [[ $s -ne 0 ]] && echo -e "\e[${PS_HDR3_COLOR}mInternal error! Statement <<$(process_yaml_quote_xtl \"$lne\")>>failed failed!\e[${PS_TXT_COLOR}m"
-    done
-  fi
+  for lne in $YML_before_install; do
+    [[ $TRAVIS_DEBUG_MODE -ge 3 ]] && echo "#> $(process_yaml_quote_xtl $lne)"
+    process_yaml_run_cmd "$lne"
+    s=$?; [[ ${s-1} -ne 0 && $sts -eq 0 ]] && sts=$s
+    [[ $s -ne 0 ]] && echo -e "\e[${PS_HDR3_COLOR}mInternal error! Statement <<$(process_yaml_quote_xtl \"$lne\")>>failed failed!\e[${PS_TXT_COLOR}m"
+  done
   [[ $sts -ne 0 ]] && exit $sts
   for lne in $YML_env; do
     line="export $(process_yaml_quote_xtl $lne)"
