[IMP] Odoo server watchdog

diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -17,14 +17,19 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
+if [ -e $TDIR/z0librc ]; then
 . $TDIR/z0librc
-elif [ -f ./z0librc ]; then
+elif [ -e ./z0librc ]; then
 . ./z0librc
-elif [ -f ~/z0librc ]; then
+elif [ -e ../z0librc ]; then
+. ../z0librc
+elif [ -e ~/z0librc ]; then
 . ~/z0librc
-else
+elif [ -f /etc/z0librc ]; then
 . /etc/z0librc
+else
+  echo "Library file z0librc not found!"
+  exit $STS_FAILED
 fi
 if [ -f $TDIR/travisrc ]; then
 . $TDIR/travisrc
@@ -39,7 +44,7 @@ else
   exit $STS_FAILED
 fi
 
-__version__=0.1.59.1
+__version__=0.1.59.2
 
 
 run_cmd () {
