[IMP] zar 2.0.8, stable version

diff --git a/zar/zar/zar_upd b/zar/zar/zar_upd
--- a/zar/zar/zar_upd
+++ b/zar/zar/zar_upd
@@ -7,7 +7,7 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2025 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
-# Based on template 2.1.0
+# Based on template 2.1.1
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
 READLINK=$(which readlink 2>/dev/null)
 export READLINK
@@ -30,10 +30,8 @@ x=$ME; while [[ $x != $HOME && $x != "/" && ! -d $x/lib && ! -d $x/bin && ! -d $
 [[ -d $x/lib ]] && PYPATH="$PYPATH $x/lib"
 [[ -d $HOME_DEVEL/venv/bin ]] && PYPATH="$PYPATH $HOME_DEVEL/venv/bin"
 [[ -d $HOME_DEVEL/../tools ]] && PYPATH="$PYPATH $(readlink -f $HOME_DEVEL/../tools)"
-# [[ -x $TDIR/../bin/python3 ]] && PYTHON=$(readlink -f $TDIR/../bin/python3) || [[ -x $TDIR/python3 ]] && PYTHON="$TDIR/python3" || PYTHON=$(which python3 2>/dev/null) || PYTHON="python"
-# [[ -z $PYPATH ]] && PYPATH=$(echo -e "import os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nC=a('"$TDIR"')\nD='"$HOME_DEVEL"'\nif not p(D) and '/devel/' in C:\n D=C\n while b(D)!='devel':  D=d(D)\nN='venv_tools'\nU='setup.py'\nO='tools'\nH=o.expanduser('~')\nT=j(d(D),O)\nR=j(d(D),'pypi') if b(D)==N else j(D,'pypi')\nW=D if b(D)==N else j(D,'venv')\nS='site-packages'\nX='scripts'\ndef pt(P):\n P=a(P)\n if b(P) in (X,'tests','travis','_travis'):\n  P=d(P)\n if b(P)==b(d(P)) and f(j(P,'..',U)):\n  P=d(d(P))\n elif b(d(C))==O and f(j(P,U)):\n  P=d(P)\n return P\ndef ik(P):\n return P.startswith((H,D,K,W)) and p(P) and p(j(P,X)) and f(j(P,'__init__.py')) and f(j(P,'__main__.py'))\ndef ak(L,P):\n if P not in L:\n  L.append(P)\nL=[C]\nK=pt(C)\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n for P in [C]+sys.path+os.environ['PATH'].split(':')+[W,R,T]:\n  P=pt(P)\n  if B==b(P) and ik(P):\n   ak(L,P)\n   break\n  elif ik(j(P,B,B)):\n   ak(L,j(P,B,B))\n   break\n  elif ik(j(P,B)):\n   ak(L,j(P,B))\n   break\n  elif ik(j(P,S,B)):\n   ak(L,j(P,S,B))\n   break\nak(L,os.getcwd())\nprint(' '.join(L))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
-for d in $PYPATH /etc; do
+for d in $TDIR $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$(readlink -e $d)
@@ -59,6 +57,7 @@ link_cfg $DIST_CONF $TCONF
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
 get_pypi_param ALL
 RED="\e[1;31m"
+CYAN="\e[1;36m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
@@ -232,8 +231,9 @@ if [ $opt_cron -gt 0 ]; then
 fi
 
 FLIST="zarrc zar_bck zar_cptbl zar_rest zar_purge zar_upd pg_db_active pg_db_reassign_owner bck_filestore.sh check_4_seq.sh"
+RCLIST="z0librc odoorc cronow"
 GZFN=zar.tar.gz
-if [ "$action" == "build" -o "$action" == "build_last" ]; then
+if [[ "$action" == "build" || "$action" == "build_last" ]]; then
   wlog "Build ZAR suite $__version__ by $USER"
   SRCDIR=$TDIR
   [[ ! -f $HOME/tmp ]] && mkdir -p $HOME/tmp
@@ -247,7 +247,7 @@ if [ "$action" == "build" -o "$action" == "build_last" ]; then
       invalid=$f
     fi
   done
-  if  [ -n "$invalid" ]; then
+  if  [[ -n "$invalid" ]]; then
     wlog "File $f not found"
     echo "File $f not found"
     exit 1
@@ -255,7 +255,7 @@ if [ "$action" == "build" -o "$action" == "build_last" ]; then
   if [ -f $GZFN ]; then
     rm -f $GZFN
   fi
-  odoo_home=$(grep odoo /etc/passwd|awk -F: '{print $6}')
+  odoo_home=$(grep odoo /etc/passwd|awk -F: '{print $6}'|head -n1)
   if [ "$action" == "build_last" ]; then
     cp $odoo_home/devel/pypi/z0lib/z0lib/z0librc $HOME/tmp
     cp $odoo_home/devel/pypi/travis_emulator/travis_emulator/cronow $HOME/tmp
@@ -272,13 +272,20 @@ if [ "$action" == "build" -o "$action" == "build_last" ]; then
     fi
     cp $odoo_home/tools/clodoo/odoorc $HOME/tmp
   fi
+  for f in $FLIST $RCLIST; do
+    if [[ ! -f $HOME/tmp/$f ]]; then
+      wlog "File $f not found"
+      echo "File $f not found"
+      exit 1
+    fi
+  done
   CWD=$PWD
   cd $HOME/tmp
   if [ $EUID -eq 0 ]; then
     chown root:root ./*
   fi
-  for f in $FLIST cronow; do
-    if [ "$f" != "zarrc" ]; then
+  for f in $FLIST $RCLIST; do
+    if [[ ! $f =~ ^(odoorc|zarrc|z0librc)$ ]]; then
       v=$($HOME/tmp/$f -V 2>/dev/null)
       echo "$f $v"
       wlog "$f $v"
@@ -287,16 +294,14 @@ if [ "$action" == "build" -o "$action" == "build_last" ]; then
   x="-cf"
   tar $x $GZFN $FLIST
   x=${x/c/r}
-  tar $x $GZFN z0librc
-  tar $x $GZFN odoorc
-  tar $x $GZFN cronow
-  if [  -n "$opt_tar" ]; then
+  for f in $RCLIST; do
+    tar $x $GZFN $f
+  done
+  if [[  -n "$opt_tar" ]]; then
     mv $GZFN $opt_tar
   else
-    for f in $FLIST z0librc odoorc cronow; do
-      if [ -f $HOME/tmp/$f ]; then
-        rm -f $HOME/tmp/$f
-      fi
+    for f in $FLIST $RCLIST; do
+      [[ -f $HOME/tmp/$f ]] && rm -f $HOME/tmp/$f
     done
     echo "See $HOME/tmp/$GZFN file ..."
   fi
@@ -325,31 +330,23 @@ cd /tmp
 if [[ -n "$opt_tar" ]]; then
   tar -xvf $opt_tar
 else
-  if [[ -f $GZFN ]]; then
-    rm -f $GZFN
-  fi
-  wget http://download.zeroincombenze.org/$GZFN
-  if [ ! -f $GZFN ]; then
-    wlog "No file $GZFN downloaded"
-    echo "No file $GZFN downloaded"
-    exit 1
-  fi
-  tar -xvf $GZFN
+  echo "No file tar issued! Please use -f switch"
+  exit 1
 fi
 
-if [ "$0" == "$PGHOME/zar_upd" -a -f ./zar_upd ]; then
+if [[ $0 == "$PGHOME/zar_upd" && -f ./zar_upd ]]; then
   mv zar_upd $PGHOME/updzar
   chown postgres:postgres $PGHOME/updzar
   exec $PGHOME/updzar "$@"
 fi
 TFQN=$(readlink -f $0)
-if [ "$TFQN" == "/tmp/zar_upd" ]; then
+if [[ $TFQN == "/tmp/zar_upd" ]]; then
   mv /tmp/zar_upd $PGHOME/updzar
   exec $PGHOME/updzar "$@"
 fi
-for f in $FLIST cronow; do
-  if [ -f ./$f ]; then
-    if [ "$f" == "pg_db_active" -o "$f" == "cronow" ]; then
+for f in $FLIST $RCLIST; do
+  if [[ -f ./$f ]]; then
+    if [[ $f == "pg_db_active" || $f == "cronow" ]]; then
       USRBIN=/usr/local/bin
       wlog "Installing $f in $USRBIN/"
       mv ./$f $USRBIN/
@@ -359,10 +356,10 @@ for f in $FLIST cronow; do
       echo "$f $v"
       wlog "$f $v"
     else
-      wlog "Installing $f in $PGHOME/"
+      wlog "Moving $f in $PGHOME/"
       mv ./$f $PGHOME/
       chown postgres:postgres $PGHOME/$f
-      if [ "$f" != "zarrc" ]; then
+      if [[ ! $f =~ ^(odoorc|zarrc|z0librc)$ ]]; then
         v=$($PGHOME/$f -V)
         echo "$f $v"
         wlog "$f $v"
@@ -373,16 +370,11 @@ for f in $FLIST cronow; do
     echo "No file $f downloaded"
   fi
 done
-for f in bckdb-v1 purgedb dup4test restdb-v1; do
-  if [ -f $PGHOME/$f ]; then
-    rm -f $PGHOME/$f
-  fi
-done
-if [ ! -d /var/log/zar ]; then
+if [[ ! -d /var/log/zar ]]; then
   mkdir -p /var/log/zar
   chown postgres:postgres /var/log/zar
 fi
-if [ -f $PGHOME/zar_bck -a ! -f $PGHOME/zar.conf ]; then
+if [[ -f $PGHOME/zar_bck && ! -f $PGHOME/zar.conf ]]; then
   create_conf
 fi
 exit 0
