[IMP] New feature for travis emulator

diff --git a/travis_emulator/_travis/travis_run_tests b/travis_emulator/_travis/travis_run_tests
--- a/travis_emulator/_travis/travis_run_tests
+++ b/travis_emulator/_travis/travis_run_tests
@@ -12,6 +12,8 @@
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
 for x in "$TDIR" "$TDIR/.." "." ".." "$HOME/tools/z0lib" "/etc"; do
+  echo "[ -e $x/z0librc ]"  #debug
+  readlink -e $x            #debug
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
@@ -21,16 +23,35 @@ for x in "$TDIR" "$TDIR/.." "." ".." "$HOME/tools/z0lib" "/etc"; do
 done
 if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
-  exit 2
+  # exit 2
+  Z0LIBDIR=$(find . -name z0librc|head -n1)
+  . $Z0LIBDIR
 fi
+for x in $TDIR . .. $HOME/dev $HOME/tools/travis_emulator; do
+  echo "[ -e $x/travisrc ]" #debug
+  readlink -e $x            #debug
+done
 TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR . .. $HOME/dev $HOME/tools/travis_emulator")
 if [ -z "$TRAVISLIBDIR" ]; then
   echo "Library file travisrc not found!"
-  exit 2
+  # exit 2
 fi
 . $TRAVISLIBDIR
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
+
+for x in $TDIR . .. $HOME/dev $TDIR/../../zerobug; do
+  echo "[ -e $x/z0testrc ]" #debug
+  readlink -e $x            #debug
+done
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file zerobug not found!"
+  # exit 2
+fi
+. $Z0TLIBDIR
+Z0TLIBDIR=$(dirname $Z0TLIBDIR)
+exit 3
 
 __version__=0.1.14
 
