[REF] local travis emulator

diff --git a/travis_emulator/_travis/travis_after_tests_success b/travis_emulator/_travis/travis_after_tests_success
--- a/travis_emulator/_travis/travis_after_tests_success
+++ b/travis_emulator/_travis/travis_after_tests_success
@@ -25,13 +25,18 @@ else
 fi
 if [ -f $TDIR/travisrc ]; then
 . $TDIR/travisrc
+elif [ -f $TDIR/../travisrc ]; then
+. $TDIR/../travisrc
 elif [ -f ./travisrc ]; then
 . ./travisrc
 elif [ -f ~/travisrc ]; then
 . ~/travisrc
+else
+  echo "Library file travisrc not found!"
+  exit $STS_FAILED
 fi
 
-__version__=0.1.5
+__version__=0.1.6
 
 
 OPTOPTS=(h        n            t         V           v)
@@ -70,31 +75,8 @@ if [ $test_mode -gt 0 ]; then
   do_chkconfig
   exit $STS_SUCCESS
 fi
-if [ $test_mode -gt 0 ]; then
-  do_chkconfig
-  exit $STS_SUCCESS
-fi
 check_4_travis
 
-
-if [ "$PRJNAME" != "Odoo" ]; then
-  run_traced "cd $PKGPATH/$PRJNAME"
-  run_traced "find . -name \"*$PRJNAME*.log\" -exec rm -f '{}' \;"
-  if [ -f ~/dev/pypi/$1/$1/__main__.py ]; then
-    run_traced "coverage erase"
-    if [ $opt_verbose -gt 0 ]; then
-      echo "DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py"
-    fi
-    sts=0
-    if [ $opt_dry_run -eq 0 ]; then
-      DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py
-      coverage report
-    fi
-    sts=$?
-  else
-    sts=$STS_FAILED
-  fi
-else
-  sts=$STS_FAILED
-fi
+run_coverage_test
+sts=$?
 exit $sts
diff --git a/travis_emulator/_travis/travis_run_tests b/travis_emulator/_travis/travis_run_tests
--- a/travis_emulator/_travis/travis_run_tests
+++ b/travis_emulator/_travis/travis_run_tests
@@ -27,98 +27,44 @@ else
 fi
 if [ -f $TDIR/travisrc ]; then
 . $TDIR/travisrc
+elif [ -f $TDIR/../travisrc ]; then
+. $TDIR/../travisrc
 elif [ -f ./travisrc ]; then
 . ./travisrc
 elif [ -f ~/travisrc ]; then
 . ~/travisrc
+else
+  echo "Library file travisrc not found!"
+  exit $STS_FAILED
 fi
 
-__version__=0.1.5
+__version__=0.1.6
 
-
-test_bash () {
-    echo "======== Testing test_bash   ========"
-    sts=$STS_SUCCESS
-    local f
-    for f in $(find . -type f|tr "\n" " "); do
-      local x=$(head $f -n1)
-      if [ "$x" == "#!/bin/bash" -o "$x" == "#! /bin/bash" ]; then
-        bash -n $f
-        local s=$?
-        if [ $sts -eq $STS_SUCCESS ]; then
-          if [ "$(grep ^[[:space:]]*set[[:space:]]*-x $f 2>/dev/null)" ]; then
-            echo "Invalid statement 'set -x' in $f"
-            sts=$STS_FAILED
-          fi
-        else
-          sts=$STS_FAILED
-        fi
-      fi
-    done
-    return $sts
-}
-
-
-test_flake8 () {
-    echo "======== Testing test_flake8 ========"
-    FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"
-    run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg"
-    local status1=$?
-    run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg"
-    local status2=$?
-    return $((${status1} || ${status2}))
-}
-
-test_pylint () {
-    echo "======== Testing test_pylint ========"
-    sts=$STS_SUCCESS
-    TRAVIS_BUILD_DIR=$PKGPATH
-    MODULES_TO_TEST=$TRAVIS_BUILD_DIR
-    PYLINT_CONFIG_DIR="$(dirname $0)/cfg"
+do_test () {
+    if [ $opt_verbose -gt 0 ]; then
+      echo "do_test \"$1\" \"$2\" \"$3\""
+    fi
     if [ "$PRJNAME" == "Odoo" ]; then
-      pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg
+      run_server_test
     else
-      pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint_PYPI.cfg
+      run_regression_test
     fi
-    export PYTHONPATH=${PYTHONPATH}:${MODULES_TO_TEST}
-    if [ "$PRJNAME" == "Odoo" ]; then
-      touch $MODULES_TO_TEST/__init__.py
-    fi
-    IFS="/" read -a REPO <<< "${ODOO_REPO}"
-    export PATH=${PATH}:${PWD}/../${REPO[1]}-${VERSION}/openerp
-
-    #run pylint command
-    run_traced "pylint --rcfile=$pylint_rcfile ${MODULES_TO_TEST}"
     sts=$?
     return $sts
 }
 
 
-run_regression_test () {
-    if [ -f ~/dev/pypi/$1/$1/tests/all_tests ]; then
-      cd ~/dev/pypi/$1/$1/tests
-      ./all_tests
-      sts=$?
-    elif [ -f ~/dev/pypi/$1/$1/tests/test_$1.py ]; then
-      cd ~/dev/pypi/$1/$1/tests
-      python ~/dev/pypi/$1/$1/tests/test_$1.py
-      sts=$?
-    else
-      sts=$STS_FAILED
-    fi
-}
-
-
-OPTOPTS=(h        C         c        n            R        t         V           v)
-OPTDEST=(opt_help opt_check opt_conf opt_dry_run  opt_regr test_mode opt_version opt_verbose)
-OPTACTI=(1        "1>"      "="      "1>"         "1>"     1         "*>"        1)
-OPTDEFL=(0        0         ""        0            0       0         ""          0)
-OPTMETA=("help"   "check"   "filr"   "do nothing" "test"   "test"    "version"   "verbose")
+OPTOPTS=(h        C         c        n            R        r     t         V           v)
+OPTDEST=(opt_help opt_check opt_conf opt_dry_run  opt_regr opt_r test_mode opt_version opt_verbose)
+OPTACTI=(1        "1>"      "="      "1>"         "1>"     1     1         "*>"        1)
+OPTDEFL=(0        0         ""        0            0       0     0         ""          0)
+OPTMETA=("help"   "check"   "filr"   "do nothing" "test"   "rxt" "test"    "version"   "verbose")
 OPTHELP=("this help"\
  "do flake8 and pylint checks"\
  "configuration file"\
  "do nothing (dry-run)"\
  "do regression tests"\
+ "restricted mode, no maintainer-quality-tools (config is local)"\
  "test mode (implies dry-run)"\
  "show version"\
  "verbose mode")
@@ -150,36 +96,44 @@ if [ $test_mode -gt 0 ]; then
 fi
 check_4_travis
 
-
-
-if [ $opt_verbose -gt 0 ]; then
-  echo "if [ \${opt_check:-0} -gt 0 -o \"\${LINT_CHECK:-1}\" == \"1\" ]; then  #($opt_check,$LINT_CHECK)"
+if [ ${opt_regr:-0} -gt 0 ]; then
+  LINT_CHECK="0"
+  TEST_CHECK="1"
 fi
-if [ ${opt_check:-0} -gt 0 -o "${LINT_CHECK:-1}" == "1" ]; then
-  if [ "${BASH_CHECK:-1}" == "1" ]; then
-    test_bash
-    sts_bash=$?
-  else
-    sts=127
-  fi
-  test_flake8
+if [ ${opt_check:-0} -gt 0 ]; then
+  BASH_CHECK="1"
+  LINT_CHECK="1"
+fi
+if [ "${BASH_CHECK:-0}" == "1" ]; then BASH_CHECK_ENABLED=1; else BASH_CHECK_ENABLED=0; fi
+if [ "${LINT_CHECK:-0}" == "1" ]; then LINT_CHECK_ENABLED=1; else LINT_CHECK_ENABLED=0; fi
+if [ "${LINT_CHECK:-1}" == "0" ]; then LINT_CHECK_DISABLED=1; else LINT_CHECK_DISABLED=0; fi
+if [ "${TEST_CHECK:-0}" == "1" ]; then TEST_CHECK_ENABLED=1; else TEST_CHECK_ENABLED=0; fi
+if [ -n "${TEST_CHECK}" ]; then TESTS_UNSPECIFIED=1; else TESTS_UNSPECIFIED=0; fi
+if [ "${TRANSIFEX_CHECK:-0}" == "1" ]; then TRANSIFEX_CHECK_ENABLED=1; else TRANSIFEX_CHECK_ENABLED=0; fi
+#echo "BASH_CHECK=$BASH_CHECK/LINT_CHECK=$LINT_CHECK/TEST_CHECK=$TEST_CHECK/"
+#echo "BASH_CHECK_ENABLED=$BASH_CHECK_ENABLED/LINT_CHECK_ENABLED=$LINT_CHECK_ENABLED/LINT_CHECK_DISABLED=$LINT_CHECK_DISABLED/TEST_CHECK_ENABLED=$TEST_CHECK_ENABLED/TESTS_UNSPECIFIED=$TESTS_UNSPECIFIED"
+if [ $BASH_CHECK_ENABLED -gt 0 ]; then
+  please_test_bash
+  sts_bash=$?
+else
+  sts_bash=127
+fi
+if [ $LINT_CHECK_DISABLED -eq 0 ]; then
+  please_test_flake8
   sts_flake8=$?
-  test_pylint
+  please_test_pylint
   sts_pylint=$?
-  do_summary "$sts_flake8" "$sts_pylint" "$sts_bash"
   sts=$(($sts_flake8 || $sts_pylint))
 fi
-if [ $opt_verbose -gt 0 ]; then
-  echo "if [ \${opt_regr:-0} -gt 0 -o \"\$LINT_CHECK\" != \"1\" ]; then  #($opt_regr,$LINT_CHECK)$sts"
-fi
-if [ ${opt_regr:-0} -gt 0 -o "$LINT_CHECK" != "1" ]; then
-  if [ $sts -eq $STS_SUCCESS ]; then
-    pkgname=$(basename $PKGPATH)
-    # if [ $opt_verbose -gt 0 ]; then
-    #   echo "run_regression_test $pkgname"
-    # fi
-    # run_regression_test $pkgname
-    #sts=$?
+if [ $sts -eq $STS_SUCCESS ]; then
+  if [ $TESTS_UNSPECIFIED -gt 0 -a $LINT_CHECK_ENABLED -eq 0 ]; then
+    do_test
+    test_sts=$?
+  elif [ $TEST_CHECK_ENABLED -gt 0 ]; then
+    do_test
+    test_sts=$?
   fi
+  sts=$test_sts
 fi
+do_summary "$sts_bash" "$sts_flake8" "$sts_pylint" "$test_sts"
 exit $sts
diff --git a/travis_emulator/please b/travis_emulator/please
--- a/travis_emulator/please
+++ b/travis_emulator/please
@@ -24,9 +24,20 @@ else
   echo "Library file z0librc not found!"
   exit $STS_FAILED
 fi
+if [ -f $TDIR/travisrc ]; then
 . $TDIR/travisrc
+elif [ -f $TDIR/../travisrc ]; then
+. $TDIR/../travisrc
+elif [ -f ./travisrc ]; then
+. ./travisrc
+elif [ -f ~/travisrc ]; then
+. ~/travisrc
+else
+  echo "Library file travisrc not found!"
+  exit $STS_FAILED
+fi
 
-__version__="0.1.20"
+__version__="0.1.21"
 
 
 ant_rm_trap () {
@@ -111,144 +122,65 @@ do_check (){
     if [ $opt_verbose -gt 0 ]; then
       echo "do_check \"$1\" \"$2\" \"$3\""
     fi
-    prepare_env_travis "check"
-    # if [ -f $TOOLS_PATH/travis_install_pkgs ]; then
-    #   run_traced $TOOLS_PATH/travis_install_pkgs
-    #   if [ $? -ne 0 ]; then sts=$?; fi
-    # fi
-    if [ $sts -eq $STS_SUCCESS ]; then
-      if [ $opt_r -gt 0 ]; then
-        test_bash
-        sts_bash=$?
-        cd $TOOLS_PATH
-        test_flake8
-        sts_flake8=$?
-        test_pylint
-        sts_pylint=$?
-        do_summary "$sts_flake8" "$sts_pylint" "$sts_bash"
-        sts=$(($sts_flake8 || $sts_pylint))
-      else
-        if [ $TOOLS_PATH/travis_run_tests ]; then
-          run_traced $TOOLS_PATH/travis_run_tests
-          if [ $? -ne 0 ]; then sts=$?; fi
-        else
-          sts=127
-        fi
-      fi
-    fi
-    return $sts
-}
-
-test_flake8 () {
-    echo "======== Testing test_flake8 ========"
-    FLAKE8_CONFIG_DIR="$PWD/cfg"
-    run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg"
-    local status1=$?
-    run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg"
-    local status2=$?
-    return $((${status1} || ${status2}))
-}
-
-test_pylint () {
-    echo "======== Testing test_pylint ========"
-    sts=$STS_SUCCESS
-    TRAVIS_BUILD_DIR=$PKGPATH
-    MODULES_TO_TEST=$TRAVIS_BUILD_DIR
-    PYLINT_CONFIG_DIR="$PWD/cfg"
-    if [ "$PRJNAME" == "Odoo" ]; then
-      pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg
+    if [ -x $TOOLS_PATH/travis_run_tests ]; then
+      opts=$(inherits_travis_opts "Cnrv")
+      run_traced "TOOLS_PATH=$TOOLS_PATH $TOOLS_PATH/travis_run_tests $opts"
+      if [ $? -ne 0 ]; then sts=$?; fi
+    elif [ $opt_r -gt 0 ]; then
+      please_run_tests "-C"
+      sts=$?
     else
-      pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint_PYPI.cfg
+      sts=127
     fi
-
-    export PYTHONPATH=${PYTHONPATH}:${MODULES_TO_TEST}
-    if [ "$PRJNAME" == "Odoo" ]; then
-      touch $MODULES_TO_TEST/__init__.py
-    fi
-    IFS="/" read -a REPO <<< "${ODOO_REPO}"
-    export PATH=${PATH}:${PWD}/../${REPO[1]}-${VERSION}/openerp
-
-    #run pylint command
-    run_traced "pylint --rcfile=$pylint_rcfile ${MODULES_TO_TEST}"
-    sts=$?
-    return $sts
-}
-
-test_bash () {
-    echo "======== Testing test_bash   ========"
-    sts=$STS_SUCCESS
-    local f
-    for f in $(find . -type f|tr "\n" " "); do
-      local x=$(head $f -n1)
-      if [ "$x" == "#!/bin/bash" -o "$x" == "#! /bin/bash" ]; then
-        bash -n $f
-        local s=$?
-        if [ $sts -eq $STS_SUCCESS ]; then
-          if [ "$(grep ^[[:space:]]*set[[:space:]]*-x $f 2>/dev/null)" ]; then
-            echo "Invalid statement 'set -x' in $f"
-            sts=$STS_FAILED
-          fi
-        else
-          sts=$STS_FAILED
-        fi
-      fi
-    done
     return $sts
 }
 
 
 do_test () {
-    prepare_env_travis "test"
-    if [ -f ~/dev/pypi/$1/$1/tests/all_tests ]; then
-      if [ $opt_dprj -gt 0 ]; then
-        cd ~/dev/pypi/$1/$1
-        ./tests/all_tests
-      else
-        cd ~/dev/pypi/$1/$1/tests
-        ./all_tests
-      fi
-      sts=$?
-    elif [ -f ~/dev/pypi/$1/$1/tests/test_$1.py ]; then
-      if [ $opt_dprj -gt 0 ]; then
-        cd ~/dev/pypi/$1/$1
-      else
-        cd ~/dev/pypi/$1/$1/tests
-      fi
-      PYTHONPATH=~/dev/pypi/$1 python ~/dev/pypi/$1/$1/tests/test_$1.py
+    if [ $opt_verbose -gt 0 ]; then
+      echo "do_test \"$1\" \"$2\" \"$3\""
+    fi
+    if [ -x $TOOLS_PATH/travis_run_tests ]; then
+      opts=$(inherits_travis_opts "Rnrv")
+      run_traced "TOOLS_PATH=$TOOLS_PATH $TOOLS_PATH/travis_run_tests $opts"
+      if [ $? -ne 0 ]; then sts=$?; fi
+    elif [ $opt_r -gt 0 ]; then
+      please_run_tests "-R"
       sts=$?
     else
-      sts=$STS_FAILED
+      test_sts=$STS_FAILED
+      sts=$test_sts
     fi
-    # set +x #debug
     return $sts
 }
 
 
 do_coverage () {
-    run_traced "cd $PRJPATH"
-    prepare_env_travis "coverage"
-    run_traced "find . -name \"*$PRJNAME*.log\" -exec rm -f '{}' \;"
-    if [ -f ~/dev/pypi/$1/$1/__main__.py ]; then
-      run_traced "coverage erase"
-      if [ $opt_verbose -gt 0 ]; then
-        echo "DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py"
-      fi
-      sts=0
-      if [ $opt_dry_run -eq 0 ]; then
-        DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py
-        coverage report
-      fi
-      sts=$?
-    else
-      sts=$STS_FAILED
+    if [ $opt_verbose -gt 0 ]; then
+      echo "do_coverage \"$1\" \"$2\" \"$3\""
     fi
+    run_coverage_test
+    sts=$?
     return $sts
 }
 
 
 do_travis (){
-    travis local/"$1";
-    return 0
+    if [ $opt_verbose -gt 0 ]; then
+      echo "do_travis \"$1\" \"$2\" \"$3\""
+    fi
+    if [ $opt_r -gt 0 ]; then
+      please_run_tests "-CR"
+    else
+      opts=$(inherits_travis_opts "cnv")
+      if [ -n "$opts" ]; then
+        travis "$opts" "$@"
+      else
+        travis "$@"
+      fi
+    fi
+    sts=$?
+    return $sts
 }
 
 
@@ -266,7 +198,7 @@ OPTOPTS=(h        b          c        d        j        k        L         n    
 OPTDEST=(opt_help opt_branch opt_conf opt_diff opt_dprj opt_keep opt_log   opt_dry_run opt_dpath opt_quiet opt_r opt_srcs test_mode opt_uop opt_version opt_verbose)
 OPTACTI=(1        "="        "="      1        1        1        "="       1           "="       1         1     "="      1         1       "*"         1)
 OPTDEFL=(1        "9.0"      ""       0        0        0        ""        0           ""        0         0     ""       0         0       ""          0)
-OPTMETA=("help"   "branch"   "file"   "diff"   "dprj"   "kkep"   "logfile" "noop"      "path"    "quiet"   "rxt" "files"  "test"    "uop"   "version"   "verbose")
+OPTMETA=("help"   "branch"   "file"   "diff"   "dprj"   "keep"   "logfile" "noop"      "path"    "quiet"   "rxt" "files"  "test"    "uop"   "version"   "verbose")
 OPTHELP=("this help, type '$THIS help' for furthermore info"\
  "branch: must be 7.0 or 8.0 or 9.0 (def 9.0)"\
  "configuration file"\
@@ -305,6 +237,10 @@ init_travis
 if [ $opt_verbose -gt 1 ]; then set -x; fi
 prepare_env_travis "$action"
 sts=$STS_SUCCESS
+sts_bash=127
+sts_flake8=127
+sts_pylint=127
+test_sts=127
 if [ "$action" == "help" ]; then
   man $TDIR/$THIS.man
 elif [ "$action" == "annotate" ]; then
@@ -337,24 +273,7 @@ elif [ "$action" == "test" ]; then
   do_test "$pkgname" "$sub1" "$sub2"
   sts=$?
 elif [ "$action" == "travis" ]; then
-  if [ $opt_r -gt 0 ]; then
-    do_check "$pkgname" "$sub1" "$sub2"
-    sts=$?
-    if [ $sts -eq $STS_SUCCESS ]; then
-      do_test "$pkgname" "$sub1" "$sub2"
-      sts=$?
-    fi
-    if [ $sts -eq $STS_SUCCESS ]; then
-      do_coverage "$pkgname" "$sub1" "$sub2"
-      sts=$?
-    fi
-  else
-    opts=$(inherits_travis_opts "cnrv")
-    if [ $opt_verbose -gt 0 ]; then
-      echo "do_travis \"$opts\" \"$pkgname\" \"$sub1\" \"$sub2\""
-    fi
-    do_travis "$opts" "$pkgname" "$sub1" "$sub2"
-  fi
+  do_travis "$pkgname" "$sub1" "$sub2"
   sts=$?
 elif [ "$action" == "version" ]; then
   do_version "$pkgname" "$sub1" "$sub2"
diff --git a/travis_emulator/travis b/travis_emulator/travis
--- a/travis_emulator/travis
+++ b/travis_emulator/travis
@@ -6,7 +6,7 @@
 # Deploy:
 # ~/dev                          -> this script
 # ~/dev/_travis                  -> default script (travis_install_pkgs, travis_runs_tests, travis_after_tests_success)
-# ~/dev/maintainer-quality-tools -> actual scripts, mainly for Odoo environment by OCA; thery replaces default scripts
+# ~/maintainer-quality-tools -> actual scripts, mainly for Odoo environment by OCA; thery replaces default scripts
 # When developping travis emulator itself, deployment is:
 # ~/dev/pypi/travis_em/travis_em -> this script
 # ~/dev/pypi/travis_em/travis_em/_travis -> default script (travis_install_pkgs, travis_runs_tests, travis_after_tests_success)
@@ -26,24 +26,50 @@ elif [ -f ~/z0librc ]; then
 else
 . /etc/z0librc
 fi
+if [ -f $TDIR/travisrc ]; then
 . $TDIR/travisrc
+elif [ -f $TDIR/../travisrc ]; then
+. $TDIR/../travisrc
+elif [ -f ./travisrc ]; then
+. ./travisrc
+elif [ -f ~/travisrc ]; then
+. ~/travisrc
+else
+  echo "Library file travisrc not found!"
+  exit $STS_FAILED
+fi
 
-__version__=0.1.34
+__version__=0.1.35
 
 
 process_local () {
     if [ $TOOLS_PATH/travis_run_tests ]; then
-      run_traced "$TOOLS_PATH/travis_run_tests $opts_dry_run$opts_verbose"
+      if [ "$action" == "check" ]; then
+        opts=$(inherits_travis_opts "Cnrv")
+      elif [ "$action" == "test" ]; then
+        opts=$(inherits_travis_opts "Rnrv")
+      else
+        opts=$(inherits_travis_opts "CRnrv")
+      fi
+      run_traced "TOOLS_PATH=$TOOLS_PATH $TOOLS_PATH/travis_run_tests $opts"
       if [ $? -ne 0 ]; then sts=$?; fi
+    elif [ $opt_r -gt 0 ]; then
+      if [ "$action" == "test" ]; then
+        please_run_tests "-R"
+        sts=$?
+      elif [ "$action" == "check" ]; then
+        please_run_tests "-C"
+        sts=$?
+      else
+        please_run_tests "-CR"
+        sts=$?
+      fi
     else
       sts=127
     fi
-    if [ $sts -eq $STS_SUCCESS -a "$action" != "check" ]; then
+    if [ $sts -eq $STS_SUCCESS -a "$action" != "check" -a "$action" != "test" ]; then
       run_traced $TOOLS_PATH/travis_after_tests_success
       if [ $? -ne 0 ]; then sts=$?; fi
-      if [ $sts -eq $STS_SUCCESS ]; then
-        coverage report
-      fi
     fi
     return $sts
 }
@@ -51,11 +77,69 @@ process_local () {
 process_yaml () {
     f1=$PRJPATH/.travis.yml
     if [ -f $f1 ]; then
+      local SCRIPTS=
+      local SET_GBLS="TOOLS_PATH=$TOOLS_PATH"
+      local lev=0
+      local ident=0
       local line=
+      local ln=
+      local sect=
+      local i
+      local a
+      local b
       while IFS=\~ read -r line; do
-        echo "$line"
+        if [[ $line =~ ^# ]]; then
+          line=
+        elif [[ $line =~ ^[[:space:]]+ ]]; then
+          for i in {0..10};do if [ "${line:i:1}" != " " ]; then break; fi; done
+          if [ $i -gt $ident ]; then
+            ((lev++))
+            ident=$i
+          elif [ $i -lt $ident ]; then
+            ((lev-))
+            ident=$i
+          fi
+        else
+          lev=0
+          ident=0
+        fi
+        ln=$(echo $line)
+        if [ $lev -eq 0 ]; then
+          IFS=: read a b <<<"$ln"
+          if [ "$a" == "script" ]; then
+            sect=$a
+          elif [ "$a" == "env" ]; then
+            sect=$a
+          else
+            sect=
+          fi
+        elif [ $lev -eq 1 ]; then
+          IFS=: read a b <<<"$ln"
+          if [ "$sect" == "env" ]; then
+            if [ "$a" == "global" ]; then
+              sect="$sect.$a"
+            fi
+          else
+            IFS=- read a b <<<"$ln"
+            if [ "$sect" == "script" ]; then
+              SCRIPTS="$SCRIPTS \"$(echo $b)\""
+            elif [ "$sect" == "env.global" ]; then
+              if [ "${b:0:8}" == " VERSION" ]; then
+                SET_GBLS="$SET_GBLS $(echo $b)"
+              fi
+            fi
+          fi
+        fi
       done < "$f1"
       sts=0
+      export $SET_GBLS
+      for ln in $SCRIPTS; do
+        line=$(echo $ln)
+        if [ $opt_verbose -gt 0 ]; then
+          echo "TOOLS_PATH=$TOOLS_PATH LINT_CHECK="1" TESTS="1" $line"
+        fi
+        TOOLS_PATH=$TOOLS_PATH LINT_CHECK="1" TESTS="1" eval $line
+      done
     else
       process_local
       sts=$?
@@ -89,6 +173,7 @@ if [ $opt_help -gt 0 ]; then
   exit $STS_SUCCESS
 fi
 
+if [ -z "$action" ]; then action=all; fi
 opts_travis
 $(init_cfg)
 $(active_cfg)
@@ -99,7 +184,6 @@ if [ $opt_verbose -gt 1 ]; then set -x; fi
 prepare_env_travis "$action"
 sts=$STS_SUCCESS
 
-if [ -z "$action" ]; then action=all; fi
 if [ "$action" != "check" -a "$action" != "test" -a "$action" != "all" -a "$action" != "setup" -a "$action" != "chkconfig" ]; then
   echo "Invalid action!"
   echo "action should be one of check, test, all, setup or chkconfig"
diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -2,12 +2,12 @@
 # -*- coding: utf-8 -*-
 #
 # Common file for travis emulator scripts
-#__version__=0.1.50
+#__version__=0.1.52
 
 MAKEF=/opt/odoo/dev/Makefile
 DIST_CONF=./conf/.local_dist_pkg.conf
 XRGI="^(.*\/|)conf\/.*sample$"
-XXXX=".pyc .log .bak .out .tmp .conf build/ dist/ conf/ .cover/ .coverage/ .git/ ~"
+XXXX=".pyc .log .bak .out .tmp .conf .tracehistory build/ dist/ conf/ .cover/ .coverage/ .git/ ~"
 
 
 opts_travis () {
@@ -63,34 +63,50 @@ inherits_travis_opts () {
   else
     local e=$1
   fi
-  if [[ $e =~ d ]]; then
-    if [ $opt_diff -gt 0 ]; then
-      opts="${opts}d"
+  if [ $(echo $TOOLS_PATH|grep -v "/maintainer-quality-tools/"  2>/dev/null) ]; then
+    if [[ $e =~ C ]]; then
+      opts="${opts}C"
     fi
-  fi
-  if [[ $e =~ n ]]; then
-    if [ $opt_dry_run -gt 0 ]; then
-      opts="${opts}n"
+    if [[ $e =~ R ]]; then
+      opts="${opts}R"
     fi
-  fi
-  if [[ $e =~ r ]]; then
-    if [ $opt_r -gt 0 ]; then
-      opts="${opts}r"
+    if [[ $e =~ d ]]; then
+      if [ $opt_diff -gt 0 ]; then
+        opts="${opts}d"
+      fi
     fi
-  fi
-  if [[ $e =~ u ]]; then
-    if [ $opt_uop -gt 0 ]; then
-      opts="${opts}u"
+    if [[ $e =~ n ]]; then
+      if [ $opt_dry_run -gt 0 ]; then
+        opts="${opts}n"
+      fi
     fi
-  fi
-  if [[ $e =~ v ]]; then
-    if [ $opt_verbose -gt 0 ]; then
-      opts="${opts}v"
+    if [[ $e =~ r ]]; then
+      if [ $opt_r -gt 0 ]; then
+        opts="${opts}r"
+      fi
     fi
-  fi
-  if [[ $e =~ c ]]; then
-    if [ -n "$opt_conf" ]; then
-     opts="${opts}c$TCONF"
+    if [[ $e =~ u ]]; then
+      if [ $opt_uop -gt 0 ]; then
+        opts="${opts}u"
+      fi
+    fi
+    if [[ $e =~ v ]]; then
+      if [ $opt_verbose -gt 0 ]; then
+        opts="${opts}v"
+      fi
+    fi
+    if [[ $e =~ c ]]; then
+      if [ -n "$opt_conf" ]; then
+        opts="${opts}c$TCONF"
+      fi
+    fi
+  else
+    if [[ $e =~ C ]]; then
+      export BASH_CHECK="1"
+      export LINT_CHECK="1"
+    fi
+    if [[ $e =~ R ]]; then
+      export TEST_CHECK="1"
     fi
   fi
   if [ -n "$opts" ]; then
@@ -112,6 +128,10 @@ init_travis () {
     fi
     if [ ${opt_verbose:-0} -eq 0 ]; then
       opt_verbose=$(get_cfg_value "" "loglevel")
+      if [ $opt_verbose -gt 0 ]; then opt_verbose=1; fi
+    elif [ ${opt_verbose:-0} -eq 1 ]; then
+      opt_verbose=$(get_cfg_value "" "loglevel")
+      if [ $opt_verbose -eq 0 ]; then opt_verbose=1; fi
     fi
     if [ $opt_verbose -ne 0 ]; then
       opts_verbose=-v
@@ -194,25 +214,42 @@ init_travis () {
         TOOLS_PATH=$TDIR/_travis
       elif [ -d $HOME/dev/_travis -a ${opt_r:-0} -gt 0 ]; then
         TOOLS_PATH=$HOME/dev/_travis
-      elif [ -d $TDIR/maintainer-quality-tools/travis ]; then
-        TOOLS_PATH=$TDIR/maintainer-quality-tools/travis
+      elif [ -d $TDIR/_travis -a "$PRJNAME" != "Odoo" ]; then
+        TOOLS_PATH=$TDIR/_travis
+      elif [ -d $HOME/dev/_travis -a "$PRJNAME" != "Odoo" ]; then
+        TOOLS_PATH=$HOME/dev/_travis
       elif [ -d $HOME/dev/maintainer-quality-tools/travis ]; then
         TOOLS_PATH=$HOME/dev/maintainer-quality-tools/travis
-      elif [ -d /opt/odoo/dev/maintainer-quality-tools/travis ]; then
-        TOOLS_PATH=/opt/odoo/dev/maintainer-quality-tools/travis
+      elif [ -d $HOME/maintainer-quality-tools/travis ]; then
+        TOOLS_PATH=$HOME/maintainer-quality-tools/travis
+      elif [ -d /opt/odoo/maintainer-quality-tools/travis ]; then
+        TOOLS_PATH=/opt/odoo/maintainer-quality-tools/travis
       else
         unset -v TOOLS_PATH
       fi
-    fi
-    if [ $opt_verbose -gt 0 ]; then
-      echo "TOOLS_PATH=$TOOLS_PATH"
+      if [ $opt_verbose -gt 0 ]; then
+        echo "--> TOOLS_PATH=$TOOLS_PATH"
+      fi
+    else
+      if [ $opt_verbose -gt 0 ]; then
+        echo "TOOLS_PATH=$TOOLS_PATH"
+      fi
     fi
 }
 
 prepare_env_travis () {
     local action="$1"
-    if [ $(echo $PATH|grep -v "$TOOLS_PATH"  2>/dev/null) ]; then
+    if [ $(echo :$PATH:|grep -v ":$TOOLS_PATH:"  2>/dev/null) ]; then
+      if [ $opt_verbose -gt 0 ]; then
+        echo "--> export PATH=$TOOLS_PATH:$PATH"
+      fi
       export PATH=$TOOLS_PATH:$PATH
+    fi
+    if [ $(echo :$PATH:|grep -v ":$DEVPATH:"  2>/dev/null) ]; then
+      if [ $opt_verbose -gt 0 ]; then
+        echo "--> export PATH=$DEVPATH:$PATH"
+      fi
+      export PATH=$DEVPATH:$PATH
     fi
     export FLAKE8_CONFIG_DIR=$TOOLS_PATH/cfg
     export LINT_CHECK=1
@@ -249,7 +286,11 @@ prepare_env_travis () {
       fi
     fi
     export LGITPATH=$(expand_path "$LGITPATH")
-    DEVPATH=$TDIR
+    if [ -x $TDIR/travis ]; then
+      export DEVPATH=$TDIR
+    else
+      export DEVPATH=$(readlink -f ~/dev)
+    fi
 }
 
 check_4_travis () {
@@ -266,7 +307,7 @@ check_4_travis () {
 
 do_chkconfig () {
     echo "Project name   = \"$PRJNAME\""
-    echo "Tools path     = \"$DEVPATH\""
+    echo "Tools path     = \"$TOOLS_PATH\" -r=\"$DEVPATH\""
     echo "Hosted         = \"$HOSTENV\""
     echo "Branch         = \"$BRANCH\""
     echo "Package name   = \"$pkgname\""
@@ -408,14 +449,14 @@ update_dev () {
         if [ -f $PKGPATH/$pkgname/$x ]; then
           if [ ${opt_diff:-0} -gt 0 ]; then
             if [ "$(diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x)" ]; then
-              if [ ${opt_verbose:-0} -gt 0 ]; then echo "> diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
+              if [ ${opt_verbose:-0} -gt 0 ]; then echo "--> diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
               diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x
             fi
           elif [ ${opt_fetch:-0} -gt 0 ]; then
-            if [ ${opt_verbose:-0} -gt 0 ]; then echo "> $opt_dry_run||cp $XDPATH/$x $PKGPATH/$pkgname/$x"; fi
+            if [ ${opt_verbose:-0} -gt 0 ]; then echo "--> $opt_dry_run||cp $XDPATH/$x $PKGPATH/$pkgname/$x"; fi
             (($opt_dry_run))||cp $XDPATH/$x $PKGPATH/$pkgname/$x
           else
-            if [ $opt_verbose -gt 0 ]; then echo "> $opt_dry_run||cp $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
+            if [ $opt_verbose -gt 0 ]; then echo "--> $opt_dry_run||cp $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
             (($opt_dry_run))||cp $PKGPATH/$pkgname/$x $XDPATH/$x
           fi
         fi
@@ -425,7 +466,7 @@ update_dev () {
           if [ ${opt_diff:-0} -gt 0 ]; then
              diff -rq $XLDF $PKGPATH/$pkgname/$x $XDPATH/$x
           elif [ ${opt_fetch:-0} -eq 0 ]; then
-             if [ $opt_verbose -gt 0 ]; then echo "> $opt_dry_run||cp -R $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
+             if [ $opt_verbose -gt 0 ]; then echo "--> $opt_dry_run||cp -R $PKGPATH/$pkgname/$x $XDPATH/$x"; fi
              (($opt_dry_run))||cp -R $PKGPATH/$pkgname/$x $XDPATH/$x
           fi
         done
@@ -435,13 +476,13 @@ update_dev () {
           if [ -f $PKGPATH/$pkgname/$x ]; then
             if [ ${opt_diff:-0} -gt 0 ]; then
               if [ "$(diff -rq $XLDF $PKGPATH/$pkgname/$x ~/bin/$x)" ]; then
-                if [ ${opt_verbose:-0} -gt 0 ]; then echo "> diff -rq $XLDF $PKGPATH/$pkgname/$x ~/bin/$x"; fi
+                if [ ${opt_verbose:-0} -gt 0 ]; then echo "--> diff -rq $XLDF $PKGPATH/$pkgname/$x ~/bin/$x"; fi
                 diff -rq $XLDF $PKGPATH/$pkgname/$x ~/bin/$x
               fi
             elif [ ${opt_fetch:-0} -gt 0 ]; then
               true
             else
-              if [ $opt_verbose -gt 0 ]; then echo "> $opt_dry_run||cp $PKGPATH/$pkgname/$x ~/bin/$x"; fi
+              if [ $opt_verbose -gt 0 ]; then echo "--> $opt_dry_run||cp $PKGPATH/$pkgname/$x ~/bin/$x"; fi
               (($opt_dry_run))||cp $PKGPATH/$pkgname/$x ~/bin/$x
             fi
           fi
@@ -604,7 +645,7 @@ robocopy () {
             local optrsync="-abzhe"
           fi
           local optssh="$3"
-          echo "rsync $opts_dry_run $optrsync \"$optssh\" $opts_upd --del --copy-links $XLFS $ff $2$v"
+          echo "--> rsync $opts_dry_run $optrsync \"$optssh\" $opts_upd --del --copy-links $XLFS $ff $2$v"
           rsync $opts_dry_run $optrsync "$optssh" $opts_upd --del --copy-links $XLFS $ff $2$v
         else
           if [ ${opt_verbose:-0} -gt 0 ]; then
@@ -613,7 +654,7 @@ robocopy () {
             local optrsync="-ab"
           fi
           local optssh=""
-          echo "rsync $opts_dry_run $optrsync $opts_upd --del --copy-links $XLFS $ff $2$v"
+          echo "--> rsync $opts_dry_run $optrsync $opts_upd --del --copy-links $XLFS $ff $2$v"
           rsync $opts_dry_run $optrsync $opts_upd --del --copy-links $XLFS $ff $2$v
         fi
       else
@@ -650,26 +691,177 @@ clean_dirs () {
 }
 
 
+please_test_bash () {
+    echo "======== Testing test_bash   ========"
+    sts=$STS_SUCCESS
+    if [ $opt_dry_run -eq 0 ]; then
+      local f
+      for f in $(find . -type f|tr "\n" " "); do
+        local x=$(head $f -n1)
+        if [ "$x" == "#!/bin/bash" -o "$x" == "#! /bin/bash" ]; then
+          bash -n $f
+          local s=$?
+          if [ $sts -eq $STS_SUCCESS ]; then
+            if [ "$(grep ^[[:space:]]*set[[:space:]]*-x $f 2>/dev/null)" ]; then
+              echo "Invalid statement 'set -x' in $f"
+              sts=$STS_FAILED
+            fi
+          else
+            sts=$STS_FAILED
+          fi
+        fi
+      done
+    else
+      sts=$STS_SUCCESS
+    fi
+    return $sts
+}
+
+please_test_flake8 () {
+    echo "======== Testing test_flake8 ========"
+    if [ $opt_dry_run -eq 0 ]; then
+      FLAKE8_CONFIG_DIR="$TOOLS_PATH/cfg"
+      run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg"
+      local status1=$?
+      run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg"
+      local status2=$?
+      sts=$((${status1} || ${status2}))
+    else
+      sts=$STS_SUCCESS
+    fi
+    return $sts
+}
+
+please_test_pylint () {
+    echo "======== Testing test_pylint ========"
+    sts=$STS_SUCCESS
+    if [ $opt_dry_run -eq 0 ]; then
+      TRAVIS_BUILD_DIR=$PKGPATH
+      MODULES_TO_TEST=$TRAVIS_BUILD_DIR
+      PYLINT_CONFIG_DIR="$TOOLS_PATH/cfg"
+      if [ "$PRJNAME" == "Odoo" ]; then
+        pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg
+      else
+        pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint_PYPI.cfg
+      fi
+      export PYTHONPATH=${PYTHONPATH}:${MODULES_TO_TEST}
+      if [ "$PRJNAME" == "Odoo" ]; then
+        touch $MODULES_TO_TEST/__init__.py
+      fi
+      IFS="/" read -a REPO <<< "${ODOO_REPO}"
+      export PATH=${PATH}:${PWD}/../${REPO[1]}-${VERSION}/openerp
+      #run pylint command
+      run_traced "pylint --rcfile=$pylint_rcfile ${MODULES_TO_TEST}"
+      sts=$?
+    fi
+    return $sts
+}
+
 do_summary () {
+# do_summary(bash,flake8,pylint,test)
     echo "+======================================="
     echo "|  Tests summary:"
     echo "|---------------------------------------"
-    if [ $3 -eq 127 ]; then
-      true
-    elif [ $3 -eq $STS_SUCCESS ]; then
-      echo "| test_bash                   Success"
+    if [ "$PRJNAME" == "Odoo" ]; then
+      local des=("" "test_bash" "test_flake8" "test_pylint" "test_server.py")
     else
-      echo "| test_bash                   FAIL"
+      local des=("" "test_bash" "test_flake8" "test_pylint" "regression_test")
     fi
-    if [ $1 -eq $STS_SUCCESS ]; then
-      echo "| test_flake8                 Success"
-    else
-      echo "| test_flake8                 FAIL"
-    fi
-    if [ $2 -eq $STS_SUCCESS ]; then
-      echo "| test_pylint                 Success"
-    else
-      echo "| test_pylint                 FAIL"
-    fi
+    for i in {1..4};do
+      if [ -n "${!i}" ]; then
+        local x=$(printf "%-20.20s" "${des[$i]}")
+        if [ ${!i} -eq $STS_SUCCESS ]; then
+          echo "| $x        Success"
+        elif [ ${!i} -ne 127 ]; then
+          echo "| $x        FAIL"
+        fi
+      fi
+    done
     echo "+======================================="
+}
+
+run_regression_test () {
+    echo "======== Running regression_test ========"
+    cd $PRJPATH
+    if [ $opt_dry_run -eq 0 ]; then
+      if [ -f ./tests/all_tests ]; then
+        if [ $opt_dprj -gt 0 ]; then
+          ./tests/all_tests
+        else
+          cd ./tests
+          ./all_tests
+        fi
+        sts=$?
+      elif [ -f ./tests/test_$PRJNAME.py ]; then
+        cd ./tests
+        python ./test_$PRJNAME.py
+        sts=$?
+      else
+        sts=$STS_FAILED
+      fi
+    else
+      sts=$STS_SUCCESS
+    fi
+    return $sts
+}
+
+run_coverage_test () {
+    cd $PRJPATH
+    if [ $opt_dry_run -eq 0 ]; then
+      if [ "$PRJNAME" != "Odoo" ]; then
+        # find . -name "*$PRJNAME*.log" -exec rm -f '{}' \;
+        if [ -f ./__main__.py ]; then
+          coverage erase
+          if [ $opt_verbose -gt 0 ]; then
+            echo "DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py"
+          fi
+          DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py
+          coverage report
+          sts=$STS_SUCCESS
+        else
+          sts=$STS_FAILED
+        fi
+      else
+        sts=$STS_SUCCESS
+      fi
+    else
+      sts=$STS_SUCCESS
+    fi
+    return $sts
+}
+
+run_server_test () {
+  echo "======== Running server_test ========"
+  sts=$STS_FAILED
+  return $sts
+}
+
+please_run_tests () {
+    sts=$STS_SUCCESS
+    if [[ $1 =~ C ]]; then
+      please_test_bash
+      sts_bash=$?
+      cd $TOOLS_PATH
+      please_test_flake8
+      sts_flake8=$?
+      please_test_pylint
+      sts_pylint=$?
+      sts=$(($sts_flake8 || $sts_pylint))
+    fi
+    if [[ $1 =~ R ]]; then
+      if [ "$PRJNAME" == "Odoo" ]; then
+        run_server_test
+      else
+        run_regression_test
+      fi
+      test_sts=$?
+      if [ $test_sts -ne $STS_SUCCESS ]; then
+        sts=$test_sts
+      fi
+    fi
+    do_summary "$sts_bash" "$sts_flake8" "$sts_pylint" "$test_sts"
+    if [ $sts -eq $STS_SUCCESS ]; then
+      run_coverage_test
+    fi
+    return $sts
 }
