[REF] partial travis emulator refactor

diff --git a/travis_emulator/_travis/travis_after_tests_success b/travis_emulator/_travis/travis_after_tests_success
--- a/travis_emulator/_travis/travis_after_tests_success
+++ b/travis_emulator/_travis/travis_after_tests_success
@@ -5,81 +5,98 @@
 #
 # This free software is released under GNU Affero GPL3
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
-# (C) 2015 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
+if [ -e $TDIR/z0librc ]; then
 . $TDIR/z0librc
-elif [ -f ./z0librc ]; then
+elif [ -e ./z0librc ]; then
 . ./z0librc
-elif [ -f ~/z0librc ]; then
+elif [ -e ../z0librc ]; then
+. ../z0librc
+elif [ -e ~/z0librc ]; then
 . ~/z0librc
-else
+elif [ -f /etc/z0librc ]; then
 . /etc/z0librc
+else
+  echo "Library file z0librc not found!"
+  exit $STS_FAILED
 fi
-TCONF=$TDIR/.$THIS.conf
+if [ -f $TDIR/travisrc ]; then
+. $TDIR/travisrc
+elif [ -f ./travisrc ]; then
+. ./travisrc
+elif [ -f ~/travisrc ]; then
+. ~/travisrc
+fi
 
-__version__=0.1.1
-
-
-
-run_traced () {
-    # set -x  #debug
-    if [ $opt_verbose -gt 0 ]; then
-      echo "$@"
-    fi
-    sts=0
-    if [ $opt_dry_run -eq 0 ]; then
-      $@
-      sts=$?
-    fi
-    # set +x  #debug
-    return $sts
-}
+__version__=0.1.4
 
 
-OPTOPTS=(h        n            V           v)
-OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose)
-OPTACTI=(1        "1>"         "*>"        1)
-OPTDEFL=(1        0            ""          0)
-OPTMETA=("help"   "do nothing" "version"   "verbose")
+OPTOPTS=(h        n            t         V           v)
+OPTDEST=(opt_help opt_dry_run  test_mode opt_version opt_verbose)
+OPTACTI=(1        "1>"         1         "*>"        1)
+OPTDEFL=(1        0            0         ""          0)
+OPTMETA=("help"   "do nothing" "test"    "version"   "verbose")
 OPTHELP=("this help"\
  "do nothing (dry-run)"\
+ "test mode (implies dry-run)"\
  "show version"\
  "verbose mode")
 OPTARGS=(PKGPATH PRJNAME)
-parseoptargs $@
 
+parseoptargs "$@"
 if [ "$opt_version" ]; then
   echo "$__version__"
   exit 0
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Run coverall after successfull test"\
-  "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 
-if [ ! -d $PKGPATH ]; then
-  echo "Invalid path $PKGPATH"
-  exit 1
-elif [ "$PRJNAME" != "Odoo" ]; then
-  if [ ! -d $PKGPATH/$pkgname ]; then
-    echo "Invalid path $PKGPATH/$pkgname"
-    exit 1
-  fi
+opts_travis
+$(init_cfg)
+$(active_cfg)
+conf_default
+link_cfg $TCONF
+init_travis
+if [ $opt_verbose -gt 1 ]; then
+  set -x
 fi
+prepare_env_travis "coverage"
+sts=$STS_SUCCESS
+if [ $test_mode -gt 0 ]; then
+  do_chkconfig
+  exit $STS_SUCCESS
+fi
+if [ $test_mode -gt 0 ]; then
+  do_chkconfig
+  exit $STS_SUCCESS
+fi
+check_4_travis
+
+
 if [ "$PRJNAME" != "Odoo" ]; then
-  cd $PKGPATH/$PRJNAME;
-  run_traced find . -name "*$PRJNAME*.log" -exec rm -f '{}' \;
-  run_traced coverage erase
-  if [ $opt_verbose -gt 0 ]; then
-    echo "DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py"
+  run_traced "cd $PKGPATH/$PRJNAME"
+  run_traced "find . -name \"*$PRJNAME*.log\" -exec rm -f '{}' \;"
+  if [ -f ~/dev/pypi/$1/$1/__main__.py ]; then
+    run_traced "coverage erase"
+    if [ $opt_verbose -gt 0 ]; then
+      echo "DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py"
+    fi
+    sts=0
+    if [ $opt_dry_run -eq 0 ]; then
+      DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py
+      coverage report
+    fi
+    sts=$?
+  else
+    sts=$STS_FAILED
   fi
-  sts=0
-  if [ $opt_dry_run -eq 0 ]; then
-    DEV_ENVIRONMENT=$PRJNAME PYTHONPATH=$PKGPATH coverage run --source $PRJNAME __main__.py
-  fi
+else
+  sts=$STS_FAILED
 fi
-exit 0
+exit $sts
diff --git a/travis_emulator/_travis/travis_run_tests b/travis_emulator/_travis/travis_run_tests
--- a/travis_emulator/_travis/travis_run_tests
+++ b/travis_emulator/_travis/travis_run_tests
@@ -7,76 +7,71 @@
 #
 # This free software is released under GNU Affero GPL3
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
-# (C) 2015 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -f $TDIR/z0librc ]; then
+if [ -e $TDIR/z0librc ]; then
 . $TDIR/z0librc
-elif [ -f ./z0librc ]; then
+elif [ -e ./z0librc ]; then
 . ./z0librc
-elif [ -f ~/z0librc ]; then
+elif [ -e ../z0librc ]; then
+. ../z0librc
+elif [ -e ~/z0librc ]; then
 . ~/z0librc
-else
+elif [ -f /etc/z0librc ]; then
 . /etc/z0librc
+else
+  echo "Library file z0librc not found!"
+  exit $STS_FAILED
 fi
-DEVPATH=$(readlink -f $TDIR/..)
-. $DEVPATH/travisrc
-TCONF=$TDIR/.$THIS.conf
+if [ -f $TDIR/travisrc ]; then
+. $TDIR/travisrc
+elif [ -f ./travisrc ]; then
+. ./travisrc
+elif [ -f ~/travisrc ]; then
+. ~/travisrc
+fi
 
-__version__=0.1.1
-
-
-run_traced () {
-    # set -x  #debug
-    if [ $opt_verbose -gt 0 ]; then
-      echo "$@"
-    fi
-    sts=0
-    if [ $opt_dry_run -eq 0 ]; then
-      $@
-      sts=$?
-    fi
-    # set +x  #debug
-    return $sts
-}
+__version__=0.1.4
 
 
 test_flake8 () {
+    echo "======== Testing test_flake8 ========"
     FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"
-    run_traced flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
-    sts=$?
-    if [ $sts -eq 0 ]; then
-      run_traced flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
-      sts=$?
-    fi
-    return $sts
+    run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg"
+    local status1=$?
+    run_traced "flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg"
+    local status2=$?
+    return $((${status1} || ${status2}))
 }
 
 test_pylint () {
-    sts=0
+    echo "======== Testing test_pylint ========"
+    sts=$STS_SUCCESS
     TRAVIS_BUILD_DIR=$PKGPATH
     MODULES_TO_TEST=$TRAVIS_BUILD_DIR
     PYLINT_CONFIG_DIR="$(dirname $0)/cfg"
-
-    # Fix pylint path. More info: https://www.mail-archive.com/code-quality@python.org/msg00294.html
+    if [ "$PRJNAME" == "Odoo" ]; then
+      pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg
+    else
+      pylint_rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint_PYPI.cfg
+    fi
     export PYTHONPATH=${PYTHONPATH}:${MODULES_TO_TEST}
     if [ "$PRJNAME" == "Odoo" ]; then
       touch $MODULES_TO_TEST/__init__.py
-      VERSION=$BRANCH
     fi
     IFS="/" read -a REPO <<< "${ODOO_REPO}"
     export PATH=${PATH}:${PWD}/../${REPO[1]}-${VERSION}/openerp
 
     #run pylint command
-    run_traced pylint --rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg ${MODULES_TO_TEST}
+    run_traced "pylint --rcfile=$pylint_rcfile ${MODULES_TO_TEST}"
     sts=$?
     return $sts
 }
 
 
 run_regression_test () {
-    #set -x  #debug
     if [ -f ~/dev/pypi/$1/$1/tests/all_tests ]; then
       cd ~/dev/pypi/$1/$1/tests
       ./all_tests
@@ -86,76 +81,78 @@ run_regression_test () {
       python ~/dev/pypi/$1/$1/tests/test_$1.py
       sts=$?
     else
-      sts=1
+      sts=$STS_FAILED
     fi
-    #set +x #debug
 }
 
 
-OPTOPTS=(h        C         n            R        V           v)
-OPTDEST=(opt_help opt_check opt_dry_run  opt_regr opt_version opt_verbose)
-OPTACTI=(1        "1>"      "1>"         "1>"     "*>"        1)
-OPTDEFL=(1        0         0            0        ""          0)
-OPTMETA=("help"   "check"   "do nothing" "test"   "version"   "verbose")
+OPTOPTS=(h        C         c        n            R        t         V           v)
+OPTDEST=(opt_help opt_check opt_conf opt_dry_run  opt_regr test_mode opt_version opt_verbose)
+OPTACTI=(1        "1>"      "="      "1>"         "1>"     1         "*>"        1)
+OPTDEFL=(0        0         ""        0            0       0         ""          0)
+OPTMETA=("help"   "check"   "filr"   "do nothing" "test"   "test"    "version"   "verbose")
 OPTHELP=("this help"\
  "do flake8 and pylint checks"\
+ "configuration file"\
  "do nothing (dry-run)"\
  "do regression tests"\
+ "test mode (implies dry-run)"\
  "show version"\
  "verbose mode")
-OPTARGS=(pkg_path PRJNAME)
-parseoptargs $@
+OPTARGS=(pkg PRJNAME)
 
+parseoptargs "$@"
 if [ "$opt_version" ]; then
   echo "$__version__"
   exit 0
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Run test in travis environment"\
-  "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 
-if [ "$pkg_path" ]; then
-  PKGPATH=$pkg_path
-else
-  PKGPATH=$PWD
+opts_travis
+$(init_cfg)
+$(active_cfg)
+conf_default
+link_cfg $TCONF
+init_travis
+if [ $opt_verbose -gt 1 ]; then
+  set -x
 fi
-PKGPATH=$(set_pkgpath "$PKGPATH")
-if [ ! -d $PKGPATH ]; then
-  echo "Invalid path $PKGPATH"
-  exit 1
-elif [ "$PRJNAME" != "Odoo" ]; then
-  if [ ! -d $PKGPATH/$pkgname ]; then
-    echo "Invalid path $PKGPATH/$pkgname"
-    exit 1
-  fi
+prepare_env_travis ""
+sts=$STS_SUCCESS
+if [ $test_mode -gt 0 ]; then
+  do_chkconfig
+  exit $STS_SUCCESS
 fi
+check_4_travis
 
 
-sts=0
+
 if [ $opt_verbose -gt 0 ]; then
   echo "if [ \${opt_check:-0} -gt 0 -o \"\${LINT_CHECK:-1}\" == \"1\" ]; then  #($opt_check,$LINT_CHECK)"
 fi
 if [ ${opt_check:-0} -gt 0 -o "${LINT_CHECK:-1}" == "1" ]; then
   test_flake8
-  sts=$?
-  if [ $sts -eq 0 ]; then
-    test_pylint
-    sts=$?
-  fi
+  sts_flake8=$?
+  test_pylint
+  sts_pylint=$?
+  do_summary "$sts_flake8" "$sts_pylint"
+  sts=$(($sts_flake8 || $sts_pylint))
 fi
 if [ $opt_verbose -gt 0 ]; then
   echo "if [ \${opt_regr:-0} -gt 0 -o \"\$LINT_CHECK\" != \"1\" ]; then  #($opt_regr,$LINT_CHECK)$sts"
 fi
 if [ ${opt_regr:-0} -gt 0 -o "$LINT_CHECK" != "1" ]; then
-  if [ $sts -eq 0 ]; then
+  if [ $sts -eq $STS_SUCCESS ]; then
     pkgname=$(basename $PKGPATH)
-    if [ $opt_verbose -gt 0 ]; then
-      echo "run_regression_test $pkgname"
-    fi
-    run_regression_test $pkgname
-    sts=$?
+    # if [ $opt_verbose -gt 0 ]; then
+    #   echo "run_regression_test $pkgname"
+    # fi
+    # run_regression_test $pkgname
+    #sts=$?
   fi
 fi
 exit $sts
diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -2,7 +2,7 @@
 # -*- coding: utf-8 -*-
 #
 # Common file for travis emulator scripts
-#__version__=0.1.45.3
+#__version__=0.1.46
 
 MAKEF=/opt/odoo/dev/Makefile
 DIST_CONF=./conf/.local_dist_pkg.conf
@@ -10,8 +10,53 @@ XRGI="^(.*\/|)conf\/.*sample$"
 XXXX=".pyc .log .bak .out .tmp .conf build/ dist/ conf/ .cover/ .coverage/ .git/ ~"
 
 
+opts_travis () {
+    if [ -n "$opt_conf" -a -f "$opt_conf" ]; then
+      TCONF=$opt_conf
+    else
+      TCONF=$TDIR/.travis.conf
+    fi
+    if [ -n "$pkg" ]; then
+      if [ ${pkg:0:6} == "local/" ]; then
+        PKGPATH=${pkg:6}
+        repository="local/"
+      elif [ ${pkg:0:5} == "odoo/" -o ${pkg:0:5} == "ODOO/" ]; then
+        PKGPATH=${pkg:5}
+        repository="ODOO/"
+      elif [ ${pkg:0:4} == "oca/" -o ${pkg:0:4} == "OCA/" ]; then
+        PKGPATH=${pkg:4}
+        repository="OCA/"
+      else
+        PKGPATH=$pkg
+        repository="local/"
+      fi
+      if [ -z "$PKGPATH" ]; then
+        PKGPATH=$PWD
+      fi
+    else
+      PKGPATH=$PWD
+      repository="local/"
+    fi
+    PKGPATH=$(set_pkgpath "$PKGPATH")
+    pkgname=$(basename $PKGPATH)
+    PKGPATH=$(set_pkgpath "$PKGPATH")
+    pkgname=$(basename $PKGPATH)
+    if [ "$DEV_ENVIRONMENT" == "$THIS" ]; then
+      test_mode=1
+    fi
+    if [ ${test_mode:-0} -gt 0 ]; then
+      opt_dry_run=1
+    fi
+    local x=$(A=${PWD#*/*/}; echo ${A%%/*})
+    if [ "$x" == "travis" ]; then
+      HOSTENV=travis
+    else
+      HOSTENV=local
+    fi
+}
+
 init_travis () {
-    if [ $opt_dry_run -gt 0 ]; then
+    if [ ${opt_dry_run:-0} -gt 0 ]; then
       opts_dry_run=-n
     else
       opts_dry_run=
@@ -21,19 +66,22 @@ init_travis () {
     else
       opts_upd=
     fi
+    if [ ${opt_verbose:-0} -eq 0 ]; then
+      opt_verbose=$(get_cfg_value "" "loglevel")
+    fi
     if [ $opt_verbose -ne 0 ]; then
       opts_verbose=-v
     else
       opts_verbose=
     fi
     ODOO_SETUP=$(get_cfg_value "" "ODOO_SETUP")
-    if [ "$ODOO_SETUP" -a -f $ODOO_SETUP ]; then
+    if [ -n "$ODOO_SETUP" -a -f $ODOO_SETUP ]; then
       SETUP="$ODOO_SETUP";
       REPOSNAME=$(basename $(readlink -e ..))
       if [ "$REPOSNAME" == "odoo" -o "$REPOSNAME" == "openerp" ]; then
         REPOSNAME=
       fi
-    elif [ "$ODOO_SETUP" -a "$(basename $(readlink -e ../))" == "openerp" ]; then
+    elif [ -n "$ODOO_SETUP" -a "$(basename $(readlink -e ../))" == "openerp" ]; then
       SETUP="$ODOO_SETUP";
       REPOSNAME=$(basename $(readlink -e ../..))
     elif [ -f $PKGPATH/setup.py ]; then
@@ -47,7 +95,7 @@ init_travis () {
       if [ -z "$PRJNAME" ]; then
         PRJNAME="Odoo"
       fi
-      if [ -f $ODOO_SETUP ]; then
+      if [ -f $SETUP ]; then
         prjversion=$(grep "'version' *:" $SETUP 2>/dev/null|awk -F":" '{print $2}'|tr -d "\"', \r\n")
         prjdesc=$(grep "'name' *:" $SETUP 2>/dev/null|awk -F":" '{print $2}'|tr -d "\"',\r\n")
       else
@@ -55,7 +103,7 @@ init_travis () {
         prjdesc="Unrecognized Odoo module"
       fi
     else
-      if [ "$SETUP" -a -f $SETUP ]; then
+      if [ -n "$SETUP" -a -f $SETUP ]; then
         if [ -z "$PRJNAME" ]; then
           PRJNAME=$(grep "[^a-zA-Z0-9_]name *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"', \r\n")
         fi
@@ -65,7 +113,7 @@ init_travis () {
         fi
         prjdesc=$(grep "[^a-zA-Z0-9_]description *=" $SETUP 2>/dev/null|awk -F"=" '{print $2}'|tr -d "\"',\r\n")
         if [ "$prjdesc" == "description" ]; then
-          prjdesc="Unrecognized Odoo module"
+          prjdesc="Unrecognized package"
         fi
       fi
     fi
@@ -73,12 +121,114 @@ init_travis () {
       PRJNAME=Odoo
     fi
     if [ "$PRJNAME" == "Odoo" ]; then
+      BRANCH=$(if $(echo "$PWD/"|grep "/v9/\|9.0/">/dev/null); then echo "9.0"; elif $(echo "$PWD/"|grep "/v8/\|8.0/">/dev/null); then echo "8.0"; else echo "7.0"; fi)
       if [ -z "$prjversion" ]; then
-        prjversion=$(if $(echo "$PWD/"|grep "/v9/\|9.0/">/dev/null); then echo "9.0"; elif $(echo "$PWD/"|grep "/v8/\|8.0/">/dev/null); then echo "8.0"; else echo "7.0"; fi)
+        prjversion="$BRANCH"
+      else
+        local v
+        local x=1
+        for v in 7.0 8.0 9.0; do
+          if [ ${prjversion:0:3} == "$v" -a $prjversion != "$v" ]; then
+            x=0
+          fi
+        done
+        if [ $x -gt 0 ]; then
+          prjversion="$BRANCH.$prjversion"
+        fi
+      fi
+      PRJPATH=$PKGPATH
+    else
+      PRJPATH=$PKGPATH/$PRJNAME
+    fi
+
+    if [ -z "$TOOLS_PATH" ]; then
+      if [ -d $TDIR/_travis -a ${opt_r:-0} -gt 0 ]; then
+        TOOLS_PATH=$TDIR/_travis
+      elif [ -d $HOME/dev/_travis -a ${opt_r:-0} -gt 0 ]; then
+        TOOLS_PATH=$HOME/dev/_travis
+      elif [ -d $TDIR/maintainer-quality-tools/travis ]; then
+        TOOLS_PATH=$TDIR/maintainer-quality-tools/travis
+      elif [ -d $HOME/dev/maintainer-quality-tools/travis ]; then
+        TOOLS_PATH=$HOME/dev/maintainer-quality-tools/travis
+      elif [ -d /opt/odoo/dev/maintainer-quality-tools/travis ]; then
+        TOOLS_PATH=/opt/odoo/dev/maintainer-quality-tools/travis
+      else
+        unset -v TOOLS_PATH
+      fi
+    fi
+    if [ $opt_verbose -gt 0 ]; then
+      echo "TOOLS_PATH=$TOOLS_PATH"
+    fi
+}
+
+prepare_env_travis () {
+    local action="$1"
+    if [ $(echo $PATH|grep -v "$TOOLS_PATH"  2>/dev/null) ]; then
+      export PATH=$TOOLS_PATH:$PATH
+    fi
+    export FLAKE8_CONFIG_DIR=$TOOLS_PATH/cfg
+    export LINT_CHECK=1
+    export BRANCH
+    export VERSION=$BRANCH
+    export TRAVIS_BUILD_DIR=$PKGPATH
+    export VERBOSE_MODE=$opt_verbose
+    if [ "$action" == "check" ]; then
+      export LINT_CHECK=1
+    elif [ "$action" == "test" ]; then
+      export LINT_CHECK=0
+    elif [ "$PRJNAME" != "Odoo" ]; then
+      export LINT_CHECK=1
+    else
+      unset -v LINT_CHECK
+    fi
+    repository=$repository$pkgname
+    if [ "$PRJNAME" != "Odoo" ]; then
+      export ODOO_REPO=$repository
+    fi
+    if [ -n "$opt_dpath" ]; then
+      LGITPATH="$opt_dpath"
+    else
+      if [ -n "$REPOSNAME" ]; then
+        LGITPATH=$(get_cfg_value "" "${REPOSNAME}_distpath")
+      else
+        LGITPATH=
+      fi
+      if [ -z "$LGITPATH" ]; then
+        LGITPATH=$(get_cfg_value "" "${PRJNAME}_distpath")
+      fi
+      if [ -z "$LGITPATH" ]; then
+        LGITPATH=$(get_cfg_value "" "distpath")
+      fi
+    fi
+    export LGITPATH=$(expand_path "$LGITPATH")
+    DEVPATH=$TDIR
+}
+
+check_4_travis () {
+    if [ ! -d $PKGPATH ]; then
+      echo "Invalid package path $PKGPATH"
+      exit $STS_FAILED
+    elif [ "$PRJNAME" != "Odoo" ]; then
+      if [ ! -d $PKGPATH/$pkgname ]; then
+        echo "Invalid package path $PKGPATH/$pkgname"
+        exit $STS_FAILED
       fi
     fi
 }
 
+do_chkconfig () {
+    echo "Project name   = \"$PRJNAME\""
+    echo "Tools path     = \"$DEVPATH\""
+    echo "Hosted         = \"$HOSTENV\""
+    echo "Branch         = \"$BRANCH\""
+    echo "Package name   = \"$pkgname\""
+    echo "Version        = \"$prjversion\""
+    echo "Setup file     = \"$SETUP\""
+    echo "Project path   = \"$PRJPATH\""
+    echo "Package path   = \"$PKGPATH\""
+    echo "Local git path = \"$LGITPATH\""
+    echo "Config file    = \"$TCONF\""
+}
 
 conf_default () {
     set_cfg_def "loglevel" "0"
@@ -184,10 +334,9 @@ update_dev () {
     XDPATH=$(echo "$(dirname $MAKEF)")
     ME_BOS="test_nightly .test_nightly.conf.sample"
     if [ "$1" == "travis_emulator" ]; then
-      RFLIST="autopep8_W503.py beauty .dist_pkg.conf dist_pkg please please.man please.py prjdiff topep8 travis travisrc vfcp vfdiff wok_doc wok_doc.py"
+      RFLIST="autopep8_W503.py beauty dist_pkg please please.man please.py prjdiff topep8 travis .travis.conf travisrc vfcp vfdiff wok_doc wok_doc.py"
       RDLIST="_travis/"
     elif [ "$1" == "z0lib" ]; then
-      # set -x #debug
       RFLIST="Makefile z0testrc"
       RDLIST=""
     else
@@ -204,7 +353,7 @@ update_dev () {
     fi
     if [ $xvalid -eq 0 ]; then
        echo "Invalid package $1!"
-       exit 1
+       exit $STS_FAILED
     fi
     if [ -z "$opt_sts" -o "$opt_cpush" != "-w" ]; then
       for x in $RFLIST; do
@@ -450,4 +599,22 @@ clean_dirs () {
         fi
       fi
     done
+}
+
+
+do_summary () {
+    echo "+======================================="
+    echo "|  Tests summary:"
+    echo "|---------------------------------------"
+    if [ $1 -eq $STS_SUCCESS ]; then
+      echo "| test_flake8                 Success"
+    else
+      echo "| test_flake8                 FAIL"
+    fi
+    if [ $2 -eq $STS_SUCCESS ]; then
+      echo "| test_pylint                 Success"
+    else
+      echo "| test_pylint                 FAIL"
+    fi
+    echo "+======================================="
 }
