[IMP] default verbose option

diff --git a/z0lib/tests/all_tests b/z0lib/tests/all_tests
--- a/z0lib/tests/all_tests
+++ b/z0lib/tests/all_tests
@@ -21,8 +21,7 @@ Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-
-__version__=0.1.43
+__version__=0.1.44
 
 
 test_00() {
@@ -39,10 +38,19 @@ sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
 UT1_LIST="test_wlog"
 UT_LIST="__version_1_${__version__}$RUNDIR/z0librc"
 UT_LIST="$UT_LIST test_00"
 UT_LIST="$UT_LIST test_findpkg test_run test_parseoptargs test_dict1 test_dict2 test_cfg1 test_cfg2 test_cfg3 test_cfg4 test_Makefile"
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
-exit $?
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/z0lib/tests/test_cfg3 b/z0lib/tests/test_cfg3
--- a/z0lib/tests/test_cfg3
+++ b/z0lib/tests/test_cfg3
@@ -21,7 +21,7 @@ Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.24
+__version__=0.1.25
 
 
 test_01() {
@@ -148,14 +148,28 @@ test_01() {
     test_result "find param1 OS" "Right" "$TRES"
 }
 
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
+parseoptest -l$TESTDIR/test_zerobug.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
+UT1_LIST=
+UT_LIST=
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 # This code must be execute at the main level
 eval $(init_cfg)
 eval $(active_cfg)
-Z0BUG_main_file "" ""
-exit $?
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/z0lib/tests/test_dict2 b/z0lib/tests/test_dict2
--- a/z0lib/tests/test_dict2
+++ b/z0lib/tests/test_dict2
@@ -21,7 +21,7 @@ Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.27
+__version__=0.1.29
 
 
 base_test () {
@@ -218,16 +218,30 @@ test_01() {
     base_test
 }
 
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_z0librc.log $@
+parseoptest -l$TESTDIR/test_zerobug.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
+UT1_LIST=
+UT_LIST=
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 # Follow code must be executed at main level sue bash limitations
 for i in {0..3}; do
   eval $(a_new $i)
   eval $(a_active $i)
 done
-Z0BUG_main_file "" ""
-exit $?
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/z0lib/tests/test_parseoptargs b/z0lib/tests/test_parseoptargs
--- a/z0lib/tests/test_parseoptargs
+++ b/z0lib/tests/test_parseoptargs
@@ -24,6 +24,18 @@ Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 __version__=0.1.29
 
 
+Z0BUG_setup() {
+    # This test could fail because opt_dry_run is parsed by test itself
+    # So opt_dry_run is saved and restored
+    SAVED_OPT_DRY_RUN=$opt_dry_run
+    FOUT=$TESTDIR/z0librc.out
+    FTEST=$TESTDIR/z0librc.test
+}
+
+Z0BUG_teardown() {
+    :
+}
+
 test_01() {
     local tested_opt_dry_run
     OPTOPTS=(h        n            V           v)
@@ -78,7 +90,11 @@ test_02() {
     test_result "cmd mytarget [-V]" "$opt_version" ""
     test_result "cmd mytarget [-n]" "$tested_opt_dry_run" "0"
     test_result "cmd mytarget [-p]" "$opt_path" "~/"
-    test_result "cmd mytarget [-qv]" "$opt_verbose" "-1"
+    if [[ -t 0 || -p /dev/stdin ]]; then
+      test_result "cmd mytarget [-qv]" "$opt_verbose" "0"
+    else
+      test_result "cmd mytarget [-qv]" "$opt_verbose" "1"
+    fi
 
     opt_verbose=-1
     parseoptargs "mytarget" "-q"
@@ -266,12 +282,10 @@ sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-# This test could fail because opt_dry_run is parsed by test itself
-# So opt_dry_run is saved and restored
-SAVED_OPT_DRY_RUN=$opt_dry_run
-FOUT=$TESTDIR/z0librc.out
-FTEST=$TESTDIR/z0librc.test
-
-Z0BUG_main_file "" ""
-exit $?
+UT1_LIST=
+UT_LIST=
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/z0lib/z0lib b/z0lib/z0lib
--- a/z0lib/z0lib
+++ b/z0lib/z0lib
@@ -1,21 +1,22 @@
-#! /bin/bash
 # -*- coding: utf-8 -*-
-
+# z0librc installer
+#
 THIS=$(basename $0)
-TDIR=$(echo $(readlink -f $(dirname $0)))
-if [ -f $TDIR/z0librc ]; then
-. $TDIR/z0librc
-  ZDIR=$TDIR
-elif [ -f ./z0librc ]; then
-. ./z0librc
-  ZDIR=.
-elif [ -f ~/z0librc ]; then
-. ~/z0librc
-  ZDIR=~
-else
-. /etc/z0librc
-  ZDIR=/etc
+TDIR=$(readlink -f $(dirname $0))
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
+
+__version__=0.1.44
 
 
 ##############################################################################
@@ -36,9 +37,6 @@ fi
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 ##############################################################################
-
-__version__=0.1.17
-__version__=$(grep "#__version__" $ZDIR/z0librc|head -n1|awk -F\= '{print $2}')
 
 OPTOPTS=(h        i         n            t        V           v)
 OPTDEST=(opt_help opt_xtl   opt_dry_run  opt_test opt_version opt_verbose)
@@ -63,17 +61,30 @@ fi
 if [ $opt_help -gt 0 ]
 then
   print_help "z0lib"\
-  "(C) 2015 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2017 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
+
+version=$(grep "#__version__" $Z0LIBDIR/z0librc|head -n1|awk -F\= '{print $2}')
+if [ "$version" != "$__version__" ]; then
+  echo "Warning: command version $__version__ and library version $version differ!"
+fi
 if [ "$opt_xtl" ]; then
-  if [ $opt_dry_run -eq 0 -a $EUID -eq 0 ]; then
+  if [ $opt_dry_run -ne 0 ]; then
+    _install_z0librc "-n"
+  elif [ $EUID -eq 0 ]; then
     _install_z0librc
     echo "Library z0librc V$__version__ installed"
   else
     echo "This command must be executed by root"
+    exit 1
   fi
 elif [ "opt_test" ]; then
-  ./tests/all_tests
+  if [ -d ./tests -a -f ./tests/all_tests ]; then
+    ./tests/all_tests
+  else
+    echo "Test environment not found!"
+    exit 1
+  fi
 fi
 exit 0
