[RUN] nightly commit

diff --git a/z0lib/tests/all_tests b/z0lib/tests/all_tests
--- a/z0lib/tests/all_tests
+++ b/z0lib/tests/all_tests
@@ -1,50 +1,111 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
-
+#
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
 if [ -f ./z0librc ]; then
 . ./z0librc
+. ./z0testrc
+  xtlver=$(grep "#__version__" ./z0librc|head -n1|awk -F\= '{print $2}')
   FINAL=./optargs
   TESTDIR=./tests
+  RUNDIR=./
   OK=$(_install_z0librc "-n")
 elif [ -f ../z0librc ]; then
 . ../z0librc
+. ../z0testrc
+  xtlver=$(grep "#__version__" ../z0librc|head -n1|awk -F\= '{print $2}')
   FINAL=../optargs
   TESTDIR=.
+  RUNDIR=../
   CWD=$PWD
   cd ..
   OK=$(_install_z0librc "-n")
   cd $CWD
-fi
-if [ "$OK" != "cp ./z0librc /etc/z0librc" ]; then
-  echo "Invalid library to test!!!"
-  exit 1
-fi
-
-
-export ctr=0
-$TESTDIR/test_wlog
-sts=$?
-# Test log file successfully ended; set log file to next tests
-set_tlog_file "$TESTDIR/test_z0librc.log" "" "echo"
-if [ $sts -eq 0 ]; then
-  $TESTDIR/test_findpkg
-  sts=$?
-fi
-if [ $sts -eq 0 ]; then
-  $TESTDIR/test_parseoptargs
-  sts=$?
-fi
-if [ $sts -eq 0 ]; then
-  $TESTDIR/test_dict
-  sts=$?
-fi
-if [ $sts -eq 0 ]; then
-  $TESTDIR/test_cfg
-  sts=$?
-fi
-if [ $sts -eq 0 ]; then
-  echo "Test successfully terminated"
+elif [ -f ~/z0librc ]; then
+. ~/z0librc
+. ~/dev/z0testrc
+  xtlver=$(grep "#__version__" ~/z0librc|head -n1|awk -F\= '{print $2}')
+  RUNDIR=./
 else
-  echo "Test failed!"
+. /etc/z0librc
+. ~/dev/z0testrc
+  xtlver=$(grep "#__version__" ~/z0librc|head -n1|awk -F\= '{print $2}')
+  RUNDIR=./
+fi
+RUNDIR=$(readlink -e $RUNDIR)
+TESTDIR=$(readlink -e $TESTDIR)
+
+__version__=0.1.24
+
+declare -a ctrs
+export WNoCtr=1
+parseoptest -l$TESTDIR/test_z0librc.log $@
+sts=$?
+if [ $sts -ne 127 ]; then
+  exit $sts
+fi
+opt4childs=$(inherit_opts)
+UT1_LIST="test_wlog"
+UT_LIST="test_findpkg test_parseoptargs test_dict test_cfg test_Makefile"
+saved_ctr=$ctr
+saved_max_test=$max_test
+saved_opt_verbose=$opt_verbose
+saved_opt_dry_run=$opt_dry_run
+saved_LNEW=$LNEW
+saved_LECHO=$LECHO
+
+ix=0
+sts=0
+WLOGCMD=echo
+FLOG=
+# pass 1: count for # of tests
+max_test=0
+# 2 test are for version id
+exec_tests_4_count "version" "2"
+exec_tests_4_count "$UT1_LIST"
+exec_tests_4_count "$UT_LIST"
+if [ ${saved_max_test:-0} -gt 0 ]; then
+  max_test=$saved_max_test
+elif [ ${opt_noctr:-0} -gt 0 ]; then
+  max_test=
+fi
+#echo "4>i=$ix;m=$max_test;c=${ctrs[@]}<<" #debug
+# pass 2: execute tests
+ctr=$saved_ctr
+opt_verbose=$saved_opt_verbose
+opt_dry_run=$saved_opt_dry_run
+LNEW=$saved_LNEW
+LECHO=$saved_LECHO
+if [ "$LECHO" == "echo" ]; then
+  WLOGCMD="wecho-1"
+else
+  WLOGCMD="wecho-0"
+fi
+FLOG=
+if [ ${opt_noctr:-0} -eq 0 -a ${ctr:-0} -gt 0 -a ${saved_max_test:-0} -eq 0 ]; then
+   let max_test="$max_test"+"$ctr"
+fi
+if [ ${opt_dry_run:-0} -eq 0 ]; then
+  ix=0
+  sts=0
+  # 2 test are for version id
+  ci-test "check for lib version (1)" "$xtlver" "$__version__"
+  ci-test "check for lib version (2)" "cp ./z0librc /etc/z0librc" "$OK"
+  ctr=$saved_ctr
+  exec_all_tests "version" "2"
+  # test w/o tracelog
+  exec_all_tests "$UT1_LIST"
+  # Test log file successfully ended; set log file to next tests
+  WLOGCMD=
+  set_tlog_file "$TESTDIR/test_z0librc.log" "" "$LECHO"
+  exec_all_tests "$UT_LIST"
+  if [ $sts -eq 0 ]; then
+    echo "Test successfully terminated"
+  else
+    echo "Test failed!"
+  fi
+else
+  echo "$max_test"
 fi
 exit $sts
diff --git a/z0lib/tests/test_parseoptargs b/z0lib/tests/test_parseoptargs
--- a/z0lib/tests/test_parseoptargs
+++ b/z0lib/tests/test_parseoptargs
@@ -1,42 +1,42 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
+#
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
 if [ -f ./z0librc ]; then
 . ./z0librc
-FINAL=./optargs
-TESTDIR=./tests
+. ./z0testrc
+  TESTDIR=./tests
+  RUNDIR=./
 elif [ -f ../z0librc ]; then
 . ../z0librc
-FINAL=../optargs
-TESTDIR=.
+. ../z0testrc
+  TESTDIR=.
+  RUNDIR=../
+elif [ -f ~/z0librc ]; then
+. ~/z0librc
+. ~/dev/z0testrc
+  TESTDIR=./tests
+  RUNDIR=./
+else
+. /etc/z0librc
+. ~/dev/z0testrc
+  TESTDIR=./tests
+  RUNDIR=./
 fi
+RUNDIR=$(readlink -e $RUNDIR)
+TESTDIR=$(readlink -e $TESTDIR)
 
-test_result () {
-  ((ctr++))
-  if [ $ctr -gt 10 ]; then
-    wlog "Test $ctr: $1"
-  else
-    echo "Test $ctr: $1"
-  fi
-  if [ "$4" ]; then
-    if [ "$($4 $2 $3)" ]; then
-      echo "Test failed: $4 '$2' '$3'"
-      exit 1
-    fi
-  else
-    if [ "$2" != "$3" ]; then
-      echo "Test failed: expected '$2', found '$3'"
-      exit 1
-    fi
-  fi
-}
-
-# Previous test_wlog executed 18 unit test
-if [ ${ctr:-0} -eq 0 ]; then
-  ctr=18
+__version__=0.1.23
+parseoptest -l$TESTDIR/test_z0librc.log $@
+sts=$?
+if [ $sts -ne 127 ]; then
+  exit $sts
 fi
-if [ -z "$FLOG" ]; then
-  set_tlog_file "$TESTDIR/test_z0librc.log" "" "echo"
-fi
+sts=0
+# This test could fail because opt_dry_run is parsed by test
+# So opt_dry_run is saved and restored
+saved_opt_dry_run=$opt_dry_run
 
 FOUT=$TESTDIR/z0librc.out
 FTEST=$TESTDIR/z0librc.test
@@ -53,10 +53,12 @@ OPTHELP=("this help"\
 OPTARGS=()
 
 parseoptargs "-V"
-test_result "cmd -h" "$opt_help" "0"
-test_result "cmd -V" "$opt_version" "-V"
-test_result "cmd -n" "$opt_dry_run" "0"
-test_result "cmd -v" "$opt_verbose" "0"
+tested_opt_dry_run=$opt_dry_run
+opt_dry_run=$saved_opt_dry_run
+ci-test "cmd -h" "$opt_help" "0"
+ci-test "cmd -V" "$opt_version" "-V"
+ci-test "cmd -n" "$tested_opt_dry_run" "0"
+ci-test "cmd -v" "$opt_verbose" "0"
 echo "Usage: test_parseoptargs [-hnVv]">$FTEST
 echo "Unit test">>$FTEST
 echo " -h             this help">>$FTEST
@@ -65,7 +67,7 @@ echo " -V             show version">>$FTEST
 echo " -v             verbose mode">>$FTEST
 print_help "Unit test"\
   "">$FOUT
-test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
 
 OPTOPTS=(h        n            V           p)
 OPTDEST=(opt_help opt_dry_run  opt_version opt_path)
@@ -79,10 +81,12 @@ OPTHELP=("this help"\
 OPTARGS=(tgt)
 
 parseoptargs "mytarget"
-test_result "cmd -h mytarget" "$opt_help" "0"
-test_result "cmd -V mytarget" "$opt_version" ""
-test_result "cmd -n mytarget" "$opt_dry_run" "0"
-test_result "cmd -v mytarget" "$opt_path" "~/"
+tested_opt_dry_run=$opt_dry_run
+opt_dry_run=$saved_opt_dry_run
+ci-test "cmd -h mytarget" "$opt_help" "0"
+ci-test "cmd -V mytarget" "$opt_version" ""
+ci-test "cmd -n mytarget" "$tested_opt_dry_run" "0"
+ci-test "cmd -v mytarget" "$opt_path" "~/"
 echo "Usage: test_parseoptargs [-hnV][-p path] tgt">$FTEST
 echo "Unit test">>$FTEST
 echo " -h             this help">>$FTEST
@@ -91,14 +95,16 @@ echo " -V             show version">>$FTEST
 echo " -p path        path">>$FTEST
 print_help "Unit test"\
   "">$FOUT
-test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
 
 parseoptargs "-p" "./mypath" "yourtarget"
-test_result "cmd -h ./mypath yourtarget" "$opt_help" "0"
-test_result "cmd -V ./mypath yourtarget" "$opt_version" ""
-test_result "cmd -n ./mypath yourtarget" "$opt_dry_run" "0"
-test_result "cmd -v ./mypath yourtarget" "$opt_path" "./mypath"
-test_result "cmd -v ./mypath yourtarget" "$tgt" "yourtarget"
+tested_opt_dry_run=$opt_dry_run
+opt_dry_run=$saved_opt_dry_run
+ci-test "cmd -h ./mypath yourtarget" "$opt_help" "0"
+ci-test "cmd -V ./mypath yourtarget" "$opt_version" ""
+ci-test "cmd -n ./mypath yourtarget" "$tested_opt_dry_run" "0"
+ci-test "cmd -v ./mypath yourtarget" "$opt_path" "./mypath"
+ci-test "cmd -v ./mypath yourtarget" "$tgt" "yourtarget"
 echo "Usage: test_parseoptargs [-hnV][-p path] tgt">$FTEST
 echo "Unit test">>$FTEST
 echo " -h             this help">>$FTEST
@@ -107,7 +113,7 @@ echo " -V             show version">>$FTEST
 echo " -p path        path">>$FTEST
 print_help "Unit test"\
   "">$FOUT
-test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
 
 
 OPTOPTS=(h        n            O       p        V)
@@ -123,12 +129,14 @@ OPTHELP=("this help"\
 OPTARGS=(tgt)
 
 parseoptargs "mytarget"
-test_result "cmd -h mytarget" "$opt_help" "0"
-test_result "cmd -V mytarget" "$opt_version" ""
-test_result "cmd -n mytarget" "$opt_dry_run" "0"
-test_result "cmd -v mytarget" "$opt_path" "~/"
-test_result "cmd -v mytarget" "$opt_own" "$USER"
-test_result "cmd -v mytarget" "$tgt" "mytarget"
+tested_opt_dry_run=$opt_dry_run
+opt_dry_run=$saved_opt_dry_run
+ci-test "cmd -h mytarget" "$opt_help" "0"
+ci-test "cmd -V mytarget" "$opt_version" ""
+ci-test "cmd -n mytarget" "$tested_opt_dry_run" "0"
+ci-test "cmd -v mytarget" "$opt_path" "~/"
+ci-test "cmd -v mytarget" "$opt_own" "$USER"
+ci-test "cmd -v mytarget" "$tgt" "mytarget"
 echo "Usage: test_parseoptargs [-hn][-O own][-p path][-V] tgt">$FTEST
 echo "Unit test">>$FTEST
 echo " -h             this help">>$FTEST
@@ -138,8 +146,12 @@ echo " -p path        path">>$FTEST
 echo " -V             show version">>$FTEST
 print_help "Unit test"\
   "">$FOUT
-test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
 
 if [ -f $FOUT ]; then rm -f $FOUT; fi
 if [ -f $FTEST ]; then rm -f $FTEST; fi
-exit 0
+
+if [ ${opt_dry_run:-0} -ne 0 ]; then
+  echo "$ctr"
+fi
+exit $sts
diff --git a/z0lib/tests/test_wlog b/z0lib/tests/test_wlog
--- a/z0lib/tests/test_wlog
+++ b/z0lib/tests/test_wlog
@@ -1,66 +1,92 @@
 #! /bin/bash
 # -*- coding: utf-8 -*-
-
+#
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
 if [ -f ./z0librc ]; then
 . ./z0librc
+. ./z0testrc
   TESTDIR=./tests
+  RUNDIR=./
 elif [ -f ../z0librc ]; then
 . ../z0librc
+. ../z0testrc
   TESTDIR=.
+  RUNDIR=../
+elif [ -f ~/z0librc ]; then
+. ~/z0librc
+. ~/dev/z0testrc
+  TESTDIR=./tests
+  RUNDIR=./
+else
+. /etc/z0librc
+. ~/dev/z0testrc
+  TESTDIR=./tests
+  RUNDIR=./
 fi
+RUNDIR=$(readlink -e $RUNDIR)
+TESTDIR=$(readlink -e $TESTDIR)
 
-test_result () {
-  ((ctr++))
-  if [ $ctr -gt 10 ]; then
-    wlog "Test $ctr: $1"
-  else
-    echo "Test $ctr: $1"
-  fi
-  if [ "$4" ]; then
-    if [ "$($4 $2 $3)" ]; then
-      echo "Test failed: $4 '$2' '$3'"
-      exit 1
-    fi
-  else
-    if [ "$2" != "$3" ]; then
-      echo "Test failed: expected '$2', found '$3'"
-      exit 1
-    fi
-  fi
-}
+__version__=0.1.23
+parseoptest -l$TESTDIR/test_z0librc.log $@
+sts=$?
+if [ $sts -ne 127 ]; then
+  exit $sts
+fi
+sts=0
 
-
-ctr=0
+if [ "$LECHO" == "echo" ]; then
+  WLOGCMD="wecho-1"
+else
+  WLOGCMD="wecho-0"
+fi
 FLOG=
-set_tlog_file "test_z0librc.log"
-test_result "set logfile" "$HOME/test_z0librc.log" "$FLOG"
-test_result "set logfile" "#" "$FLOG_ECHO"
+FLOGTMP="test_z0librc.log"
+set_tlog_file "$FLOGTMP"
+ci-test "set logfile (1)" "$HOME/$FLOGTMP" "$FLOG"
+ci-test "set logfile (2)" "#" "$FLOG_ECHO"
 
-touch $HOME/test_z0librc.log
-if [ ! -f $HOME/test_z0librc.log ]; then
-  echo "Test failed due internal error!!"
-  exit 1
+if [ ${opt_dry_run:-0} -eq 0 ]; then
+  touch $HOME/$FLOGTMP
+  if [ ! -f $HOME/$FLOGTMP ]; then
+    echo "Test failed due impossible internal error!!"
+    exit 1
+  fi
+  set_tlog_file "$FLOGTMP" "new"
+  if [ -f $HOME/test_z0librc.log ]; then TRES="1"; else TRES="0"; fi
 fi
-set_tlog_file "test_z0librc.log" "new"
-if [ -f $HOME/test_z0librc.log ]; then TRES="1"; else TRES="0"; fi
-test_result "rm logfile" "0" "$TRES"
-test_result "rm logfile" "#" "$FLOG_ECHO"
+ci-test "rm logfile (1)" "0" "$TRES"
+ci-test "rm logfile (2)" "#" "$FLOG_ECHO"
 
-set_tlog_file "./test_z0librc.log" "new"
-test_result "set logfile" "./test_z0librc.log" "$FLOG"
-test_result "set logfile" "#" "$FLOG_ECHO"
+FLOGTMP="./test_tmp.log"
+set_tlog_file "$FLOGTMP" "new"
+ci-test "set logfile (3)" "$FLOGTMP" "$FLOG"
+ci-test "set logfile (4)" "#" "$FLOG_ECHO"
 
-set_tlog_file "$TESTDIR/test_z0librc.log" "new"
-test_result "set logfile" "$TESTDIR/test_z0librc.log" "$FLOG"
-test_result "set logfile" "#" "$FLOG_ECHO"
+FLOGTMP="$TESTDIR/test_tmp.log"
+set_tlog_file "$FLOGTMP" "new"
+ci-test "set logfile (5)" "$FLOGTMP" "$FLOG"
+ci-test "set logfile (6)" "#" "$FLOG_ECHO"
 
-set_tlog_file "$TESTDIR/test_z0librc.log" "new" "echo"
-test_result "set logfile" "$TESTDIR/test_z0librc.log" "$FLOG"
-test_result "set logfile" "echo" "$FLOG_ECHO"
+set_tlog_file "$FLOGTMP" "new" "echo"
+ci-test "set logfile (7)" "$FLOGTMP" "$FLOG"
+ci-test "set logfile (8)" "echo" "$FLOG_ECHO"
+if [ -f $FLOGTMP ]; then rm -f $FLOGTMP; fi
 
-set_tlog_file "$TESTDIR/test_z0librc.log" "" "echo"
-wlog "Since now, test messages are store in $FLOG"
-test_result "echoing with wlog" "$TESTDIR/test_z0librc.log" "$FLOG"
-test_result "echoing with wlog" "echo" "$FLOG_ECHO"
 
-exit 0
+WLOGCMD=
+set_tlog_file "$logfn" "$LNEW" "$LECHO"
+if [ ${opt_dry_run:-0} -eq 0 ]; then
+  wlog "Since now, test messages are store in $FLOG"
+fi
+ci-test "echoing with wlog (1)" "$TESTDIR/test_z0librc.log" "$FLOG"
+if [ "$LECHO" == "echo" ]; then
+  ci-test "echoing with wlog (2)" "echo" "$FLOG_ECHO"
+else
+  ci-test "echoing with wlog (2)" "#" "$FLOG_ECHO"
+fi
+
+if [ ${opt_dry_run:-0} -ne 0 ]; then
+  echo "$ctr"
+fi
+exit $sts
