[IMP] Stable versions

diff --git a/z0lib/tests/test_params b/z0lib/tests/test_params
--- a/z0lib/tests/test_params
+++ b/z0lib/tests/test_params
@@ -4,13 +4,13 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
-# Based on template 1.0.2.7
+# Based on template 1.0.4.2
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
 HOME_DEV="$HOME/devel"
 [[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
-PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ -z $PYPATH ]] && PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEV"'\nimport os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nH=o.expanduser('~')\nT=j(H,'tools')\nR=j(H,'pypi') if b(D)=='venv_tools' else j(H,D,'pypi')\nW=D if b(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'scripts')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C) in ('scripts','tests','travis','_travis'):\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==d(C) and f(j(C,'..','setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+[os.getcwd()]+P\np=set()\npa=p.add\np=[x for x in L if x and x.startswith((H,D,C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
@@ -24,11 +24,21 @@ if [[ -z "$Z0LIBDIR" ]]; then
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
+
+TRAVISLIBDIR=$(findpkg travisrc "$PYPATH" "travis_emulator")
+if [[ -z "$TRAVISLIBDIR" ]]; then
+  echo "Library file travisrc not found!"
+  exit 72
+fi
+. $TRAVISLIBDIR
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TRAVISLIBDIR=$TRAVISLIBDIR"
+
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
 RUNDIR=$(readlink -e $TESTDIR/..)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
-Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
+
+Z0TLIBDIR=$(findpkg z0testrc "$PYPATH ." "zerobug")
 if [[ -z "$Z0TLIBDIR" ]]; then
   echo "Library file z0testrc not found!"
   exit 72
@@ -48,28 +58,119 @@ RED="\e[1;31m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
+__version__=1.0.6
 
-__version__=1.0.5
-
+test_common() {
+    local res pypath tag tres
+    tag="RUNDIR"
+    [[ $1 =~ ^$HOME/devel/venv/bin ]] && tag="VENV"
+    [[ $1 =~ ^$HOME/devel/pypi/z0lib/z0lib ]] && tag="DEVEL"
+    [[ $1 =~ ^$TESTDIR ]] && tag="TESTDIR"
+    [[ -f ./travisrc ]] && rm -f ./travisrc
+    res=$($1 PYPATH|cut -f1 -d" ")
+    test_result "$PWD> $tag/simulate_cmd PYPATH" "$res" "$(dirname $1)"
+    res=$($1 Z0LIBDIR)
+    tres="$RUNDIR"
+    [[ $tag == "DEVEL" ]] && tres="$HOME/devel/pypi/z0lib/z0lib"
+    [[ $tag == "VENV" ]] && tres="$HOME/devel/venv/bin"
+    test_result "$PWD> $tag/simulate_cmd Z0LIBDIR" "$res" "$tres"
+    # travisrc is found in python site packages
+    pypath=$(echo "import sys;print([x for x in sys.path if 'site-packages' in x][0])"|python)
+    res=$($1 PYPATH|grep -Eo $pypath/travis_emulator)
+    test_result "$PWD> $tag/simulate_cmd PYPATH/travis_emulator" "$res" "$pypath/travis_emulator"
+    res=$($1 TRAVISLIBDIR)
+    test_result "$PWD> $tag/simulate_cmd TRAVISLIBDIR" "$res" "$pypath/travis_emulator/travisrc"
+    # Now travisrc should be found in current directory
+    cp $HOME/tools/travis_emulator/travisrc ./
+    res=$($1 TRAVISLIBDIR)
+    if [[ $2 != "N" ]]; then
+      test_result "$PWD> $tag/simulate_cmd TRAVISLIBDIR (2)" "$res" "$PWD/travisrc"
+    else
+      test_result "$PWD> $tag/simulate_cmd TRAVISLIBDIR (2)" "$res" "$pypath/travis_emulator/travisrc"
+    fi
+    rm -f ./travisrc
+    res=$($1 PKGNAME)
+    test_result "$PWD> $tag/simulate_cmd PKGNAME" "$res" "z0lib"
+    res=$($1 PKGPATH)
+    tres="$TRAVIS_BUILD_DIR"
+    [[ $tag == "DEVEL" ]] && tres="$HOME/devel/pypi/z0lib"
+    [[ $tag == "VENV" ]] && tres="$HOME/devel/pypi/z0lib"
+    test_result "$PWD> $tag/simulate_cmd PKGPATH" "$res" "$tres"
+    res=$($1 PRJNAME)
+    test_result "$PWD> $tag/simulate_cmd PRJNAME" "$res" "z0lib"
+    res=$($1 PRJPATH)
+    tres="$TRAVIS_BUILD_DIR"
+    [[ $tag == "DEVEL" ]] && tres="$HOME/devel/pypi/z0lib/z0lib"
+    [[ $tag == "VENV" ]] && tres="$HOME/devel/pypi/z0lib/z0lib"
+    test_result "$PWD> $tag/simulate_cmd PRJPATH" "$res" "$tres"
+}
 
 test_01() {
     local res
     cd $TESTDIR
-    res=$($TESTDIR/simulate_cmd PKGNAME)
-    test_result "$TESTDIR/simulate_cmd PKGNAME" "$res" "z0lib"
-    res=$($TESTDIR/simulate_cmd PKGPATH)
-    # test_result "$TESTDIR/simulate_cmd PKGPATH" "$res" "$TRAVIS_BUILD_DIR/z0lib"
-    res=$($TESTDIR/simulate_cmd PRJNAME)
-    test_result "$TESTDIR/simulate_cmd PRJNAME" "$res" "z0lib"
-    res=$($TESTDIR/simulate_cmd PRJPATH)
-    # test_result "$TESTDIR/simulate_cmd PRJPATH" "$res" "$TRAVIS_BUILD_DIR/z0lib"
+    res=$($TESTDIR/simulate_cmd THIS)
+    test_result "$PWD> TESTDIR/simulate_cmd THIS" "$res" "simulate_cmd"
+    res=$($TESTDIR/simulate_cmd TDIR)
+    test_result "$PWD> TESTDIR/simulate_cmd TDIR" "$res" "$TESTDIR"
+    res=$($TESTDIR/simulate_cmd HOME_DEV)
+    test_result "$PWD> TESTDIR/simulate_cmd HOME_DEV" "$res" "$HOME/devel"
+    test_common $TESTDIR/simulate_cmd
+    cd $RUNDIR
+    test_common $TESTDIR/simulate_cmd
+    mv $TESTDIR/simulate_cmd $RUNDIR/simulate_cmd
+    cd $TESTDIR
+    test_common $RUNDIR/simulate_cmd "N"
+    cd $RUNDIR
+    test_common $RUNDIR/simulate_cmd
+    mv $RUNDIR/simulate_cmd $HOME/tools/z0lib/simulate_cmd
+    cd $HOME/tools/z0lib
+    res=$($HOME/tools/z0lib/simulate_cmd TDIR)
+    test_result "$PWD> TOOLS/z0lib/simulate_cmd TDIR" "$res" "$HOME/tools/z0lib"
+    res=$($HOME/tools/z0lib/simulate_cmd PRJNAME)
+    # TODO> error
+    # test_result "$PWD> TOOLS/z0lib/simulate_cmd PRJNAME" "$res" "z0lib"
+    res=$($HOME/tools/z0lib/simulate_cmd PKGNAME)
+    # TODO> error
+    # test_result "$PWD> TOOLS/z0lib/simulate_cmd PKGNAME" "$res" "z0lib"
+    res=$($HOME/tools/z0lib/simulate_cmd PRJPATH)
+    test_result "$PWD> TOOLS/z0lib/simulate_cmd PRJPATH" "$res" "$HOME/tools/z0lib"
+    # TODO> error
+    res=$($HOME/tools/z0lib/simulate_cmd PKGPATH)
+    # test_result "$PWD> TOOLS/z0lib/simulate_cmd PKGPATH" "$res" "$HOME/tools"
+    mkdir -p $HOME/devel/pypi/z0lib
+    cp -R $HOME/build/local/z0lib/ $HOME/devel/pypi/z0lib/
+    mv $HOME/devel/pypi/z0lib/z0lib/scripts/setup.info $HOME/devel/pypi/z0lib/setup.py
+    mkdir -p $HOME/devel/pypi/travis_emulator/
+    cp -R $HOME/tools/travis_emulator/ $HOME/devel/pypi/travis_emulator/
+    mv $HOME/devel/pypi/travis_emulator/travis_emulator/setup.py $HOME/devel/pypi/travis_emulator/setup.py
+    cd $HOME/devel/pypi/z0lib/z0lib
+    mv $HOME/tools/z0lib/simulate_cmd $HOME/devel/pypi/z0lib/z0lib/simulate_cmd
+    # [[ -f $HOME/devel/pypi/z0lib/z0lib/travisrc ]] && rm -f $HOME/devel/pypi/z0lib/z0lib/travisrc
+    test_common $HOME/devel/pypi/z0lib/z0lib/simulate_cmd
+    mv $HOME/devel/pypi/z0lib/z0lib/simulate_cmd $HOME/devel/venv/bin/simulate_cmd
+    test_common $HOME/devel/venv/bin/simulate_cmd "N"
+    mv $HOME/devel/venv/bin/simulate_cmd $TESTDIR/simulate_cmd
 }
 
 Z0BUG_setup() {
-    rm -f $TESTDIR/simulate_cmd
+    local f
+    [[ -f $TESTDIR/simulate_cmd ]] && rm -f $TESTDIR/simulate_cmd
+    [[ -f $HOME/devel/venv/bin/simulate_cmd ]] && rm -f $HOME/devel/venv/bin/simulate_cmd
+    [[ -d $HOME/devel/pypi/z0lib ]] && rm -fR $HOME/devel/pypi/z0lib
+    [[ -d $HOME/devel/pypi/travis_emulator ]] && rm -fR $HOME/devel/pypi/travis_emulator
     # echo "set -x" >>$TESTDIR/simulate_cmd
     while IFS= read -r line || [[ -n "$line" ]]; do
+      [[ $line =~ ^DIST_CONF= ]] && break
       echo "$line" >>$TESTDIR/simulate_cmd
+    done <$0
+    echo "#############################" >>$TESTDIR/simulate_cmd
+    f=0
+    while IFS= read -r line || [[ -n "$line" ]]; do
+      [[ $line =~ ^\[\[\ -x\ \$TDIR/../bin/python ]] && f=1
+      [[ $line =~ ^DIST_CONF= ]] && f=1
+      [[ $f -ne 0 && $line =~ ^\[\[\ -z\ \$PYPATH ]] && line="${line:20}"
+      [[ $f -ne 0 ]] && echo "$line" >>$TESTDIR/simulate_cmd
+      [[ $f -ne 0 && $line =~ ^done ]] && echo -e "#############################\n" >>$TESTDIR/simulate_cmd && f=0
       [[ $line =~ ^__version__= ]] && break
     done <$0
     echo "" >>$TESTDIR/simulate_cmd
@@ -77,10 +178,24 @@ Z0BUG_setup() {
     chmod +x $TESTDIR/simulate_cmd
 }
 
+Z0BUG_teardown() {
+    rm -f $TESTDIR/simulate_cmd
+}
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_..log "$@"
+parseoptest -l$TESTDIR/test_z0lib.log "$@" "-J"
 sts=$?
 [[ $sts -ne 127 ]] && exit $sts
+if [ ${opt_tjLib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg travisrc "$PYPATH ." "travis_emulator")
+  if [[ -z "$TRAVISLIBDIR" ]]; then
+    echo "Library file travisrc not found!"
+    exit 72
+  fi
+  . $TRAVISLIBDIR
+  [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TRAVISLIBDIR=$TRAVISLIBDIR"
+fi
+
 
 UT1_LIST=
 UT_LIST=
