[RUN] test nightly

diff --git a/z0lib/tests/test_wlog b/z0lib/tests/test_wlog
--- a/z0lib/tests/test_wlog
+++ b/z0lib/tests/test_wlog
@@ -11,13 +11,18 @@ for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
     break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.1.24
+__version__=0.1.25
+
 
 test_01() {
     if [ "$LECHO" == "echo" ]; then
diff --git a/zerobug/tests/zerobug_test_02 b/zerobug/tests/zerobug_test_02
--- a/zerobug/tests/zerobug_test_02
+++ b/zerobug/tests/zerobug_test_02
@@ -4,21 +4,25 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. ~/dev" "_travis")
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. ~/dev")
+Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
-__version__=0.2.3
+__version__=0.2.4
 
 
 Z0BUG_init
@@ -30,7 +34,7 @@ fi
 
 UT1_LIST=""
 UT_LIST="__version_0_${__version__}$Z0TLIBDIR/z0testrc"
-UT_LIST="$UT_LIST __version_1_0.1.40.8$Z0LIBDIR/z0librc"
+UT_LIST="$UT_LIST __version_1_0.1.42$Z0LIBDIR/z0librc"
 UT_LIST="$UT_LIST __version_V_0.2.0$TESTDIR/dummy_01.py"
 UT_LIST="$UT_LIST __version_v_0.2.1$TESTDIR/dummy_01.py"
 UT_LIST="$UT_LIST __version_P_0.2.2$TESTDIR/dummy_01.py"
