[IMP] zerobug new featues

diff --git a/z0lib/tests/test_Makefile b/z0lib/tests/test_Makefile
--- a/z0lib/tests/test_Makefile
+++ b/z0lib/tests/test_Makefile
@@ -1,62 +1,23 @@
-#! /bin/bash
 # -*- coding: utf-8 -*-
-# Regression tests for submodule of z0lib module
-#
-## TODO: test TESTFILE and/or TESTPATH
+# Regression tests on z0lib
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -d $TDIR/tests ]; then
-  TESTDIR=$TDIR/tests
-  RUNDIR=$TDIR
-elif [ -d $TDIR/../tests ]; then
-  TESTDIR=$TDIR
-  RUNDIR=$TDIR/..
-elif [ -d ./tests ]; then
-  TESTDIR=./tests
-  RUNDIR=./
-elif [ -d ../tests ]; then
-  TESTDIR=./
-  RUNDIR=../
-else
-  TESTDIR=$TDIR
-  RUNDIR=$TDIR/..
-fi
-if [ -d $TDIR/_travis ]; then
-  TRAVISDIR=$TDIR
-elif [ -d $TDIR/../_travis ]; then
-  TRAVISDIR=$TDIR/..
-elif [ -d ./_travis ]; then
-  TRAVISDIR=./
-elif [ -d ../_travis ]; then
-  TRAVISDIR=../
-else
-  TRAVISDIR=~/dev/_travis
-fi
-if [ -e $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -e ./z0librc ]; then
-. ./z0librc
-elif [ -e ../z0librc ]; then
-. ../z0librc
-elif [ -e ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
-fi
-if [ -e $TDIR/z0testrc ]; then
-. $TDIR/z0testrc
-elif [ -e ./z0testrc ]; then
-. ./z0testrc
-elif [ -e ../z0testrc ]; then
-. ../z0testrc
-else
-. ~/dev/z0testrc
-fi
-TESTDIR=$(readlink -e $TESTDIR)
-RUNDIR=$(readlink -e $RUNDIR)
-TRAVISDIR=$(readlink -e $TRAVISDIR)
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+  fi
+done
+TESTDIR=$(findpkg "" "$TDIR . .." "tests")
+RUNDIR=$(readlink -e $TESTDIR/..)
+Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+. $Z0TLIBDIR
+Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
+
+__version__=0.1.83
 
 testpath () {
   if [ ${opt_dry_run:-0} -eq 0 ]; then
@@ -65,129 +26,129 @@ testpath () {
     fi
     cd $1
     p=$(make -f $MAKEF chkconfig|grep "Hosted"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Hosted" "local" "$p"
+    test_result "$1: Hosted" "local" "$p"
     p2=$(make -f $MAKEF chkconfig|grep "Project name"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Project name" "$2" "$p2"
+    test_result "$1: Project name" "$2" "$p2"
     p3=$(make -f $MAKEF chkconfig|grep "Branch"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Branch" "$3" "$p3"
+    test_result "$1: Branch" "$3" "$p3"
     p4=$(make -f $MAKEF chkconfig|grep "Package name"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Package name" "$4" "$p4"
+    test_result "$1: Package name" "$4" "$p4"
     p5=$(make -f $MAKEF chkconfig|grep "Version"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Version" "$5" "$p5"
+    test_result "$1: Version" "$5" "$p5"
     p6=$(make -f $MAKEF chkconfig|grep "Setup file"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Setup file" "$6" "$p6"
+    test_result "$1: Setup file" "$6" "$p6"
     p7=$(make -f $MAKEF chkconfig|grep "Project path"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Project path" "$7" "$p7"
+    test_result "$1: Project path" "$7" "$p7"
     p8=$(make -f $MAKEF chkconfig|grep "Package path"|awk -F"=" '{print $2}'|tr -d "\"', \r")
-    ci-test "$1: Package path" "$8" "$p8"
+    test_result "$1: Package path" "$8" "$p8"
   else
     for i in {1..8}; do
-      ci-test "dry_run" "" ""
+      test_result "dry_run" "" ""
    done
   fi
 }
 
+test_01() {
+    MAKEF=/opt/odoo/dev/pypi/z0lib/z0lib/Makefile
+    export DEVPATH=/opt/odoo/dev
+    OS_VER=0.2.11
+    BB_VER=7.0.0.2
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      if [ ${opt_verbose:-0} -gt 0 ]; then
+        echo "**************************************************************************************"
+        echo "Warning: test could fail if os version is not $OS_VER or l10n_it_bbone is not $BB_VER"
+      fi
+    fi
+    xtlver=$(grep "__version__" $MAKEF|head -n1|awk -F\= '{print $2}')
+    test_result "Makefile version" "$__version__" "$xtlver"
 
-__version__=0.1.83
+    WD=/opt/openerp/7.0/zeroincombenze
+    if [ -d $WD ]; then
+      p2=Odoo
+      p3=7.0
+      p4="()"
+      p5=$p3
+      p6=__openerp__.py
+      p7=/opt/openerp/7.0/zeroincombenze
+      p8=$p7/
+      testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+    fi
+
+    WD=/opt/openerp/7.0/zeroincombenze/l10n_it_bbone
+    if [ -d $WD ]; then
+      p2=Odoo
+      p3=7.0
+      p4="l10n_it_bbone(ItalianLocalization-Base)"
+      p5=$BB_VER
+      p6=__openerp__.py
+      p7=/opt/openerp/7.0/zeroincombenze
+      p8=$WD/
+      testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+    fi
+
+    WD=/opt/odoo/8.0
+    p2=Odoo
+    p3=8.0
+    p4="()"
+    p5=$p3
+    p6=__openerp__.py
+    p7=$WD
+    p8=$p7/
+    testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+
+    WD=/opt/odoo/7.0
+    p2=Odoo
+    p3=7.0
+    p4="()"
+    p5=$p3
+    p6=__openerp__.py
+    p7=$WD
+    p8=$p7/
+    testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+
+    WD=/opt/odoo/dev/pypi/os0
+    p2=os0
+    p3=
+    p4="$p2($p2)"
+    p5=$OS_VER
+    p6=/opt/odoo/dev/pypi/os0/setup.py
+    p7=/opt/odoo/dev/pypi/os0/os0
+    p8=/opt/odoo/dev/pypi/os0/
+    testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+
+    WD=/opt/odoo/dev/pypi/os0/os0
+    p2=os0
+    p3=
+    p4="$p2($p2)"
+    p5=$OS_VER
+    p6=/opt/odoo/dev/pypi/os0/setup.py
+    p7=/opt/odoo/dev/pypi/os0/os0
+    p8=/opt/odoo/dev/pypi/os0/
+    testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+
+    WD=/opt/odoo/7.0/openerp/workflow
+    p2=Odoo
+    p3=7.0
+    p4="workflow()"
+    p5=$p3
+    p6=__openerp__.py
+    p7=/opt/odoo/7.0/openerp
+    p8=$p7/workflow/
+    testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
+
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      if [ ${opt_verbose:-0} -gt 0 ]; then
+        echo "**************************************************************************************"
+      fi
+    fi
+}
+
+Z0BUG_init
 parseoptest -l$TESTDIR/test_z0librc.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-sts=0
 
-MAKEF=/opt/odoo/dev/pypi/z0lib/z0lib/Makefile
-export DEVPATH=/opt/odoo/dev
-OS_VER=0.2.11
-BB_VER=7.0.0.2
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  if [ ${opt_verbose:-0} -gt 0 ]; then
-    echo "**************************************************************************************"
-    echo "Warning: test could fail if os version is not $OS_VER or l10n_it_bbone is not $BB_VER"
-  fi
-fi
-xtlver=$(grep "__version__" $MAKEF|head -n1|awk -F\= '{print $2}')
-ci-test "Makefile version" "$__version__" "$xtlver"
-
-WD=/opt/openerp/7.0/zeroincombenze
-if [ -d $WD ]; then
-  p2=Odoo
-  p3=7.0
-  p4="()"
-  p5=$p3
-  p6=__openerp__.py
-  p7=/opt/openerp/7.0/zeroincombenze
-  p8=$p7/
-  testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-fi
-
-WD=/opt/openerp/7.0/zeroincombenze/l10n_it_bbone
-if [ -d $WD ]; then
-  p2=Odoo
-  p3=7.0
-  p4="l10n_it_bbone(ItalianLocalization-Base)"
-  p5=$BB_VER
-  p6=__openerp__.py
-  p7=/opt/openerp/7.0/zeroincombenze
-  p8=$WD/
-  testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-fi
-
-WD=/opt/odoo/8.0
-p2=Odoo
-p3=8.0
-p4="()"
-p5=$p3
-p6=__openerp__.py
-p7=$WD
-p8=$p7/
-testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-
-WD=/opt/odoo/7.0
-p2=Odoo
-p3=7.0
-p4="()"
-p5=$p3
-p6=__openerp__.py
-p7=$WD
-p8=$p7/
-testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-
-WD=/opt/odoo/dev/pypi/os0
-p2=os0
-p3=
-p4="$p2($p2)"
-p5=$OS_VER
-p6=/opt/odoo/dev/pypi/os0/setup.py
-p7=/opt/odoo/dev/pypi/os0/os0
-p8=/opt/odoo/dev/pypi/os0/
-testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-
-WD=/opt/odoo/dev/pypi/os0/os0
-p2=os0
-p3=
-p4="$p2($p2)"
-p5=$OS_VER
-p6=/opt/odoo/dev/pypi/os0/setup.py
-p7=/opt/odoo/dev/pypi/os0/os0
-p8=/opt/odoo/dev/pypi/os0/
-testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-
-WD=/opt/odoo/7.0/openerp/workflow
-p2=Odoo
-p3=7.0
-p4="workflow()"
-p5=$p3
-p6=__openerp__.py
-p7=/opt/odoo/7.0/openerp
-p8=$p7/workflow/
-testpath "$WD" "$p2" "$p3" "$p4" "$p5" "$p6" "$p7" "$p8"
-
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  if [ ${opt_verbose:-0} -gt 0 ]; then
-    echo "**************************************************************************************"
-  fi
-else
-  echo "$ctr"
-fi
-exit $sts
+Z0BUG_main_file "" ""
+exit $?
diff --git a/z0lib/tests/test_parseoptargs b/z0lib/tests/test_parseoptargs
--- a/z0lib/tests/test_parseoptargs
+++ b/z0lib/tests/test_parseoptargs
@@ -1,301 +1,272 @@
-#! /bin/bash
 # -*- coding: utf-8 -*-
-# Regression tests for submodule of z0lib module
+# Regression tests on z0lib
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -d $TDIR/tests ]; then
-  TESTDIR=$TDIR/tests
-  RUNDIR=$TDIR
-elif [ -d $TDIR/../tests ]; then
-  TESTDIR=$TDIR
-  RUNDIR=$TDIR/..
-elif [ -d ./tests ]; then
-  TESTDIR=./tests
-  RUNDIR=./
-elif [ -d ../tests ]; then
-  TESTDIR=./
-  RUNDIR=../
-else
-  TESTDIR=$TDIR
-  RUNDIR=$TDIR/..
-fi
-if [ -d $TDIR/_travis ]; then
-  TRAVISDIR=$TDIR
-elif [ -d $TDIR/../_travis ]; then
-  TRAVISDIR=$TDIR/..
-elif [ -d ./_travis ]; then
-  TRAVISDIR=./
-elif [ -d ../_travis ]; then
-  TRAVISDIR=../
-else
-  TRAVISDIR=~/dev/_travis
-fi
-if [ -e $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -e ./z0librc ]; then
-. ./z0librc
-elif [ -e ../z0librc ]; then
-. ../z0librc
-elif [ -e ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
-fi
-if [ -e $TDIR/z0testrc ]; then
-. $TDIR/z0testrc
-elif [ -e ./z0testrc ]; then
-. ./z0testrc
-elif [ -e ../z0testrc ]; then
-. ../z0testrc
-else
-. ~/dev/z0testrc
-fi
-TESTDIR=$(readlink -e $TESTDIR)
-RUNDIR=$(readlink -e $RUNDIR)
-TRAVISDIR=$(readlink -e $TRAVISDIR)
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+  fi
+done
+TESTDIR=$(findpkg "" "$TDIR . .." "tests")
+RUNDIR=$(readlink -e $TESTDIR/..)
+Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+. $Z0TLIBDIR
+Z0TLIBDIR=$(dirname $Z0TLIBDIR)
+
 
 __version__=0.1.28
+
+test_01() {
+    local tested_opt_dry_run
+    OPTOPTS=(h        n            V           v)
+    OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose)
+    OPTACTI=(1        "1>"         "*>"        1)
+    OPTDEFL=(1        0            ""          0)
+    OPTMETA=("help"   "do nothing" "version"   "verbose")
+    OPTHELP=("this help"\
+     "do nothing (dry-run)"\
+     "show version"\
+     "verbose mode")
+    OPTARGS=()
+
+    parseoptargs "-V"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -V [-h]" "$opt_help" "0"
+    test_result "cmd -V" "$opt_version" "-V"
+    test_result "cmd -V [-n]" "$tested_opt_dry_run" "0"
+    test_result "cmd -V [-v]" "$opt_verbose" "0"
+    echo "Usage: test_parseoptargs [-hnVv]">$FTEST
+    echo "Unit test">>$FTEST
+    echo " -h             this help">>$FTEST
+    echo " -n             do nothing (dry-run)">>$FTEST
+    echo " -V             show version">>$FTEST
+    echo " -v             verbose mode">>$FTEST
+    print_help "Unit test"\
+      "">$FOUT
+    test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+}
+
+test_02() {
+    local tested_opt_dry_run
+    OPTOPTS=(h        n            V           p        q           v)
+    OPTDEST=(opt_help opt_dry_run  opt_version opt_path opt_verbose opt_verbose)
+    OPTACTI=(1        "1>"         "*>"        "=>"     0           1)
+    OPTDEFL=(1        0            ""          "~/"     "#"         "#")
+    OPTMETA=("help"   "do nothing" "version"   "path"   "quiet"     "verbose")
+    OPTHELP=("this help"\
+     "do nothing (dry-run)"\
+     "show version"\
+     "path"
+     "silent mode"\
+     "verbose mode")
+    OPTARGS=(tgt)
+
+    opt_verbose=-1
+    parseoptargs "mytarget"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd mytarget [-h]" "$opt_help" "0"
+    test_result "cmd mytarget [-V]" "$opt_version" ""
+    test_result "cmd mytarget [-n]" "$tested_opt_dry_run" "0"
+    test_result "cmd mytarget [-p]" "$opt_path" "~/"
+    test_result "cmd mytarget [-qv]" "$opt_verbose" "-1"
+
+    opt_verbose=-1
+    parseoptargs "mytarget" "-q"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd mytarget [-q]" "$opt_verbose" "0"
+
+    opt_verbose=-1
+    parseoptargs "mytarget" "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd mytarget [-v]" "$opt_verbose" "1"
+
+    echo "Usage: test_parseoptargs [-hnV][-p path][-qv] tgt">$FTEST
+    echo "Unit test">>$FTEST
+    echo " -h             this help">>$FTEST
+    echo " -n             do nothing (dry-run)">>$FTEST
+    echo " -V             show version">>$FTEST
+    echo " -p path        path">>$FTEST
+    echo " -q             silent mode">>$FTEST
+    echo " -v             verbose mode">>$FTEST
+    print_help "Unit test"\
+      "">$FOUT
+    test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+
+    parseoptargs "-p" "./mypath" "yourtarget"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -p ./mypath yourtarget [-h]" "$opt_help" "0"
+    test_result "cmd -p ./mypath yourtarget [-V]" "$opt_version" ""
+    test_result "cmd -p ./mypath yourtarget [-n]" "$tested_opt_dry_run" "0"
+    test_result "cmd -p ./mypath yourtarget [-p]" "$opt_path" "./mypath"
+    test_result "cmd -p ./mypath yourtarget [\$1]" "$tgt" "yourtarget"
+}
+
+test_03() {
+    local tested_opt_dry_run
+    OPTOPTS=(h        n            O       p        V)
+    OPTDEST=(opt_help opt_dry_run  opt_own opt_path opt_version)
+    OPTACTI=(1        "1>"         "="     "=>"     "*>")
+    OPTDEFL=(1        0            "$USER" "~/"     "")
+    OPTMETA=("help"   "do nothing" "own"   "path"   "version")
+    OPTHELP=("this help"\
+     "do nothing (dry-run)"\
+     "owner username"\
+     "path"\
+     "show version")
+    OPTARGS=(tgt)
+
+    parseoptargs "mytarget"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd mytarget [-h]" "$opt_help" "0"
+    test_result "cmd mytarget [-V]" "$opt_version" ""
+    test_result "cmd mytarget [-n]" "$tested_opt_dry_run" "0"
+    test_result "cmd mytarget [-p]" "$opt_path" "~/"
+    test_result "cmd mytarget [-O]" "$opt_own" "$USER"
+    test_result "cmd mytarget [\$1]" "$tgt" "mytarget"
+    echo "Usage: test_parseoptargs [-hn][-O own][-p path][-V] tgt">$FTEST
+    echo "Unit test">>$FTEST
+    echo " -h             this help">>$FTEST
+    echo " -n             do nothing (dry-run)">>$FTEST
+    echo " -O own owner username">>$FTEST
+    echo " -p path        path">>$FTEST
+    echo " -V             show version">>$FTEST
+    print_help "Unit test"\
+      "">$FOUT
+    test_result "print_help" "$FOUT" "$FTEST" "diff -qEbB"
+
+    parseoptargs "mytarget" "-x"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -x mytarget [-h]" "$opt_help" "1"
+    if [ -f $FOUT ]; then rm -f $FOUT; fi
+    if [ -f $FTEST ]; then rm -f $FTEST; fi
+}
+
+test_04() {
+    local tested_opt_dry_run
+    OPTOPTS=(h        a     b     c     d     e     f     g     i     j     k     l     V)
+    OPTDEST=(opt_help opt_a opt_b opt_c opt_d opt_e opt_f opt_g opt_i opt_j opt_k opt_l opt_version)
+    OPTACTI=(1        1     1     1     1     1     1     1     1     1     1     1     "*>")
+    OPTDEFL=(0        0     0     0     0     0     0     0     0     0     0     0     "")
+    OPTMETA=("help"   "o_a" "o_b" "o_c" "0_d" "o_e" "o_f" "o_g" "o_i" "o_j" "o_k" "o_l" "version")
+    OPTHELP=("this help"\
+     "opt_a"\
+     "opt_b"\
+     "opt_c"\
+     "opt_d"\
+     "opt_e"\
+     "opt_f"\
+     "opt_g"\
+     "opt_i"\
+     "opt_j"\
+     "opt_k"\
+     "opt_l"\
+     "show version")
+    OPTARGS=()
+
+    parseoptargs "-a" "-b" "-c" "-d" "-e" "-f" "-g" "-i" "-j" "-k" "-l"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    for i in {a..l}; do
+      if [ "$i" == "h" ]; then
+        test_result "cmd -a -b -c ... [-h]" "$opt_help" "0"
+      else
+        o="opt_$i"
+        test_result "cmd -a -b -c ... [-$i]" "${!o}" "1"
+      fi
+    done
+}
+
+test_05() {
+    local tested_opt_dry_run
+    OPTOPTS=(h        n            v           V)
+    OPTDEST=(opt_help opt_dry_run  opt_verbose opt_version)
+    OPTACTI=(1        1            "+"         "*>")
+    OPTDEFL=(0        0            0           "")
+    OPTMETA=("help"   "do nothing" "verbose"   "version")
+    OPTHELP=("this help"\
+     "do nothing (dry-run)"\
+     "verbose mode"\
+     "show version")
+    OPTARGS=()
+
+    parseoptargs "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -v [-h]" "$opt_help" "0"
+    test_result "cmd -v" "$opt_verbose" "1"
+
+    parseoptargs "-vv"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -vv" "$opt_verbose" "2"
+
+    parseoptargs "-v" "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -v -v" "$opt_verbose" "2"
+
+    parseoptargs "-v" "-n" "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -v -v" "$opt_verbose" "2"
+}
+
+test_06() {
+    local tested_opt_dry_run
+    OPTOPTS=(h        n            v           V)
+    OPTDEST=(opt_help opt_dry_run  opt_verbose opt_version)
+    OPTACTI=(1        1            "+"         "*>")
+    OPTDEFL=(0        0            -1          "")
+    OPTMETA=("help"   "do nothing" "verbose"   "version")
+    OPTHELP=("this help"\
+     "do nothing (dry-run)"\
+     "verbose mode"\
+     "show version")
+    OPTARGS=()
+
+    parseoptargs "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -v" "$opt_verbose" "1"
+
+    parseoptargs "-vv"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -vv" "$opt_verbose" "2"
+
+    parseoptargs "-v" "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -v -v" "$opt_verbose" "2"
+
+    parseoptargs "-v" "-n" "-v"
+    tested_opt_dry_run=$opt_dry_run
+    opt_dry_run=$SAVED_OPT_DRY_RUN
+    test_result "cmd -v -v" "$opt_verbose" "2"
+}
+
+Z0BUG_init
 parseoptest -l$TESTDIR/test_z0librc.log $@
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-sts=0
-# This test could fail because opt_dry_run is parsed by test
-# So opt_dry_run is saved and restored
-saved_opt_dry_run=$opt_dry_run
 
+# This test could fail because opt_dry_run is parsed by test itself
+# So opt_dry_run is saved and restored
+SAVED_OPT_DRY_RUN=$opt_dry_run
 FOUT=$TESTDIR/z0librc.out
 FTEST=$TESTDIR/z0librc.test
 
-OPTOPTS=(h        n            V           v)
-OPTDEST=(opt_help opt_dry_run  opt_version opt_verbose)
-OPTACTI=(1        "1>"         "*>"        1)
-OPTDEFL=(1        0            ""          0)
-OPTMETA=("help"   "do nothing" "version"   "verbose")
-OPTHELP=("this help"\
- "do nothing (dry-run)"\
- "show version"\
- "verbose mode")
-OPTARGS=()
-
-parseoptargs "-V"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -V [-h]" "$opt_help" "0"
-ci-test "cmd -V" "$opt_version" "-V"
-ci-test "cmd -V [-n]" "$tested_opt_dry_run" "0"
-ci-test "cmd -V [-v]" "$opt_verbose" "0"
-echo "Usage: test_parseoptargs [-hnVv]">$FTEST
-echo "Unit test">>$FTEST
-echo " -h             this help">>$FTEST
-echo " -n             do nothing (dry-run)">>$FTEST
-echo " -V             show version">>$FTEST
-echo " -v             verbose mode">>$FTEST
-print_help "Unit test"\
-  "">$FOUT
-ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
-
-OPTOPTS=(h        n            V           p        q           v)
-OPTDEST=(opt_help opt_dry_run  opt_version opt_path opt_verbose opt_verbose)
-OPTACTI=(1        "1>"         "*>"        "=>"     0           1)
-OPTDEFL=(1        0            ""          "~/"     "#"         "#")
-OPTMETA=("help"   "do nothing" "version"   "path"   "quiet"     "verbose")
-OPTHELP=("this help"\
- "do nothing (dry-run)"\
- "show version"\
- "path"
- "silent mode"\
- "verbose mode")
-OPTARGS=(tgt)
-
-opt_verbose=-1
-parseoptargs "mytarget"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd mytarget [-h]" "$opt_help" "0"
-ci-test "cmd mytarget [-V]" "$opt_version" ""
-ci-test "cmd mytarget [-n]" "$tested_opt_dry_run" "0"
-ci-test "cmd mytarget [-p]" "$opt_path" "~/"
-ci-test "cmd mytarget [-qv]" "$opt_verbose" "-1"
-
-opt_verbose=-1
-parseoptargs "mytarget" "-q"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd mytarget [-q]" "$opt_verbose" "0"
-
-opt_verbose=-1
-parseoptargs "mytarget" "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd mytarget [-v]" "$opt_verbose" "1"
-
-echo "Usage: test_parseoptargs [-hnV][-p path][-qv] tgt">$FTEST
-echo "Unit test">>$FTEST
-echo " -h             this help">>$FTEST
-echo " -n             do nothing (dry-run)">>$FTEST
-echo " -V             show version">>$FTEST
-echo " -p path        path">>$FTEST
-echo " -q             silent mode">>$FTEST
-echo " -v             verbose mode">>$FTEST
-print_help "Unit test"\
-  "">$FOUT
-ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
-
-parseoptargs "-p" "./mypath" "yourtarget"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -p ./mypath yourtarget [-h]" "$opt_help" "0"
-ci-test "cmd -p ./mypath yourtarget [-V]" "$opt_version" ""
-ci-test "cmd -p ./mypath yourtarget [-n]" "$tested_opt_dry_run" "0"
-ci-test "cmd -p ./mypath yourtarget [-p]" "$opt_path" "./mypath"
-ci-test "cmd -p ./mypath yourtarget [\$1]" "$tgt" "yourtarget"
-
-
-OPTOPTS=(h        n            O       p        V)
-OPTDEST=(opt_help opt_dry_run  opt_own opt_path opt_version)
-OPTACTI=(1        "1>"         "="     "=>"     "*>")
-OPTDEFL=(1        0            "$USER" "~/"     "")
-OPTMETA=("help"   "do nothing" "own"   "path"   "version")
-OPTHELP=("this help"\
- "do nothing (dry-run)"\
- "owner username"\
- "path"\
- "show version")
-OPTARGS=(tgt)
-
-parseoptargs "mytarget"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd mytarget [-h]" "$opt_help" "0"
-ci-test "cmd mytarget [-V]" "$opt_version" ""
-ci-test "cmd mytarget [-n]" "$tested_opt_dry_run" "0"
-ci-test "cmd mytarget [-p]" "$opt_path" "~/"
-ci-test "cmd mytarget [-O]" "$opt_own" "$USER"
-ci-test "cmd mytarget [\$1]" "$tgt" "mytarget"
-echo "Usage: test_parseoptargs [-hn][-O own][-p path][-V] tgt">$FTEST
-echo "Unit test">>$FTEST
-echo " -h             this help">>$FTEST
-echo " -n             do nothing (dry-run)">>$FTEST
-echo " -O own owner username">>$FTEST
-echo " -p path        path">>$FTEST
-echo " -V             show version">>$FTEST
-print_help "Unit test"\
-  "">$FOUT
-ci-test "print_help" "$FOUT" "$FTEST" "diff -qEbB"
-
-parseoptargs "mytarget" "-x"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -x mytarget [-h]" "$opt_help" "1"
-
-if [ -f $FOUT ]; then rm -f $FOUT; fi
-if [ -f $FTEST ]; then rm -f $FTEST; fi
-
-
-OPTOPTS=(h        a     b     c     d     e     f     g     i     j     k     l     V)
-OPTDEST=(opt_help opt_a opt_b opt_c opt_d opt_e opt_f opt_g opt_i opt_j opt_k opt_l opt_version)
-OPTACTI=(1        1     1     1     1     1     1     1     1     1     1     1     "*>")
-OPTDEFL=(0        0     0     0     0     0     0     0     0     0     0     0     "")
-OPTMETA=("help"   "o_a" "o_b" "o_c" "0_d" "o_e" "o_f" "o_g" "o_i" "o_j" "o_k" "o_l" "version")
-OPTHELP=("this help"\
- "opt_a"\
- "opt_b"\
- "opt_c"\
- "opt_d"\
- "opt_e"\
- "opt_f"\
- "opt_g"\
- "opt_i"\
- "opt_j"\
- "opt_k"\
- "opt_l"\
- "show version")
-OPTARGS=()
-
-parseoptargs "-a" "-b" "-c" "-d" "-e" "-f" "-g" "-i" "-j" "-k" "-l"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-for i in {a..l}; do
-  if [ "$i" == "h" ]; then
-    ci-test "cmd -a -b -c ... [-h]" "$opt_help" "0"
-  else
-    o="opt_$i"
-    ci-test "cmd -a -b -c ... [-$i]" "${!o}" "1"
-  fi
-done
-
-
-OPTOPTS=(h        n            v           V)
-OPTDEST=(opt_help opt_dry_run  opt_verbose opt_version)
-OPTACTI=(1        1            "+"         "*>")
-OPTDEFL=(0        0            0           "")
-OPTMETA=("help"   "do nothing" "verbose"   "version")
-OPTHELP=("this help"\
- "do nothing (dry-run)"\
- "verbose mode"\
- "show version")
-OPTARGS=()
-
-
-parseoptargs "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -v [-h]" "$opt_help" "0"
-ci-test "cmd -v" "$opt_verbose" "1"
-
-parseoptargs "-vv"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -vv" "$opt_verbose" "2"
-
-parseoptargs "-v" "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -v -v" "$opt_verbose" "2"
-
-parseoptargs "-v" "-n" "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -v -v" "$opt_verbose" "2"
-
-
-OPTOPTS=(h        n            v           V)
-OPTDEST=(opt_help opt_dry_run  opt_verbose opt_version)
-OPTACTI=(1        1            "+"         "*>")
-OPTDEFL=(0        0            -1          "")
-OPTMETA=("help"   "do nothing" "verbose"   "version")
-OPTHELP=("this help"\
- "do nothing (dry-run)"\
- "verbose mode"\
- "show version")
-OPTARGS=()
-
-
-parseoptargs "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -v" "$opt_verbose" "1"
-
-parseoptargs "-vv"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -vv" "$opt_verbose" "2"
-
-parseoptargs "-v" "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -v -v" "$opt_verbose" "2"
-
-parseoptargs "-v" "-n" "-v"
-tested_opt_dry_run=$opt_dry_run
-opt_dry_run=$saved_opt_dry_run
-ci-test "cmd -v -v" "$opt_verbose" "2"
-
-
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
-fi
-exit $sts
+Z0BUG_main_file "" ""
+exit $?
diff --git a/z0lib/tests/test_wlog b/z0lib/tests/test_wlog
--- a/z0lib/tests/test_wlog
+++ b/z0lib/tests/test_wlog
@@ -1,121 +1,83 @@
-#! /bin/bash
 # -*- coding: utf-8 -*-
-# Regression tests for submodule of z0lib module
+# Regression tests on z0lib
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-if [ -d $TDIR/tests ]; then
-  TESTDIR=$TDIR/tests
-  RUNDIR=$TDIR
-elif [ -d $TDIR/../tests ]; then
-  TESTDIR=$TDIR
-  RUNDIR=$TDIR/..
-elif [ -d ./tests ]; then
-  TESTDIR=./tests
-  RUNDIR=./
-elif [ -d ../tests ]; then
-  TESTDIR=./
-  RUNDIR=../
-else
-  TESTDIR=$TDIR
-  RUNDIR=$TDIR/..
-fi
-if [ -d $TDIR/_travis ]; then
-  TRAVISDIR=$TDIR
-elif [ -d $TDIR/../_travis ]; then
-  TRAVISDIR=$TDIR/..
-elif [ -d ./_travis ]; then
-  TRAVISDIR=./
-elif [ -d ../_travis ]; then
-  TRAVISDIR=../
-else
-  TRAVISDIR=~/dev/_travis
-fi
-if [ -e $TDIR/z0librc ]; then
-. $TDIR/z0librc
-elif [ -e ./z0librc ]; then
-. ./z0librc
-elif [ -e ../z0librc ]; then
-. ../z0librc
-elif [ -e ~/z0librc ]; then
-. ~/z0librc
-else
-. /etc/z0librc
-fi
-if [ -e $TDIR/z0testrc ]; then
-. $TDIR/z0testrc
-elif [ -e ./z0testrc ]; then
-. ./z0testrc
-elif [ -e ../z0testrc ]; then
-. ../z0testrc
-else
-. ~/dev/z0testrc
-fi
-TESTDIR=$(readlink -e $TESTDIR)
-RUNDIR=$(readlink -e $RUNDIR)
-TRAVISDIR=$(readlink -e $TRAVISDIR)
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+  fi
+done
+TESTDIR=$(findpkg "" "$TDIR . .." "tests")
+RUNDIR=$(readlink -e $TESTDIR/..)
+Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+. $Z0TLIBDIR
+Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
 __version__=0.1.24
+
+test_01() {
+    if [ "$LECHO" == "echo" ]; then
+      WLOGCMD="wecho-1"
+    else
+      WLOGCMD="wecho-0"
+    fi
+    FLOG=
+    FLOGTMP="test_z0librc.log"
+    set_tlog_file "$FLOGTMP"
+    test_result "set logfile (1)" "$HOME/$FLOGTMP" "$FLOG"
+    test_result "set logfile (2)" "#" "$FLOG_ECHO"
+
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      touch $HOME/$FLOGTMP
+      if [ ! -f $HOME/$FLOGTMP ]; then
+        echo "Test failed due impossible internal error!!"
+        exit 1
+      fi
+      set_tlog_file "$FLOGTMP" "new"
+      if [ -f $HOME/test_z0librc.log ]; then TRES="1"; else TRES="0"; fi
+    fi
+    test_result "rm logfile (1)" "0" "$TRES"
+    test_result "rm logfile (2)" "#" "$FLOG_ECHO"
+
+    FLOGTMP="./test_tmp.log"
+    set_tlog_file "$FLOGTMP" "new"
+    FLOGTMP=$(readlink -f $FLOGTMP)
+    test_result "set logfile (3)" "$FLOGTMP" "$FLOG"
+    test_result "set logfile (4)" "#" "$FLOG_ECHO"
+
+    FLOGTMP="$TESTDIR/test_tmp.log"
+    set_tlog_file "$FLOGTMP" "new"
+    test_result "set logfile (5)" "$FLOGTMP" "$FLOG"
+    test_result "set logfile (6)" "#" "$FLOG_ECHO"
+
+    set_tlog_file "$FLOGTMP" "new" "echo"
+    test_result "set logfile (7)" "$FLOGTMP" "$FLOG"
+    test_result "set logfile (8)" "echo" "$FLOG_ECHO"
+    if [ -f $FLOGTMP ]; then rm -f $FLOGTMP; fi
+
+
+    WLOGCMD=
+    set_tlog_file "$logfn" "$LNEW" "$LECHO"
+    if [ ${opt_dry_run:-0} -eq 0 ]; then
+      wlog "Since now, test messages are store in $FLOG"
+    fi
+    test_result "echoing with wlog (1)" "$TESTDIR/test_z0librc.log" "$FLOG"
+    if [ "$LECHO" == "echo" ]; then
+      test_result "echoing with wlog (2)" "echo" "$FLOG_ECHO"
+    else
+      test_result "echoing with wlog (2)" "#" "$FLOG_ECHO"
+    fi
+}
+
+Z0BUG_init
 parseoptest -l$TESTDIR/test_z0librc.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-sts=0
 
-if [ "$LECHO" == "echo" ]; then
-  WLOGCMD="wecho-1"
-else
-  WLOGCMD="wecho-0"
-fi
-FLOG=
-FLOGTMP="test_z0librc.log"
-set_tlog_file "$FLOGTMP"
-ci-test "set logfile (1)" "$HOME/$FLOGTMP" "$FLOG"
-ci-test "set logfile (2)" "#" "$FLOG_ECHO"
-
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  touch $HOME/$FLOGTMP
-  if [ ! -f $HOME/$FLOGTMP ]; then
-    echo "Test failed due impossible internal error!!"
-    exit 1
-  fi
-  set_tlog_file "$FLOGTMP" "new"
-  if [ -f $HOME/test_z0librc.log ]; then TRES="1"; else TRES="0"; fi
-fi
-ci-test "rm logfile (1)" "0" "$TRES"
-ci-test "rm logfile (2)" "#" "$FLOG_ECHO"
-
-FLOGTMP="./test_tmp.log"
-set_tlog_file "$FLOGTMP" "new"
-FLOGTMP=$(readlink -f $FLOGTMP)
-ci-test "set logfile (3)" "$FLOGTMP" "$FLOG"
-ci-test "set logfile (4)" "#" "$FLOG_ECHO"
-
-FLOGTMP="$TESTDIR/test_tmp.log"
-set_tlog_file "$FLOGTMP" "new"
-ci-test "set logfile (5)" "$FLOGTMP" "$FLOG"
-ci-test "set logfile (6)" "#" "$FLOG_ECHO"
-
-set_tlog_file "$FLOGTMP" "new" "echo"
-ci-test "set logfile (7)" "$FLOGTMP" "$FLOG"
-ci-test "set logfile (8)" "echo" "$FLOG_ECHO"
-if [ -f $FLOGTMP ]; then rm -f $FLOGTMP; fi
-
-
-WLOGCMD=
-set_tlog_file "$logfn" "$LNEW" "$LECHO"
-if [ ${opt_dry_run:-0} -eq 0 ]; then
-  wlog "Since now, test messages are store in $FLOG"
-fi
-ci-test "echoing with wlog (1)" "$TESTDIR/test_z0librc.log" "$FLOG"
-if [ "$LECHO" == "echo" ]; then
-  ci-test "echoing with wlog (2)" "echo" "$FLOG_ECHO"
-else
-  ci-test "echoing with wlog (2)" "#" "$FLOG_ECHO"
-fi
-
-if [ ${opt_dry_run:-0} -ne 0 ]; then
-  echo "$ctr"
-fi
-exit $sts
+Z0BUG_main_file "" ""
+exit $?
