[IMP] vem: package versions improvements

diff --git a/zerobug/_travis/travis_run_pypi_tests b/zerobug/_travis/travis_run_pypi_tests
--- a/zerobug/_travis/travis_run_pypi_tests
+++ b/zerobug/_travis/travis_run_pypi_tests
@@ -215,9 +215,8 @@ do_test () {
         [[ -n $TRAVIS_TEST_PATTERN ]] && OPTS="$OPTS -p $TRAVIS_TEST_PATTERN"
         coverage_set
         run_traced "cd $PRJPATH/tests && DEV_ENVIRONMENT=$PRJNAME $(which zerobug) $OPTS"
-        if [[ ! -f $COVERAGE_DATA_FILE ]]; then
-            echo "Result coverage file $COVERAGE_DATA_FILE not found!"
-        fi
+        sts=$?
+        [[ ! -f $COVERAGE_DATA_FILE ]] && echo "Result coverage file $COVERAGE_DATA_FILE not found!"
     fi
     return $sts
 }
@@ -375,7 +374,7 @@ if [ "${TRANSIFEX_CHECK:-0}" == "1" ]; then
 else
     TRANSIFEX_CHECK_ENABLED=0;
 fi
-[[ -z "$PYPI_RUN_PYVER" ]] && PYPI_RUN_PYVER="(2.7|3.5|3.6|3.7|3.8|3.9)"
+[[ -z "$PYPI_RUN_PYVER" ]] && PYPI_RUN_PYVER="(2.7|3.7|3.8|3.9|3.10)"
 [[ -f ./travis.ini && $(grep -qv "^#" ./travis.ini) ]] && export $(cat ./travis.ini|grep -v "^#"|tr -d "'"|tr -d '"')
 [[ "$PRJNAME" == "Odoo" ]] && ULI="$(build_odoo_param GIT_ORGID '.')${BRANCH}-${PKGNAME}" || ULI="${PKGNAME}-${BRANCH}"
 [[ -n "$REPOSNAME" ]] && UMLI="${REPOSNAME//,/+}.${ULI}" || UMLI=$ULI
