[IMP] Check database configuration

diff --git a/clodoo/manage_db b/clodoo/manage_db
--- a/clodoo/manage_db
+++ b/clodoo/manage_db
@@ -35,7 +35,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.3.8.12
+__version__=0.3.8.14
 
 
 up_oemod() {
@@ -136,25 +136,25 @@ set_opt_conf() {
       x=$(parse_URI "$cf" "" "+NAMEID+LOCAL")
       x=${x: -2}
       if [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$x[[:space:]] ]]; then
-        echo "This file require -D switch to be executed!"
+        echo "This file require -o switch to be executed!"
         exit 1
       fi
     fi
 }
 
-OPTOPTS=(h        b         c        D             d      m         n           o       q           r           t         U          V           v           x)
-OPTDEST=(opt_help odoo_vids opt_conf opt_with_demo opt_DB opt_multi opt_dry_run opt_del opt_verbose opt_xmlport test_mode opt_DBuser opt_version opt_verbose opt_exit)
-OPTACTI=(1        "="       "="      "*"           "="    1         1           1       0           "="         1         "="        "*"         "+"         1)
-OPTDEFL=(1        "7.0"     ""       ""            ""     -1        0           0       -1          ""          0         ""         ""          -1          0)
-OPTMETA=("help"   "branch"  "file"   ""            "name" ""        "noop"      "del"   "quiet"     "port"      "test"    "user"     "version"   "verbose"   "")
+OPTOPTS=(h        b         c        D       d      m         n           o             q           r           t         U          V           v           x)
+OPTDEST=(opt_help odoo_vids opt_conf opt_del opt_DB opt_multi opt_dry_run opt_with_demo opt_verbose opt_xmlport test_mode opt_DBuser opt_version opt_verbose opt_exit)
+OPTACTI=(1        "="       "="      1       "="    1         1           "*"           0           "="         1         "="        "*"         "+"         1)
+OPTDEFL=(1        "10.0"    ""       0       ""     -1        0           ""            -1          ""          0         ""         ""          -1          0)
+OPTMETA=("help"   "branch"  "file"   "del"   "name" ""        "noop"      ""            "quiet"     "port"      "test"    "user"     "version"   "verbose"   "")
 OPTHELP=("this help"\
- "branch: must be 6.1 7.0 8.0 9.0 10.0 11.0 12.0 or * (def 7.0)"\
+ "branch: must be 6.1 7.0 8.0 9.0 10.0 11.0 12.0 or * (def 10.0)"\
  "configuration file (only update/action)"\
- "add demo data to new db"\
+ "delete DB if exists"\
  "set database name or regex when update/action (@ is replaced by odoo major version)"\
  "multi-version odoo environment"\
  "do nothing (dry-run)"\
- "delete DB if exists"\
+ "add demo data to new db"\
  "silent mode"\
  "xmlrpc port"\
  "test mode (implies dry-run)"\
@@ -173,7 +173,7 @@ if [ "$opt_version" ]; then
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Manage Cloud DB(s) \n"\
-  "Action may be on of: action,install,update,upgrade,module,translate,rename_phase\ncmdlist of action may be upd_oemod or clodoo action\ncmdlist of module,upgrade is module list\ncmdlist of install/update is phase list: $PHASE_LIST\ncmdlist of rename_phase (phase) is old=new\n\n(C) 2015-2019 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "Action may be on of: action,install,update,upgrade,module,translate,reassign,rename,rename_phase\ncmdlist of action may be upd_oemod or clodoo action\ncmdlist of module,upgrade is module list\ncmdlist of install/update is phase list: $PHASE_LIST\ncmdlist of reassign is new username\ncmdlist of rename_phase (phase) is old=new\ncmdlist of rename is a csv filename with module renames list\n\n(C) 2015-2019 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Linux/dev\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
 opts=
@@ -190,7 +190,7 @@ fi
 sts=$STS_SUCCESS
 discover_multi
 if [ "$odoo_vids" == "*" ]; then
-  [ $opt_multi -gt 0 ] && odoo_vids="12.0,11.0,10.0,9.0,8.0,7.0,6.1" || odoo_vids="7.0"
+  [ $opt_multi -gt 0 ] && odoo_vids="12.0,11.0,10.0,9.0,8.0,7.0,6.1" || odoo_vids="10.0"
 fi
 [ $opt_exit -ne 0 ] && opts_x=-x || opts_x=
 for odoo_vid in ${odoo_vids//,/ }; do
@@ -256,6 +256,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
     fi
     sts=0
     for cf in $CFLOOP; do
+      # TODO FIX
       if [ "$cf" == "02" ]; then
         opts="-lit_IT"
       else
@@ -268,7 +269,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
           else
             optdb=
           fi
-          run_traced "nice $TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf $optdb -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts -b$odoo_fver -c code/z0_install_$cf.conf $optdb -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
         else
           echo "Invalid phase $cf in update!"
@@ -276,8 +277,13 @@ for odoo_vid in ${odoo_vids//,/ }; do
         fi
       elif [ "$cf" == "00" ]; then
         if [ $action == "install" ]; then
+          if [ -n "$opt_db" ]; then
+            db=$opt_db
+          else
+            db=$(cat clodoo_last.conf|awk -F= '{print $2}')
+          fi
           if [ $opt_del -eq 0 ]; then
-            [ $opt_verbose -gt 0 ] && echo "Warning: you must enable dropping DB using -o switch"
+            [ $opt_verbose -gt 0 ] && echo "Warning: you must enable dropping DB using -D switch"
             sts=1
           else
             if $(psql -l|grep -q $db); then
@@ -291,7 +297,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
                 run_traced "sudo systemctl restart $svcname"
                 sleep 2
               fi
-              run_traced "nice $TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo $opts"
+              run_traced "nice $TDIR/clodoo.py $opts -b$odoo_fver -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo $opts"
               if $(psql -l|grep -q $db); then
                 run_traced "pg_db_active -wa $db; dropdb --if-exists -U$opt_dbuser $db"
               fi
@@ -309,7 +315,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
           sts=1
         fi
       elif [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$cf[[:space:]] ]]; then
-        [ $opt_verbose -gt 0 ] && echo "Warning: phase $cf is just for demo (use -D switch to enable)"
+        [ $opt_verbose -gt 0 ] && echo "Warning: phase $cf is just for demo (use -o switch to enable)"
       else
         if [ $action == "update" ]; then
           W4T=0
@@ -319,7 +325,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
             else
               eval $WCMD
             fi
-            run_traced "nice $TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo $opts"
+            run_traced "nice $TDIR/clodoo.py $opts -b$odoo_fver -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo $opts"
             s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
             [ $sts -ne 0 -a $opt_exit -ne 0 ] && break
           done
@@ -329,7 +335,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
           else
             db=$(cat clodoo_last.conf|awk -F= '{print $2}')
           fi
-          run_traced "nice $TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts -b$odoo_fver -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
         fi
       fi
@@ -372,7 +378,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
         echo "$TDIR/run_odoo_debug $odoo_vid -um $cmdlist -d $db -sk -x$xmlport"
         [ $opt_dry_run -ne 0 ] || nice $TDIR/run_odoo_debug $odoo_vid -um $cmdlist -d $db -sk -x$xmlport
         if [ "$cmdlist" != "all" ]; then
-          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -A upgrade_modules -b$odoo_vid -u $cmdlist -d $db -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -A upgrade_modules -b$odoo_fver -u $cmdlist -d $db -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
         fi
         if [ $sts -ne $STS_SUCCESS ]; then
@@ -380,15 +386,15 @@ for odoo_vid in ${odoo_vids//,/ }; do
         fi
       elif [ "$action" == "action" ]; then
         if [ "$cmdlist" == "upd_oemod" ]; then
-          run_traced "nice $TDIR/clodoo.py $opts -b$odoo_vid -c=code/z0_install_10.conf -d $db -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts -b$odoo_fver -c=code/z0_install_10.conf -d $db -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
           [ $opt_dry_run -ne 0 ] || up_oemod $db $odoo_vid
         elif [ -n "$cmdlist" -a "$cmdlist" == "translation" ]; then
           echo "$TDIR/run_odoo_debug $odoo_vid -l -d $db -x$xmlport"
           [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug $odoo_vid -l -d $db -x$xmlport
         else
-          echo "$TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$xmlport $opt_with_demo $opts"
-          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$xmlport $opt_with_demo $opts"
+          echo "$TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_fver -d $db -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_fver -d $db -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
           if [ $sts -ne $STS_SUCCESS ]; then
             break
@@ -399,7 +405,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
         [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug $odoo_vid -l -d $db -x$xmlport
       else
         if [ -n "$cmdlist" ]; then
-          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_fver -d $db -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
           if [ $sts -ne $STS_SUCCESS ]; then
             break
@@ -409,7 +415,7 @@ for odoo_vid in ${odoo_vids//,/ }; do
             echo "Configuration file $opt_conf not found!"
             exit 1
           fi
-          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -b$odoo_vid -c $cf -d $db -r$xmlport $opt_with_demo $opts"
+          run_traced "nice $TDIR/clodoo.py $opts $opts_cf -b$odoo_fver -c $cf -d $db -r$xmlport $opt_with_demo $opts"
           s=$?; [ $s -ne 0 -a $sts -eq 0 ] && sts=$s
         fi
       fi
@@ -447,12 +453,52 @@ for odoo_vid in ${odoo_vids//,/ }; do
     fi
     DBlist=$(db_list)
     DBlist=${DBlist//,/ }
+    [ -z "$cmdlist" ] && cmdlist=./moduli_alias.csv
+    if [ ! -f $cmdlist ]; then
+      echo "File $cmdlist not found!"
+      exit 1
+    fi
     for db in $DBlist; do
       while IFS== read src tgt; do
         if [ -n "$src" -a -n "$tgt" -a "$src" != "$tgt" ]; then
           run_traced "psql -U$opt_dbuser -c \"update ir_module_module set name='$tgt' where name='$src';\" $db"
         fi
-      done < ./moduli_alias.csv
+      done < $cmdlist
+    done
+  elif [ "$action" == "reassign" ]; then
+    if [ -z "$opt_dbuser" ]; then
+      opt_dbuser=$(build_odoo_param USER $odoo_vid)
+    fi
+    DBlist=$(db_list)
+    DBlist=${DBlist//,/ }
+    if [ -z "$cmdlist" ]; then
+      echo "Missing username to reassing!"
+      exit 1
+    fi
+    OWNER=$cmdlist
+    for db in $DBlist; do
+      run_traced "psql -Upostgres -qc 'COMMENT ON EXTENSION plpgsql IS null;' $db"
+      run_traced "psql -Upostgres -qc 'GRANT ALL PRIVILEGES ON DATABASE $db TO $OWNER;' $db"
+      run_traced "psql -Upostgres -qc 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $OWNER' $db"
+      run_traced "psql -Upostgres -qc 'GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $OWNER' $db"
+      run_traced "psql -Upostgres -qc 'GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $OWNER' $db"
+      run_traced "psql -Upostgres -qc 'ALTER DEFAULT PRIVILEGES GRANT ALL ON TABLES TO $OWNER' $db"
+      run_traced "psql -Upostgres -qc 'ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO $OWNER' $db"
+      if [ $opt_dry_run -eq 0 ]; then
+        [ $opt_verbose -gt 0 ] && echo "Reassigning all tables ..."
+        for tbl in $(psql -Upostgres -qAtc "select tablename from pg_tables where schemaname = 'public'" $db); do
+          psql -Upostgres -qc "ALTER TABLE \"$tbl\" OWNER TO $OWNER" $db
+          psql -Upostgres -qc "GRANT ALL PRIVILEGES ON TABLE \"$tbl\" TO $OWNER" $db
+        done
+        for tbl in $(psql -Upostgres -qAtc "select sequence_name from information_schema.sequences where sequence_schema = 'public'" $db); do
+          psql -Upostgres -qc "ALTER SEQUENCE \"$tbl\" OWNER TO $OWNER" $db
+          psql -Upostgres -qc "GRANT ALL PRIVILEGES ON SEQUENCE \"$tbl\" TO $OWNER" $db
+        done
+        for tbl in $(psql -qAtc "select table_name from information_schema.views where table_schema = 'public'" $db); do
+          psql -Upostgres -qc "ALTER view \"$tbl\" OWNER TO $OWNER" $db
+          psql -Upostgres -qc "GRANT ALL PRIVILEGES ON TABLE \"$tbl\" TO $OWNER" $db
+        done
+      fi
     done
   else
     echo "Invalid action!"
diff --git a/clodoo/run_odoo_debug b/clodoo/run_odoo_debug
--- a/clodoo/run_odoo_debug
+++ b/clodoo/run_odoo_debug
@@ -28,7 +28,7 @@ if [ -z "$ODOOLIBDIR" ]; then
 fi
 . $ODOOLIBDIR
 
-__version__=0.3.8.13
+__version__=0.3.8.14
 
 
 OPTOPTS=(h        b          c        d        e       k        i       I       l        L        m           M         n           o         p        s         T        t         U          u       V           v           w       x)
@@ -68,7 +68,7 @@ if [ "$opt_version" ]; then
   exit 0
 fi
 if [ $opt_help -gt 0 ]; then
-  print_help "Run odoo in debug mode"\
+  print_help "Run odoo for debug mode"\
   "(C) 2015-2019 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
@@ -155,53 +155,45 @@ if [ -z "$opt_dbuser" ]; then
 fi
 if [ -n "$opt_modules" ]; then
   if [ $opt_keep -eq 0 ]; then
-    addons_list=
-    [ -d $odoo_root/addons ] && addons_list=$addons_list,$odoo_root/addons
-    [ -d $odoo_root/openerp/addons ] && addons_list=$addons_list,$odoo_root/openerp/addons
-    [ -d $odoo_root/odoo/addons ] && addons_list=$addons_list,$odoo_root/odoo/addons
-    [ -d $odoo_root/server/openerp/addons ] && addons_list=$addons_list,$odoo_root/server/openerp/addons
-    srcs=$(find $odoo_root  -not -path '*/__to_remove/*' -type d -name "$opt_modules")
-    [ -n "$srcs" ] && addons_list=$addons_list,$srcs
-    addons_list=${addons_list:1}
-    if [ -x /opt/odoo/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/get_test_dependencies.py ]; then
-      pushd /opt/odoo/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/ >/dev/null
+    PL="$(grep ^addons_path /etc/odoo/odoo10.conf|awk -F= '{print $2}')"
+    if [ -z "$($which odoo_dependencies.py 2>/dev/null)" ]; then
+      echo "Test incomplete!"
+      echo "File odoo_dependencies.py not found!"
+    else
       if [ "$opt_modules" == "all" ];then
-        depmods=$(python ./get_test_dependencies.py mod $addons_list)
+        depmods=$(odoo_dependencies.py -m $PL)
       else
-        depmods=$(python ./get_test_dependencies.py dep $addons_list $opt_modules)
+        depmods=$(odoo_dependencies.py -d $PL -PM $opt_modules)
       fi
       if [ -n "$depmods" -a $opt_test -eq 0 ]; then
         opt_modules="$opt_modules,$depmods"
       fi
-    else
-      echo "Test incomplete!"
-      echo "File /opt/odoo/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/travis/get_test_dependencies.py not found!"
     fi
-    opts="-i $opt_modules"
-    optcdb=""
-    [ $opt_test -ne 0 ] && opts="$opts --test-enable"
+    OPTS="-i $opt_modules"
+    OPTDB=""
+    [ $opt_test -ne 0 ] && OPTS="$OPTS --test-enable"
     create_db=1
   else
     mods=${opt_modules//,/ }
-    opti=
+    OPTI=
     xi=-i
-    optu=
+    OPTU=
     xu=-u
     for m in $mods; do
       r=$(psql -U$opt_dbuser $opt_db -tc "select state from ir_module_module where name='$m';")
       if [[ $r =~ uninstalled ]]; then
-        opti="$opti$xi$m"
+        OPTI="$OPTI$xi$m"
         xi=,
       else
-        optu="$optu$xu$m"
+        OPTU="$OPTU$xu$m"
         xu=,
       fi
     done
-    optsiu="$opti $optu"
+    OPTSIU="$OPTI $OPTU"
     alt=
     if [ $opt_exp -ne 0 -a -n "$opt_ofile" ]; then
       src=$(readlink -f $opt_ofile)
-      opts="--modules=$opt_modules --i18n-export=$src -lit_IT"
+      OPTS="--modules=$opt_modules --i18n-export=$src -lit_IT"
     elif [ $opt_exp -ne 0 -o $opt_imp -ne 0 ]; then
       srcs=$(find $odoo_root  -not -path '*/__to_remove/*' -type d -name "$opt_modules")
       f=0
@@ -229,23 +221,23 @@ if [ -n "$opt_modules" ]; then
         exit 1
       fi
       if [ $opt_imp -ne 0 ]; then
-        opts="--modules=$opt_modules --i18n-import=$src -lit_IT --i18n-overwrite"
+        OPTS="--modules=$opt_modules --i18n-import=$src -lit_IT --i18n-overwrite"
       else
-        opts="--modules=$opt_modules --i18n-export=$src -lit_IT"
+        OPTS="--modules=$opt_modules --i18n-export=$src -lit_IT"
       fi
     elif [ $opt_upd -ne 0 -o $opt_xtl -ne 0 ]; then
-      opts="$optsiu"
-      [ $opt_test -ne 0 ] && opts="$opts --test-enable"
+      OPTS="$OPTSIU"
+      [ $opt_test -ne 0 ] && OPTS="$OPTS --test-enable"
     else
-      opts="$optsiu"
+      OPTS="$OPTSIU"
     fi
   fi
 else
   if [ $opt_lang -ne 0 ]; then
-    opts=--load-language=it_IT
+    OPTS=--load-language=it_IT
   else
-    opts=""
-    optcdb=""
+    OPTS=""
+    OPTDB=""
   fi
 fi
 if [ -z "$opt_xport" ]; then
@@ -259,16 +251,16 @@ if [ -n "$opt_modules" -o $opt_upd -ne 0 -o $opt_xtl -ne 0 -o $opt_exp -ne 0 -o 
     fi
   fi
 fi
-optcdb="$optcdb --stop-after-init"
+OPTDB="$OPTDB --stop-after-init"
 if [ $opt_stop -gt 0 ]; then
-  opts="$opts --stop-after-init"
+  OPTS="$OPTS --stop-after-init"
   if [ $opt_exp -eq 0 -a $opt_imp -eq 0 -a  $opt_lang -eq 0 ]; then
-    [ $opt_test -ne 0 ] && opts="$opts --test-commit"
+    [ $opt_test -ne 0 ] && OPTS="$OPTS --test-commit"
   fi
 fi
 if [ -n "$opt_db" ]; then
-   opts="$opts -d $opt_db"
-   optcdb="$optcdb -d $opt_db"
+   OPTS="$OPTS -d $opt_db"
+   OPTDB="$OPTDB -d $opt_db"
 fi
 if [ $opt_touch -eq 0 ]; then
   [ $drop_db -gt 0 ] && run_traced "pg_db_active -a $opt_db; dropdb -U$opt_dbuser --if-exists $opt_db"
@@ -281,34 +273,44 @@ if [ $opt_touch -eq 0 ]; then
   if [ $create_db -gt 0 -a $odoo_ver -lt 10 ]; then
     run_traced "createdb -U$opt_dbuser $opt_db"
   fi
+  tty -s
+  if [ $? == 0 ]; then
+    OPT_CONF="--config=$confn --logfile=/dev/stdout"
+  else
+    OPT_CONF="--config=$confn --logfile=$HOME/$$.log"
+  fi
+  OPT_LLEV=
   if [ $opt_dry_run -eq 0 ]; then
     [ -f $HOME/.openerp_serverrc ] && rm -f $HOME/.openerp_serverrc
     [ -f $HOME/.odoorc ] && rm -f $HOME/.odoorc
     echo "\$ cp $confn $HOME/$lconfn"
     cp $confn $HOME/$lconfn
-    sed -i -e 's:^logfile *=.*:logfile = False:' $HOME/$lconfn
+    sed -i -e "s|^logfile *=.*|logfile = False|" $HOME/$lconfn
     if [ -n "$opt_xport" ]; then
-      sed -i -e "s:^xmlrpc_port *=.*:xmlrpc_port = $opt_xport:" $HOME/$lconfn
+    sed -i -e "s|^xmlrpc_port *=.*|xmlrpc_port = $opt_xport|" $HOME/$lconfn
+      OPT_CONF="$OPT_CONF --xmlrpc-port=$opt_xport"
     fi
     if [ -n "$opt_dbuser" ]; then
-      sed -i -e "s:^db_user *=.*:db_user = $opt_dbuser:" $HOME/$lconfn
+      sed -i -e "s|^db_user *=.*|db_user = $opt_dbuser|" $HOME/$lconfn
+      OPT_CONF="$OPT_CONF --db_user=$opt_dbuser"
     fi
     if [ -n "$opt_llvl" ]; then
-      sed -i -e "s/^log_level *=.*/log_level = $opt_llvl/" $HOME/$lconfn
+      sed -i -e "s|^log_level *=.*|log_level = $opt_llvl|" $HOME/$lconfn
+      OPT_LLEV="--log-level=$opt_llvl"
     fi
   fi
   if [ $create_db -gt 0 ]; then
     if [ -n "$depmods" -a $opt_test -ne 0 ]; then
-      run_traced "$script $optcdb --log-level=error -i $depmods"
+      run_traced "$script $OPTDB $OPT_CONF --log-level=error -i $depmods"
     else
-      run_traced "$script $optcdb --log-level=error"
+      run_traced "$script $OPTDB $OPT_CONF --log-level=error"
     fi
   fi
   echo "===================================================================="
   if [ $odoo_ver -lt 10 -a $opt_dry_run -eq 0 -a $opt_exp -eq 0 -a $opt_imp -eq 0 -a $opt_lang -eq 0 ]; then
-    opts="--debug $opts"
+    OPTS="--debug $OPTS"
   fi
-  run_traced "$script $opts"
+  run_traced "$script $OPT_CONF $OPT_LLEV $OPTS"
   if [ $VENV -ne 0 ]; then
     [ $opt_verbose -gt 0 ] && echo "\$ deactivate"
     deactivate
