[RUN] test nightly

diff --git a/clodoo/manage_db b/clodoo/manage_db
--- a/clodoo/manage_db
+++ b/clodoo/manage_db
@@ -123,11 +123,11 @@ declare_cfloop() {
     fi
 }
 
-OPTOPTS=(h        b        c        D             E        d      m         n           o       q           r           t         U          V           v)
-OPTDEST=(opt_help odoo_vid opt_conf opt_with_demo opt_tenv opt_DB opt_multi opt_dry_run opt_del opt_verbose opt_xmlport test_mode opt_dbuser opt_version opt_verbose)
-OPTACTI=(1        "="      "="      "*"           "*"      "="    1         1           1       0           "="         1         "="        "*"         "+")
-OPTDEFL=(1        "7.0"    ""       ""            ""       ""     -1        0           0       -1          ""          0         ""         ""          -1)
-OPTMETA=("help"   "branch" "file"   ""            ""       "name" ""        "noop"      "del"   "quiet"     "port"      "test"    "user"     "version"   "verbose")
+OPTOPTS=(h        b         c        D             E        d      m         n           o       q           r           t         U          V           v)
+OPTDEST=(opt_help odoo_vids opt_conf opt_with_demo opt_tenv opt_DB opt_multi opt_dry_run opt_del opt_verbose opt_xmlport test_mode opt_dbuser opt_version opt_verbose)
+OPTACTI=(1        "="       "="      "*"           "*"      "="    1         1           1       0           "="         1         "="        "*"         "+")
+OPTDEFL=(1        "7.0"     ""       ""            ""       ""     -1        0           0       -1          ""          0         ""         ""          -1)
+OPTMETA=("help"   "branch"  "file"   ""            ""       "name" ""        "noop"      "del"   "quiet"     "port"      "test"    "user"     "version"   "verbose")
 OPTHELP=("this help"\
  "branch: must be 7.0 or 8.0 or 9.0 or 10.0 or 11.0 (def 7.0)"\
  "configuration file (only update)"\
@@ -170,223 +170,239 @@ else
 fi
 sts=$STS_SUCCESS
 discover_multi
-odoo_fver=$(build_odoo_param FULLVER $odoo_vid)
-odoo_ver=$(build_odoo_param MAJVER $odoo_vid)
-if [ -z "$opt_dbuser" ]; then
-  opt_dbuser=$(build_odoo_param USER $odoo_vid)
+if [ "$odoo_vids" == "*" ]; then
+  [ $opt_multi -gt 0 ] && odoo_vids="11.0,10.0,9.0,8.0,7.0,6.1" || odoo_vids="7.0"
 fi
-if [ -z "$opt_xmlport" ]; then
-  opt_xmlport=$(build_odoo_param RPCPORT $odoo_vid)
-fi
-if [ "${HOSTNAME:0:3}" == "shs" ]; then
-  lgi_user=zeroadm
-elif [ "${HOSTNAME:0:7}" == "vg7odoo" ]; then
-  lgi_user=vg7admin
-else
-  lgi_user=admin
-fi
-if [ "$action" == "install" ]; then
-  if [ ! -d data ]; then
-    echo "Directory data/ not found!"
-    exit 1
+for odoo_vid in ${odoo_vids//,/ }; do
+  odoo_fver=$(build_odoo_param FULLVER $odoo_vid)
+  odoo_ver=$(build_odoo_param MAJVER $odoo_vid)
+  if [ -z "$opt_dbuser" ]; then
+    opt_dbuser=$(build_odoo_param USER $odoo_vid)
   fi
-  if [ ! -d code ]; then
-    echo "Directory code/ not found!"
-    exit 1
+  if [ -z "$opt_xmlport" ]; then
+    xmlport=$(build_odoo_param RPCPORT $odoo_vid)
+  else
+    xmlport=$opt_xmlport
   fi
-  declare_cfloop
-  for cf in $CFLOOP; do
-    if [ ! -f code/z0_install_$cf.conf ]; then
-      echo "Configuration file z0_install_$cf.conf not found!"
+  if [ "${HOSTNAME:0:3}" == "shs" ]; then
+    lgi_user=zeroadm
+  elif [ "${HOSTNAME:0:7}" == "vg7odoo" ]; then
+    lgi_user=vg7admin
+  else
+    lgi_user=admin
+  fi
+  if [ -n "$opt_DB" ]; then
+    opt_db=${opt_DB/./$odoo_ver}
+  else
+    opt_db=
+  fi
+  if [ "$action" == "install" ]; then
+    if [ ! -d data ]; then
+      echo "Directory data/ not found!"
       exit 1
     fi
-  done
-  run_traced "$TDIR/set_odoover_confn $odoo_fver $opt_DB -r$opt_xmlport -q $opt_tenv -u$lgi_user"
-  [ -f ~/.openerp_serverrc ] && run_traced "rm -f ~/.openerp_serverrc"
-  [ -f .odoorc ] && run_traced "rm -f .odoorc"
-  for cf in $CFLOOP; do
-    if [ "$cf" == "00" ]; then
-      if [ -n "$opt_DB" ]; then
-        optdb="-d $opt_DB -lit_IT"
-      else
-        optdb=
+    if [ ! -d code ]; then
+      echo "Directory code/ not found!"
+      exit 1
+    fi
+    declare_cfloop
+    for cf in $CFLOOP; do
+      if [ ! -f code/z0_install_$cf.conf ]; then
+        echo "Configuration file z0_install_$cf.conf not found!"
+        exit 1
       fi
-      run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf $optdb -r$opt_xmlport $opt_with_demo"
-    elif [ "$cf" == "09" -a $opt_del -eq 0 ]; then
-      [ $opt_verbose -gt 0 ] && echo "Warning: you must enable dropping DB using -o switch"
-    elif [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$cf[[:space:]] ]]; then
-      [ $opt_verbose -gt 0 ] && echo "Warning: phase $cf is just for demo (use -D switch to enable)"
-    else
-      if [ -n "$opt_DB" ]; then
-        db=$opt_DB
-      else
-        db=$(cat clodoo_last.conf|awk -F= '{print $2}')
-      fi
-      if [ "$cf" == "09" ]; then
-        if $(psql -l|grep -q $db); then
-          eval $WCMD
-          svcname=$(build_odoo_param SVCNAME $odoo_vid)
-          run_traced "sudo systemctl restart $svcname"
-          sleep 2
-          run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$opt_xmlport $opt_with_demo"
-          if $(psql -l|grep -q $db); then
-            run_traced "pg_db_active -wa $db; dropdb --if-exists -U$opt_dbuser $db"
-          fi
-          if $(psql -l|grep -q $db); then
-            echo "DB $db not dropped!"
-          fi
+    done
+    [ -n "$opt_db" ] && run_traced "$TDIR/set_odoover_confn $odoo_fver $opt_db -r$xmlport -q $opt_tenv -u$lgi_user"
+    [ -f ~/.openerp_serverrc ] && run_traced "rm -f ~/.openerp_serverrc"
+    [ -f .odoorc ] && run_traced "rm -f .odoorc"
+    for cf in $CFLOOP; do
+      if [ "$cf" == "00" ]; then
+        if [ -n "$db" ]; then
+          optdb="-d $db -lit_IT"
         else
-          echo "DB $db already dropped"
+          optdb=
         fi
-        sts=0
+        run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf $optdb -r$xmlport $opt_with_demo"
+      elif [ "$cf" == "09" -a $opt_del -eq 0 ]; then
+        [ $opt_verbose -gt 0 ] && echo "Warning: you must enable dropping DB using -o switch"
+      elif [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$cf[[:space:]] ]]; then
+        [ $opt_verbose -gt 0 ] && echo "Warning: phase $cf is just for demo (use -D switch to enable)"
       else
-        run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$opt_xmlport $opt_with_demo"
-        sts=$?
+        if [ -n "$opt_db" ]; then
+          db=$opt_db
+        else
+          db=$(cat clodoo_last.conf|awk -F= '{print $2}')
+        fi
+        if [ "$cf" == "09" ]; then
+          if $(psql -l|grep -q $db); then
+            datadir=$(build_odoo_param DDIR $odoo_vid search)
+            for f in $(grep -l "$db" $datadir/sessions/*); do run_traced "rm -f $f"; done
+            for f in $(grep -l "$db" /tmp//oe-sessions-odoo/*); do run_traced "rm -f $f"; done
+            [ -d $datadir/filestore/$db ] && run_traced "rm -fR $datadir/filestore/$db"
+            eval $WCMD
+            svcname=$(build_odoo_param SVCNAME $odoo_vid)
+            run_traced "sudo systemctl restart $svcname"
+            sleep 2
+            run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo"
+            if $(psql -l|grep -q $db); then
+              run_traced "pg_db_active -wa $db; dropdb --if-exists -U$opt_dbuser $db"
+            fi
+            if $(psql -l|grep -q $db); then
+              echo "DB $db not dropped!"
+            fi
+          else
+            echo "DB $db already dropped"
+          fi
+          sts=0
+        else
+          run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$cf.conf -d $db -r$xmlport $opt_with_demo"
+          sts=$?
+        fi
+      fi
+    done
+  elif [ "$action" == "update" -o "$action" == "module" -o "$action" == "translate" -o "$action" == "upgrade" ]; then
+    if [ -f "$opt_conf" ]; then
+      cf=$opt_conf
+    elif [ -f "$opt_conf.conf" ]; then
+      cf=$opt_conf.conf
+    elif [ -f "code/$opt_conf" ]; then
+      cf=code/$opt_conf
+    elif [ -f "code/$opt_conf.conf" ]; then
+      cf=code/$opt_conf.conf
+    else
+      cf=
+    fi
+    [ -n "$cf" ] && opts_cf="-c $cf" || opts_cf=""
+    declare_cfloop
+    if [ -n "$cf" ]; then
+      x=$(parse_URI "$cf" "" "+NAMEID+LOCAL")
+      x=${x: -2}
+      if [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$x[[:space:]] ]]; then
+        echo "This file require -D switch to be codeuted!"
+        exit 1
       fi
     fi
-  done
-elif [ "$action" == "update" -o "$action" == "module" -o "$action" == "translate" -o "$action" == "upgrade" ]; then
-  if [ -f "$opt_conf" ]; then
-    cf=$opt_conf
-  elif [ -f "$opt_conf.conf" ]; then
-    cf=$opt_conf.conf
-  elif [ -f "code/$opt_conf" ]; then
-    cf=code/$opt_conf
-  elif [ -f "code/$opt_conf.conf" ]; then
-    cf=code/$opt_conf.conf
-  else
-    cf=
-  fi
-  [ -n "$cf" ] && opts_cf="-c $cf" || opts_cf=""
-  declare_cfloop
-  if [ -n "$cf" ]; then
-    x=$(parse_URI "$cf" "" "+NAMEID+LOCAL")
-    x=${x: -2}
-    if [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$x[[:space:]] ]]; then
-      echo "This file require -D switch to be codeuted!"
+    if [ -z "$opt_db" ]; then
+      opt_db=".*"
+    fi
+    if [ "$cf" == "code/z0_install_00.conf" ]; then
+      DBlist="$opt_db -lit_IT"
+      found=1
+    else
+      DBlist=$(db_list)
+    fi
+    if [ -z "$DBlist" ]; then
+      if [ $found -eq 0 ]; then
+        [ $opt_verbose -gt 0 ] && echo "No DB found!"
+      else
+        [ $opt_verbose -gt 0 ] && echo "No DB found, owned by $opt_dbuser!"
+      fi
       exit 1
     fi
-  fi
-  if [ -z "$opt_DB" ]; then
-    opt_DB=".*"
-  fi
-  if [ "$cf" == "code/z0_install_00.conf" ]; then
-    DBlist="$opt_DB -lit_IT"
-    found=1
-  else
-    DBlist=$(db_list)
-  fi
-  if [ -z "$DBlist" ]; then
-    if [ $found -eq 0 ]; then
-      [ $opt_verbose -gt 0 ] && echo "No DB found!"
-    else
-      [ $opt_verbose -gt 0 ] && echo "No DB found, owned by $opt_dbuser!"
-    fi
-    exit 1
-  fi
-  $TDIR/set_odoover_confn $odoo_fver "$opt_DB" -r$opt_xmlport -q $opt_tenv -u$lgi_user
-  DBlist=${DBlist//,/ }
-  W4T=0
-  for db in $DBlist; do
-    if [ $W4T -eq 0 -o $opt_dry_run -ne 0 ]; then
-      W4T=1
-    else
-      eval $WCMD
-    fi
-    if [ "$action" == "module" ]; then
-      echo "$TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$opt_xmlport"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$opt_xmlport
-    elif [ "$action" == "upgrade" ]; then
-      echo "$TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$opt_xmlport"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$opt_xmlport
-      echo "$TDIR/clodoo.py $opts $opts_cf -A upgrade_modules -b$odoo_vid -u $cmdlist -d $db -r$opt_xmlport $opt_with_demo"
-      $TDIR/clodoo.py $opts $opts_cf -A upgrade_modules -b$odoo_vid -u $cmdlist -d $db -r$opt_xmlport $opt_with_demo
-      sts=$?
-      if [ $sts -ne $STS_SUCCESS ]; then
-        break
+    $TDIR/set_odoover_confn $odoo_fver "$opt_db" -r$xmlport -q $opt_tenv -u$lgi_user
+    DBlist=${DBlist//,/ }
+    W4T=0
+    for db in $DBlist; do
+      if [ $W4T -eq 0 -o $opt_dry_run -ne 0 ]; then
+        W4T=1
+      else
+        eval $WCMD
       fi
-    elif [ "$action" == "translate" ]; then
-      echo "$TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$opt_xmlport"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$opt_xmlport
-    elif [ -n "$cmdlist" -a "$cmdlist" == "upd_oemod" ]; then
-      echo "$TDIR/clodoo.py $opts -b$odoo_vid -c=code/z0_install_10.conf -d $db -r$opt_xmlport $opt_with_demo"
-      $TDIR/clodoo.py $opts -b$odoo_vid -c=code/z0_install_10.conf -d $db -r$opt_xmlport $opt_with_demo
-      [ $opt_dry_run -ne 0 ] || up_oemod $db $odoo_vid
-    elif [ -n "$cmdlist" -a "$cmdlist" == "translation" ]; then
-      echo "$TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$opt_xmlport"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$opt_xmlport
-    else
-      if [[ -n "$cmdlist" &&  -z "$cf" && "$cmdlist"  =~ [0-9,]+ ]]; then
-        for ph in $CFLOOP; do
-          if [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$ph[[:space:]] ]]; then
-            [ $opt_verbose -gt 0 ] && echo "Warning: phase $ph is just for demo (use -D switch to enable)"
-          else
-            run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$ph.conf -d $db -r$opt_xmlport $opt_with_demo"
-            sts=$?
-          fi
-          if [ $sts -ne $STS_SUCCESS ]; then
-            break
-          fi
-        done
-      elif [ -n "$cmdlist" ]; then
-        echo "$TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$opt_xmlport $opt_with_demo"
-        $TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$opt_xmlport $opt_with_demo
+      if [ "$action" == "module" ]; then
+        echo "$TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$xmlport"
+        [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$xmlport
+      elif [ "$action" == "upgrade" ]; then
+        echo "$TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$xmlport"
+        [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk -x$xmlport
+        echo "$TDIR/clodoo.py $opts $opts_cf -A upgrade_modules -b$odoo_vid -u $cmdlist -d $db -r$xmlport $opt_with_demo"
+        $TDIR/clodoo.py $opts $opts_cf -A upgrade_modules -b$odoo_vid -u $cmdlist -d $db -r$xmlport $opt_with_demo
         sts=$?
         if [ $sts -ne $STS_SUCCESS ]; then
           break
         fi
+      elif [ "$action" == "translate" ]; then
+        echo "$TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$xmlport"
+        [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$xmlport
+      elif [ -n "$cmdlist" -a "$cmdlist" == "upd_oemod" ]; then
+        echo "$TDIR/clodoo.py $opts -b$odoo_vid -c=code/z0_install_10.conf -d $db -r$xmlport $opt_with_demo"
+        $TDIR/clodoo.py $opts -b$odoo_vid -c=code/z0_install_10.conf -d $db -r$xmlport $opt_with_demo
+        [ $opt_dry_run -ne 0 ] || up_oemod $db $odoo_vid
+      elif [ -n "$cmdlist" -a "$cmdlist" == "translation" ]; then
+        echo "$TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$xmlport"
+        [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -l -d $db -x$xmlport
       else
-        if [ -z "$cf" ]; then
-          echo "Configuration file $opt_conf not found!"
-          exit 1
+        if [[ -n "$cmdlist" &&  -z "$cf" && "$cmdlist"  =~ [0-9,]+ ]]; then
+          for ph in $CFLOOP; do
+            if [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$ph[[:space:]] ]]; then
+              [ $opt_verbose -gt 0 ] && echo "Warning: phase $ph is just for demo (use -D switch to enable)"
+            else
+              run_traced "$TDIR/clodoo.py $opts -b$odoo_vid -c code/z0_install_$ph.conf -d $db -r$xmlport $opt_with_demo"
+              sts=$?
+            fi
+            if [ $sts -ne $STS_SUCCESS ]; then
+              break
+            fi
+          done
+        elif [ -n "$cmdlist" ]; then
+          echo "$TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$xmlport $opt_with_demo"
+          $TDIR/clodoo.py $opts $opts_cf -A $cmdlist -b$odoo_vid -d $db -r$xmlport $opt_with_demo
+          sts=$?
+          if [ $sts -ne $STS_SUCCESS ]; then
+            break
+          fi
+        else
+          if [ -z "$cf" ]; then
+            echo "Configuration file $opt_conf not found!"
+            exit 1
+          fi
+          echo "$TDIR/clodoo.py $opts $opts_cf -b$odoo_vid -c $cf -d $db -r$xmlport $opt_with_demo"
+          $TDIR/clodoo.py $opts $opts_cf -b$odoo_vid -c $cf -d $db -r$xmlport $opt_with_demo
+          sts=$?
         fi
-        echo "$TDIR/clodoo.py $opts $opts_cf -b$odoo_vid -c $cf -d $db -r$opt_xmlport $opt_with_demo"
-        $TDIR/clodoo.py $opts $opts_cf -b$odoo_vid -c $cf -d $db -r$opt_xmlport $opt_with_demo
-        sts=$?
       fi
-    fi
-  done
-elif [ "$action" == "rename_phase" ]; then
-  if [  -z "$cmdlist" ]; then
-    echo "Missed phase rename!"
-    echo "$THIS rename_phase old=new"
-    sts=1
-  else
-    IFS== read old new <<< "$cmdlist"
-    confn=$(ls code/*${old}.conf 2>/dev/null|head -n1)
-    if [ -z "$confn" ]; then
-      echo "phase $old not found!"
+    done
+  elif [ "$action" == "rename_phase" ]; then
+    if [  -z "$cmdlist" ]; then
+      echo "Missed phase rename!"
+      echo "$THIS rename_phase old=new"
       sts=1
     else
-      new_confn=${confn/$old/$new}
-      echo "mv $confn $new_confn"
-      mv $confn $new_confn
-      for datafn in $(ls data/*${old}.csv 2>/dev/null); do
-        new_datafn=${datafn/$old/$new}
-        echo "mv $datafn $new_datafn"
-        mv $datafn $new_datafn
-        f=$(basename $datafn)
-        n=$(basename $new_datafn)
-        echo "sed -e \"s|$f|$n|g\" -i $new_confn"
-        sed -e "s|$f|$n|g" -i $new_confn
-      done
-    fi
-  fi
-elif [ "$action" == "rename" ]; then
-  if [ -z "$opt_dbuser" ]; then
-    opt_dbuser=$(build_odoo_param USER $odoo_vid)
-  fi
-  DBlist=$(db_list)
-  DBlist=${DBlist//,/ }
-  for db in $DBlist; do
-    while IFS== read src tgt; do
-      if [ -n "$src" -a -n "$tgt" -a "$src" != "$tgt" ]; then
-        run_traced "psql -U$opt_dbuser -c \"update ir_module_module set name='$tgt' where name='$src';\" $db"
+      IFS== read old new <<< "$cmdlist"
+      confn=$(ls code/*${old}.conf 2>/dev/null|head -n1)
+      if [ -z "$confn" ]; then
+        echo "phase $old not found!"
+        sts=1
+      else
+        new_confn=${confn/$old/$new}
+        echo "mv $confn $new_confn"
+        mv $confn $new_confn
+        for datafn in $(ls data/*${old}.csv 2>/dev/null); do
+          new_datafn=${datafn/$old/$new}
+          echo "mv $datafn $new_datafn"
+          mv $datafn $new_datafn
+          f=$(basename $datafn)
+          n=$(basename $new_datafn)
+          echo "sed -e \"s|$f|$n|g\" -i $new_confn"
+          sed -e "s|$f|$n|g" -i $new_confn
+        done
       fi
-    done < ./moduli_alias.csv
-  done
-else
-  echo "Invalid action!"
-  sts=1
-fi
+    fi
+  elif [ "$action" == "rename" ]; then
+    if [ -z "$opt_dbuser" ]; then
+      opt_dbuser=$(build_odoo_param USER $odoo_vid)
+    fi
+    DBlist=$(db_list)
+    DBlist=${DBlist//,/ }
+    for db in $DBlist; do
+      while IFS== read src tgt; do
+        if [ -n "$src" -a -n "$tgt" -a "$src" != "$tgt" ]; then
+          run_traced "psql -U$opt_dbuser -c \"update ir_module_module set name='$tgt' where name='$src';\" $db"
+        fi
+      done < ./moduli_alias.csv
+    done
+  else
+    echo "Invalid action!"
+    sts=1
+  fi
+done
 exit $sts
