[RUN] test nightly

diff --git a/clodoo/manage_db b/clodoo/manage_db
--- a/clodoo/manage_db
+++ b/clodoo/manage_db
@@ -29,7 +29,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.3.4
+__version__=0.3.4.1
 
 
 up_oemod() {
@@ -77,11 +77,11 @@ db_list() {
     DBlist=
     local db user a b c
     local found=0
-    psql -Upostgres -tl > $HOME/tmp.log
+    psql -Upostgres -Atl > $HOME/tmp.log
     while IFS=\| read db user a b c; do
       ((found++))
-      db=$(echo $db)
-      user=$(echo $user)
+      # db=$(echo $db)
+      # user=$(echo $user)
       if [ -n "$db" -a "$user" == "$opt_dbuser" ]; then
         if [[ $db =~ $opt_DB ]]; then
           DBlist=$DBlist,$db
@@ -93,12 +93,25 @@ db_list() {
     echo "$DBlist"
 }
 
+declare_cfloop() {
+    if [ "$opt_conf" == "code/z0_install_00.conf" ]; then
+      if [ $opt_del -ne 0 ]; then
+        CFLOOP="09 00"
+      else
+        CFLOOP="00"
+      fi
+    elif [ -n "$cmdlist" ]; then
+      CFLOOP="${cmdlist//,/ }"
+    else
+      CFLOOP="$PHASE_LIST"
+    fi
+}
 
-OPTOPTS=(h        b          c        D             E        d      m         n           o       q           r           t         U          V           v)
-OPTDEST=(opt_help opt_branch opt_conf opt_with_demo opt_tenv opt_DB opt_multi opt_dry_run opt_del opt_verbose opt_xmlport test_mode opt_dbuser opt_version opt_verbose)
-OPTACTI=(1        "="        "="      "*"           "*"      "="    1         1           1       0           "="         1         "="        "*"         "+")
-OPTDEFL=(1        "7.0"      ""       ""            ""       ""     -1        0           0       -1          ""          0         ""         ""          -1)
-OPTMETA=("help"   "branch"   "file"   ""            ""       "name" ""        "noop"      "del"   "quiet"     "port"      "test"    "user"     "version"   "verbose")
+OPTOPTS=(h        b        c        D             E        d      m         n           o       q           r           t         U          V           v)
+OPTDEST=(opt_help odoo_vid opt_conf opt_with_demo opt_tenv opt_DB opt_multi opt_dry_run opt_del opt_verbose opt_xmlport test_mode opt_dbuser opt_version opt_verbose)
+OPTACTI=(1        "="      "="      "*"           "*"      "="    1         1           1       0           "="         1         "="        "*"         "+")
+OPTDEFL=(1        "7.0"    ""       ""            ""       ""     -1        0           0       -1          ""          0         ""         ""          -1)
+OPTMETA=("help"   "branch" "file"   ""            ""       "name" ""        "noop"      "del"   "quiet"     "port"      "test"    "user"     "version"   "verbose")
 OPTHELP=("this help"\
  "branch: must be 7.0 or 8.0 or 9.0 or 10.0 or 11.0 (def 7.0)"\
  "configuration file (only update)"\
@@ -140,25 +153,9 @@ else
   WCMD="sleep $SLEEP_TIME"
 fi
 sts=$STS_SUCCESS
-odoo_vid=$opt_branch
+discover_multi
 odoo_fver=$(build_odoo_param FULLVER $odoo_vid)
-odoo_ver=$(build_odoo_param FULLVER $odoo_vid)
-if [ $opt_multi -lt 0 ]; then
-  c=0
-  for v in 6.1 7.0 8.0 9.0 10.0 11.0; do
-    for p in "" v odoo- ODOO-; do
-      odoo_bin=$(build_odoo_param BIN $p$v search)
-      if [ -n "$odoo_bin" ] && [ -f "$odoo_bin" ]; then
-        ((c++))
-      fi
-    done
-  done
-  if [ $c -gt 2 ]; then
-    opt_multi=1
-  else
-    opt_multi=0
-  fi
-fi
+odoo_ver=$(build_odoo_param MAJVER $odoo_vid)
 if [ -z "$opt_dbuser" ]; then
   opt_dbuser=$(build_odoo_param USER $odoo_vid)
 fi
@@ -174,17 +171,7 @@ if [ "$action" == "install" ]; then
     echo "Directory code/ not found!"
     exit 1
   fi
-  if [ "$opt_conf" == "code/z0_install_00.conf" ]; then
-    if [ $opt_del -ne 0 ]; then
-      CFLOOP="09 00"
-    else
-      CFLOOP="00"
-    fi
-  elif [ -n "$cmdlist" ]; then
-    CFLOOP="${cmdlist//,/ }"
-  else
-    CFLOOP="$PHASE_LIST"
-  fi
+  declare_cfloop
   for cf in $CFLOOP; do
     if [ ! -f code/z0_install_$cf.conf ]; then
       echo "Configuration file z0_install_$cf.conf not found!"
@@ -226,6 +213,7 @@ elif [ "$action" == "update" -o "$action" == "module" -o "$action" == "translate
   else
     cf=
   fi
+  declare_cfloop
   if [ -n "$cf" ]; then
     x=$(parse_URI "$cf" "" "+NAMEID+LOCAL")
     x=${x: -2}
@@ -261,11 +249,11 @@ elif [ "$action" == "update" -o "$action" == "module" -o "$action" == "translate
       eval $WCMD
     fi
     if [ "$action" == "module" ]; then
-      echo "$TDIR/run_odoo_debug.sh $opt_branch -um $cmdlist -d $db -sk"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $opt_branch -um $cmdlist -d $db -s
+      echo "$TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk"
+      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -s
     elif [ "$action" == "upgrade" ]; then
-      echo "$TDIR/run_odoo_debug.sh $opt_branch -um $cmdlist -d $db -sk"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $opt_branch -um $cmdlist -d $db -s
+      echo "$TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -sk"
+      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -um $cmdlist -d $db -s
       echo "$TDIR/clodoo.py $opts -A upgrade_modules -b$odoo_fver -u $cmdlist -d $db -r$opt_xmlport $opt_with_demo"
       $TDIR/clodoo.py $opts -A upgrade_modules -b$odoo_fver -u $cmdlist -d $db -r$opt_xmlport $opt_with_demo
       sts=$?
@@ -273,32 +261,43 @@ elif [ "$action" == "update" -o "$action" == "module" -o "$action" == "translate
         break
       fi
     elif [ "$action" == "translate" ]; then
-      echo "$TDIR/run_odoo_debug.sh $opt_branch -l -d $db"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $opt_branch -l -d $db
+      echo "$TDIR/run_odoo_debug.sh $odoo_vid -l -d $db"
+      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -l -d $db
     elif [ -n "$cmdlist" -a "$cmdlist" == "upd_oemod" ]; then
       echo "$TDIR/clodoo.py $opts -b$odoo_fver -c=code/z0_install_10.conf -d $db -r$opt_xmlport $opt_with_demo"
       $TDIR/clodoo.py $opts -b$odoo_fver -c=code/z0_install_10.conf -d $db -r$opt_xmlport $opt_with_demo
-      [ $opt_dry_run -ne 0 ] || up_oemod $db $opt_branch
+      [ $opt_dry_run -ne 0 ] || up_oemod $db $odoo_vid
     elif [ -n "$cmdlist" -a "$cmdlist" == "translation" ]; then
-      echo "$TDIR/run_odoo_debug.sh $opt_branch -l -d $db"
-      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $opt_branch -l -d $db
-    elif [ -n "$cmdlist" ]; then
-      echo "$TDIR/clodoo.py $opts -A $cmdlist  -b$odoo_fver -d $db -r$opt_xmlport $opt_with_demo"
-      $TDIR/clodoo.py $opts -A $cmdlist -b$odoo_fver -d $db -r$opt_xmlport $opt_with_demo
-      sts=$?
-      if [ $sts -ne $STS_SUCCESS ]; then
-        break
-      fi
+      echo "$TDIR/run_odoo_debug.sh $odoo_vid -l -d $db"
+      [ $opt_dry_run -ne 0 ] || $TDIR/run_odoo_debug.sh $odoo_vid -l -d $db
     else
-      if [ -z "$cf" ]; then
-        echo "Configuration file $opt_conf not found!"
-        exit 1
-      fi
-      echo "$TDIR/clodoo.py $opts -b$odoo_fver -c $cf -d $db -r$opt_xmlport $opt_with_demo"
-      $TDIR/clodoo.py $opts -b$odoo_fver -c $cf -d $db -r$opt_xmlport $opt_with_demo
-      sts=$?
-      if [ $sts -ne $STS_SUCCESS ]; then
-        break
+      if [[ -n "$cmdlist" &&  -z "$cf" && "$cmdlist"  =~ [0-9,]+ ]]; then
+        for ph in $CFLOOP; do
+          if [ -z "$opt_with_demo" ] && [[ " $DEMO_PHASE_LIST " =~ [[:space:]]$ph[[:space:]] ]]; then
+            [ $opt_verbose -gt 0 ] && echo "Warning: phase $ph is just for demo (use -D switch to enable)"
+          else
+            run_traced "$TDIR/clodoo.py $opts -b$odoo_fver -c code/z0_install_$ph.conf -d $db -r$opt_xmlport $opt_with_demo"
+            sts=$?
+          fi
+          if [ $sts -ne $STS_SUCCESS ]; then
+            break
+          fi
+        done
+      elif [ -n "$cmdlist" ]; then
+        echo "$TDIR/clodoo.py $opts -A $cmdlist -b$odoo_fver -d $db -r$opt_xmlport $opt_with_demo"
+        $TDIR/clodoo.py $opts -A $cmdlist -b$odoo_fver -d $db -r$opt_xmlport $opt_with_demo
+        sts=$?
+        if [ $sts -ne $STS_SUCCESS ]; then
+          break
+        fi
+      else
+        if [ -z "$cf" ]; then
+          echo "Configuration file $opt_conf not found!"
+          exit 1
+        fi
+        echo "$TDIR/clodoo.py $opts -b$odoo_fver -c $cf -d $db -r$opt_xmlport $opt_with_demo"
+        $TDIR/clodoo.py $opts -b$odoo_fver -c $cf -d $db -r$opt_xmlport $opt_with_demo
+        sts=$?
       fi
     fi
   done
diff --git a/travis_emulator/topep8 b/travis_emulator/topep8
--- a/travis_emulator/topep8
+++ b/travis_emulator/topep8
@@ -7,10 +7,16 @@
 
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
-  if [ -e $x/z0librc ]; then
-    . $x/z0librc
-    Z0LIBDIR=$x
+PYTHONPATH=$(echo -e "import sys\nprint str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1]"|python)
+for d in $TDIR $TDIR/.. ${PYTHONPATH//:/ } /etc; do
+  if [ -e $d/z0librc ]; then
+    . $d/z0librc
+    Z0LIBDIR=$d
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  elif [ -d $d/z0lib ]; then
+    . $d/z0lib/z0librc
+    Z0LIBDIR=$d/z0lib
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
     break
   fi
@@ -19,15 +25,142 @@ if [ -z "$Z0LIBDIR" ]; then
   echo "Library file z0librc not found!"
   exit 2
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $TDIR/../clodoo $TDIR/../../clodoo . .. $HOME/dev")
+ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/clodoo $HOME/dev" "clodoo")
 if [ -z "$ODOOLIBDIR" ]; then
   echo "Library file odoorc not found!"
   exit 2
 fi
 . $ODOOLIBDIR
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
+TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. ${PYTHONPATH//:/ } . .. $HOME/tools/travis_emulator $HOME/dev" "travis_emulator")
+if [ -z "$TRAVISLIBDIR" ]; then
+  echo "Library file travisrc not found!"
+  exit 2
+fi
+. $TRAVISLIBDIR
 
-__version__=0.2.0
+__version__=0.2.0.2
+LIST_REQ=~/dev/pypi/lisa/lisa/list_requirements.py
+YAML_TMPL=~/dev/pypi/maintainer-quality-tools/maintainer-quality-tools/sample_files/.travis.yml
 
+
+format_yaml() {
+    local fn=$1
+    if [ -f $fn ]; then
+      local fntmp=$fn.new
+      local fntmpl=$YAML_TMPL
+      rm -f $fntmp
+      local a f line lne p wf=0
+      f=$(readlink -e $fn)
+      p=$(dirname $f)
+      while IFS= read -r line || [ -n "$line" ]; do
+        if [ -n "$odoo_vid" ]; then
+          line=${line/\$TRAVIS_BRANCH/$odoo_fver}
+        fi
+        lne=$(echo $line)
+        if [ -z "$line" ]; then
+          if [ $wf -eq 1 ]; then
+            echo "# Use Zeroincombenze(R) tools">>$fntmp
+            echo "  - git clone https://github.com/zeroincombenze/tools.git \${HOME}/tools --single-branch --depth=1">>$fntmp
+            echo "  - mv \${HOME}/tools/maintainer-quality-tools \${HOME}">>$fntmp
+            echo "  - export PATH=\${HOME}/maintainer-quality-tools/travis:\${PATH}">>$fntmp
+            wf=0
+          fi
+          echo "$line">>$fntmp
+        elif [ "$line" == "before_install:" ]; then
+          wf=1
+          echo "$line">>$fntmp
+          if [ $opt_debug -ne 0 ]; then
+            echo "  - export TRAVIS_DEBUG_MODE=\"1\"">>$fntmp
+          fi
+        elif [ "$line" == "install:" ]; then
+          echo "$line">>$fntmp
+          if [ $opt_ut7 -eq 0 ]; then
+            echo "  - ln -s \${HOME}/build/\${ODOO_REPO} \${HOME}/\${ODOO_REPO#*/}-\${VERSION}">>$fntmp
+            echo "  - pip install -r \${HOME}/maintainer-quality-tools/requirements.txt">>$fntmp
+            echo "  - pip install -q QUnitSuite flake8 coveralls pylint \"pywebdav<0.9.8\"">>$fntmp
+            echo "  - export INCLUDE=\$(getaddons.py -m \${HOME}/build/\${ODOO_REPO}/openerp/addons \${HOME}/build/\${ODOO_REPO}/addons)">>$fntmp
+          fi
+          echo "  # tests of document_ftp and delivery fail. The following two are excluded because they depend on delivery">>$fntmp
+          echo "  - export EXCLUDE=hw_scanner,hw_escpos,document_ftp,delivery,stock_invoice_directly,claim_from_delivery">>$fntmp
+          echo "  - export INSTALL_OPTIONS=\"--without-demo=account\"">>$fntmp
+          echo "  # - cp \${HOME}/maintainer-quality-tools/cfg/.coveragerc .">>$fntmp
+        elif [ "$line" == "# Odoo yaml template for travis-ci" ]; then
+          :
+        elif [ "$line" == "#   - export TRAVIS_DEBUG_MODE=\"1\"" ]; then
+          if [ $opt_debug -eq 0 ]; then
+            echo "#   - export TRAVIS_DEBUG_MODE=\"1\"">>$fntmp
+          fi
+        elif [ "$line" == "  - TRANSIFEX=\"1\"" ]; then
+          :
+        elif [ "$line" == "  - TESTS=\"1\" ODOO_REPO=\"OCA/OCB\"" ]; then
+          if [ "$PKGNAME" == "OCB" ]; then
+            echo "  - TESTS=\"1\" ODOO_REPO=\"\$TRAVIS_REPO_SLUG\"">>$fntmp
+          else
+            echo "$line">>$fntmp
+          fi
+        elif [ "$line" == "  - TESTS=\"1\" ODOO_REPO=\"odoo/odoo\"" ]; then
+          if [ "$PKGNAME" == "OCB" ]; then
+            :
+          else
+            echo "$line">>$fntmp
+          fi
+        elif [ "$line" == "  - travis_install_nightly" ]; then
+          if [ "$PKGNAME" == "OCB" ]; then
+            echo "# $line">>$fntmp
+          else
+            echo "$line">>$fntmp
+          fi
+        elif [ "$line" == "# [//]: # (addons)" ]; then
+          a=${a//,/ }
+          for f in $s; do
+            if [ "$f" == "PyXB" ]; then
+              f=$f==1.2.4
+            elif [ "$f" == "Pillow" ]; then
+              f=$f==3.4.2
+            fi
+            echo "  - pip install $f">>$fntmp
+          done
+        elif [ "$line" == "  - LINT_CHECK=\"1\"" ]; then
+          if [ "$PKGNAME" == "OCB" ]; then
+            echo "# $line">>$fntmp
+          else
+            echo "$line">>$fntmp
+          fi
+        elif [ "$line" == "#     Search your packages here:" ]; then
+          for f in expect-dev python-lxml python-simplejson python-serial python-yaml; do
+            echo "      - $f">>$fntmp
+          done
+          echo "$line">>$fntmp
+        elif [ "$line" == "  - ln -s \${HOME}/build/\${ODOO_REPO} \${HOME}/\${ODOO_REPO#*/}-\${VERSION}" ]; then
+          if [ $opt_ut7 -ne 0 ]; then
+            echo "# $line">>$fntmp
+          else
+            echo "$line">>$fntmp
+          fi
+        elif [ "$line" == "  - pip install -r \${HOME}/maintainer-quality-tools/requirements.txt" ]; then
+          if [ $opt_ut7 -ne 0 ]; then
+            echo "# $line">>$fntmp
+          else
+            echo "$line">>$fntmp
+          fi
+        elif [ "$line" == "  - export INCLUDE=\$(getaddons.py -m \${HOME}/build/\${ODOO_REPO}/openerp/addons \${HOME}/build/\${ODOO_REPO}/addons)" ]; then
+          if [ $opt_ut7 -ne 0 ]; then
+            echo "# $line">>$fntmp
+          else
+            echo "$line">>$fntmp
+          fi
+        else
+          echo "$line">>$fntmp
+        fi
+      done < "$fntmpl"
+    fi
+}
 
 format_xml() {
     local fn=$1
@@ -104,7 +237,6 @@ format_xml() {
             act=0
           fi
         fi
-        # echo "$level)$lne" #debug
         if [ -z "$line" ]; then
           if [ -z "$lne" ]; then
             line="$lne"
@@ -120,12 +252,6 @@ format_xml() {
         fi
         echo "$line">>$fntmp
       done < "$fn"
-      # if [ "$(diff -q $fn $fntmp)" ]; then
-      #   run_traced "cp -p $fn $fn.bak"
-      #   run_traced "mv $fntmp $fn"
-      # else
-      #   rm -f $fntmp
-      # fi
     fi
 }
 
@@ -150,7 +276,7 @@ OPTHELP=("this help"\
  "do nothing (dry-run)"\
  "output filename, leave source unchanged rather than source becomes .bak"\
  "silent mode"\
- "update unit test source to odoo<8.0"\
+ "update unit test source to odoo<8.0 or create yaml old style"\
  "show version"\
  "verbose mode"\
  "Undocumented")
@@ -166,6 +292,14 @@ if [ $opt_help -gt 0 ]; then
   "(C) 2015-2018 by zeroincombenze(R)\nhttp://www.zeroincombenze.it\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
+
+opts_travis
+CFG_init
+conf_default
+link_cfg $DIST_CONF $TCONF
+if [ $opt_verbose -gt 1 ]; then set -x; fi
+init_travis
+
 if [ -d "$pathname" ]; then
   path=$(readlink -f $pathname)
   if [ -z "$basename" ]; then
@@ -220,6 +354,8 @@ for fl in $LIST; do
   cd $p
   if [ "${f: -4}" == ".xml" ]; then
     format_xml $f
+  elif [ "${f: -4}" == ".yml" ]; then
+    format_yaml $f
   else
     mime=$(file -b --mime-type $f)
     if [ "$mime" == "text/x-python" -o "${f: -3}" == ".py" ]; then
