[FIX] z0bug_odoo old data for mk_test_env

diff --git a/clodoo/manage_db b/clodoo/manage_db
--- a/clodoo/manage_db
+++ b/clodoo/manage_db
@@ -6,31 +6,52 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2020 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
+READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
+export READLINK
+# Based on template 1.0.2.7
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/../z0lib /home/odoo/devel/../../z0lib /home/odoo/devel/../../z0lib/z0lib; do
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
+for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
 if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found!"
-  exit 2
+  echo "Library file z0librc not found in <$PYPATH>!"
+  exit 72
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "clodoo")
-if [ -z "$ODOOLIBDIR" ]; then
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
+ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
+if [[ -z "$ODOOLIBDIR" ]]; then
   echo "Library file odoorc not found!"
-  exit 2
+  exit 72
 fi
 . $ODOOLIBDIR
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
 RUNDIR=$(readlink -e $TESTDIR/..)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
 
-__version__=0.3.36
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+CLR="\e[0m"
+
+__version__=0.3.36.1
 
 
 up_oemod() {
@@ -155,7 +176,7 @@ set_opt_conf() {
 
 OPTOPTS=(h        B       b         c        D       d      m         n           o             q           r           t         U          V           v           w       x)
 OPTDEST=(opt_help opt_dbg odoo_vids opt_conf opt_del opt_DB opt_multi opt_dry_run opt_with_demo opt_verbose opt_xmlport test_mode opt_dbuser opt_version opt_verbose opt_way opt_exit)
-OPTACTI=(1        1       "="       "="      1       "="    1         1           "*"           0           "="         1         "="        "*"         "+"         "="     1)
+OPTACTI=("+"      1       "="       "="      1       "="    1         1           "*"           0           "="         1         "="        "*"         "+"         "="     1)
 OPTDEFL=(1        0       "10.0"    ""       0       ""     -1        0           ""            -1          ""          0         ""         ""          -1          ""      0)
 OPTMETA=("help"   ""      "branch"  "file"   "del"   "name" ""        "noop"      ""            "quiet"     "port"      "test"    "user"     "version"   "verbose"   "A|E"   "")
 OPTHELP=("this help"\
@@ -180,11 +201,11 @@ PHASE_LIST="00 01 02 03 10 11 12 13 14 15 16 17 18 19 20 22 30 31 32 50 51 53 54
 DEMO_PHASE_LIST="50 51 53 54 55 61 62"
 
 parseoptargs "$@"
-if [ "$opt_version" ]; then
+if [[ "$opt_version" ]]; then
   echo "$__version__"
   exit 0
 fi
-if [ $opt_help -gt 0 ]; then
+if [[ $opt_help -gt 0 ]]; then
   print_help "Manage Cloud DB(s) \n"\
   "Action may be on of: action,install,update,upgrade,module,translate,reassign,rename,rename_phase\ncmdlist of action may be upd_oemod or clodoo action\ncmdlist of module,upgrade is module list\ncmdlist of install/update is phase list: $PHASE_LIST\ncmdlist of reassign is new username\ncmdlist of rename_phase (phase) is old=new\ncmdlist of rename is a csv filename with module renames list\n\n(C) 2015-2020 by zeroincombenze(R)\nhttps://zeroincombenze-tools.readthedocs.io/\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
diff --git a/clodoo/manage_odoo b/clodoo/manage_odoo
--- a/clodoo/manage_odoo
+++ b/clodoo/manage_odoo
@@ -7,33 +7,46 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
+# Based on template 1.0.2.7
 THIS=$(basename "$0")
-TDIR=$($READLINK -f $(dirname $0))
-[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
-PYPATH=$(echo -e "import os,sys\np=[x for x in (os.environ['PATH']+':$TDIR:..:$HOME_DEV').split(':') if x not in sys.path];p.extend(sys.path);print(' '.join(p))"|python)
+TDIR=$(readlink -f $(dirname $0))
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
 if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found!"
-  exit 2
+  echo "Library file z0librc not found in <$PYPATH>!"
+  exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
 ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
-if [ -z "$ODOOLIBDIR" ]; then
+if [[ -z "$ODOOLIBDIR" ]]; then
   echo "Library file odoorc not found!"
-  exit 2
+  exit 72
 fi
 . $ODOOLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
 
-__version__=0.3.36
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+CLR="\e[0m"
+
+__version__=0.3.36.1
 
 
 explore() {
@@ -177,7 +190,7 @@ do_action() {
 OPTOPTS=(h        B         b          c        D                  d        f       H           L         m         n            O         o         P        p         q           s          u          V           v           x         y)
 OPTLONG=(help     ""        branch     config   deploy-mode        ""       ""      humdrum     ""        ""        dry_run      git-org   odoo-path ""       ""        quiet       no-stop    username   version     verbose)
 OPTDEST=(opt_help opt_nobin opt_branch opt_conf opt_deploy         opt_deps opt_def opt_humdrum opt_noloc opt_multi opt_dry_run  opt_org   opt_odir  opt_nopy opt_pyver opt_verbose opt_nostop opt_user   opt_version opt_verbose opt_excl  opt_yes)
-OPTACTI=(1        1         "="        "="      "="                "="      1       1           1         1         1            "="       "="       1        "="       1           1          "="        "*>"        "+"         "="       1)
+OPTACTI=("+"      1         "="        "="      "="                "="      1       1           1         1         1            "="       "="       1        "="       1           1          "="        "*>"        "+"         "="       1)
 OPTDEFL=(0        0         ""         ""       ""                 ""       0       0           0         0         0            "zero"    ""        0        ""        -1          0          ""         ""          -1          ""        0)
 OPTMETA=("help"   ""        "branch"   "file"   "tree|server|odoo" "dirs"   ""      ""          ""        ""        "do nothing" "git-org" "path"    ""       ""        "verbose"   ""         "username" "version"   "verbose"   "modules" "")
 OPTHELP=("this help"
@@ -221,7 +234,7 @@ if [[ $opt_help -gt 0 ]]; then
   exit $STS_SUCCESS
 fi
 if [[ "$actions" == "help" ]]; then
-  man $TDIR/$THIS.man
+  man $(dirname $0)/man/man8/$(basename $0).8.gz
   exit 0
 fi
 
diff --git a/clodoo/oe_watchdog b/clodoo/oe_watchdog
--- a/clodoo/oe_watchdog
+++ b/clodoo/oe_watchdog
@@ -9,27 +9,46 @@
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
 # (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 #
+READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
+export READLINK
+# Based on template 1.0.2.7
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])"|python)
-for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../.. $TDIR/../../z0lib $TDIR/../../z0lib/z0lib $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
-  if [ -e $d/z0librc ]; then
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
+for d in $PYPATH /etc; do
+  if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
-if [ -z "$Z0LIBDIR" ]; then
-  echo "Library file z0librc not found!"
-  exit 2
+if [[ -z "$Z0LIBDIR" ]]; then
+  echo "Library file z0librc not found in <$PYPATH>!"
+  exit 72
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/dev ${PYPATH//:/ } . .." "clodoo")
-if [ -z "$ODOOLIBDIR" ]; then
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
+ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
+if [[ -z "$ODOOLIBDIR" ]]; then
   echo "Library file odoorc not found!"
-  exit 2
+  exit 72
 fi
 . $ODOOLIBDIR
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
+
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+CLR="\e[0m"
 
 __version__=0.1.27.5
 
@@ -226,28 +245,28 @@ test_hung_up () {
 }
 
 conf_default () {
-    set_cfg_def "DEV_HOST" "shsdev16"
-    set_cfg_def "PRD_HOST" "shsprd14"
+    CFG_set "DEV_HOST" "shsdev16"
+    CFG_set "PRD_HOST" "shsprd14"
     # set_cfg_def "ODOO_SETUP" "__openerp__.py"
-    set_cfg_def "SVC_NAME" ""
-    set_cfg_def "login_user" "zeroadm"
-    set_cfg_def "login_password" "Wg\"0JK!P"
-    set_cfg_def "ODOO_VID" "v7"
-    set_cfg_def "CLODIR" "/opt/odoo/clodoo"
-    set_cfg_def "CLOBIN" "/opt/odoo/tools/clodoo"
-    set_cfg_def "ODOO_CONF" ""
-    set_cfg_def "ODOO_LOG" ""
-    set_cfg_def "MAX_RETRY" "3"
-    set_cfg_def "TIME_SLEEP" "90"
-    set_cfg_def "TIME_WAIT" "10"
-    set_cfg_def "HELLO_CTR" "21"
-    set_cfg_def "HUPTST_CTR" "3"
-    set_cfg_def "HUPTST_TAIL" "0"
-    set_cfg_def "DEBUG_MODE" "0"
-    set_cfg_def "DBFILTER" ".*"
-    set_cfg_def "PG_USER" "postgres"
-    set_cfg_def "DB_USER" ""
-    set_cfg_def "ODOO_MULTI_VERSION" "0"
+    CFG_set "SVC_NAME" ""
+    CFG_set "login_user" "zeroadm"
+    CFG_set "login_password" "Wg\"0JK!P"
+    CFG_set "ODOO_VID" "v7"
+    CFG_set "CLODIR" "/opt/odoo/clodoo"
+    CFG_set "CLOBIN" "/opt/odoo/tools/clodoo"
+    CFG_set "ODOO_CONF" ""
+    CFG_set "ODOO_LOG" ""
+    CFG_set "MAX_RETRY" "3"
+    CFG_set "TIME_SLEEP" "90"
+    CFG_set "TIME_WAIT" "10"
+    CFG_set "HELLO_CTR" "21"
+    CFG_set "HUPTST_CTR" "3"
+    CFG_set "HUPTST_TAIL" "0"
+    CFG_set "DEBUG_MODE" "0"
+    CFG_set "DBFILTER" ".*"
+    CFG_set "PG_USER" "postgres"
+    CFG_set "DB_USER" ""
+    CFG_set "ODOO_MULTI_VERSION" "0"
     TCONF=/etc/odoo/oe_watchdog.conf
     if [ ! -f $TCONF -a ! -f $TCONF.sample ]; then
       TCONF=/etc/oe_watchdog.conf
@@ -264,7 +283,7 @@ conf_default () {
 
 OPTOPTS=(h        D      K        n            s            V           v           X)
 OPTDEST=(opt_help opt_DB opt_cron opt_dry_run  opt_svc_name opt_version opt_verbose opt_lxs)
-OPTACTI=(1        "=>"   "1>"     "1>"         "=>"         "*>"        1           "1>")
+OPTACTI=("+"      "=>"   "1>"     "1>"         "=>"         "*>"        1           "1>")
 OPTDEFL=(1        ""     0        0            ""           ""          0           0)
 OPTMETA=("help"   "db"   "cron"   "do nothing" "svc_name"   "version"   "verbose"   "")
 OPTHELP=("this help"\
diff --git a/odoo_score/run_odoo_debug b/odoo_score/run_odoo_debug
--- a/odoo_score/run_odoo_debug
+++ b/odoo_score/run_odoo_debug
@@ -3,21 +3,23 @@
 
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
+# Based on template 1.0.2.7
 THIS=$(basename "$0")
-TDIR=$($READLINK -f $(dirname $0))
-[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
-PYPATH=$(echo -e "import os,sys\np=[x for x in (os.environ['PATH']+':$TDIR:..:$HOME_DEV').split(':') if x not in sys.path];p.extend(sys.path);print(' '.join(p))"|python)
+TDIR=$(readlink -f $(dirname $0))
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
 if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found!"
+  echo "Library file z0librc not found in <$PYPATH>!"
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
@@ -29,7 +31,18 @@ fi
 . $ODOOLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
 
-__version__=1.0.3
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+CLR="\e[0m"
+
+__version__=1.0.3.6
 
 run_traced_debug() {
     if [ $opt_verbose -gt 1 ]; then
@@ -73,12 +86,11 @@ check_for_modules() {
 }
 
 
-
-OPTOPTS=(h        B       b          c        d        e       f         k        i       I       l        L        m           M         n           o         O      p        s        T        t         U          u       V           v           w       W        x)
-OPTDEST=(opt_help opt_dbg opt_branch opt_conf opt_db   opt_exp opt_force opt_keep opt_imp opt_xtl opt_lang opt_llvl opt_modules opt_multi opt_dry_run opt_ofile opt_ou opt_odir opt_stop opt_test opt_touch opt_dbuser opt_upd opt_version opt_verbose opt_web opt_venv opt_rport)
-OPTACTI=(1        1       "=>"       "="      "="      1       1         1        1       1       1        "="      "="         1         1           "="       1      "="      1        1        1         "="        1       "*>"        "+"         1       1        "=")
-OPTDEFL=(1        0       ""         ""       ""       0       0         0        0       0       0        ""       ""          -1        0           ""        0      ""       0        0        0         ""         0       ""          -1          0       0        "")
-OPTMETA=("help"   ""      "branch"   "fname"  "dbname" ""      ""        ""       ""      ""      ""       "level"  "modules"   ""        "no op"     "file"    ""     "dir"    ""       ""       "touch"   "user"     ""      "version"   "verbose"   0       ""       "port")
+OPTOPTS=(h        B       b          c        d        e       f         k        i       I       l        L        m           M         n           o         O      p        P         s        T        t         U          u       V           v           w       W        x)
+OPTDEST=(opt_help opt_dbg opt_branch opt_conf opt_db   opt_exp opt_force opt_keep opt_imp opt_xtl opt_lang opt_llvl opt_modules opt_multi opt_dry_run opt_ofile opt_ou opt_odir opt_qport opt_stop opt_test opt_touch opt_dbuser opt_upd opt_version opt_verbose opt_web opt_venv opt_rport)
+OPTACTI=("+"      1       "=>"       "="      "="      1       1         1        1       1       1        "="      "="         1         1           "="       1      "="      "="       1        1        1         "="        1       "*>"        "+"         1       1        "=")
+OPTDEFL=(1        0       ""         ""       ""       0       0         0        0       0       0        ""       ""          -1        0           ""        0      ""       ""        0        0        0         ""         0       ""          -1          0       0        "")
+OPTMETA=("help"   ""      "branch"   "fname"  "dbname" ""      ""        ""       ""      ""      ""       "level"  "modules"   ""        "no op"     "file"    ""     "dir"    "port"    ""       ""       "touch"   "user"     ""      "version"   "verbose"   0       ""       "port")
 OPTHELP=("this help"
     "debug mode"
     "odoo branch (version id)"
@@ -97,6 +109,7 @@ OPTHELP=("this help"
     "output file (if export multiple modules)"
     "use openupgrade, if avaiable"
     "odoo root path"
+    "psql port"
     "stop after init"
     "execute odoo test on module"
     "touch config file, do not run odoo"
@@ -140,25 +153,41 @@ manifest=$(build_odoo_param MANIFEST $odoo_vid)
 create_db=0
 drop_db=0
 depmods=""
+
 if [[ -n "$opt_rport" ]]; then
     RPCPORT=$opt_rport
-elif [[ $opt_test -ne 0 ]]; then
-    RPCPORT=$(build_odoo_param RPCPORT $odoo_vid DEBUG)
-elif [[ -z "$CONFN" || ( $opt_force -ne 0 && $opt_web -ne 0 ) ]]; then
-    RPCPORT=$(build_odoo_param RPCPORT $odoo_vid $GIT_ORGNM)
-else
+elif [[ -n "$CONFN" && $opt_test -eq 0 && $opt_force -eq 0 && $opt_web -eq 0 ]]; then
     RPCPORT=$(grep ^xmlrpc_port $CONFN | awk -F= '{print $2}' | tr -d " ")
+    [[ -z "$RPCPORT" ]] && RPCPORT=$(grep ^http_port $CONFN | awk -F= '{print $2}' | tr -d " ")
 fi
+if [[ -z "$RPCPORT" ]]; then
+    if [[ $opt_web -ne 0 ]]; then
+        RPCPORT=$(build_odoo_param RPCPORT $odoo_vid $GIT_ORGNM)
+    elif [[ $opt_test -ne 0 ]]; then
+        RPCPORT=$(build_odoo_param RPCPORT $odoo_vid DEBUG)
+    else
+        RPCPORT=$(build_odoo_param RPCPORT $odoo_vid)
+    fi
+fi
+
 if [[ -n "$opt_dbuser" ]]; then
     DB_USER=$opt_dbuser
-elif [[ -z "$CONFN" || $opt_force -ne 0 ]]; then
-  if [[ $opt_web -ne 0 ]]; then
-      DB_USER=$(build_odoo_param DB_USER $odoo_vid $GIT_ORGNM)
-  else
-      DB_USER=$(build_odoo_param DB_USER $odoo_vid DEBUG)
-  fi
-else
-  DB_USER=$(grep ^db_user $CONFN | awk -F= '{print $2}' | tr -d " ")
+elif [[ -n "$CONFN" && $opt_force -eq 0 ]]; then
+    DB_USER=$(grep ^db_user $CONFN | awk -F= '{print $2}' | tr -d " ")
+fi
+if [[ -z "$DB_USER" ]]; then
+    if [[ $opt_web -ne 0 ]]; then
+        DB_USER=$(build_odoo_param DB_USER $odoo_vid $GIT_ORGNM)
+    else
+        DB_USER=$(build_odoo_param DB_USER $odoo_vid DEBUG)
+    fi
+fi
+
+if [[ -n "$opt_qport" ]]; then
+    DB_PORT=$opt_qport
+elif [[ -n "$CONFN" && $opt_force -eq 0 ]]; then
+    DB_PORT=$(grep ^db_port $CONFN | awk -F= '{print $2}' | tr -d " ")
+    [[ $DB_PORT == "False" ]] && unset DB_PORT
 fi
 
 if [[ $opt_test -ne 0 ]]; then
@@ -228,7 +257,8 @@ if [[ -n "$opt_modules" ]]; then
         fi
         OPTS="-i $opt_modules"
         OPTDB=""
-        [[ $opt_test -ne 0 ]] && OPTS="$OPTS --test-enable"
+        [[ $opt_test -ne 0 && $odoo_ver -gt 6 ]] && OPTS="$OPTS --test-enable"
+        [[ $opt_test -eq 0 && $odoo_ver -eq 6 ]] && OPTS="$OPTS --test-disable"
     else
         check_for_modules
         OPTSIU="$OPTI $OPTU"
@@ -308,8 +338,9 @@ if [[ -n "$opt_db" ]]; then
     OPTDB="$OPTDB -d $opt_db"
 fi
 if [[ $opt_touch -eq 0 ]]; then
-    [[ $drop_db -gt 0 ]] && run_traced "pg_db_active -wa $opt_db; dropdb -U$DB_USER --if-exists $opt_db"
-    [[ $create_db -gt 0 && $odoo_ver -lt 10 ]] && run_traced "createdb -U$DB_USER $opt_db"
+    [[ -n "$DB_PORT" ]] && opts="-U$DB_USER -p$DB_PORT" || opts="-U$DB_USER"
+    [[ $drop_db -gt 0 ]] && run_traced "pg_db_active -wa $opt_db; dropdb $opts --if-exists $opt_db"
+    [[ $create_db -gt 0 && $odoo_ver -lt 10 ]] && run_traced "createdb $opts $opt_db"
     [[ -n "$VDIR" ]] && ve_root=$VDIR || ve_root=$HOME
     OPT_LLEV=
     FULL_LCONFN="$ve_root/$LCONFN"
@@ -344,10 +375,13 @@ if [[ $opt_touch -eq 0 ]]; then
     fi
     if [[ -z "$RPCPORT" || "$RPCPORT" == "0" ]]; then
         run_traced_debug "sed -e \"s|^xmlrpc_port *=.*|xmlrpc_port = False|\" -i $FULL_LCONFN"
-        [[ $opt_force -ne 0 ]] && OPT_CONF="$OPT_CONF --no-xmlrpc"
-    else
+        OPT_CONF="$OPT_CONF --no-xmlrpc"
+    elif [[ $(grep -E "^xmlrpc_port *=" $FULL_LCONFN) || $odoo_ver -lt 10 ]]; then
         run_traced_debug "sed -e \"s|^xmlrpc_port *=.*|xmlrpc_port = $RPCPORT|\" -i $FULL_LCONFN"
-        [[ $opt_force -ne 0 ]] && OPT_CONF="$OPT_CONF --xmlrpc-port=$RPCPORT"
+        OPT_CONF="$OPT_CONF --xmlrpc-port=$RPCPORT"
+    else
+        run_traced_debug "sed -e \"s|^http_port *=.*|http_port = $RPCPORT|\" -i $FULL_LCONFN"
+        OPT_CONF="$OPT_CONF --http-port=$RPCPORT"
     fi
     if [[ -n "$DB_USER" ]]; then
         run_traced_debug "sed -e \"s|^db_user *=.*|db_user = $DB_USER|\" -i $FULL_LCONFN"
@@ -376,7 +410,8 @@ if [[ $opt_touch -eq 0 ]]; then
     fi
     if [ $drop_db -gt 0 ]; then
         if [ -z "$opt_modules" -o $opt_stop -eq 0 ]; then
-            run_traced "dropdb -U$DB_USER --if-exists $opt_db"
+            [[ -n "$DB_PORT" ]] && opts="-U$DB_USER -p$DB_PORT" || opts="-U$DB_USER"
+            run_traced "dropdb $opts --if-exists $opt_db"
         fi
     fi
     if [ $opt_exp -ne 0 ]; then
