[FIX] First version for osx darwin

diff --git a/clodoo/odoo_install_repository b/clodoo/odoo_install_repository
--- a/clodoo/odoo_install_repository
+++ b/clodoo/odoo_install_repository
@@ -7,36 +7,39 @@
 # author: Antonio M. Vigliotti <antoniomaria.vigliotti@gmail.com>
 # (C) 2015-2021 by SHS-AV s.r.l. - http://www.shs-av.com <info@shs-av.com>
 #
+READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
+export READLINK
 THIS=$(basename "$0")
-TDIR=$(readlink -f $(dirname $0))
-PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])" | python)
-for d in $TDIR $TDIR/.. $TDIR/../.. $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
-    if [ -e $d/z0librc ]; then
-        . $d/z0librc
-        Z0LIBDIR=$d
-        Z0LIBDIR=$(readlink -e $Z0LIBDIR)
-        break
-    elif [ -d $d/z0lib ] && [ -e $d/z0lib/z0librc ]; then
-        . $d/z0lib/z0librc
-        Z0LIBDIR=$d/z0lib
-        Z0LIBDIR=$(readlink -e $Z0LIBDIR)
-        break
-    fi
+TDIR=$($READLINK -f $(dirname $0))
+[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
+PYPATH=$(echo -e "import os,sys\np=[x for x in (os.environ['PATH']+':$TDIR:..:$HOME_DEV').split(':') if x not in sys.path];p.extend(sys.path);print(' '.join(p))"|python)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
+for d in $PYPATH /etc; do
+  if [[ -e $d/z0librc ]]; then
+    . $d/z0librc
+    Z0LIBDIR=$d
+    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
+    break
+  fi
 done
-if [ -z "$Z0LIBDIR" ]; then
-    echo "Library file z0librc not found!"
-    exit 2
+if [[ -z "$Z0LIBDIR" ]]; then
+  echo "Library file z0librc not found!"
+  exit 72
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR $TDIR/.. $HOME/tools/clodoo $HOME/dev ${PYPATH//:/ } . .." "clodoo")
-if [ -z "$ODOOLIBDIR" ]; then
-    echo "Library file odoorc not found!"
-    exit 2
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
+ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
+if [[ -z "$ODOOLIBDIR" ]]; then
+  echo "Library file odoorc not found!"
+  exit 72
 fi
 . $ODOOLIBDIR
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
-RUNDIR=$(readlink -e $TESTDIR/..)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
+RUNDIR=$($READLINK -e $TESTDIR/..)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
 
-__version__=0.3.31.13
+__version__=0.3.31.14
 
 rmdir_if_exists() {
     #rmdir_if_exists (DSTPATH REPOS odoo_vid new_vid)
@@ -256,7 +259,7 @@ OPTHELP=("this help"
 OPTARGS=(git_repo odoo_vid new_odoo_vid)
 
 parseoptargs "$@"
-if [ "$opt_version" ]; then
+if [[ "$opt_version" ]]; then
     echo "$__version__"
     exit $STS_SUCCESS
 fi
@@ -402,7 +405,7 @@ else
         exit 1
     fi
     new_odoo_fver=$(build_odoo_param FULLVER "$new_odoo_vid")
-    DSTROOT=$(readlink -e $DSTPATH/..)
+    DSTROOT=$($READLINK -e $DSTPATH/..)
     if [[ -z "$DSTROOT" ]]; then
         echo "Cannot found target parent directory $DSTPATH!"
         exit 1
diff --git a/travis_emulator/travisrc b/travis_emulator/travisrc
--- a/travis_emulator/travisrc
+++ b/travis_emulator/travisrc
@@ -2,15 +2,17 @@
 #
 # Common file for travis emulator scripts
 #
-#__version__=1.0.1.3
+#__version__=1.0.1.4
 
 # MAKEF=$HOME/dev/Makefile
 [[ "${BASH_SOURCE-}" == "$0" ]] && echo "You must source this script: \$ source $0" >&2 && exit 33
 XRGI="^(.*\/|)conf\/.*sample$"
-READLINK=readlink
+READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
+export READLINK
 
-PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])" | python)
-for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/wok_code/wok_code/../z0lib /home/odoo/devel/pypi/wok_code/wok_code/../../z0lib /home/odoo/devel/pypi/wok_code/wok_code/../../z0lib/z0lib; do
+PYPATH=$(echo -e "import os,sys\np=[x for x in (os.environ['PATH']+':$TDIR:..:$HOME_DEV').split(':') if x not in sys.path];p.extend(sys.path);print(' '.join(p))"|python)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
+for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
     Z0LIBDIR=$d
@@ -20,14 +22,17 @@ for d in $TDIR ${PATH//:/ } ${PYPATH//:/ } /etc /home/odoo/devel/pypi/wok_code/w
 done
 if [[ -z "$Z0LIBDIR" ]]; then
   echo "Library file z0librc not found!"
-  exit 2
+  exit 72
 fi
-ODOOLIBDIR=$(findpkg odoorc "$TDIR ${PATH//:/ } ${PYPATH//:/ } . .." "clodoo")
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
+ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
 if [ -z "$ODOOLIBDIR" ]; then
   echo "Library file odoorc not found!"
-  exit 2
+  exit 72
 fi
 . $ODOOLIBDIR
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
+
 
 opts_travis() {
   # opts_travis(git-org/pkgname)
@@ -403,8 +408,9 @@ set_osx() {
     local x
     x=$(which readlink)
     run_traced "ln -s $x $TRAVIS_HOME/bin/greadlink"
-    echo "echo '*** INVALID READLINK: USE GREADLINK! ***'" >$TRAVIS_HOME/bin/readlink
-    echo "exit 2" >>$TRAVIS_HOME/bin/readlink
+    echo "echo '*** INVALID READLINK: use GREADLINK! ***'" >$TRAVIS_HOME/bin/readlink
+    echo "set -x" >>$TRAVIS_HOME/bin/readlink
+    echo "exit 126" >>$TRAVIS_HOME/bin/readlink
     chmod +x $TRAVIS_HOME/bin/readlink
 }
 
@@ -1345,12 +1351,12 @@ clone_dependencies() {
       clone_1_dependence "$p"
       s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
     done
-    p=$(readlink -e $oetpath/odoo)
+    p=$($READLINK -e $oetpath/odoo)
     if [ -n "$p" ]; then
       clone_1_dependence "$p"
       s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
     fi
-    p=$(readlink -e $oetpath/openerp)
+    p=$($READLINK -e $oetpath/openerp)
     if [ -n "$p" ]; then
       clone_1_dependence "$p"
       s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
