[RUN] test nightly

diff --git a/product/product b/product/product
--- a/product/product
+++ b/product/product
@@ -905,6 +905,15 @@ get_full_xtlcmd() {
     echo "$xtlcmd"
 }
 
+get_full_svccmd() {
+# get_full_svccmd(action svcname OPTS)
+  if [ "$DISTO" == "CentOS7" ]; then
+    :
+  else
+    :
+  fi
+}
+
 set_config_cmd() {
 # set_config_cmd::pkgname opt_yes xtlcmd, stscmd STD_PKGS
 # return: -> cmd, cmd0
@@ -1433,6 +1442,16 @@ post_dry_install_service() {
     return $sts
 }
 
+post_dry_config_service() {
+# post_dry_config_service(action pkgname OPTS)
+    if [[ $3 =~ b ]]; then echo "post_dry_config_service($1 $2 $3)">>~/$THIS.his; fi #debug
+    local svcname=$(get_prm_value "0" "${2}_svcname")
+    cmd="chkconfig $svcname on"
+    run_traced "$cmd"
+    sts=$?
+    return $sts
+}
+
 post_dry_update_service() {
 # post_dry_update_service(action pkgname OPTS)
     if [[ $3 =~ b ]]; then echo "post_dry_update_service($1 $2 $3)">>~/$THIS.his; fi #debug
@@ -1480,6 +1499,40 @@ do_1_status_package() {
     local pkgversion="$(get_pkg_ver $2 $3)"
     [ -n "$pkgversion" ]
     return $?
+}
+
+do_1_info_package() {
+# do_1_info_package(action pkgname OPTS)
+    if [[ $3 =~ b ]]; then echo "do_1_info_package($1 $2 $3 $4 $5)">>~/$THIS.his; fi    #debug
+    local pkgname=$(get_realname $2)
+    local pkglist=$(prod realname $2)
+    local xtlcmd=$(get_act_xtlcmd $pkgname "install")
+    local svcname=$(get_prm_value "0" "${pkgname}_svcname")
+    local cmdname=$(get_prm_value "0" "${pkgname}_cmdname")
+    local vfycmd=$(get_prm_value "0" "${pkgname}_vfycmd")
+    if [[ $pkglist =~ = ]]; then
+      if [ "$2" == "$pkgname" ]; then
+        echo "$pkglist (install by $xtlcmd)"
+      else
+        echo "$2=$pkglist (install by $xtlcmd)"
+      fi
+    else
+      if [ "$2" == "$pkgname" ]; then
+        echo "$2 (install by $xtlcmd)"
+      else
+        echo "$2=$pkgname (install by $xtlcmd)"
+      fi
+    fi
+    if [ -n "$svcname" ]; then
+      echo " service=$svcname"
+    fi
+    if [ -n "$cmdname" ]; then
+      echo " command=$cmdname"
+    fi
+    if [ -n "$vfycmd" ]; then
+      echo " get ver=$vfycmd"
+    fi
+    return $STS_SUCCESS
 }
 
 do_dry_status_package() {
@@ -1543,7 +1596,6 @@ do_dry_whatis_package() {
     return $STS_SUCCESS
 }
 
-
 satisfy_request() {
 # satisfy_request(action pkgname OPTS)
     # echo "satisfy_request($1 $2 '$3')">>~/$THIS.his    #debug
@@ -1576,6 +1628,9 @@ do_iteration() {
     # echo "do_iteration($1 $2 '$3')">>~/$THIS.his    #debug
     local pkgname=$(get_realname $2 $1)
     if [[ $3 =~ [qQ] ]]; then
+      return 127
+    fi
+    if [ "$1" == "info" ]; then
       return 127
     fi
     local iter=$(set_iter $pkgname)
@@ -1662,8 +1717,12 @@ prod() {
     fi
     local x=$((prdstk_level*2))
     local lm=$(printf "%${x}.${x}s" " "|sed y'/ /-/')
-    local pkgname=$(get_realname $2 $1)
-    satisfy_request $1 $pkgname "$3" "$4" "$5"
+    if [ "$1" == "info" ]; then
+      local pkgname=$2
+    else
+      local pkgname=$(get_realname $2 $1)
+      satisfy_request $1 $pkgname "$3" "$4" "$5"
+    fi
     if [[ " $SIMULATE_YES " =~ [[:space:]]$pkgname[[:space:]] ]]; then
        local ij="I"
     elif [[ " $SIMULATE_NO " =~ [[:space:]]$pkgname[[:space:]] ]]; then
@@ -1675,10 +1734,10 @@ prod() {
     local SUBcmd1=do_1_${1}_package
     local SUBcmd2=
     local svcname=$(get_prm_value "0" "${pkgname}_svcname")
-    if [ "$(type -t $SUBcmd1)" == "function" -a "$(type -t $SUBcmd)" != "function" ]; then
+    if [ "$(type -t $SUBcmd1)" == "function" ] && [[  "$3" =~ q ]]; then
       eval $SUBcmd1 $1 $pkgname "$3$ij" "$4" "$5"
       return $?
-    elif [ "$(type -t $SUBcmd1)" == "function" ] && [[  "$3" =~ q ]]; then
+    elif [ "$(type -t $SUBcmd1)" == "function" -a "$(type -t $SUBcmd)" != "function" ]; then
       eval $SUBcmd1 $1 $pkgname "$3$ij" "$4" "$5"
       return $?
     fi
@@ -1688,7 +1747,7 @@ prod() {
       do_local_function "do" "$svcname" "$1" "$pkgname" "$3$ij" "$4" "$5"
       sts=$?
     fi
-    if [ $sts -eq $STS_SUCCESS -o $sts -eq 127 ]; then
+    if [ $sts -eq $STS_SUCCESS ]; then
       do_local_function "post" "$svcname" "$1" "$pkgname" "$3$ij" "$4" "$5"
       sts=$?
       if [ $sts -eq 127 ]; then sts=$STS_SUCCESS; fi
@@ -1698,18 +1757,23 @@ prod() {
     fi
     local SUBlist="$(get_prm_value "0" SUB_$pkgname)"
     if [[ $3 =~ b ]]; then echo "SUBlist=$SUBlist($prdstk_level<$opt_depth)">>~/$THIS.his; fi    #debug
+    local s
     if [ -n "$SUBlist" -a $prdstk_level -lt $opt_depth ]; then
       ((prdstk_level++))
       local ps
       for ps in $SUBlist; do
         do_action_sub $1 $ps $3 "$4" "$5"
+        s=$?
+        if [ $sts -eq $STS_SUCCESS -a $s -ne 127 -a $s -ne $STS_SUCCESS ]; then
+          sts=$s
+        fi
       done
       ((prdstk_level--))
     fi
     if [ $prdstk_level -eq 0 -a "$FH" == "Debian" -a "$1" == "remove" ]; then
       run_traced "apt-get autoremove"
     fi
-    return $STS_SUCCESS
+    return $sts
 }
 
 init_odoo_env() {
@@ -2480,7 +2544,7 @@ test_remove() {
 }
 
 # main
-OPTOPTS=(h        b       c        D       d         E       e       g       H        I        i      J        L         l          m        n           O         P          q         s         t         u       V           v           y       1)
+OPTOPTS=(h        b       c        D       d         E       e       g       H        I        i      J        L         l          m        n           O         P          q         s         T         u       V           v           y       1)
 OPTDEST=(opt_help opt_dbg opt_conf opt_dev opt_depth opt_osf opt_oed opt_grf opt_host opt_xtly opt_if opt_xtln opt_log   opt_locale opt_mult opt_dry_run opt_odoo  opt_pwd    opt_quiet opt_sub   test_mode use2xtl opt_version opt_verbose opt_yes opt_1st)
 OPTACTI=(1        1       "="      1       "="       "="     "="     1       "="      "="      "="    "="      "="       "="        1        1           "="       "="        1         "="       1         "="     "*"         1           1       1)
 OPTDEFL=(1        0       ""       0       ""        ""      ""      0       ""       ""       ""     ""       ""        ""         0        0           ""        ""         0         ""        0         ""      ""          0           0       0)
@@ -2633,42 +2697,6 @@ if [ ${opt_dbg:-0} -gt 0 ]; then rm -f ~/$THIS.his; fi    #debug
 
 if [ "$action" == "help" ]; then
   man $TDIR/$THIS.man
-elif [ "$action" == "whatis" ]; then
-  if [ $test_mode -eq 0 ]; then
-    print_title "List managed packages"
-  fi
-  prod $action $pkg $OPTS
-elif [ "$action" == "status" ]; then
-  if [ $EUID -ne 0 -a $test_mode -eq 0 ]; then
-    elog "This command must be executed by root"
-    exit $STS_FAILED
-  fi
-  set_tlog_file "$FLOG" "" "echo"
-  if [ $test_mode -eq 0 ]; then
-    print_title "Check for installation status"
-  fi
-  prod $action $pkg $OPTS
-  ending_msg
-elif [ "$action" == "version" ]; then
-  if [ $EUID -ne 0 -a $test_mode -eq 0 ]; then
-    elog "This command must be executed by root"
-    exit $STS_FAILED
-  fi
-  set_tlog_file "$FLOG" "" "echo"
-  if [ $test_mode -eq 0 ]; then
-    print_title "Show installed package version"
-  fi
-  if $(prod status $pkg "-q"); then
-    prod version $pkg
-  fi
-elif [ "$action" == "update" ]; then
-  if [ $EUID -ne 0 -a $test_mode -eq 0 ]; then
-    elog "This command must be executed by root"
-    exit $STS_FAILED
-  fi
-  print_title "Update/upgrade package(s)"
-  prod $action $pkg $OPTS
-  ending_msg
 elif [ "$action" == "config" ]; then
   if [ $EUID -ne 0 ]; then
     elog "This command must be executed by root"
@@ -2741,32 +2769,6 @@ elif [ "$action" == "config" ]; then
       fi
     done
   fi
-  ending_msg
-elif [ "$action" == "remove" ]; then
-  if [ $EUID -ne 0 -a $test_mode -eq 0 ]; then
-    elog "This command must be executed by root"
-    exit $STS_FAILED
-  fi
-  if [ -z "$pkg" ]; then
-     echo "You must specify package to remove!"
-     exit $STS_FAILED
-  fi
-  print_title "Remove package $pkg"
-  prod $action $pkg $OPTS
-  ending_msg
-elif [ "$action" == "install" ]; then
-  if [ $EUID -ne 0 -a $test_mode -eq 0 ]; then
-    elog "This command must be executed by root"
-    exit $STS_FAILED
-  fi
-  print_title "Install package(s)"
-  if [ $opt_1st -gt 0 ]; then
-    wlog "Setup for 1st installation"
-    if [ $opt_dry_run -eq 0 ]; then
-      prod update "."
-    fi
-  fi
-  prod $action $pkg "$OPTS"
   ending_msg
 elif [ "$action" == "prepare" ]; then
   if [ $EUID -ne 0 ]; then
@@ -2841,46 +2843,123 @@ elif [ "$action" == "debug" ]; then
      echo "${DEFPRM[jy]}=${DEFVAL[jy]}">>product.conf.sample
      ((jy++))
    done
-elif [ "$action" == "realname" ]; then
-  p=$(prod $action $pkg)
-  if [ "$p" == "$pkg" ]; then
-    echo $pkg
-  elif [[ $p =~ = ]]; then
-     echo $p
-  else
-    echo $pkg=$p
-  fi
-elif [ "$action" == "info" ]; then
-  pkgname=$(get_realname $pkg)
-  pkglist=$(prod realname $pkg)
-  xtlcmd=$(get_act_xtlcmd ${pkgname} "install")
-  svcname=$(get_prm_value "0" "${pkgname}_svcname")
-  cmdname=$(get_prm_value "0" "${pkgname}_cmdname")
-  vfycmd=$(get_prm_value "0" "${cmdname}_vfycmd")
-  if [[ $pkglist =~ = ]]; then
-    if [ "$pkg" == "$pkgname" ]; then
-      echo "$pkglist (install by $xtlcmd)"
-    else
-      echo "$pkg=$pkglist (install by $xtlcmd)"
-    fi
-  else
-    if [ "$pkg" == "$pkgname" ]; then
-      echo "$pkg (install by $xtlcmd)"
-    else
-      echo "$pkg=$pkgname (install by $xtlcmd)"
-    fi
-  fi
-  if [ -n "$svcname" ]; then
-    echo " service=$svcname"
-  fi
-  if [ -n "$cmdname" ]; then
-    echo " command=$cmdname"
-  fi
-  if [ -n "$vfycmd" ]; then
-    echo " get ver=$vfycmd"
-  fi
+# elif [ "$action" == "realname" ]; then
+#   p=$(prod $action $pkg)
+#   if [ "$p" == "$pkg" ]; then
+#     echo $pkg
+#   elif [[ $p =~ = ]]; then
+#      echo $p
+#   else
+#     echo $pkg=$p
+#   fi
+# elif [ "$action" == "info" ]; then
+#   pkgname=$(get_realname $pkg)
+#   pkglist=$(prod realname $pkg)
+#   xtlcmd=$(get_act_xtlcmd ${pkgname} "install")
+#   svcname=$(get_prm_value "0" "${pkgname}_svcname")
+#   cmdname=$(get_prm_value "0" "${pkgname}_cmdname")
+#   vfycmd=$(get_prm_value "0" "${cmdname}_vfycmd")
+#   if [[ $pkglist =~ = ]]; then
+#     if [ "$pkg" == "$pkgname" ]; then
+#       echo "$pkglist (install by $xtlcmd)"
+#     else
+#       echo "$pkg=$pkglist (install by $xtlcmd)"
+#     fi
+#   else
+#     if [ "$pkg" == "$pkgname" ]; then
+#       echo "$pkg (install by $xtlcmd)"
+#     else
+#       echo "$pkg=$pkgname (install by $xtlcmd)"
+#     fi
+#   fi
+#   if [ -n "$svcname" ]; then
+#     echo " service=$svcname"
+#   fi
+#   if [ -n "$cmdname" ]; then
+#     echo " command=$cmdname"
+#   fi
+#   if [ -n "$vfycmd" ]; then
+#     echo " get ver=$vfycmd"
+#   fi
+# else
+#   echo "No valid action $action!"
+#  exit $STS_FAILED
 else
-  echo "No valid action $action!"
-  exit $STS_FAILED
+  actions=${action//+/ }
+  actions=${actions//,/ }
+  pkgs=${pkg//+/ }
+  pkgs=${pkgs//,/ }
+  # set -x #debug
+  TITL_whatis="List managed packages"
+  TITL_status="Check for installation status"
+  TITL_version="Show installed package version"
+  TITL_install="Install package(s)"
+  TITL_update="Update/upgrade package(s)"
+  TITL_remove="Remove package package(s)"
+  SYSPRIV="install remove status update version"
+  OPTS1ST="install update"
+  ECHOCMDS="install remove status update version"
+  TAILMSG="install remove status update"
+  opt_tail=0
+  if [ $opt_1st -gt 0 ]; then
+    for act in $actions; do
+      if [[ " $OPTS1ST " =~ [[:space:]]$act[[:space:]] ]]; then
+        opt_tail=1
+        break
+      fi
+    done
+  fi
+  if [ $opt_tail -gt 0 ]; then
+    wlog "Setup for 1st installation"
+    if [ $opt_dry_run -eq 0 ]; then
+      prod update "."
+    fi
+  fi
+  opt_tail=0
+  for act in $actions; do
+    if [[ " $SYSPRIV " =~ [[:space:]]$act[[:space:]] ]]; then
+      if [ $EUID -ne 0 -a $test_mode -eq 0 ]; then
+        elog "This command must be executed by root"
+        exit $STS_FAILED
+      fi
+    fi
+    if [[ " $ECHOCMDS " =~ [[:space:]]$act[[:space:]] ]]; then
+      set_tlog_file "$FLOG" "" "echo"
+    fi
+    if [ $test_mode -eq 0 ]; then
+      X="TITL_$act"
+      if [ -n "${!X}" ]; then
+        print_title "${!X}"
+      fi
+    fi
+    for package in $pkgs; do
+      if [ "$act" == "realname" ]; then
+        p=$(prod $act $package)
+        if [ "$p" == "$package" ]; then
+          echo $package
+        elif [[ $p =~ = ]]; then
+          echo $p
+        else
+          echo $package=$p
+        fi
+      else
+        prod $act $package $OPTS
+      fi
+      sts=$?
+      if [ $sts -eq 127 ]; then
+        echo "Unknow action $act"
+        exit $sts
+      elif [ $sts -ne $STS_SUCCESS ]; then
+        echo "Error in $act $package"
+        exit $sts
+      fi
+    done
+    if [[ " $TAILMSG " =~ [[:space:]]$act[[:space:]] ]]; then
+      opt_tail=1
+    fi
+  done
+  if [ $opt_tail -gt 0 ]; then
+    ending_msg
+  fi
 fi
 exit 0
