[IMP] New feature for travis emulator

diff --git a/zerobug/tests/all_tests b/zerobug/tests/all_tests
--- a/zerobug/tests/all_tests
+++ b/zerobug/tests/all_tests
@@ -18,7 +18,11 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 
@@ -50,10 +54,18 @@ Z0BUG_teardown() {
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_zerobug.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
+fi
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
 UT1_LIST=
 UT_LIST=
diff --git a/zerobug/tests/zerobug_test_02 b/zerobug/tests/zerobug_test_02
--- a/zerobug/tests/zerobug_test_02
+++ b/zerobug/tests/zerobug_test_02
@@ -18,25 +18,38 @@ if [ -z "$Z0LIBDIR" ]; then
 fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR . .. $HOME/dev $TDIR/../../zerobug")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. . .. $HOME/dev $TDIR/../../zerobug")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
 __version__=0.2.7
 
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_zerobug.log $@
+parseoptest -l$TESTDIR/test_zerobug.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg "travisrc" "$TDIR $TDIR/..")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
 UT1_LIST=""
 UT_LIST="__version_0_${__version__}$Z0TLIBDIR/z0testrc"
 UT_LIST="$UT_LIST __version_1_0.1.44$Z0LIBDIR/z0librc"
 UT_LIST="$UT_LIST __version_V_0.2.0$TESTDIR/dummy_01.py"
 UT_LIST="$UT_LIST __version_v_0.2.1$TESTDIR/dummy_01.py"
 UT_LIST="$UT_LIST __version_P_0.2.2$TESTDIR/dummy_01.py"
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
-exit $?
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
