[FIX] Various fixes 20220903

diff --git a/lisa/lisa/odoo-server_Debian b/lisa/lisa/odoo-server_Debian
--- a/lisa/lisa/odoo-server_Debian
+++ b/lisa/lisa/odoo-server_Debian
@@ -83,9 +83,9 @@ else
   CONFIGFILE=""
 fi
 # search for execution command script
-xtl_org=$(echo $(basename $0)|grep -Eo "(oca|librerp|zero|powerp)"|tail -n1)
+xtl_org=$(echo $(basename $0)|grep --color=never -Eo "(oca|librerp|zero|powerp)"|tail -n1)
 [[ -z "$xtl_org" ]] && ORG="odoo" || ORG="$xtl_org"
-mult=$(echo $(basename $0)|grep -Eo "(6|7|8|9|10|11|12|13|14|15|16)")
+mult=$(echo $(basename $0)|grep --color=never -Eo "(6|7|8|9|10|11|12|13|14|15|16)")
 [[ $DRY_RUN -gt 0 ]] && echo "mult=${mult}"
 [[ $DRY_RUN -gt 0 ]] && echo "ORG=$ORG"
 DAEMON=""
@@ -173,7 +173,7 @@ set_lessc() {
     local f=$1
     local minv=$2
     [[ -z "$minv" ]] && minv=30000
-    local lv=$($f --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+    local lv=$($f --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
     [[ -z "$lv" ]] && lv=0
     dt=$(date +"%Y-%m-%d %H:%M:%S,000")
     if [[ $lv -ge $minv ]]; then
@@ -192,7 +192,7 @@ set_lessc() {
 
 check_lessc() {
     local d dt f x
-    local lv=$(lessc --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+    local lv=$(lessc --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
     local alt_less=
     [[ -z "$lv" ]] && lv=0
     dt=$(date +"%Y-%m-%d %H:%M:%S,000")
@@ -203,7 +203,7 @@ check_lessc() {
         if [[ -d $d ]]; then
           if [[ -x $d/less/bin/lessc ]]; then
             f=$d/less/bin/lessc
-            lv=$($f --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+            lv=$($f --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
             [[ -z "$lv" ]] && lv=0
             if [[ $lv -gt 30000 ]]; then
               set_lessc $f 30000
@@ -215,7 +215,7 @@ check_lessc() {
         fi
       done
     fi
-    lv=$(lessc --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+    lv=$(lessc --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
     [[ -z "$lv" ]] && lv=0
     if [[ $lv -lt 20000 && -n "$alt_less" ]]; then
       set_lessc $alt_less 20000
@@ -360,6 +360,13 @@ start() {
     return $RETVAL
 }
 
+stop_by_ps() {
+      echo "Error during stopping .. try to stop process ..."
+      [[ ${xtl_version} -lt 11 ]] && py=python || py=python3
+      local pid=$(ps -ef | grep "$py .*$DAEMON.*\.conf" | grep -v grep | awk '{print $2}' | head -n1)
+      [[ -z "$pid" ]] || kill $pid
+      RETVAL=$?
+}
 
 stop_RHEL() {
     if [[ -f $PIDFILE ]]; then
@@ -370,13 +377,7 @@ stop_RHEL() {
         fi
     fi
     RETVAL=$?
-    if [[ $RETVAL -ne 0 ]]; then
-        echo "Error during stopping .. try to stop process ..."
-        [[ ${xtl_version} -lt 11 ]] && py=python || py=python3
-        local pid=$(ps -ef | grep "$py .*$DAEMON.*\.conf" | grep -v grep | awk '{print $2}')
-        [[ -z "$pid" ]] || kill $pid
-        RETVAL=$?
-    fi
+    [[ $RETVAL -ne 0 ]] && stop_by_ps
     if [[ $RETVAL -eq 0 ]]; then
         [[ $DRY_RUN -eq 0 ]] && rm -f $LOCKFILE
         # echo_success
@@ -390,7 +391,6 @@ stop_RHEL() {
         run-parts /etc/${xtl_id}/stop.d
         echo
     fi
-    # [[ $DRY_RUN -eq 0 && -f "$PIDFILE" ]] && rm -f $PIDFILE
     return $RETVAL
 }
 
@@ -402,7 +402,7 @@ stop_Debian () {
         start-stop-daemon --stop --quiet --pidfile ${PIDFILE}  --oknodo --remove-pidfile
     fi
     RETVAL=$?
-    # [[ $DRY_RUN -eq 0 && -f "$PIDFILE" ]] && rm -f $PIDFILE
+    [[ $RETVAL -ne 0 ]] && stop_by_ps
     return $RETVAL
 }
 
diff --git a/zerobug/zerobug/_travis/travis_install_env b/zerobug/zerobug/_travis/travis_install_env
--- a/zerobug/zerobug/_travis/travis_install_env
+++ b/zerobug/zerobug/_travis/travis_install_env
@@ -86,7 +86,7 @@ run_traced() {
 }
 
 cp_n_upd_odoo_conf() {
-  local odoo_ver=$(echo $VERSION | grep -Eo '[0-9]*' | head -n1)
+  local odoo_ver=$(echo $VERSION | grep --color=never -Eo '[0-9]*' | head -n1)
   if [ $odoo_ver -ge 10 ]; then
     local tgt=~/.odoorc
     local atgt=~/.openerp_serverrc
@@ -155,8 +155,8 @@ git_clone_ocb() {
   local ODOO_URL="https://github.com/$REMOTE/$REPO_NAME.git"
   echo -e "\e[${PS_HDR3_COLOR}m### Installing Odoo from $ODOO_URL\e[${PS_TXT_COLOR}m"
   if [[ ! -L ${ODOO_PATH} && ! "$TRAVIS" == "true" ]]; then
-    prjhome=$(echo $TRAVIS_HOME_BRANCH | grep -Eo "$TRAVIS_SAVED_HOME/[^/]+")
-    majver=$(echo $BRANCH | grep -Eo [0-9]+ | head -n1)
+    prjhome=$(echo $TRAVIS_HOME_BRANCH | grep --color=never -Eo "$TRAVIS_SAVED_HOME/[^/]+")
+    majver=$(echo $BRANCH | grep --color=never -Eo '[0-9]+' | head -n1)
     if [[ -n "$prjhome" ]]; then
       if [[ $REMOTE == "oca" && -d $prjhome/oca$majver ]]; then
         SRCREPOPATH="$prjhome/oca$majver"
@@ -247,20 +247,27 @@ check_pythonpath() {
   local TOOLS_PATH="${1//,/ }"
   TOOLS_PATH="${TOOLS_PATH//:/ }"
   local PYTHON=${2:-python}
-  local PYVER=$(python --version 2>&1 | grep -Eo "[0-9]+" | head -n1)
+  local PYVER=$(${PYTHON} --version 2>&1 | grep --color=never -Eo "[0-9]+" | head -n1)
   local pth PYLIB
   for pth in $TOOLS_PATH; do
-    if [ "$PYVER" == "2" ]; then
+    if [[ $PYVER -eq 2 ]]; then
       echo -e "import sys\nfor x in sys.path:\n  print x," | $PYTHON | grep -q " $pth "
     else
       echo -e "import sys\nfor x in sys.path:\n  print(x,end=' ')" | $PYTHON | grep -q " $pth "
     fi
-    if [ $? -ne 0 ]; then
+    if [[ $? -ne 0 ]]; then
       echo "Warning: sitecustomize.py without effect! Use PYTHONPATH method"
-      [ -n "$PYTHONPATH" ] && export PYTHONPATH=$PYTHONPATH:$pth
-      [ -z "$PYTHONPATH" ] && export PYTHONPATH=$pth
+      [[ -n "$PYTHONPATH" ]] && export PYTHONPATH=$PYTHONPATH:$pth
+      [[ -z "$PYTHONPATH" ]] && export PYTHONPATH=$pth
     fi
   done
+  if [[ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ]]; then
+    if [[ $PYVER -eq 2 ]]; then
+      echo -e "import sys\nprint 'sys.path=%s' % sys.path\n" | $PYTHON
+    else
+      echo -e "import sys\nprint('sys.path=%s' % sys.path)\n" | $PYTHON
+    fi
+  fi
 }
 
 install_n_activate_tools() {
@@ -268,19 +275,9 @@ install_n_activate_tools() {
     [[ $test_mode -ne 0 ]] && o="t"
     [[ -z $ODOO_ROOT ]] && ODOO_ROOT=$(readlink -f $HOME_DEVEL/..)
     x=$(readlink -f $ODOO_ROOT/tools)
-    if [[ -d $x ]]; then
-        [[ ${opt_verbose:-1} -gt 0 ]] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ cd $x\e[${PS_TXT_COLOR}m"
-        pushd $x > /dev/null
-        [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && x=-p${o}
-        [ ${TRAVIS_DEBUG_MODE:-0} -le 2 ] && x=-qp${o}
-        run_traced "./install_tools.sh $x"
-        [[ $test_mode -ne 0 ]] && o="-t"
-        [[ ${opt_verbose:-1} -gt 0 ]] && echo -e "\e[${PS_RUN_COLOR}m$pfx$xcmd\$ . $HOME_DEVEL/activate_tools ${o}\e[${PS_TXT_COLOR}m"
-        . $HOME_DEVEL/activate_tools ${o}
-        popd > /dev/null
-        [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PATH=$PATH"
-        [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PYTHONPATH=$PYTHONPATH"
-    fi
+    [[ ! -d $x ]] && echo "Tools environment not found (path $ODOO_ROOT/tools)" && exit 1
+    x=$(readlink -f $ODOO_ROOT/devel)
+    [[ ! -d $x ]] && echo "Tools environment not found (path $ODOO_ROOT/devel)" && exit 1
 }
 
 check_4_needing_pkgs() {
@@ -288,7 +285,7 @@ check_4_needing_pkgs() {
   NEEDING_PKGS="future configparser os0 z0lib"
   for p in $NEEDING_PKGS; do
     x=${p^^}
-    eval $x=$(pip show $p 2>/dev/null | grep "Version" | grep -Eo "[0-9.]+")
+    eval $x=$(pip show $p 2>/dev/null | grep "Version" | grep --color=never -Eo "[0-9.]+")
     [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && echo "Inner package $p=${!x}"
   done
 }
@@ -373,30 +370,21 @@ export MQT_TEST_MODE=$mode
 set_pybin $TRAVIS_PYTHON_VERSION
 export PYTHON PIP
 install_n_activate_tools
-if [[ -d $HOME/devel ]]; then
-  set_pythonpath "$HOME/tools" "$HOME/devel/sitecustomize.py" $PIP
-  [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PATH=$PATH"
-  [ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ] && echo "PYTHONPATH=$PYTHONPATH"
-else
-  echo "!! Error! Directory $HOME/devel not found!"
-fi
-check_pythonpath "$HOME/tools" $PYTHON
-if [ "${TRAVIS_PYTHON_VERSION:0:1}" == "2" ]; then
-  echo -e "import sys\nprint 'sys.path=%s' % sys.path\n" | python
-else
-  echo -e "import sys\nprint('sys.path=%s' % sys.path)\n" | python3
-fi
-run_traced "$PIP install -q pip --upgrade" "nolocal"
-PIPVER=$($PIP --version | grep -Eo [0-9]+ | head -n1)
-[ $PIPVER -gt 18 ] && PIP_OPTS="$PIP_OPTS --no-warn-conflicts"
-[ $PIPVER -gt 19 ] && PIP_OPTS="$PIP_OPTS --use-feature=2020-resolver"
-check_installed_pkgs
+# set_pythonpath "$HOME/tools" "$HOME/devel/sitecustomize.py" $PIP
+[[ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ]] && echo "PATH=$PATH"
+[[ ${TRAVIS_DEBUG_MODE:-0} -ge 2 ]] && echo "PYTHONPATH=$PYTHONPATH"
+# check_pythonpath "$HOME/tools" $PYTHON
+# run_traced "$PIP install -q pip --upgrade" "nolocal"
+# PIPVER=$($PIP --version | grep --color=never -Eo [0-9]+ | head -n1)
+[[ $PIPVER -gt 18 ]] && PIP_OPTS="$PIP_OPTS --no-warn-conflicts"
+[[ $PIPVER -gt 19 ]] && PIP_OPTS="$PIP_OPTS --use-feature=2020-resolver"
+# check_installed_pkgs
 LISTREQ=$(which list_requirements.py 2>/dev/null)
 if [[ -z "$LISTREQ" ]]; then
-  if [ -n "$YML_mgrodoo" ]; then
+  if [[ -n "$YML_mgrodoo" ]]; then
     LISTREQ=$(dirname $YML_mgrodoo)/list_requirements.py
   else
-    [ -f $HOME/tools/clodoo/list_requirements.py ] && LISTREQ=$HOME/tools/clodoo/list_requirements.py || LISTREQ=list_requirements.py
+    [[ -f $HOME/tools/clodoo/list_requirements.py ]] && LISTREQ=$HOME/tools/clodoo/list_requirements.py || LISTREQ=list_requirements.py
   fi
 fi
 LISA=$(which lisa 2>/dev/null)
@@ -480,7 +468,7 @@ if [[ "$MQT_TEST_MODE" == "tools" ]]; then
 else
   # Odoo
   if [[ "${LINT_CHECK:-1}" != "0" ]]; then
-    NODE_VER=$(node --version | grep -Eo "[0-9]+" | head -n1)
+    NODE_VER=$(node --version | grep --color=never -Eo "[0-9]+" | head -n1)
     if [ $NODE_VER -lt 6 -a -f "${HOME}/.nvm/nvm.sh" ]; then
       [ ${TRAVIS_DEBUG_MODE:-0} -gt 2 ] && echo "1> node version: $NODE_VER"
       CURRENT_NODE=$(which node)
@@ -500,7 +488,7 @@ else
   if [[ $TESTS == "1" ]]; then
     echo -e "\e[${PS_HDR3_COLOR}m### Install Packages for Base Environment\e[${PS_TXT_COLOR}m"
     if [[ $UNIT_TEST != "0" ]]; then
-      NODE_VER=$(node --version | grep -Eo "[0-9]+" | head -n1)
+      NODE_VER=$(node --version | grep --color=never -Eo "[0-9]+" | head -n1)
       if [[ $NODE_VER -lt 6 ]]; then
         x=$(which nodejs 2>/dev/null)
         [[ -z "$x" ]] && x=$(which node 2>/dev/null)
@@ -519,13 +507,13 @@ else
       lessc --version
     fi
     [[ -z "${WKHTMLTOPDF_VERSION}" ]] && export WKHTMLTOPDF_VERSION="0.12.5"
-    [[ -n "$(which example.com 2>/dev/null)" ]] && CUR_WKHTMLTOPDF_VERSION=$(wkhtmltopdf --version | grep -Eo [0-9.]+ | head -n1) || CUR_WKHTMLTOPDF_VERSION=
+    [[ -n "$(which example.com 2>/dev/null)" ]] && CUR_WKHTMLTOPDF_VERSION=$(wkhtmltopdf --version | grep --color=never -Eo '[0-9.]+' | head -n1) || CUR_WKHTMLTOPDF_VERSION=
     if [[ "$CUR_WKHTMLTOPDF_VERSION" == "$WKHTMLTOPDF_VERSION" ]]; then
       [ $opt_verbose -gt 0 ] && echo "Installed version of wkhtmltopdf is $WKHTMLTOPDF_VERSION"
     else
       [[ $opt_verbose -gt 0 ]] && echo "Installing wkhtmltopdf version $WKHTMLTOPDF_VERSION (current is $CUR_WKHTMLTOPDF_VERSION)"
       vem install "wkhtmltopdf==$WKHTMLTOPDF_VERSION"
-      CUR_WKHTMLTOPDF_VERSION=$(wkhtmltopdf --version | grep -Eo [0-9.]+ | head -n1)
+      CUR_WKHTMLTOPDF_VERSION=$(wkhtmltopdf --version | grep --color=never -Eo '[0-9.]+' | head -n1)
       [[ $opt_verbose -gt 0 ]] && echo "Current version of wkhtmltopdf is $CUR_WKHTMLTOPDF_VERSION"
     fi
     if [[ "${WEBSITE_REPO}" == "1" ]]; then
