[IMP] Various upgrades

diff --git a/travis_emulator/travis_emulator/travisrc b/travis_emulator/travis_emulator/travisrc
--- a/travis_emulator/travis_emulator/travisrc
+++ b/travis_emulator/travis_emulator/travisrc
@@ -2,19 +2,21 @@
 #
 # Common file for travis emulator scripts
 #
-#__version__=1.0.5.1
+#__version__=1.0.5.2
 
 [[ "${BASH_SOURCE-}" == "$0" ]] && echo "You must source this script: \$ source $0" >&2 && exit 33
 XRGI="^(.*\/|)conf\/.*sample$"
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
-# Based on template 1.0.4.1
+# Based on template 1.0.8
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
-HOME_DEV="$HOME/devel"
+if [[ -z $HOME_DEVEL ]]; then
+  [[ -d $HOME/odoo/devel ]] && HOME_DEVEL="$HOME/odoo/devel" || HOME_DEVEL="$HOME/devel"
+fi
 [[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
-[[ -z $PYPATH ]] && PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEV"'\nimport os,sys\no=os.path\na=o.abspath\nj=os.path.join\nd=os.path.dirname\nb=os.path.basename\nf=os.path.isfile\np=os.path.isdir\nH=o.expanduser('~')\nT=j(H,'tools')\nR=j(H,'pypi') if o.basename(D)=='venv_tools' else j(H,D,'pypi')\nW=D if o.basename(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'script')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C)=='tests':\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==d(C) and f(j(C,'..','setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+P\np=set()\npa=p.add\np=[x for x in L if x and (x.startswith(H) or x.startswith(D) or x.startswith(C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ -z $PYPATH ]] && PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEVEL"'\nimport os,sys\no=os.path\na=o.abspath\nj=os.path.join\nd=os.path.dirname\nb=os.path.basename\nf=os.path.isfile\np=os.path.isdir\nH=o.expanduser('~')\nT=j(d(D), 'tools')\nR=j(d(D),'pypi') if o.basename(D)=='venv_tools' else j(D,'pypi')\nW=D if o.basename(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'script')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C) in ('tests','travis','_travis'):\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==b(d(C)) and f(j(C,'..','setup.py')):\n C=a(j(C,'..','..'))\nelif b(d(C))=='tools' and f(j(C,'setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)) or p(j(C,b(C),B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+P\np=set()\npa=p.add\np=[x for x in L if x and (x.startswith(H) or x.startswith(D) or x.startswith(C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
@@ -28,7 +30,7 @@ if [[ -z "$Z0LIBDIR" ]]; then
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
-ODOOLIBDIR=$(findpkg odoorc "$PYPATH ." "clodoo")
+ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
 if [[ -z "$ODOOLIBDIR" ]]; then
   echo "Library file odoorc not found!"
   exit 72
@@ -41,7 +43,7 @@ opts_travis() {
   # opts_travis(git-org/pkgname)
   [[ -n "$1" ]] && IFS="/" read REMOTEREPO x <<<"$1"
   [[ -z "$REMOTEREPO" ]] && REMOTEREPO="local"
-  export TRAVIS_REPO_SLUG=$REMOTEREPO/$PKGNAME
+  [[ -z $TRAVIS_REPO_SLUG ]] && export TRAVIS_REPO_SLUG=$REMOTEREPO/$PKGNAME
 }
 
 inherits_travis_opts() {
@@ -296,15 +298,11 @@ create_virtual_env() {
   [[ -z ${Z0_STACK:+_} ]] && export Z0_STACK=0
   ((Z0_STACK=Z0_STACK+2))
   local sts=0
-  # local VER=${VERSION}
-  [[ -d $HOME/devel ]] && HOME_DEV=$HOME/devel
-  if [[ -z "$HOME_DEV" ]]; then
-    echo "Zeroincombenze(R) tools not found!"
-    exit 1
-  fi
+  [[ -z "$HOME_DEVEL" ]] && echo "Zeroincombenze(R) tools not found!" && exit 1
   VENVOPTS="-Dlen_US"
   drop_test_db
   export TRAVIS_SAVED_HOME=$HOME
+  [[ -d $HOME/odoo/devel ]] && export TRAVIS_SAVED_DHOME=$HOME/odoo || export TRAVIS_SAVED_DHOME=$HOME
   if [[ $HOME =~ ^/(home|opt)/travis && -d $HOME/virtualenv ]]; then
     export TRAVIS=true
     export TRAVIS_HOME=$HOME/virtualenv
@@ -318,48 +316,47 @@ create_virtual_env() {
   [[ $SYSTEM_SITE_PACKAGES == "true" ]] && TRAVIS_ENVOPTS="$TRAVIS_ENVOPTS --system-site-packages"
   [[ $SYSTEM_SITE_PACKAGES != "true" ]] && VENVOPTS="-DI"
   hash -r
-  if [[ "$PRJNAME" == "Odoo" && ( ! -d $TRAVIS_SAVED_HOME/VME/VME$BRANCH || $(stat -c %Y $TRAVIS_SAVED_HOME/VME/VME$BRANCH) -lt 1639237000 ) ]]; then
-    echo -e "\n\n${RED}Cached virtual environment $TRAVIS_SAVED_HOME/VME/VME$BRANCH not found or expired!${CLR}"
-    echo -e "Now virtual environment $TRAVIS_SAVED_HOME/VME/VME$BRANCH will be (re)created."
+  if [[ "$PRJNAME" == "Odoo" && ( ! -d $TRAVIS_SAVED_DHOME/VME/VME$BRANCH || $(stat -c %Y $TRAVIS_SAVED_DHOME/VME/VME$BRANCH) -lt 1639237000 ) ]]; then
+    echo -e "\n\n${RED}Cached virtual environment $TRAVIS_SAVED_DHOME/VME/VME$BRANCH not found or expired!${CLR}"
+    echo -e "Now virtual environment $TRAVIS_SAVED_DHOME/VME/VME$BRANCH will be (re)created."
     [[ $BRANCH =~ ^(6|7|8|9|10) ]] && pv="2.7" || pv="3.7"
-    run_traced "vem create $TRAVIS_SAVED_HOME/VME/VME$BRANCH -p$pv -DIfq -O$BRANCH -len_US"
+    run_traced "vem create $TRAVIS_SAVED_DHOME/VME/VME$BRANCH -p$pv -DIfq -O$BRANCH -len_US"
     echo -e "\n\n"
     [[ -d $TRAVIS_HOME ]] && rm -fR $TRAVIS_HOME    # STRANGE ERROR! WORKAROUND!
-  elif [[ ! -d "$TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION" || $(stat -c %Y $TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION) -lt 1639237000 ]]; then
-    echo -e "\n\n${RED}Cached virtual environment $TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION not found or expired!${CLR}"
-    run_traced "vem create $TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION -p$TRAVIS_PYTHON_VERSION -DIfq -len_US"
+  elif [[ ! -d "$TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION" || $(stat -c %Y $TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION) -lt 1639237000 ]]; then
+    echo -e "\n\n${RED}Cached virtual environment $TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION not found or expired!${CLR}"
+    run_traced "vem create $TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION -p$TRAVIS_PYTHON_VERSION -DIfq -len_US"
     echo -e "\n\n"
     [[ -d $TRAVIS_HOME ]] && rm -fR $TRAVIS_HOME    # STRANGE ERROR! WORKAROUND!
   fi
   if [[ $TRAVIS == "true" || -d $TRAVIS_HOME ]]; then
     true
   elif [[ $opt_full -eq 0 && ${opt_cache:-0} -ne 0 && -n "$TRAVIS_PYTHON_VERSION" ]]; then
-    [[ -d $TRAVIS_SAVED_HOME ]] || mkdir $TRAVIS_SAVED_HOME
-     if [[ "$PRJNAME" == "Odoo" && -d $TRAVIS_SAVED_HOME/VME/VME$BRANCH ]]; then
+    [[ -d $TRAVIS_SAVED_DHOME ]] || mkdir $TRAVIS_SAVED_DHOME
+    if [[ "$PRJNAME" == "Odoo" && -d $TRAVIS_SAVED_DHOME/VME/VME$BRANCH ]]; then
       opt_keepE=0
-      TRAVIS_SRC_VME=$TRAVIS_SAVED_HOME/VME/VME$BRANCH
+      TRAVIS_SRC_VME=$TRAVIS_SAVED_DHOME/VME/VME$BRANCH
       opts=$(inherits_travis_opts "" "V")
       [[ $TRAVIS == "true" ]] || opts="$opts -f"
       run_traced "vem cp $VENVOPTS $opts $TRAVIS_SRC_VME $TRAVIS_HOME"
       sts=$?
-    elif [[ -d "$TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION" ]]; then
+    elif [[ -d "$TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION" ]]; then
       opt_keepE=0
-      TRAVIS_SRC_VME=$TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION
+      TRAVIS_SRC_VME=$TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION
       opts=$(inherits_travis_opts "" "V")
       [[ $TRAVIS == "true" ]] || opts="$opts -f"
       run_traced "vem cp $VENVOPTS $opts $TRAVIS_SRC_VME $TRAVIS_HOME"
-      # run_traced "/home/odoo/devel/pypi/python_plus/python_plus/vem cp $VENVOPTS $opts -vvv $TRAVIS_SRC_VME $TRAVIS_HOME"   #debug
       sts=$?
     else
       if [[ "$PRJNAME" == "Odoo" && -n "$VERSION" ]]; then
-        TRAVIS_SRC_VME=$TRAVIS_SAVED_HOME/VME/VME$VERSION
+        TRAVIS_SRC_VME=$TRAVIS_SAVED_DHOME/VME/VME$VERSION
         opts=$(inherits_travis_opts "" "V")
         [[ $TRAVIS == "true" ]] || opts="$opts -f"
         opts="$opts -q"
         run_traced "vem create $VENVOPTS $TRAVIS_HOME $opts -p$TRAVIS_PYTHON_VERSION -O$VERSION"
         sts=$?
       else
-        TRAVIS_SRC_VME=$TRAVIS_SAVED_HOME/VME/VME$TRAVIS_PYTHON_VERSION
+        TRAVIS_SRC_VME=$TRAVIS_SAVED_DHOME/VME/VME$TRAVIS_PYTHON_VERSION
         opts=$(inherits_travis_opts "" "V")
         [[ $TRAVIS == "true" ]] || opts="$opts -f"
         opts="$opts -q"
@@ -378,6 +375,17 @@ create_virtual_env() {
   [[ $sts -ne 0 ]] && return
 
   run_traced "source $TRAVIS_HOME/bin/activate"
+  PYTHON=$(which python)
+  [[ $TRAVIS_PYTHON_VERSION =~ ^3 ]] && PYTHON3=$(which python3)
+  PIP=$(which pip)
+  if [[ $opt_dbgmnt -ne 0 ]]; then
+    for p in $(get_cfg_value "" "PKGS_LIST"); do
+        # Use unstable version
+        [[ $p =~ (python-plus|z0bug-odoo) ]] && p="${p//-/_}"
+        [[ -f $TRAVIS_SAVED_DHOME/devel/pypi/$p/$p/scripts/setup.info ]] && \
+          run_traced "pip install -U $TRAVIS_SAVED_DHOME/devel/pypi/$p"
+      done
+  fi
   [[ -n $NVM_DIR && -f $NVM_DIR/nvm.sh ]] && source $NVM_DIR/nvm.sh
   if [ $opt_cache -ne 0 -a "$TRAVIS" == "false" -a -d $HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages ]; then
     export PYPI_CACHED=$HOME/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
@@ -387,15 +395,15 @@ create_virtual_env() {
   # Compatibility with OCA test
   [[ -d $TRAVIS_HOME/maintainer-quality-tools ]] && rm -fR -d $TRAVIS_HOME/maintainer-quality-tools
   export TRAVIS_BUILD_DIR="$TRAVIS_HOME/build/$TRAVIS_REPO_SLUG"
-  if [ "$PKGNAME" == "OCB" ]; then
-    emulate_git_clone_OCB $TRAVIS_HOME_BRANCH $TRAVIS_BUILD_DIR
+  if [[ $PKGNAME == "OCB" ]]; then
+    emulate_git_clone_OCB $TRAVIS_HOME_BRANCH $TRAVIS_BUILD_DIR/$TRAVIS_REPO_SLUG
   else
     mkdir -p $TRAVIS_BUILD_DIR
     x=$(readlink -f $TRAVIS_BUILD_DIR/..)
     run_traced "cp -R $TRAVIS_HOME_BRANCH/ $x/"
     if [[ ${opt_dbgmnt:-0} -ne 0 && "$TRAVIS_REPO_SLUG" == "local/tools" ]]; then
       git_clone "https://github.com/zeroincombenze/tools.git"
-      [[ HOME_DEV =~ /devel$ ]] && run_traced "cp $TRAVIS_SAVED_HOME/devel/pypi/tools/install_tools.sh $TRAVIS_BUILD_DIR/ -o"
+      [[ $HOME_DEVEL =~ /devel$ ]] && run_traced "cp $TRAVIS_SAVED_DHOME/devel/pypi/tools/install_tools.sh $TRAVIS_BUILD_DIR/ -o"
     fi
   fi
   [[ $PWD != $TRAVIS_BUILD_DIR ]] && run_traced "cd $TRAVIS_BUILD_DIR"
@@ -425,6 +433,7 @@ drop_virtual_env() {
   [[ $TRAVIS == "true" ]] && export HOME=$(readlink -f $TRAVIS_HOME/..) || export HOME=$TRAVIS_SAVED_HOME
   hash -r
   unset TRAVIS_SAVED_HOME
+  unset TRAVIS_SAVED_DHOME
   cd $HOME
   if [[ ${opt_keep:-0} -eq 0 ]]; then
     drop_test_db
@@ -469,20 +478,21 @@ git_clone() {
     else
       d="./"
     fi
-    run_traced "cp -R $TRAVIS_SAVED_HOME/tools $d"
-    if [ $opt_dbgmnt -ne 0 ]; then
+    run_traced "cp -R $TRAVIS_SAVED_DHOME/tools $d"
+    if [[ $opt_dbgmnt -ne 0 ]]; then
       x=${TRAVIS_REPO_SLUG#*/}
+      echo "$d=\$(find $HOME/lib -type d -name site-packages|head -n1)" #debug
       for p in $(get_cfg_value "" "PKGS_LIST"); do
         # Use unstable version
         [[ $p =~ (python-plus|z0bug-odoo) ]] && p="${p//-/_}"
-        [[ -f $TRAVIS_SAVED_HOME/devel/pypi/$p/$p/scripts/setup.info ]] && \
-          run_traced "rsync -rlpgoW --delete $TRAVIS_SAVED_HOME/devel/pypi/$p/$p/ $HOME/tools/$p/" && \
-          run_traced "cp $TRAVIS_SAVED_HOME/devel/pypi/$p/setup.py $HOME/tools/$p/"
+        [[ -f $TRAVIS_SAVED_DHOME/devel/pypi/$p/$p/scripts/setup.info ]] && \
+          run_traced "rsync -rlpgoW --delete $TRAVIS_SAVED_DHOME/devel/pypi/$p/$p/ $HOME/tools/$p/" && \
+          run_traced "cp $TRAVIS_SAVED_DHOME/devel/pypi/$p/setup.py $HOME/tools/$p/"
         s=$?; [ ${s-1} -eq 0 ] || echo "Internal error $s! Statement rsync $p failed!!"
       done
       for p in install_tools.sh odoo_default_tnl.xlsx; do
-        [[ -d $TRAVIS_SAVED_HOME/devel/pypi/tools/ ]] && \
-          run_traced "cp $TRAVIS_SAVED_HOME/devel/pypi/tools/$p $HOME/tools/$p"
+        [[ -d $TRAVIS_SAVED_DHOME/devel/pypi/tools/ ]] && \
+          run_traced "cp $TRAVIS_SAVED_DHOME/devel/pypi/tools/$p $HOME/tools/$p"
       done
       true # FIX: return no error
     fi
