[IMP] z0lib more tests

diff --git a/travis_emulator/travis_emulator/travisrc b/travis_emulator/travis_emulator/travisrc
--- a/travis_emulator/travis_emulator/travisrc
+++ b/travis_emulator/travis_emulator/travisrc
@@ -8,7 +8,7 @@
 XRGI="^(.*\/|)conf\/.*sample$"
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
-# Based on template 1.0.2.7
+# Based on template 1.0.4
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
@@ -318,7 +318,6 @@ create_virtual_env() {
   [[ $SYSTEM_SITE_PACKAGES == "true" ]] && TRAVIS_ENVOPTS="$TRAVIS_ENVOPTS --system-site-packages"
   [[ $SYSTEM_SITE_PACKAGES != "true" ]] && VENVOPTS="-DI"
   hash -r
-# TODO> restore after vem cp works
   if [[ "$PRJNAME" == "Odoo" && ( ! -d $TRAVIS_SAVED_HOME/VME/VME$BRANCH || $(stat -c %Y $TRAVIS_SAVED_HOME/VME/VME$BRANCH) -lt 1639237000 ) ]]; then
     echo -e "\n\n${RED}Cached virtual environment $TRAVIS_SAVED_HOME/VME/VME$BRANCH not found or expired!${CLR}"
     echo -e "Now virtual environment $TRAVIS_SAVED_HOME/VME/VME$BRANCH will be (re)created."
@@ -336,7 +335,6 @@ create_virtual_env() {
     true
   elif [[ $opt_full -eq 0 && ${opt_cache:-0} -ne 0 && -n "$TRAVIS_PYTHON_VERSION" ]]; then
     [[ -d $TRAVIS_SAVED_HOME ]] || mkdir $TRAVIS_SAVED_HOME
-# TODO> restore after vem cp works
      if [[ "$PRJNAME" == "Odoo" && -d $TRAVIS_SAVED_HOME/VME/VME$BRANCH ]]; then
       opt_keepE=0
       TRAVIS_SRC_VME=$TRAVIS_SAVED_HOME/VME/VME$BRANCH
@@ -370,7 +368,6 @@ create_virtual_env() {
       fi
       opts=$(inherits_travis_opts "" "V")
       [[ $TRAVIS == "true" ]] || opts="$opts -f"
-      # TODO> reactivate after validation
       [[ $sts -ne 0 || $opt_keepE -eq 0 ]] || run_traced "vem cp $VENVOPTS $opts $TRAVIS_HOME $TRAVIS_SRC_VME"
     fi
   else
@@ -402,6 +399,24 @@ create_virtual_env() {
     fi
   fi
   [[ $PWD != $TRAVIS_BUILD_DIR ]] && run_traced "cd $TRAVIS_BUILD_DIR"
+  if [[ -n "$opt_pybrk" ]]; then
+    IFS=":" read f t <<<"$opt_pybrk"
+    [[ $f =~ ^\. ]] && x=$(readlink -f $TRAVIS_BUILD_DIR/$f) || x=$(find $TRAVIS_BUILD_DIR -name $f)
+    [[ -z "$x" ]] && echo "File $f not found!" && exit 1
+    cp $x $x.bak
+    cat <<EOF | python
+with open('$x', 'r') as fd:
+    lines = fd.read().split('\n')
+    line = lines[$t - 1]
+    i = 0
+    while i < len(line) and line[i] == ' ':
+        i += 1
+    line = '%s%s' % (line[:i], 'import pdb; pdb.set_trace(); ')
+    lines.insert($t - 1, line)
+with open('$x', 'w') as fd:
+    fd.write('\n'.join(lines))
+EOF
+  fi
   ((Z0_STACK=Z0_STACK-2))
 }
 
@@ -457,7 +472,7 @@ git_clone() {
     run_traced "cp -R $TRAVIS_SAVED_HOME/tools $d"
     if [ $opt_dbgmnt -ne 0 ]; then
       x=${TRAVIS_REPO_SLUG#*/}
-      for p in $(get_cfg_value 0 "PKGS_LIST"); do
+      for p in $(get_cfg_value "" "PKGS_LIST"); do
         # Use unstable version
         [[ $p =~ (python-plus|z0bug-odoo) ]] && p="${p//-/_}"
         [[ -f $TRAVIS_SAVED_HOME/devel/pypi/$p/$p/scripts/setup.info ]] && \
@@ -566,21 +581,21 @@ check_4_travis() {
 }
 
 conf_default() {
-  [[ -z $(get_cfg_value 0 "loglevel") ]] && CFG_set "loglevel" "-1"
-  [[ -z $(get_cfg_value 0 "RUN_travis_install_nightly") ]] && CFG_set "RUN_travis_install_nightly" "travis_install_nightly"
-  [[ -z $(get_cfg_value 0 "RUN_travis_run_tests") ]] && CFG_set "RUN_travis_run_tests" "travis_run_tests"
-  [[ -z $(get_cfg_value 0 "RUN_travis_after_tests_success") ]] && CFG_set "RUN_travis_after_tests_success" "travis_after_tests_success"
-  [[ -z $(get_cfg_value 0 "MQT_TEMPLATE_DB") ]] && CFG_set "MQT_TEMPLATE_DB" "openerp_template"
-  [[ -z $(get_cfg_value 0 "MQT_TEST_DB") ]] && CFG_set "MQT_TEST_DB" "openerp_test"
-  [[ -z $(get_cfg_value 0 "MQT_DBUSER") ]] && CFG_set "MQT_DBUSER" ""
-  [[ -z $(get_cfg_value 0 "UNBUFFER") ]] && CFG_set "UNBUFFER" "0"
-  [[ -z $(get_cfg_value 0 "ME_BOS") ]] && CFG_set "ME_BOS" "test_nightly .test_nightly.conf.sample"
-  [[ -z $(get_cfg_value 0 "Environment") ]] && CFG_set "Environment" "bash"
-  [[ -z $(get_cfg_value 0 "virtualenv_opts") ]] && CFG_set "virtualenv_opts" ""
-  [[ -z $(get_cfg_value 0 "NPM_CONFIG_PREFIX") ]] && CFG_set "NPM_CONFIG_PREFIX" "$HOME/.npm-global"
-  [[ -z $(get_cfg_value 0 "PYTHON_MATRIX") ]] && CFG_set "PYTHON_MATRIX" "(2.7|3.6|3.7|3.8)"
-  [[ -z $(get_cfg_value 0 "LOGDIR") ]] && CFG_set "LOGDIR" "$HOME/travis_log"
-  [[ -z $(get_cfg_value 0 "GBL_EXCLUDE") ]] && CFG_set "GBL_EXCLUDE" "test_impex,test_ir_actions,test_lint,test_main_flows,test_search,test_user_has_group"
+  [[ -z $(get_cfg_value "" "loglevel") ]] && CFG_set "loglevel" "-1"
+  [[ -z $(get_cfg_value "" "RUN_travis_install_nightly") ]] && CFG_set "RUN_travis_install_nightly" "travis_install_nightly"
+  [[ -z $(get_cfg_value "" "RUN_travis_run_tests") ]] && CFG_set "RUN_travis_run_tests" "travis_run_tests"
+  [[ -z $(get_cfg_value "" "RUN_travis_after_tests_success") ]] && CFG_set "RUN_travis_after_tests_success" "travis_after_tests_success"
+  [[ -z $(get_cfg_value "" "MQT_TEMPLATE_DB") ]] && CFG_set "MQT_TEMPLATE_DB" "openerp_template"
+  [[ -z $(get_cfg_value "" "MQT_TEST_DB") ]] && CFG_set "MQT_TEST_DB" "openerp_test"
+  [[ -z $(get_cfg_value "" "MQT_DBUSER") ]] && CFG_set "MQT_DBUSER" ""
+  [[ -z $(get_cfg_value "" "UNBUFFER") ]] && CFG_set "UNBUFFER" "0"
+  [[ -z $(get_cfg_value "" "ME_BOS") ]] && CFG_set "ME_BOS" "test_nightly .test_nightly.conf.sample"
+  [[ -z $(get_cfg_value "" "Environment") ]] && CFG_set "Environment" "bash"
+  [[ -z $(get_cfg_value "" "virtualenv_opts") ]] && CFG_set "virtualenv_opts" ""
+  [[ -z $(get_cfg_value "" "NPM_CONFIG_PREFIX") ]] && CFG_set "NPM_CONFIG_PREFIX" "$HOME/.npm-global"
+  [[ -z $(get_cfg_value "" "PYTHON_MATRIX") ]] && CFG_set "PYTHON_MATRIX" "(2.7|3.6|3.7|3.8)"
+  [[ -z $(get_cfg_value "" "LOGDIR") ]] && CFG_set "LOGDIR" "$HOME/travis_log"
+  [[ -z $(get_cfg_value "" "GBL_EXCLUDE") ]] && CFG_set "GBL_EXCLUDE" "test_impex,test_ir_actions,test_lint,test_main_flows,test_search,test_user_has_group,test_mimetypes"
 }
 
 #
@@ -657,13 +672,10 @@ a_search() {
 matches1of() {
   # matches1of (filename, exclist)
   # return:true/false
-  local x=
+  local x sts
   sts=1
   for x in $2; do
-    if [[ "$1" =~ $x ]]; then
-      sts=0
-      break
-    fi
+    [[ $1 =~ $x ]] && sts=0 && break
   done
   return $sts
 }
@@ -692,16 +704,16 @@ robocopy_init() {
     fi
     a_append "^.*" ""
   fi
-  local xx="$(get_cfg_value 0 ignore)"
-  local yy="$(get_cfg_value 0 ignorediff)"
+  local xx="$(get_cfg_value "" ignore)"
+  local yy="$(get_cfg_value "" ignorediff)"
   if [ -z "$xx" ]; then
     # TODO: addons
     # local xx=".pyc .log .bak .out .tmp .conf .tracehis .tracehistory ,cover .coverage build/ dist/ conf/ filestore/ .cover/ .coverage/ .git/ ~"
     # local yy=".po .pot"
-    local xx="$(get_cfg_value 0 filedel)"
-    local yy="$(get_cfg_value 0 fileignore)"
+    local xx="$(get_cfg_value "" filedel)"
+    local yy="$(get_cfg_value "" fileignore)"
     local xx="$xx $yy"
-    local yy="$(get_cfg_value 0 filediffignore)"
+    local yy="$(get_cfg_value "" filediffignore)"
   fi
   XRGX=
   XLFS=
diff --git a/z0lib/z0lib/tests/test_params b/z0lib/z0lib/tests/test_params
--- a/z0lib/z0lib/tests/test_params
+++ b/z0lib/z0lib/tests/test_params
@@ -4,13 +4,13 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
-# Based on template 1.0.2.7
+# Based on template 1.0.4
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
 HOME_DEV="$HOME/devel"
 [[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
-PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEV"'\nimport os,sys\no=os.path\na=o.abspath\nj=os.path.join\nd=os.path.dirname\nb=os.path.basename\nf=os.path.isfile\np=os.path.isdir\nH=o.expanduser('~')\nT=j(H,'tools')\nR=j(H,'pypi') if o.basename(D)=='venv_tools' else j(H,D,'pypi')\nW=D if o.basename(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'script')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C)=='tests':\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==d(C) and f(j(C,'..','setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+P\np=set()\npa=p.add\np=[x for x in L if x and (x.startswith(H) or x.startswith(D) or x.startswith(C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
@@ -24,6 +24,15 @@ if [[ -z "$Z0LIBDIR" ]]; then
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
+
+TRAVISLIBDIR=$(findpkg travisrc "$PYPATH" "travis_emulator")
+if [[ -z "$TRAVISLIBDIR" ]]; then
+  echo "Library file travisrc not found!"
+  exit 72
+fi
+. $TRAVISLIBDIR
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TRAVISLIBDIR=$TRAVISLIBDIR"
+
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
 RUNDIR=$(readlink -e $TESTDIR/..)
@@ -36,6 +45,18 @@ fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+#############################
+PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEV"'\nimport os,sys\no=os.path\na=o.abspath\nj=os.path.join\nd=os.path.dirname\nb=os.path.basename\nf=os.path.isfile\np=os.path.isdir\nH=o.expanduser('~')\nT=j(H,'tools')\nR=j(H,'pypi') if o.basename(D)=='venv_tools' else j(H,D,'pypi')\nW=D if o.basename(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'script')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C)=='tests':\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==d(C) and f(j(C,'..','setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+P\np=set()\npa=p.add\np=[x for x in L if x and (x.startswith(H) or x.startswith(D) or x.startswith(C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
+for d in $PYPATH /etc; do
+  if [[ -e $d/z0librc ]]; then
+    . $d/z0librc
+    Z0LIBDIR=$(readlink -e $d)
+    break
+  fi
+done
+##############################
 
 DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
 TCONF="$HOME/.z0tools.conf"
@@ -48,21 +69,61 @@ RED="\e[1;31m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
-
 __version__=1.0.5
 
+test_common() {
+    local res pypath
+    [[ -f ./travisrc ]] && rm -f ./travisrc
+    res=$($1 PYPATH|cut -f1 -d" ")
+    test_result "$PWD/simulate_cmd PYPATH" "$res" "$(dirname $1)"
+    res=$($1 Z0LIBDIR)
+    test_result "$PWD/simulate_cmd Z0LIBDIR" "$res" "$RUNDIR"
+    # travisrc is found in python site packages
+    pypath=$(echo "import sys;print([x for x in sys.path if 'site-packages' in x][0])"|python)
+    res=$($1 PYPATH|grep -Eo $pypath/travis_emulator)
+    test_result "$PWD/simulate_cmd PYPATH/travis_emulator" "$res" "$pypath/travis_emulator"
+    res=$($1 TRAVISLIBDIR)
+    test_result "$PWD/simulate_cmd TRAVISLIBDIR" "$res" "$pypath/travis_emulator/travisrc"
+    # Now travisrc should be found in current directory
+    cp $HOME/tools/travis_emulator/travisrc ./
+    res=$($1 TRAVISLIBDIR)
+    if [[ $2 != "N" ]]; then
+      test_result "$PWD/simulate_cmd TRAVISLIBDIR (2)" "$res" "$PWD/travisrc"
+    else
+      test_result "$PWD/simulate_cmd TRAVISLIBDIR (2)" "$res" "$pypath/travis_emulator/travisrc"
+    fi
+    rm -f ./travisrc
+    res=$($1 PKGNAME)
+    test_result "$PWD/simulate_cmd PKGNAME" "$res" "z0lib"
+    res=$($1 PKGPATH)
+    test_result "$PWD/simulate_cmd PKGPATH" "$res" "$TRAVIS_BUILD_DIR"
+    res=$($1 PRJNAME)
+    test_result "$PWD/simulate_cmd PRJNAME" "$res" "z0lib"
+    res=$($1 PRJPATH)
+    test_result "$PWD/simulate_cmd PRJPATH" "$res" "$TRAVIS_BUILD_DIR"
+}
 
 test_01() {
-    local res
+    local res pypath
     cd $TESTDIR
-    res=$($TESTDIR/simulate_cmd PKGNAME)
-    test_result "$TESTDIR/simulate_cmd PKGNAME" "$res" "z0lib"
-    res=$($TESTDIR/simulate_cmd PKGPATH)
-    # test_result "$TESTDIR/simulate_cmd PKGPATH" "$res" "$TRAVIS_BUILD_DIR/z0lib"
-    res=$($TESTDIR/simulate_cmd PRJNAME)
-    test_result "$TESTDIR/simulate_cmd PRJNAME" "$res" "z0lib"
-    res=$($TESTDIR/simulate_cmd PRJPATH)
-    # test_result "$TESTDIR/simulate_cmd PRJPATH" "$res" "$TRAVIS_BUILD_DIR/z0lib"
+    res=$($TESTDIR/simulate_cmd THIS)
+    test_result "$PWD/simulate_cmd THIS" "$res" "simulate_cmd"
+    res=$($TESTDIR/simulate_cmd TDIR)
+    test_result "$PWD/simulate_cmd TDIR" "$res" "$TESTDIR"
+    res=$($TESTDIR/simulate_cmd HOME_DEV)
+    test_result "$PWD/simulate_cmd HOME_DEV" "$res" "$HOME/devel"
+    test_common $TESTDIR/simulate_cmd
+    cd $RUNDIR
+    test_common $TESTDIR/simulate_cmd
+    mv $TESTDIR/simulate_cmd $RUNDIR/simulate_cmd
+    cd $TESTDIR
+    test_common $RUNDIR/simulate_cmd "N"
+    cd $RUNDIR
+    test_common $RUNDIR/simulate_cmd
+    # mv $RUNDIR/simulate_cmd $HOME/tools/z0lib
+    # res=$($HOME/tools/z0lib/simulate_cmd TDIR)
+    # test_result "$HOME/tools/z0lib/simulate_cmd TDIR" "$res" "$HOME/tools/z0lib"
+    # mv $HOME/tools/z0lib $TESTDIR/simulate_cmd
 }
 
 Z0BUG_setup() {
@@ -77,8 +138,12 @@ Z0BUG_setup() {
     chmod +x $TESTDIR/simulate_cmd
 }
 
+Z0BUG_teardown() {
+    rm -f $TESTDIR/simulate_cmd
+}
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_..log "$@"
+parseoptest -l$TESTDIR/test_z0lib.log "$@" "-J"
 sts=$?
 [[ $sts -ne 127 ]] && exit $sts
 
