[IMP] Wide spread tests (4)

diff --git a/wok_code/tests/test_autopep8 b/wok_code/tests/test_autopep8
--- a/wok_code/tests/test_autopep8
+++ b/wok_code/tests/test_autopep8
@@ -4,22 +4,23 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
+# Based on template 1.0.2.7
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
-[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
-PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
 if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found!"
+  echo "Library file z0librc not found in <$PYPATH>!"
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
@@ -27,9 +28,6 @@ TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
 RUNDIR=$(readlink -e $TESTDIR/..)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
-RED="\e[1;31m"
-GREEN="\e[1;32m"
-CLR="\e[0m"
 Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
 if [[ -z "$Z0TLIBDIR" ]]; then
   echo "Library file z0testrc not found!"
@@ -39,7 +37,18 @@ fi
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"
 
-__version__=1.0.2.7
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
+RED="\e[1;31m"
+GREEN="\e[1;32m"
+CLR="\e[0m"
+
+__version__=1.0.3
 
 
 test_01() {
@@ -84,7 +93,7 @@ class my_class(osv.osv):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b6.1 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b6.1" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b6.1 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 7.0
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -97,7 +106,7 @@ class my_class(orm.Model):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b7.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b7.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b7.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 8.0 -u
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -110,7 +119,7 @@ class MyClass(orm.Model):
 EOF
         $RUNDIR/topep8 -qAANu -F6.1 -b8.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AANu -F6.1 -b8.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AANu -F6.1 -b8.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 8.0
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -123,7 +132,7 @@ class MyClass(models.Model):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b8.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b8.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b8.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 9.0
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -136,7 +145,7 @@ class MyClass(models.Model):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b9.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b9.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b9.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 10.0
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -149,7 +158,7 @@ class MyClass(models.Model):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b10.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b10.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b10.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 11.0
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -161,7 +170,7 @@ class MyClass(models.Model):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b11.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b11.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b11.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
     # Validate against Odoo 12.0
     if [ ${opt_dry_run:-0} -eq 0 ]; then
         cat <<EOF >$TESTRES
@@ -173,7 +182,7 @@ class MyClass(models.Model):
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b12.0 $TESTSRC -o $TESTOUT
     fi
-    test_result "topep8 -AAN -F6.1 -b12.0" "$TESTOUT" "$TESTRES" "diff"
+    test_result "topep8 -AAN -F6.1 -b12.0 $TESTSRC -o $TESTOUT" "$TESTOUT" "$TESTRES" "diff"
 }
 
 
@@ -458,7 +467,6 @@ Z0BUG_init
 parseoptest -l$TESTDIR/test_wok_code.log "$@"
 sts=$?
 [[ $sts -ne 127 ]] && exit $sts
-
 
 
 UT1_LIST=""
