[FIX] no use git --show-current

diff --git a/wok_code/tests/test_autopep8 b/wok_code/tests/test_autopep8
--- a/wok_code/tests/test_autopep8
+++ b/wok_code/tests/test_autopep8
@@ -2,30 +2,38 @@
 # -*- coding: utf-8 -*-
 # Regression tests on devel-tools
 #
+READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
+export READLINK
 THIS=$(basename "$0")
-TDIR=$(readlink -f $(dirname $0))
-PYPATH=$(echo -e "import sys\nprint(str(sys.path).replace(' ','').replace('\"','').replace(\"'\",\"\").replace(',',':')[1:-1])" | python)
-for d in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../.. $TDIR/../../z0lib $TDIR/../../z0lib/z0lib $HOME/dev $HOME/tools ${PYPATH//:/ } /etc; do
-    if [ -e $d/z0librc ]; then
-        . $d/z0librc
-        Z0LIBDIR=$d
-        Z0LIBDIR=$(readlink -e $Z0LIBDIR)
-        break
-    fi
+TDIR=$($READLINK -f $(dirname $0))
+[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
+PYPATH=$(echo -e "import os,sys\np=[x for x in (os.environ['PATH']+':$TDIR:..:$HOME_DEV').split(':') if x not in sys.path];p.extend(sys.path);print(' '.join(p))"|python)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
+for d in $PYPATH /etc; do
+  if [[ -e $d/z0librc ]]; then
+    . $d/z0librc
+    Z0LIBDIR=$d
+    Z0LIBDIR=$($READLINK -e $Z0LIBDIR)
+    break
+  fi
 done
-if [ -z "$Z0LIBDIR" ]; then
-    echo "Library file z0librc not found!"
-    exit 2
+if [[ -z "$Z0LIBDIR" ]]; then
+  echo "Library file z0librc not found!"
+  exit 72
 fi
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
-RUNDIR=$(readlink -e $TESTDIR/..)
-Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $HOME/tools/zerobug $HOME/dev ${PYPATH//:/ } . .." "zerobug")
-if [ -z "$Z0TLIBDIR" ]; then
-    echo "Library file z0testrc not found!"
-    exit 2
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
+RUNDIR=$($READLINK -e $TESTDIR/..)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
+Z0TLIBDIR=$(findpkg z0testrc "$PYPATH" "zerobug")
+if [[ -z "$Z0TLIBDIR" ]]; then
+  echo "Library file z0testrc not found!"
+  exit 72
 fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0TLIBDIR=$Z0TLIBDIR"
 
 __version__=1.0.1.11
 
@@ -69,7 +77,6 @@ a = 1
 B = A
 class my_class(osv.osv):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b6.1 $TESTSRC -o $TESTOUT
     fi
@@ -83,7 +90,6 @@ a = 1
 B = A
 class my_class(orm.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b7.0 $TESTSRC -o $TESTOUT
     fi
@@ -97,7 +103,6 @@ a = 1
 B = A
 class MyClass(orm.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAANu -F6.1 -b8.0 $TESTSRC -o $TESTOUT
     fi
@@ -111,7 +116,6 @@ a = 1
 B = A
 class MyClass(models.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b8.0 $TESTSRC -o $TESTOUT
     fi
@@ -125,7 +129,6 @@ a = 1
 B = A
 class MyClass(models.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b9.0 $TESTSRC -o $TESTOUT
     fi
@@ -139,7 +142,6 @@ a = 1
 B = A
 class MyClass(models.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b10.0 $TESTSRC -o $TESTOUT
     fi
@@ -152,7 +154,6 @@ a = 1
 B = A
 class MyClass(models.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b11.0 $TESTSRC -o $TESTOUT
     fi
@@ -165,7 +166,6 @@ a = 1
 B = A
 class MyClass(models.Model):
     pass
-
 EOF
         $RUNDIR/topep8 -qAAN -F6.1 -b12.0 $TESTSRC -o $TESTOUT
     fi
@@ -175,7 +175,7 @@ EOF
 
 test_02() {
     local TESTOUT TESTRES TESTFN
-    TESTFN=test_autopep_01
+    TESTFN=test_autopep_02
     TESTSRC=$TESTDIR/res/$TESTFN.py
     TESTRES=$TESTDIR/res/$TESTFN.test
     TESTOUT=$TESTDIR/res/$TESTFN.out
@@ -213,7 +213,6 @@ a = 1
 B = A
 
 class my_class(osv.osv):
-
 EOF
         $RUNDIR/topep8 -qAAN -F10.0 -b6.1 $TESTSRC -o $TESTOUT
     fi
@@ -228,7 +227,6 @@ a = 1
 B = A
 
 class my_class(orm.Model):
-
 EOF
         $RUNDIR/topep8 -qAAN -F10.0 -b7.0 $TESTSRC -o $TESTOUT
     fi
@@ -243,7 +241,6 @@ a = 1
 B = A
 
 class MyClass(orm.Model):
-
 EOF
         $RUNDIR/topep8 -qAANu -F10.0 -b8.0 $TESTSRC -o $TESTOUT
     fi
@@ -258,7 +255,6 @@ a = 1
 B = A
 
 class MyClass(models.Model):
-
 EOF
         $RUNDIR/topep8 -qAAN -F10.0 -b8.0 $TESTSRC -o $TESTOUT
     fi
@@ -273,7 +269,6 @@ a = 1
 B = A
 
 class MyClass(models.Model):
-
 EOF
         $RUNDIR/topep8 -qAAN -F10.0 -b9.0 $TESTSRC -o $TESTOUT
     fi
@@ -288,7 +283,6 @@ a = 1
 B = A
 
 class MyClass(models.Model):
-
 EOF
         $RUNDIR/topep8 -qAAN -F10.0 -b10.0 $TESTSRC -o $TESTOUT
     fi
@@ -302,7 +296,6 @@ a = 1
 B = A
 
 class MyClass(models.Model):
-
 EOF
         $RUNDIR/topep8 -qAAN -F10.0 -b11.0 $TESTSRC -o $TESTOUT
     fi
@@ -316,7 +309,6 @@ a = 1
 B = A
 
 class MyClass(models.Model):
-
 EOF
         $RUNDIR/topep8 -qAAN -b12.0 $TESTSRC -o $TESTOUT
     fi
@@ -381,7 +373,6 @@ EOF
         cat <<EOF >$TESTRES
 # -*- coding: utf-8 -*-
     einv_type_model = self.env['fiscal.document.type']
-
 EOF
         $RUNDIR/topep8 -qAAN -b10.0 -Rto_oca $TESTSRC -o $TESTOUT
     fi
@@ -444,7 +435,7 @@ EOF
 EOF
         cat <<EOF >$TESTRES
 # -*- coding: utf-8 -*-
-    
+
     name = fields.char()
     date = fields.date('Date')
 EOF
@@ -462,14 +453,13 @@ Z0BUG_setup() {
 Z0BUG_init
 parseoptest -l$TESTDIR/test_wok_code.log "$@"
 sts=$?
-if [ $sts -ne 127 ]; then
-  exit $sts
-fi
+[[ $sts -ne 127 ]] && exit $sts
+
 
 UT1_LIST=""
 UT_LIST=""
-if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+[[ "$(type -t Z0BUG_setup)" == "function" ]] && Z0BUG_setup
 Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
 sts=$?
-if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+[[ "$(type -t Z0BUG_teardown)" == "function" ]] && Z0BUG_teardown
 exit $sts
