[REF] Stable version

diff --git a/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis b/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis
--- a/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis
+++ b/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis
@@ -10,15 +10,15 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
-# Based on template 1.0.8
+# Based on template 2.0.0
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
-if [[ -z $HOME_DEVEL ]]; then
+if [[ -z $HOME_DEVEL || ! -d $HOME_DEVEL ]]; then
   [[ -d $HOME/odoo/devel ]] && HOME_DEVEL="$HOME/odoo/devel" || HOME_DEVEL="$HOME/devel"
 fi
-[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
-[[ -z $PYPATH ]] && PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEVEL"'\nimport os,sys\no=os.path\na=o.abspath\nj=os.path.join\nd=os.path.dirname\nb=os.path.basename\nf=os.path.isfile\np=os.path.isdir\nH=o.expanduser('~')\nT=j(d(D), 'tools')\nR=j(d(D),'pypi') if o.basename(D)=='venv_tools' else j(D,'pypi')\nW=D if o.basename(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'script')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C) in ('tests','travis','_travis'):\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==b(d(C)) and f(j(C,'..','setup.py')):\n C=a(j(C,'..','..'))\nelif b(d(C))=='tools' and f(j(C,'setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)) or p(j(C,b(C),B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+P\np=set()\npa=p.add\np=[x for x in L if x and (x.startswith(H) or x.startswith(D) or x.startswith(C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ -x $TDIR/../bin/python3 ]] && PYTHON=$(readlink -f $TDIR/../bin/python3) || [[ -x $TDIR/python3 ]] && PYTHON="$TDIR/python3" || PYTHON="python3"
+[[ -z $PYPATH ]] && PYPATH=$(echo -e "import os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nC=a('"$TDIR"')\nD='"$HOME_DEVEL"'\nif not p(D) and '/devel/' in C:\n D=C\n while b(D)!='devel':  D=d(D)\nN='venv_tools'\nU='setup.py'\nO='tools'\nH=o.expanduser('~')\nT=j(d(D),O)\nR=j(d(D),'pypi') if b(D)==N else j(D,'pypi')\nW=D if b(D)==N else j(D,'venv')\nS='site-packages'\nX='scripts'\ndef pt(P):\n P=a(P)\n if b(P) in (X,'tests','travis','_travis'):\n  P=d(P)\n if b(P)==b(d(P)) and f(j(P,'..',U)):\n  P=d(d(P))\n elif b(d(C))==O and f(j(P,U)):\n  P=d(P)\n return P\ndef ik(P):\n return P.startswith((H,D,K,W)) and p(P) and p(j(P,X)) and f(j(P,'__init__.py')) and f(j(P,'__main__.py'))\ndef ak(L,P):\n if P not in L:\n  L.append(P)\nL=[C]\nK=pt(C)\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n for P in [C]+sys.path+os.environ['PATH'].split(':')+[W,R,T]:\n  P=pt(P)\n  if B==b(P) and ik(P):\n   ak(L,P)\n   break\n  elif ik(j(P,B,B)):\n   ak(L,j(P,B,B))\n   break\n  elif ik(j(P,B)):\n   ak(L,j(P,B))\n   break\n  elif ik(j(P,S,B)):\n   ak(L,j(P,S,B))\n   break\nak(L,os.getcwd())\nprint(' '.join(L))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
@@ -27,23 +27,14 @@ for d in $PYPATH /etc; do
     break
   fi
 done
-if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found in <$PYPATH>!"
-  exit 72
-fi
+[[ -z "$Z0LIBDIR" ]] && echo "Library file z0librc not found in <$PYPATH>!" && exit 72
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
 ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
-if [[ -z "$ODOOLIBDIR" ]]; then
-  echo "Library file odoorc not found!"
-  exit 72
-fi
+[[ -z "$ODOOLIBDIR" ]] && echo "Library file odoorc not found!" && exit 72
 . $ODOOLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
 TRAVISLIBDIR=$(findpkg travisrc "$PYPATH" "travis_emulator")
-if [[ -z "$TRAVISLIBDIR" ]]; then
-  echo "Library file travisrc not found!"
-  exit 72
-fi
+[[ -z "$TRAVISLIBDIR" ]] && echo "Library file travisrc not found!" && exit 72
 . $TRAVISLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TRAVISLIBDIR=$TRAVISLIBDIR"
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
@@ -51,8 +42,8 @@ TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
 
-DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
-TCONF="$HOME/.z0tools.conf"
+# DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+# TCONF="$HOME/.z0tools.conf"
 CFG_init "ALL"
 link_cfg_def
 link_cfg $DIST_CONF $TCONF
@@ -62,7 +53,7 @@ RED="\e[1;31m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
-__version__=1.0.6
+__version__=2.0.0
 
 
 store_cfg_param_value() {
@@ -111,9 +102,9 @@ process_yaml_init() {
   [[ -z $PGUSER ]] && export PGUSER=$(get_dbuser)
   python_ver_req=""
   python_ver_ena=""
-  [[ -f $PRJPATH/travis.ini ]] && python_ver_ena=$(cat $PRJPATH/travis.ini|grep "^PYPI_RUN_PYVER"|awk -F= '{print $2}'|grep -Eo "[0-9.]+"|head -n1)
+  [[ -f $PRJPATH/travis.ini ]] && python_ver_ena=$(cat $PRJPATH/travis.ini|grep "^PYPI_RUN_PYVER"|awk -F= '{print $2}'|grep --color=never -Eo "[0-9.]+"|head -n1)
   if [ $opt_dbgmnt -ne 0 ]; then
-    [[ -d $HOME_DEVEL/pypi ]] && export YML_lisa=$HOME/devel/pypi/lisa/lisa/lisa
+    [[ -d $HOME_DEVEL/pypi ]] && export YML_lisa=$HOME_DEVEL/pypi/lisa/lisa/lisa
     (($opt_debug)) && export TRAVIS_PDB="true"
   else
     export YML_lisa=lisa
@@ -448,7 +439,7 @@ process_yaml_before_install() {
   fi
   if [ $sts -eq $STS_SUCCESS ]; then
     [[ -n $opt_trace && ::addons.apt.package =~ $opt_trace ]] && debug_shell "::addons.apt.package"
-    CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo [0-9] | head -n1)
+    CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep --color=never -Eo '[0-9]' | head -n1)
     for lne in $YML_packages; do
       if [[ "$lne" == "python-dev" && $CURPYVER == "3" ]]; then
         [[ "$FH" == "RHEL" ]] && lne="python3-devel" || lne="python3-dev"
@@ -657,9 +648,9 @@ process_yaml_run_cmd() {
             if [ -n "$tk" ]; then
               if [ "${tk:0:4}" == "http" ]; then
                 p=$(basename $tk)
-                tk=$(echo $p | grep -Eo '[a-zA-Z0-9_]*' | head -n1)
+                tk=$(echo $p | grep --color=never -Eo '[a-zA-Z0-9_]*' | head -n1)
               fi
-              p=$(echo "$tk" | grep -Eo '[^!<=>;\[]*' | head -n1)
+              p=$(echo "$tk" | grep --color=never -Eo '[^!<=>;\[]*' | head -n1)
               p=${p//\"/}
               p=$(echo $p)
               if [ "$p" == "transifex-client" ]; then
@@ -672,7 +663,7 @@ process_yaml_run_cmd() {
             fi
           done <$pp
         elif [ "${tk:0:1}" != "-" ]; then
-          p=$(echo "${x[$ix]}" | grep -Eo '[^!<=>;]*' | head -n1)
+          p=$(echo "${x[$ix]}" | grep --color=never -Eo '[^!<=>;]*' | head -n1)
           p=${p//\"/}
           if $(pip show $p &>/dev/null); then
             xcmd="$xcmd $p"
@@ -770,6 +761,7 @@ process_yaml_run_cmd() {
 #    fi
     [[ $c != $xcmd && ! $xcmd =~ ^# ]] && ((Z0_STACK=Z0_STACK-2))
   fi
+  [[ $TRAVIS_DEBUG_MODE -gt 2 ]] && echo "<<<PATH=$PATH>>>"
   [[ -n $opt_tafter && $xcmd =~ $opt_tafter ]] && debug_shell
   return $sts
 }
@@ -800,7 +792,7 @@ process_yaml() {
     sts=$STS_SUCCESS
     wlog "\e[${PS_HDR2_COLOR}m===== [System informations] =====\e[0m"
     TODAY=$(date "+%Y-%m-%d %H:%M:%S")
-    for lne in TODAY job-id __version__ TCONF YML_FILE YML_lisa YML_mgrodoo YML_repo BRANCH DIST LOGFILE PGUSER MQT_TEMPLATE_DB MQT_TEST_DB PRJNAME PKGNAME REPOSNAME PRJPATH PKGPATH PATH TOOLS_PATH TRAVIS TRAVIS_EMULATE_OSX TRAVIS_HOME_BRANCH TRAVIS_REPO_SLUG TRAVIS_PDB; do
+    for lne in TODAY job-id __version__ TCONF YML_FILE YML_lisa YML_mgrodoo YML_repo BRANCH DIST HOME HOME_DEVEL LOGFILE PGUSER MQT_TEMPLATE_DB MQT_TEST_DB ODOO_ROOT PRJNAME PKGNAME REPOSNAME PRJPATH PKGPATH PATH TOOLS_PATH TRAVIS TRAVIS_EMULATE_OSX TRAVIS_HOME_BRANCH TRAVIS_REPO_SLUG TRAVIS_PDB; do
       if [[ $lne == "job-id" ]]; then
         lne1=$$
       elif [[ $lne == "DIST" ]]; then
@@ -818,7 +810,7 @@ process_yaml() {
     fi
     if [[ $sts -eq $STS_SUCCESS ]]; then
       [[ -n $opt_trace && ::matrix =~ $opt_trace ]] && debug_shell "::matrix"
-      [[ -z "$python_ver_req" ]] && python_ver_req=$(python --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
+      [[ -z "$python_ver_req" ]] && python_ver_req=$(python --version 2>&1 | grep --color=never -Eo "[0-9]+\.[0-9]+")
       [[ -z "$opt_pyv" ]] && opt_pyv=$(get_cfg_value "" "PYTHON_MATRIX")
       [[ -z "$opt_pyv" ]] && opt_pyv="(2.7|3.5|3.6|3.7|3.8)"
       opt_pyv="${opt_pyv//,/|}"
@@ -833,13 +825,15 @@ process_yaml() {
       for TRAVIS_PYTHON_VERSION in $python_matrix; do
         [[ $sts -eq $STS_SUCCESS ]] || break
         wlog "\e[${PS_HDR1_COLOR}m===== [Build python $TRAVIS_PYTHON_VERSION] =====\e[0m"
-        CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo "[0-9]" | head -n1)
-        CURPYVER2=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo "[0-9]\.[0-9]" | head -n1)
-        PYTHON=$(which python$TRAVIS_PYTHON_VERSION)
-        [[ -z "$PYTHON" ]] && PYTHON=$(which python$CURPYVER2)
-        [[ -z "$PYTHON" ]] && PYTHON=$(which python$CURPYVER)
-        PYTHON_VERSION=$($PYTHON --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
-        if [[ $($PYTHON --version 2>&1 | grep -Eo "[0-9.]+") != $TRAVIS_PYTHON_VERSION ]]; then
+        set_pybin $TRAVIS_PYTHON_VERSION "PYTHON_VERSION"
+        CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep --color=never -Eo "[0-9]" | head -n1)
+        CURPYVER2=$(echo $TRAVIS_PYTHON_VERSION | grep --color=never -Eo "[0-9]\.[0-9]" | head -n1)
+#        PYTHON=$(which python$TRAVIS_PYTHON_VERSION)
+#        [[ -z "$PYTHON" ]] && PYTHON=$(which python$CURPYVER2)
+#        [[ -z "$PYTHON" ]] && PYTHON=$(which python$CURPYVER)
+#        PYTHON_VERSION=$($PYTHON --version 2>&1 | grep --color=never -Eo "[0-9]+\.[0-9]+")
+#        if [[ $($PYTHON --version 2>&1 | grep --color=never -Eo "[0-9]+\.[0-9]+") != $TRAVIS_PYTHON_VERSION ]]; then
+        if [[ $PYTHON_VERSION != $TRAVIS_PYTHON_VERSION ]]; then
           if [[ $PYTHON_VERSION != $CURPYVER2 ]]; then
             wlog "\e[${PS_HDR1_COLOR}mError: Required version $TRAVIS_PYTHON_VERSION of python is not availale. Replace by $PYTHON_VERSION\e[${PS_TXT_COLOR}m"
             continue
@@ -857,7 +851,7 @@ process_yaml() {
           [[ -n "$lne1" || $lne =~ PATH ]] && wlog "\e[${PS_RUN_COLOR}m\$ $lne=$lne1\e[0m"
         done
         if [[ $TRAVIS_DEBUG_MODE -gt 2 ]]; then
-          if [ $CURPYVER -eq 3 ]; then
+          if [[ $CURPYVER -eq 3 ]]; then
             echo -e "import sys\nprint('sys.path=%s' % sys.path)\n" | $PYTHON
           else
             echo -e "import sys\nprint 'sys.path=%s' % sys.path\n" | $PYTHON
@@ -894,13 +888,10 @@ process_yaml() {
           [[ -n $opt_trace && ::build =~ $opt_trace ]] && debug_shell "::build"
           create_virtual_env
           wlog "\e[${PS_HDR2_COLOR}m----- [System informations] -----\e[0m"
-          for p in PATH HOME HOME_BRANCH PIP PYTHON PYTHONPATH PYPI_CACHED TRAVIS SYSTEM_SITE_PACKAGES TRAVIS_BUILD_DIR TRAVIS_BRANCH TRAVIS_HOME TRAVIS_SAVED_HOME; do
+          for p in PATH HOME HOME_BRANCH PIP PYTHON PYTHONPATH PYPI_CACHED TRAVIS SYSTEM_SITE_PACKAGES TRAVIS_BUILD_DIR TRAVIS_BRANCH TRAVIS_HOME TRAVIS_SAVED_HOME TRAVIS_SAVED_HOME_DEVEL; do
             X=${!p}
             [[ -n "$X" || $p =~ PATH ]] && wlog "\e[${PS_RUN_COLOR}m\$ $p=$X\e[0m"
           done
-#          for p in pip python; do
-#            eval $p --version
-#          done
           [[ -n $opt_tafter && ::build =~ $opt_tafter ]] && debug_shell
           process_yaml_global
           if [ $sts -eq $STS_SUCCESS ]; then
@@ -917,6 +908,7 @@ process_yaml() {
           fi
           if [ $sts -eq $STS_SUCCESS ]; then
             wlog "\e[${PS_HDR2_COLOR}m===== [Script matrix $lne1] =====\e[0m"
+            [[ -n $opt_trace && ::script =~ $opt_trace ]] && debug_shell "::script"
             for lne in $YML_script; do
               process_yaml_run_cmd "$lne"
               s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
@@ -1046,7 +1038,6 @@ opts_travis
 conf_default
 [[ $opt_verbose -gt 2 ]] && set -x
 init_travis
-# prepare_env_travis
 
 [[ -n $opt_flog ]] && LOGDIR="$(dirname $opt_flog)" || LOGDIR="$(get_cfg_value "" "LOGDIR")"
 [[ -d $LOGDIR ]] || mkdir $LOGDIR
@@ -1131,61 +1122,64 @@ elif [[ $action == "parseyaml" ]]; then
 elif [[ $action =~ (wep_db|wep-db) ]]; then
   export PGUSER="$(get_cfg_value "" "MQT_DBUSER")"
   [[ -z $PGUSER ]] && export PGUSER=$(get_dbuser)
-  if [[ -n $PGUSER ]]; then
-    done=0
-    all_dbs=1
-    [[ $opt_force -ne 0 ]] && md=30 || md=1800
-    dt=$(date "+%s")
-    for d in $HOME/VENV_*; do
-      if [[ "$d" != "$HOME/VENV_*" ]]; then
-        dd=$(stat -c "%Y" $d)
-        df=$(($dt - $dd))
-        if [[ $df -gt $md ]]; then
-          echo "\$ rm -fR $d ($(date -d@$df -u +"%H:%M:%S") old)"
-          rm -fR $d
-          sfx=$(echo "$d" | grep -Eo "[0-9]+$")
+  done_db=0
+  done_ve=0
+  all_dbs=1
+  [[ $opt_force -ne 0 ]] && md=30 || md=1800
+  dt=$(date "+%s")
+  for d in $HOME/VENV_*; do
+    if [[ "$d" != "$HOME/VENV_*" ]]; then
+      dd=$(stat -c "%Y" $d)
+      df=$(($dt - $dd))
+      if [[ $df -gt $md ]]; then
+        [[ $opt_verbose -gt 0 ]] && echo "\$ rm -fR $d ($(date -d@$df -u +"%H:%M:%S") old)"
+        rm -fR $d
+        ((done_ve++))
+        sfx=$(echo "$d" | grep --color=never -Eo "[0-9]+$")
+        if [[ -n $PGUSER ]]; then
           for db in openerp_template$sfx openerp_test$sfx; do
-            echo "\$ dropdb -U$PGUSER $db"
+            [[ $opt_verbose -gt 0 ]] && echo "\$ dropdb -U$PGUSER $db"
             pg_db_active -wa $db
             dropdb -U$PGUSER $db --if-exists &>/dev/null
-            done=1
+            ((done_db++))
           done
-        else
-          ((dd = md - df))
-          echo "$d ($(date -d@$df -u +"%H:%M:%S") old) will be removed in ${dd}s"
-          all_dbs=0
         fi
+      else
+        ((dd = md - df))
+        echo "$d ($(date -d@$df -u +"%H:%M:%S") old) will be removed in ${dd}s"
+        all_dbs=0
+      fi
+    fi
+  done
+  if [[ -n $PGUSER && $all_dbs -ne 0 ]]; then
+    for db in $(psql -U$PGUSER -Atl | grep -E "(openerp_template|openerp_test)" | awk -F"|" '{print $1}'); do
+      [[ $opt_verbose -gt 0 ]] && echo "\$ dropdb -U$PGUSER $db"
+      pg_db_active -wa $db
+      dropdb -U$PGUSER $db --if-exists &>/dev/null
+      ((done_db++))
+    done
+  fi
+  ((md = 60 * 60 * 24 * 90))
+  if [[ -n "$LOGDIR" && -d $LOGDIR ]]; then
+    for d in $LOGDIR/*; do
+      dd=$(stat -c "%Y" $d)
+      df=$(($dt - $dd))
+      if [[ $df -gt $md ]]; then
+        [[ $opt_verbose -gt 0 ]] && echo "\$ rm -fR $d ($(date -d@$df -u +"%H:%M:%S") old)"
+        rm -fR $d
+        ((done_ve++))
       fi
     done
-    if [[ $all_dbs -ne 0 ]]; then
-      for db in $(psql -U$PGUSER -Atl | grep -E "(openerp_template|openerp_test)" | awk -F"|" '{print $1}'); do
-        echo "\$ dropdb -U$PGUSER $db"
-        pg_db_active -wa $db
-        dropdb -U$PGUSER $db --if-exists &>/dev/null
-        done=1
-      done
-    fi
-    ((md = 60 * 60 * 24 * 90))
-    if [[ -n "$LOGDIR" && -d $LOGDIR ]]; then
-      for d in $LOGDIR/*; do
-        dd=$(stat -c "%Y" $d)
-        df=$(($dt - $dd))
-        if [[ $df -gt $md ]]; then
-          echo "\$ rm -fR $d ($(date -d@$df -u +"%H:%M:%S") old)"
-          rm -fR $d
-        fi
-      done
-    fi
-    [[ $done -eq 0 ]] && echo "Nothing to wep"
-    exit $STS_SUCCESS
-  else
-    exit 2
   fi
+  [[ $done_db -eq 0 ]] && echo "Warning: no DB to wep"
+  [[ $done_db -ne 0 && $opt_verbose -gt 0 ]] && echo "$done_db DB removed"
+  [[ $done_ve -ne 0 && $opt_verbose -gt 0 ]] && echo "$done_ve directories removed"
+  exit $STS_SUCCESS
 elif [[ $action == "summary" ]]; then
   [[ "$sub" == "old" ]] && logfile=$OLD_LOGFILE || logfile=$LOGFILE
   sts=0
   if [[ -f $logfile ]]; then
-    echo "$(readlink -f $logfile):\$ VIRTUALENV=$(grep -E "vem .*VENV_" $logfile|grep -Eo "VENV_[0-9]+"|head -n1)"
+    echo "$(readlink -f $logfile):\$ VIRTUALENV=$(grep -E "vem .*VENV_" $logfile|grep --color=never -Eo "VENV_[0-9]+"|head -n1)"
     grep -EH "(\| .*test|TODAY=|PKGNAME=|LOGFILE=|Build python [23])" $logfile
     travis_status "$logfile"
     sts=$?
@@ -1235,6 +1229,7 @@ if [[ $sts -eq $STS_SUCCESS ]]; then
         if [[ ${opt_dry_run:-0} -gt 0 ]]; then
             echo "> travis > $LOGFILE"
         else
+            clear
             echo -e "\e[0;30;107m$(printf '%-80.80s' ' ')\e[0m"
             process_yaml 2>&1 | stdbuf -i0 -o0 -e0 tee -a $TMP_LOGFILE
             sts=$?
diff --git a/wok_code/build/lib.linux-x86_64-2.7/wok_code/topep8 b/wok_code/build/lib.linux-x86_64-2.7/wok_code/topep8
--- a/wok_code/build/lib.linux-x86_64-2.7/wok_code/topep8
+++ b/wok_code/build/lib.linux-x86_64-2.7/wok_code/topep8
@@ -7,15 +7,15 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
-# Based on template 1.0.8
+# Based on template 2.0.0
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
 [ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
-if [[ -z $HOME_DEVEL ]]; then
+if [[ -z $HOME_DEVEL || ! -d $HOME_DEVEL ]]; then
   [[ -d $HOME/odoo/devel ]] && HOME_DEVEL="$HOME/odoo/devel" || HOME_DEVEL="$HOME/devel"
 fi
-[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
-[[ -z $PYPATH ]] && PYPATH=$(echo -e "C='"$TDIR"'\nD='"$HOME_DEVEL"'\nimport os,sys\no=os.path\na=o.abspath\nj=os.path.join\nd=os.path.dirname\nb=os.path.basename\nf=os.path.isfile\np=os.path.isdir\nH=o.expanduser('~')\nT=j(d(D), 'tools')\nR=j(d(D),'pypi') if o.basename(D)=='venv_tools' else j(D,'pypi')\nW=D if o.basename(D)=='venv_tools' else j(D,'venv')\ndef apl(L,P,B):\n if P:\n  if p(j(P,B,B)) and p(j(P,B,B,'script')) and f(j(P,B,B,'__init__')):\n   L.append(j(P,B,B))\n   return 1\n  elif j(P,B):\n   L.append(j(P,B))\n   return 1\n return 0\nL=[C]\nif b(C) in ('tests','travis','_travis'):\n C=a(j(C,'..'))\n L.append(C)\nif b(C)==b(d(C)) and f(j(C,'..','setup.py')):\n C=a(j(C,'..','..'))\nelif b(d(C))=='tools' and f(j(C,'setup.py')):\n C=a(j(C,'..'))\nP=os.environ['PATH'].split(':')\nV= ''\nfor X in sys.path:\n if not p(T) and p(j(X,'tools')):\n  T=j(X,'tools')\n if not V and b(X)=='site-packages':\n  V=X\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if p(j(C,B)) or p(j(C,b(C),B)):\n  F=apl(L,C,B)\n else:\n  F=0\n  for X in P:\n   if p(j(X,B)):\n    F=apl(L,X,B)\n    break\n  if not F:\n   F=apl(L,V,B)\n  if not F:\n   apl(L,T,B)\nL=L+P\np=set()\npa=p.add\np=[x for x in L if x and (x.startswith(H) or x.startswith(D) or x.startswith(C)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
+[[ -x $TDIR/../bin/python3 ]] && PYTHON=$(readlink -f $TDIR/../bin/python3) || [[ -x $TDIR/python3 ]] && PYTHON="$TDIR/python3" || PYTHON="python3"
+[[ -z $PYPATH ]] && PYPATH=$(echo -e "import os,sys\no=os.path\na=o.abspath\nj=o.join\nd=o.dirname\nb=o.basename\nf=o.isfile\np=o.isdir\nC=a('"$TDIR"')\nD='"$HOME_DEVEL"'\nif not p(D) and '/devel/' in C:\n D=C\n while b(D)!='devel':  D=d(D)\nN='venv_tools'\nU='setup.py'\nO='tools'\nH=o.expanduser('~')\nT=j(d(D),O)\nR=j(d(D),'pypi') if b(D)==N else j(D,'pypi')\nW=D if b(D)==N else j(D,'venv')\nS='site-packages'\nX='scripts'\ndef pt(P):\n P=a(P)\n if b(P) in (X,'tests','travis','_travis'):\n  P=d(P)\n if b(P)==b(d(P)) and f(j(P,'..',U)):\n  P=d(d(P))\n elif b(d(C))==O and f(j(P,U)):\n  P=d(P)\n return P\ndef ik(P):\n return P.startswith((H,D,K,W)) and p(P) and p(j(P,X)) and f(j(P,'__init__.py')) and f(j(P,'__main__.py'))\ndef ak(L,P):\n if P not in L:\n  L.append(P)\nL=[C]\nK=pt(C)\nfor B in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n for P in [C]+sys.path+os.environ['PATH'].split(':')+[W,R,T]:\n  P=pt(P)\n  if B==b(P) and ik(P):\n   ak(L,P)\n   break\n  elif ik(j(P,B,B)):\n   ak(L,j(P,B,B))\n   break\n  elif ik(j(P,B)):\n   ak(L,j(P,B))\n   break\n  elif ik(j(P,S,B)):\n   ak(L,j(P,S,B))\n   break\nak(L,os.getcwd())\nprint(' '.join(L))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
@@ -24,28 +24,19 @@ for d in $PYPATH /etc; do
     break
   fi
 done
-if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found in <$PYPATH>!"
-  exit 72
-fi
+[[ -z "$Z0LIBDIR" ]] && echo "Library file z0librc not found in <$PYPATH>!" && exit 72
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
 ODOOLIBDIR=$(findpkg odoorc "$PYPATH" "clodoo")
-if [[ -z "$ODOOLIBDIR" ]]; then
-  echo "Library file odoorc not found!"
-  exit 72
-fi
+[[ -z "$ODOOLIBDIR" ]] && echo "Library file odoorc not found!" && exit 72
 . $ODOOLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "ODOOLIBDIR=$ODOOLIBDIR"
 TRAVISLIBDIR=$(findpkg travisrc "$PYPATH" "travis_emulator")
-if [[ -z "$TRAVISLIBDIR" ]]; then
-  echo "Library file travisrc not found!"
-  exit 72
-fi
+[[ -z "$TRAVISLIBDIR" ]] && echo "Library file travisrc not found!" && exit 72
 . $TRAVISLIBDIR
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TRAVISLIBDIR=$TRAVISLIBDIR"
 
-DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
-TCONF="$HOME/.z0tools.conf"
+# DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+# TCONF="$HOME/.z0tools.conf"
 CFG_init "ALL"
 link_cfg_def
 link_cfg $DIST_CONF $TCONF
@@ -55,7 +46,7 @@ RED="\e[1;31m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
-__version__=1.0.9
+__version__=2.0.0
 
 [[ -f $TDIR/../../clodoo/list_requirements.py ]] && LISTREQ=$TDIR/../../clodoo/list_requirements.py || LISTREQ=list_requirements.py
 YAML_TMPL=~/dev/pypi/z0bug_odd/z0bug_odoo/sample_files/.travis.yml
@@ -79,7 +70,7 @@ get_ver() {
     if [ "$BRANCH" == "master" ]; then
       ver=$BRANCH
     else
-      ver=$(echo $BRANCH | grep -Eo '[0-9]+' | head -n1)
+      ver=$(echo $BRANCH | grep --color=never -Eo '[0-9]+' | head -n1)
     fi
   else
     ver=master
@@ -275,7 +266,7 @@ format_yaml() {
       lne=$(echo $line)
       if [[ "$cur_sub" == "odoo_repo" && ! $lne =~ -\ TESTS=...\ ODOO_REPO=.*/OCB ]]; then
         if [[ ! "${found[repo_zero]}" == "t" || "$PKGNAME" == "OCB" ]]; then
-          x=$(echo $opt_copy | grep -Eo [a-z]+ | head -n1)
+          x=$(echo $opt_copy | grep --color=never -Eo '[a-z]+' | head -n1)
           org=$(build_odoo_param GIT_ORGNM $odoo_vid "" "$x")
           echo "    - TESTS=\"1\" ODOO_REPO=\"$org/OCB\"" >>$fntmp
         fi
@@ -423,7 +414,7 @@ format_yaml() {
           echo "  # Use Zeroincombenze(R) tools" >>$fntmp
           echo "  - git clone https://github.com/zeroincombenze/tools.git \${HOME}/tools --single-branch --depth=1" >>$fntmp
           echo "  - \${HOME}/tools/install_tools.sh -qpt" >>$fntmp
-          echo "  - source \${HOME}/devel/activate_tools" >>$fntmp
+          echo "  - source \${HOME}/devel/activate_tools -t" >>$fntmp
           if [[ $PKGNAME == "OCB" ]]; then
             echo "  # - \"export DISPLAY=:99.0\"" >>$fntmp
             echo "  # - \"sh -e /etc/init.d/xvfb start\"" >>$fntmp
@@ -539,9 +530,9 @@ format_xml() {
       elif [ "${lne:0:9}" == "<template" ]; then
         ((level++))
       else
-        o=$(echo $lne | grep -Eo "<[a-zA-Z0-9-]+" | wc -l)
-        c=$(echo $lne | grep -Eo "</[a-zA-Z0-9-]+" | wc -l)
-        k=$(echo $lne | grep -Eo "/>" | wc -l)
+        o=$(echo $lne | grep --color=never -Eo "<[a-zA-Z0-9-]+" | wc -l)
+        c=$(echo $lne | grep --color=never -Eo "</[a-zA-Z0-9-]+" | wc -l)
+        k=$(echo $lne | grep --color=never -Eo "/>" | wc -l)
         ((c = c + k))
         if [ $o -gt $c ]; then
           ((level++))
@@ -565,7 +556,7 @@ format_xml() {
         line="$lne"
       elif [ "${lne:0:1}" == "<" ]; then
         [ "$line" == "⌂" ] && line="$lm$lne"
-        x=$(echo "$line" | grep -Eo "[[:space:]]*<[a-zA-Z0-9-]+[[:space:]]*")
+        x=$(echo "$line" | grep --color=never -Eo "[[:space:]]*<[a-zA-Z0-9-]+[[:space:]]*")
         nxtlm=${#x}
       elif [ "$line" == "⌂" ]; then
         lm=
@@ -613,14 +604,14 @@ FCONF=$TDIR/.$THIS.conf
 OPTOPTS=(h        a        A         B         b         c         C        D       d        e        F        f       G       i       L         n            N        o       O        R        q           u       V           v           X       x       0     1)
 OPTDEST=(opt_help opt_aggr opt_nauto opt_debug odoo_vid  opt_Camel opt_copy opt_dbg opt_diff opt_nenh opt_from opt_fut opt_gpl opt_imp opt_nlint opt_dry_run  opt_nonl opt_out opt_c2o  opt_rule opt_verbose opt_ut7 opt_version opt_verbose opt_xec opt_fmt opt_z opt_1)
 OPTACTI=('+'      "+"      '+'       1         "="       1         "="      1       1        1        "="      1       "="     1       1         1            1        "="     1        "="      0           1       "*>"        "+"         1       1       1     1)
-OPTDEFL=(1        0        0         0         ""        0         ""       0       0        0        ""       0       ""      0       0         0            0        ""      0        ""       0           0       ""          -1          0       0       0     0)
+OPTDEFL=(1        0        2         0         ""        0         ""       0       0        0        ""       0       ""      0       0         0            0        ""      0        ""       0           0       ""          -1          0       0       0     0)
 OPTMETA=("help"   "aggres" ""        ""        "version" "camel"   "org"    ""      "diff"   ""       "ver"    ""      "gpl"   ""      ""        "do nothing" ""       "file"  ""       "file"   "silent"   "ut7"   "version"    "verbose"   ""      ""      ""    "")
 OPTHELP=("this help"
   "enable non-whitespace changes (may issue multiple -a)"
-  "do not execute autoflake (-A) neither autopep8 (-AA)"
+  "deprecated"
   "activate debug statements"
   "odoo branch; may be 6.1 7.0 8.0 9.0 10.0 11.0 12.0 or 13.0"
-  "change class name to CamelCase"
+  "deprecated"
   "add developers Copyright (comma separated, def zero)"
   "show debug informations"
   "show diff"
@@ -628,12 +619,12 @@ OPTHELP=("this help"
   "from odoo branch, value like -b switch"
   "futurize"
   "Write GPL info into header (agpl,lgpl,gpl,opl,oee)"
-  "sort import statements"
+  "deprecated"
   "set file excluded by lint parse"
   "do nothing (dry-run)"
   "do not add newline at the EOF"
   "output filename, leave source unchanged rather than source becomes .bak"
-  "change copyright from openerp to odoo"
+  "deprecated"
   "use specific rule file"
   "silent mode"
   "use old api odoo<8.0 or create yaml old style"
@@ -660,6 +651,8 @@ opts_travis
 conf_default
 [[ $opt_verbose -gt 2 ]] && set -x
 init_travis
+# prepare_env_travis
+# prepare_env_travis
 # prepare_env_travis
 
 optfnd="-type f"
@@ -750,10 +743,10 @@ for fl in $LIST; do
           AP8OPTS="$AP8OPTS -$x"
         fi
         srcfile="$f"
-        if [ $opt_imp -ne 0 ]; then
-          isort $f -d >$f.tmp
-          ! $(grep -q "Skipped [0-9]* files" $f.tmp) && srcfile="$f.tmp"
-        fi
+#        if [ $opt_imp -ne 0 ]; then
+#          isort $f -d >$f.tmp
+#          ! $(grep -q "Skipped [0-9]* files" $f.tmp) && srcfile="$f.tmp"
+#        fi
         if [ $opt_fut -ne 0 ] && [[ ! $f =~ (__manifest__.py|__openerp__.py|__init__.py) ]]; then
           futurize --no-diffs -pauwn2 $srcfile -o ~/py3
           if [[ -f ~/py3/$(basename $f) ]]; then
@@ -769,20 +762,20 @@ for fl in $LIST; do
           cp $srcfile $f.new
         fi
         [ -f $f.tmp ] && rm -f $f.tmp
-        [ $opt_c2o -ne 0 ] && sed -e 's/openerp\.com/odoo.com/' -i $f.new
-        if [ $opt_nauto -lt 2 ]; then
-          run_traced "autopep8 $AP8OPTS $f.new -i && sed 's/ $/\n/' -i $f.new"
-        fi
-        if [ $opt_Camel -gt 0 ]; then
-          run_traced "oca-autopep8 --select=CW0001 -i $f.new"
-        fi
-        if [ $opt_nauto -lt 1 ]; then
-          oca-autopep8 --select=CW0002 -i $f.new
-          run_traced "autoflake --imports=openerp,openerp.http.request,openerp.SUPERUSER_ID,openerp.addons.base.ir.ir_qweb,openerp.exceptions.ValidationError,openerp.fields,openerp.api.openerp.models,openerp.osv.fields,openerp.osv.api,telebot,lxml,werkzeug,MySQLdb.cursors,cStringIO.StringIO,werkzeug.utils,pandas.merge,pandas.DataFrame,werkzeug.wsgi.wrap_file,werkzeug.wsgi,werkzeug.wsgi.wrap_file,openerp.exceptions,openerp.tools.DEFAULT_SERVER_DATETIME_FORMAT -i $f.new"
-        fi
+#        [ $opt_c2o -ne 0 ] && sed -e 's/openerp\.com/odoo.com/' -i $f.new
+#        if [ $opt_nauto -lt 2 ]; then
+#          run_traced "autopep8 $AP8OPTS $f.new -i && sed 's/ $/\n/' -i $f.new"
+#        fi
+#        if [ $opt_Camel -gt 0 ]; then
+#          run_traced "oca-autopep8 --select=CW0001 -i $f.new"
+#        fi
+#        if [ $opt_nauto -lt 1 ]; then
+#          oca-autopep8 --select=CW0002 -i $f.new
+#          run_traced "autoflake --imports=openerp,openerp.http.request,openerp.SUPERUSER_ID,openerp.addons.base.ir.ir_qweb,openerp.exceptions.ValidationError,openerp.fields,openerp.api.openerp.models,openerp.osv.fields,openerp.osv.api,telebot,lxml,werkzeug,MySQLdb.cursors,cStringIO.StringIO,werkzeug.utils,pandas.merge,pandas.DataFrame,werkzeug.wsgi.wrap_file,werkzeug.wsgi,werkzeug.wsgi.wrap_file,openerp.exceptions,openerp.tools.DEFAULT_SERVER_DATETIME_FORMAT -i $f.new"
+#        fi
         # TOFIX
         if [[ -n "$opt_from" && $f =~ (__manifest__.py|__openerp__.py) ]]; then
-          vf=$(grep -Eo "['\"]version['\"]: ['\"][0-9.]+['\"]" $f.new)
+          vf=$(grep --color=never -Eo "['\"]version['\"]: ['\"][0-9.]+['\"]" $f.new)
           vt="${vf/$opt_from/$odoo_fver}"
           sed -e "s|$vf|$vt|" -i $f.new
         fi
