[IMP] Stable apps

diff --git a/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis b/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis
--- a/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis
+++ b/travis_emulator/build/lib.linux-x86_64-2.7/travis_emulator/travis
@@ -10,22 +10,23 @@
 #
 READLINK=$(which greadlink 2>/dev/null) || READLINK=$(which readlink 2>/dev/null)
 export READLINK
+# Based on template 1.0.3.3
 THIS=$(basename "$0")
 TDIR=$(readlink -f $(dirname $0))
-[ $BASH_VERSINFO -lt 4 ] && echo "This script cvt_script requires bash 4.0+!" && exit 4
-[[ -d "$HOME/dev" ]] && HOME_DEV="$HOME/dev" || HOME_DEV="$HOME/devel"
-PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\nHOME=os.environ.get('HOME');y=os.path.join(HOME_DEV,'pypi');t=os.path.join(HOME,'tools')\ndef apl(l,p,x):\n  d2=os.path.join(p,x,x)\n  d1=os.path.join(p,x)\n  if os.path.isdir(d2):\n   l.append(d2)\n  elif os.path.isdir(d1):\n   l.append(d1)\nl=[TDIR]\nfor x in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(y):\n  apl(l,y,x)\n elif TDIR.startswith(t):\n  apl(l,t,x)\nl=l+os.environ['PATH'].split(':')\np=set()\npa=p.add\np=[x for x in l if x and x.startswith(HOME) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|python)
+[ $BASH_VERSINFO -lt 4 ] && echo "This script $0 requires bash 4.0+!" && exit 4
+HOME_DEV="$HOME/devel"
+[[ -x $TDIR/../bin/python ]] && PYTHON=$(readlink -f $TDIR/../bin/python) || [[ -x $TDIR/python ]] && PYTHON="$TDIR/python" || PYTHON="python"
+PYPATH=$(echo -e "import os,sys;\nTDIR='"$TDIR"';HOME_DEV='"$HOME_DEV"'\no=os.path\nHOME=os.environ.get('HOME');t=o.join(HOME,'tools')\nn=o.join(HOME,'pypi') if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME,HOME_DEV, 'pypi')\nd=HOME_DEV if o.basename(HOME_DEV)=='venv_tools' else o.join(HOME_DEV,'venv')\ndef apl(l,p,b):\n if p:\n  p2=o.join(p,b,b)\n  p1=o.join(p,b)\n  if o.isdir(p2):\n   l.append(p2)\n  elif o.isdir(p1):\n   l.append(p1)\nl=[TDIR]\nv=''\nfor x in sys.path:\n if not o.isdir(t) and o.isdir(o.join(x,'tools')):\n  t=o.join(x,'tools')\n if not v and o.basename(x)=='site-packages':\n  v=x\nfor x in os.environ['PATH'].split(':'):\n if x.startswith(d):\n  d=x\n  break\nfor b in ('z0lib','zerobug','odoo_score','clodoo','travis_emulator'):\n if TDIR.startswith(d):\n  apl(l,d,b)\n elif TDIR.startswith(n):\n  apl(l,n,b)\n apl(l,v,b)\n apl(l,t,b)\nl=l+os.environ['PATH'].split(':')\ntdir=o.dirname(TDIR)\np=set()\npa=p.add\np=[x for x in l if x and (x.startswith(HOME) or x.startswith(HOME_DEV) or x.startswith(tdir)) and not (x in p or pa(x))]\nprint(' '.join(p))\n"|$PYTHON)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "PYPATH=$PYPATH"
 for d in $PYPATH /etc; do
   if [[ -e $d/z0librc ]]; then
     . $d/z0librc
-    Z0LIBDIR=$d
-    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    Z0LIBDIR=$(readlink -e $d)
     break
   fi
 done
 if [[ -z "$Z0LIBDIR" ]]; then
-  echo "Library file z0librc not found!"
+  echo "Library file z0librc not found in <$PYPATH>!"
   exit 72
 fi
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "Z0LIBDIR=$Z0LIBDIR"
@@ -47,11 +48,19 @@ TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "TESTDIR=$TESTDIR"
 RUNDIR=$(readlink -e $TESTDIR/..)
 [[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "RUNDIR=$RUNDIR"
+
+DIST_CONF=$(findpkg ".z0tools.conf" "$PYPATH")
+TCONF="$HOME/.z0tools.conf"
+CFG_init "ALL"
+link_cfg_def
+link_cfg $DIST_CONF $TCONF
+[[ $TRAVIS_DEBUG_MODE -ge 8 ]] && echo "DIST_CONF=$DIST_CONF" && echo "TCONF=$TCONF"
+get_pypi_param ALL
 RED="\e[1;31m"
 GREEN="\e[1;32m"
 CLR="\e[0m"
 
-__version__=1.0.2.1
+__version__=1.0.4
 
 
 store_cfg_param_value() {
@@ -64,7 +73,14 @@ store_cfg_param_value() {
     p=${2:12}
     PIPPKGVER[$p]=$3
   fi
-  a_add "$1" "$2" "$3" "$4"
+  # a_add "$1" "$2" "$3" "$4"
+  CFG_set "$2" "$3" "$1" "$4" "$5"
+}
+
+debug_shell() {
+    echo "PS1='ctrl+d to exit> '">/tmp/$$.sh
+    [[ -n "$1" ]] && echo "TODO>$1"
+    eval $SHELL --noprofile --rcfile -s/tmp/$$.sh -s
 }
 
 process_yaml_init() {
@@ -94,11 +110,10 @@ process_yaml_init() {
   [[ -z $PGUSER ]] && export PGUSER=$(get_dbuser)
   python_ver_req=""
   python_ver_ena=""
-  [[ -f $PRJPATH/travis.ini ]] && python_ver_ena=$(cat $PRJPATH/travis.ini|grep PYPI_RUN_PYVER|awk -F= '{print $2}'|grep -Eo "[0-9.]+"|head -n1)
+  [[ -f $PRJPATH/travis.ini ]] && python_ver_ena=$(cat $PRJPATH/travis.ini|grep "^PYPI_RUN_PYVER"|awk -F= '{print $2}'|grep -Eo "[0-9.]+"|head -n1)
   if [ $opt_dbgmnt -ne 0 ]; then
     [[ -d $HOME/devel ]] && \
-      export YML_lisa=$HOME/devel/pypi/lisa/lisa/lisa || \
-      export YML_lisa=$HOME/dev/pypi/lisa/lisa/lisa
+      export YML_lisa=$HOME/devel/pypi/lisa/lisa/lisa
     (($opt_debug)) && export TRAVIS_PDB="true"
   else
     export YML_lisa=lisa
@@ -118,6 +133,7 @@ process_yaml_init() {
     declare YML_CMD_DIS_$i=$(get_cfg_value "" "yaml__cmd_dis__$i")
   done
   FH=$(xuname -f)
+  TRAVIS_VERBOSE=$opt_verbose
 }
 
 process_yaml_unquote() {
@@ -348,10 +364,12 @@ process_yaml_file() {
 process_yaml_initialize() {
   local sts=$STS_SUCCESS
   local i s line lne X
+  opt_verbose=$TRAVIS_VERBOSE
   wlog "\e[${PS_HDR2_COLOR}m===== [Initialize] =====\e[0m"
   if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
-    wlog "\e[${PS_HDR3_COLOR}m------ [[initialize] from .travis.conf] ------\e[0m"
+    wlog "\e[${PS_HDR3_COLOR}m------ [Initialize from .travis.conf] ------\e[0m"
   fi
+  [[ -n $opt_trace && ::travis.conf =~ $opt_trace ]] && debug_shell "::travis.conf"
   line=$(get_cfg_value "" "GBL_EXCLUDE")
   [[ -n "$line" ]] && run_traced "export GBL_EXCLUDE=$line"
   for i in {1..9}; do
@@ -361,9 +379,6 @@ process_yaml_initialize() {
         s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
     fi
   done
-  if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
-    wlog "\e[${PS_HDR3_COLOR}m------ [[initialize.packages] from .travis.conf] ------\e[0m"
-  fi
   X="${PKGNAME}__"
   line=$(get_cfg_value "" "${X}yaml_init_1")
   if [ -n "$line" ]; then
@@ -375,6 +390,7 @@ process_yaml_initialize() {
       fi
     done
   fi
+  [[ -n $opt_tafter && ::travis.conf =~ $opt_tafter ]] && debug_shell
   return $sts
 }
 
@@ -412,22 +428,26 @@ process_yaml_global() {
   if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
     wlog "\e[${PS_HDR3_COLOR}m------ [[env.global] in .travis.yml] ------\e[0m"
   fi
+  [[ -n $opt_trace && ::env.global =~ $opt_trace ]] && debug_shell "::env.global"
   for lne in $YML_global; do
     line="export $(process_yaml_quote_xtl $lne)"
     run_traced "$line"
     s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
   done
+  [[ -n $opt_tafter && ::env.global =~ $opt_tafter ]] && debug_shell
   return $sts
 }
 
 process_yaml_before_install() {
   wlog "\e[${PS_HDR2_COLOR}m===== [Before install] =====\e[0m"
+  [[ -n $opt_trace && ::before_install =~ $opt_trace ]] && debug_shell "::before_install"
   local sts=$STS_SUCCESS
   local i s line lne X CURPYVER
   if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
-    wlog "\e[${PS_HDR3_COLOR}m------ [[addons.packages] in .travis.yml] ------\e[0m"
+    wlog "\e[${PS_HDR3_COLOR}m------ [[addons.apt.packages] in .travis.yml] ------\e[0m"
   fi
   if [ $sts -eq $STS_SUCCESS ]; then
+    [[ -n $opt_trace && ::addons.apt.package =~ $opt_trace ]] && debug_shell "::addons.apt.package"
     CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo [0-9] | head -n1)
     for lne in $YML_packages; do
       if [[ "$lne" == "python-dev" && $CURPYVER == "3" ]]; then
@@ -460,6 +480,7 @@ process_yaml_before_install() {
       s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
       [ $s -ne 0 ] && echo "Internal error! Statement failed! <<<"
     done
+    [[ -n $opt_tafter && ::addons.apt.package =~ $opt_tafter ]] && debug_shell
   fi
   if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
     wlog "\e[${PS_HDR3_COLOR}m------ [[before_install] in .travis.yml] ------\e[0m"
@@ -472,9 +493,6 @@ process_yaml_before_install() {
       [ $s -ne 0 ] && echo "Internal error! Statement failed! <<<"
     done
   fi
-  if [[ $TRAVIS_DEBUG_MODE -ne 0 ]]; then
-    wlog "\e[${PS_HDR3_COLOR}m------ [[env] in .travis.yml] ------\e[0m"
-  fi
   if [ $sts -eq $STS_SUCCESS ]; then
     for lne in $YML_env; do
       line="export $(process_yaml_quote_xtl $lne)"
@@ -482,6 +500,7 @@ process_yaml_before_install() {
       s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
     done
   fi
+  [[ -n $opt_tafter && ::before_install =~ $opt_tafter ]] && debug_shell
   return $sts
 }
 
@@ -544,6 +563,7 @@ process_yaml_run_cmd() {
   else
     local line1
   fi
+  [[ -n $opt_trace && $xcmd =~ $opt_trace ]] && debug_shell "$xcmd"
   c=$xcmd
   if [ "$FH" == "RHEL" ]; then
     if [[ $xcmd =~ which[[:space:]]nodejs ]]; then
@@ -687,7 +707,7 @@ process_yaml_run_cmd() {
     if [ -z "$REPOSNAME" ]; then
       pp=$PKGPATH
     else
-      pp=$($READLINK -e $PRJPATH/../$REPOSNAME/)
+      pp=$(readlink -e $PRJPATH/../$REPOSNAME/)
     fi
     while [ -n "${x[$ix]}" ]; do
       if [[ "${x[$ix]}" =~ cd ]]; then
@@ -741,15 +761,16 @@ process_yaml_run_cmd() {
     [[ $c != $xcmd && ! $xcmd =~ ^# ]] && wlog "\e[${PS_NOP_COLOR}m> $c\e[${PS_TXT_COLOR}m" && ((Z0_STACK=Z0_STACK+2))
     run_traced "$line1$xcmd"
     s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
-    if [[ $xcmd =~ "travis_install_env" ]]; then
-      ((Z0_STACK=Z0_STACK+2))
-      opts=$(inherits_travis_opts "" "V")
-      [[ $TRAVIS == "true" ]] || opts="$opts -f"
-      [ $opt_keepE -eq 0 ] || run_traced "vem create $VENVOPTS $TRAVIS_HOME $opts -p$TRAVIS_PYTHON_VERSION"
-      ((Z0_STACK=Z0_STACK-2))
-    fi
+#    if [[ $xcmd =~ "travis_install_env" ]]; then
+#      ((Z0_STACK=Z0_STACK+2))
+#      opts=$(inherits_travis_opts "" "V")
+#      [[ $TRAVIS == "true" ]] || opts="$opts -f"
+#      [ $opt_keepE -eq 0 ] || run_traced "vem create $VENVOPTS $TRAVIS_HOME $opts -p$TRAVIS_PYTHON_VERSION"
+#      ((Z0_STACK=Z0_STACK-2))
+#    fi
     [[ $c != $xcmd && ! $xcmd =~ ^# ]] && ((Z0_STACK=Z0_STACK-2))
   fi
+  [[ -n $opt_tafter && $xcmd =~ $opt_tafter ]] && debug_shell
   return $sts
 }
 
@@ -770,7 +791,7 @@ process_yaml() {
     [[ ! -f $YML_FILE ]] && YML_FILE=$PRJPATH/$opt_fyaml
     [[ ! -f $YML_FILE ]] && YML_FILE=$TOOLS_PATH/travis.yml
   fi
-  if [ -f $YML_FILE ]; then
+  if [[ -f $YML_FILE ]]; then
     echo -e "\e[0;30;107m$(printf '%-80.80s' ' ')\e[0m"
     wlog "\e[${PS_HDR1_COLOR}m$(printf '%-80.80s' '=== Process YAML file ===')\e[0m"
     export TRAVIS_HOME_BRANCH=$PWD
@@ -791,11 +812,12 @@ process_yaml() {
       fi
       [[ -n "$lne1" || $lne =~ PATH ]] && wlog "\e[${PS_NOP_COLOR}m\$ $lne=$lne1\e[0m"
     done
-    if [ $sts -eq $STS_SUCCESS ]; then
+    if [[ $sts -eq $STS_SUCCESS ]]; then
       process_yaml_initialize
       s=$?; [ ${s-1} -eq 0 -o $sts -ne 0 ] || sts=$s
     fi
-    if [ $sts -eq $STS_SUCCESS ]; then
+    if [[ $sts -eq $STS_SUCCESS ]]; then
+      [[ -n $opt_trace && ::matrix =~ $opt_trace ]] && debug_shell "::matrix"
       [[ -z "$python_ver_req" ]] && python_ver_req=$(python --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
       [[ -z "$opt_pyv" ]] && opt_pyv=$(get_cfg_value "" "PYTHON_MATRIX")
       [[ -z "$opt_pyv" ]] && opt_pyv="(2.7|3.5|3.6|3.7|3.8)"
@@ -811,13 +833,19 @@ process_yaml() {
       for TRAVIS_PYTHON_VERSION in $python_matrix; do
         [[ $sts -eq $STS_SUCCESS ]] || break
         wlog "\e[${PS_HDR1_COLOR}m===== [Build python $TRAVIS_PYTHON_VERSION] =====\e[0m"
-        CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo [0-9] | head -n1)
+        CURPYVER=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo "[0-9]" | head -n1)
+        CURPYVER2=$(echo $TRAVIS_PYTHON_VERSION | grep -Eo "[0-9]\.[0-9]" | head -n1)
         PYTHON=$(which python$TRAVIS_PYTHON_VERSION)
+        [[ -z "$PYTHON" ]] && PYTHON=$(which python$CURPYVER2)
         [[ -z "$PYTHON" ]] && PYTHON=$(which python$CURPYVER)
         PYTHON_VERSION=$($PYTHON --version 2>&1 | grep -Eo "[0-9]+\.[0-9]+")
-        if [[ $PYTHON_VERSION != $TRAVIS_PYTHON_VERSION ]]; then
-          wlog "\e[${PS_HDR1_COLOR}mError: Required version $TRAVIS_PYTHON_VERSION of python is not availale. Replace by $PYTHON_VERSION\e[${PS_TXT_COLOR}m"
-          continue
+        if [[ $($PYTHON --version 2>&1 | grep -Eo "[0-9.]+") != $TRAVIS_PYTHON_VERSION ]]; then
+          if [[ $PYTHON_VERSION != $CURPYVER2 ]]; then
+            wlog "\e[${PS_HDR1_COLOR}mError: Required version $TRAVIS_PYTHON_VERSION of python is not availale. Replace by $PYTHON_VERSION\e[${PS_TXT_COLOR}m"
+            continue
+          fi
+          wlog "\e[${PS_HDR1_COLOR}mWarning: Required version $TRAVIS_PYTHON_VERSION of python is replaced by $PYTHON_VERSION\e[${PS_TXT_COLOR}m"
+          TRAVIS_PYTHON_VERSION=$CURPYVER2
         fi
         alias python=$PYTHON
         export TRAVIS_PYTHON_VERSION
@@ -844,6 +872,7 @@ process_yaml() {
             line1="$lne"
             lne1=$(process_yaml_quote "$lne")
           fi
+          [[ -n $opt_tafter && ::matrix =~ $opt_tafter ]] && debug_shell
           if [[ $lne1 =~ ODOO_REPO=.[A-Za-z]+ && ! $lne1 =~ ODOO_REPO=.$YML_repo. ]]; then
             wlog "\e[${PS_HDR3_COLOR}mMatrix [$lne1] skipped due invalid repo\e[${PS_TXT_COLOR}m"
             continue
@@ -862,12 +891,14 @@ process_yaml() {
             continue
           fi
           wlog "\e[${PS_HDR1_COLOR}m===== [Build job $lne1] =====\e[0m"
+          [[ -n $opt_trace && ::build =~ $opt_trace ]] && debug_shell "::build"
           create_virtual_env
           wlog "\e[${PS_HDR2_COLOR}m----- [System informations] -----\e[0m"
           for p in PATH HOME TRAVIS TRAVIS_BUILD_DIR TRAVIS_BRANCH TRAVIS_HOME TRAVIS_SAVED_HOME HOME_BRANCH PYPI_CACHED SYSTEM_SITE_PACKAGES; do
             X=${!p}
             [[ -n "$X" || $p =~ PATH ]] && wlog "\e[${PS_RUN_COLOR}m\$ $p=$X\e[0m"
           done
+          [[ -n $opt_tafter && ::build =~ $opt_tafter ]] && debug_shell
           process_yaml_global
           if [ $sts -eq $STS_SUCCESS ]; then
             process_yaml_before_install
@@ -947,25 +978,26 @@ travis_status() {
 }
 
 
-OPTOPTS=(h        B         C         c        D           E         F        f         j        k        L          l        M          m       n            O         p        q           r     S            V           v           X           Y             y       Z)
-OPTLONG=(help     debug     no-cache  conf     debug-level no-savenv full     force     ''       keep     lint-level logdir   ''         missing dry-run      org       pytest   quiet       ''    syspkg       version     verbose     translation yaml-file     pyver   zero)
-OPTDEST=(opt_help opt_debug opt_cache opt_conf opt_dlvl    opt_keepE opt_full opt_force opt_dprj opt_keep opt_llvl   opt_flog opt_dbgmnt opt_mis opt_dry_run  opt_org   opt_pyth opt_verbose opt_r  opt_syspkg  opt_version opt_verbose opt_tnl     opt_fyaml     opt_pyv opt_dbgmnt)
-OPTACTI=(1        1         0         "="      "="         0         1        1         1        1        "="        "="      1          1       "1>"         "="       1        0           1     "="          "*>"        "+"         "="         "="           "="     1)
-OPTDEFL=(0        0         1         ""       ""          1         0        0         0        0        ""         ""       0          0       0            "local"   0        -1          0     ""           ""          -1          ""          ".travis.yml" ""      0)
-OPTMETA=("help"   "version" ""        "file"   "number"    ""        ""       ""        "dprj"   ""       "number"   "dir"    ""         ""      "do nothing" "git-org" ""       "verbose"   "res" "false|true" "version"   "verbose"   "0|1"       "file"        "pyver" "")
+OPTOPTS=(h        A           B         C         c        D           E         F        f         j        k        L          l        M          m       n            O         p        q           r     S            T         V           v           X           Y             y       Z)
+OPTLONG=(help     trace-after debug     no-cache  conf     debug-level no-savenv full     force     ''       keep     lint-level logdir   ''         missing dry-run      org       pytest   quiet       ''    syspkg       trace     version     verbose     translation yaml-file     pyver   zero)
+OPTDEST=(opt_help opt_tafter  opt_debug opt_cache opt_conf opt_dlvl    opt_keepE opt_full opt_force opt_dprj opt_keep opt_llvl   opt_flog opt_dbgmnt opt_mis opt_dry_run  opt_org   opt_pyth opt_verbose opt_r  opt_syspkg  opt_trace opt_version opt_verbose opt_tnl     opt_fyaml     opt_pyv opt_dbgmnt)
+OPTACTI=('+'      "="         1         0         "="      "="         0         1        1         1        1        "="        "="      1          1       "1>"         "="       1        0           1     "="          "="       "*>"        "+"         "="         "="           "="     1)
+OPTDEFL=(0        ""          0         1         ""       ""          1         0        0         0        0        ""         ""       0          0       0            "local"   0        0           0     ""           ""        ""          -1          ""          ".travis.yml" ""      0)
+OPTMETA=("help"   "regex"     "version" ""        "file"   "number"    ""        ""       ""        "dprj"   ""       "number"   "dir"    ""         ""      "do nothing" "git-org" ""       "verbose"   "res" "false|true" "regex"   "version"   "verbose"   "0|1"       "file"        "pyver" "")
 OPTHELP=("this help"
+  "set trace after executed yaml statement"
   "debug mode: do not create log"
   "do not use stored PYPI"
   "configuration file (def .travis.conf)"
   "travis_debug_mode: may be 0,1,2,3,8 or 9 (def yaml dependents)"
   "do not save virtual environment into ~/VME/... if does not exist"
   "run final travis with full features"
-  "force yaml to run w/o cmd subst"
-  "execute tests in project dir rather in test dir (or expand macro if parseyaml)"
+  "force to remove recent log (wep-db)"
+  "deprecated: kept just for compatibility"
   "keep DB and virtual environment after tests"
   "lint_check_level: may be minimal,reduced,average,nearby,oca; def value from .travis.yml"
   "log directory (def=$HOME/travis_log)"
-  "use local MQT (deprecated)"
+  "deprecated: kept just for compatibility"
   "show missing line in report coverage"
   "do nothing (dry-run)"
   "git organization, i.e. oca or zeroincombenze"
@@ -973,6 +1005,7 @@ OPTHELP=("this help"
   "silent mode"
   "run restricted mode (deprecated)"
   "use python system packages (def yaml dependents)"
+  "set trace before executing yaml statement"
   "show version"
   "verbose mode"
   "enable translation test (def yaml dependents)"
@@ -995,6 +1028,7 @@ fi
 
 export PYTHONWARNINGS="ignore"
 [[ -z "$action" ]] && action=emulate
+[[ -n "$opt_tafter" || -n "$opt_trace" ]] && opt_debug=1
 VIRTACTS="(force-lint|lint|force-test|test|emulate)"
 opt_virt=1
 if [[ $action =~ $ACTIONS ]]; then
@@ -1005,11 +1039,10 @@ else
   exit $STS_FAILED
 fi
 opts_travis
-CFG_init
 conf_default
-link_cfg $DIST_CONF $TCONF
 [[ $opt_verbose -gt 2 ]] && set -x
 init_travis
+# prepare_env_travis
 
 [[ -n $opt_flog ]] && LOGDIR="$(dirname $opt_flog)" || LOGDIR="$(get_cfg_value "" "LOGDIR")"
 [[ -d $LOGDIR ]] || mkdir $LOGDIR
@@ -1100,10 +1133,10 @@ elif [[ $action =~ (wep_db|wep-db) ]]; then
     [[ $opt_force -ne 0 ]] && md=30 || md=1800
     dt=$(date "+%s")
     for d in $HOME/VENV_*; do
-      if [ "$d" != "$HOME/VENV_*" ]; then
+      if [[ "$d" != "$HOME/VENV_*" ]]; then
         dd=$(stat -c "%Y" $d)
         df=$(($dt - $dd))
-        if [ $df -gt $md ]; then
+        if [[ $df -gt $md ]]; then
           echo "\$ rm -fR $d ($(date -d@$df -u +"%H:%M:%S") old)"
           rm -fR $d
           sfx=$(echo "$d" | grep -Eo "[0-9]+$")
