[RUN] test nightly

diff --git a/lisa/lisa b/lisa/lisa
--- a/lisa/lisa
+++ b/lisa/lisa
@@ -57,7 +57,7 @@ fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
 
-__version__=0.2.36.27
+__version__=0.2.36.28
 
 
 STS_FAILED=1
@@ -165,21 +165,14 @@ conf_default() {
       set_cfg_def "${THIS}_cmdname" "$0" "0"
       set_cfg_def "${THIS}_vfycmd" "$0 -V" "0"
     fi
-    set_cfg_def "apache2_cmdname" "apachectl" "0" "Debian"
+    # set_cfg_def "apache2_cmdname" "apachectl" "0" "Debian"
     set_cfg_def "apache2_LocalRoot" "/var/www/html" "0" "Debian"
-    set_cfg_def "httpd_cmdname" "apachectl" "0" "RHEL"
+    # set_cfg_def "httpd_cmdname" "apachectl" "0" "RHEL"
     set_cfg_def "httpd_LocalRoot" "/var/www/html" "0" "RHEL"
-    # set_cfg_def "postgresql-server_cmdname" "psql" "0" "RHEL"
-    # set_cfg_def "postgresql_cmdname" "psql" "0" "Debian"
     set_cfg_def "mysql-server_cmdname" "mysql" "0"
     set_cfg_def "mariadb-server_cmdname" "mysql" "0" "CentOS7"
     set_cfg_def "mysql_cmdname" "mysql" "0"
     set_cfg_def "mariadb_cmdname" "mysql" "0" "CentOS7"
-    # set_cfg_def "openssh-server_cmdname" "NULL" "0"
-    # set_cfg_def "openssh-client_cmdname" "ssh" "0" "Debian"
-    # set_cfg_def "openssh-clients_cmdname" "ssh" "0" "RHEL"
-    # set_cfg_def "lisa_git_URL" "https://github.com/zeroincombenze/tools.git" "0"
-    # set_cfg_def "lisa_git_LocalUser" "odoo:odoo" "0"
     set_cfg_def "wkhtmltopdf_wget_URL" "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1"
     if [ "$MACHARCH" != "x86_64" ]; then
       set_cfg_def "wkhtmltopdf_wget_xname" "wkhtmltox-0.12.1_linux-trusty-i386.deb" "0" "Ubuntu14"
@@ -200,31 +193,26 @@ conf_default() {
     set_cfg_def "pandoc_git_LocalRoot" "/opt/pandoc" "0"
     set_cfg_def "pandoc_SubPkgList" "." "0"
     # Service names
-    set_cfg_def "vsftpd_svcname" "vsftpd" "0"
+    # set_cfg_def "vsftpd_svcname" "vsftpd" "0"
     set_cfg_def "iptables_svcname" "iptables" "0"
-    set_cfg_def "apache2_svcname" "apache2" "0" "Debian"
-    set_cfg_def "httpd_svcname" "httpd" "0" "RHEL"
+    # set_cfg_def "apache2_svcname" "apache2" "0" "Debian"
+    # set_cfg_def "httpd_svcname" "httpd" "0" "RHEL"
     set_cfg_def "mysql_svcname" "mysql" "0" "Debian"
     set_cfg_def "mariadb_svcname" "mariadb" "0" "CentOS7"
     set_cfg_def "mariadb-server_svcname" "mariadb" "0" "CentOS7"
     set_cfg_def "mysql_svcname" "mysqld" "0" "CentOS6"
-    # set_cfg_def "postgresql_svcname" "postgresql" "0"
-    # set_cfg_def "postgresql-server_svcname" "postgresql" "0"
-    # set_cfg_def "openssh-server_svcname" "ssh" "0" "Debian"
-    # set_cfg_def "openssh-server_svcname" "sshd" "0" "RHEL"
     set_cfg_def "odoo_svcname" "odoo-server" "0"
     # TCP & UDP Ports
-    set_cfg_def "TCP_httpd" "80 443" "0" "RHEL"
-    set_cfg_def "TCP_apache2" "80 443" "0" "Debian"
-    set_cfg_def "TCP_vsftpd" "21" "0"
-    # set_cfg_def "TCP_openssh-server" "22" "0"
+    # set_cfg_def "TCP_httpd" "80 443" "0" "RHEL"
+    # set_cfg_def "TCP_apache2" "80 443" "0" "Debian"
+    # set_cfg_def "TCP_vsftpd" "21" "0"
     set_cfg_def "TCP_odoo" "8069" "0"
     # Configuration files
     p="/etc/httpd /etc/apache2; conf"
-    set_cfg_def "apache2_FINDCFN" "$p" "0" "Debian"
-    set_cfg_def "apache2_confn" "apache2.conf" "0" "Debian"
-    set_cfg_def "httpd_FINDCFN" "$p" "0" "RHEL"
-    set_cfg_def "httpd_confn" "httpd.conf" "0" "RHEL"
+    # set_cfg_def "apache2_FINDCFN" "$p" "0" "Debian"
+    # set_cfg_def "apache2_confn" "apache2.conf" "0" "Debian"
+    # set_cfg_def "httpd_FINDCFN" "$p" "0" "RHEL"
+    # set_cfg_def "httpd_confn" "httpd.conf" "0" "RHEL"
     p="/var/lib /etc;postgresql pgsql;9.4 9.3 9.2 9.1 9.0 8.4;data main"
     set_cfg_def "postgresql_FINDCFN" "$p" "0" "Debian"
     set_cfg_def "postgresql_confn" "pg_hba.conf" "0" "Debian"
@@ -239,7 +227,7 @@ conf_default() {
 store_cfg_param_value() {
 #store_cfg_param_value(tid key value [-d|-f|] [-D|1] [section])
     local p tid=$1
-    if [[ " xyz " =~ [[:space:]]$2[[:space:]] ]]; then
+    if [[ " xyz TCP " =~ [[:space:]]$2[[:space:]] ]]; then
       p="${2}_$6"
     elif [[ " BOP BOP_GRF_ADD binPkgList build_fileignore build_PkgList build_PKGPATH\
  build_with_z0libr build_with_odoorc cmdname confn etcPkgList FINDCFN git_LocalDir\
@@ -303,7 +291,7 @@ clr_conf_pkg() {
 set_from_conf_pkg() {
 # set_from_conf_pkg (pkgname [confn] [opts]])
     [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "set_from_conf_pkg($1 \"$2\" $3)">>~/$THIS.his
-    local FCONF FCONFDEF SAMPLE sdir
+    local pkg pkgname FCONF FCONFDEF SAMPLE sdir
     if [ $test_mode -gt 0 ]; then
       sdir="$TESTDIR $TDIR"
     elif [ -n "$2" ]; then
@@ -311,7 +299,7 @@ set_from_conf_pkg() {
     else
       sdir=". $TDIR /etc/lisa /etc"
     fi
-    local pkgname=$(get_realname $1)
+    pkgname=$(get_realname $1)
     if [ -n "$2" ]; then
       if [ -n "$opt_conf" -a -f "$opt_conf" ]; then
         FCONF=$opt_conf
@@ -353,7 +341,9 @@ set_from_conf_pkg() {
       PKG_CONF=$(findpkg "lisa.lish" "$sdir")
       SAMPLE=$(findpkg "lisa.lish.sample" "$sdir")
     fi
-    get_conf_pkg "$PKG_CONF" "$SAMPLE" "" $3
+    pkg=$(echo "$1"|grep -Eo '[^!<=>]*'|head -n1)
+    get_conf_pkg "$PKG_CONF" "$SAMPLE" "$pkg" $3
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return #set_from_conf_pkg">>~/$THIS.his
 }
 
 get_prm_value() {
@@ -796,6 +786,7 @@ get_odoo_full_ver() {
 get_pkg_ver_inq() {
 # get_pkg_ver_inq(pkgname [OPTS])
 # return: ->  pkgversion
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "get_pkg_ver_inq($1 $2)">>~/$THIS.his
     local pkgname=$1
     local X="VER__${1//-/_}"
     local cmdname p pkgversion= vfycmd x
@@ -828,13 +819,14 @@ get_pkg_ver_inq() {
         declare $X="$pkgversion"
       fi
     fi
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "$pkgversion=get_pkg_ver_inq($1 $2)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "  $pkgversion=get_pkg_ver_inq($1 $2)">>~/$THIS.his
     echo $pkgversion
 }
 
 get_pkg_ver_pip() {
 # get_pkg_ver_pip(pkgname [OPTS])
 # return: pkgversion
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "get_pkg_ver_pip($1 $2)">>~/$THIS.his
     local pkgname="$1"
     local stscmd=pip
     local pkgversion=
@@ -858,13 +850,14 @@ get_pkg_ver_pip() {
         declare $X="$pkgversion"
       fi
     fi
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "$pkgversion=get_pkg_ver_pip($1 $2)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "  $pkgversion=get_pkg_ver_pip($1 $2)">>~/$THIS.his
     echo $pkgversion
 }
 
 get_pkg_ver_rpm() {
 # get_pkg_ver_rpm(pkgname [OPTS])
 # return: pkgversion
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "get_pkg_ver_rpm($1 $2)">>~/$THIS.his
     local pkgname="$1"
     local stscmd=$(get_prm_value "${1}_stscmd")
     local pkgversion=
@@ -888,13 +881,14 @@ get_pkg_ver_rpm() {
         declare $X="$pkgversion"
       fi
     fi
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "$pkgversion=get_pkg_ver_rpm($1 $2)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "  $pkgversion=get_pkg_ver_rpm($1 $2)">>~/$THIS.his
     echo $pkgversion
 }
 
 get_pkg_ver_dpkg() {
 # get_pkg_ver_dpkg(pkgname [OPTS])
 # return: pkgversion
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "get_pkg_ver_dpkg($1 $2)">>~/$THIS.his
     local pkgname="$1"
     local stscmd=$(get_prm_value "${1}_stscmd")
     local pkgversion=
@@ -922,7 +916,7 @@ get_pkg_ver_dpkg() {
         declare $X="$pkgversion"
       fi
     fi
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "$pkgversion=get_pkg_ver_dkpg($1 $2)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "  $pkgversion=get_pkg_ver_dkpg($1 $2)">>~/$THIS.his
     echo $pkgversion
 }
 
@@ -930,6 +924,7 @@ get_pkg_ver_dpkg() {
 get_pkg_ver_git() {
 # get_pkg_ver_git(pkgname [OPTS] [param] [SPECIMEN])
 # return: pkgversion
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "get_pkg_ver_git($1 $2)">>~/$THIS.his
     local pkgname="$1"
     local pkgversion=
     local x=
@@ -963,14 +958,14 @@ get_pkg_ver_git() {
         fi
       # fi
     fi
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "$pkgversion=get_pkg_ver_git($1 $2 $3 $4 $5)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  $pkgversion=get_pkg_ver_git($1 $2 $3 $4 $5)">>~/$THIS.his
     echo $pkgversion
 }
 
 get_pkg_ver() {
 # get_pkg_ver(pkgname [OPTS] [param] [SPECIMEN])
 # return: pkgversion
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " "  "get_pkg_ver($1 $2 $3 $4 $5)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "get_pkg_ver($1 $2 $3 $4 $5)">>~/$THIS.his
     local pkgname=$1
     local cmd pkgversion stscmd
     local ij
@@ -1006,7 +1001,7 @@ get_pkg_ver() {
         fi
       fi
     fi
-    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "$pkgversion=get_pkg_ver($1 $2)">>~/$THIS.his
+    [[ $2 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  $pkgversion=get_pkg_ver($1 $2)">>~/$THIS.his
     echo $pkgversion
 }
 
@@ -1584,6 +1579,7 @@ create_pkglist() {
       rm -f ./tmp.log
       popd $PKGPATH > /dev/null
     fi
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " ">>> PKGLIST=$PKGLIST $BINLIST $ETCLIST $Z0LIB $OELIB">>~/$THIS.his
     echo "$PKGLIST $BINLIST $ETCLIST $Z0LIB $OELIB"
 }
 
@@ -1776,7 +1772,7 @@ satisfy_request() {
     fi
     [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  REQ=$ReqPkgList">>~/$THIS.his
     if [ -n "$ReqPkgList" -a "$1" != "whatis" -a "$1" != "version" ]; then
-      ((prdstk_level++))
+      [ $(is_virtualname $2) ] || ((prdstk_level++))
       if [[ $3 =~ b ]]; then local x="-qb"; else local x="-q"; fi
       for p in $ReqPkgList; do
         realname=$(get_realname $p $1 $3)
@@ -1789,7 +1785,7 @@ satisfy_request() {
           [ $sts -eq $STS_SUCCESS ] && [ $s -ne $STS_SUCCESS ] && sts=$s
         fi
       done
-      ((prdstk_level--))
+      [ $(is_virtualname $2) ] || ((prdstk_level--))
     fi
     [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #satisfy_request">>~/$THIS.his
     return $sts
@@ -1807,6 +1803,7 @@ do_action_subpkg() {
       :
     else
       local iter=$(get_iter $3)
+      [[ $4 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " ">>> iter=$iter">>~/$THIS.his
       local sts=$STS_SUCCESS
       if [ "$3" != "$iter" ]; then
         for p in $iter; do
@@ -1843,18 +1840,18 @@ do_act_all_deppkgs() {
 # do_act_all_deppkgs(pfx action pkgname OPTS [param] [SPECIMEN])
     [[ $4 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "do_act_all_deppkgs($1 $2 $3 $4)">>~/$THIS.his
     local sts=$STS_SUCCESS
-    local s
+    local p s
     local BOPlist="$(get_prm_value ${3}_BOP list)"
     if [ -n "$BOPlist" -a $prdstk_level -lt $opt_depth ]; then
-      ((prdstk_level++))
-      local p
+      [ $(is_virtualname $3) ] || ((prdstk_level++))
+      [[ $4 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " ">>> BOPlist=$BOPlist">>~/$THIS.his
       for p in $BOPlist; do
         do_action_subpkg "$1" $2 $p $4 $5 "$6"
         s=$?
         [ $sts -eq 127 ] && sts=$s
         [ $sts -eq $STS_SUCCESS ] && [ $s -ne $STS_SUCCESS ] && sts=$s
       done
-      ((prdstk_level--))
+      [ $(is_virtualname $3) ] || ((prdstk_level--))
     fi
     [[ $4 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #do_act_all_deppkgs">>~/$THIS.his
     return $sts
@@ -2243,6 +2240,7 @@ do_dry_install_by_git() {
         fi
       fi
     fi
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return #do_dry_install_by_git">>~/$THIS.his
     return $sts
 }
 
@@ -2258,6 +2256,7 @@ do_dry_update_package() {
     fi
     run_traced "$cmd"
     local sts=$?
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #do_dry_update_package">>~/$THIS.his
     return $sts
 }
 
@@ -2311,6 +2310,7 @@ do_whatis_ports() {
     local lm X x=$((prdstk_level*2+1))
     [ $x -eq 0 ]||eval printf -v lm '%.s-' {1..$x}
     X="$(get_prm_value TCP_$2)"
+    X=${X//,/ }
     if [ -n "$X" ]; then
       for port in $X; do
         test_msg "$lm TCP port $port"
@@ -2330,6 +2330,7 @@ post_install_ports() {
 # post_install_ports(action pkgname OPTS)
     [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "post_install_ports($1 $2 $3)">>~/$THIS.his
     local X="$(get_prm_value TCP_$2)"
+    X=${X//,/ }
     if [ -n "$X" ]; then
       if [ "$1" == "install" -o "$1" == "update" -o "$1" == "config" ]; then
         for port in $X; do
@@ -2368,6 +2369,7 @@ post_update_ports() {
 # post_update_ports(action pkgname OPTS)
     if [[ $3 =~ b ]]; then printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "post_update_ports($1 $2 $3)">>~/$THIS.his; fi #debug
     local X="$(get_prm_value TCP_$2)"
+    X=${X//,/ }
     if [ -n "$X" ]; then
       for port in $X; do
         enable_port $port tcp $3
@@ -2387,6 +2389,7 @@ post_remove_ports() {
 # post_remove_ports(action pkgname OPTS)
     if [[ $3 =~ b ]]; then printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "post_remove_ports($1 $2 $3)">>~/$THIS.his; fi #debug
     local X="$(get_prm_value TCP_$2)"
+    X=${X//,/ }
     if [ -n "$X" ]; then
       for port in $X; do
         disable_port $port tcp $3
@@ -2946,6 +2949,7 @@ do_local_function() {
             act="update"
             DETECTED_UPD="$DETECTED_UPD $4"
           else
+            [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($STS_FAILED) #do_local_function">>~/$THIS.his
             return $STS_FAILED
           fi
         fi
@@ -2958,6 +2962,7 @@ do_local_function() {
           act="install"
           DETECTED_INS="$DETECTED_INS $4"
         else
+          [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($STS_FAILED) #do_local_function">>~/$THIS.his
           return $STS_FAILED
         fi
       elif [ "$3" == "remove" -a $sts -ne $STS_SUCCESS ]; then
@@ -2966,6 +2971,7 @@ do_local_function() {
           ij=J
           DETECTED_NO="$DETECTED_NO $4"
         else
+          [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($STS_FAILED) #do_local_function">>~/$THIS.his
           return $STS_FAILED
         fi
       elif [ "$3" == "remove" -a $prdstk_level -ge $opt_depth ]; then
@@ -3008,6 +3014,7 @@ do_local_function() {
                 [ $sts -eq $STS_SUCCESS ] && [ $s -ne $STS_SUCCESS ] && sts=$s
               fi
             fi
+            [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #do_local_function">>~/$THIS.his
             return $sts
           fi
         done
@@ -3021,6 +3028,7 @@ do_local_function() {
       [ $sts -eq 127 ] && sts=$s
       [ $sts -eq $STS_SUCCESS ] && [ $s -ne $STS_SUCCESS ] && sts=$s
     fi
+    [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #do_local_function">>~/$THIS.his
     return $sts
 }
 
@@ -3036,15 +3044,17 @@ do_local_function_BOP() {
     s=$?
     [ $sts -eq 127 ] && sts=$s
     [ $sts -eq $STS_SUCCESS ] && [ $s -ne $STS_SUCCESS ] && sts=$s
-    local BOPlist="$(get_prm_value ${4}_BOP list)"
-    if [ -n "$BOPlist" ] && [ $sts -eq $STS_SUCCESS -o $sts -eq 127 ]; then
-      if [ $prdstk_level -lt $opt_depth ]; then
+    if [ $sts -eq $STS_SUCCESS -o $sts -eq 127 ]; then
+      local BOPlist="$(get_prm_value ${4}_BOP list)"
+      [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " ">>> BOPlist=$BOPlist [ $prdstk_level -lt $opt_depth ]">>~/$THIS.his
+      if [ -n "$BOPlist" ] && [ $prdstk_level -lt $opt_depth ]; then
         local opts=${5//I/}
         opts=${opts//J/}
         do_act_all_deppkgs "$1" $3 $4 $opts $6 "$7"
         sts=$?
       fi
     fi
+    [[ $5 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #do_local_function_BOP">>~/$THIS.his
     return $sts
 }
 
@@ -3083,6 +3093,7 @@ do_iter_prod() {
          break
        fi
     done
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #do_iter_prod">>~/$THIS.his
     return $sts
 }
 
@@ -3163,6 +3174,7 @@ please() {
         eval $BOPcmd $act $3$ij $4 $5
       fi
     fi
+    [[ $3 =~ b ]] && printf "%${prdstk_level}.${prdstk_level}s %s\n" " " "  return($sts) #please">>~/$THIS.his
     return $sts
 }
 
@@ -3174,7 +3186,7 @@ OPTACTI=(1        1       "="      "*"     "="       "="     "="       1       "
 OPTDEFL=(1        0       ""       ""      ""        ""      ""        0       ""       ""       ""     ""       ""        ""         0        0        0           ""      0         ""         -1          ""        0         ""      ""          -1           0       0)
 OPTMETA=("help"   "dbg"   "file"   "dev"   "number"  "disto" "0-4,0-4" "win"   "host"   "pkg(s)" "file" "pkg(s)" "logfile" "iso3166"  "multi"  ""       "noop"      "disto" "pip"     "password" "quiet"     "modules" "teste"   "file"  "version"   "verbose"   "yes"   "first")
 OPTHELP=("this help, type '$THIS help' for furthermore info"\
- "undocumented"\
+ "trace to build configuration"\
  "configuration file (def /etc/lisa/lisa.conf)"\
  "add development package(s)"\
  "max depth level"\
