[FIX] lisa can install odoo 10.0

diff --git a/lisa/lisa_bld_ods b/lisa/lisa_bld_ods
--- a/lisa/lisa_bld_ods
+++ b/lisa/lisa_bld_ods
@@ -4,23 +4,25 @@
 # Tool for internal use
 #
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
-# (C) 2015-2016 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
+# (C) 2015-2017 by SHS-AV s.r.l. - http://www.shs-av.com - info@shs-av.com
 # This free software is released under GNU Affero GPL3
-
-if [ -f z0librc ]; then
-  . ./z0librc
-elif [ -f ~/z0librc ]; then
-  . ~/z0librc
-elif [ -f /etc/z0librc ]; then
-  . /etc/z0librc
-else
-  echo "Libreria z0librc non trovata!"
-  exit 1
+THIS=$(basename $0)
+TDIR=$(readlink -f $(dirname $0))
+for x in "$TDIR" "$TDIR/.." "." ".." "~" "/etc"; do
+  if [ -e $x/z0librc ]; then
+    . $x/z0librc
+    Z0LIBDIR=$x
+    Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
+  fi
+done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
 fi
 
-__version__="0.2.3"
-THIS=$(basename $0)
-TDIR=$(echo $(readlink -f $(dirname $0)))
+__version__="0.2.4"
+
 
 get_arch () {
     if [ "$1" == "CentOS7" -o "$1" == "CentOS" -o "$1" == "RHEL" ]; then
@@ -50,7 +52,7 @@ get_arch () {
 OPTOPTS=(h        C       E        I         L        m        N        n            O         P       T        t        U        V           v)
 OPTDEST=(opt_help opt_cfg opt_osf  opt_id    opt_flog opt_mult opt_name opt_dry_run  odoo_ver  opt_pid opt_test opt_tmpl opt_user opt_version opt_verbose)
 OPTACTI=(1        "=>"    "=>"     "=>"      "=>"     1        "=>"     1            "=>"      "=>"    "*>"     "=>"     "=>"     "*>"        1)
-OPTDEFL=(1        ""      ""       "odoo"    ""       0        ""       0            "9"        ""     ""       ""       "odoo"   ""          0)
+OPTDEFL=(1        ""      ""       "odoo"    ""       0        ""       0            "10"        ""     ""       ""       "odoo"   ""          0)
 OPTMETA=("help"   "file"  "linux"  "id-name" "file"   "mult"   "name"   "do nothing" "version" "file"  "test"   "file"   "user"   "version"   "verbose")
 OPTHELP=("this help"\
  "set odoo configuration file (default search in /etc/{id_name}/{id_name}-server).conf"\
@@ -60,7 +62,7 @@ OPTHELP=("this help"\
  "multiple version environment (append version to filenames)"\
  "set odoo service name (default {id_name}-server)"\
  "do nothing (dry-run)"\
- "select odoo version: may be 7, 8 or 9"\
+ "select odoo version: may be 7, 8, 9 or 10"\
  "set odoo PID filename (default /var/run/{id_name}/{id_name}-server).pid"\
  "created test script does nothing (used for debug)"\
  "use template (def /etc/product/odoo-server_{linux_dist})"\
@@ -76,41 +78,80 @@ if [ "$opt_version" ]; then
 fi
 if [ $opt_help -gt 0 ]; then
   print_help "Build Odoo daemon script (default name is odoo-server)"\
-  "(C) 2015-2016 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Odoo\nAuthor: antoniomaria.vigliotti@gmail.com"
+  "(C) 2015-2017 by zeroincombenze(R)\nhttp://wiki.zeroincombenze.org/en/Odoo\nAuthor: antoniomaria.vigliotti@gmail.com"
   exit 0
 fi
+if [[ " 10 9 8 7 " =~ [[:space:]]$odoo_ver[[:space:]] ]]; then
+  odoo_fver="$odoo_ver.0"
+elif [[ " 10.0 9.0 8.0 7.0 " =~ [[:space:]]$odoo_ver[[:space:]] ]]; then
+  odoo_fver="$odoo_ver"
+  odoo_ver=$(echo $odoo_fver|grep -Eo [0-9]*|head -n1)
+elif [[ " v10 v9 v8 v7 " =~ [[:space:]]$odoo_ver[[:space:]] ]]; then
+  odoo_fver=$(echo $odoo_fver|grep -Eo [0-9]*|head -n1).0
+  odoo_ver=$(echo $odoo_fver|grep -Eo [0-9]*|head -n1)
+else
+  echo "Invalid Odoo version"
+  exit 1
+fi
 if [ -z "$opt_name" ]; then
-  if [ $opt_mult -gt 0 ]; then
-    opt_name=${opt_id}${odoo_ver}-server
+  if [ "$odoo_ver" == "10" ]; then
+    if [ $opt_mult -gt 0 ]; then
+      opt_name=${opt_id}${odoo_ver}
+    else
+      opt_name=${opt_id}
+    fi
   else
-    opt_name=${opt_id}-server
+    if [ $opt_mult -gt 0 ]; then
+      opt_name=${opt_id}${odoo_ver}-server
+    else
+      opt_name=${opt_id}-server
+    fi
   fi
 fi
-if [ "$odoo_ver" == "7" -o "$odoo_ver" == "8" -o "$odoo_ver" == "9" ]; then
-  odoo_fver="$odoo_ver.0"
-else
-  odoo_fver="$odoo_ver"
-  odoo_ver=$(if $(echo "/$odoo_ver/"|grep "/v9/\|9.0/">/dev/null); then echo "9"; elif $(echo "/$odoo_ver/"|grep "/v8/\|8.0/">/dev/null); then echo "8"; else echo "7"; fi)
-fi
+
 if [ -z "$opt_pid" ]; then
-  if [ $opt_mult -gt 0 ]; then
-    opt_pid=/var/run/${opt_id}/${opt_id}${odoo_ver}-server.pid
+  if [ "$odoo_ver" == "10" ]; then
+    if [ $opt_mult -gt 0 ]; then
+      opt_pid=/var/run/${opt_id}/${opt_id}${odoo_ver}.pid
+    else
+      opt_pid=/var/run/${opt_id}/${opt_name}.pid
+    fi
   else
-    opt_pid=/var/run/${opt_id}/${opt_name}.pid
+    if [ $opt_mult -gt 0 ]; then
+      opt_pid=/var/run/${opt_id}/${opt_id}${odoo_ver}-server.pid
+    else
+      opt_pid=/var/run/${opt_id}/${opt_name}.pid
+    fi
   fi
 fi
 if [ -z "$opt_flog" ]; then
-  if [ $opt_mult -gt 0 ]; then
-    opt_flog=/var/log/${opt_id}/${opt_id}${odoo_ver}-server.log
+  if [ "$odoo_ver" == "10" ]; then
+    if [ $opt_mult -gt 0 ]; then
+      opt_flog=/var/log/${opt_id}/${opt_id}${odoo_ver}.log
+    else
+      opt_flog=/var/log/${opt_id}/${opt_name}.log
+    fi
   else
-    opt_flog=/var/log/${opt_id}/${opt_name}.log
+    if [ $opt_mult -gt 0 ]; then
+      opt_flog=/var/log/${opt_id}/${opt_id}${odoo_ver}-server.log
+    else
+      opt_flog=/var/log/${opt_id}/${opt_name}.log
+    fi
   fi
 fi
 if [ -z "$opt_cfg" ]; then
-  if [ $opt_mult -gt 0 ]; then
-    opt_cfg=/etc/${opt_id}/${opt_id}${odoo_ver}-server.conf
+  if [ "$odoo_ver" == "10" ]; then
+    if [ $opt_mult -gt 0 ]; then
+      opt_cfg=/etc/${opt_id}/${opt_id}${odoo_ver}.conf
+    else
+      opt_cfg=/etc/${opt_id}/${opt_name}.conf
+    fi
   else
-    opt_cfg=/etc/${opt_id}/${opt_name}.conf
+    if [ $opt_mult -gt 0 ]; then
+      opt_cfg=/etc/${opt_id}/${opt_id}${odoo_ver}-server.conf
+    else
+      opt_cfg=/etc/${opt_id}/${opt_name}.conf
+    fi
   fi
 fi
 opt_cfg2="$(dirname $opt_cfg)"
@@ -154,7 +195,7 @@ echo "- pidfile is $opt_pid"
 echo "- def.conf.file is $opt_cfg"
 echo "- alt.conf.file is $opt_cfg2"
 src_template=""
-for d in $TDIR . /etc/product; do
+for d in $TDIR . /etc/lisa /etc/product; do
   for p in $FH .;do
     if [ "$p" == "." ]; then
       n=$d/odoo-server
diff --git a/lisa/tests/all_tests b/lisa/tests/all_tests
--- a/lisa/tests/all_tests
+++ b/lisa/tests/all_tests
@@ -4,35 +4,48 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $TDIR/../zerobug $TDIR/../../zerobug  . .. $HOME/dev")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
-
-__version__=0.2.36.8
+__version__=0.2.36.10
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log $@
+parseoptest -l$TESTDIR/test_lisa.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-# temporary
-cp -v $RUNDIR/*.lish $TESTDIR/
-cp -v $RUNDIR/*.sample $TESTDIR/
-# end temp
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
 UT1_LIST=""
 UT_LIST="__version_V_${__version__}$RUNDIR/lisa"
 UT_LIST="$UT_LIST lisa_test_01 lisa_test_02 lisa_test_03 lisa_test_04 lisa_test_05 lisa_test_06 lisa_test_07 lisa_test_08"
-Z0BUG_main_file "" "$UT_LIST"
-exit $?
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/lisa/tests/lisa_test_04 b/lisa/tests/lisa_test_04
--- a/lisa/tests/lisa_test_04
+++ b/lisa/tests/lisa_test_04
@@ -5,25 +5,32 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $TDIR/../zerobug $TDIR/../../zerobug  . .. $HOME/dev")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
-
-__version__=0.2.1.21
+__version__=0.2.1.22
 
 test_run () {
 # test_run(msg,package,disto,cmd)
+    TPRODUCT="$RUNDIR/lisa -T"
     local msg="$1"
     local Package="$2"
     local Disto="$3"
@@ -202,18 +209,32 @@ for Package in apache2 httpd python; do
 done
 }
 
+Z0BUG_setup() {
+    Real_FH=$(xuname "-f")
+    x=$(xuname "-v")
+    v=$(echo $x|awk -F. '{print $1}')
+    Real_DISTO=$(xuname "-d")$v
+}
+
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log $@
+parseoptest -l$TESTDIR/test_lisa.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-TPRODUCT="$RUNDIR/lisa -T"
-Real_FH=$(xuname "-f")
-x=$(xuname "-v")
-v=$(echo $x|awk -F. '{print $1}')
-Real_DISTO=$(xuname "-d")$v
-
-Z0BUG_main_file "" ""
-exit $?
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
+UT1_LIST=""
+UT_LIST=""
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/lisa/tests/lisa_test_05 b/lisa/tests/lisa_test_05
--- a/lisa/tests/lisa_test_05
+++ b/lisa/tests/lisa_test_05
@@ -5,24 +5,32 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $TDIR/../zerobug $TDIR/../../zerobug  . .. $HOME/dev")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
-__version__=0.2.1.19
+__version__=0.2.1.20
 
 test_run () {
 # test_run(msg,package,disto,cmd,opt_d)
+    TPRODUCT="$RUNDIR/lisa -T"
     local msg="$1"
     local Package="$2"
     local Disto="$3"
@@ -119,6 +127,7 @@ if [ ${opt_dry_run:-0} -eq 0 ]; then
 > cp $RUNDIR/lisa /usr/bin
 > cp $RUNDIR/lisa.man /usr/bin
 > cp $RUNDIR/lisa_bld_ods /usr/bin
+> cp $RUNDIR/*.lish /etc/lisa
 > chmod +x /usr/bin/lisa*
 EOF
   cat <<EOF >$TESTDIR/res/lisa__Debian.05.test
@@ -128,9 +137,10 @@ EOF
 > cp $RUNDIR/lisa /usr/bin
 > cp $RUNDIR/lisa.man /usr/bin
 > cp $RUNDIR/lisa_bld_ods /usr/bin
+> cp $RUNDIR/*.lish /etc/lisa
 > chmod +x /usr/bin/lisa*
 EOF
-  for f in lisa.conf odoo-server_Debian odoo-server_RHEL odoo-server; do
+  for f in lisa.conf lisa.conf.sample odoo-server_Debian odoo-server_RHEL odoo-server; do
     if [ -f $RUNDIR/$f ]; then
       echo "> cp $RUNDIR/$f /etc/lisa">>$TESTDIR/res/lisa__RHEL.05.test
       echo "> cp $RUNDIR/$f /etc/lisa">>$TESTDIR/res/lisa__Debian.05.test
@@ -425,20 +435,33 @@ for Package in python; do
 done
 }
 
+Z0BUG_setup() {
+    if [ -f /tmp/wkhtml*  ]; then
+      echo "Test not executable!"
+      echo "Please, remove wkhtmltopdf file from /tmp"
+      exit 1
+    fi
+}
+
+
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log $@
+parseoptest -l$TESTDIR/test_lisa.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-if [ -f /tmp/wkhtml*  ]; then
-  echo "Test not executable!"
-  echo "Please, remove wkhtmltopdf file from /tmp"
-  exit 1
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
 fi
-
-TPRODUCT="$RUNDIR/lisa -T"
-
-Z0BUG_main_file "" ""
-exit $?
+UT1_LIST=""
+UT_LIST=""
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
diff --git a/lisa/tests/lisa_test_08 b/lisa/tests/lisa_test_08
--- a/lisa/tests/lisa_test_08
+++ b/lisa/tests/lisa_test_08
@@ -5,26 +5,33 @@
 #
 THIS=$(basename $0)
 TDIR=$(readlink -f $(dirname $0))
-for x in "$TDIR" "." ".." "~" "/etc"; do
+for x in $TDIR $TDIR/.. $TDIR/../z0lib $TDIR/../../z0lib . .. /etc; do
   if [ -e $x/z0librc ]; then
     . $x/z0librc
     Z0LIBDIR=$x
     Z0LIBDIR=$(readlink -e $Z0LIBDIR)
+    break
   fi
 done
+if [ -z "$Z0LIBDIR" ]; then
+  echo "Library file z0librc not found!"
+  exit 2
+fi
 TESTDIR=$(findpkg "" "$TDIR . .." "tests")
 RUNDIR=$(readlink -e $TESTDIR/..)
-TRAVISDIR=$(findpkg "" "$TDIR . .. $HOME/dev" "_travis")
-Z0TLIBDIR=$(findpkg "z0testrc" "$TDIR . .. $HOME/dev")
+Z0TLIBDIR=$(findpkg z0testrc "$TDIR $TDIR/.. $TDIR/../zerobug $TDIR/../../zerobug  . .. $HOME/dev")
+if [ -z "$Z0TLIBDIR" ]; then
+  echo "Library file z0testrc not found!"
+  exit 2
+fi
 . $Z0TLIBDIR
 Z0TLIBDIR=$(dirname $Z0TLIBDIR)
-
-
-__version__=0.2.1.19
+__version__=0.2.1.20
 
 test_run () {
 # test_run(msg,package,disto,cmd)
     # set -x #debug
+    TPRODUCT="$RUNDIR/lisa -T"
     local msg="$1"
     local Package=$(echo "$2"|grep -Eo '[^!<=>]*'|head -n1)
     local Disto="$3"
@@ -302,6 +309,10 @@ if [ "${HOSTNAME:0:3}" == "shs" ]; then
 > systemctl start postgresql
 > chkconfig postgresql on
 # yum -y install php
+> yum -y install python-pip
+#
+> yum -y install python-wheel
+> pip install wheel
 # yum -y install python
 EOF
   test_run "install $Package" "$Package" "$Disto" "install"
@@ -309,26 +320,26 @@ EOF
   Package=odoo
   for ver in 7.0 8.0 9.0 10.0; do
     opt_e=
-    if [ "$ver" == "10.0" ]; then
-      echo "odoo should be installed by git">$TESTDIR/res/odoo__$Disto.08.test
-    else
-      echo "odoo: $ver">$TESTDIR/res/odoo__$Disto.08.test
-    fi
+    # if [ "$ver" == "10.0" ]; then
+    #   echo "odoo should be installed by git">$TESTDIR/res/odoo__$Disto.08.test
+    # else
+    echo "odoo: $ver">$TESTDIR/res/odoo__$Disto.08.test
+    # fi
     test_run "version $Package==$ver" "$Package==$ver" "$Disto" "version"
   done
   echo "odoo: 8.0">$TESTDIR/res/odoo__$Disto.08.test
   test_run "version $Package<9.0" "$Package<9.0" "$Disto" "version"
-  echo "odoo: 9.0">$TESTDIR/res/odoo__$Disto.08.test
+  echo "odoo: 10.0">$TESTDIR/res/odoo__$Disto.08.test
   test_run "version $Package>7.0" "$Package>7.0" "$Disto" "version"
   echo "odoo: 8.0">$TESTDIR/res/odoo__$Disto.08.test
   test_run "version $Package<=8.0" "$Package<=8.0" "$Disto" "version"
-  echo "odoo: 9.0">$TESTDIR/res/odoo__$Disto.08.test
+  echo "odoo: 10.0">$TESTDIR/res/odoo__$Disto.08.test
   test_run "version $Package>=8.0" "$Package>=8.0" "$Disto" "version"
+  echo "odoo: 9.0">$TESTDIR/res/odoo__$Disto.08.test
+  test_run "version $Package<>10.0" "$Package<>10.0" "$Disto" "version"
+  # echo "odoo: 9.0">$TESTDIR/res/odoo__$Disto.08.test
+  test_run "version $Package!=10.0" "$Package!=10.0" "$Disto" "version"
   echo "odoo: 8.0">$TESTDIR/res/odoo__$Disto.08.test
-  test_run "version $Package<>9.0" "$Package<>9.0" "$Disto" "version"
-  # echo "odoo: 8.0">$TESTDIR/res/odoo__$Disto.08.test
-  test_run "version $Package!=9.0" "$Package!=9.0" "$Disto" "version"
-  # echo "odoo: 8.0">$TESTDIR/res/odoo__$Disto.08.test
   test_run "version $Package>7.0<9.0" "$Package>7.0<9.0" "$Disto" "version"
 
   cat <<EOF >$TESTDIR/res/odoo__$Disto.08.test
@@ -346,24 +357,9 @@ EOF
 > chmod u+rwx,g=rx,o=rx /var/run/odoo/
 > git checkout 8.0
 > cd /tmp
-> echo "l10n-italy-supplemental/">>.gitignore
-> git clone https://github.com/zeroincombenze/l10n-italy-supplemental.git l10n-italy-supplemental/ -b 8.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/l10n-italy-supplemental.git l10n-italy-supplemental/
-> cd /opt/odoo
-> cd /tmp
 > echo "account-closing/">>.gitignore
 > git clone https://github.com/zeroincombenze/account-closing.git account-closing/ -b 8.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/account-closing.git account-closing/
-> cd /opt/odoo
-> cd /tmp
-> echo "account-financial-tools/">>.gitignore
-> git clone https://github.com/zeroincombenze/account-financial-tools.git account-financial-tools/ -b 8.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/account-financial-tools.git account-financial-tools/
-> cd /opt/odoo
-> cd /tmp
-> echo "account-financial-reporting/">>.gitignore
-> git clone https://github.com/zeroincombenze/account-financial-reporting.git account-financial-reporting/ -b 8.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/account-financial-reporting.git account-financial-reporting/
 > cd /opt/odoo
 > cd /tmp
 > echo "account-invoicing/">>.gitignore
@@ -386,19 +382,24 @@ EOF
 > git submodule add -f https://github.com/zeroincombenze/knowledge.git knowledge/
 > cd /opt/odoo
 > cd /tmp
+> echo "l10n-italy/">>.gitignore
+> git clone https://github.com/zeroincombenze/l10n-italy.git l10n-italy/ -b 8.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/l10n-italy.git l10n-italy/
+> cd /opt/odoo
+> cd /tmp
 > echo "partner-contact/">>.gitignore
 > git clone https://github.com/zeroincombenze/partner-contact.git partner-contact/ -b 8.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/partner-contact.git partner-contact/
 > cd /opt/odoo
 > cd /tmp
-> echo "stock-logistics-workflow/">>.gitignore
-> git clone https://github.com/zeroincombenze/stock-logistics-workflow.git stock-logistics-workflow/ -b 8.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/stock-logistics-workflow.git stock-logistics-workflow/
+> echo "web/">>.gitignore
+> git clone https://github.com/zeroincombenze/web.git web/ -b 8.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/web.git web/
 > cd /opt/odoo
 > cd /tmp
-> echo "webkit-tools/">>.gitignore
-> git clone https://github.com/zeroincombenze/webkit-tools.git webkit-tools/ -b 8.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/webkit-tools.git webkit-tools/
+> echo "website/">>.gitignore
+> git clone https://github.com/zeroincombenze/website.git website/ -b 8.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/website.git website/
 > cd /opt/odoo
 > systemctl start odoo-server
 > chkconfig odoo-server on
@@ -421,24 +422,19 @@ EOF
 > chmod u+rwx,g=rx,o=rx /var/run/odoo/
 > git checkout 7.0
 > cd /tmp
-> echo "l10n-italy-supplemental/">>.gitignore
-> git clone https://github.com/zeroincombenze/l10n-italy-supplemental.git l10n-italy-supplemental/ -b 7.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/l10n-italy-supplemental.git l10n-italy-supplemental/
-> cd /opt/odoo
-> cd /tmp
 > echo "account-closing/">>.gitignore
 > git clone https://github.com/zeroincombenze/account-closing.git account-closing/ -b 7.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/account-closing.git account-closing/
 > cd /opt/odoo
 > cd /tmp
-> echo "account-financial-tools/">>.gitignore
-> git clone https://github.com/zeroincombenze/account-financial-tools.git account-financial-tools/ -b 7.0 --single-branch --depth=1
-> git submodule add -f https://github.com/zeroincombenze/account-financial-tools.git account-financial-tools/
-> cd /opt/odoo
-> cd /tmp
 > echo "account-financial-reporting/">>.gitignore
 > git clone https://github.com/zeroincombenze/account-financial-reporting.git account-financial-reporting/ -b 7.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/account-financial-reporting.git account-financial-reporting/
+> cd /opt/odoo
+> cd /tmp
+> echo "account-financial-tools/">>.gitignore
+> git clone https://github.com/zeroincombenze/account-financial-tools.git account-financial-tools/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/account-financial-tools.git account-financial-tools/
 > cd /opt/odoo
 > cd /tmp
 > echo "account-invoicing/">>.gitignore
@@ -456,9 +452,24 @@ EOF
 > git submodule add -f https://github.com/zeroincombenze/bank-payment.git bank-payment/
 > cd /opt/odoo
 > cd /tmp
+> echo "connector/">>.gitignore
+> git clone https://github.com/zeroincombenze/connector.git connector/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/connector.git connector/
+> cd /opt/odoo
+> cd /tmp
 > echo "knowledge/">>.gitignore
 > git clone https://github.com/zeroincombenze/knowledge.git knowledge/ -b 7.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/knowledge.git knowledge/
+> cd /opt/odoo
+> cd /tmp
+> echo "l10n-italy/">>.gitignore
+> git clone https://github.com/zeroincombenze/l10n-italy.git l10n-italy/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/l10n-italy.git l10n-italy/
+> cd /opt/odoo
+> cd /tmp
+> echo "l10n-italy-supplemental/">>.gitignore
+> git clone https://github.com/zeroincombenze/l10n-italy-supplemental.git l10n-italy-supplemental/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/l10n-italy-supplemental.git l10n-italy-supplemental/
 > cd /opt/odoo
 > cd /tmp
 > echo "partner-contact/">>.gitignore
@@ -466,14 +477,59 @@ EOF
 > git submodule add -f https://github.com/zeroincombenze/partner-contact.git partner-contact/
 > cd /opt/odoo
 > cd /tmp
+> echo "product-attribute/">>.gitignore
+> git clone https://github.com/zeroincombenze/product-attribute.git product-attribute/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/product-attribute.git product-attribute/
+> cd /opt/odoo
+> cd /tmp
+> echo "reporting-engine/">>.gitignore
+> git clone https://github.com/zeroincombenze/reporting-engine.git reporting-engine/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/reporting-engine.git reporting-engine/
+> cd /opt/odoo
+> cd /tmp
+> echo "report-print-send/">>.gitignore
+> git clone https://github.com/zeroincombenze/report-print-send.git report-print-send/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/report-print-send.git report-print-send/
+> cd /opt/odoo
+> cd /tmp
+> echo "server-tools/">>.gitignore
+> git clone https://github.com/zeroincombenze/server-tools.git server-tools/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/server-tools.git server-tools/
+> cd /opt/odoo
+> cd /tmp
+> echo "stock-logistics-barcode/">>.gitignore
+> git clone https://github.com/zeroincombenze/stock-logistics-barcode.git stock-logistics-barcode/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/stock-logistics-barcode.git stock-logistics-barcode/
+> cd /opt/odoo
+> cd /tmp
+> echo "stock-logistics-tracking/">>.gitignore
+> git clone https://github.com/zeroincombenze/stock-logistics-tracking.git stock-logistics-tracking/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/stock-logistics-tracking.git stock-logistics-tracking/
+> cd /opt/odoo
+> cd /tmp
+> echo "stock-logistics-warehouse/">>.gitignore
+> git clone https://github.com/zeroincombenze/stock-logistics-warehouse.git stock-logistics-warehouse/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/stock-logistics-warehouse.git stock-logistics-warehouse/
+> cd /opt/odoo
+> cd /tmp
 > echo "stock-logistics-workflow/">>.gitignore
 > git clone https://github.com/zeroincombenze/stock-logistics-workflow.git stock-logistics-workflow/ -b 7.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/stock-logistics-workflow.git stock-logistics-workflow/
 > cd /opt/odoo
 > cd /tmp
+> echo "web/">>.gitignore
+> git clone https://github.com/zeroincombenze/web.git web/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/web.git web/
+> cd /opt/odoo
+> cd /tmp
 > echo "webkit-tools/">>.gitignore
 > git clone https://github.com/zeroincombenze/webkit-tools.git webkit-tools/ -b 7.0 --single-branch --depth=1
 > git submodule add -f https://github.com/zeroincombenze/webkit-tools.git webkit-tools/
+> cd /opt/odoo
+> cd /tmp
+> echo "website/">>.gitignore
+> git clone https://github.com/zeroincombenze/website.git website/ -b 7.0 --single-branch --depth=1
+> git submodule add -f https://github.com/zeroincombenze/website.git website/
 > cd /opt/odoo
 > systemctl start odoo-server
 > chkconfig odoo-server on
@@ -484,13 +540,22 @@ fi
 }
 
 Z0BUG_init
-parseoptest -l$TESTDIR/test_lisa.log $@
+parseoptest -l$TESTDIR/test_lisa.log "$@"
 sts=$?
 if [ $sts -ne 127 ]; then
   exit $sts
 fi
-
-TPRODUCT="$RUNDIR/lisa -T"
-
-Z0BUG_main_file "" ""
-exit $?
+if [ ${opt_tlib:-0} -ne 0 ]; then
+  TRAVISLIBDIR=$(findpkg travisrc "$TDIR $TDIR/.. $TDIR/../travis_emulator $TDIR/../../travis_emulator . .. $HOME/dev")
+  if [ -z "$TRAVISLIBDIR" ]; then
+    echo "Library file travisrc not found!"
+    exit 2
+  fi
+  . $TRAVISLIBDIR
+fi
+UT_LIST=""
+if [ "$(type -t Z0BUG_setup)" == "function" ]; then Z0BUG_setup; fi
+Z0BUG_main_file "$UT1_LIST" "$UT_LIST"
+sts=$?
+if [ "$(type -t Z0BUG_teardown)" == "function" ]; then Z0BUG_teardown; fi
+exit $sts
