[FIX] clodoo with python3

diff --git a/lisa/odoo-server_Debian b/lisa/odoo-server_Debian
--- a/lisa/odoo-server_Debian
+++ b/lisa/odoo-server_Debian
@@ -5,8 +5,8 @@ xtl_pidfile=/var/run/${xtl_id}/${xtl_name}.pid
 xtl_logfile=/var/log/${xtl_id}/${xtl_name}.log
 xtl_cfgfile=/etc/${xtl_id}/${xtl_name}.conf
 xtl_altcfgfile=/etc/${xtl_name}.conf
-xtl_version=10
-xtl_fversion=10.0
+xtl_version=12
+xtl_fversion=12.0
 xtl_user=odoo
 xtl_test=0
 xtl_sudo=0
@@ -31,7 +31,7 @@ xtl_sudo=0
 # Short-Description:    Complete Business Application software
 # Description:          Odoo is a complete suite of business tools.
 ### END INIT INFO
-# version: 0.4.19-Debian
+# version: 0.4.21-Debian
 # Warning: this is a customized ${xtl_Id} script, running Linux
 # It was tested on: CentOS6, CentOS7, Ubuntu12, Ubuntu14, Debian7, Debian8, Debian9
 # author: Antonio M. Vigliotti - antoniomaria.vigliotti@gmail.com
@@ -88,6 +88,15 @@ xtl_org=$(echo $(basename $0)|grep -Eo "(oca|librerp|flectra|zero|powerp)"|tail 
 mult=$(echo $(basename $0)|grep -Eo "(6|7|8|9|10|11|12|13|14)")
 [[ $DRY_RUN -gt 0 ]] && echo "mult=${mult}"
 [[ $DRY_RUN -gt 0 ]] && echo "ORG=$ORG"
+[[ $DRY_RUN -gt 0 ]] && echo "CONFIGFILE=$CONFIGFILE"
+if [[ -z "$CONFIGFILE" || ! -f $CONFIGFILE ]]; then
+  CONFIGFILE="/etc/odoo/odoo"
+  [[ -n "$mult" ]] && CONFIGFILE="$CONFIGFILE${mult}"
+  [[ -n "$xtl_org" ]] && CONFIGFILE="$CONFIGFILE-${xtk_org}"
+  CONFIGFILE="$CONFIGFILE.conf"
+  echo "Configuration file not found! Search for $CONFIGFILE!"
+fi
+[[ ! -f $CONFIGFILE ]] && echo "Configuration file $CONFIGFILE not found!"
 DAEMON=""
 VENV_DIR=""
 [[ $DRY_RUN -gt 0 ]] && echo "find /usr/local/bin /usr/bin -maxdepth 1 -type f -executable -name \"${ORG}*${mult}*\" -o -name \"ODOO*${mult}*\" -o -name \"openerp*${mult}*\""
@@ -153,10 +162,9 @@ fi
 [[ $DRY_RUN -gt 0 ]] && echo "VENV_DIR=$VENV_DIR"
 NAME=${xtl_name}
 DESC="${xtl_Id} Server Daemon ($NAME)"
-# pidfile
-PIDFILE=${xtl_pidfile}
+[[ -n "$CONFIGFILE" ]] && PIDFILE=$(grep "^pidfile *=" $CONFIGFILE|awk -F= '{print $2}'|tr -d " ") || PIDFILE=${xtl_pidfile}
 LOCKFILE=/var/lock/subsys/${NAME}
-LOGFILE=${xtl_logfile}
+[[ -n "$CONFIGFILE" ]] && LOGFILE=$(grep "^logfile *=" $CONFIGFILE|awk -F= '{print $2}'|tr -d " ") || LOGFILE=${xtl_logfile}
 # Additional options that are passed to the Daemon.
 if [[ "$FH" == "Debian" ]]; then
   DAEMON_OPTS="--logfile=$LOGFILE"
@@ -168,7 +176,7 @@ if [[ -f $CONFIGFILE ]]; then
   DAEMON_OPTS="-c $CONFIGFILE $DAEMON_OPTS"
 fi
 DAEMON_OPTS="$DAEMON_OPTS $2 $3 $4 $5 $6 $7 $8 $9"
-[[ -x $DAEMON ]] || exit 0
+[[ -x $DAEMON ]] || exit 1
 RETVAL=0
 
 
@@ -271,28 +279,40 @@ check_privsep_dir() {
     local uu x
     local grp=$(id -g ${USER})
     local PIDDIR=$(dirname $PIDFILE)
-    if [[ "$PIDDIR" != "/var/run" && "$PIDDIR" != "/run" ]]; then
-      if [[ ! -d $PIDDIR ]]; then
-        mkdir $PIDDIR
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0775 $PIDDIR || chmod 0755 $PIDDIR
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER}:${grp} $PIDDIR || chown ${USER}:${USER} $PIDDIR
-      fi
+    local LOGDIR=$(dirname $LOGFILE)
+
+    [[ "$LOGDIR" != "/var/log/$USER" && ! -d $LOGDIR ]] && mkdir $LOGDIR
+    [[ ! -f "$LOGFILE" ]] && touch $LOGFILE
+    [[ ! -f "$LOGFILE" ]] && echo "Cannot create logfile $LOGFILE!" && exit 2
+    uu=$(stat -c %U $LOGDIR)
+    if [[ "$uu" != "${USER}" ]]; then
+      local x=$(date +"%Y-%m-%d %H:%M:%S,000")
+      echo "$x $$ DAEMON ? $0: Invalid $LOGDIR directory owner ($uu)! Should be $USER">>$LOGFILE
+      [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0775 $LOGDIR || chmod 0755 $LOGDIR
+      [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER}:${grp} $LOGDIR || chown ${USER}:${USER} $LOGDIR
     fi
+    uu=$(stat -c %U $LOGFILE)
+    if [[ "$uu" != "${USER}" ]]; then
+      local x=$(date +"%Y-%m-%d %H:%M:%S,000")
+      echo "$x $$ DAEMON ? $0: Invalid file $LOGFILE owner $uu! Should be $USER">>$LOGFILE
+    fi
+    [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0664 $LOGFILE || chmod 0644 $LOGFILE
+    [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER}:${grp} $LOGFILE || chown ${USER}:${USER} $LOGFILE
+
+    [[ "$PIDDIR" != "/var/run" && "$PIDDIR" != "/run" && ! -d $PIDDIR ]] && mkdir $PIDDIR
     [[ ! -f "$PIDFILE" ]] && touch $PIDFILE
-    if [[ "$PIDDIR" != "/var/run" && "$PIDDIR" != "/run" ]]; then
-      uu=$(stat -c %U $PIDDIR)
-      if [[ "$uu" != "${USER}" ]]; then
-        local x=$(date +"%Y-%m-%d %H:%M:%S,000")
-        echo "$x $$ DAEMON ? $0: Invalid pid directory owner!">>$LOGFILE
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0775 $PIDDIR || chmod 0755 $PIDDIR
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER}:${grp} $PIDDIR || chown ${USER}:${USER} $PIDDIR
-      fi
+    uu=$(stat -c %U $PIDDIR)
+    if [[ "$uu" != "${USER}" ]]; then
+      local x=$(date +"%Y-%m-%d %H:%M:%S,000")
+      echo "$x $$ DAEMON ? $0: Invalid $PIDDIR directory owner ($uu)! Should be $USER">>$LOGFILE
+      [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0775 $PIDDIR || chmod 0755 $PIDDIR
+      [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER}:${grp} $PIDDIR || chown ${USER}:${USER} $PIDDIR
     fi
     if [[ -f "$PIDFILE" ]]; then
       uu=$(stat -c %U $PIDFILE)
       if [[ "$uu" != "${USER}" ]]; then
         local x=$(date +"%Y-%m-%d %H:%M:%S,000")
-        echo "$x $$ DAEMON ? $0: Invalid pid directory owner!">>$LOGFILE
+        echo "$x $$ DAEMON ? $0: Invalid file $PIDFILE owner $uu! Should be $USER">>$LOGFILE
       fi
       [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0664 $PIDFILE || chmod 0644 $PIDFILE
       [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER}:${grp} $PIDFILE || chown ${USER}:${USER} $PIDFILE
@@ -315,7 +335,7 @@ start_RHEL () {
     fi
 
     check_privsep_dir
-    if [ $DRY_RUN -gt 0 ]; then
+    if [[ $DRY_RUN -gt 0 ]]; then
       echo "> daemon --user ${USER} --check ${NAME} \"/usr/bin/setsid ${DAEMON} ${DAEMON_OPTS} &\""
     else
       daemon --user ${USER} --check ${NAME} \
@@ -332,8 +352,8 @@ start_RHEL () {
 
 start_Debian () {
     check_privsep_dir
-    if [ -z "$USE_SUDO" ] || [ $USE_SUDO -eq 0 ]; then
-      if [ $DRY_RUN -gt 0 ]; then
+    if [[ -z "$USE_SUDO" || $USE_SUDO -eq 0 ]]; then
+      if [[ $DRY_RUN -gt 0 ]]; then
         echo "> start-stop-daemon --start --quiet --pidfile ${PIDFILE} --chuid ${USER} --background --make-pidfile --exec ${DAEMON} -- ${DAEMON_OPTS}"
       else
         start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
@@ -342,7 +362,7 @@ start_Debian () {
       fi
       RETVAL=$?
     else
-      if [ $DRY_RUN -gt 0 ]; then
+      if [[ $DRY_RUN -gt 0 ]]; then
         echo "> sudo -u ${USER} -bn ${DAEMON} ${DAEMON_OPTS}"
       else
         sudo -u ${USER} -bn ${DAEMON} ${DAEMON_OPTS}
