[FIX] Various fixes 20220904

diff --git a/lisa/odoo-server_Debian b/lisa/odoo-server_Debian
--- a/lisa/odoo-server_Debian
+++ b/lisa/odoo-server_Debian
@@ -83,9 +83,9 @@ else
   CONFIGFILE=""
 fi
 # search for execution command script
-xtl_org=$(echo $(basename $0)|grep -Eo "(oca|librerp|zero|powerp)"|tail -n1)
+xtl_org=$(echo $(basename $0)|grep --color=never -Eo "(oca|librerp|zero|powerp)"|tail -n1)
 [[ -z "$xtl_org" ]] && ORG="odoo" || ORG="$xtl_org"
-mult=$(echo $(basename $0)|grep -Eo "(6|7|8|9|10|11|12|13|14|15|16)")
+mult=$(echo $(basename $0)|grep --color=never -Eo "(6|7|8|9|10|11|12|13|14|15|16)")
 [[ $DRY_RUN -gt 0 ]] && echo "mult=${mult}"
 [[ $DRY_RUN -gt 0 ]] && echo "ORG=$ORG"
 DAEMON=""
@@ -173,7 +173,7 @@ set_lessc() {
     local f=$1
     local minv=$2
     [[ -z "$minv" ]] && minv=30000
-    local lv=$($f --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+    local lv=$($f --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
     [[ -z "$lv" ]] && lv=0
     dt=$(date +"%Y-%m-%d %H:%M:%S,000")
     if [[ $lv -ge $minv ]]; then
@@ -192,7 +192,7 @@ set_lessc() {
 
 check_lessc() {
     local d dt f x
-    local lv=$(lessc --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+    local lv=$(lessc --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
     local alt_less=
     [[ -z "$lv" ]] && lv=0
     dt=$(date +"%Y-%m-%d %H:%M:%S,000")
@@ -203,7 +203,7 @@ check_lessc() {
         if [[ -d $d ]]; then
           if [[ -x $d/less/bin/lessc ]]; then
             f=$d/less/bin/lessc
-            lv=$($f --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+            lv=$($f --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
             [[ -z "$lv" ]] && lv=0
             if [[ $lv -gt 30000 ]]; then
               set_lessc $f 30000
@@ -215,7 +215,7 @@ check_lessc() {
         fi
       done
     fi
-    lv=$(lessc --version 2>/dev/null|grep -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
+    lv=$(lessc --version 2>/dev/null|grep --color=never -Eo "[0-9.]+"|head -n1|awk -F. '{print $1*10000 + $2*100 + $3}')
     [[ -z "$lv" ]] && lv=0
     if [[ $lv -lt 20000 && -n "$alt_less" ]]; then
       set_lessc $alt_less 20000
@@ -230,9 +230,9 @@ check_lessc() {
 
 
 checkpid() {
-    [[ -f $PIDFILE ]] || return 1
-    pid=$(cat $PIDFILE)
-    [[ -d /proc/$pid ]] && return 0
+    local pid=$1
+    [[ -z $pid && -s $PIDFILE ]] && pid=$(cat $PIDFILE)
+    [[ -n $pid && -d /proc/$pid ]] && return 0
     return 1
 }
 
@@ -256,34 +256,31 @@ check_4_venv() {
 
 check_privsep_dir() {
     # Create the PrivSep empty dir if necessary
-    local uu x
+    local ur ugr uu x
     local grp=$(id -g ${USER_RUN})
     local PIDDIR=$(dirname $PIDFILE)
-    if [[ "$PIDDIR" != "/var/run" && "$PIDDIR" != "/run" ]]; then
-      if [[ ! -d $PIDDIR ]]; then
-        mkdir $PIDDIR
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0775 $PIDDIR || chmod 0755 $PIDDIR
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER_RUN}:${grp} $PIDDIR || chown ${USER_RUN}:${USER_RUN} $PIDDIR
-      fi
-    fi
-    [[ ! -f "$PIDFILE" ]] && touch $PIDFILE && chown ${USER_RUN}:${grp} $PIDFILE
+    [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && ur=${USER_RUN} || ur=root
+    [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && ugr=${USER_RUN}:${grp} || ugr=root:root
+
+    [[ "$PIDDIR" != "/var/run" && "$PIDDIR" != "/run" && ! -d $PIDDIR ]] && mkdir $PIDDIR
+    [[ ! -f "$PIDFILE" ]] && touch $PIDFILE && chown ${ugr} $PIDFILE
     if [[ "$PIDDIR" != "/var/run" && "$PIDDIR" != "/run" ]]; then
       uu=$(stat -c %U $PIDDIR)
-      if [[ "$uu" != "${USER_RUN}" ]]; then
+      if [[ ${uu} != ${ur} ]]; then
         local x=$(date +"%Y-%m-%d %H:%M:%S,000")
-        echo "$x $$ DAEMON ? $0: Invalid pid directory owner!">>$LOGFILE
+        echo "$x $$ DAEMON ? $0: Invalid pid directory owner ${uu}!">>$LOGFILE
         [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0775 $PIDDIR || chmod 0755 $PIDDIR
-        [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER_RUN}:${grp} $PIDDIR || chown ${USER_RUN}:${USER_RUN} $PIDDIR
+        chown ${ugr} $PIDDIR
       fi
     fi
     if [[ -f "$PIDFILE" ]]; then
       uu=$(stat -c %U $PIDFILE)
       if [[ "$uu" != "${USER_RUN}" ]]; then
         local x=$(date +"%Y-%m-%d %H:%M:%S,000")
-        echo "$x $$ DAEMON ? $0: Invalid pid file $PIDFILE owner $uu: expected ${USER_RUN}!">>$LOGFILE
+        echo "$x $$ DAEMON ? $0: Invalid pid file $PIDFILE owner $uu: expected ${ur}!">>$LOGFILE
       fi
       [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chmod 0664 $PIDFILE || chmod 0644 $PIDFILE
-      [[ -n "$HOSTNAME_DEV" && $HOSTNAME =~ $HOSTNAME_DEV ]] && chown ${USER_RUN}:${grp} $PIDFILE || chown ${USER_RUN}:${USER_RUN} $PIDFILE
+      chown ${ugr} $PIDFILE
     fi
 }
 
@@ -363,6 +360,13 @@ start() {
     return $RETVAL
 }
 
+stop_by_ps() {
+      echo "Error during stopping .. try to stop process ..."
+      [[ ${xtl_version} -lt 11 ]] && py=python || py=python3
+      local pid=$(ps -ef | grep "$py .*$DAEMON.*\.conf" | grep -v grep | awk '{print $2}' | head -n1)
+      [[ -n "$pid" ]] && kill $pid && echo "Killed process $pid!"
+      RETVAL=$?
+}
 
 stop_RHEL() {
     if [[ -f $PIDFILE ]]; then
@@ -373,13 +377,7 @@ stop_RHEL() {
         fi
     fi
     RETVAL=$?
-    if [[ $RETVAL -ne 0 ]]; then
-        echo "Error during stopping .. try to stop process ..."
-        [[ ${xtl_version} -lt 11 ]] && py=python || py=python3
-        local pid=$(ps -ef | grep "$py .*$DAEMON.*\.conf" | grep -v grep | awk '{print $2}')
-        [[ -z "$pid" ]] || kill $pid
-        RETVAL=$?
-    fi
+    [[ $RETVAL -ne 0 ]] && stop_by_ps
     if [[ $RETVAL -eq 0 ]]; then
         [[ $DRY_RUN -eq 0 ]] && rm -f $LOCKFILE
         # echo_success
@@ -393,7 +391,6 @@ stop_RHEL() {
         run-parts /etc/${xtl_id}/stop.d
         echo
     fi
-    # [[ $DRY_RUN -eq 0 && -f "$PIDFILE" ]] && rm -f $PIDFILE
     return $RETVAL
 }
 
@@ -405,22 +402,24 @@ stop_Debian () {
         start-stop-daemon --stop --quiet --pidfile ${PIDFILE}  --oknodo --remove-pidfile
     fi
     RETVAL=$?
-    # [[ $DRY_RUN -eq 0 && -f "$PIDFILE" ]] && rm -f $PIDFILE
+    [[ $RETVAL -ne 0 ]] && stop_by_ps
     return $RETVAL
 }
 
 
 stop() {
-    if [ "$1" != "mute" ]; then
-        echo "Stopping ${DESC}: "
-    fi
-    if [ "$FH" == "RHEL" ]; then
-        stop_RHEL
-    elif [ "$FH" == "Debian" ]; then
-        stop_Debian
+    if [[ -f $PIDFILE ]]; then
+        chown root:root $PIDFILE
+        if [ "$FH" == "RHEL" ]; then
+            stop_RHEL
+        elif [ "$FH" == "Debian" ]; then
+            stop_Debian
+        else
+            echo "Unrecognized Linux distribution"
+            exit 1
+        fi
     else
-        echo "Unrecognized Linux distribution"
-        exit 1
+        stop_by_ps
     fi
     RETVAL=$?
     local x=$(date +"%Y-%m-%d %H:%M:%S,000")
@@ -439,14 +438,16 @@ restart() {
 
 
 status() {
-    if [[ -f $PIDFILE ]] ; then
+    if [[ -s $PIDFILE ]] ; then
         checkpid $(cat $PIDFILE)
         RETVAL=$?
-        if [ $RETVAL -eq 0 ] ; then
-            echo "$NAME is running..."
-        else
-            echo "$NAME is stopped"
-        fi
+    else
+        [[ ${xtl_version} -lt 11 ]] && py=python || py=python3
+        checkpid $(ps -ef | grep "$py .*$DAEMON.*\.conf" | grep -v grep | awk '{print $2}' | head -n1)
+        RETVAL=$?
+    fi
+    if [[ $RETVAL -eq 0 ]] ; then
+        echo "$NAME is running..."
     else
         echo "$NAME is stopped"
     fi
