[IMP] Improvements

diff --git a/odoo_score/build/lib/odoo_score/run_odoo_debug b/odoo_score/build/lib/odoo_score/run_odoo_debug
--- a/odoo_score/build/lib/odoo_score/run_odoo_debug
+++ b/odoo_score/build/lib/odoo_score/run_odoo_debug
@@ -91,13 +91,13 @@ check_for_modules() {
 OPTOPTS=(h        B       b          c        C           d        e       f         k        i       I       l        L        m           M         n           o         O      p        P         q           s        T        t         U          u       V           v           w       W        x)
 OPTLONG=(help     debug   branch     conf     no-coverage database export  force     keep     import  install lang     lint-lev modules     multi     dry-run     ""        ""     path     psql-port quiet       stop     test     ""        db-user    update  version     verbose     web     ""       xmlrpc-port)
 OPTDEST=(opt_help opt_dbg opt_branch opt_conf opt_nocov   opt_db   opt_exp opt_force opt_keep opt_imp opt_xtl opt_lang opt_llvl opt_modules opt_multi opt_dry_run opt_ofile opt_ou opt_odir opt_qport opt_verbose opt_stop opt_test opt_touch opt_dbuser opt_upd opt_version opt_verbose opt_web opt_venv opt_rport)
-OPTACTI=("+"      1       "=>"       "="      1           "="      1       1         1        1       1       1        "="      "="         1         1           "="       1      "="      "="       0           1        1        1         "="        1       "*>"        "+"         1       1        "=")
+OPTACTI=("+"      1       "=>"       "=>"     1           "="      1       1         1        1       1       1        "="      "="         1         1           "="       1      "="      "="       0           1        1        1         "="        1       "*>"        "+"         1       1        "=")
 OPTDEFL=(1        0       ""         ""       0           ""       0       0         0        0       0       0        ""       ""          -1        0           ""        0      ""       ""        0           0        0        0         ""         0       ""          -1          0       0        "")
 OPTMETA=("help"   ""      "version"  "fname"  ""          "name"   ""      ""        ""       ""      ""      ""       "level"  "modules"   ""        "no op"     "file"    ""     "dir"    "port"    ""          ""       ""       "touch"   "user"     ""      "version"   "verbose"   0       ""       "port")
 OPTHELP=("this help"
     "debug mode"
     "odoo branch (version id)"
-    "configuration file"
+    "odoo configuration file"
     "use coverage to run test"
     "db name to test,translate o upgrade (require -m switch)"
     "export translation (conflict with -i -u -I)"
@@ -125,7 +125,7 @@ OPTHELP=("this help"
     "run as web server"
     "run virtualenv if avaiable"
     "set odoo xmlrpc port")
-OPTARGS=(odoo_vid)
+OPTARGS=()
 
 parseoptargs "$@"
 if [[ "$opt_version" ]]; then
@@ -137,63 +137,75 @@ if [[ $opt_help -gt 0 ]]; then
         "(C) 2015-2022 by zeroincombenze(R)\nhttps://zeroincombenze-tools.readthedocs.io/\nAuthor: antoniomaria.vigliotti@gmail.com"
     exit 0
 fi
-[[ -n "$opt_branch" && -z "$odoo_vid" ]] && odoo_vid=$opt_branch
+
 discover_multi
-odoo_fver=$(build_odoo_param FULLVER $odoo_vid)
-odoo_ver=$(build_odoo_param MAJVER $odoo_fver)
-[[ -n "$opt_odir" ]] && odoo_root=$($READLINK -f $opt_odir) || odoo_root=$(build_odoo_param ROOT $odoo_vid search)
-[[ -n "$opt_conf" ]] && CONFN=$opt_conf || CONFN=$(build_odoo_param CONFN $odoo_vid search)
-LCONFN=$(build_odoo_param LCONFN $odoo_vid)
-script=$(build_odoo_param BIN $odoo_root search)
-if [[ -z "$script" ]]; then
-    echo "! No odoo script found!!"
-    exit 1
+CONFN=""
+opaths=""
+odoo_root=""
+odoo_fver=""
+if [[ -n $opt_conf ]]; then
+    CONFN=$opt_conf
+    [[ ! -f $CONFN ]] && echo "File $CONFN not found!" && exit 1
+    opaths="$(grep ^addons_path $CONFN | awk -F= '{print $2}')"
+    [[ -z $opaths ]] && echo "No path list found in $CONFN!" && exit 1
+    for p in ${opaths//,/ }; do
+        [[ -x $p/../odoo-bin || -x $p/../openerp-server ]] && odoo_root=$(readlink -f $p/..) && break
+    done
+    [[ -n $odoo_root ]] && odoo_fver=$(build_odoo_param FULLVER $odoo_root)
+    [[ -n $opt_branch ]] && x=$(build_odoo_param FULLVER $odoo_fver) || x=$odoo_fver
+    [[ $odoo_fver != $x ]] && echo "Version mismatch -b $opt_branch <> -c $opt_conf" && exit 1
+    [[ -n $opt_odir && $opt_odir != $odoo_root ]] && echo "Path mismatch $odoo_root (-c $opt_conf) <> -p $opt_odir" && exit 1
+elif [[ -n $opt_branch ]]; then
+    odoo_fver=$(build_odoo_param FULLVER $opt_branch)
+    [[ -n "$opt_odir" ]] && odoo_root=$($READLINK -f $opt_odir) || odoo_root=$(build_odoo_param ROOT $opt_branch search)
+    CONFN=$(build_odoo_param CONFN $odoo_fver search)
+    [[ -f $CONFN ]] && opaths="$(grep ^addons_path $CONFN | awk -F= '{print $2}')"
 fi
+# [[ -z $CONFN || ! -f $CONFN ]] &&  && echo "Configuration file $CONFN not found!" && exit 1
+[[ -z $odoo_root || ! -d $odoo_root ]] && echo "Odoo path $odoo_root not found!" && exit 1
+odoo_ver=$(build_odoo_param MAJVER $odoo_fver)
+LCONFN=$(build_odoo_param LCONFN $odoo_fver)
+script=$(build_odoo_param BIN $odoo_root search)
+[[ -z "$script" ]] && echo "No odoo script found!!" && exit 1
 ODOO_RUNDIR=$(dirname $script)
 VDIR=$(build_odoo_param VDIR $odoo_root)
-GIT_ORGNM=$(build_odoo_param GIT_ORGNM $odoo_root)
-manifest=$(build_odoo_param MANIFEST $odoo_vid)
 [[ $opt_verbose -gt 0 && -n "$VDIR" ]] && echo "# Found $VDIR virtual directory"
+GIT_ORGNM=$(build_odoo_param GIT_ORGNM $odoo_root)
+manifest=$(build_odoo_param MANIFEST $odoo_fver)
+if [[ -n $opt_rport ]]; then
+    RPCPORT=$opt_rport
+elif [[ -z $opt_conf && $opt_web -ne 0 ]]; then
+    RPCPORT=$(build_odoo_param RPCPORT $odoo_fver $GIT_ORGNM)
+elif [[ -z $opt_conf && $opt_test -ne 0 ]]; then
+    RPCPORT=$(build_odoo_param RPCPORT $odoo_fver DEBUG)
+elif [[ -z $opt_conf || ! -f $CONFN ]]; then
+    RPCPORT=$(build_odoo_param RPCPORT $odoo_fver)
+elif [[ -f $CONFN ]]; then
+    RPCPORT=$(grep ^xmlrpc_port $CONFN | awk -F= '{print $2}' | tr -d " ")
+    [[ -z "$RPCPORT" ]] && RPCPORT=$(grep ^http_port $CONFN | awk -F= '{print $2}' | tr -d " ")
+else
+    RPCPORT=$(build_odoo_param RPCPORT $odoo_fver)
+fi
+[[ -z "$RPCPORT" || $RPCPORT -eq 0 ]] && RPCPORT=$(build_odoo_param RPCPORT $odoo_fver)
+if [[ -n $opt_dbuser ]]; then
+    DB_USER=$opt_dbuser
+elif [[ -z $opt_conf || ! -f $CONFN ]]; then
+    DB_USER=$(build_odoo_param DB_USER $odoo_fver $GIT_ORGNM)
+elif [[ -f $CONFN ]]; then
+    DB_USER=$(grep ^db_user $CONFN | awk -F= '{print $2}' | tr -d " ")
+else
+    DB_USER=$(build_odoo_param DB_USER $odoo_fver)
+fi
+if [[ -n "$opt_qport" ]]; then
+    DB_PORT=$opt_qport
+elif [[ -f $CONFN ]]; then
+    DB_PORT=$(grep ^db_port $CONFN | awk -F= '{print $2}' | tr -d " ")
+    [[ $DB_PORT == "False" ]] && unset DB_PORT
+fi
 
 create_db=0
 drop_db=0
 depmods=""
-
-if [[ -n "$opt_rport" ]]; then
-    RPCPORT=$opt_rport
-elif [[ -n "$CONFN" && $opt_test -eq 0 && $opt_force -eq 0 && $opt_web -eq 0 ]]; then
-    RPCPORT=$(grep ^xmlrpc_port $CONFN | awk -F= '{print $2}' | tr -d " ")
-    [[ -z "$RPCPORT" ]] && RPCPORT=$(grep ^http_port $CONFN | awk -F= '{print $2}' | tr -d " ")
-fi
-if [[ -z "$RPCPORT" ]]; then
-    if [[ $opt_web -ne 0 ]]; then
-        RPCPORT=$(build_odoo_param RPCPORT $odoo_vid $GIT_ORGNM)
-    elif [[ $opt_test -ne 0 ]]; then
-        RPCPORT=$(build_odoo_param RPCPORT $odoo_vid DEBUG)
-    else
-        RPCPORT=$(build_odoo_param RPCPORT $odoo_vid)
-    fi
-fi
-
-if [[ -n "$opt_dbuser" ]]; then
-    DB_USER=$opt_dbuser
-elif [[ -n "$CONFN" && $opt_force -eq 0 ]]; then
-    DB_USER=$(grep ^db_user $CONFN | awk -F= '{print $2}' | tr -d " ")
-fi
-if [[ -z "$DB_USER" ]]; then
-    if [[ $opt_web -ne 0 ]]; then
-        DB_USER=$(build_odoo_param DB_USER $odoo_vid $GIT_ORGNM)
-    else
-        DB_USER=$(build_odoo_param DB_USER $odoo_vid DEBUG)
-    fi
-fi
-
-if [[ -n "$opt_qport" ]]; then
-    DB_PORT=$opt_qport
-elif [[ -n "$CONFN" && $opt_force -eq 0 ]]; then
-    DB_PORT=$(grep ^db_port $CONFN | awk -F= '{print $2}' | tr -d " ")
-    [[ $DB_PORT == "False" ]] && unset DB_PORT
-fi
 
 if [[ $opt_test -ne 0 ]]; then
     opt_web=0
@@ -210,51 +222,32 @@ elif [[ $opt_lang -ne 0 ]]; then
 elif [[ $opt_exp -ne 0 || $opt_imp -ne 0 ]]; then
     opt_keep=1
     opt_stop=1
-    if [[ -z "$opt_modules" ]]; then
-        echo "! Missing -m switch!!"
-        exit 1
-    fi
-    if [[ -z "$opt_db" ]]; then
-        echo "! Missing -d switch !!"
-        exit 1
-    fi
+    [[ -z "$opt_modules" ]] && echo "Missing -m switch!!" && exit 1
+    [[ -z "$opt_db" ]] && echo "Missing -d switch !!" && exit 1
 elif [[ $opt_upd -ne 0 ]]; then
     opt_keep=1
-    if [[ -z "$opt_modules" ]]; then
-        echo "! Missing -m switch !!"
-        exit 1
-    fi
-    if [[ -z "$opt_db" ]]; then
-        echo "! Missing -d switch!!"
-        exit 1
-    fi
+    [[ -z "$opt_modules" ]] && echo "Missing -m switch!!" && exit 1
+    [[ -z "$opt_db" ]] && echo "Missing -d switch !!" && exit 1
 elif [[ $opt_xtl -ne 0 ]]; then
-    if [[ -z "$opt_modules" ]]; then
-        echo "Missing -m switch"
-        exit 1
-    fi
-    if [[ -z "$opt_db" ]]; then
-        echo "Missing -d switch"
-        exit 1
-    fi
+    [[ -z "$opt_modules" ]] && echo "Missing -m switch!!" && exit 1
+    [[ -z "$opt_db" ]] && echo "Missing -d switch !!" && exit 1
 fi
 
 if [[ -n "$opt_modules" ]]; then
     if [[ $create_db -ne 0 ]]; then
-        PL="$(grep ^addons_path $CONFN | awk -F= '{print $2}')"
-        [[ -z $PL ]] && echo "No path list found in $CONFN!" && exit 1
+        [[ -z $opaths ]] && echo "No path list found in $CONFN!" && exit 1
         if [[ -z "$($which odoo_dependencies.py 2>/dev/null)" ]]; then
             echo "Test incomplete!"
             echo "File odoo_dependencies.py not found!"
         else
             if [[ "$opt_modules" == "all" ]]; then
-                depmods=$(odoo_dependencies.py -RA mod $PL)
+                depmods=$(odoo_dependencies.py -RA mod $opaths)
             else
-                depmods=$(odoo_dependencies.py -RA mod $PL -PM $opt_modules)
+                depmods=$(odoo_dependencies.py -RA mod $opaths -PM $opt_modules)
             fi
             [[ -z "$depmods" ]] && echo "Modules $opt_modules not found!" && exit 1
             if [[ "$opt_modules" != "all" ]]; then
-                depmods=$(odoo_dependencies.py -RA dep $PL -PM $opt_modules)
+                depmods=$(odoo_dependencies.py -RA dep $opaths -PM $opt_modules)
             fi
             if [[ -n "$depmods" && $opt_test -eq 0 ]]; then
                 opt_modules="$opt_modules,$depmods"
@@ -271,29 +264,17 @@ if [[ -n "$opt_modules" ]]; then
         if [[ $opt_exp -ne 0 && -n "$opt_ofile" ]]; then
             src=$($READLINK -f $opt_ofile)
             OPTS="--modules=$opt_modules --i18n-export=$src -lit_IT"
-        elif [ $opt_exp -ne 0 -o $opt_imp -ne 0 ]; then
-            srcs=$(find -L $odoo_root -not -path '*/__to_remove/*' -type d -name "$opt_modules")
-            f=0
-            for src in $srcs; do
-                if [[ -n "$src" ]]; then
-                    if [[ -f $src/i18n/it.po ]]; then
-                        src=$src/i18n/it.po
-                        [[ $opt_exp -ne 0 ]] && run_traced "cp $src $src.bak"
-                        f=1
-                        break
-                    else
-                        alt=$(find -L $src/i18n -name '*.po' | head -n1)
-                        src=
-                        [[ -n "$alt" ]] && fi=1 && break
-                    fi
-                fi
-            done
-            if [[ $f -eq 0 ]]; then
-                echo "! Translation file not found!!"
-                [[ -n "$alt" ]] && echo ".. may be $alt ?"
+        elif [[ $opt_exp -ne 0 || $opt_imp -ne 0 ]]; then
+            [[ -z $opaths ]] && echo "No path list found in $CONFN!" && exit 1
+            src=$(find ${opaths//,/ } -type d -name $opt_modules 2>/dev/null)
+            if [[ -z $src ]]; then
+                echo "Translation file not found!!"
                 exit 1
             fi
             src=$($READLINK -f $src)
+            [[ ! -d $src/i18n ]] && echo "Non directory $src/i18n found!!" && exit 1
+            src="$src/1i8n/it.po"
+            makepo_it.py -f -b$odoo_fver -m$opt_modules $src
             if [[ $opt_imp -ne 0 ]]; then
                 OPTS="--modules=$opt_modules --i18n-import=$src -lit_IT --i18n-overwrite"
             else
@@ -301,7 +282,7 @@ if [[ -n "$opt_modules" ]]; then
             fi
         elif [[ $opt_upd -ne 0 && $opt_xtl -ne 0 ]]; then
             OPTS="$OPTSIU"
-            [ $opt_test -ne 0 ] && OPTS="$OPTS --test-enable"
+            [[ $opt_test -ne 0 ]] && OPTS="$OPTS --test-enable"
         elif [[ $opt_upd -ne 0 ]]; then
             OPTS="$OPTU"
             [[ $opt_test -ne 0 ]] && OPTS="$OPTS --test-enable"
@@ -309,7 +290,7 @@ if [[ -n "$opt_modules" ]]; then
             [[ -z $OPTU ]] && echo "No module found to update" && exit 1
         elif [[ $opt_xtl -ne 0 ]]; then
             OPTS="$OPTI"
-            [ $opt_test -ne 0 ] && OPTS="$OPTS --test-enable"
+            [[ $opt_test -ne 0 ]] && OPTS="$OPTS --test-enable"
             [[ -n $OPTU && $opt_verbose -ne 0 ]] && echo -e "Warning: some modules must be updated\n$OPTU"
             [[ -z $OPTI ]] && echo "No module found to install" && exit 1
         else
@@ -396,10 +377,7 @@ if [[ $opt_touch -eq 0 ]]; then
         run_traced_debug "sed -e \"s|^limit_time_cpu *=.*|limit_time_cpu = 0|\" -i $FULL_LCONFN"
         run_traced_debug "sed -e \"s|^limit_time_real *=.*|limit_time_real = 0|\" -i $FULL_LCONFN"
     fi
-    if [[ -z "$RPCPORT" || "$RPCPORT" == "0" ]]; then
-        run_traced_debug "sed -e \"s|^xmlrpc_port *=.*|xmlrpc_port = False|\" -i $FULL_LCONFN"
-        OPT_CONF="$OPT_CONF --no-xmlrpc"
-    elif [[ $(grep -E "^xmlrpc_port *=" $FULL_LCONFN) || $odoo_ver -lt 10 ]]; then
+    if [[ $odoo_ver -le 10 ]]; then
         run_traced_debug "sed -e \"s|^xmlrpc_port *=.*|xmlrpc_port = $RPCPORT|\" -i $FULL_LCONFN"
         OPT_CONF="$OPT_CONF --xmlrpc-port=$RPCPORT"
     else
@@ -422,9 +400,9 @@ if [[ $opt_touch -eq 0 ]]; then
             run_traced "cd $ODOO_RUNDIR; $script $OPTDB $OPT_CONF --log-level=error"
         fi
     fi
-    if [ $odoo_ver -lt 10 -a $opt_dry_run -eq 0 -a $opt_exp -eq 0 -a $opt_imp -eq 0 -a $opt_lang -eq 0 ]; then
-        OPTS="--debug $OPTS"
-    fi
+    # if [[ $odoo_ver -lt 10 && $opt_dry_run -eq 0 && $opt_exp -eq 0 && $opt_imp -eq 0 && $opt_lang -eq 0 ]]; then
+    #     OPTS="--debug $OPTS"
+    # fi
 
     if [[ -n $COVERAGE_RCFILE ]]; then
       v=$(coverage --version|grep -Eo "[0-9]+"|head -n1)
@@ -445,7 +423,7 @@ if [[ $opt_touch -eq 0 ]]; then
         fi
     fi
     if [ $opt_exp -ne 0 ]; then
-        makepo_it.py -b$odoo_vid -m$opt_modules $src
+        makepo_it.py -b$odoo_fver -m$opt_modules $src
         echo "# Translation exported to '$src' file"
     elif [ $opt_imp -ne 0 ]; then
         echo "# Translation imported from '$src' file"
